// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct AppUpdateStrings {
    let pageTitle: String
    let hubDescription: String
    let caption: String
    let panelCaption: String
    let checkNow: String
    let checking: String
    let lastCheckFormat: String
    let neverChecked: String
    let upToDate: String
    let partialUpToDate: String
    let coverageNote: String
    let selectAll: String
    let clearSelection: String
    let updateSelectedFormat: String
    let updateOne: String
    let openAppStore: String
    let appStoreBadge: String
    let storeHint: String
    let frequencyLabel: String
    let frequencyOff: String
    let frequencyDaily: String
    let frequencyWeekly: String
    let nextCheckFormat: String
    let notifyToggle: String
    let includeStoreToggle: String
    let includeStoreCaption: String
    let packageMissing: String
    let notificationBodyFormat: String
    /// Used when exactly one app is waiting, so the note never reads "1 apps".
    let notificationBodyOne: String
    let showInPanel: String
    let homebrewBadge: String
    let sourcesTitle: String
    let includeHomebrewToggle: String
    let onlineBadge: String
    let openApp: String
    let openAppHint: String
    let includeOnlineToggle: String
    let includeOnlineCaption: String
    let incompleteCheck: String
    let onlineUnavailable: String
}

extension FeatureStrings {
    static func appUpdates(_ language: AppLanguage) -> AppUpdateStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension AppUpdateStrings {
    static let enUS = AppUpdateStrings(
        pageTitle: "App updates",
        hubDescription: "Find and install updates for the apps you have",
        caption: "Looks for newer versions of the apps on this Mac and helps you finish each update from its original source.",
        panelCaption: "See which apps have a newer version",
        checkNow: "Check now",
        checking: "Checking",
        lastCheckFormat: "Last checked %@",
        neverChecked: "Not checked yet",
        upToDate: "No updates found",
        partialUpToDate: "No updates found in this partial check",
        coverageNote: "Checks the original sources of installed apps and a public catalog. Updates install through their original source.",
        selectAll: "Select all",
        clearSelection: "Clear",
        updateSelectedFormat: "Update %d",
        updateOne: "Update",
        openAppStore: "Open the App Store",
        appStoreBadge: "App Store",
        storeHint: "Opens the App Store, where this update is installed",
        frequencyLabel: "Check in the background",
        frequencyOff: "Off",
        frequencyDaily: "Every day",
        frequencyWeekly: "Every week",
        nextCheckFormat: "Next check %@",
        notifyToggle: "Tell me when an app has an update",
        includeStoreToggle: "Include apps from the App Store",
        includeStoreCaption: "Checks store versions using this Mac’s region. Apple installs these updates.",
        packageMissing: "Homebrew is not installed, so apps cannot be updated from here yet.",
        notificationBodyFormat: "%@ apps have a newer version.",
        notificationBodyOne: "One app has a newer version.",
        showInPanel: "Show in panel",
        homebrewBadge: "Homebrew",
        sourcesTitle: "Sources",
        includeHomebrewToggle: "Include Homebrew apps",
        onlineBadge: "Online",
        openApp: "Open",
        openAppHint: "Opens the app so its own updater can finish",
        includeOnlineToggle: "Include other installed apps",
        includeOnlineCaption: "Checks directly with app developers when supported, then uses a public catalog. The app’s own updater installs the update.",
        incompleteCheck: "Check incomplete",
        onlineUnavailable: "The online check could not be completed. Other results are still shown."
    )

    static let ptBR = AppUpdateStrings(
        pageTitle: "Atualizações de apps",
        hubDescription: "Encontre e instale atualizações dos seus apps",
        caption: "Procura versões novas dos apps deste Mac e ajuda você a concluir cada atualização pela origem do app.",
        panelCaption: "Veja quais apps têm versão nova",
        checkNow: "Verificar agora",
        checking: "Verificando",
        lastCheckFormat: "Última verificação %@",
        neverChecked: "Ainda não verificado",
        upToDate: "Nenhuma atualização encontrada",
        partialUpToDate: "Nenhuma atualização encontrada nesta verificação parcial",
        coverageNote: "Verifica as fontes originais dos apps instalados e um catálogo público. Cada atualização é instalada pela fonte original.",
        selectAll: "Selecionar tudo",
        clearSelection: "Limpar",
        updateSelectedFormat: "Atualizar %d",
        updateOne: "Atualizar",
        openAppStore: "Abrir a App Store",
        appStoreBadge: "App Store",
        storeHint: "Abre a App Store, onde essa atualização é instalada",
        frequencyLabel: "Verificar em segundo plano",
        frequencyOff: "Desligado",
        frequencyDaily: "Todo dia",
        frequencyWeekly: "Toda semana",
        nextCheckFormat: "Próxima verificação %@",
        notifyToggle: "Avisar quando um app tiver atualização",
        includeStoreToggle: "Incluir apps da App Store",
        includeStoreCaption: "Consulta as versões da loja usando a região deste Mac. A Apple instala essas atualizações.",
        packageMissing: "O Homebrew não está instalado, então ainda não dá para atualizar apps por aqui.",
        notificationBodyFormat: "%@ apps têm versão nova.",
        notificationBodyOne: "Um app tem versão nova.",
        showInPanel: "Mostrar no painel",
        homebrewBadge: "Homebrew",
        sourcesTitle: "Fontes",
        includeHomebrewToggle: "Incluir apps do Homebrew",
        onlineBadge: "Online",
        openApp: "Abrir",
        openAppHint: "Abre o app para que o atualizador dele conclua",
        includeOnlineToggle: "Incluir outros apps instalados",
        includeOnlineCaption: "Consulta diretamente os desenvolvedores quando possível e usa um catálogo público como complemento. O próprio app instala a atualização.",
        incompleteCheck: "Verificação incompleta",
        onlineUnavailable: "A verificação online não pôde ser concluída. Os demais resultados continuam visíveis."
    )

    static let tr = AppUpdateStrings(
        pageTitle: "Uygulama güncellemeleri",
        hubDescription: "Uygulamalarının güncellemelerini bul ve kur",
        caption: "Bu Mac’teki uygulamaların yeni sürümlerini arar ve her güncellemeyi kendi kaynağında tamamlamana yardımcı olur.",
        panelCaption: "Hangi uygulamaların yeni sürümü olduğunu gör",
        checkNow: "Şimdi denetle",
        checking: "Denetleniyor",
        lastCheckFormat: "Son denetleme %@",
        neverChecked: "Henüz denetlenmedi",
        upToDate: "Güncelleme bulunamadı",
        partialUpToDate: "Bu kısmi denetimde güncelleme bulunamadı",
        coverageNote: "Yüklü uygulamaların özgün kaynaklarını ve herkese açık bir kataloğu denetler. Güncellemeler özgün kaynaklarından yüklenir.",
        selectAll: "Tümünü seç",
        clearSelection: "Temizle",
        updateSelectedFormat: "%d güncelle",
        updateOne: "Güncelle",
        openAppStore: "App Store’u aç",
        appStoreBadge: "App Store",
        storeHint: "Bu güncellemenin kurulduğu App Store’u açar",
        frequencyLabel: "Arka planda denetle",
        frequencyOff: "Kapalı",
        frequencyDaily: "Her gün",
        frequencyWeekly: "Her hafta",
        nextCheckFormat: "Sonraki denetleme %@",
        notifyToggle: "Bir uygulamanın güncellemesi olduğunda haber ver",
        includeStoreToggle: "App Store uygulamalarını da kat",
        includeStoreCaption: "Bu Mac’in bölgesini kullanarak mağazadaki sürümleri denetler. Bu güncellemeleri Apple yükler.",
        packageMissing: "Homebrew kurulu değil, bu yüzden uygulamalar buradan henüz güncellenemiyor.",
        notificationBodyFormat: "%@ uygulamanın yeni sürümü var.",
        notificationBodyOne: "Bir uygulamanın yeni sürümü var.",
        showInPanel: "Panelde göster",
        homebrewBadge: "Homebrew",
        sourcesTitle: "Kaynaklar",
        includeHomebrewToggle: "Homebrew uygulamalarını dahil et",
        onlineBadge: "Çevrimiçi",
        openApp: "Aç",
        openAppHint: "Kendi güncelleyicisinin tamamlaması için uygulamayı açar",
        includeOnlineToggle: "Yüklü diğer uygulamaları dahil et",
        includeOnlineCaption: "Desteklendiğinde doğrudan uygulama geliştiricilerine danışır, ardından herkese açık bir katalog kullanır. Güncellemeyi uygulamanın kendisi yükler.",
        incompleteCheck: "Denetim tamamlanamadı",
        onlineUnavailable: "Çevrimiçi denetleme tamamlanamadı. Diğer sonuçlar gösterilmeye devam ediyor."
    )

    static let ru = AppUpdateStrings(
        pageTitle: "Обновления приложений",
        hubDescription: "Находите и устанавливайте обновления ваших приложений",
        caption: "Ищет новые версии приложений на этом Mac и помогает завершить каждое обновление из его исходного источника.",
        panelCaption: "Посмотрите, у каких приложений есть новая версия",
        checkNow: "Проверить сейчас",
        checking: "Проверка",
        lastCheckFormat: "Последняя проверка %@",
        neverChecked: "Ещё не проверялось",
        upToDate: "Обновления не найдены",
        partialUpToDate: "При частичной проверке обновления не найдены",
        coverageNote: "Проверяет исходные источники установленных приложений и общедоступный каталог. Обновления устанавливаются из исходного источника.",
        selectAll: "Выбрать все",
        clearSelection: "Снять выбор",
        updateSelectedFormat: "Обновить: %d",
        updateOne: "Обновить",
        openAppStore: "Открыть App Store",
        appStoreBadge: "App Store",
        storeHint: "Открывает App Store, где устанавливается это обновление",
        frequencyLabel: "Проверять в фоне",
        frequencyOff: "Выключено",
        frequencyDaily: "Каждый день",
        frequencyWeekly: "Каждую неделю",
        nextCheckFormat: "Следующая проверка %@",
        notifyToggle: "Сообщать, когда у приложения есть обновление",
        includeStoreToggle: "Включать приложения из App Store",
        includeStoreCaption: "Проверяет версии в магазине с учётом региона этого Mac. Эти обновления устанавливает Apple.",
        packageMissing: "Homebrew не установлен, поэтому обновлять приложения отсюда пока нельзя.",
        notificationBodyFormat: "Приложений с новой версией: %@.",
        notificationBodyOne: "У одного приложения есть новая версия.",
        showInPanel: "Показывать в панели",
        homebrewBadge: "Homebrew",
        sourcesTitle: "Источники",
        includeHomebrewToggle: "Включать приложения Homebrew",
        onlineBadge: "Онлайн",
        openApp: "Открыть",
        openAppHint: "Открывает приложение, чтобы его средство обновления завершило работу",
        includeOnlineToggle: "Включать другие установленные приложения",
        includeOnlineCaption: "По возможности проверяет обновления напрямую у разработчиков, затем использует общедоступный каталог. Обновление устанавливает само приложение.",
        incompleteCheck: "Проверка не завершена",
        onlineUnavailable: "Онлайн-проверку не удалось завершить. Остальные результаты по-прежнему показаны."
    )

    static let es = AppUpdateStrings(
        pageTitle: "Actualizaciones de apps",
        hubDescription: "Encuentra e instala actualizaciones de tus apps",
        caption: "Busca versiones más nuevas de las apps de este Mac y te ayuda a completar cada actualización desde su origen.",
        panelCaption: "Mira qué apps tienen una versión más nueva",
        checkNow: "Buscar ahora",
        checking: "Buscando",
        lastCheckFormat: "Última búsqueda %@",
        neverChecked: "Todavía sin buscar",
        upToDate: "No se encontraron actualizaciones",
        partialUpToDate: "No se encontraron actualizaciones en esta revisión parcial",
        coverageNote: "Revisa las fuentes originales de las apps instaladas y un catálogo público. Cada actualización se instala desde su fuente original.",
        selectAll: "Seleccionar todo",
        clearSelection: "Limpiar",
        updateSelectedFormat: "Actualizar %d",
        updateOne: "Actualizar",
        openAppStore: "Abrir la App Store",
        appStoreBadge: "App Store",
        storeHint: "Abre la App Store, donde se instala esta actualización",
        frequencyLabel: "Buscar en segundo plano",
        frequencyOff: "Desactivado",
        frequencyDaily: "Cada día",
        frequencyWeekly: "Cada semana",
        nextCheckFormat: "Próxima búsqueda %@",
        notifyToggle: "Avisarme cuando una app tenga actualización",
        includeStoreToggle: "Incluir apps de la App Store",
        includeStoreCaption: "Consulta las versiones de la tienda usando la región de este Mac. Apple instala estas actualizaciones.",
        packageMissing: "Homebrew no está instalado, así que todavía no se pueden actualizar apps desde aquí.",
        notificationBodyFormat: "%@ apps tienen una versión más nueva.",
        notificationBodyOne: "Una app tiene una versión más nueva.",
        showInPanel: "Mostrar en el panel",
        homebrewBadge: "Homebrew",
        sourcesTitle: "Fuentes",
        includeHomebrewToggle: "Incluir apps de Homebrew",
        onlineBadge: "En línea",
        openApp: "Abrir",
        openAppHint: "Abre la app para que su propio actualizador pueda terminar",
        includeOnlineToggle: "Incluir otras apps instaladas",
        includeOnlineCaption: "Consulta directamente a los desarrolladores cuando es posible y complementa la búsqueda con un catálogo público. La propia app instala la actualización.",
        incompleteCheck: "Revisión incompleta",
        onlineUnavailable: "No se pudo completar la revisión en línea. Los demás resultados siguen visibles."
    )

    static let de = AppUpdateStrings(
        pageTitle: "App-Updates",
        hubDescription: "Updates für deine Apps finden und installieren",
        caption: "Sucht nach neueren Versionen der Apps auf diesem Mac und hilft dir, jedes Update über seine ursprüngliche Quelle abzuschließen.",
        panelCaption: "Sieh, welche Apps eine neuere Version haben",
        checkNow: "Jetzt prüfen",
        checking: "Wird geprüft",
        lastCheckFormat: "Zuletzt geprüft %@",
        neverChecked: "Noch nicht geprüft",
        upToDate: "Keine Updates gefunden",
        partialUpToDate: "Bei dieser teilweisen Prüfung wurden keine Updates gefunden",
        coverageNote: "Prüft die ursprünglichen Quellen installierter Apps und einen öffentlichen Katalog. Updates werden über die ursprüngliche Quelle installiert.",
        selectAll: "Alle auswählen",
        clearSelection: "Aufheben",
        updateSelectedFormat: "%d aktualisieren",
        updateOne: "Aktualisieren",
        openAppStore: "App Store öffnen",
        appStoreBadge: "App Store",
        storeHint: "Öffnet den App Store, wo dieses Update installiert wird",
        frequencyLabel: "Im Hintergrund prüfen",
        frequencyOff: "Aus",
        frequencyDaily: "Jeden Tag",
        frequencyWeekly: "Jede Woche",
        nextCheckFormat: "Nächste Prüfung %@",
        notifyToggle: "Bescheid geben, wenn eine App ein Update hat",
        includeStoreToggle: "Apps aus dem App Store einbeziehen",
        includeStoreCaption: "Prüft die Versionen im Store für die Region dieses Mac. Apple installiert diese Updates.",
        packageMissing: "Homebrew ist nicht installiert, deshalb lassen sich Apps von hier noch nicht aktualisieren.",
        notificationBodyFormat: "%@ Apps haben eine neuere Version.",
        notificationBodyOne: "Eine App hat eine neuere Version.",
        showInPanel: "Im Panel anzeigen",
        homebrewBadge: "Homebrew",
        sourcesTitle: "Quellen",
        includeHomebrewToggle: "Homebrew-Apps einbeziehen",
        onlineBadge: "Online",
        openApp: "Öffnen",
        openAppHint: "Öffnet die App, damit ihr eigener Updater abschließen kann",
        includeOnlineToggle: "Andere installierte Apps einbeziehen",
        includeOnlineCaption: "Prüft nach Möglichkeit direkt bei den Entwicklern und ergänzt die Suche mit einem öffentlichen Katalog. Die App selbst installiert das Update.",
        incompleteCheck: "Prüfung unvollständig",
        onlineUnavailable: "Die Online-Prüfung konnte nicht abgeschlossen werden. Andere Ergebnisse werden weiterhin angezeigt."
    )

    static let fr = AppUpdateStrings(
        pageTitle: "Mises à jour des apps",
        hubDescription: "Trouvez et installez les mises à jour de vos apps",
        caption: "Cherche des versions plus récentes des apps de ce Mac et vous aide à terminer chaque mise à jour depuis sa source d’origine.",
        panelCaption: "Voyez quelles apps ont une version plus récente",
        checkNow: "Vérifier maintenant",
        checking: "Vérification",
        lastCheckFormat: "Dernière vérification %@",
        neverChecked: "Pas encore vérifié",
        upToDate: "Aucune mise à jour trouvée",
        partialUpToDate: "Aucune mise à jour trouvée lors de cette vérification partielle",
        coverageNote: "Vérifie les sources d’origine des apps installées et un catalogue public. Les mises à jour s’installent depuis leur source d’origine.",
        selectAll: "Tout sélectionner",
        clearSelection: "Effacer",
        updateSelectedFormat: "Mettre à jour %d",
        updateOne: "Mettre à jour",
        openAppStore: "Ouvrir l’App Store",
        appStoreBadge: "App Store",
        storeHint: "Ouvre l’App Store, où cette mise à jour s’installe",
        frequencyLabel: "Vérifier en arrière-plan",
        frequencyOff: "Désactivé",
        frequencyDaily: "Chaque jour",
        frequencyWeekly: "Chaque semaine",
        nextCheckFormat: "Prochaine vérification %@",
        notifyToggle: "Me prévenir quand une app a une mise à jour",
        includeStoreToggle: "Inclure les apps de l’App Store",
        includeStoreCaption: "Vérifie les versions du magasin pour la région de ce Mac. Apple installe ces mises à jour.",
        packageMissing: "Homebrew n’est pas installé, les apps ne peuvent donc pas encore être mises à jour d’ici.",
        notificationBodyFormat: "%@ apps ont une version plus récente.",
        notificationBodyOne: "Une app a une version plus récente.",
        showInPanel: "Afficher dans le panneau",
        homebrewBadge: "Homebrew",
        sourcesTitle: "Sources",
        includeHomebrewToggle: "Inclure les apps Homebrew",
        onlineBadge: "En ligne",
        openApp: "Ouvrir",
        openAppHint: "Ouvre l’app pour permettre à son propre outil de mise à jour de terminer",
        includeOnlineToggle: "Inclure les autres apps installées",
        includeOnlineCaption: "Consulte directement les développeurs lorsque c’est possible, puis complète la recherche avec un catalogue public. L’app installe elle-même la mise à jour.",
        incompleteCheck: "Vérification incomplète",
        onlineUnavailable: "La vérification en ligne n’a pas pu aboutir. Les autres résultats restent affichés."
    )

    static let it = AppUpdateStrings(
        pageTitle: "Aggiornamenti delle app",
        hubDescription: "Trova e installa gli aggiornamenti delle tue app",
        caption: "Cerca versioni più recenti delle app di questo Mac e ti aiuta a completare ogni aggiornamento dalla fonte originale.",
        panelCaption: "Guarda quali app hanno una versione più recente",
        checkNow: "Controlla ora",
        checking: "Controllo in corso",
        lastCheckFormat: "Ultimo controllo %@",
        neverChecked: "Non ancora controllato",
        upToDate: "Nessun aggiornamento trovato",
        partialUpToDate: "Nessun aggiornamento trovato in questa verifica parziale",
        coverageNote: "Controlla le fonti originali delle app installate e un catalogo pubblico. Gli aggiornamenti vengono installati dalla fonte originale.",
        selectAll: "Seleziona tutto",
        clearSelection: "Azzera",
        updateSelectedFormat: "Aggiorna %d",
        updateOne: "Aggiorna",
        openAppStore: "Apri l’App Store",
        appStoreBadge: "App Store",
        storeHint: "Apre l’App Store, dove questo aggiornamento viene installato",
        frequencyLabel: "Controlla in background",
        frequencyOff: "Off",
        frequencyDaily: "Ogni giorno",
        frequencyWeekly: "Ogni settimana",
        nextCheckFormat: "Prossimo controllo %@",
        notifyToggle: "Avvisami quando un’app ha un aggiornamento",
        includeStoreToggle: "Includi le app dell’App Store",
        includeStoreCaption: "Controlla le versioni nello store usando la regione di questo Mac. Apple installa questi aggiornamenti.",
        packageMissing: "Homebrew non è installato, quindi da qui non si possono ancora aggiornare le app.",
        notificationBodyFormat: "%@ app hanno una versione più recente.",
        notificationBodyOne: "Un’app ha una versione più recente.",
        showInPanel: "Mostra nel pannello",
        homebrewBadge: "Homebrew",
        sourcesTitle: "Fonti",
        includeHomebrewToggle: "Includi le app Homebrew",
        onlineBadge: "Online",
        openApp: "Apri",
        openAppHint: "Apre l’app per consentire al suo programma di aggiornamento di terminare",
        includeOnlineToggle: "Includi le altre app installate",
        includeOnlineCaption: "Consulta direttamente gli sviluppatori quando possibile e integra la ricerca con un catalogo pubblico. L’app installa il proprio aggiornamento.",
        incompleteCheck: "Verifica incompleta",
        onlineUnavailable: "Non è stato possibile completare il controllo online. Gli altri risultati restano visibili."
    )

    static let ja = AppUpdateStrings(
        pageTitle: "Appのアップデート",
        hubDescription: "使っているAppのアップデートを見つけて適用",
        caption: "このMacのAppに新しいバージョンがないか調べ、それぞれの元の配布元からアップデートを完了できるようにします。",
        panelCaption: "新しいバージョンがあるAppを確認",
        checkNow: "今すぐ確認",
        checking: "確認中",
        lastCheckFormat: "前回の確認 %@",
        neverChecked: "まだ確認していません",
        upToDate: "アップデートは見つかりませんでした",
        partialUpToDate: "確認できた範囲ではアップデートは見つかりませんでした",
        coverageNote: "インストール済みAppの配布元と公開カタログを確認します。アップデートは元の配布元からインストールされます。",
        selectAll: "すべて選択",
        clearSelection: "選択解除",
        updateSelectedFormat: "%d件をアップデート",
        updateOne: "アップデート",
        openAppStore: "App Storeを開く",
        appStoreBadge: "App Store",
        storeHint: "このアップデートを適用するApp Storeを開きます",
        frequencyLabel: "バックグラウンドで確認",
        frequencyOff: "オフ",
        frequencyDaily: "毎日",
        frequencyWeekly: "毎週",
        nextCheckFormat: "次回の確認 %@",
        notifyToggle: "アップデートがあるときに知らせる",
        includeStoreToggle: "App StoreのAppも含める",
        includeStoreCaption: "このMacの地域を使ってストアのバージョンを確認します。これらのアップデートはAppleがインストールします。",
        packageMissing: "Homebrewが入っていないため、ここからAppをアップデートすることはまだできません。",
        notificationBodyFormat: "%@件のAppに新しいバージョンがあります。",
        notificationBodyOne: "1件のAppに新しいバージョンがあります。",
        showInPanel: "パネルに表示",
        homebrewBadge: "Homebrew",
        sourcesTitle: "ソース",
        includeHomebrewToggle: "HomebrewのAppを含める",
        onlineBadge: "オンライン",
        openApp: "開く",
        openAppHint: "Appを開き、内蔵のアップデート機能で完了します",
        includeOnlineToggle: "その他のインストール済みAppを含める",
        includeOnlineCaption: "対応している場合は開発元に直接確認し、公開カタログで検索を補います。アップデートはApp自身がインストールします。",
        incompleteCheck: "確認が完了していません",
        onlineUnavailable: "オンライン確認を完了できませんでした。その他の結果は引き続き表示されます。"
    )

    static let ko = AppUpdateStrings(
        pageTitle: "앱 업데이트",
        hubDescription: "사용 중인 앱의 업데이트를 찾아 설치",
        caption: "이 Mac에 있는 앱의 새 버전을 찾아 각 업데이트를 원래 출처에서 완료할 수 있도록 도와줍니다.",
        panelCaption: "새 버전이 있는 앱 보기",
        checkNow: "지금 확인",
        checking: "확인 중",
        lastCheckFormat: "마지막 확인 %@",
        neverChecked: "아직 확인하지 않음",
        upToDate: "업데이트를 찾지 못했습니다",
        partialUpToDate: "확인된 범위에서 업데이트를 찾지 못했습니다",
        coverageNote: "설치된 앱의 원래 배포처와 공개 카탈로그를 확인합니다. 업데이트는 원래 배포처를 통해 설치됩니다.",
        selectAll: "모두 선택",
        clearSelection: "선택 해제",
        updateSelectedFormat: "%d개 업데이트",
        updateOne: "업데이트",
        openAppStore: "App Store 열기",
        appStoreBadge: "App Store",
        storeHint: "이 업데이트를 설치하는 App Store를 엽니다",
        frequencyLabel: "백그라운드에서 확인",
        frequencyOff: "끔",
        frequencyDaily: "매일",
        frequencyWeekly: "매주",
        nextCheckFormat: "다음 확인 %@",
        notifyToggle: "앱에 업데이트가 있으면 알리기",
        includeStoreToggle: "App Store 앱 포함",
        includeStoreCaption: "이 Mac의 지역을 기준으로 스토어 버전을 확인합니다. 이 업데이트는 Apple에서 설치합니다.",
        packageMissing: "Homebrew가 설치되어 있지 않아 아직 여기에서 앱을 업데이트할 수 없습니다.",
        notificationBodyFormat: "%@개의 앱에 새 버전이 있습니다.",
        notificationBodyOne: "앱 1개에 새 버전이 있습니다.",
        showInPanel: "패널에 표시",
        homebrewBadge: "Homebrew",
        sourcesTitle: "소스",
        includeHomebrewToggle: "Homebrew 앱 포함",
        onlineBadge: "온라인",
        openApp: "열기",
        openAppHint: "앱을 열어 자체 업데이트 기능으로 완료합니다",
        includeOnlineToggle: "설치된 다른 앱 포함",
        includeOnlineCaption: "지원되는 경우 개발자에게 직접 확인하고 공개 카탈로그로 검색을 보완합니다. 업데이트는 앱 자체에서 설치합니다.",
        incompleteCheck: "확인이 완료되지 않았습니다",
        onlineUnavailable: "온라인 확인을 완료하지 못했습니다. 다른 결과는 계속 표시됩니다."
    )

    static let zhHans = AppUpdateStrings(
        pageTitle: "App 更新",
        hubDescription: "查找并安装你的 App 更新",
        caption: "检查这台 Mac 上的 App 有没有更新版本，并帮助你从各自的原始来源完成更新。",
        panelCaption: "看看哪些 App 有更新的版本",
        checkNow: "立即检查",
        checking: "正在检查",
        lastCheckFormat: "上次检查 %@",
        neverChecked: "尚未检查",
        upToDate: "未找到更新",
        partialUpToDate: "本次部分检查未发现更新",
        coverageNote: "检查已安装 App 的原始来源和公开目录。更新通过原始来源安装。",
        selectAll: "全选",
        clearSelection: "清除",
        updateSelectedFormat: "更新 %d 个",
        updateOne: "更新",
        openAppStore: "打开 App Store",
        appStoreBadge: "App Store",
        storeHint: "打开 App Store，在那里安装此更新",
        frequencyLabel: "在后台检查",
        frequencyOff: "关闭",
        frequencyDaily: "每天",
        frequencyWeekly: "每周",
        nextCheckFormat: "下次检查 %@",
        notifyToggle: "有 App 可以更新时通知我",
        includeStoreToggle: "包含 App Store 的 App",
        includeStoreCaption: "使用此 Mac 的地区查询商店版本。这些更新由 Apple 安装。",
        packageMissing: "没有安装 Homebrew，所以暂时还不能从这里更新 App。",
        notificationBodyFormat: "%@ 个 App 有更新的版本。",
        notificationBodyOne: "有 1 个 App 有更新的版本。",
        showInPanel: "在面板中显示",
        homebrewBadge: "Homebrew",
        sourcesTitle: "来源",
        includeHomebrewToggle: "包含 Homebrew App",
        onlineBadge: "在线",
        openApp: "打开",
        openAppHint: "打开 App，让它自己的更新程序完成更新",
        includeOnlineToggle: "包含其他已安装的 App",
        includeOnlineCaption: "在支持时直接向开发者查询，并通过公开目录补充搜索。更新由 App 自身安装。",
        incompleteCheck: "检查未完成",
        onlineUnavailable: "无法完成在线检查。其他结果仍会显示。"
    )

    static let zhTW = AppUpdateStrings(
        pageTitle: "App 更新",
        hubDescription: "尋找並安裝你的 App 更新",
        caption: "檢查這台 Mac 上的 App 有沒有更新版本，並協助你從各自的原始來源完成更新。",
        panelCaption: "看看哪些 App 有更新的版本",
        checkNow: "立即檢查",
        checking: "正在檢查",
        lastCheckFormat: "上次檢查 %@",
        neverChecked: "尚未檢查",
        upToDate: "找不到更新",
        partialUpToDate: "本次部分檢查未找到更新",
        coverageNote: "檢查已安裝 App 的原始來源與公開目錄。更新透過原始來源安裝。",
        selectAll: "全選",
        clearSelection: "清除",
        updateSelectedFormat: "更新 %d 個",
        updateOne: "更新",
        openAppStore: "打開 App Store",
        appStoreBadge: "App Store",
        storeHint: "打開 App Store，在那裡安裝此更新",
        frequencyLabel: "在背景檢查",
        frequencyOff: "關閉",
        frequencyDaily: "每天",
        frequencyWeekly: "每週",
        nextCheckFormat: "下次檢查 %@",
        notifyToggle: "有 App 可以更新時通知我",
        includeStoreToggle: "包含 App Store 的 App",
        includeStoreCaption: "使用此 Mac 的地區查詢商店版本。這些更新由 Apple 安裝。",
        packageMissing: "沒有安裝 Homebrew，所以暫時還不能從這裡更新 App。",
        notificationBodyFormat: "%@ 個 App 有更新的版本。",
        notificationBodyOne: "有 1 個 App 有更新的版本。",
        showInPanel: "在面板中顯示",
        homebrewBadge: "Homebrew",
        sourcesTitle: "來源",
        includeHomebrewToggle: "包含 Homebrew App",
        onlineBadge: "線上",
        openApp: "打開",
        openAppHint: "打開 App，讓它自己的更新程式完成更新",
        includeOnlineToggle: "包含其他已安裝的 App",
        includeOnlineCaption: "支援時直接向開發者查詢，並透過公開目錄補充搜尋。更新由 App 自行安裝。",
        incompleteCheck: "檢查未完成",
        onlineUnavailable: "無法完成線上檢查。其他結果仍會顯示。"
    )

    static let zhHK = AppUpdateStrings(
        pageTitle: "App 更新",
        hubDescription: "尋找並安裝你的 App 更新",
        caption: "檢查呢部 Mac 上嘅 App 有冇更新版本，並協助你由各自原來嘅來源完成更新。",
        panelCaption: "睇吓邊啲 App 有更新版本",
        checkNow: "立即檢查",
        checking: "正在檢查",
        lastCheckFormat: "上次檢查 %@",
        neverChecked: "尚未檢查",
        upToDate: "搵唔到更新",
        partialUpToDate: "今次部分檢查未搵到更新",
        coverageNote: "檢查已安裝 App 嘅原始來源同公開目錄。更新由原始來源安裝。",
        selectAll: "全選",
        clearSelection: "清除",
        updateSelectedFormat: "更新 %d 個",
        updateOne: "更新",
        openAppStore: "打開 App Store",
        appStoreBadge: "App Store",
        storeHint: "打開 App Store，喺嗰度安裝呢個更新",
        frequencyLabel: "喺背景檢查",
        frequencyOff: "關閉",
        frequencyDaily: "每日",
        frequencyWeekly: "每週",
        nextCheckFormat: "下次檢查 %@",
        notifyToggle: "有 App 可以更新時通知我",
        includeStoreToggle: "包含 App Store 的 App",
        includeStoreCaption: "使用呢部 Mac 嘅地區查詢商店版本。呢啲更新由 Apple 安裝。",
        packageMissing: "未安裝 Homebrew，所以暫時仲未可以喺呢度更新 App。",
        notificationBodyFormat: "%@ 個 App 有更新版本。",
        notificationBodyOne: "有 1 個 App 有更新版本。",
        showInPanel: "喺面板中顯示",
        homebrewBadge: "Homebrew",
        sourcesTitle: "來源",
        includeHomebrewToggle: "包含 Homebrew App",
        onlineBadge: "網上",
        openApp: "打開",
        openAppHint: "打開 App，等佢自己嘅更新程式完成更新",
        includeOnlineToggle: "包含其他已安裝嘅 App",
        includeOnlineCaption: "支援時會直接向開發者查詢，再用公開目錄補充搜尋。更新由 App 自行安裝。",
        incompleteCheck: "檢查未完成",
        onlineUnavailable: "無法完成網上檢查。其他結果仍然會顯示。"
    )
}
