// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct FanControlFeatureStrings {
    let title: String
    let hubDescription: String
    let showInPanel: String
    let settingsCaption: String
    let fanNameFormat: String
    let rpmFormat: String
    let allowControl: String
    let approvalCaption: String
    let openSettings: String
    let noFans: String
    let unsupported: String
    let alreadyControlled: String
    let failed: String
    let safetyCaption: String
    let safetyStopped: String
    let menuBarTitle: String
    let systemControl: String
    let manualControl: String
    let customCurve: String
    let mode: String
    let coolingIntensity: String
    let currentRPMFormat: String
    let targetRPMFormat: String
    let applyManual: String
    let applyCurve: String
    let returnToSystem: String
    let temperatureUnavailable: String
    let curveUnavailable: String
    let sensor: String
    let temperature: String
    let fanSpeed: String
    let addPoint: String
    let addSensor: String
    let removePoint: String
    let removeSensor: String
    let curveGraph: String
    let averageSoC: String
    let hottestSoC: String
    let averageCPU: String
    let hottestCPU: String
    let hottestGPU: String
    let helperUnavailable: String
}

extension FeatureStrings {
    static func fanControl(_ language: AppLanguage) -> FanControlFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension FanControlFeatureStrings {
    static let enUS = FanControlFeatureStrings(
        title: "Fan Control",
        hubDescription: "Control fans manually or with temperature curves while seeing live and target RPM",
        showInPanel: "Show Fan Control in the panel",
        settingsCaption: "Adds manual fan speeds and temperature curves to the menu bar panel.",
        fanNameFormat: "Fan %d",
        rpmFormat: "%d RPM",
        allowControl: "Allow fan control",
        approvalCaption: "Allow Vorssaint in Login Items to use the protected fan controller.",
        openSettings: "Open System Settings",
        noFans: "This Mac has no controllable fan.",
        unsupported: "Fan control is not available on this Mac.",
        alreadyControlled: "Another process is controlling the fans. Return it to system control first.",
        failed: "The fans returned to system control because the requested control could not be verified.",
        safetyCaption: "Control stays active until you return to System. It returns automatically if the app disconnects, the Mac sleeps, sensor readings fail or thermal pressure rises.",
        safetyStopped: "Returned to system control because fan control was interrupted.",
        menuBarTitle: "Fan speed",
        systemControl: "System",
        manualControl: "Manual",
        customCurve: "Curve",
        mode: "Control mode",
        coolingIntensity: "Fan speed",
        currentRPMFormat: "Current %d RPM",
        targetRPMFormat: "Target %d RPM",
        applyManual: "Apply manual control",
        applyCurve: "Apply fan curve",
        returnToSystem: "Use system control",
        temperatureUnavailable: "The selected temperature sensor stopped responding. Fan control returned to System.",
        curveUnavailable: "A selected temperature sensor is not available on this Mac.",
        sensor: "Temperature sensor",
        temperature: "Temperature",
        fanSpeed: "Fan speed",
        addPoint: "Add point",
        addSensor: "Add sensor",
        removePoint: "Remove point",
        removeSensor: "Remove sensor",
        curveGraph: "Temperature and fan speed curve",
        averageSoC: "Average SoC",
        hottestSoC: "Hottest SoC",
        averageCPU: "Average CPU",
        hottestCPU: "Hottest CPU",
        hottestGPU: "Hottest GPU",
        helperUnavailable: "The protected fan controller is unavailable. Allow Vorssaint in Login Items, then try again."
    )

    static let ptBR = FanControlFeatureStrings(
        title: "Controle das ventoinhas",
        hubDescription: "Controle manual ou por curvas de temperatura, com RPM atual e RPM-alvo",
        showInPanel: "Mostrar controle das ventoinhas no painel",
        settingsCaption: "Adiciona velocidades manuais e curvas de temperatura ao painel.",
        fanNameFormat: "Ventoinha %d",
        rpmFormat: "%d RPM",
        allowControl: "Permitir controle",
        approvalCaption: "Permita o Vorssaint nos Itens de Início para usar o controle protegido das ventoinhas.",
        openSettings: "Abrir Ajustes do Sistema",
        noFans: "Este Mac não tem ventoinha controlável.",
        unsupported: "O controle das ventoinhas não está disponível neste Mac.",
        alreadyControlled: "Outro processo está controlando as ventoinhas. Volte ao controle do sistema nele primeiro.",
        failed: "As ventoinhas voltaram ao sistema porque não foi possível confirmar o controle solicitado.",
        safetyCaption: "O controle fica ativo até você voltar ao Sistema. Ele é devolvido automaticamente se o app desconectar, o Mac repousar, os sensores falharem ou a pressão térmica subir.",
        safetyStopped: "Voltou ao controle do sistema porque o controle das ventoinhas foi interrompido.",
        menuBarTitle: "Velocidade das ventoinhas",
        systemControl: "Sistema",
        manualControl: "Manual",
        customCurve: "Curva",
        mode: "Modo de controle",
        coolingIntensity: "Velocidade das ventoinhas",
        currentRPMFormat: "Atual: %d RPM",
        targetRPMFormat: "Alvo: %d RPM",
        applyManual: "Aplicar controle manual",
        applyCurve: "Aplicar curva",
        returnToSystem: "Usar controle do sistema",
        temperatureUnavailable: "O sensor de temperatura selecionado parou de responder. O controle voltou ao Sistema.",
        curveUnavailable: "Um sensor de temperatura selecionado não está disponível neste Mac.",
        sensor: "Sensor de temperatura",
        temperature: "Temperatura",
        fanSpeed: "Velocidade",
        addPoint: "Adicionar ponto",
        addSensor: "Adicionar sensor",
        removePoint: "Remover ponto",
        removeSensor: "Remover sensor",
        curveGraph: "Curva de temperatura e velocidade",
        averageSoC: "Média do SoC",
        hottestSoC: "SoC mais quente",
        averageCPU: "Média da CPU",
        hottestCPU: "CPU mais quente",
        hottestGPU: "GPU mais quente",
        helperUnavailable: "O controlador protegido das ventoinhas não está disponível. Permita o Vorssaint nos Itens de Início e tente novamente."
    )

    static let tr = FanControlFeatureStrings(
        title: "Fan denetimi",
        hubDescription: "Canlı ve hedef RPM ile fanları elle veya sıcaklık eğrileriyle denetleyin",
        showInPanel: "Fan denetimini panelde göster",
        settingsCaption: "Menü çubuğu paneline elle fan hızı ve sıcaklık eğrileri ekler.",
        fanNameFormat: "Fan %d",
        rpmFormat: "%d RPM",
        allowControl: "Fan denetimine izin ver",
        approvalCaption: "Korumalı fan denetimini kullanmak için Giriş Öğeleri’nde Vorssaint’e izin verin.",
        openSettings: "Sistem Ayarları’nı Aç",
        noFans: "Bu Mac’te denetlenebilir fan yok.",
        unsupported: "Bu Mac’te fan denetimi kullanılamıyor.",
        alreadyControlled: "Fanları başka bir işlem denetliyor. Önce oradan sistem denetimine dönün.",
        failed: "İstenen denetim doğrulanamadığı için fanlar sistem denetimine döndü.",
        safetyCaption: "Sistem’e dönene kadar denetim etkin kalır. Uygulama bağlantısı kesilirse, Mac uyursa, sensör okumaları başarısız olursa veya termal basınç yükselirse otomatik olarak geri verilir.",
        safetyStopped: "Fan denetimi kesildiği için sistem denetimine dönüldü.",
        menuBarTitle: "Fan hızı",
        systemControl: "Sistem",
        manualControl: "Elle",
        customCurve: "Eğri",
        mode: "Denetim modu",
        coolingIntensity: "Fan hızı",
        currentRPMFormat: "Anlık %d RPM",
        targetRPMFormat: "Hedef %d RPM",
        applyManual: "Elle denetimi uygula",
        applyCurve: "Fan eğrisini uygula",
        returnToSystem: "Sistem denetimini kullan",
        temperatureUnavailable: "Seçilen sıcaklık sensörü yanıt vermeyi bıraktı. Fan denetimi Sistem’e döndü.",
        curveUnavailable: "Seçilen bir sıcaklık sensörü bu Mac’te kullanılamıyor.",
        sensor: "Sıcaklık sensörü",
        temperature: "Sıcaklık",
        fanSpeed: "Fan hızı",
        addPoint: "Nokta ekle",
        addSensor: "Sensör ekle",
        removePoint: "Noktayı kaldır",
        removeSensor: "Sensörü kaldır",
        curveGraph: "Sıcaklık ve fan hızı eğrisi",
        averageSoC: "Ortalama SoC",
        hottestSoC: "En sıcak SoC",
        averageCPU: "Ortalama CPU",
        hottestCPU: "En sıcak CPU",
        hottestGPU: "En sıcak GPU",
        helperUnavailable: "Korumalı fan denetleyicisi kullanılamıyor. Giriş Öğeleri’nde Vorssaint’e izin verip yeniden deneyin."
    )

    static let ru = FanControlFeatureStrings(
        title: "Управление вентиляторами",
        hubDescription: "Ручное управление и температурные кривые с текущими и целевыми оборотами",
        showInPanel: "Показывать управление вентиляторами на панели",
        settingsCaption: "Добавляет на панель ручную скорость и температурные кривые.",
        fanNameFormat: "Вентилятор %d",
        rpmFormat: "%d об/мин",
        allowControl: "Разрешить управление",
        approvalCaption: "Разрешите Vorssaint в Объектах входа для защищённого управления вентиляторами.",
        openSettings: "Открыть Системные настройки",
        noFans: "На этом Mac нет управляемого вентилятора.",
        unsupported: "Управление вентиляторами недоступно на этом Mac.",
        alreadyControlled: "Вентиляторами управляет другой процесс. Сначала верните там управление системе.",
        failed: "Вентиляторы вернулись под управление системы, потому что запрос не удалось проверить.",
        safetyCaption: "Управление действует до возврата в режим «Система». Оно возвращается автоматически при отключении приложения, сне Mac, сбое датчиков или росте тепловой нагрузки.",
        safetyStopped: "Управление возвращено системе из-за прерывания управления вентиляторами.",
        menuBarTitle: "Скорость вентилятора",
        systemControl: "Система",
        manualControl: "Вручную",
        customCurve: "Кривая",
        mode: "Режим управления",
        coolingIntensity: "Скорость вентиляторов",
        currentRPMFormat: "Сейчас %d об/мин",
        targetRPMFormat: "Цель %d об/мин",
        applyManual: "Применить ручной режим",
        applyCurve: "Применить кривую",
        returnToSystem: "Использовать управление системы",
        temperatureUnavailable: "Выбранный датчик температуры перестал отвечать. Управление возвращено системе.",
        curveUnavailable: "Один из выбранных датчиков температуры недоступен на этом Mac.",
        sensor: "Датчик температуры",
        temperature: "Температура",
        fanSpeed: "Скорость",
        addPoint: "Добавить точку",
        addSensor: "Добавить датчик",
        removePoint: "Удалить точку",
        removeSensor: "Удалить датчик",
        curveGraph: "Кривая температуры и скорости вентилятора",
        averageSoC: "Средняя SoC",
        hottestSoC: "Самая горячая SoC",
        averageCPU: "Средняя CPU",
        hottestCPU: "Самая горячая CPU",
        hottestGPU: "Самая горячая GPU",
        helperUnavailable: "Защищённый контроллер вентиляторов недоступен. Разрешите Vorssaint в Объектах входа и повторите попытку."
    )

    static let es = FanControlFeatureStrings(
        title: "Control de ventiladores",
        hubDescription: "Control manual o por curvas de temperatura con RPM actuales y objetivo",
        showInPanel: "Mostrar el control de ventiladores en el panel",
        settingsCaption: "Añade velocidades manuales y curvas de temperatura al panel.",
        fanNameFormat: "Ventilador %d",
        rpmFormat: "%d RPM",
        allowControl: "Permitir control",
        approvalCaption: "Permite Vorssaint en Ítems de inicio para usar el control protegido de los ventiladores.",
        openSettings: "Abrir Ajustes del Sistema",
        noFans: "Este Mac no tiene ningún ventilador controlable.",
        unsupported: "El control de ventiladores no está disponible en este Mac.",
        alreadyControlled: "Otro proceso controla los ventiladores. Devuélvelos primero al control del sistema.",
        failed: "Los ventiladores volvieron al sistema porque no se pudo verificar el control solicitado.",
        safetyCaption: "El control sigue activo hasta que vuelvas a Sistema. Se devuelve automáticamente si la app se desconecta, el Mac entra en reposo, fallan los sensores o aumenta la presión térmica.",
        safetyStopped: "Se devolvió el control al sistema porque se interrumpió el control de los ventiladores.",
        menuBarTitle: "Velocidad de ventiladores",
        systemControl: "Sistema",
        manualControl: "Manual",
        customCurve: "Curva",
        mode: "Modo de control",
        coolingIntensity: "Velocidad de los ventiladores",
        currentRPMFormat: "Actual: %d RPM",
        targetRPMFormat: "Objetivo: %d RPM",
        applyManual: "Aplicar control manual",
        applyCurve: "Aplicar curva",
        returnToSystem: "Usar control del sistema",
        temperatureUnavailable: "El sensor de temperatura seleccionado dejó de responder. El control volvió al Sistema.",
        curveUnavailable: "Uno de los sensores de temperatura seleccionados no está disponible en este Mac.",
        sensor: "Sensor de temperatura",
        temperature: "Temperatura",
        fanSpeed: "Velocidad",
        addPoint: "Añadir punto",
        addSensor: "Añadir sensor",
        removePoint: "Eliminar punto",
        removeSensor: "Eliminar sensor",
        curveGraph: "Curva de temperatura y velocidad",
        averageSoC: "Promedio del SoC",
        hottestSoC: "SoC más caliente",
        averageCPU: "Promedio de CPU",
        hottestCPU: "CPU más caliente",
        hottestGPU: "GPU más caliente",
        helperUnavailable: "El controlador protegido de los ventiladores no está disponible. Permite Vorssaint en Ítems de inicio e inténtalo de nuevo."
    )

    static let de = FanControlFeatureStrings(
        title: "Lüftersteuerung",
        hubDescription: "Lüfter manuell oder per Temperaturkurve mit Ist- und Ziel-Drehzahl steuern",
        showInPanel: "Lüftersteuerung im Panel anzeigen",
        settingsCaption: "Fügt dem Panel manuelle Drehzahlen und Temperaturkurven hinzu.",
        fanNameFormat: "Lüfter %d",
        rpmFormat: "%d U/min",
        allowControl: "Lüftersteuerung erlauben",
        approvalCaption: "Erlaube Vorssaint unter Anmeldeobjekte, um die geschützte Lüftersteuerung zu verwenden.",
        openSettings: "Systemeinstellungen öffnen",
        noFans: "Dieser Mac hat keinen steuerbaren Lüfter.",
        unsupported: "Die Lüftersteuerung ist auf diesem Mac nicht verfügbar.",
        alreadyControlled: "Ein anderer Prozess steuert die Lüfter. Gib sie dort zuerst an das System zurück.",
        failed: "Die Lüfter wurden an das System zurückgegeben, weil die gewünschte Steuerung nicht bestätigt werden konnte.",
        safetyCaption: "Die Steuerung bleibt bis zur Rückkehr zu System aktiv. Sie wird bei getrennter App, Ruhezustand, Sensorausfall oder steigendem thermischem Druck automatisch zurückgegeben.",
        safetyStopped: "Wegen einer Unterbrechung wurde die Lüftersteuerung an das System zurückgegeben.",
        menuBarTitle: "Lüftergeschwindigkeit",
        systemControl: "System",
        manualControl: "Manuell",
        customCurve: "Kurve",
        mode: "Steuerungsmodus",
        coolingIntensity: "Lüftergeschwindigkeit",
        currentRPMFormat: "Aktuell %d U/min",
        targetRPMFormat: "Ziel %d U/min",
        applyManual: "Manuelle Steuerung anwenden",
        applyCurve: "Lüfterkurve anwenden",
        returnToSystem: "Systemsteuerung verwenden",
        temperatureUnavailable: "Der gewählte Temperatursensor antwortet nicht mehr. Die Steuerung wurde an das System zurückgegeben.",
        curveUnavailable: "Ein ausgewählter Temperatursensor ist auf diesem Mac nicht verfügbar.",
        sensor: "Temperatursensor",
        temperature: "Temperatur",
        fanSpeed: "Lüftergeschwindigkeit",
        addPoint: "Punkt hinzufügen",
        addSensor: "Sensor hinzufügen",
        removePoint: "Punkt entfernen",
        removeSensor: "Sensor entfernen",
        curveGraph: "Temperatur- und Lüfterkurve",
        averageSoC: "SoC-Durchschnitt",
        hottestSoC: "Heißester SoC",
        averageCPU: "CPU-Durchschnitt",
        hottestCPU: "Heißeste CPU",
        hottestGPU: "Heißeste GPU",
        helperUnavailable: "Die geschützte Lüftersteuerung ist nicht verfügbar. Erlaube Vorssaint unter Anmeldeobjekte und versuche es erneut."
    )

    static let fr = FanControlFeatureStrings(
        title: "Contrôle des ventilateurs",
        hubDescription: "Contrôle manuel ou par courbes de température avec vitesses réelle et cible",
        showInPanel: "Afficher le contrôle des ventilateurs dans le panneau",
        settingsCaption: "Ajoute les vitesses manuelles et les courbes de température au panneau.",
        fanNameFormat: "Ventilateur %d",
        rpmFormat: "%d tr/min",
        allowControl: "Autoriser le contrôle",
        approvalCaption: "Autorisez Vorssaint dans Ouverture pour utiliser le contrôle protégé des ventilateurs.",
        openSettings: "Ouvrir Réglages Système",
        noFans: "Ce Mac ne possède aucun ventilateur contrôlable.",
        unsupported: "Le contrôle des ventilateurs n’est pas disponible sur ce Mac.",
        alreadyControlled: "Un autre processus contrôle les ventilateurs. Rendez-les d’abord au système.",
        failed: "Les ventilateurs ont été rendus au système car le contrôle demandé n’a pas pu être vérifié.",
        safetyCaption: "Le contrôle reste actif jusqu’au retour à Système. Il est rendu automatiquement si l’app se déconnecte, si le Mac veille, si les capteurs échouent ou si la pression thermique augmente.",
        safetyStopped: "Le contrôle a été rendu au système car le contrôle des ventilateurs a été interrompu.",
        menuBarTitle: "Vitesse des ventilateurs",
        systemControl: "Système",
        manualControl: "Manuel",
        customCurve: "Courbe",
        mode: "Mode de contrôle",
        coolingIntensity: "Vitesse des ventilateurs",
        currentRPMFormat: "Actuelle %d tr/min",
        targetRPMFormat: "Cible %d tr/min",
        applyManual: "Appliquer le contrôle manuel",
        applyCurve: "Appliquer la courbe",
        returnToSystem: "Utiliser le contrôle du système",
        temperatureUnavailable: "Le capteur de température choisi ne répond plus. Le contrôle a été rendu au Système.",
        curveUnavailable: "Un capteur de température sélectionné n’est pas disponible sur ce Mac.",
        sensor: "Capteur de température",
        temperature: "Température",
        fanSpeed: "Vitesse",
        addPoint: "Ajouter un point",
        addSensor: "Ajouter un capteur",
        removePoint: "Supprimer le point",
        removeSensor: "Supprimer le capteur",
        curveGraph: "Courbe de température et de vitesse",
        averageSoC: "Moyenne du SoC",
        hottestSoC: "SoC le plus chaud",
        averageCPU: "Moyenne du CPU",
        hottestCPU: "CPU le plus chaud",
        hottestGPU: "GPU le plus chaud",
        helperUnavailable: "Le contrôleur protégé des ventilateurs est indisponible. Autorisez Vorssaint dans Ouverture, puis réessayez."
    )

    static let it = FanControlFeatureStrings(
        title: "Controllo ventole",
        hubDescription: "Controllo manuale o con curve termiche e RPM attuali e obiettivo",
        showInPanel: "Mostra il controllo ventole nel pannello",
        settingsCaption: "Aggiunge velocità manuali e curve di temperatura al pannello.",
        fanNameFormat: "Ventola %d",
        rpmFormat: "%d RPM",
        allowControl: "Consenti controllo",
        approvalCaption: "Consenti Vorssaint in Elementi login per usare il controllo protetto delle ventole.",
        openSettings: "Apri Impostazioni di Sistema",
        noFans: "Questo Mac non ha ventole controllabili.",
        unsupported: "Il controllo ventole non è disponibile su questo Mac.",
        alreadyControlled: "Un altro processo controlla le ventole. Riportale prima al controllo di sistema.",
        failed: "Le ventole sono tornate al sistema perché non è stato possibile verificare il controllo richiesto.",
        safetyCaption: "Il controllo resta attivo finché non torni a Sistema. Viene restituito automaticamente se l’app si disconnette, il Mac va in stop, i sensori falliscono o aumenta la pressione termica.",
        safetyStopped: "Il controllo è tornato al sistema perché il controllo delle ventole è stato interrotto.",
        menuBarTitle: "Velocità ventole",
        systemControl: "Sistema",
        manualControl: "Manuale",
        customCurve: "Curva",
        mode: "Modalità di controllo",
        coolingIntensity: "Velocità delle ventole",
        currentRPMFormat: "Attuale %d RPM",
        targetRPMFormat: "Obiettivo %d RPM",
        applyManual: "Applica controllo manuale",
        applyCurve: "Applica curva",
        returnToSystem: "Usa controllo di sistema",
        temperatureUnavailable: "Il sensore di temperatura selezionato non risponde più. Il controllo è tornato al Sistema.",
        curveUnavailable: "Un sensore di temperatura selezionato non è disponibile su questo Mac.",
        sensor: "Sensore di temperatura",
        temperature: "Temperatura",
        fanSpeed: "Velocità",
        addPoint: "Aggiungi punto",
        addSensor: "Aggiungi sensore",
        removePoint: "Rimuovi punto",
        removeSensor: "Rimuovi sensore",
        curveGraph: "Curva di temperatura e velocità",
        averageSoC: "Media SoC",
        hottestSoC: "SoC più caldo",
        averageCPU: "Media CPU",
        hottestCPU: "CPU più calda",
        hottestGPU: "GPU più calda",
        helperUnavailable: "Il controller protetto delle ventole non è disponibile. Consenti Vorssaint negli elementi di login e riprova."
    )

    static let ja = FanControlFeatureStrings(
        title: "ファン制御",
        hubDescription: "現在と目標の回転数を確認しながら手動または温度曲線でファンを制御",
        showInPanel: "ファン制御をパネルに表示",
        settingsCaption: "手動の回転数と温度曲線をメニューバーパネルに追加します。",
        fanNameFormat: "ファン%d",
        rpmFormat: "%d RPM",
        allowControl: "ファン制御を許可",
        approvalCaption: "保護されたファン制御を使うには、ログイン項目でVorssaintを許可してください。",
        openSettings: "システム設定を開く",
        noFans: "このMacには制御可能なファンがありません。",
        unsupported: "このMacではファン制御を利用できません。",
        alreadyControlled: "別のプロセスがファンを制御しています。先にシステム制御へ戻してください。",
        failed: "要求した制御を確認できなかったため、ファンはシステム制御へ戻りました。",
        safetyCaption: "システムへ戻すまで制御は有効です。アプリの切断、Macのスリープ、センサー障害、熱圧力の上昇時には自動でシステムへ戻ります。",
        safetyStopped: "ファン制御が中断されたため、システム制御へ戻りました。",
        menuBarTitle: "ファン速度",
        systemControl: "システム",
        manualControl: "手動",
        customCurve: "曲線",
        mode: "制御モード",
        coolingIntensity: "ファン速度",
        currentRPMFormat: "現在 %d RPM",
        targetRPMFormat: "目標 %d RPM",
        applyManual: "手動制御を適用",
        applyCurve: "ファン曲線を適用",
        returnToSystem: "システム制御を使用",
        temperatureUnavailable: "選択した温度センサーが応答しなくなりました。システム制御へ戻りました。",
        curveUnavailable: "選択した温度センサーのいずれかをこのMacで利用できません。",
        sensor: "温度センサー",
        temperature: "温度",
        fanSpeed: "ファン速度",
        addPoint: "ポイントを追加",
        addSensor: "センサーを追加",
        removePoint: "ポイントを削除",
        removeSensor: "センサーを削除",
        curveGraph: "温度とファン速度の曲線",
        averageSoC: "SoC平均",
        hottestSoC: "最高SoC",
        averageCPU: "CPU平均",
        hottestCPU: "最高CPU",
        hottestGPU: "最高GPU",
        helperUnavailable: "保護されたファンコントローラを利用できません。ログイン項目でVorssaintを許可してから、もう一度お試しください。"
    )

    static let ko = FanControlFeatureStrings(
        title: "팬 제어",
        hubDescription: "현재 및 목표 RPM을 보며 수동 또는 온도 곡선으로 팬 제어",
        showInPanel: "패널에 팬 제어 표시",
        settingsCaption: "메뉴 막대 패널에 수동 속도와 온도 곡선을 추가합니다.",
        fanNameFormat: "팬 %d",
        rpmFormat: "%d RPM",
        allowControl: "팬 제어 허용",
        approvalCaption: "보호된 팬 제어를 사용하려면 로그인 항목에서 Vorssaint를 허용하세요.",
        openSettings: "시스템 설정 열기",
        noFans: "이 Mac에는 제어 가능한 팬이 없습니다.",
        unsupported: "이 Mac에서는 팬 제어를 사용할 수 없습니다.",
        alreadyControlled: "다른 프로세스가 팬을 제어하고 있습니다. 먼저 시스템 제어로 돌려놓으세요.",
        failed: "요청한 제어를 확인할 수 없어 팬이 시스템 제어로 돌아갔습니다.",
        safetyCaption: "시스템으로 돌아갈 때까지 제어가 유지됩니다. 앱 연결 해제, Mac 잠자기, 센서 오류 또는 열 압력 상승 시 자동으로 시스템에 반환됩니다.",
        safetyStopped: "팬 제어가 중단되어 시스템 제어로 돌아갔습니다.",
        menuBarTitle: "팬 속도",
        systemControl: "시스템",
        manualControl: "수동",
        customCurve: "곡선",
        mode: "제어 모드",
        coolingIntensity: "팬 속도",
        currentRPMFormat: "현재 %d RPM",
        targetRPMFormat: "목표 %d RPM",
        applyManual: "수동 제어 적용",
        applyCurve: "팬 곡선 적용",
        returnToSystem: "시스템 제어 사용",
        temperatureUnavailable: "선택한 온도 센서가 응답하지 않습니다. 팬 제어가 시스템으로 돌아갔습니다.",
        curveUnavailable: "선택한 온도 센서 중 하나를 이 Mac에서 사용할 수 없습니다.",
        sensor: "온도 센서",
        temperature: "온도",
        fanSpeed: "팬 속도",
        addPoint: "지점 추가",
        addSensor: "센서 추가",
        removePoint: "지점 제거",
        removeSensor: "센서 제거",
        curveGraph: "온도 및 팬 속도 곡선",
        averageSoC: "평균 SoC",
        hottestSoC: "가장 뜨거운 SoC",
        averageCPU: "평균 CPU",
        hottestCPU: "가장 뜨거운 CPU",
        hottestGPU: "가장 뜨거운 GPU",
        helperUnavailable: "보호된 팬 컨트롤러를 사용할 수 없습니다. 로그인 항목에서 Vorssaint를 허용한 다음 다시 시도하세요."
    )

    static let zhHans = FanControlFeatureStrings(
        title: "风扇控制",
        hubDescription: "查看当前和目标转速，并手动或按温度曲线控制风扇",
        showInPanel: "在面板中显示风扇控制",
        settingsCaption: "在菜单栏面板中添加手动转速和温度曲线。",
        fanNameFormat: "风扇%d",
        rpmFormat: "%d RPM",
        allowControl: "允许风扇控制",
        approvalCaption: "请在登录项中允许Vorssaint使用受保护的风扇控制。",
        openSettings: "打开系统设置",
        noFans: "这台Mac没有可控风扇。",
        unsupported: "这台Mac不支持风扇控制。",
        alreadyControlled: "另一个进程正在控制风扇。请先在那里恢复系统控制。",
        failed: "无法验证请求的控制，风扇已恢复系统控制。",
        safetyCaption: "控制会保持到你恢复系统模式。App 断开、Mac睡眠、传感器失效或热压力升高时会自动交还系统。",
        safetyStopped: "风扇控制中断，已恢复系统控制。",
        menuBarTitle: "风扇转速",
        systemControl: "系统",
        manualControl: "手动",
        customCurve: "曲线",
        mode: "控制模式",
        coolingIntensity: "风扇速度",
        currentRPMFormat: "当前 %d RPM",
        targetRPMFormat: "目标 %d RPM",
        applyManual: "启用手动控制",
        applyCurve: "启用风扇曲线",
        returnToSystem: "使用系统控制",
        temperatureUnavailable: "所选温度传感器停止响应。风扇控制已恢复系统模式。",
        curveUnavailable: "这台Mac不支持某个所选温度传感器。",
        sensor: "温度传感器",
        temperature: "温度",
        fanSpeed: "风扇速度",
        addPoint: "添加节点",
        addSensor: "添加传感器",
        removePoint: "移除节点",
        removeSensor: "移除传感器",
        curveGraph: "温度与风扇速度曲线",
        averageSoC: "SoC平均温度",
        hottestSoC: "SoC最高温度",
        averageCPU: "CPU平均温度",
        hottestCPU: "CPU最高温度",
        hottestGPU: "GPU最高温度",
        helperUnavailable: "受保护的风扇控制器不可用。请在登录项中允许 Vorssaint，然后重试。"
    )

    static let zhTW = FanControlFeatureStrings(
        title: "風扇控制",
        hubDescription: "查看目前與目標轉速，並手動或依溫度曲線控制風扇",
        showInPanel: "在面板中顯示風扇控制",
        settingsCaption: "在選單列面板中加入手動轉速與溫度曲線。",
        fanNameFormat: "風扇%d",
        rpmFormat: "%d RPM",
        allowControl: "允許風扇控制",
        approvalCaption: "請在登入項目中允許Vorssaint使用受保護的風扇控制。",
        openSettings: "打開系統設定",
        noFans: "這台Mac沒有可控制的風扇。",
        unsupported: "這台Mac不支援風扇控制。",
        alreadyControlled: "另一個程序正在控制風扇。請先在那裡恢復系統控制。",
        failed: "無法驗證要求的控制，風扇已恢復系統控制。",
        safetyCaption: "控制會持續到你恢復系統模式。App中斷、Mac睡眠、感測器失效或熱壓力升高時會自動交還系統。",
        safetyStopped: "風扇控制中斷，已恢復系統控制。",
        menuBarTitle: "風扇轉速",
        systemControl: "系統",
        manualControl: "手動",
        customCurve: "曲線",
        mode: "控制模式",
        coolingIntensity: "風扇速度",
        currentRPMFormat: "目前 %d RPM",
        targetRPMFormat: "目標 %d RPM",
        applyManual: "套用手動控制",
        applyCurve: "套用風扇曲線",
        returnToSystem: "使用系統控制",
        temperatureUnavailable: "所選溫度感測器停止回應。風扇控制已恢復系統模式。",
        curveUnavailable: "這台Mac不支援某個所選溫度感測器。",
        sensor: "溫度感測器",
        temperature: "溫度",
        fanSpeed: "風扇速度",
        addPoint: "加入節點",
        addSensor: "加入感測器",
        removePoint: "移除節點",
        removeSensor: "移除感測器",
        curveGraph: "溫度與風扇速度曲線",
        averageSoC: "SoC平均溫度",
        hottestSoC: "SoC最高溫度",
        averageCPU: "CPU平均溫度",
        hottestCPU: "CPU最高溫度",
        hottestGPU: "GPU最高溫度",
        helperUnavailable: "受保護的風扇控制器無法使用。請在登入項目中允許 Vorssaint，然後再試一次。"
    )

    static let zhHK = FanControlFeatureStrings(
        title: "風扇控制",
        hubDescription: "查看目前與目標轉速，並手動或依溫度曲線控制風扇",
        showInPanel: "在面板中顯示風扇控制",
        settingsCaption: "在選單列面板中加入手動轉速與溫度曲線。",
        fanNameFormat: "風扇%d",
        rpmFormat: "%d RPM",
        allowControl: "允許風扇控制",
        approvalCaption: "請在登入項目中允許Vorssaint使用受保護的風扇控制。",
        openSettings: "開啟系統設定",
        noFans: "這部Mac沒有可控制的風扇。",
        unsupported: "這部Mac不支援風扇控制。",
        alreadyControlled: "另一個程序正在控制風扇。請先在那裡恢復系統控制。",
        failed: "無法驗證要求的控制，風扇已恢復系統控制。",
        safetyCaption: "控制會持續到你恢復系統模式。App中斷、Mac睡眠、感測器失效或熱壓力升高時會自動交還系統。",
        safetyStopped: "風扇控制中斷，已恢復系統控制。",
        menuBarTitle: "風扇轉速",
        systemControl: "系統",
        manualControl: "手動",
        customCurve: "曲線",
        mode: "控制模式",
        coolingIntensity: "風扇速度",
        currentRPMFormat: "目前 %d RPM",
        targetRPMFormat: "目標 %d RPM",
        applyManual: "套用手動控制",
        applyCurve: "套用風扇曲線",
        returnToSystem: "使用系統控制",
        temperatureUnavailable: "所選溫度感測器停止回應。風扇控制已恢復系統模式。",
        curveUnavailable: "這部Mac不支援某個所選溫度感測器。",
        sensor: "溫度感測器",
        temperature: "溫度",
        fanSpeed: "風扇速度",
        addPoint: "加入節點",
        addSensor: "加入感測器",
        removePoint: "移除節點",
        removeSensor: "移除感測器",
        curveGraph: "溫度與風扇速度曲線",
        averageSoC: "SoC平均溫度",
        hottestSoC: "SoC最高溫度",
        averageCPU: "CPU平均溫度",
        hottestCPU: "CPU最高溫度",
        hottestGPU: "GPU最高溫度",
        helperUnavailable: "受保護的風扇控制器無法使用。請在登入項目允許 Vorssaint，然後再試一次。"
    )
}
