// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct MediaImageConverterStrings {
    let filesSelectedFormat: String
    let profile: String
    let noProfile: String
    let profileName: String
    let saveAsNew: String
    let updateProfile: String
    let deleteProfile: String
    let profileModified: String
    let profileDefaultNameFormat: String
    let presetWeb: String
    let presetSocial: String
    let presetDocs: String
    let resize: String
    let resizeNone: String
    let resizeMax: String
    let resizeWidth: String
    let resizeHeight: String
    let resizeExact: String
    let exactStretch: String
    let exactFit: String
    let exactFill: String
    let height: String
    let watermark: String
    let watermarkOff: String
    let watermarkText: String
    let watermarkLogo: String
    let watermarkBoth: String
    let watermarkTextPlaceholder: String
    let noLogo: String
    let chooseLogo: String
    let position: String
    let topLeft: String
    let topRight: String
    let center: String
    let bottomLeft: String
    let bottomRight: String
    let opacity: String
    let margin: String
    let scale: String
    let rename: String
    let preview: String
    let outputName: String
    let background: String
    let backgroundTransparent: String
    let backgroundWhite: String
    let backgroundBlack: String
    let preserveDate: String
    let moreOptions: String
    let tooLarge: String
    let copySummary: String
    let savedBytesFormat: String
    let grewBytesFormat: String
    let batchSavedFormat: String
    let batchPartialFormat: String
    let batchSummaryHeaderFormat: String
    let batchSummaryItemFormat: String

    static func localized(_ language: AppLanguage) -> MediaImageConverterStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension MediaImageConverterStrings {
    static let enUS = MediaImageConverterStrings(
        filesSelectedFormat: "%d files selected",
        profile: "Profile",
        noProfile: "No profile",
        profileName: "Profile name",
        saveAsNew: "Save new",
        updateProfile: "Update",
        deleteProfile: "Delete profile",
        profileModified: "Modified",
        profileDefaultNameFormat: "Profile %d",
        presetWeb: "Web",
        presetSocial: "Social",
        presetDocs: "Docs",
        resize: "Resize",
        resizeNone: "No change",
        resizeMax: "Max side",
        resizeWidth: "Width",
        resizeHeight: "Height",
        resizeExact: "Custom",
        exactStretch: "Stretch",
        exactFit: "Fit",
        exactFill: "Fill",
        height: "Height",
        watermark: "Watermark",
        watermarkOff: "Off",
        watermarkText: "Text",
        watermarkLogo: "Logo",
        watermarkBoth: "Text + logo",
        watermarkTextPlaceholder: "Watermark text",
        noLogo: "No logo",
        chooseLogo: "Choose logo",
        position: "Position",
        topLeft: "Top left",
        topRight: "Top right",
        center: "Center",
        bottomLeft: "Bottom left",
        bottomRight: "Bottom right",
        opacity: "Opacity",
        margin: "Margin",
        scale: "Scale",
        rename: "Rename",
        preview: "Preview",
        outputName: "Output",
        background: "Background",
        backgroundTransparent: "Transparent",
        backgroundWhite: "White",
        backgroundBlack: "Black",
        preserveDate: "Keep original modified date",
        moreOptions: "More options",
        tooLarge: "These dimensions are too large to process safely. Choose a smaller size.",
        copySummary: "Copy summary",
        savedBytesFormat: "%@ saved",
        grewBytesFormat: "%@ larger",
        batchSavedFormat: "%d images saved",
        batchPartialFormat: "%d saved, %d failed",
        batchSummaryHeaderFormat: "%d saved, %d failed",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let ptBR = MediaImageConverterStrings(
        filesSelectedFormat: "%d arquivos selecionados",
        profile: "Perfil",
        noProfile: "Sem perfil",
        profileName: "Nome do perfil",
        saveAsNew: "Salvar novo",
        updateProfile: "Atualizar",
        deleteProfile: "Excluir perfil",
        profileModified: "Alterado",
        profileDefaultNameFormat: "Perfil %d",
        presetWeb: "Web",
        presetSocial: "Redes sociais",
        presetDocs: "Documentos",
        resize: "Redimensionar",
        resizeNone: "Sem alterar",
        resizeMax: "Maior lado",
        resizeWidth: "Largura",
        resizeHeight: "Altura",
        resizeExact: "Personalizado",
        exactStretch: "Esticar",
        exactFit: "Ajustar",
        exactFill: "Preencher",
        height: "Altura",
        watermark: "Marca d’água",
        watermarkOff: "Desativada",
        watermarkText: "Texto",
        watermarkLogo: "Logotipo",
        watermarkBoth: "Texto + logotipo",
        watermarkTextPlaceholder: "Texto da marca d’água",
        noLogo: "Sem logotipo",
        chooseLogo: "Escolher logotipo",
        position: "Posição",
        topLeft: "Superior esquerdo",
        topRight: "Superior direito",
        center: "Centro",
        bottomLeft: "Inferior esquerdo",
        bottomRight: "Inferior direito",
        opacity: "Opacidade",
        margin: "Margem",
        scale: "Escala",
        rename: "Renomear",
        preview: "Prévia",
        outputName: "Saída",
        background: "Fundo",
        backgroundTransparent: "Transparente",
        backgroundWhite: "Branco",
        backgroundBlack: "Preto",
        preserveDate: "Manter data de modificação original",
        moreOptions: "Mais opções",
        tooLarge: "Estas dimensões são grandes demais para processar com segurança. Escolha um tamanho menor.",
        copySummary: "Copiar resumo",
        savedBytesFormat: "%@ economizados",
        grewBytesFormat: "%@ maior",
        batchSavedFormat: "%d imagens salvas",
        batchPartialFormat: "%d salvas, %d falharam",
        batchSummaryHeaderFormat: "%d salvas, %d falharam",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let tr = MediaImageConverterStrings(
        filesSelectedFormat: "%d dosya seçildi",
        profile: "Profil",
        noProfile: "Profil yok",
        profileName: "Profil adı",
        saveAsNew: "Yeni kaydet",
        updateProfile: "Güncelle",
        deleteProfile: "Profili sil",
        profileModified: "Değiştirildi",
        profileDefaultNameFormat: "Profil %d",
        presetWeb: "Web",
        presetSocial: "Sosyal",
        presetDocs: "Belgeler",
        resize: "Yeniden boyutlandır",
        resizeNone: "Değişiklik yok",
        resizeMax: "En uzun kenar",
        resizeWidth: "Genişlik",
        resizeHeight: "Yükseklik",
        resizeExact: "Özel",
        exactStretch: "Esnet",
        exactFit: "Sığdır",
        exactFill: "Doldur",
        height: "Yükseklik",
        watermark: "Filigran",
        watermarkOff: "Kapalı",
        watermarkText: "Metin",
        watermarkLogo: "Logo",
        watermarkBoth: "Metin + logo",
        watermarkTextPlaceholder: "Filigran metni",
        noLogo: "Logo yok",
        chooseLogo: "Logo seç",
        position: "Konum",
        topLeft: "Sol üst",
        topRight: "Sağ üst",
        center: "Orta",
        bottomLeft: "Sol alt",
        bottomRight: "Sağ alt",
        opacity: "Opaklık",
        margin: "Kenar boşluğu",
        scale: "Ölçek",
        rename: "Yeniden adlandır",
        preview: "Önizleme",
        outputName: "Çıktı",
        background: "Arka plan",
        backgroundTransparent: "Saydam",
        backgroundWhite: "Beyaz",
        backgroundBlack: "Siyah",
        preserveDate: "Özgün değiştirilme tarihini koru",
        moreOptions: "Daha fazla seçenek",
        tooLarge: "Bu boyutlar güvenle işlenemeyecek kadar büyük. Daha küçük bir boyut seçin.",
        copySummary: "Özeti kopyala",
        savedBytesFormat: "%@ tasarruf edildi",
        grewBytesFormat: "%@ daha büyük",
        batchSavedFormat: "%d görüntü kaydedildi",
        batchPartialFormat: "%d kaydedildi, %d başarısız",
        batchSummaryHeaderFormat: "%d kaydedildi, %d başarısız",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let ru = MediaImageConverterStrings(
        filesSelectedFormat: "Выбрано файлов: %d",
        profile: "Профиль",
        noProfile: "Без профиля",
        profileName: "Название профиля",
        saveAsNew: "Сохранить новый",
        updateProfile: "Обновить",
        deleteProfile: "Удалить профиль",
        profileModified: "Изменено",
        profileDefaultNameFormat: "Профиль %d",
        presetWeb: "Для веба",
        presetSocial: "Соцсети",
        presetDocs: "Документы",
        resize: "Изменить размер",
        resizeNone: "Без изменений",
        resizeMax: "Макс. сторона",
        resizeWidth: "Ширина",
        resizeHeight: "Высота",
        resizeExact: "Другой",
        exactStretch: "Растянуть",
        exactFit: "Вписать",
        exactFill: "Заполнить",
        height: "Высота",
        watermark: "Водяной знак",
        watermarkOff: "Выкл.",
        watermarkText: "Текст",
        watermarkLogo: "Логотип",
        watermarkBoth: "Текст + логотип",
        watermarkTextPlaceholder: "Текст водяного знака",
        noLogo: "Без логотипа",
        chooseLogo: "Выбрать логотип",
        position: "Положение",
        topLeft: "Сверху слева",
        topRight: "Сверху справа",
        center: "По центру",
        bottomLeft: "Снизу слева",
        bottomRight: "Снизу справа",
        opacity: "Непрозрачность",
        margin: "Отступ",
        scale: "Масштаб",
        rename: "Переименовать",
        preview: "Предпросмотр",
        outputName: "Результат",
        background: "Фон",
        backgroundTransparent: "Прозрачный",
        backgroundWhite: "Белый",
        backgroundBlack: "Черный",
        preserveDate: "Сохранить исходную дату изменения",
        moreOptions: "Дополнительные параметры",
        tooLarge: "Эти размеры слишком велики для безопасной обработки. Выберите меньший размер.",
        copySummary: "Копировать сводку",
        savedBytesFormat: "Сэкономлено %@",
        grewBytesFormat: "Больше на %@",
        batchSavedFormat: "Сохранено изображений: %d",
        batchPartialFormat: "Сохранено: %d, ошибок: %d",
        batchSummaryHeaderFormat: "Сохранено: %d, ошибок: %d",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let es = MediaImageConverterStrings(
        filesSelectedFormat: "%d archivos seleccionados",
        profile: "Perfil",
        noProfile: "Sin perfil",
        profileName: "Nombre del perfil",
        saveAsNew: "Guardar nuevo",
        updateProfile: "Actualizar",
        deleteProfile: "Eliminar perfil",
        profileModified: "Modificado",
        profileDefaultNameFormat: "Perfil %d",
        presetWeb: "Web",
        presetSocial: "Redes sociales",
        presetDocs: "Documentos",
        resize: "Redimensionar",
        resizeNone: "Sin cambios",
        resizeMax: "Lado máximo",
        resizeWidth: "Ancho",
        resizeHeight: "Alto",
        resizeExact: "Personalizado",
        exactStretch: "Estirar",
        exactFit: "Encajar",
        exactFill: "Rellenar",
        height: "Alto",
        watermark: "Marca de agua",
        watermarkOff: "Desactivada",
        watermarkText: "Texto",
        watermarkLogo: "Logotipo",
        watermarkBoth: "Texto + logotipo",
        watermarkTextPlaceholder: "Texto de la marca de agua",
        noLogo: "Sin logotipo",
        chooseLogo: "Elegir logotipo",
        position: "Posición",
        topLeft: "Arriba a la izquierda",
        topRight: "Arriba a la derecha",
        center: "Centro",
        bottomLeft: "Abajo a la izquierda",
        bottomRight: "Abajo a la derecha",
        opacity: "Opacidad",
        margin: "Margen",
        scale: "Escala",
        rename: "Renombrar",
        preview: "Vista previa",
        outputName: "Salida",
        background: "Fondo",
        backgroundTransparent: "Transparente",
        backgroundWhite: "Blanco",
        backgroundBlack: "Negro",
        preserveDate: "Conservar la fecha de modificación original",
        moreOptions: "Más opciones",
        tooLarge: "Estas dimensiones son demasiado grandes para procesarlas con seguridad. Elige un tamaño menor.",
        copySummary: "Copiar resumen",
        savedBytesFormat: "%@ ahorrados",
        grewBytesFormat: "%@ más grande",
        batchSavedFormat: "%d imágenes guardadas",
        batchPartialFormat: "%d guardadas, %d fallidas",
        batchSummaryHeaderFormat: "%d guardadas, %d fallidas",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let de = MediaImageConverterStrings(
        filesSelectedFormat: "%d Dateien ausgewählt",
        profile: "Profil",
        noProfile: "Kein Profil",
        profileName: "Profilname",
        saveAsNew: "Neu speichern",
        updateProfile: "Aktualisieren",
        deleteProfile: "Profil löschen",
        profileModified: "Geändert",
        profileDefaultNameFormat: "Profil %d",
        presetWeb: "Web",
        presetSocial: "Soziale Medien",
        presetDocs: "Dokumente",
        resize: "Größe ändern",
        resizeNone: "Keine Änderung",
        resizeMax: "Längste Seite",
        resizeWidth: "Breite",
        resizeHeight: "Höhe",
        resizeExact: "Eigene Größe",
        exactStretch: "Strecken",
        exactFit: "Einpassen",
        exactFill: "Ausfüllen",
        height: "Höhe",
        watermark: "Wasserzeichen",
        watermarkOff: "Aus",
        watermarkText: "Text",
        watermarkLogo: "Logo",
        watermarkBoth: "Text + Logo",
        watermarkTextPlaceholder: "Wasserzeichentext",
        noLogo: "Kein Logo",
        chooseLogo: "Logo auswählen",
        position: "Position",
        topLeft: "Oben links",
        topRight: "Oben rechts",
        center: "Mitte",
        bottomLeft: "Unten links",
        bottomRight: "Unten rechts",
        opacity: "Deckkraft",
        margin: "Rand",
        scale: "Skalierung",
        rename: "Umbenennen",
        preview: "Vorschau",
        outputName: "Ausgabe",
        background: "Hintergrund",
        backgroundTransparent: "Transparent",
        backgroundWhite: "Weiß",
        backgroundBlack: "Schwarz",
        preserveDate: "Ursprüngliches Änderungsdatum behalten",
        moreOptions: "Weitere Optionen",
        tooLarge: "Diese Abmessungen sind für eine sichere Verarbeitung zu groß. Wähle eine kleinere Größe.",
        copySummary: "Zusammenfassung kopieren",
        savedBytesFormat: "%@ gespart",
        grewBytesFormat: "%@ größer",
        batchSavedFormat: "%d Bilder gespeichert",
        batchPartialFormat: "%d gespeichert, %d fehlgeschlagen",
        batchSummaryHeaderFormat: "%d gespeichert, %d fehlgeschlagen",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let fr = MediaImageConverterStrings(
        filesSelectedFormat: "%d fichiers sélectionnés",
        profile: "Profil",
        noProfile: "Aucun profil",
        profileName: "Nom du profil",
        saveAsNew: "Enregistrer un nouveau",
        updateProfile: "Mettre à jour",
        deleteProfile: "Supprimer le profil",
        profileModified: "Modifié",
        profileDefaultNameFormat: "Profil %d",
        presetWeb: "Web",
        presetSocial: "Réseaux sociaux",
        presetDocs: "Documents",
        resize: "Redimensionner",
        resizeNone: "Aucun changement",
        resizeMax: "Côté maximal",
        resizeWidth: "Largeur",
        resizeHeight: "Hauteur",
        resizeExact: "Personnalisé",
        exactStretch: "Étirer",
        exactFit: "Ajuster",
        exactFill: "Remplir",
        height: "Hauteur",
        watermark: "Filigrane",
        watermarkOff: "Désactivé",
        watermarkText: "Texte",
        watermarkLogo: "Logo",
        watermarkBoth: "Texte + logo",
        watermarkTextPlaceholder: "Texte du filigrane",
        noLogo: "Aucun logo",
        chooseLogo: "Choisir un logo",
        position: "Position",
        topLeft: "En haut à gauche",
        topRight: "En haut à droite",
        center: "Centre",
        bottomLeft: "En bas à gauche",
        bottomRight: "En bas à droite",
        opacity: "Opacité",
        margin: "Marge",
        scale: "Échelle",
        rename: "Renommer",
        preview: "Aperçu",
        outputName: "Sortie",
        background: "Arrière-plan",
        backgroundTransparent: "Transparent",
        backgroundWhite: "Blanc",
        backgroundBlack: "Noir",
        preserveDate: "Conserver la date de modification d’origine",
        moreOptions: "Plus d’options",
        tooLarge: "Ces dimensions sont trop grandes pour un traitement sûr. Choisissez une taille plus petite.",
        copySummary: "Copier le résumé",
        savedBytesFormat: "%@ économisés",
        grewBytesFormat: "%@ plus grand",
        batchSavedFormat: "%d images enregistrées",
        batchPartialFormat: "%d enregistrées, %d échouées",
        batchSummaryHeaderFormat: "%d enregistrées, %d échouées",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let it = MediaImageConverterStrings(
        filesSelectedFormat: "%d file selezionati",
        profile: "Profilo",
        noProfile: "Nessun profilo",
        profileName: "Nome del profilo",
        saveAsNew: "Salva nuovo",
        updateProfile: "Aggiorna",
        deleteProfile: "Elimina profilo",
        profileModified: "Modificato",
        profileDefaultNameFormat: "Profilo %d",
        presetWeb: "Web",
        presetSocial: "Social",
        presetDocs: "Documenti",
        resize: "Ridimensiona",
        resizeNone: "Nessuna modifica",
        resizeMax: "Lato massimo",
        resizeWidth: "Larghezza",
        resizeHeight: "Altezza",
        resizeExact: "Personalizzato",
        exactStretch: "Allunga",
        exactFit: "Adatta",
        exactFill: "Riempi",
        height: "Altezza",
        watermark: "Filigrana",
        watermarkOff: "Disattivata",
        watermarkText: "Testo",
        watermarkLogo: "Logo",
        watermarkBoth: "Testo + logo",
        watermarkTextPlaceholder: "Testo della filigrana",
        noLogo: "Nessun logo",
        chooseLogo: "Scegli logo",
        position: "Posizione",
        topLeft: "In alto a sinistra",
        topRight: "In alto a destra",
        center: "Centro",
        bottomLeft: "In basso a sinistra",
        bottomRight: "In basso a destra",
        opacity: "Opacità",
        margin: "Margine",
        scale: "Scala",
        rename: "Rinomina",
        preview: "Anteprima",
        outputName: "Uscita",
        background: "Sfondo",
        backgroundTransparent: "Trasparente",
        backgroundWhite: "Bianco",
        backgroundBlack: "Nero",
        preserveDate: "Mantieni la data di modifica originale",
        moreOptions: "Altre opzioni",
        tooLarge: "Queste dimensioni sono troppo grandi per un’elaborazione sicura. Scegli una dimensione più piccola.",
        copySummary: "Copia riepilogo",
        savedBytesFormat: "%@ risparmiati",
        grewBytesFormat: "%@ più grande",
        batchSavedFormat: "%d immagini salvate",
        batchPartialFormat: "%d salvate, %d non riuscite",
        batchSummaryHeaderFormat: "%d salvate, %d non riuscite",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let ja = MediaImageConverterStrings(
        filesSelectedFormat: "%d個のファイルを選択",
        profile: "プロファイル",
        noProfile: "プロファイルなし",
        profileName: "プロファイル名",
        saveAsNew: "新規保存",
        updateProfile: "更新",
        deleteProfile: "プロファイルを削除",
        profileModified: "変更済み",
        profileDefaultNameFormat: "プロファイル%d",
        presetWeb: "Web",
        presetSocial: "SNS",
        presetDocs: "書類",
        resize: "サイズ変更",
        resizeNone: "変更しない",
        resizeMax: "長辺",
        resizeWidth: "幅",
        resizeHeight: "高さ",
        resizeExact: "カスタム",
        exactStretch: "引き伸ばす",
        exactFit: "収める",
        exactFill: "埋める",
        height: "高さ",
        watermark: "透かし",
        watermarkOff: "オフ",
        watermarkText: "テキスト",
        watermarkLogo: "ロゴ",
        watermarkBoth: "テキスト + ロゴ",
        watermarkTextPlaceholder: "透かしテキスト",
        noLogo: "ロゴなし",
        chooseLogo: "ロゴを選択",
        position: "位置",
        topLeft: "左上",
        topRight: "右上",
        center: "中央",
        bottomLeft: "左下",
        bottomRight: "右下",
        opacity: "不透明度",
        margin: "余白",
        scale: "大きさ",
        rename: "名前を変更",
        preview: "プレビュー",
        outputName: "出力",
        background: "背景",
        backgroundTransparent: "透明",
        backgroundWhite: "白",
        backgroundBlack: "黒",
        preserveDate: "元の変更日を保持",
        moreOptions: "その他のオプション",
        tooLarge: "このサイズは安全に処理するには大きすぎます。小さいサイズを選んでください。",
        copySummary: "概要をコピー",
        savedBytesFormat: "%@節約",
        grewBytesFormat: "%@増加",
        batchSavedFormat: "%d枚の画像を保存",
        batchPartialFormat: "%d枚を保存、%d枚が失敗",
        batchSummaryHeaderFormat: "%d枚を保存、%d枚が失敗",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let ko = MediaImageConverterStrings(
        filesSelectedFormat: "%d개 파일 선택됨",
        profile: "프로필",
        noProfile: "프로필 없음",
        profileName: "프로필 이름",
        saveAsNew: "새로 저장",
        updateProfile: "업데이트",
        deleteProfile: "프로필 삭제",
        profileModified: "수정됨",
        profileDefaultNameFormat: "프로필 %d",
        presetWeb: "웹",
        presetSocial: "소셜",
        presetDocs: "문서",
        resize: "크기 조절",
        resizeNone: "변경 안 함",
        resizeMax: "긴 변",
        resizeWidth: "너비",
        resizeHeight: "높이",
        resizeExact: "사용자 설정",
        exactStretch: "늘이기",
        exactFit: "맞추기",
        exactFill: "채우기",
        height: "높이",
        watermark: "워터마크",
        watermarkOff: "끔",
        watermarkText: "텍스트",
        watermarkLogo: "로고",
        watermarkBoth: "텍스트 + 로고",
        watermarkTextPlaceholder: "워터마크 텍스트",
        noLogo: "로고 없음",
        chooseLogo: "로고 선택",
        position: "위치",
        topLeft: "왼쪽 위",
        topRight: "오른쪽 위",
        center: "가운데",
        bottomLeft: "왼쪽 아래",
        bottomRight: "오른쪽 아래",
        opacity: "불투명도",
        margin: "여백",
        scale: "크기",
        rename: "이름 변경",
        preview: "미리보기",
        outputName: "출력",
        background: "배경",
        backgroundTransparent: "투명",
        backgroundWhite: "흰색",
        backgroundBlack: "검은색",
        preserveDate: "원본 수정일 유지",
        moreOptions: "추가 옵션",
        tooLarge: "이 크기는 안전하게 처리하기에 너무 큽니다. 더 작은 크기를 선택하세요.",
        copySummary: "요약 복사",
        savedBytesFormat: "%@ 절약",
        grewBytesFormat: "%@ 더 큼",
        batchSavedFormat: "이미지 %d개 저장됨",
        batchPartialFormat: "%d개 저장, %d개 실패",
        batchSummaryHeaderFormat: "%d개 저장, %d개 실패",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let zhHans = MediaImageConverterStrings(
        filesSelectedFormat: "已选择 %d 个文件",
        profile: "配置",
        noProfile: "无配置",
        profileName: "配置名称",
        saveAsNew: "另存为新配置",
        updateProfile: "更新",
        deleteProfile: "删除配置",
        profileModified: "已修改",
        profileDefaultNameFormat: "配置 %d",
        presetWeb: "网页",
        presetSocial: "社交",
        presetDocs: "文档",
        resize: "调整大小",
        resizeNone: "不更改",
        resizeMax: "最长边",
        resizeWidth: "宽度",
        resizeHeight: "高度",
        resizeExact: "自定义",
        exactStretch: "拉伸",
        exactFit: "适应",
        exactFill: "填充",
        height: "高度",
        watermark: "水印",
        watermarkOff: "关闭",
        watermarkText: "文字",
        watermarkLogo: "标志",
        watermarkBoth: "文字 + 标志",
        watermarkTextPlaceholder: "水印文字",
        noLogo: "无标志",
        chooseLogo: "选择标志",
        position: "位置",
        topLeft: "左上",
        topRight: "右上",
        center: "居中",
        bottomLeft: "左下",
        bottomRight: "右下",
        opacity: "不透明度",
        margin: "边距",
        scale: "缩放",
        rename: "重命名",
        preview: "预览",
        outputName: "输出",
        background: "背景",
        backgroundTransparent: "透明",
        backgroundWhite: "白色",
        backgroundBlack: "黑色",
        preserveDate: "保留原始修改日期",
        moreOptions: "更多选项",
        tooLarge: "这些尺寸太大，无法安全处理。请选择更小的尺寸。",
        copySummary: "拷贝摘要",
        savedBytesFormat: "节省 %@",
        grewBytesFormat: "增大 %@",
        batchSavedFormat: "已存储 %d 张图像",
        batchPartialFormat: "已存储 %d 张，%d 张失败",
        batchSummaryHeaderFormat: "已存储 %d 张，%d 张失败",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let zhTW = MediaImageConverterStrings(
        filesSelectedFormat: "已選取 %d 個檔案",
        profile: "設定檔",
        noProfile: "無設定檔",
        profileName: "設定檔名稱",
        saveAsNew: "另存新設定檔",
        updateProfile: "更新",
        deleteProfile: "刪除設定檔",
        profileModified: "已修改",
        profileDefaultNameFormat: "設定檔 %d",
        presetWeb: "網頁",
        presetSocial: "社群",
        presetDocs: "文件",
        resize: "調整大小",
        resizeNone: "不更改",
        resizeMax: "最長邊",
        resizeWidth: "寬度",
        resizeHeight: "高度",
        resizeExact: "自訂",
        exactStretch: "拉伸",
        exactFit: "符合",
        exactFill: "填滿",
        height: "高度",
        watermark: "浮水印",
        watermarkOff: "關閉",
        watermarkText: "文字",
        watermarkLogo: "標誌",
        watermarkBoth: "文字 + 標誌",
        watermarkTextPlaceholder: "浮水印文字",
        noLogo: "無標誌",
        chooseLogo: "選擇標誌",
        position: "位置",
        topLeft: "左上",
        topRight: "右上",
        center: "置中",
        bottomLeft: "左下",
        bottomRight: "右下",
        opacity: "不透明度",
        margin: "邊距",
        scale: "縮放",
        rename: "重新命名",
        preview: "預覽",
        outputName: "輸出",
        background: "背景",
        backgroundTransparent: "透明",
        backgroundWhite: "白色",
        backgroundBlack: "黑色",
        preserveDate: "保留原始修改日期",
        moreOptions: "更多選項",
        tooLarge: "這些尺寸太大，無法安全處理。請選擇較小的尺寸。",
        copySummary: "複製摘要",
        savedBytesFormat: "節省 %@",
        grewBytesFormat: "增加 %@",
        batchSavedFormat: "已儲存 %d 張影像",
        batchPartialFormat: "已儲存 %d 張，%d 張失敗",
        batchSummaryHeaderFormat: "已儲存 %d 張，%d 張失敗",
        batchSummaryItemFormat: "%@ -> %@"
    )

    static let zhHK = MediaImageConverterStrings(
        filesSelectedFormat: "已選取 %d 個檔案",
        profile: "設定檔",
        noProfile: "無設定檔",
        profileName: "設定檔名稱",
        saveAsNew: "另存新設定檔",
        updateProfile: "更新",
        deleteProfile: "刪除設定檔",
        profileModified: "已修改",
        profileDefaultNameFormat: "設定檔 %d",
        presetWeb: "網頁",
        presetSocial: "社交媒體",
        presetDocs: "文件",
        resize: "調整大小",
        resizeNone: "不變",
        resizeMax: "最長邊",
        resizeWidth: "闊度",
        resizeHeight: "高度",
        resizeExact: "自訂",
        exactStretch: "拉伸",
        exactFit: "配合",
        exactFill: "填滿",
        height: "高度",
        watermark: "水印",
        watermarkOff: "關閉",
        watermarkText: "文字",
        watermarkLogo: "標誌",
        watermarkBoth: "文字 + 標誌",
        watermarkTextPlaceholder: "水印文字",
        noLogo: "無標誌",
        chooseLogo: "選擇標誌",
        position: "位置",
        topLeft: "左上",
        topRight: "右上",
        center: "置中",
        bottomLeft: "左下",
        bottomRight: "右下",
        opacity: "不透明度",
        margin: "邊距",
        scale: "縮放",
        rename: "重新命名",
        preview: "預覽",
        outputName: "輸出",
        background: "背景",
        backgroundTransparent: "透明",
        backgroundWhite: "白色",
        backgroundBlack: "黑色",
        preserveDate: "保留原本修改日期",
        moreOptions: "更多選項",
        tooLarge: "這些尺寸太大，無法安全處理。請選擇較小的尺寸。",
        copySummary: "複製摘要",
        savedBytesFormat: "節省 %@",
        grewBytesFormat: "增加 %@",
        batchSavedFormat: "已儲存 %d 張圖像",
        batchPartialFormat: "已儲存 %d 張，%d 張失敗",
        batchSummaryHeaderFormat: "已儲存 %d 張，%d 張失敗",
        batchSummaryItemFormat: "%@ -> %@"
    )
}
