// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct RadialMenuFeatureStrings {
    let pageTitle: String
    let hubDescription: String
    let enableLabel: String
    let enableCaption: String
    let positionLabel: String
    let positionPointer: String
    let positionCenter: String
    let tryButton: String
    let actionsHeader: String
    let addButton: String
    let limitCaption: String
    let emptyCaption: String
    let backButton: String
    let editActionsButton: String
    let nameLabel: String
    let automaticLabel: String
    let iconLabel: String
    let actionLabel: String
    let kindApp: String
    let kindFile: String
    let kindURL: String
    let kindShortcut: String
    let kindTool: String
    let kindMedia: String
    let kindSubmenu: String
    let chooseButton: String
    let urlPlaceholder: String
    let urlInvalid: String
    let toolLabel: String
    let mediaLabel: String
    let mediaPlayPause: String
    let mediaPrevious: String
    let mediaNext: String
    let mediaNowPlaying: String
    let mediaNothingPlaying: String
    let mediaOpenAppFormat: String
    let submenuCaption: String
    let saveButton: String
    let deleteButton: String
    let permissionCaption: String
    let manageButton: String
    let panelCaption: String
    let mouseTriggerLabel: String
    let mouseTriggerOff: String
    let mouseTriggerBack: String
    let mouseTriggerForward: String
    let mouseTriggerWarning: String
    let buttonTestLabel: String
    let buttonTestWaiting: String
    let buttonTestSeen: String
    let buttonTestOther: String
    let buttonTestBlind: String
    let buttonTestHint: String
    let activationModeLabel: String
    let activationModePressOrHold: String
    let activationModePress: String
    let activationModeHold: String
    let activationModeCaption: String
    let profilesHeader: String
    let profilePickerLabel: String
    let addProfileButton: String
    let duplicateProfileButton: String
    let deleteProfileButton: String
    let profileNameLabel: String
    let profileColorLabel: String
    let profileShortcutLabel: String
    let profileMouseTriggerLabel: String
    let presetGeneral: String
    let presetMedia: String
    let presetTools: String
    let presetWindowLayout: String
    let presetQuickToggles: String
    let presetBlank: String
    let colorAccent: String
    let colorBlue: String
    let colorPurple: String
    let colorPink: String
    let colorRed: String
    let colorOrange: String
    let colorYellow: String
    let colorGreen: String
    let colorMint: String
    let colorCyan: String
    let colorIndigo: String
    let colorGraphite: String
    let fetchFaviconButton: String
    let fetchFaviconDisclaimer: String
    let fetchFaviconLoading: String
    let fetchFaviconSuccess: String
    let fetchFaviconError: String
    let mouseTriggerRequirement: String
    let canvasHint: String
    let resetActionsButton: String
    let resetActionsConfirm: String
    let resetActionsConfirmMessage: String
    let showListButton: String
    let hideListButton: String
}

extension FeatureStrings {
    static func radialMenu(_ language: AppLanguage) -> RadialMenuFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension RadialMenuFeatureStrings {
    static let enUS = RadialMenuFeatureStrings(
        pageTitle: "Radial menu",
        hubDescription: "Opens a wheel of your favorite actions around the pointer",
        enableLabel: "Use the radial menu",
        enableCaption: "Hold the shortcut, point at an action and release. A quick press keeps the wheel open.",
        positionLabel: "Opens",
        positionPointer: "At the pointer",
        positionCenter: "At the screen center",
        tryButton: "Try it",
        actionsHeader: "Actions",
        addButton: "Add action",
        limitCaption: "A wheel holds up to 12 actions.",
        emptyCaption: "No actions here yet.",
        backButton: "Back",
        editActionsButton: "Edit actions",
        nameLabel: "Name",
        automaticLabel: "Automatic",
        iconLabel: "Icon",
        actionLabel: "Action",
        kindApp: "Open an app",
        kindFile: "Open a file or folder",
        kindURL: "Open a link",
        kindShortcut: "Press a shortcut",
        kindTool: "Vorssaint tool",
        kindMedia: "Media control",
        kindSubmenu: "Submenu",
        chooseButton: "Choose…",
        urlPlaceholder: "example.com",
        urlInvalid: "Enter a valid link.",
        toolLabel: "Tool",
        mediaLabel: "Control",
        mediaPlayPause: "Play or pause",
        mediaPrevious: "Previous track",
        mediaNext: "Next track",
        mediaNowPlaying: "Now Playing",
        mediaNothingPlaying: "Nothing playing",
        mediaOpenAppFormat: "Open %@",
        submenuCaption: "Opens a second wheel with its own actions.",
        saveButton: "Save",
        deleteButton: "Remove",
        permissionCaption: "Key actions and the side mouse button trigger need the Accessibility permission.",
        manageButton: "Manage the menu",
        panelCaption: "Your favorite actions on a wheel",
        mouseTriggerLabel: "Mouse button",
        mouseTriggerOff: "Off",
        mouseTriggerBack: "Back side button",
        mouseTriggerForward: "Forward side button",
        mouseTriggerWarning: "While this is on, that button no longer goes back or forward in apps. If you navigate with it, leave this off.",
        buttonTestLabel: "Button test",
        buttonTestWaiting: "Press the button now",
        buttonTestSeen: "Vorssaint sees this button",
        buttonTestOther: "That was a different button",
        buttonTestBlind: "Vorssaint cannot watch the mouse right now",
        buttonTestHint: "If nothing lights up, macOS is not sending that button to apps. Mice that come with their own software often turn the side buttons into something else. Change it back there, or give the button a key combination and use that combination above.",
        activationModeLabel: "Opening behavior",
        activationModePressOrHold: "Press or hold",
        activationModePress: "Press to open",
        activationModeHold: "Hold to select",
        activationModeCaption: "Press or hold keeps the current adaptive gesture. Press stays open; hold runs the highlighted action on release.",
        profilesHeader: "Profiles",
        profilePickerLabel: "Profile",
        addProfileButton: "Add profile",
        duplicateProfileButton: "Duplicate profile",
        deleteProfileButton: "Delete profile",
        profileNameLabel: "Profile name",
        profileColorLabel: "Color",
        profileShortcutLabel: "Shortcut",
        profileMouseTriggerLabel: "Mouse button",
        presetGeneral: "General",
        presetMedia: "Media",
        presetTools: "Tools",
        presetWindowLayout: "Window layout",
        presetQuickToggles: "Quick toggles",
        presetBlank: "Blank",
        colorAccent: "Accent",
        colorBlue: "Blue",
        colorPurple: "Purple",
        colorPink: "Pink",
        colorRed: "Red",
        colorOrange: "Orange",
        colorYellow: "Yellow",
        colorGreen: "Green",
        colorMint: "Mint",
        colorCyan: "Cyan",
        colorIndigo: "Indigo",
        colorGraphite: "Graphite",
        fetchFaviconButton: "Fetch Website Icon",
        fetchFaviconDisclaimer: "Connects to the website once to download its icon. Saved locally.",
        fetchFaviconLoading: "Fetching icon…",
        fetchFaviconSuccess: "Icon downloaded",
        fetchFaviconError: "Could not find a website icon",
        mouseTriggerRequirement: "Only extra mouse buttons work here. With a trackpad or a mouse without extra buttons, use the keyboard shortcut above.",
        canvasHint: "Click a button to choose what it starts, or to remove it. Drag a button to move it.",
        resetActionsButton: "Reset",
        resetActionsConfirm: "Reset actions",
        resetActionsConfirmMessage: "Restore the default actions for this profile? Custom actions will be replaced.",
        showListButton: "Show as list",
        hideListButton: "Hide list"
    )

    static let ptBR = RadialMenuFeatureStrings(
        pageTitle: "Menu radial",
        hubDescription: "Abre uma roda com as suas ações favoritas ao redor do ponteiro",
        enableLabel: "Usar o menu radial",
        enableCaption: "Segure o atalho, aponte para uma ação e solte. Um toque rápido mantém a roda aberta.",
        positionLabel: "Abre",
        positionPointer: "No ponteiro",
        positionCenter: "No centro da tela",
        tryButton: "Experimentar",
        actionsHeader: "Ações",
        addButton: "Adicionar ação",
        limitCaption: "Uma roda comporta até 12 ações.",
        emptyCaption: "Ainda não há ações aqui.",
        backButton: "Voltar",
        editActionsButton: "Editar ações",
        nameLabel: "Nome",
        automaticLabel: "Automático",
        iconLabel: "Ícone",
        actionLabel: "Ação",
        kindApp: "Abrir um app",
        kindFile: "Abrir arquivo ou pasta",
        kindURL: "Abrir um link",
        kindShortcut: "Pressionar um atalho",
        kindTool: "Ferramenta do Vorssaint",
        kindMedia: "Controle de mídia",
        kindSubmenu: "Submenu",
        chooseButton: "Escolher…",
        urlPlaceholder: "exemplo.com",
        urlInvalid: "Digite um link válido.",
        toolLabel: "Ferramenta",
        mediaLabel: "Controle",
        mediaPlayPause: "Tocar ou pausar",
        mediaPrevious: "Faixa anterior",
        mediaNext: "Próxima faixa",
        mediaNowPlaying: "Reproduzindo agora",
        mediaNothingPlaying: "Nada em reprodução",
        mediaOpenAppFormat: "Abrir %@",
        submenuCaption: "Abre uma segunda roda com as próprias ações.",
        saveButton: "Salvar",
        deleteButton: "Remover",
        permissionCaption: "Ações de tecla e o gatilho pelo botão lateral exigem a permissão de Acessibilidade.",
        manageButton: "Gerenciar o menu",
        panelCaption: "Suas ações favoritas em uma roda",
        mouseTriggerLabel: "Botão do mouse",
        mouseTriggerOff: "Desligado",
        mouseTriggerBack: "Botão lateral de voltar",
        mouseTriggerForward: "Botão lateral de avançar",
        mouseTriggerWarning: "Enquanto isso está ligado, esse botão deixa de voltar ou avançar nos apps. Se você navega com ele, deixe desligado.",
        buttonTestLabel: "Teste do botão",
        buttonTestWaiting: "Aperte o botão agora",
        buttonTestSeen: "O Vorssaint enxerga esse botão",
        buttonTestOther: "Esse foi outro botão",
        buttonTestBlind: "O Vorssaint não consegue observar o mouse agora",
        buttonTestHint: "Se nada acender, o macOS não está entregando esse botão para os apps. Mouses que vêm com programa próprio costumam trocar os botões laterais por outra coisa. Volte lá e desfaça, ou dê uma combinação de teclas ao botão e use essa combinação acima.",
        activationModeLabel: "Comportamento de abertura",
        activationModePressOrHold: "Pressionar ou segurar",
        activationModePress: "Pressionar para abrir",
        activationModeHold: "Segurar para selecionar",
        activationModeCaption: "Pressionar ou segurar mantém o gesto adaptável atual. Pressionar deixa aberto; segurar executa a ação destacada ao soltar.",
        profilesHeader: "Perfis",
        profilePickerLabel: "Perfil",
        addProfileButton: "Adicionar perfil",
        duplicateProfileButton: "Duplicar perfil",
        deleteProfileButton: "Excluir perfil",
        profileNameLabel: "Nome do perfil",
        profileColorLabel: "Cor",
        profileShortcutLabel: "Atalho",
        profileMouseTriggerLabel: "Botão do mouse",
        presetGeneral: "Geral",
        presetMedia: "Mídia",
        presetTools: "Ferramentas",
        presetWindowLayout: "Organização de janelas",
        presetQuickToggles: "Atalhos rápidos",
        presetBlank: "Em branco",
        colorAccent: "Destaque",
        colorBlue: "Azul",
        colorPurple: "Roxo",
        colorPink: "Rosa",
        colorRed: "Vermelho",
        colorOrange: "Laranja",
        colorYellow: "Amarelo",
        colorGreen: "Verde",
        colorMint: "Menta",
        colorCyan: "Ciano",
        colorIndigo: "Índigo",
        colorGraphite: "Grafite",
        fetchFaviconButton: "Buscar ícone do site",
        fetchFaviconDisclaimer: "Conecta ao site uma única vez para baixar o ícone. Salvo localmente.",
        fetchFaviconLoading: "Buscando ícone…",
        fetchFaviconSuccess: "Ícone baixado",
        fetchFaviconError: "Não foi possível encontrar o ícone do site",
        mouseTriggerRequirement: "Só botões extras do mouse funcionam aqui. Com um trackpad ou um mouse sem botões extras, use o atalho de teclado acima.",
        canvasHint: "Clique em um botão para escolher sua ação ou removê-lo. Arraste para mover de lugar.",
        resetActionsButton: "Redefinir",
        resetActionsConfirm: "Redefinir ações",
        resetActionsConfirmMessage: "Restaurar as ações padrão deste perfil? As ações personalizadas serão substituídas.",
        showListButton: "Mostrar em lista",
        hideListButton: "Ocultar lista"
    )

    static let tr = RadialMenuFeatureStrings(
        pageTitle: "Dairesel menü",
        hubDescription: "İşaretçinin çevresinde en sevdiğiniz eylemlerden oluşan bir çark açar",
        enableLabel: "Dairesel menüyü kullan",
        enableCaption: "Kısayolu basılı tutun, bir eyleme yönelin ve bırakın. Kısa bir basış çarkı açık tutar.",
        positionLabel: "Açılış yeri",
        positionPointer: "İşaretçide",
        positionCenter: "Ekranın ortasında",
        tryButton: "Dene",
        actionsHeader: "Eylemler",
        addButton: "Eylem ekle",
        limitCaption: "Bir çark en fazla 12 eylem alır.",
        emptyCaption: "Burada henüz eylem yok.",
        backButton: "Geri",
        editActionsButton: "Eylemleri düzenle",
        nameLabel: "Ad",
        automaticLabel: "Otomatik",
        iconLabel: "Simge",
        actionLabel: "Eylem",
        kindApp: "Uygulama aç",
        kindFile: "Dosya veya klasör aç",
        kindURL: "Bağlantı aç",
        kindShortcut: "Kısayola bas",
        kindTool: "Vorssaint aracı",
        kindMedia: "Ortam denetimi",
        kindSubmenu: "Alt menü",
        chooseButton: "Seç…",
        urlPlaceholder: "ornek.com",
        urlInvalid: "Geçerli bir bağlantı girin.",
        toolLabel: "Araç",
        mediaLabel: "Denetim",
        mediaPlayPause: "Çal veya duraklat",
        mediaPrevious: "Önceki parça",
        mediaNext: "Sonraki parça",
        mediaNowPlaying: "Şu An Çalıyor",
        mediaNothingPlaying: "Şu anda çalan bir şey yok",
        mediaOpenAppFormat: "%@ uygulamasını aç",
        submenuCaption: "Kendi eylemleriyle ikinci bir çark açar.",
        saveButton: "Kaydet",
        deleteButton: "Kaldır",
        permissionCaption: "Tuş eylemleri ve yan düğme tetikleyicisi Erişilebilirlik iznini gerektirir.",
        manageButton: "Menüyü yönet",
        panelCaption: "En sevdiğiniz eylemler bir çarkta",
        mouseTriggerLabel: "Fare düğmesi",
        mouseTriggerOff: "Kapalı",
        mouseTriggerBack: "Geri yan düğmesi",
        mouseTriggerForward: "İleri yan düğmesi",
        mouseTriggerWarning: "Bu açıkken o düğme uygulamalarda artık geri veya ileri gitmez. Onunla geziniyorsanız kapalı bırakın.",
        buttonTestLabel: "Düğme testi",
        buttonTestWaiting: "Şimdi düğmeye basın",
        buttonTestSeen: "Vorssaint bu düğmeyi görüyor",
        buttonTestOther: "Bu başka bir düğmeydi",
        buttonTestBlind: "Vorssaint şu anda fareyi izleyemiyor",
        buttonTestHint: "Hiçbir şey yanmıyorsa macOS o düğmeyi uygulamalara iletmiyordur. Kendi yazılımıyla gelen fareler yan düğmeleri çoğu zaman başka bir şeye çevirir. Oradan geri alın veya düğmeye bir tuş birleşimi verip o birleşimi yukarıda kullanın.",
        activationModeLabel: "Açılma davranışı",
        activationModePressOrHold: "Bas veya basılı tut",
        activationModePress: "Açmak için bas",
        activationModeHold: "Seçmek için basılı tut",
        activationModeCaption: "Bas veya basılı tut mevcut uyarlanabilir hareketi korur. Bas modu açık kalır; basılı tutma modu bırakınca vurgulanan eylemi çalıştırır.",
        profilesHeader: "Profiller",
        profilePickerLabel: "Profil",
        addProfileButton: "Profil ekle",
        duplicateProfileButton: "Profili çoğalt",
        deleteProfileButton: "Profili sil",
        profileNameLabel: "Profil adı",
        profileColorLabel: "Renk",
        profileShortcutLabel: "Kısayol",
        profileMouseTriggerLabel: "Fare düğmesi",
        presetGeneral: "Genel",
        presetMedia: "Ortam",
        presetTools: "Araçlar",
        presetWindowLayout: "Pencere düzeni",
        presetQuickToggles: "Hızlı geçişler",
        presetBlank: "Boş",
        colorAccent: "Vurgu",
        colorBlue: "Mavi",
        colorPurple: "Mor",
        colorPink: "Pembe",
        colorRed: "Kırmızı",
        colorOrange: "Turuncu",
        colorYellow: "Sarı",
        colorGreen: "Yeşil",
        colorMint: "Nane",
        colorCyan: "Camgöbeği",
        colorIndigo: "Çivit",
        colorGraphite: "Grafit",
        fetchFaviconButton: "Web Sitesi Simgesini Getir",
        fetchFaviconDisclaimer: "Simgeyi indirmek için web sitesine bir kez bağlanır. Yerel olarak kaydedilir.",
        fetchFaviconLoading: "Simge getiriliyor…",
        fetchFaviconSuccess: "Simge indirildi",
        fetchFaviconError: "Web sitesi simgesi bulunamadı",
        mouseTriggerRequirement: "Burada yalnızca ek fare düğmeleri çalışır. İzleme dörtgeni veya ek düğmesi olmayan bir fareyle yukarıdaki klavye kestirmesini kullanın.",
        canvasHint: "Başlatacağı eylemi seçmek veya kaldırmak için bir düğmeye tıklayın. Taşımak için sürükleyin.",
        resetActionsButton: "Sıfırla",
        resetActionsConfirm: "Eylemleri sıfırla",
        resetActionsConfirmMessage: "Bu profil için saptanmış eylemler geri yüklensin mi? Özel eylemler değiştirilecek.",
        showListButton: "Liste olarak göster",
        hideListButton: "Listeyi gizle"
    )

    static let ru = RadialMenuFeatureStrings(
        pageTitle: "Радиальное меню",
        hubDescription: "Открывает колесо с любимыми действиями вокруг указателя",
        enableLabel: "Использовать радиальное меню",
        enableCaption: "Удерживайте сочетание, наведите на действие и отпустите. Короткое нажатие оставляет колесо открытым.",
        positionLabel: "Открывается",
        positionPointer: "У указателя",
        positionCenter: "В центре экрана",
        tryButton: "Попробовать",
        actionsHeader: "Действия",
        addButton: "Добавить действие",
        limitCaption: "Колесо вмещает до 12 действий.",
        emptyCaption: "Здесь пока нет действий.",
        backButton: "Назад",
        editActionsButton: "Изменить действия",
        nameLabel: "Название",
        automaticLabel: "Автоматически",
        iconLabel: "Значок",
        actionLabel: "Действие",
        kindApp: "Открыть приложение",
        kindFile: "Открыть файл или папку",
        kindURL: "Открыть ссылку",
        kindShortcut: "Нажать сочетание клавиш",
        kindTool: "Инструмент Vorssaint",
        kindMedia: "Управление медиа",
        kindSubmenu: "Подменю",
        chooseButton: "Выбрать…",
        urlPlaceholder: "example.com",
        urlInvalid: "Введите действительную ссылку.",
        toolLabel: "Инструмент",
        mediaLabel: "Управление",
        mediaPlayPause: "Воспроизведение или пауза",
        mediaPrevious: "Предыдущий трек",
        mediaNext: "Следующий трек",
        mediaNowPlaying: "Сейчас играет",
        mediaNothingPlaying: "Сейчас ничего не играет",
        mediaOpenAppFormat: "Открыть %@",
        submenuCaption: "Открывает второе колесо с собственными действиями.",
        saveButton: "Сохранить",
        deleteButton: "Удалить",
        permissionCaption: "Действиям с клавишами и запуску боковой кнопкой нужно разрешение «Универсальный доступ».",
        manageButton: "Настроить меню",
        panelCaption: "Любимые действия на одном колесе",
        mouseTriggerLabel: "Кнопка мыши",
        mouseTriggerOff: "Выключено",
        mouseTriggerBack: "Боковая кнопка «Назад»",
        mouseTriggerForward: "Боковая кнопка «Вперёд»",
        mouseTriggerWarning: "Пока это включено, кнопка перестаёт работать как «Назад» и «Вперёд» в приложениях. Если вы так переходите по страницам, оставьте выключенным.",
        buttonTestLabel: "Проверка кнопки",
        buttonTestWaiting: "Нажмите кнопку сейчас",
        buttonTestSeen: "Vorssaint видит эту кнопку",
        buttonTestOther: "Это была другая кнопка",
        buttonTestBlind: "Vorssaint сейчас не может следить за мышью",
        buttonTestHint: "Если ничего не загорается, macOS не передаёт эту кнопку приложениям. Мыши со своей программой часто заменяют боковые кнопки чем-то другим. Верните там как было или назначьте кнопке сочетание клавиш и используйте его выше.",
        activationModeLabel: "Способ открытия",
        activationModePressOrHold: "Нажать или удерживать",
        activationModePress: "Нажать, чтобы открыть",
        activationModeHold: "Удерживать для выбора",
        activationModeCaption: "Первый режим сохраняет текущее адаптивное поведение. Нажатие оставляет меню открытым; удержание запускает выделенное действие при отпускании.",
        profilesHeader: "Профили",
        profilePickerLabel: "Профиль",
        addProfileButton: "Добавить профиль",
        duplicateProfileButton: "Дублировать профиль",
        deleteProfileButton: "Удалить профиль",
        profileNameLabel: "Название профиля",
        profileColorLabel: "Цвет",
        profileShortcutLabel: "Сочетание клавиш",
        profileMouseTriggerLabel: "Кнопка мыши",
        presetGeneral: "Основной",
        presetMedia: "Медиа",
        presetTools: "Инструменты",
        presetWindowLayout: "Разметка окон",
        presetQuickToggles: "Быстрые переключатели",
        presetBlank: "Пустой",
        colorAccent: "Акцент",
        colorBlue: "Синий",
        colorPurple: "Фиолетовый",
        colorPink: "Розовый",
        colorRed: "Красный",
        colorOrange: "Оранжевый",
        colorYellow: "Жёлтый",
        colorGreen: "Зелёный",
        colorMint: "Мятный",
        colorCyan: "Голубой",
        colorIndigo: "Индиго",
        colorGraphite: "Графит",
        fetchFaviconButton: "Загрузить значок сайта",
        fetchFaviconDisclaimer: "Подключается к сайту один раз для загрузки значка. Сохраняется локально.",
        fetchFaviconLoading: "Загрузка значка…",
        fetchFaviconSuccess: "Значок загружен",
        fetchFaviconError: "Не удалось найти значок сайта",
        mouseTriggerRequirement: "Здесь работают только дополнительные кнопки мыши. С трекпадом или мышью без дополнительных кнопок используйте сочетание клавиш выше.",
        canvasHint: "Нажмите кнопку, чтобы настроить или удалить действие. Перетащите, чтобы переместить.",
        resetActionsButton: "Сбросить",
        resetActionsConfirm: "Сбросить действия",
        resetActionsConfirmMessage: "Восстановить действия по умолчанию для этого профиля? Пользовательские действия будут заменены.",
        showListButton: "Показать списком",
        hideListButton: "Скрыть список"
    )

    static let es = RadialMenuFeatureStrings(
        pageTitle: "Menú radial",
        hubDescription: "Abre una rueda con tus acciones favoritas alrededor del puntero",
        enableLabel: "Usar el menú radial",
        enableCaption: "Mantén pulsado el atajo, apunta a una acción y suelta. Una pulsación breve deja la rueda abierta.",
        positionLabel: "Se abre",
        positionPointer: "En el puntero",
        positionCenter: "En el centro de la pantalla",
        tryButton: "Probar",
        actionsHeader: "Acciones",
        addButton: "Añadir acción",
        limitCaption: "Una rueda admite hasta 12 acciones.",
        emptyCaption: "Aún no hay acciones aquí.",
        backButton: "Atrás",
        editActionsButton: "Editar acciones",
        nameLabel: "Nombre",
        automaticLabel: "Automático",
        iconLabel: "Icono",
        actionLabel: "Acción",
        kindApp: "Abrir una app",
        kindFile: "Abrir un archivo o carpeta",
        kindURL: "Abrir un enlace",
        kindShortcut: "Pulsar un atajo",
        kindTool: "Herramienta de Vorssaint",
        kindMedia: "Control multimedia",
        kindSubmenu: "Submenú",
        chooseButton: "Elegir…",
        urlPlaceholder: "ejemplo.com",
        urlInvalid: "Introduce un enlace válido.",
        toolLabel: "Herramienta",
        mediaLabel: "Control",
        mediaPlayPause: "Reproducir o pausar",
        mediaPrevious: "Pista anterior",
        mediaNext: "Siguiente pista",
        mediaNowPlaying: "Reproduciendo ahora",
        mediaNothingPlaying: "Nada reproduciéndose",
        mediaOpenAppFormat: "Abrir %@",
        submenuCaption: "Abre una segunda rueda con sus propias acciones.",
        saveButton: "Guardar",
        deleteButton: "Eliminar",
        permissionCaption: "Las acciones de teclas y el botón lateral necesitan el permiso de Accesibilidad.",
        manageButton: "Gestionar el menú",
        panelCaption: "Tus acciones favoritas en una rueda",
        mouseTriggerLabel: "Botón del ratón",
        mouseTriggerOff: "Desactivado",
        mouseTriggerBack: "Botón lateral de retroceso",
        mouseTriggerForward: "Botón lateral de avance",
        mouseTriggerWarning: "Mientras esté activado, ese botón deja de ir atrás o adelante en las apps. Si navegas con él, déjalo desactivado.",
        buttonTestLabel: "Prueba del botón",
        buttonTestWaiting: "Pulsa el botón ahora",
        buttonTestSeen: "Vorssaint ve este botón",
        buttonTestOther: "Ese fue otro botón",
        buttonTestBlind: "Vorssaint no puede observar el ratón ahora",
        buttonTestHint: "Si no se enciende nada, macOS no está enviando ese botón a las apps. Los ratones que traen su propio programa suelen convertir los botones laterales en otra cosa. Deshazlo allí, o dale una combinación de teclas al botón y usa esa combinación arriba.",
        activationModeLabel: "Comportamiento de apertura",
        activationModePressOrHold: "Pulsar o mantener",
        activationModePress: "Pulsar para abrir",
        activationModeHold: "Mantener para seleccionar",
        activationModeCaption: "Pulsar o mantener conserva el gesto adaptable actual. Pulsar deja el menú abierto; mantener ejecuta la acción resaltada al soltar.",
        profilesHeader: "Perfiles",
        profilePickerLabel: "Perfil",
        addProfileButton: "Añadir perfil",
        duplicateProfileButton: "Duplicar perfil",
        deleteProfileButton: "Eliminar perfil",
        profileNameLabel: "Nombre del perfil",
        profileColorLabel: "Color",
        profileShortcutLabel: "Atajo",
        profileMouseTriggerLabel: "Botón del ratón",
        presetGeneral: "General",
        presetMedia: "Multimedia",
        presetTools: "Herramientas",
        presetWindowLayout: "Organización de ventanas",
        presetQuickToggles: "Ajustes rápidos",
        presetBlank: "En blanco",
        colorAccent: "Realce",
        colorBlue: "Azul",
        colorPurple: "Morado",
        colorPink: "Rosa",
        colorRed: "Rojo",
        colorOrange: "Naranja",
        colorYellow: "Amarillo",
        colorGreen: "Verde",
        colorMint: "Menta",
        colorCyan: "Cian",
        colorIndigo: "Índigo",
        colorGraphite: "Grafito",
        fetchFaviconButton: "Obtener icono del sitio web",
        fetchFaviconDisclaimer: "Se conecta al sitio web una sola vez para descargar el icono. Guardado localmente.",
        fetchFaviconLoading: "Obteniendo icono…",
        fetchFaviconSuccess: "Icono descargado",
        fetchFaviconError: "No se pudo encontrar el icono del sitio web",
        mouseTriggerRequirement: "Aquí solo funcionan los botones adicionales del ratón. Con un trackpad o un ratón sin botones adicionales, usa el atajo de teclado de arriba.",
        canvasHint: "Haz clic en un botón para elegir su acción o eliminarlo. Arrastra para moverlo.",
        resetActionsButton: "Restablecer",
        resetActionsConfirm: "Restablecer acciones",
        resetActionsConfirmMessage: "¿Restaurar las acciones predeterminadas de este perfil? Se reemplazarán las acciones personalizadas.",
        showListButton: "Mostrar como lista",
        hideListButton: "Ocultar lista"
    )

    static let de = RadialMenuFeatureStrings(
        pageTitle: "Radialmenü",
        hubDescription: "Öffnet ein Rad mit deinen Lieblingsaktionen rund um den Zeiger",
        enableLabel: "Radialmenü verwenden",
        enableCaption: "Kurzbefehl gedrückt halten, auf eine Aktion zeigen und loslassen. Ein kurzer Druck hält das Rad offen.",
        positionLabel: "Öffnet sich",
        positionPointer: "Am Zeiger",
        positionCenter: "In der Bildschirmmitte",
        tryButton: "Ausprobieren",
        actionsHeader: "Aktionen",
        addButton: "Aktion hinzufügen",
        limitCaption: "Ein Rad fasst bis zu 12 Aktionen.",
        emptyCaption: "Hier gibt es noch keine Aktionen.",
        backButton: "Zurück",
        editActionsButton: "Aktionen bearbeiten",
        nameLabel: "Name",
        automaticLabel: "Automatisch",
        iconLabel: "Symbol",
        actionLabel: "Aktion",
        kindApp: "App öffnen",
        kindFile: "Datei oder Ordner öffnen",
        kindURL: "Link öffnen",
        kindShortcut: "Kurzbefehl drücken",
        kindTool: "Vorssaint-Werkzeug",
        kindMedia: "Mediensteuerung",
        kindSubmenu: "Untermenü",
        chooseButton: "Auswählen…",
        urlPlaceholder: "beispiel.de",
        urlInvalid: "Gib einen gültigen Link ein.",
        toolLabel: "Werkzeug",
        mediaLabel: "Steuerung",
        mediaPlayPause: "Wiedergabe oder Pause",
        mediaPrevious: "Vorheriger Titel",
        mediaNext: "Nächster Titel",
        mediaNowPlaying: "Aktuelle Wiedergabe",
        mediaNothingPlaying: "Keine Wiedergabe",
        mediaOpenAppFormat: "%@ öffnen",
        submenuCaption: "Öffnet ein zweites Rad mit eigenen Aktionen.",
        saveButton: "Sichern",
        deleteButton: "Entfernen",
        permissionCaption: "Tastenaktionen und die seitliche Maustaste brauchen die Berechtigung für Bedienungshilfen.",
        manageButton: "Menü verwalten",
        panelCaption: "Deine Lieblingsaktionen auf einem Rad",
        mouseTriggerLabel: "Maustaste",
        mouseTriggerOff: "Aus",
        mouseTriggerBack: "Seitliche Zurück-Taste",
        mouseTriggerForward: "Seitliche Vorwärts-Taste",
        mouseTriggerWarning: "Solange das aktiv ist, geht die Taste in Apps nicht mehr zurück oder vor. Wer damit navigiert, lässt es besser aus.",
        buttonTestLabel: "Tastentest",
        buttonTestWaiting: "Jetzt die Taste drücken",
        buttonTestSeen: "Vorssaint sieht diese Taste",
        buttonTestOther: "Das war eine andere Taste",
        buttonTestBlind: "Vorssaint kann die Maus gerade nicht beobachten",
        buttonTestHint: "Leuchtet nichts auf, gibt macOS diese Taste nicht an Apps weiter. Mäuse mit eigener Software belegen die Seitentasten oft anders. Dort zurückstellen, oder der Taste eine Tastenkombination geben und diese oben verwenden.",
        activationModeLabel: "Öffnungsverhalten",
        activationModePressOrHold: "Drücken oder halten",
        activationModePress: "Zum Öffnen drücken",
        activationModeHold: "Zum Auswählen halten",
        activationModeCaption: "Drücken oder halten behält die bisherige adaptive Geste bei. Drücken lässt das Rad offen; Halten führt beim Loslassen die markierte Aktion aus.",
        profilesHeader: "Profile",
        profilePickerLabel: "Profil",
        addProfileButton: "Profil hinzufügen",
        duplicateProfileButton: "Profil duplizieren",
        deleteProfileButton: "Profil löschen",
        profileNameLabel: "Profilname",
        profileColorLabel: "Farbe",
        profileShortcutLabel: "Kurzbefehl",
        profileMouseTriggerLabel: "Maustaste",
        presetGeneral: "Allgemein",
        presetMedia: "Medien",
        presetTools: "Werkzeuge",
        presetWindowLayout: "Fensteranordnung",
        presetQuickToggles: "Schnellschalter",
        presetBlank: "Leer",
        colorAccent: "Akzent",
        colorBlue: "Blau",
        colorPurple: "Lila",
        colorPink: "Rosa",
        colorRed: "Rot",
        colorOrange: "Orange",
        colorYellow: "Gelb",
        colorGreen: "Grün",
        colorMint: "Minze",
        colorCyan: "Cyan",
        colorIndigo: "Indigo",
        colorGraphite: "Graphit",
        fetchFaviconButton: "Website-Icon laden",
        fetchFaviconDisclaimer: "Verbindet sich einmal mit der Website, um das Icon zu laden. Lokal gespeichert.",
        fetchFaviconLoading: "Icon wird geladen…",
        fetchFaviconSuccess: "Icon heruntergeladen",
        fetchFaviconError: "Website-Icon konnte nicht gefunden werden",
        mouseTriggerRequirement: "Hier funktionieren nur zusätzliche Maustasten. Verwende mit einem Trackpad oder einer Maus ohne zusätzliche Tasten den Tastaturkurzbefehl oben.",
        canvasHint: "Klicke auf eine Taste, um die Aktion festzulegen oder sie zu entfernen. Ziehe zum Verschieben.",
        resetActionsButton: "Zurücksetzen",
        resetActionsConfirm: "Aktionen zurücksetzen",
        resetActionsConfirmMessage: "Standardaktionen für dieses Profil wiederherstellen? Eigene Aktionen werden ersetzt.",
        showListButton: "Als Liste anzeigen",
        hideListButton: "Liste ausblenden"
    )

    static let fr = RadialMenuFeatureStrings(
        pageTitle: "Menu radial",
        hubDescription: "Ouvre une roue avec vos actions préférées autour du pointeur",
        enableLabel: "Utiliser le menu radial",
        enableCaption: "Maintenez le raccourci, visez une action et relâchez. Un appui bref garde la roue ouverte.",
        positionLabel: "S’ouvre",
        positionPointer: "Au pointeur",
        positionCenter: "Au centre de l’écran",
        tryButton: "Essayer",
        actionsHeader: "Actions",
        addButton: "Ajouter une action",
        limitCaption: "Une roue contient jusqu’à 12 actions.",
        emptyCaption: "Aucune action ici pour le moment.",
        backButton: "Retour",
        editActionsButton: "Modifier les actions",
        nameLabel: "Nom",
        automaticLabel: "Automatique",
        iconLabel: "Icône",
        actionLabel: "Action",
        kindApp: "Ouvrir une app",
        kindFile: "Ouvrir un fichier ou un dossier",
        kindURL: "Ouvrir un lien",
        kindShortcut: "Appuyer sur un raccourci",
        kindTool: "Outil Vorssaint",
        kindMedia: "Contrôle multimédia",
        kindSubmenu: "Sous-menu",
        chooseButton: "Choisir…",
        urlPlaceholder: "exemple.fr",
        urlInvalid: "Saisissez un lien valide.",
        toolLabel: "Outil",
        mediaLabel: "Contrôle",
        mediaPlayPause: "Lecture ou pause",
        mediaPrevious: "Piste précédente",
        mediaNext: "Piste suivante",
        mediaNowPlaying: "À l’écoute",
        mediaNothingPlaying: "Aucune lecture",
        mediaOpenAppFormat: "Ouvrir %@",
        submenuCaption: "Ouvre une seconde roue avec ses propres actions.",
        saveButton: "Enregistrer",
        deleteButton: "Supprimer",
        permissionCaption: "Les actions de touches et le bouton latéral demandent l’autorisation Accessibilité.",
        manageButton: "Gérer le menu",
        panelCaption: "Vos actions préférées sur une roue",
        mouseTriggerLabel: "Bouton de la souris",
        mouseTriggerOff: "Désactivé",
        mouseTriggerBack: "Bouton latéral précédent",
        mouseTriggerForward: "Bouton latéral suivant",
        mouseTriggerWarning: "Tant que c’est activé, ce bouton ne fait plus précédent ou suivant dans les apps. Si vous naviguez avec, laissez désactivé.",
        buttonTestLabel: "Test du bouton",
        buttonTestWaiting: "Appuyez sur le bouton",
        buttonTestSeen: "Vorssaint voit ce bouton",
        buttonTestOther: "C’était un autre bouton",
        buttonTestBlind: "Vorssaint ne peut pas observer la souris pour le moment",
        buttonTestHint: "Si rien ne s’allume, macOS ne transmet pas ce bouton aux apps. Les souris livrées avec leur propre logiciel changent souvent les boutons latéraux. Rétablissez-le là-bas, ou donnez une combinaison de touches au bouton et utilisez cette combinaison ci-dessus.",
        activationModeLabel: "Comportement d’ouverture",
        activationModePressOrHold: "Appuyer ou maintenir",
        activationModePress: "Appuyer pour ouvrir",
        activationModeHold: "Maintenir pour choisir",
        activationModeCaption: "Appuyer ou maintenir conserve le geste adaptatif actuel. Appuyer laisse la roue ouverte\u{00A0}; maintenir lance l’action surlignée au relâchement.",
        profilesHeader: "Profils",
        profilePickerLabel: "Profil",
        addProfileButton: "Ajouter un profil",
        duplicateProfileButton: "Dupliquer le profil",
        deleteProfileButton: "Supprimer le profil",
        profileNameLabel: "Nom du profil",
        profileColorLabel: "Couleur",
        profileShortcutLabel: "Raccourci",
        profileMouseTriggerLabel: "Bouton de la souris",
        presetGeneral: "Général",
        presetMedia: "Médias",
        presetTools: "Outils",
        presetWindowLayout: "Disposition des fenêtres",
        presetQuickToggles: "Boutons rapides",
        presetBlank: "Vierge",
        colorAccent: "Accent",
        colorBlue: "Bleu",
        colorPurple: "Violet",
        colorPink: "Rose",
        colorRed: "Rouge",
        colorOrange: "Orange",
        colorYellow: "Jaune",
        colorGreen: "Vert",
        colorMint: "Menthe",
        colorCyan: "Cyan",
        colorIndigo: "Indigo",
        colorGraphite: "Graphite",
        fetchFaviconButton: "Récupérer l’icône du site",
        fetchFaviconDisclaimer: "Se connecte au site web une seule fois pour télécharger l’icône. Enregistrée localement.",
        fetchFaviconLoading: "Récupération de l’icône…",
        fetchFaviconSuccess: "Icône téléchargée",
        fetchFaviconError: "Impossible de trouver l’icône du site web",
        mouseTriggerRequirement: "Seuls les boutons supplémentaires de la souris fonctionnent ici. Avec un trackpad ou une souris sans boutons supplémentaires, utilisez le raccourci clavier ci-dessus.",
        canvasHint: "Cliquez sur un bouton pour choisir son action ou le retirer. Faites glisser pour le déplacer.",
        resetActionsButton: "Réinitialiser",
        resetActionsConfirm: "Réinitialiser les actions",
        resetActionsConfirmMessage: "Restaurer les actions par défaut de ce profil\u{00A0}? Les actions personnalisées seront remplacées.",
        showListButton: "Afficher sous forme de liste",
        hideListButton: "Masquer la liste"
    )

    static let it = RadialMenuFeatureStrings(
        pageTitle: "Menu radiale",
        hubDescription: "Apre una ruota con le tue azioni preferite attorno al puntatore",
        enableLabel: "Usa il menu radiale",
        enableCaption: "Tieni premuta l’abbreviazione, punta un’azione e rilascia. Una pressione breve lascia la ruota aperta.",
        positionLabel: "Si apre",
        positionPointer: "Sul puntatore",
        positionCenter: "Al centro dello schermo",
        tryButton: "Prova",
        actionsHeader: "Azioni",
        addButton: "Aggiungi azione",
        limitCaption: "Una ruota contiene fino a 12 azioni.",
        emptyCaption: "Qui non ci sono ancora azioni.",
        backButton: "Indietro",
        editActionsButton: "Modifica azioni",
        nameLabel: "Nome",
        automaticLabel: "Automatico",
        iconLabel: "Icona",
        actionLabel: "Azione",
        kindApp: "Apri un’app",
        kindFile: "Apri un file o una cartella",
        kindURL: "Apri un link",
        kindShortcut: "Premi un’abbreviazione",
        kindTool: "Strumento Vorssaint",
        kindMedia: "Controllo multimediale",
        kindSubmenu: "Sottomenu",
        chooseButton: "Scegli…",
        urlPlaceholder: "esempio.it",
        urlInvalid: "Inserisci un link valido.",
        toolLabel: "Strumento",
        mediaLabel: "Controllo",
        mediaPlayPause: "Riproduci o metti in pausa",
        mediaPrevious: "Brano precedente",
        mediaNext: "Brano successivo",
        mediaNowPlaying: "In riproduzione",
        mediaNothingPlaying: "Nessuna riproduzione",
        mediaOpenAppFormat: "Apri %@",
        submenuCaption: "Apre una seconda ruota con le proprie azioni.",
        saveButton: "Salva",
        deleteButton: "Rimuovi",
        permissionCaption: "Le azioni con i tasti e il pulsante laterale richiedono il permesso Accessibilità.",
        manageButton: "Gestisci il menu",
        panelCaption: "Le tue azioni preferite su una ruota",
        mouseTriggerLabel: "Pulsante del mouse",
        mouseTriggerOff: "Disattivato",
        mouseTriggerBack: "Pulsante laterale indietro",
        mouseTriggerForward: "Pulsante laterale avanti",
        mouseTriggerWarning: "Finché è attivo, quel pulsante non va più indietro o avanti nelle app. Se lo usi per navigare, lascialo disattivato.",
        buttonTestLabel: "Prova del pulsante",
        buttonTestWaiting: "Premi ora il pulsante",
        buttonTestSeen: "Vorssaint vede questo pulsante",
        buttonTestOther: "Quello era un altro pulsante",
        buttonTestBlind: "Vorssaint non riesce a osservare il mouse in questo momento",
        buttonTestHint: "Se non si accende nulla, macOS non sta passando quel pulsante alle app. I mouse che arrivano con un programma proprio spesso trasformano i pulsanti laterali in altro. Rimettilo com’era da lì, oppure assegna al pulsante una combinazione di tasti e usa quella combinazione qui sopra.",
        activationModeLabel: "Comportamento di apertura",
        activationModePressOrHold: "Premi o tieni premuto",
        activationModePress: "Premi per aprire",
        activationModeHold: "Tieni premuto per scegliere",
        activationModeCaption: "Premi o tieni premuto conserva il gesto adattivo attuale. Premi lascia aperta la ruota; tieni premuto esegue l’azione evidenziata al rilascio.",
        profilesHeader: "Profili",
        profilePickerLabel: "Profilo",
        addProfileButton: "Aggiungi profilo",
        duplicateProfileButton: "Duplica profilo",
        deleteProfileButton: "Elimina profilo",
        profileNameLabel: "Nome del profilo",
        profileColorLabel: "Colore",
        profileShortcutLabel: "Abbreviazione",
        profileMouseTriggerLabel: "Pulsante del mouse",
        presetGeneral: "Generale",
        presetMedia: "File multimediali",
        presetTools: "Strumenti",
        presetWindowLayout: "Disposizione finestre",
        presetQuickToggles: "Interruttori rapidi",
        presetBlank: "Vuoto",
        colorAccent: "Accento",
        colorBlue: "Blu",
        colorPurple: "Viola",
        colorPink: "Rosa",
        colorRed: "Rosso",
        colorOrange: "Arancione",
        colorYellow: "Giallo",
        colorGreen: "Verde",
        colorMint: "Menta",
        colorCyan: "Ciano",
        colorIndigo: "Indaco",
        colorGraphite: "Grafite",
        fetchFaviconButton: "Scarica icona del sito",
        fetchFaviconDisclaimer: "Si connette al sito una sola volta per scaricare l’icona. Salvata localmente.",
        fetchFaviconLoading: "Scaricamento icona…",
        fetchFaviconSuccess: "Icona scaricata",
        fetchFaviconError: "Impossibile trovare l’icona del sito",
        mouseTriggerRequirement: "Qui funzionano solo i pulsanti aggiuntivi del mouse. Con un trackpad o un mouse senza pulsanti aggiuntivi, usa l’abbreviazione da tastiera qui sopra.",
        canvasHint: "Fai clic su un pulsante per sceglierne l’azione o rimuoverlo. Trascina per spostarlo.",
        resetActionsButton: "Ripristina",
        resetActionsConfirm: "Ripristina azioni",
        resetActionsConfirmMessage: "Ripristinare le azioni predefinite per questo profilo? Le azioni personalizzate verranno sostituite.",
        showListButton: "Mostra come elenco",
        hideListButton: "Nascondi elenco"
    )

    static let ja = RadialMenuFeatureStrings(
        pageTitle: "ラジアルメニュー",
        hubDescription: "ポインタの周りにお気に入りのアクションのホイールを開きます",
        enableLabel: "ラジアルメニューを使用",
        enableCaption: "ショートカットを押したまま、アクションに向けて放します。短く押すとホイールが開いたままになります。",
        positionLabel: "表示位置",
        positionPointer: "ポインタの位置",
        positionCenter: "画面の中央",
        tryButton: "試す",
        actionsHeader: "アクション",
        addButton: "アクションを追加",
        limitCaption: "1つのホイールには最大12個のアクションを置けます。",
        emptyCaption: "ここにはまだアクションがありません。",
        backButton: "戻る",
        editActionsButton: "アクションを編集",
        nameLabel: "名前",
        automaticLabel: "自動",
        iconLabel: "アイコン",
        actionLabel: "アクション",
        kindApp: "アプリを開く",
        kindFile: "ファイルまたはフォルダを開く",
        kindURL: "リンクを開く",
        kindShortcut: "ショートカットを押す",
        kindTool: "Vorssaintのツール",
        kindMedia: "メディアコントロール",
        kindSubmenu: "サブメニュー",
        chooseButton: "選択…",
        urlPlaceholder: "example.jp",
        urlInvalid: "有効なリンクを入力してください。",
        toolLabel: "ツール",
        mediaLabel: "コントロール",
        mediaPlayPause: "再生または一時停止",
        mediaPrevious: "前の曲",
        mediaNext: "次の曲",
        mediaNowPlaying: "再生中",
        mediaNothingPlaying: "再生中の項目はありません",
        mediaOpenAppFormat: "%@を開く",
        submenuCaption: "独自のアクションを持つ2つ目のホイールを開きます。",
        saveButton: "保存",
        deleteButton: "削除",
        permissionCaption: "キー操作とサイドボタンでの呼び出しには、アクセシビリティの許可が必要です。",
        manageButton: "メニューを管理",
        panelCaption: "お気に入りのアクションをホイールに",
        mouseTriggerLabel: "マウスボタン",
        mouseTriggerOff: "オフ",
        mouseTriggerBack: "サイドの「戻る」ボタン",
        mouseTriggerForward: "サイドの「進む」ボタン",
        mouseTriggerWarning: "オンの間、そのボタンではアプリ内で戻る/進むができなくなります。ナビゲーションに使っている場合はオフのままにしてください。",
        buttonTestLabel: "ボタンのテスト",
        buttonTestWaiting: "いまボタンを押してください",
        buttonTestSeen: "Vorssaint はこのボタンを認識しています",
        buttonTestOther: "いまのは別のボタンです",
        buttonTestBlind: "Vorssaint はいまマウスを見られません",
        buttonTestHint: "何も光らない場合、macOS がそのボタンをアプリに渡していません。専用ソフトが付属するマウスは、サイドボタンを別の動作に置き換えていることがよくあります。そちらで元に戻すか、ボタンにキーの組み合わせを割り当てて、その組み合わせを上で使ってください。",
        activationModeLabel: "開き方",
        activationModePressOrHold: "押す／長押し",
        activationModePress: "押して開く",
        activationModeHold: "長押しで選択",
        activationModeCaption: "押す／長押しは現在の自動ジェスチャーを維持します。押すモードは開いたまま、長押しモードは放したときに強調中の操作を実行します。",
        profilesHeader: "プロファイル",
        profilePickerLabel: "プロファイル",
        addProfileButton: "プロファイルを追加",
        duplicateProfileButton: "プロファイルを複製",
        deleteProfileButton: "プロファイルを削除",
        profileNameLabel: "プロファイル名",
        profileColorLabel: "カラー",
        profileShortcutLabel: "ショートカット",
        profileMouseTriggerLabel: "マウスボタン",
        presetGeneral: "一般",
        presetMedia: "メディア",
        presetTools: "ツール",
        presetWindowLayout: "ウインドウ配置",
        presetQuickToggles: "クイック切り替え",
        presetBlank: "空白",
        colorAccent: "アクセント",
        colorBlue: "ブルー",
        colorPurple: "パープル",
        colorPink: "ピンク",
        colorRed: "レッド",
        colorOrange: "オレンジ",
        colorYellow: "イエロー",
        colorGreen: "グリーン",
        colorMint: "ミント",
        colorCyan: "シアン",
        colorIndigo: "インディゴ",
        colorGraphite: "グラファイト",
        fetchFaviconButton: "Webサイトのアイコンを取得",
        fetchFaviconDisclaimer: "アイコンをダウンロードするために1回だけWebサイトに接続します。ローカルに保存されます。",
        fetchFaviconLoading: "アイコンを取得中…",
        fetchFaviconSuccess: "アイコンをダウンロードしました",
        fetchFaviconError: "Webサイトのアイコンが見つかりませんでした",
        mouseTriggerRequirement: "ここではマウスの追加ボタンだけを使用できます。トラックパッドや追加ボタンのないマウスでは、上のキーボードショートカットを使用してください。",
        canvasHint: "ボタンをクリックして機能の選択や削除を行います。ドラッグして並べ替えます。",
        resetActionsButton: "リセット",
        resetActionsConfirm: "アクションをリセット",
        resetActionsConfirmMessage: "このプロファイルのデフォルトアクションに戻しますか？カスタムアクションは置き換えられます。",
        showListButton: "リストとして表示",
        hideListButton: "リストを非表示"
    )

    static let ko = RadialMenuFeatureStrings(
        pageTitle: "방사형 메뉴",
        hubDescription: "포인터 주위에 즐겨 쓰는 동작의 휠을 엽니다",
        enableLabel: "방사형 메뉴 사용",
        enableCaption: "단축키를 누른 채 동작을 향해 이동한 뒤 놓으세요. 짧게 누르면 휠이 열린 상태로 유지됩니다.",
        positionLabel: "열리는 위치",
        positionPointer: "포인터 위치",
        positionCenter: "화면 중앙",
        tryButton: "사용해 보기",
        actionsHeader: "동작",
        addButton: "동작 추가",
        limitCaption: "휠 하나에 최대 12개의 동작을 담을 수 있습니다.",
        emptyCaption: "아직 동작이 없습니다.",
        backButton: "뒤로",
        editActionsButton: "동작 편집",
        nameLabel: "이름",
        automaticLabel: "자동",
        iconLabel: "아이콘",
        actionLabel: "동작",
        kindApp: "앱 열기",
        kindFile: "파일 또는 폴더 열기",
        kindURL: "링크 열기",
        kindShortcut: "단축키 누르기",
        kindTool: "Vorssaint 도구",
        kindMedia: "미디어 제어",
        kindSubmenu: "하위 메뉴",
        chooseButton: "선택…",
        urlPlaceholder: "example.kr",
        urlInvalid: "올바른 링크를 입력하세요.",
        toolLabel: "도구",
        mediaLabel: "제어",
        mediaPlayPause: "재생 또는 일시 정지",
        mediaPrevious: "이전 트랙",
        mediaNext: "다음 트랙",
        mediaNowPlaying: "지금 재생 중",
        mediaNothingPlaying: "재생 중인 항목 없음",
        mediaOpenAppFormat: "%@ 열기",
        submenuCaption: "자체 동작을 가진 두 번째 휠을 엽니다.",
        saveButton: "저장",
        deleteButton: "제거",
        permissionCaption: "키 동작과 측면 버튼 호출에는 손쉬운 사용 권한이 필요합니다.",
        manageButton: "메뉴 관리",
        panelCaption: "즐겨 쓰는 동작을 휠 하나에",
        mouseTriggerLabel: "마우스 버튼",
        mouseTriggerOff: "끔",
        mouseTriggerBack: "뒤로 가기 측면 버튼",
        mouseTriggerForward: "앞으로 가기 측면 버튼",
        mouseTriggerWarning: "이 기능이 켜져 있는 동안 해당 버튼은 앱에서 뒤로/앞으로 이동하지 않습니다. 이 버튼으로 탐색한다면 꺼 두세요.",
        buttonTestLabel: "버튼 테스트",
        buttonTestWaiting: "지금 버튼을 눌러 보세요",
        buttonTestSeen: "Vorssaint가 이 버튼을 인식합니다",
        buttonTestOther: "방금 것은 다른 버튼입니다",
        buttonTestBlind: "지금은 Vorssaint가 마우스를 살펴볼 수 없습니다",
        buttonTestHint: "아무것도 켜지지 않으면 macOS가 그 버튼을 앱에 전달하지 않는 것입니다. 전용 프로그램이 함께 오는 마우스는 옆 버튼을 다른 동작으로 바꿔 두는 경우가 많습니다. 거기서 되돌리거나, 버튼에 키 조합을 지정하고 그 조합을 위에서 사용하세요.",
        activationModeLabel: "열기 동작",
        activationModePressOrHold: "누르기 또는 길게 누르기",
        activationModePress: "눌러서 열기",
        activationModeHold: "길게 눌러 선택",
        activationModeCaption: "누르기 또는 길게 누르기는 현재의 자동 제스처를 유지합니다. 누르기 모드는 열린 상태를 유지하고, 길게 누르기 모드는 놓을 때 강조된 동작을 실행합니다.",
        profilesHeader: "프로필",
        profilePickerLabel: "프로필",
        addProfileButton: "프로필 추가",
        duplicateProfileButton: "프로필 복제",
        deleteProfileButton: "프로필 삭제",
        profileNameLabel: "프로필 이름",
        profileColorLabel: "색상",
        profileShortcutLabel: "단축키",
        profileMouseTriggerLabel: "마우스 버튼",
        presetGeneral: "일반",
        presetMedia: "미디어",
        presetTools: "도구",
        presetWindowLayout: "윈도우 레이아웃",
        presetQuickToggles: "빠른 전환",
        presetBlank: "빈 프로필",
        colorAccent: "강조 색상",
        colorBlue: "파란색",
        colorPurple: "보라색",
        colorPink: "분홍색",
        colorRed: "빨간색",
        colorOrange: "주황색",
        colorYellow: "노란색",
        colorGreen: "초록색",
        colorMint: "민트색",
        colorCyan: "청록색",
        colorIndigo: "남색",
        colorGraphite: "흑연색",
        fetchFaviconButton: "웹사이트 아이콘 가져오기",
        fetchFaviconDisclaimer: "아이콘을 다운로드하기 위해 웹사이트에 한 번 연결합니다. 로컬에 저장됩니다.",
        fetchFaviconLoading: "아이콘 가져오는 중…",
        fetchFaviconSuccess: "아이콘 다운로드됨",
        fetchFaviconError: "웹사이트 아이콘을 찾을 수 없습니다",
        mouseTriggerRequirement: "여기서는 마우스의 추가 버튼만 사용할 수 있습니다. 트랙패드나 추가 버튼이 없는 마우스에서는 위의 키보드 단축키를 사용하세요.",
        canvasHint: "버튼을 클릭하여 동작을 선택하거나 제거할 수 있습니다. 드래그하여 위치를 이동하세요.",
        resetActionsButton: "재설정",
        resetActionsConfirm: "동작 재설정",
        resetActionsConfirmMessage: "이 프로필의 기본 동작을 복원할까요? 사용자 설정 동작이 대체됩니다.",
        showListButton: "목록으로 표시",
        hideListButton: "목록 숨기기"
    )

    static let zhHans = RadialMenuFeatureStrings(
        pageTitle: "径向菜单",
        hubDescription: "在指针周围打开一个由常用操作组成的转盘",
        enableLabel: "使用径向菜单",
        enableCaption: "按住快捷键，指向某个操作后松开。快速按一下可让转盘保持打开。",
        positionLabel: "打开位置",
        positionPointer: "指针处",
        positionCenter: "屏幕中央",
        tryButton: "试一试",
        actionsHeader: "操作",
        addButton: "添加操作",
        limitCaption: "一个转盘最多容纳 12 个操作。",
        emptyCaption: "这里还没有操作。",
        backButton: "返回",
        editActionsButton: "编辑操作",
        nameLabel: "名称",
        automaticLabel: "自动",
        iconLabel: "图标",
        actionLabel: "操作",
        kindApp: "打开 App",
        kindFile: "打开文件或文件夹",
        kindURL: "打开链接",
        kindShortcut: "按下快捷键",
        kindTool: "Vorssaint 工具",
        kindMedia: "媒体控制",
        kindSubmenu: "子菜单",
        chooseButton: "选择…",
        urlPlaceholder: "example.com",
        urlInvalid: "请输入有效的链接。",
        toolLabel: "工具",
        mediaLabel: "控制",
        mediaPlayPause: "播放或暂停",
        mediaPrevious: "上一首",
        mediaNext: "下一首",
        mediaNowPlaying: "正在播放",
        mediaNothingPlaying: "当前无播放内容",
        mediaOpenAppFormat: "打开 %@",
        submenuCaption: "打开带有自己操作的第二个转盘。",
        saveButton: "保存",
        deleteButton: "移除",
        permissionCaption: "按键操作和侧键呼出需要辅助功能权限。",
        manageButton: "管理菜单",
        panelCaption: "常用操作都在一个转盘上",
        mouseTriggerLabel: "鼠标按钮",
        mouseTriggerOff: "关闭",
        mouseTriggerBack: "侧面后退键",
        mouseTriggerForward: "侧面前进键",
        mouseTriggerWarning: "开启期间，该按钮在 App 里不再后退或前进。如果你用它来导航，请保持关闭。",
        buttonTestLabel: "按键测试",
        buttonTestWaiting: "现在按一下该按键",
        buttonTestSeen: "Vorssaint 能看到这个按键",
        buttonTestOther: "刚才是另一个按键",
        buttonTestBlind: "Vorssaint 现在无法观察鼠标",
        buttonTestHint: "如果没有任何反应，说明 macOS 没有把该按键交给 App。自带软件的鼠标常把侧键改成了别的功能。请到那边改回来，或者给该按键设置一个快捷键组合，然后在上面使用这个组合。",
        activationModeLabel: "打开方式",
        activationModePressOrHold: "按下或按住",
        activationModePress: "按下打开",
        activationModeHold: "按住选择",
        activationModeCaption: "按下或按住会保留当前的自适应手势。按下模式会保持打开；按住模式会在松开时执行高亮操作。",
        profilesHeader: "配置文件",
        profilePickerLabel: "配置",
        addProfileButton: "添加配置",
        duplicateProfileButton: "复制配置",
        deleteProfileButton: "删除配置",
        profileNameLabel: "配置名称",
        profileColorLabel: "颜色",
        profileShortcutLabel: "快捷键",
        profileMouseTriggerLabel: "鼠标按钮",
        presetGeneral: "通用",
        presetMedia: "媒体",
        presetTools: "工具",
        presetWindowLayout: "窗口布局",
        presetQuickToggles: "快捷开关",
        presetBlank: "空白",
        colorAccent: "强调色",
        colorBlue: "蓝色",
        colorPurple: "紫色",
        colorPink: "粉色",
        colorRed: "红色",
        colorOrange: "橙色",
        colorYellow: "黄色",
        colorGreen: "绿色",
        colorMint: "薄荷绿",
        colorCyan: "青色",
        colorIndigo: "靛蓝",
        colorGraphite: "石墨灰",
        fetchFaviconButton: "获取网站图标",
        fetchFaviconDisclaimer: "仅连接网站一次以下载图标。保存在本地。",
        fetchFaviconLoading: "正在获取图标…",
        fetchFaviconSuccess: "图标已下载",
        fetchFaviconError: "未找到网站图标",
        mouseTriggerRequirement: "这里仅支持鼠标的额外按键。使用触控板或没有额外按键的鼠标时，请使用上方的键盘快捷键。",
        canvasHint: "点按按钮以选择动作或将其移除。拖移即可调整位置。",
        resetActionsButton: "重置",
        resetActionsConfirm: "重置动作",
        resetActionsConfirmMessage: "恢复此描述文件的默认动作？自定义动作将被替换。",
        showListButton: "显示为列表",
        hideListButton: "隐藏列表"
    )

    static let zhTW = RadialMenuFeatureStrings(
        pageTitle: "放射狀選單",
        hubDescription: "在指標周圍打開一個由常用動作組成的轉盤",
        enableLabel: "使用放射狀選單",
        enableCaption: "按住快速鍵，指向某個動作後放開。快速按一下可讓轉盤保持開啟。",
        positionLabel: "開啟位置",
        positionPointer: "指標處",
        positionCenter: "螢幕中央",
        tryButton: "試試看",
        actionsHeader: "動作",
        addButton: "加入動作",
        limitCaption: "一個轉盤最多容納 12 個動作。",
        emptyCaption: "這裡還沒有動作。",
        backButton: "返回",
        editActionsButton: "編輯動作",
        nameLabel: "名稱",
        automaticLabel: "自動",
        iconLabel: "圖像",
        actionLabel: "動作",
        kindApp: "打開 App",
        kindFile: "打開檔案或檔案夾",
        kindURL: "打開連結",
        kindShortcut: "按下快速鍵",
        kindTool: "Vorssaint 工具",
        kindMedia: "媒體控制",
        kindSubmenu: "子選單",
        chooseButton: "選擇…",
        urlPlaceholder: "example.com",
        urlInvalid: "請輸入有效的連結。",
        toolLabel: "工具",
        mediaLabel: "控制",
        mediaPlayPause: "播放或暫停",
        mediaPrevious: "上一首",
        mediaNext: "下一首",
        mediaNowPlaying: "播放中",
        mediaNothingPlaying: "目前沒有播放內容",
        mediaOpenAppFormat: "開啟 %@",
        submenuCaption: "打開帶有自己動作的第二個轉盤。",
        saveButton: "儲存",
        deleteButton: "移除",
        permissionCaption: "按鍵動作和側鍵呼出需要「輔助使用」權限。",
        manageButton: "管理選單",
        panelCaption: "常用動作都在一個轉盤上",
        mouseTriggerLabel: "滑鼠按鈕",
        mouseTriggerOff: "關閉",
        mouseTriggerBack: "側面上一頁鍵",
        mouseTriggerForward: "側面下一頁鍵",
        mouseTriggerWarning: "開啟期間，該按鈕在 App 裡不再上一頁或下一頁。如果你用它來瀏覽，請保持關閉。",
        buttonTestLabel: "按鍵測試",
        buttonTestWaiting: "現在按一下該按鍵",
        buttonTestSeen: "Vorssaint 看得到這個按鍵",
        buttonTestOther: "剛才是另一個按鍵",
        buttonTestBlind: "Vorssaint 目前無法觀察滑鼠",
        buttonTestHint: "如果沒有任何反應，表示 macOS 沒有把該按鍵交給 App。自帶軟體的滑鼠常把側鍵改成別的功能。請到那邊改回來，或者給該按鍵設定一組快速鍵，然後在上面使用這組快速鍵。",
        activationModeLabel: "開啟方式",
        activationModePressOrHold: "按下或按住",
        activationModePress: "按下以開啟",
        activationModeHold: "按住以選擇",
        activationModeCaption: "按下或按住會保留目前的自適應手勢。按下模式會保持開啟；按住模式會在放開時執行醒目顯示的動作。",
        profilesHeader: "設定檔",
        profilePickerLabel: "設定檔",
        addProfileButton: "新增設定檔",
        duplicateProfileButton: "複製設定檔",
        deleteProfileButton: "刪除設定檔",
        profileNameLabel: "設定檔名稱",
        profileColorLabel: "顏色",
        profileShortcutLabel: "快速鍵",
        profileMouseTriggerLabel: "滑鼠按鈕",
        presetGeneral: "一般",
        presetMedia: "媒體",
        presetTools: "工具",
        presetWindowLayout: "視窗佈局",
        presetQuickToggles: "快速開關",
        presetBlank: "空白",
        colorAccent: "強調色",
        colorBlue: "藍色",
        colorPurple: "紫色",
        colorPink: "粉紅色",
        colorRed: "紅色",
        colorOrange: "橙色",
        colorYellow: "黃色",
        colorGreen: "綠色",
        colorMint: "薄荷綠",
        colorCyan: "青色",
        colorIndigo: "靛青",
        colorGraphite: "石墨灰",
        fetchFaviconButton: "取得網站圖示",
        fetchFaviconDisclaimer: "僅連接網站一次以下載圖示。儲存在本機。",
        fetchFaviconLoading: "正在取得圖示…",
        fetchFaviconSuccess: "圖示已下載",
        fetchFaviconError: "找不到網站圖示",
        mouseTriggerRequirement: "這裡只支援滑鼠的額外按鈕。使用觸控式軌跡板或沒有額外按鈕的滑鼠時，請使用上方的鍵盤快速鍵。",
        canvasHint: "按一下按鈕以選擇動作或將其移除。拖移即可調整位置。",
        resetActionsButton: "重設",
        resetActionsConfirm: "重設動作",
        resetActionsConfirmMessage: "恢復此設定檔的預設動作？自訂動作將會被取代。",
        showListButton: "顯示為列表",
        hideListButton: "隱藏列表"
    )

    static let zhHK = RadialMenuFeatureStrings(
        pageTitle: "放射狀選單",
        hubDescription: "在指標周圍打開一個由常用動作組成的轉盤",
        enableLabel: "使用放射狀選單",
        enableCaption: "按住快速鍵，指向某個動作後放開。快速按一下可讓轉盤保持開啟。",
        positionLabel: "開啟位置",
        positionPointer: "指標處",
        positionCenter: "螢幕中央",
        tryButton: "試試看",
        actionsHeader: "動作",
        addButton: "加入動作",
        limitCaption: "一個轉盤最多容納 12 個動作。",
        emptyCaption: "這裡還沒有動作。",
        backButton: "返回",
        editActionsButton: "編輯動作",
        nameLabel: "名稱",
        automaticLabel: "自動",
        iconLabel: "圖像",
        actionLabel: "動作",
        kindApp: "打開 App",
        kindFile: "打開檔案或資料夾",
        kindURL: "打開連結",
        kindShortcut: "按下快速鍵",
        kindTool: "Vorssaint 工具",
        kindMedia: "媒體控制",
        kindSubmenu: "子選單",
        chooseButton: "選擇…",
        urlPlaceholder: "example.com",
        urlInvalid: "請輸入有效的連結。",
        toolLabel: "工具",
        mediaLabel: "控制",
        mediaPlayPause: "播放或暫停",
        mediaPrevious: "上一首",
        mediaNext: "下一首",
        mediaNowPlaying: "播放中",
        mediaNothingPlaying: "目前沒有播放內容",
        mediaOpenAppFormat: "開啟 %@",
        submenuCaption: "打開帶有自己動作的第二個轉盤。",
        saveButton: "儲存",
        deleteButton: "移除",
        permissionCaption: "按鍵動作和側鍵呼出需要「輔助使用」權限。",
        manageButton: "管理選單",
        panelCaption: "常用動作都在一個轉盤上",
        mouseTriggerLabel: "滑鼠按鈕",
        mouseTriggerOff: "關閉",
        mouseTriggerBack: "側面上一頁鍵",
        mouseTriggerForward: "側面下一頁鍵",
        mouseTriggerWarning: "開啟期間，該按鈕在 App 裡不再上一頁或下一頁。如果你用它來瀏覽，請保持關閉。",
        buttonTestLabel: "按鍵測試",
        buttonTestWaiting: "現在按一下該按鍵",
        buttonTestSeen: "Vorssaint 看得到這個按鍵",
        buttonTestOther: "剛才是另一個按鍵",
        buttonTestBlind: "Vorssaint 目前無法觀察滑鼠",
        buttonTestHint: "如果沒有任何反應，表示 macOS 沒有把該按鍵交給 App。自帶軟體的滑鼠常把側鍵改成別的功能。請到那邊改回來，或者給該按鍵設定一組快速鍵，然後在上面使用這組快速鍵。",
        activationModeLabel: "開啟方式",
        activationModePressOrHold: "按下或按住",
        activationModePress: "按下以開啟",
        activationModeHold: "按住以選擇",
        activationModeCaption: "按下或按住會保留目前的自適應手勢。按下模式會保持開啟；按住模式會在放開時執行醒目顯示的動作。",
        profilesHeader: "設定檔",
        profilePickerLabel: "設定檔",
        addProfileButton: "新增設定檔",
        duplicateProfileButton: "複製設定檔",
        deleteProfileButton: "刪除設定檔",
        profileNameLabel: "設定檔名稱",
        profileColorLabel: "顏色",
        profileShortcutLabel: "快捷鍵",
        profileMouseTriggerLabel: "滑鼠按鈕",
        presetGeneral: "一般",
        presetMedia: "媒體",
        presetTools: "工具",
        presetWindowLayout: "視窗佈局",
        presetQuickToggles: "快速開關",
        presetBlank: "空白",
        colorAccent: "強調色",
        colorBlue: "藍色",
        colorPurple: "紫色",
        colorPink: "粉紅色",
        colorRed: "紅色",
        colorOrange: "橙色",
        colorYellow: "黃色",
        colorGreen: "綠色",
        colorMint: "薄荷綠",
        colorCyan: "青色",
        colorIndigo: "靛青",
        colorGraphite: "石墨灰",
        fetchFaviconButton: "取得網站圖示",
        fetchFaviconDisclaimer: "僅連線網站一次以下載圖示。儲存在本機。",
        fetchFaviconLoading: "正在取得圖示…",
        fetchFaviconSuccess: "圖示已下載",
        fetchFaviconError: "找不到網站圖示",
        mouseTriggerRequirement: "這裡只支援滑鼠的額外按鈕。使用觸控板或沒有額外按鈕的滑鼠時，請使用上方的鍵盤快速鍵。",
        canvasHint: "按一下按鈕以選擇動作或將其移除。拖移即可調整位置。",
        resetActionsButton: "重設",
        resetActionsConfirm: "重設動作",
        resetActionsConfirmMessage: "恢復此設定檔的預設動作？自訂動作將會被取代。",
        showListButton: "顯示為列表",
        hideListButton: "隱藏列表"
    )
}
