// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

/// Localized strings for the screen recorder.
struct RecorderFeatureStrings {
    let pageTitle: String
    let hubDescription: String
    let panelCaption: String
    let startButton: String
    let stopButton: String
    let fileNamePrefix: String
    let selectionPurpose: String
    let indicatorTooltip: String
    let countdownLabel: String
    let countdownOff: String
    let countdownSecondsFormat: String
    let qualityLabel: String
    let qualitySmall: String
    let qualityBalanced: String
    let qualityHigh: String
    let qualityCaption: String
    let frameRateLabel: String
    let frameRateFormat: String
    let systemAudioToggle: String
    let systemAudioCaption: String
    let folderLabel: String
    let folderChoose: String
    let moreOptions: String
    let copyButton: String
    let saveButton: String
    let discardButton: String
    let copiedHUD: String
    let savedHUDFormat: String
    let recordFailed: String
    let noSpaceTitle: String
    let noSpaceMessage: String
    let stoppedNoSpaceHUD: String
    let shortcutLabel: String
    let editorTitle: String
    let saveVideoButton: String
    let saveGIFButton: String
    let exportingLabel: String
    let cancelButton: String
    let exportFailed: String
    let gifTooLongFormat: String
    let gifSizeLabel: String
    let gifSizeSmall: String
    let gifSizeMedium: String
    let gifSizeLarge: String
    let gifFrameRateLabel: String
    let discardTitle: String
    let discardMessage: String
    let openEditorToggle: String
    let openEditorCaption: String
    let lookLabel: String
    let lookRaw: String
    let lookClean: String
    let lookStudio: String
    let lookCaption: String
    let pointerSectionLabel: String
    let pointerShowToggle: String
    let pointerSmoothingLabel: String
    let pointerSmoothingOff: String
    let pointerSmoothingLight: String
    let pointerSmoothingSmooth: String
    let pointerSmoothingCinematic: String
    let pointerSizeLabel: String
    let clickRingToggle: String
    let zoomSectionLabel: String
    let zoomToggle: String
    let zoomAmountLabel: String
    let backgroundSectionLabel: String
    let shapeLabel: String
    let shapeOriginal: String
    let shapeWide: String
    let shapeSquare: String
    let shapeVertical: String
    let noPointerNote: String
    let zoomLaneEmptyHint: String
    let addZoomButton: String
    let removeZoom: String
    let thisZoomLabel: String
    let zoomWhereLabel: String
    let zoomFollowsPointer: String
    let zoomPickSpot: String
    let zoomPickSpotHint: String
    let regenerateZooms: String
    let backToOptions: String
    let cutOutButton: String
    let cutHint: String
    let addTextButton: String
    let textLaneEmptyHint: String
    let thisTextLabel: String
    let textPlaceholder: String
    let textContentLabel: String
    let textSizeLabel: String
    let textPositionLabel: String
    let textColorLabel: String
    let removeText: String
    let copyAndDeleteButton: String
    let saveAsButton: String
    let discardSavedMessage: String
    let presetsButton: String
    let savePreset: String
    let presetNamePlaceholder: String
    let removePreset: String
    let zoomEmptyTitle: String
    let zoomEmptyCaption: String
    let createAutomaticZooms: String
    let typingZoomToggle: String
    let typingZoomCaption: String
    let microphoneToggle: String
    let microphoneCaption: String
    let systemAudioTrackLabel: String
    let microphoneTrackLabel: String
    let audioVolumeLabel: String
    let removeAudio: String
    let restoreAudio: String
    let microphoneUnavailableHUD: String
    let microphonePermissionName: String
    let microphonePermissionExplain: String
    let automaticZoomToggle: String
    let automaticZoomCaption: String
    let pauseButton: String
    let resumeButton: String
    let blurLaneLabel: String
    let addBlurButton: String
    let blurLaneEmptyHint: String
    let thisBlurLabel: String
    let blurPickArea: String
    let blurPickAreaHint: String
    let blurCaption: String
    let addImageButton: String
    let imageLaneLabel: String
    let imageLaneEmptyHint: String
    let thisImageLabel: String
    let imageSizeLabel: String
    let imageOpacityLabel: String
    let imagePositionLabel: String
    let imageImportFailed: String
}

extension FeatureStrings {
    static func recorder(_ language: AppLanguage) -> RecorderFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension RecorderFeatureStrings {
    static let enUS = RecorderFeatureStrings(
        pageTitle: "Screen recording",
        hubDescription: "Records an area, window or screen and edits it afterwards",
        panelCaption: "Record an area, window or the whole screen",
        startButton: "Record now",
        stopButton: "Stop recording",
        fileNamePrefix: "Recording",
        selectionPurpose: "Choose what to record",
        indicatorTooltip: "Recording controls",
        countdownLabel: "Countdown",
        countdownOff: "Off",
        countdownSecondsFormat: "%d s",
        qualityLabel: "Quality",
        qualitySmall: "Small file",
        qualityBalanced: "Balanced",
        qualityHigh: "High",
        qualityCaption: "Balanced fits most uses. High keeps every detail and makes bigger files.",
        frameRateLabel: "Frames per second",
        frameRateFormat: "%d fps",
        systemAudioToggle: "Record the sound of the Mac",
        systemAudioCaption: "Everything you hear goes into the recording, on its own track, so you can silence it later.",
        folderLabel: "Save to",
        folderChoose: "Choose…",
        moreOptions: "More options",
        copyButton: "Copy",
        saveButton: "Save",
        discardButton: "Delete",
        copiedHUD: "Recording copied",
        savedHUDFormat: "Saved to %@",
        recordFailed: "The screen could not be recorded",
        noSpaceTitle: "Not enough space to record",
        noSpaceMessage: "Free up some space on the disk and try again.",
        stoppedNoSpaceHUD: "Recording stopped, the disk is almost full",
        shortcutLabel: "Shortcut",
        editorTitle: "Recording",
        saveVideoButton: "Save",
        saveGIFButton: "Save as GIF",
        exportingLabel: "Saving…",
        cancelButton: "Cancel",
        exportFailed: "The recording could not be saved",
        gifTooLongFormat: "A GIF can be up to %d seconds long",
        gifSizeLabel: "GIF size",
        gifSizeSmall: "Small",
        gifSizeMedium: "Medium",
        gifSizeLarge: "Large",
        gifFrameRateLabel: "GIF smoothness",
        discardTitle: "Delete this recording?",
        discardMessage: "It has not been saved anywhere yet.",
        openEditorToggle: "Open the editor after recording",
        openEditorCaption: "The recording opens ready to trim, mute and save. Turn this off to get the file straight away.",
        lookLabel: "Look",
        lookRaw: "Original",
        lookClean: "Smooth",
        lookStudio: "Studio",
        lookCaption: "A starting point. Change anything below and it stays changed.",
        pointerSectionLabel: "Pointer",
        pointerShowToggle: "Draw the pointer",
        pointerSmoothingLabel: "Smoothing",
        pointerSmoothingOff: "None",
        pointerSmoothingLight: "Light",
        pointerSmoothingSmooth: "Smooth",
        pointerSmoothingCinematic: "Cinematic",
        pointerSizeLabel: "Size",
        clickRingToggle: "Mark where you click",
        zoomSectionLabel: "Zoom",
        zoomToggle: "Zoom in on every click",
        zoomAmountLabel: "How close",
        backgroundSectionLabel: "Background",
        shapeLabel: "Shape",
        shapeOriginal: "Original",
        shapeWide: "Wide",
        shapeSquare: "Square",
        shapeVertical: "Tall",
        noPointerNote: "This recording has no pointer track, so there is nothing to smooth. Zooms placed by hand still work.",
        zoomLaneEmptyHint: "Click here to add a zoom",
        addZoomButton: "Add a zoom",
        removeZoom: "Remove",
        thisZoomLabel: "This zoom",
        zoomWhereLabel: "Where it looks",
        zoomFollowsPointer: "Follows the pointer",
        zoomPickSpot: "Pick a spot",
        zoomPickSpotHint: "Click the picture to aim it",
        regenerateZooms: "Back to one per click",
        backToOptions: "All options",
        cutOutButton: "Cut out",
        cutHint: "Drag across the film to pick a part to remove",
        addTextButton: "Add text",
        textLaneEmptyHint: "Click here to add text",
        thisTextLabel: "This text",
        textPlaceholder: "Your text here",
        textContentLabel: "Text",
        textSizeLabel: "Size",
        textPositionLabel: "Position",
        textColorLabel: "Colour",
        removeText: "Remove",
        copyAndDeleteButton: "Copy and delete",
        saveAsButton: "Save as…",
        discardSavedMessage: "Saved and copied files will stay where they are.",
        presetsButton: "Presets",
        savePreset: "Save current preset…",
        presetNamePlaceholder: "Preset name",
        removePreset: "Remove preset",
        zoomEmptyTitle: "No zooms yet",
        zoomEmptyCaption: "Create them from your clicks or add one on the timeline.",
        createAutomaticZooms: "Create automatic zooms",
        typingZoomToggle: "Keep zoomed in while typing",
        typingZoomCaption: "After a click, typing keeps the automatic zoom on that spot.",
        microphoneToggle: "Record the microphone",
        microphoneCaption: "Your voice goes into its own track and stays adjustable in the editor.",
        systemAudioTrackLabel: "Mac sound",
        microphoneTrackLabel: "Microphone",
        audioVolumeLabel: "Volume",
        removeAudio: "Remove",
        restoreAudio: "Restore",
        microphoneUnavailableHUD: "Microphone unavailable",
        microphonePermissionName: "Microphone",
        microphonePermissionExplain: "Lets screen recordings include your voice when you turn it on.",
        automaticZoomToggle: "Add zooms automatically",
        automaticZoomCaption: "Turn this off to start new recordings without zooms. You can still add them in the editor.",
        pauseButton: "Pause recording",
        resumeButton: "Resume recording",
        blurLaneLabel: "Blur",
        addBlurButton: "Blur an area",
        blurLaneEmptyHint: "Click here to add a blur",
        thisBlurLabel: "This blur",
        blurPickArea: "Choose the area",
        blurPickAreaHint: "Drag over what should stay hidden",
        blurCaption: "Hidden for as long as its block lasts on the timeline.",
        addImageButton: "Add image",
        imageLaneLabel: "Image",
        imageLaneEmptyHint: "Click here to add an image",
        thisImageLabel: "This image",
        imageSizeLabel: "Size",
        imageOpacityLabel: "Opacity",
        imagePositionLabel: "Position",
        imageImportFailed: "Couldn’t add this image."
    )

    static let ptBR = RecorderFeatureStrings(
        pageTitle: "Gravação de tela",
        hubDescription: "Grava uma área, janela ou tela e edita depois",
        panelCaption: "Grave uma área, uma janela ou a tela inteira",
        startButton: "Gravar agora",
        stopButton: "Parar a gravação",
        fileNamePrefix: "Gravação",
        selectionPurpose: "Escolha o que gravar",
        indicatorTooltip: "Controles da gravação",
        countdownLabel: "Contagem regressiva",
        countdownOff: "Desligada",
        countdownSecondsFormat: "%d s",
        qualityLabel: "Qualidade",
        qualitySmall: "Arquivo pequeno",
        qualityBalanced: "Equilibrada",
        qualityHigh: "Alta",
        qualityCaption: "A equilibrada serve para quase tudo. A alta guarda cada detalhe e gera arquivos maiores.",
        frameRateLabel: "Quadros por segundo",
        frameRateFormat: "%d qps",
        systemAudioToggle: "Gravar o som do Mac",
        systemAudioCaption: "Tudo o que você ouve entra na gravação, em uma faixa separada, então dá para silenciar depois.",
        folderLabel: "Salvar em",
        folderChoose: "Escolher…",
        moreOptions: "Mais opções",
        copyButton: "Copiar",
        saveButton: "Salvar",
        discardButton: "Apagar",
        copiedHUD: "Gravação copiada",
        savedHUDFormat: "Salva em %@",
        recordFailed: "Não foi possível gravar a tela",
        noSpaceTitle: "Sem espaço para gravar",
        noSpaceMessage: "Libere espaço no disco e tente de novo.",
        stoppedNoSpaceHUD: "A gravação parou, o disco está quase cheio",
        shortcutLabel: "Atalho",
        editorTitle: "Gravação",
        saveVideoButton: "Salvar",
        saveGIFButton: "Salvar como GIF",
        exportingLabel: "Salvando…",
        cancelButton: "Cancelar",
        exportFailed: "Não foi possível salvar a gravação",
        gifTooLongFormat: "Um GIF pode ter até %d segundos",
        gifSizeLabel: "Tamanho do GIF",
        gifSizeSmall: "Pequeno",
        gifSizeMedium: "Médio",
        gifSizeLarge: "Grande",
        gifFrameRateLabel: "Suavidade do GIF",
        discardTitle: "Apagar esta gravação?",
        discardMessage: "Ela ainda não foi salva em lugar nenhum.",
        openEditorToggle: "Abrir o editor depois de gravar",
        openEditorCaption: "A gravação abre pronta para cortar, tirar o som e salvar. Desligue para receber o arquivo direto.",
        lookLabel: "Estilo",
        lookRaw: "Original",
        lookClean: "Suave",
        lookStudio: "Estúdio",
        lookCaption: "Um ponto de partida. Mude o que quiser abaixo e fica mudado.",
        pointerSectionLabel: "Ponteiro",
        pointerShowToggle: "Desenhar o ponteiro",
        pointerSmoothingLabel: "Suavização",
        pointerSmoothingOff: "Nenhuma",
        pointerSmoothingLight: "Leve",
        pointerSmoothingSmooth: "Suave",
        pointerSmoothingCinematic: "Cinematográfica",
        pointerSizeLabel: "Tamanho",
        clickRingToggle: "Marcar onde você clica",
        zoomSectionLabel: "Zoom",
        zoomToggle: "Aproximar a cada clique",
        zoomAmountLabel: "Quanto aproxima",
        backgroundSectionLabel: "Fundo",
        shapeLabel: "Formato",
        shapeOriginal: "Original",
        shapeWide: "Larga",
        shapeSquare: "Quadrada",
        shapeVertical: "Alta",
        noPointerNote: "Esta gravação não tem trilha do ponteiro, então não há o que suavizar. Zooms colocados na mão continuam funcionando.",
        zoomLaneEmptyHint: "Clique aqui para adicionar um zoom",
        addZoomButton: "Adicionar um zoom",
        removeZoom: "Remover",
        thisZoomLabel: "Este zoom",
        zoomWhereLabel: "Para onde olha",
        zoomFollowsPointer: "Segue o ponteiro",
        zoomPickSpot: "Escolher um ponto",
        zoomPickSpotHint: "Clique na imagem para mirar",
        regenerateZooms: "Voltar a um por clique",
        backToOptions: "Todas as opções",
        cutOutButton: "Cortar fora",
        cutHint: "Arraste sobre o filme para escolher um trecho a remover",
        addTextButton: "Adicionar texto",
        textLaneEmptyHint: "Clique aqui para adicionar texto",
        thisTextLabel: "Este texto",
        textPlaceholder: "Seu texto aqui",
        textContentLabel: "Texto",
        textSizeLabel: "Tamanho",
        textPositionLabel: "Posição",
        textColorLabel: "Cor",
        removeText: "Remover",
        copyAndDeleteButton: "Copiar e excluir",
        saveAsButton: "Salvar como…",
        discardSavedMessage: "Os arquivos salvos e copiados continuarão onde estão.",
        presetsButton: "Predefinições",
        savePreset: "Salvar predefinição atual…",
        presetNamePlaceholder: "Nome da predefinição",
        removePreset: "Remover predefinição",
        zoomEmptyTitle: "Nenhum zoom ainda",
        zoomEmptyCaption: "Crie a partir dos seus cliques ou adicione um na linha do tempo.",
        createAutomaticZooms: "Criar zooms automáticos",
        typingZoomToggle: "Manter o zoom ao digitar",
        typingZoomCaption: "Depois de um clique, a digitação mantém o zoom automático naquele ponto.",
        microphoneToggle: "Gravar o microfone",
        microphoneCaption: "Sua voz entra em uma faixa separada e pode ser ajustada no editor.",
        systemAudioTrackLabel: "Som do Mac",
        microphoneTrackLabel: "Microfone",
        audioVolumeLabel: "Volume",
        removeAudio: "Remover",
        restoreAudio: "Restaurar",
        microphoneUnavailableHUD: "Microfone indisponível",
        microphonePermissionName: "Microfone",
        microphonePermissionExplain: "Permite incluir sua voz nas gravações de tela quando você ativar.",
        automaticZoomToggle: "Adicionar zooms automaticamente",
        automaticZoomCaption: "Desative para começar novas gravações sem zooms. Você ainda pode adicioná-los no editor.",
        pauseButton: "Pausar gravação",
        resumeButton: "Retomar gravação",
        blurLaneLabel: "Desfoque",
        addBlurButton: "Desfocar uma área",
        blurLaneEmptyHint: "Clique aqui para adicionar um desfoque",
        thisBlurLabel: "Este desfoque",
        blurPickArea: "Escolher a área",
        blurPickAreaHint: "Arraste sobre o que deve ficar escondido",
        blurCaption: "Fica escondido enquanto o bloco durar na linha do tempo.",
        addImageButton: "Adicionar imagem",
        imageLaneLabel: "Imagem",
        imageLaneEmptyHint: "Clique aqui para adicionar uma imagem",
        thisImageLabel: "Esta imagem",
        imageSizeLabel: "Tamanho",
        imageOpacityLabel: "Opacidade",
        imagePositionLabel: "Posição",
        imageImportFailed: "Não foi possível adicionar esta imagem."
    )

    static let tr = RecorderFeatureStrings(
        pageTitle: "Ekran Kaydı",
        hubDescription: "Bir alanı, pencereyi ya da ekranı kaydedip sonradan düzenlemenizi sağlar",
        panelCaption: "Bir alanı, pencereyi ya da tüm ekranı kaydedin",
        startButton: "Kaydı başlat",
        stopButton: "Kaydı durdur",
        fileNamePrefix: "Kayıt",
        selectionPurpose: "Neyi kaydedeceğinizi seçin",
        indicatorTooltip: "Kayıt denetimleri",
        countdownLabel: "Geri sayım",
        countdownOff: "Kapalı",
        countdownSecondsFormat: "%d sn",
        qualityLabel: "Kalite",
        qualitySmall: "Küçük dosya",
        qualityBalanced: "Dengeli",
        qualityHigh: "Yüksek",
        qualityCaption: "Dengeli, çoğu iş için yeterlidir. Yüksek her ayrıntıyı korur ve dosyaları büyütür.",
        frameRateLabel: "Kare hızı",
        frameRateFormat: "%d fps",
        systemAudioToggle: "Mac’in sesini kaydet",
        systemAudioCaption: "Duyduğunuz her şey kayda ayrı bir ses parçası olarak girer, böylece sonradan susturabilirsiniz.",
        folderLabel: "Kaydetme yeri",
        folderChoose: "Seç…",
        moreOptions: "Diğer seçenekler",
        copyButton: "Kopyala",
        saveButton: "Kaydet",
        discardButton: "Sil",
        copiedHUD: "Kayıt kopyalandı",
        savedHUDFormat: "Şuraya kaydedildi: %@",
        recordFailed: "Ekran kaydedilemedi",
        noSpaceTitle: "Kayıt için yeterli alan yok",
        noSpaceMessage: "Diskte biraz yer açıp yeniden deneyin.",
        stoppedNoSpaceHUD: "Kayıt durduruldu, disk neredeyse dolu",
        shortcutLabel: "Kısayol",
        editorTitle: "Kayıt",
        saveVideoButton: "Kaydet",
        saveGIFButton: "GIF olarak kaydet",
        exportingLabel: "Kaydediliyor…",
        cancelButton: "Vazgeç",
        exportFailed: "Dosya kaydedilemedi",
        gifTooLongFormat: "GIF en fazla %d saniye uzunluğunda olabilir",
        gifSizeLabel: "GIF boyutu",
        gifSizeSmall: "Küçük",
        gifSizeMedium: "Orta",
        gifSizeLarge: "Büyük",
        gifFrameRateLabel: "GIF akıcılığı",
        discardTitle: "Bu kayıt silinsin mi?",
        discardMessage: "Henüz hiçbir yere kaydedilmedi.",
        openEditorToggle: "Kayıttan sonra düzenleyiciyi aç",
        openEditorCaption: "Kayıt açıldığında budayabilir, sesini kapatabilir ve kaydedebilirsiniz. Dosyayı hemen almak için bunu kapatın.",
        lookLabel: "Görünüm",
        lookRaw: "Orijinal",
        lookClean: "Akıcı",
        lookStudio: "Stüdyo",
        lookCaption: "Bir başlangıç noktası. Aşağıda ne değiştirirseniz öyle kalır.",
        pointerSectionLabel: "İmleç",
        pointerShowToggle: "İmleci göster",
        pointerSmoothingLabel: "Yumuşatma",
        pointerSmoothingOff: "Yok",
        pointerSmoothingLight: "Hafif",
        pointerSmoothingSmooth: "Yumuşak",
        pointerSmoothingCinematic: "Sinematik",
        pointerSizeLabel: "Boyut",
        clickRingToggle: "Tıkladığınız yeri işaretle",
        zoomSectionLabel: "Yakınlaştırma",
        zoomToggle: "Her tıklamada yakınlaştır",
        zoomAmountLabel: "Ne kadar yakın",
        backgroundSectionLabel: "Arka plan",
        shapeLabel: "Şekil",
        shapeOriginal: "Özgün",
        shapeWide: "Geniş",
        shapeSquare: "Kare",
        shapeVertical: "Dikey",
        noPointerNote: "Bu kayıt, imleç izlenmeye başlamadan önce yapıldı. Yumuşatılacak ya da yakınlaştırılacak bir şey yok.",
        zoomLaneEmptyHint: "Yakınlaştırma eklemek için tıklayın",
        addZoomButton: "Yakınlaştırma ekle",
        removeZoom: "Kaldır",
        thisZoomLabel: "Bu yakınlaştırma",
        zoomWhereLabel: "Baktığı yer",
        zoomFollowsPointer: "İşaretçiyi izler",
        zoomPickSpot: "Sabit nokta",
        zoomPickSpotHint: "Görüntüye tıklayıp noktayı seçin",
        regenerateZooms: "Her tıklamaya bir yakınlaştırma",
        backToOptions: "Tüm seçenekler",
        cutOutButton: "Kes çıkar",
        cutHint: "Kaldırmak istediğiniz bölümü şerit üzerinde sürükleyerek seçin",
        addTextButton: "Metin ekle",
        textLaneEmptyHint: "Metin eklemek için tıklayın",
        thisTextLabel: "Bu metin",
        textPlaceholder: "Metniniz buraya",
        textContentLabel: "Metin",
        textSizeLabel: "Boyut",
        textPositionLabel: "Konum",
        textColorLabel: "Renk",
        removeText: "Kaldır",
        copyAndDeleteButton: "Kopyala ve sil",
        saveAsButton: "Farklı kaydet…",
        discardSavedMessage: "Kaydedilen ve kopyalanan dosyalar yerinde kalır.",
        presetsButton: "Hazır ayarlar",
        savePreset: "Geçerli hazır ayarı kaydet…",
        presetNamePlaceholder: "Hazır ayar adı",
        removePreset: "Hazır ayarı kaldır",
        zoomEmptyTitle: "Henüz yakınlaştırma yok",
        zoomEmptyCaption: "Tıklamalarınızdan oluşturun veya zaman çizelgesine bir tane ekleyin.",
        createAutomaticZooms: "Otomatik yakınlaştırmalar oluştur",
        typingZoomToggle: "Yazarken yakınlaştırmayı koru",
        typingZoomCaption: "Bir tıklamadan sonra yazmak, otomatik yakınlaştırmayı o noktada tutar.",
        microphoneToggle: "Mikrofonu kaydet",
        microphoneCaption: "Sesiniz ayrı bir parçaya kaydedilir ve düzenleyicide ayarlanabilir.",
        systemAudioTrackLabel: "Mac sesi",
        microphoneTrackLabel: "Mikrofon",
        audioVolumeLabel: "Ses düzeyi",
        removeAudio: "Kaldır",
        restoreAudio: "Geri yükle",
        microphoneUnavailableHUD: "Mikrofon kullanılamıyor",
        microphonePermissionName: "Mikrofon",
        microphonePermissionExplain: "Açtığınızda ekran kayıtlarına sesinizi ekler.",
        automaticZoomToggle: "Yakınlaştırmaları otomatik ekle",
        automaticZoomCaption: "Yeni kayıtları yakınlaştırmasız başlatmak için kapatın. Düzenleyicide yine ekleyebilirsiniz.",
        pauseButton: "Kaydı duraklat",
        resumeButton: "Kayda devam et",
        blurLaneLabel: "Bulanıklık",
        addBlurButton: "Bir alanı bulanıklaştır",
        blurLaneEmptyHint: "Bulanıklık eklemek için buraya tıklayın",
        thisBlurLabel: "Bu bulanıklık",
        blurPickArea: "Alanı seç",
        blurPickAreaHint: "Gizli kalması gerekenin üzerine sürükleyin",
        blurCaption: "Zaman çizelgesindeki blok sürdüğü sürece gizli kalır.",
        addImageButton: "Görsel ekle",
        imageLaneLabel: "Görsel",
        imageLaneEmptyHint: "Görsel eklemek için buraya tıklayın",
        thisImageLabel: "Bu görsel",
        imageSizeLabel: "Boyut",
        imageOpacityLabel: "Matlık",
        imagePositionLabel: "Konum",
        imageImportFailed: "Bu görsel eklenemedi."
    )

    static let ru = RecorderFeatureStrings(
        pageTitle: "Запись экрана",
        hubDescription: "Записывает область, окно или экран, а потом даёт отредактировать запись",
        panelCaption: "Запишите область, окно или весь экран",
        startButton: "Начать запись",
        stopButton: "Остановить запись",
        fileNamePrefix: "Запись",
        selectionPurpose: "Выберите, что записать",
        indicatorTooltip: "Управление записью",
        countdownLabel: "Обратный отсчёт",
        countdownOff: "Выкл.",
        countdownSecondsFormat: "%d с",
        qualityLabel: "Качество",
        qualitySmall: "Небольшой файл",
        qualityBalanced: "Сбалансированное",
        qualityHigh: "Высокое",
        qualityCaption: "Сбалансированное подходит почти для всего. Высокое сохраняет все детали, а файлы получаются больше.",
        frameRateLabel: "Кадров в секунду",
        frameRateFormat: "%d кадр/с",
        systemAudioToggle: "Записывать звук Mac",
        systemAudioCaption: "Всё, что вы слышите, попадёт в запись отдельной дорожкой, чтобы потом звук можно было убрать.",
        folderLabel: "Сохранять в",
        folderChoose: "Выбрать…",
        moreOptions: "Дополнительно",
        copyButton: "Скопировать",
        saveButton: "Сохранить",
        discardButton: "Удалить",
        copiedHUD: "Запись скопирована",
        savedHUDFormat: "Сохранено в %@",
        recordFailed: "Не удалось записать экран",
        noSpaceTitle: "Не хватает места для записи",
        noSpaceMessage: "Освободите место на диске и попробуйте снова.",
        stoppedNoSpaceHUD: "Запись остановлена, диск почти полон",
        shortcutLabel: "Сочетание клавиш",
        editorTitle: "Запись",
        saveVideoButton: "Сохранить",
        saveGIFButton: "Сохранить GIF",
        exportingLabel: "Сохранение…",
        cancelButton: "Отменить",
        exportFailed: "Не удалось сохранить запись",
        gifTooLongFormat: "GIF может длиться до %d секунд",
        gifSizeLabel: "Размер GIF",
        gifSizeSmall: "Маленький",
        gifSizeMedium: "Средний",
        gifSizeLarge: "Большой",
        gifFrameRateLabel: "Плавность GIF",
        discardTitle: "Удалить эту запись?",
        discardMessage: "Она ещё нигде не сохранена.",
        openEditorToggle: "Открывать редактор после записи",
        openEditorCaption: "Запись открывается в редакторе, где её можно обрезать, выключить звук и сохранить. Отключите, чтобы сразу получать файл.",
        lookLabel: "Стиль",
        lookRaw: "Оригинал",
        lookClean: "Плавный",
        lookStudio: "Студийный",
        lookCaption: "Отправная точка. Всё, что измените ниже, так и останется.",
        pointerSectionLabel: "Указатель",
        pointerShowToggle: "Показывать указатель",
        pointerSmoothingLabel: "Сглаживание",
        pointerSmoothingOff: "Нет",
        pointerSmoothingLight: "Лёгкое",
        pointerSmoothingSmooth: "Плавное",
        pointerSmoothingCinematic: "Как в кино",
        pointerSizeLabel: "Размер",
        clickRingToggle: "Отмечать нажатия",
        zoomSectionLabel: "Увеличение",
        zoomToggle: "Приближать при каждом нажатии",
        zoomAmountLabel: "Насколько близко",
        backgroundSectionLabel: "Фон",
        shapeLabel: "Форма",
        shapeOriginal: "Исходная",
        shapeWide: "Широкая",
        shapeSquare: "Квадратная",
        shapeVertical: "Вертикальная",
        noPointerNote: "В этой записи нет указателя, поэтому сглаживать и приближать нечего.",
        zoomLaneEmptyHint: "Нажмите, чтобы добавить увеличение",
        addZoomButton: "Добавить увеличение",
        removeZoom: "Удалить",
        thisZoomLabel: "Это увеличение",
        zoomWhereLabel: "Куда смотрит",
        zoomFollowsPointer: "Следует за указателем",
        zoomPickSpot: "Смотрит в одну точку",
        zoomPickSpotHint: "Нажмите на кадр, чтобы выбрать точку",
        regenerateZooms: "Заново по одному на нажатие",
        backToOptions: "Все настройки",
        cutOutButton: "Вырезать",
        cutHint: "Проведите по ленте, чтобы выбрать участок для удаления",
        addTextButton: "Добавить текст",
        textLaneEmptyHint: "Нажмите, чтобы добавить текст",
        thisTextLabel: "Этот текст",
        textPlaceholder: "Ваш текст",
        textContentLabel: "Текст",
        textSizeLabel: "Размер",
        textPositionLabel: "Положение",
        textColorLabel: "Цвет",
        removeText: "Удалить",
        copyAndDeleteButton: "Скопировать и удалить",
        saveAsButton: "Сохранить как…",
        discardSavedMessage: "Сохраненные и скопированные файлы останутся на месте.",
        presetsButton: "Предустановки",
        savePreset: "Сохранить текущую предустановку…",
        presetNamePlaceholder: "Название предустановки",
        removePreset: "Удалить предустановку",
        zoomEmptyTitle: "Масштабов пока нет",
        zoomEmptyCaption: "Создайте их из нажатий или добавьте один на шкалу времени.",
        createAutomaticZooms: "Создать автоматические масштабы",
        typingZoomToggle: "Сохранять масштаб при наборе",
        typingZoomCaption: "После щелчка набор текста удерживает автоматический масштаб в этой точке.",
        microphoneToggle: "Записывать микрофон",
        microphoneCaption: "Ваш голос записывается на отдельную дорожку и настраивается в редакторе.",
        systemAudioTrackLabel: "Звук Mac",
        microphoneTrackLabel: "Микрофон",
        audioVolumeLabel: "Громкость",
        removeAudio: "Удалить",
        restoreAudio: "Вернуть",
        microphoneUnavailableHUD: "Микрофон недоступен",
        microphonePermissionName: "Микрофон",
        microphonePermissionExplain: "Добавляет ваш голос в запись экрана, когда вы это включаете.",
        automaticZoomToggle: "Добавлять масштабирование автоматически",
        automaticZoomCaption: "Отключите, чтобы новые записи начинались без масштабирования. Его можно добавить в редакторе.",
        pauseButton: "Приостановить запись",
        resumeButton: "Продолжить запись",
        blurLaneLabel: "Размытие",
        addBlurButton: "Размыть область",
        blurLaneEmptyHint: "Нажмите здесь, чтобы добавить размытие",
        thisBlurLabel: "Это размытие",
        blurPickArea: "Выбрать область",
        blurPickAreaHint: "Проведите по тому, что нужно скрыть",
        blurCaption: "Скрыто, пока длится блок на шкале времени.",
        addImageButton: "Добавить изображение",
        imageLaneLabel: "Изображение",
        imageLaneEmptyHint: "Нажмите здесь, чтобы добавить изображение",
        thisImageLabel: "Это изображение",
        imageSizeLabel: "Размер",
        imageOpacityLabel: "Непрозрачность",
        imagePositionLabel: "Положение",
        imageImportFailed: "Не удалось добавить это изображение."
    )

    static let es = RecorderFeatureStrings(
        pageTitle: "Grabación de pantalla",
        hubDescription: "Graba un área, una ventana o la pantalla, y luego te deja editarla",
        panelCaption: "Graba un área, una ventana o toda la pantalla",
        startButton: "Grabar ahora",
        stopButton: "Detener grabación",
        fileNamePrefix: "Grabación",
        selectionPurpose: "Elige qué grabar",
        indicatorTooltip: "Controles de grabación",
        countdownLabel: "Cuenta atrás",
        countdownOff: "Desactivada",
        countdownSecondsFormat: "%d s",
        qualityLabel: "Calidad",
        qualitySmall: "Archivo pequeño",
        qualityBalanced: "Equilibrada",
        qualityHigh: "Alta",
        qualityCaption: "Equilibrada va bien para casi todo. Alta conserva cada detalle y crea archivos más grandes.",
        frameRateLabel: "Fotogramas por segundo",
        frameRateFormat: "%d fps",
        systemAudioToggle: "Grabar el sonido del Mac",
        systemAudioCaption: "Todo lo que oyes entra en la grabación, en una pista aparte, para que puedas silenciarlo después.",
        folderLabel: "Guardar en",
        folderChoose: "Elegir…",
        moreOptions: "Más opciones",
        copyButton: "Copiar",
        saveButton: "Guardar",
        discardButton: "Eliminar",
        copiedHUD: "Grabación copiada",
        savedHUDFormat: "Guardada en %@",
        recordFailed: "No se pudo grabar la pantalla",
        noSpaceTitle: "No hay espacio suficiente para grabar",
        noSpaceMessage: "Libera espacio en el disco y vuelve a intentarlo.",
        stoppedNoSpaceHUD: "Grabación detenida, el disco está casi lleno",
        shortcutLabel: "Atajo",
        editorTitle: "Grabación",
        saveVideoButton: "Guardar",
        saveGIFButton: "Guardar como GIF",
        exportingLabel: "Guardando…",
        cancelButton: "Cancelar",
        exportFailed: "No se pudo guardar la grabación",
        gifTooLongFormat: "Un GIF puede durar como máximo %d segundos",
        gifSizeLabel: "Tamaño del GIF",
        gifSizeSmall: "Pequeño",
        gifSizeMedium: "Mediano",
        gifSizeLarge: "Grande",
        gifFrameRateLabel: "Fluidez del GIF",
        discardTitle: "¿Eliminar esta grabación?",
        discardMessage: "Todavía no se ha guardado en ninguna parte.",
        openEditorToggle: "Abrir el editor al terminar de grabar",
        openEditorCaption: "La grabación se abre lista para recortar, silenciar y guardar. Desactiva esta opción para tener el archivo directamente.",
        lookLabel: "Estilo",
        lookRaw: "Original",
        lookClean: "Suave",
        lookStudio: "Estudio",
        lookCaption: "Un punto de partida. Lo que cambies abajo se mantiene.",
        pointerSectionLabel: "Puntero",
        pointerShowToggle: "Mostrar el puntero",
        pointerSmoothingLabel: "Suavizado",
        pointerSmoothingOff: "Ninguno",
        pointerSmoothingLight: "Ligero",
        pointerSmoothingSmooth: "Suave",
        pointerSmoothingCinematic: "Cine",
        pointerSizeLabel: "Tamaño",
        clickRingToggle: "Marcar dónde haces clic",
        zoomSectionLabel: "Zoom",
        zoomToggle: "Acercar en cada clic",
        zoomAmountLabel: "Cuánto se acerca",
        backgroundSectionLabel: "Fondo",
        shapeLabel: "Forma",
        shapeOriginal: "Original",
        shapeWide: "Horizontal",
        shapeSquare: "Cuadrada",
        shapeVertical: "Vertical",
        noPointerNote: "Esta grabación se hizo antes de que se guardara el puntero, así que no hay nada que suavizar ni acercar.",
        zoomLaneEmptyHint: "Haz clic aquí para añadir un zoom",
        addZoomButton: "Añadir un zoom",
        removeZoom: "Eliminar",
        thisZoomLabel: "Este zoom",
        zoomWhereLabel: "Hacia dónde mira",
        zoomFollowsPointer: "Sigue el puntero",
        zoomPickSpot: "Elegir un punto",
        zoomPickSpotHint: "Haz clic en la imagen para elegir el punto",
        regenerateZooms: "Volver a uno por cada clic",
        backToOptions: "Todas las opciones",
        cutOutButton: "Cortar",
        cutHint: "Arrastra sobre la tira para elegir el trozo a quitar",
        addTextButton: "Añadir texto",
        textLaneEmptyHint: "Haz clic aquí para añadir texto",
        thisTextLabel: "Este texto",
        textPlaceholder: "Tu texto aquí",
        textContentLabel: "Texto",
        textSizeLabel: "Tamaño",
        textPositionLabel: "Posición",
        textColorLabel: "Color",
        removeText: "Eliminar",
        copyAndDeleteButton: "Copiar y eliminar",
        saveAsButton: "Guardar como…",
        discardSavedMessage: "Los archivos guardados y copiados permanecerán donde están.",
        presetsButton: "Preajustes",
        savePreset: "Guardar preajuste actual…",
        presetNamePlaceholder: "Nombre del preajuste",
        removePreset: "Eliminar preajuste",
        zoomEmptyTitle: "Aún no hay zooms",
        zoomEmptyCaption: "Créelos a partir de tus clics o añade uno a la línea de tiempo.",
        createAutomaticZooms: "Crear zooms automáticos",
        typingZoomToggle: "Mantener el zoom al escribir",
        typingZoomCaption: "Después de un clic, escribir mantiene el zoom automático en ese punto.",
        microphoneToggle: "Grabar el micrófono",
        microphoneCaption: "Tu voz va a una pista separada y se puede ajustar en el editor.",
        systemAudioTrackLabel: "Sonido del Mac",
        microphoneTrackLabel: "Micrófono",
        audioVolumeLabel: "Volumen",
        removeAudio: "Quitar",
        restoreAudio: "Restaurar",
        microphoneUnavailableHUD: "Micrófono no disponible",
        microphonePermissionName: "Micrófono",
        microphonePermissionExplain: "Permite incluir tu voz en las grabaciones de pantalla al activarlo.",
        automaticZoomToggle: "Añadir zooms automáticamente",
        automaticZoomCaption: "Desactívalo para iniciar nuevas grabaciones sin zooms. Aún puedes añadirlos en el editor.",
        pauseButton: "Pausar grabación",
        resumeButton: "Reanudar grabación",
        blurLaneLabel: "Desenfoque",
        addBlurButton: "Desenfocar un área",
        blurLaneEmptyHint: "Haz clic aquí para añadir un desenfoque",
        thisBlurLabel: "Este desenfoque",
        blurPickArea: "Elegir el área",
        blurPickAreaHint: "Arrastra sobre lo que debe quedar oculto",
        blurCaption: "Queda oculto mientras dure su bloque en la línea de tiempo.",
        addImageButton: "Añadir imagen",
        imageLaneLabel: "Imagen",
        imageLaneEmptyHint: "Haz clic aquí para añadir una imagen",
        thisImageLabel: "Esta imagen",
        imageSizeLabel: "Tamaño",
        imageOpacityLabel: "Opacidad",
        imagePositionLabel: "Posición",
        imageImportFailed: "No se pudo añadir esta imagen."
    )

    static let de = RecorderFeatureStrings(
        pageTitle: "Bildschirmaufnahme",
        hubDescription: "Nimmt einen Bereich, ein Fenster oder den Bildschirm auf und bearbeitet die Aufnahme danach",
        panelCaption: "Bereich, Fenster oder den ganzen Bildschirm aufnehmen",
        startButton: "Jetzt aufnehmen",
        stopButton: "Aufnahme stoppen",
        fileNamePrefix: "Bildschirmaufnahme",
        selectionPurpose: "Wähle aus, was du aufnehmen möchtest",
        indicatorTooltip: "Aufnahmesteuerung",
        countdownLabel: "Countdown",
        countdownOff: "Aus",
        countdownSecondsFormat: "%d s",
        qualityLabel: "Qualität",
        qualitySmall: "Kleine Datei",
        qualityBalanced: "Ausgewogen",
        qualityHigh: "Hoch",
        qualityCaption: "Ausgewogen reicht für die meisten Fälle. Hoch behält jedes Detail und erzeugt größere Dateien.",
        frameRateLabel: "Bilder pro Sekunde",
        frameRateFormat: "%d fps",
        systemAudioToggle: "Ton des Mac aufnehmen",
        systemAudioCaption: "Alles, was du hörst, kommt als eigene Spur in die Aufnahme und lässt sich später stummschalten.",
        folderLabel: "Sichern unter",
        folderChoose: "Auswählen…",
        moreOptions: "Weitere Optionen",
        copyButton: "Kopieren",
        saveButton: "Sichern",
        discardButton: "Löschen",
        copiedHUD: "Aufnahme kopiert",
        savedHUDFormat: "Gesichert in %@",
        recordFailed: "Der Bildschirm konnte nicht aufgenommen werden",
        noSpaceTitle: "Zu wenig Speicherplatz für die Aufnahme",
        noSpaceMessage: "Gib Speicherplatz frei und versuche es erneut.",
        stoppedNoSpaceHUD: "Aufnahme gestoppt, der Speicher ist fast voll",
        shortcutLabel: "Kurzbefehl",
        editorTitle: "Aufnahme",
        saveVideoButton: "Sichern",
        saveGIFButton: "Als GIF sichern",
        exportingLabel: "Wird gesichert…",
        cancelButton: "Abbrechen",
        exportFailed: "Die Aufnahme konnte nicht gesichert werden",
        gifTooLongFormat: "Ein GIF darf höchstens %d Sekunden lang sein",
        gifSizeLabel: "GIF-Größe",
        gifSizeSmall: "Klein",
        gifSizeMedium: "Mittel",
        gifSizeLarge: "Groß",
        gifFrameRateLabel: "Flüssige Bewegung",
        discardTitle: "Diese Aufnahme löschen?",
        discardMessage: "Sie wurde noch nirgendwo gesichert.",
        openEditorToggle: "Editor nach der Aufnahme öffnen",
        openEditorCaption: "Die Aufnahme wird geöffnet und lässt sich sofort kürzen, stummschalten und sichern. Schalte die Option aus, um die Datei direkt zu erhalten.",
        lookLabel: "Stil",
        lookRaw: "Original",
        lookClean: "Sanft",
        lookStudio: "Studio",
        lookCaption: "Ein Ausgangspunkt. Was du unten änderst, bleibt so.",
        pointerSectionLabel: "Zeiger",
        pointerShowToggle: "Zeiger anzeigen",
        pointerSmoothingLabel: "Glättung",
        pointerSmoothingOff: "Keine",
        pointerSmoothingLight: "Leicht",
        pointerSmoothingSmooth: "Weich",
        pointerSmoothingCinematic: "Filmisch",
        pointerSizeLabel: "Größe",
        clickRingToggle: "Klicks markieren",
        zoomSectionLabel: "Zoom",
        zoomToggle: "Bei jedem Klick zoomen",
        zoomAmountLabel: "Stärke",
        backgroundSectionLabel: "Hintergrund",
        shapeLabel: "Form",
        shapeOriginal: "Original",
        shapeWide: "Breit",
        shapeSquare: "Quadrat",
        shapeVertical: "Hoch",
        noPointerNote: "Bei dieser Aufnahme wurde der Zeiger noch nicht aufgezeichnet. Deshalb gibt es nichts zu glätten und nichts zum Zoomen.",
        zoomLaneEmptyHint: "Hier klicken für einen Zoom",
        addZoomButton: "Zoom hinzufügen",
        removeZoom: "Entfernen",
        thisZoomLabel: "Dieser Zoom",
        zoomWhereLabel: "Ziel",
        zoomFollowsPointer: "Folgt dem Zeiger",
        zoomPickSpot: "Stelle wählen",
        zoomPickSpotHint: "Stelle im Bild anklicken",
        regenerateZooms: "Wieder ein Zoom pro Klick",
        backToOptions: "Alle Optionen",
        cutOutButton: "Herausschneiden",
        cutHint: "Über den Filmstreifen ziehen, um einen Teil zum Entfernen zu wählen",
        addTextButton: "Text hinzufügen",
        textLaneEmptyHint: "Hier klicken für Text",
        thisTextLabel: "Dieser Text",
        textPlaceholder: "Dein Text hier",
        textContentLabel: "Text",
        textSizeLabel: "Größe",
        textPositionLabel: "Position",
        textColorLabel: "Farbe",
        removeText: "Entfernen",
        copyAndDeleteButton: "Kopieren und löschen",
        saveAsButton: "Sichern unter…",
        discardSavedMessage: "Gesicherte und kopierte Dateien bleiben an ihrem Speicherort.",
        presetsButton: "Voreinstellungen",
        savePreset: "Aktuelle Voreinstellung sichern…",
        presetNamePlaceholder: "Name der Voreinstellung",
        removePreset: "Voreinstellung entfernen",
        zoomEmptyTitle: "Noch keine Zooms",
        zoomEmptyCaption: "Erstelle sie aus deinen Klicks oder füge einen zur Zeitleiste hinzu.",
        createAutomaticZooms: "Automatische Zooms erstellen",
        typingZoomToggle: "Beim Tippen eingezoomt bleiben",
        typingZoomCaption: "Nach einem Klick hält das Tippen den automatischen Zoom an dieser Stelle.",
        microphoneToggle: "Mikrofon aufnehmen",
        microphoneCaption: "Deine Stimme kommt auf eine eigene Spur und bleibt im Editor anpassbar.",
        systemAudioTrackLabel: "Mac-Ton",
        microphoneTrackLabel: "Mikrofon",
        audioVolumeLabel: "Lautstärke",
        removeAudio: "Entfernen",
        restoreAudio: "Wiederherstellen",
        microphoneUnavailableHUD: "Mikrofon nicht verfügbar",
        microphonePermissionName: "Mikrofon",
        microphonePermissionExplain: "Nimmt deine Stimme auf Wunsch in Bildschirmaufnahmen auf.",
        automaticZoomToggle: "Zooms automatisch hinzufügen",
        automaticZoomCaption: "Deaktivieren, um neue Aufnahmen ohne Zooms zu beginnen. Im Editor kannst du sie weiterhin hinzufügen.",
        pauseButton: "Aufnahme pausieren",
        resumeButton: "Aufnahme fortsetzen",
        blurLaneLabel: "Unschärfe",
        addBlurButton: "Bereich unkenntlich machen",
        blurLaneEmptyHint: "Hier klicken, um eine Unschärfe hinzuzufügen",
        thisBlurLabel: "Diese Unschärfe",
        blurPickArea: "Bereich wählen",
        blurPickAreaHint: "Über das ziehen, was verborgen bleiben soll",
        blurCaption: "Bleibt verborgen, solange der Block in der Zeitleiste dauert.",
        addImageButton: "Bild hinzufügen",
        imageLaneLabel: "Bild",
        imageLaneEmptyHint: "Hier klicken, um ein Bild hinzuzufügen",
        thisImageLabel: "Dieses Bild",
        imageSizeLabel: "Größe",
        imageOpacityLabel: "Deckkraft",
        imagePositionLabel: "Position",
        imageImportFailed: "Dieses Bild konnte nicht hinzugefügt werden."
    )

    static let fr = RecorderFeatureStrings(
        pageTitle: "Enregistrement de l’écran",
        hubDescription: "Enregistre une zone, une fenêtre ou l’écran, puis permet de retoucher la vidéo",
        panelCaption: "Enregistrez une zone, une fenêtre ou tout l’écran",
        startButton: "Lancer l’enregistrement",
        stopButton: "Arrêter l’enregistrement",
        fileNamePrefix: "Enregistrement",
        selectionPurpose: "Choisissez ce que vous voulez enregistrer",
        indicatorTooltip: "Commandes d’enregistrement",
        countdownLabel: "Compte à rebours",
        countdownOff: "Aucun",
        countdownSecondsFormat: "%d s",
        qualityLabel: "Qualité",
        qualitySmall: "Fichier léger",
        qualityBalanced: "Équilibrée",
        qualityHigh: "Élevée",
        qualityCaption: "Équilibrée convient à la plupart des usages. Élevée garde tous les détails et donne des fichiers plus lourds.",
        frameRateLabel: "Images par seconde",
        frameRateFormat: "%d i/s",
        systemAudioToggle: "Enregistrer le son du Mac",
        systemAudioCaption: "Tout ce que vous entendez est enregistré sur une piste à part, pour pouvoir le couper plus tard.",
        folderLabel: "Enregistrer dans",
        folderChoose: "Choisir…",
        moreOptions: "Plus d’options",
        copyButton: "Copier",
        saveButton: "Enregistrer",
        discardButton: "Supprimer",
        copiedHUD: "Enregistrement copié",
        savedHUDFormat: "Enregistré dans %@",
        recordFailed: "L’écran n’a pas pu être enregistré",
        noSpaceTitle: "Espace insuffisant pour enregistrer",
        noSpaceMessage: "Libérez de l’espace sur le disque et réessayez.",
        stoppedNoSpaceHUD: "Enregistrement arrêté, le disque est presque plein",
        shortcutLabel: "Raccourci",
        editorTitle: "Enregistrement",
        saveVideoButton: "Enregistrer",
        saveGIFButton: "Enregistrer en GIF",
        exportingLabel: "Enregistrement en cours…",
        cancelButton: "Annuler",
        exportFailed: "Impossible d’enregistrer la vidéo",
        gifTooLongFormat: "Un GIF peut durer jusqu’à %d secondes",
        gifSizeLabel: "Taille du GIF",
        gifSizeSmall: "Petite",
        gifSizeMedium: "Moyenne",
        gifSizeLarge: "Grande",
        gifFrameRateLabel: "Fluidité du GIF",
        discardTitle: "Supprimer cet enregistrement\u{00A0}?",
        discardMessage: "Il n’a encore été enregistré nulle part.",
        openEditorToggle: "Ouvrir l’éditeur après l’enregistrement",
        openEditorCaption: "La vidéo s’ouvre pour que vous puissiez la rogner, couper le son et l’enregistrer. Désactivez cette option pour obtenir le fichier tout de suite.",
        lookLabel: "Style",
        lookRaw: "Original",
        lookClean: "Fluide",
        lookStudio: "Studio",
        lookCaption: "Un point de départ. Ce que vous modifiez ci-dessous est conservé.",
        pointerSectionLabel: "Pointeur",
        pointerShowToggle: "Afficher le pointeur",
        pointerSmoothingLabel: "Lissage",
        pointerSmoothingOff: "Aucun",
        pointerSmoothingLight: "Léger",
        pointerSmoothingSmooth: "Fluide",
        pointerSmoothingCinematic: "Cinématique",
        pointerSizeLabel: "Taille",
        clickRingToggle: "Marquer les clics",
        zoomSectionLabel: "Zoom",
        zoomToggle: "Zoomer à chaque clic",
        zoomAmountLabel: "Intensité",
        backgroundSectionLabel: "Arrière-plan",
        shapeLabel: "Forme",
        shapeOriginal: "Original",
        shapeWide: "Large",
        shapeSquare: "Carré",
        shapeVertical: "Vertical",
        noPointerNote: "Cet enregistrement a été réalisé sans suivi du pointeur. Il n’y a donc rien à lisser ni à agrandir.",
        zoomLaneEmptyHint: "Cliquez ici pour ajouter un zoom",
        addZoomButton: "Ajouter un zoom",
        removeZoom: "Supprimer",
        thisZoomLabel: "Ce zoom",
        zoomWhereLabel: "Ce qu’il vise",
        zoomFollowsPointer: "Suit le pointeur",
        zoomPickSpot: "Choisir un point",
        zoomPickSpotHint: "Cliquez dans l’image pour placer le point",
        regenerateZooms: "Revenir à un zoom par clic",
        backToOptions: "Toutes les options",
        cutOutButton: "Couper",
        cutHint: "Faites glisser sur la pellicule pour choisir le passage à retirer",
        addTextButton: "Ajouter du texte",
        textLaneEmptyHint: "Cliquez ici pour ajouter du texte",
        thisTextLabel: "Ce texte",
        textPlaceholder: "Votre texte ici",
        textContentLabel: "Texte",
        textSizeLabel: "Taille",
        textPositionLabel: "Position",
        textColorLabel: "Couleur",
        removeText: "Supprimer",
        copyAndDeleteButton: "Copier et supprimer",
        saveAsButton: "Enregistrer sous…",
        discardSavedMessage: "Les fichiers enregistrés et copiés resteront à leur emplacement.",
        presetsButton: "Préréglages",
        savePreset: "Enregistrer le préréglage actuel…",
        presetNamePlaceholder: "Nom du préréglage",
        removePreset: "Supprimer le préréglage",
        zoomEmptyTitle: "Aucun zoom pour le moment",
        zoomEmptyCaption: "Créez-les à partir de vos clics ou ajoutez-en un à la chronologie.",
        createAutomaticZooms: "Créer des zooms automatiques",
        typingZoomToggle: "Garder le zoom pendant la saisie",
        typingZoomCaption: "Après un clic, la saisie maintient le zoom automatique sur cet endroit.",
        microphoneToggle: "Enregistrer le micro",
        microphoneCaption: "Votre voix va sur une piste séparée et reste réglable dans l’éditeur.",
        systemAudioTrackLabel: "Son du Mac",
        microphoneTrackLabel: "Micro",
        audioVolumeLabel: "Volume",
        removeAudio: "Retirer",
        restoreAudio: "Restaurer",
        microphoneUnavailableHUD: "Microphone indisponible",
        microphonePermissionName: "Microphone",
        microphonePermissionExplain: "Permet d’ajouter votre voix aux enregistrements d’écran si vous l’activez.",
        automaticZoomToggle: "Ajouter les zooms automatiquement",
        automaticZoomCaption: "Désactivez cette option pour commencer sans zoom. Vous pourrez toujours en ajouter dans l’éditeur.",
        pauseButton: "Mettre l’enregistrement en pause",
        resumeButton: "Reprendre l’enregistrement",
        blurLaneLabel: "Flou",
        addBlurButton: "Flouter une zone",
        blurLaneEmptyHint: "Cliquez ici pour ajouter un flou",
        thisBlurLabel: "Ce flou",
        blurPickArea: "Choisir la zone",
        blurPickAreaHint: "Faites glisser sur ce qui doit rester caché",
        blurCaption: "Reste caché tant que son bloc dure dans la chronologie.",
        addImageButton: "Ajouter une image",
        imageLaneLabel: "Image",
        imageLaneEmptyHint: "Cliquez ici pour ajouter une image",
        thisImageLabel: "Cette image",
        imageSizeLabel: "Taille",
        imageOpacityLabel: "Opacité",
        imagePositionLabel: "Position",
        imageImportFailed: "Impossible d’ajouter cette image."
    )

    static let it = RecorderFeatureStrings(
        pageTitle: "Registrazione schermo",
        hubDescription: "Registra un’area, una finestra o lo schermo, e dopo puoi modificare il video",
        panelCaption: "Registra un’area, una finestra o tutto lo schermo",
        startButton: "Registra ora",
        stopButton: "Interrompi registrazione",
        fileNamePrefix: "Registrazione",
        selectionPurpose: "Scegli cosa registrare",
        indicatorTooltip: "Controlli di registrazione",
        countdownLabel: "Conto alla rovescia",
        countdownOff: "Disattivato",
        countdownSecondsFormat: "%d s",
        qualityLabel: "Qualità",
        qualitySmall: "File piccolo",
        qualityBalanced: "Bilanciata",
        qualityHigh: "Alta",
        qualityCaption: "Bilanciata va bene quasi sempre. Alta conserva ogni dettaglio e crea file più grandi.",
        frameRateLabel: "Fotogrammi al secondo",
        frameRateFormat: "%d fps",
        systemAudioToggle: "Registra l’audio del Mac",
        systemAudioCaption: "Tutto quello che senti finisce nella registrazione, su una traccia separata, così puoi silenziarla dopo.",
        folderLabel: "Salva in",
        folderChoose: "Scegli…",
        moreOptions: "Altre opzioni",
        copyButton: "Copia",
        saveButton: "Salva",
        discardButton: "Elimina",
        copiedHUD: "Registrazione copiata",
        savedHUDFormat: "Salvata in %@",
        recordFailed: "Non è stato possibile registrare lo schermo",
        noSpaceTitle: "Spazio insufficiente per registrare",
        noSpaceMessage: "Libera spazio sul disco e riprova.",
        stoppedNoSpaceHUD: "Registrazione interrotta, il disco è quasi pieno",
        shortcutLabel: "Abbreviazione",
        editorTitle: "Registrazione",
        saveVideoButton: "Salva",
        saveGIFButton: "Salva come GIF",
        exportingLabel: "Salvataggio…",
        cancelButton: "Annulla",
        exportFailed: "Non è stato possibile salvare la registrazione",
        gifTooLongFormat: "Una GIF può durare al massimo %d secondi",
        gifSizeLabel: "Dimensione GIF",
        gifSizeSmall: "Piccola",
        gifSizeMedium: "Media",
        gifSizeLarge: "Grande",
        gifFrameRateLabel: "Fluidità GIF",
        discardTitle: "Eliminare questa registrazione?",
        discardMessage: "Non è ancora stata salvata da nessuna parte.",
        openEditorToggle: "Apri l’editor dopo la registrazione",
        openEditorCaption: "La registrazione si apre nell’editor, dove puoi tagliarla, disattivare l’audio e salvarla. Disattiva questa opzione per avere subito il file.",
        lookLabel: "Stile",
        lookRaw: "Originale",
        lookClean: "Fluido",
        lookStudio: "Studio",
        lookCaption: "Un punto di partenza. Le modifiche qui sotto restano.",
        pointerSectionLabel: "Puntatore",
        pointerShowToggle: "Mostra il puntatore",
        pointerSmoothingLabel: "Fluidità",
        pointerSmoothingOff: "Nessuna",
        pointerSmoothingLight: "Leggera",
        pointerSmoothingSmooth: "Morbida",
        pointerSmoothingCinematic: "Cinematica",
        pointerSizeLabel: "Dimensione",
        clickRingToggle: "Evidenzia i clic",
        zoomSectionLabel: "Zoom",
        zoomToggle: "Ingrandisci a ogni clic",
        zoomAmountLabel: "Quanto ingrandire",
        backgroundSectionLabel: "Sfondo",
        shapeLabel: "Forma",
        shapeOriginal: "Originale",
        shapeWide: "Panoramica",
        shapeSquare: "Quadrata",
        shapeVertical: "Verticale",
        noPointerNote: "Questa registrazione è stata fatta senza seguire il puntatore, quindi non c’è nulla da rendere fluido o da ingrandire.",
        zoomLaneEmptyHint: "Fai clic qui per aggiungere uno zoom",
        addZoomButton: "Aggiungi uno zoom",
        removeZoom: "Rimuovi",
        thisZoomLabel: "Questo zoom",
        zoomWhereLabel: "Dove inquadra",
        zoomFollowsPointer: "Segue il puntatore",
        zoomPickSpot: "Scegli un punto",
        zoomPickSpotHint: "Fai clic sull’immagine per puntare lo zoom",
        regenerateZooms: "Torna a uno zoom per clic",
        backToOptions: "Tutte le opzioni",
        cutOutButton: "Taglia via",
        cutHint: "Trascina sulla pellicola per scegliere la parte da togliere",
        addTextButton: "Aggiungi testo",
        textLaneEmptyHint: "Fai clic qui per aggiungere del testo",
        thisTextLabel: "Questo testo",
        textPlaceholder: "Il tuo testo qui",
        textContentLabel: "Testo",
        textSizeLabel: "Dimensione",
        textPositionLabel: "Posizione",
        textColorLabel: "Colore",
        removeText: "Rimuovi",
        copyAndDeleteButton: "Copia ed elimina",
        saveAsButton: "Salva con nome…",
        discardSavedMessage: "I file salvati e copiati resteranno dove si trovano.",
        presetsButton: "Preset",
        savePreset: "Salva preset attuale…",
        presetNamePlaceholder: "Nome del preset",
        removePreset: "Rimuovi preset",
        zoomEmptyTitle: "Nessuno zoom",
        zoomEmptyCaption: "Creali dai tuoi clic o aggiungine uno alla timeline.",
        createAutomaticZooms: "Crea zoom automatici",
        typingZoomToggle: "Mantieni lo zoom mentre scrivi",
        typingZoomCaption: "Dopo un clic, la digitazione mantiene lo zoom automatico su quel punto.",
        microphoneToggle: "Registra il microfono",
        microphoneCaption: "La tua voce va su una traccia separata e resta regolabile nell’editor.",
        systemAudioTrackLabel: "Audio del Mac",
        microphoneTrackLabel: "Microfono",
        audioVolumeLabel: "Volume",
        removeAudio: "Rimuovi",
        restoreAudio: "Ripristina",
        microphoneUnavailableHUD: "Microfono non disponibile",
        microphonePermissionName: "Microfono",
        microphonePermissionExplain: "Include la tua voce nelle registrazioni dello schermo quando lo attivi.",
        automaticZoomToggle: "Aggiungi zoom automaticamente",
        automaticZoomCaption: "Disattiva per iniziare le nuove registrazioni senza zoom. Puoi comunque aggiungerli nell’editor.",
        pauseButton: "Metti in pausa la registrazione",
        resumeButton: "Riprendi la registrazione",
        blurLaneLabel: "Sfocatura",
        addBlurButton: "Sfoca un’area",
        blurLaneEmptyHint: "Fai clic qui per aggiungere una sfocatura",
        thisBlurLabel: "Questa sfocatura",
        blurPickArea: "Scegli l’area",
        blurPickAreaHint: "Trascina su ciò che deve restare nascosto",
        blurCaption: "Resta nascosto finché dura il blocco nella timeline.",
        addImageButton: "Aggiungi immagine",
        imageLaneLabel: "Immagine",
        imageLaneEmptyHint: "Fai clic qui per aggiungere un’immagine",
        thisImageLabel: "Questa immagine",
        imageSizeLabel: "Dimensione",
        imageOpacityLabel: "Opacità",
        imagePositionLabel: "Posizione",
        imageImportFailed: "Impossibile aggiungere questa immagine."
    )

    static let ja = RecorderFeatureStrings(
        pageTitle: "画面収録",
        hubDescription: "範囲やウインドウ、画面を収録して、あとから編集できます",
        panelCaption: "範囲やウインドウ、画面全体を収録します",
        startButton: "今すぐ収録",
        stopButton: "収録を停止",
        fileNamePrefix: "画面収録",
        selectionPurpose: "収録する対象を選択",
        indicatorTooltip: "収録コントロール",
        countdownLabel: "カウントダウン",
        countdownOff: "オフ",
        countdownSecondsFormat: "%d秒",
        qualityLabel: "品質",
        qualitySmall: "小さいファイル",
        qualityBalanced: "バランス",
        qualityHigh: "高品質",
        qualityCaption: "たいていの用途にはバランスで十分です。高品質は細部まで残りますが、ファイルは大きくなります。",
        frameRateLabel: "フレームレート",
        frameRateFormat: "%d fps",
        systemAudioToggle: "Macの音を収録",
        systemAudioCaption: "聞こえている音がすべて別のトラックに収録されるので、あとから消せます。",
        folderLabel: "保存先",
        folderChoose: "選択…",
        moreOptions: "その他のオプション",
        copyButton: "コピー",
        saveButton: "保存",
        discardButton: "削除",
        copiedHUD: "画面収録をコピーしました",
        savedHUDFormat: "%@に保存しました",
        recordFailed: "画面を収録できませんでした",
        noSpaceTitle: "収録するための空き容量が足りません",
        noSpaceMessage: "ディスクの空き容量を増やしてから、もう一度お試しください。",
        stoppedNoSpaceHUD: "空き容量が少ないため収録を停止しました",
        shortcutLabel: "ショートカット",
        editorTitle: "画面収録",
        saveVideoButton: "保存",
        saveGIFButton: "GIFとして保存",
        exportingLabel: "保存中…",
        cancelButton: "キャンセル",
        exportFailed: "画面収録を保存できませんでした",
        gifTooLongFormat: "GIFの長さは最大%d秒です",
        gifSizeLabel: "GIFのサイズ",
        gifSizeSmall: "小",
        gifSizeMedium: "中",
        gifSizeLarge: "大",
        gifFrameRateLabel: "動きのなめらかさ",
        discardTitle: "この画面収録を削除しますか？",
        discardMessage: "まだどこにも保存されていません。",
        openEditorToggle: "収録後にエディタを開く",
        openEditorCaption: "収録した動画がそのまま開き、トリムや消音、保存をすぐに行えます。オフにすると、エディタを開かずにファイルがそのまま保存されます。",
        lookLabel: "見た目",
        lookRaw: "オリジナル",
        lookClean: "なめらか",
        lookStudio: "スタジオ",
        lookCaption: "はじめの設定です。下の項目を変えると、その変更が残ります。",
        pointerSectionLabel: "ポインタ",
        pointerShowToggle: "ポインタを表示",
        pointerSmoothingLabel: "なめらかさ",
        pointerSmoothingOff: "なし",
        pointerSmoothingLight: "弱め",
        pointerSmoothingSmooth: "強め",
        pointerSmoothingCinematic: "シネマティック",
        pointerSizeLabel: "サイズ",
        clickRingToggle: "クリックした場所を示す",
        zoomSectionLabel: "ズーム",
        zoomToggle: "クリックのたびにズーム",
        zoomAmountLabel: "ズームの強さ",
        backgroundSectionLabel: "背景",
        shapeLabel: "形状",
        shapeOriginal: "オリジナル",
        shapeWide: "横長",
        shapeSquare: "正方形",
        shapeVertical: "縦長",
        noPointerNote: "ポインタを記録する前の録画なので、なめらかにすることもズームすることもできません。",
        zoomLaneEmptyHint: "クリックしてズームを追加",
        addZoomButton: "ズームを追加",
        removeZoom: "削除",
        thisZoomLabel: "このズーム",
        zoomWhereLabel: "ズームの中心",
        zoomFollowsPointer: "ポインタを追う",
        zoomPickSpot: "場所を選ぶ",
        zoomPickSpotHint: "映像をクリックして指定",
        regenerateZooms: "クリックごとに作り直す",
        backToOptions: "すべての設定",
        cutOutButton: "切り取る",
        cutHint: "フィルムをドラッグして削除する部分を選びます",
        addTextButton: "テキストを追加",
        textLaneEmptyHint: "クリックしてテキストを追加",
        thisTextLabel: "このテキスト",
        textPlaceholder: "ここにテキスト",
        textContentLabel: "テキスト",
        textSizeLabel: "サイズ",
        textPositionLabel: "位置",
        textColorLabel: "色",
        removeText: "削除",
        copyAndDeleteButton: "コピーして削除",
        saveAsButton: "別名で保存…",
        discardSavedMessage: "保存またはコピーしたファイルはそのまま残ります。",
        presetsButton: "プリセット",
        savePreset: "現在のプリセットを保存…",
        presetNamePlaceholder: "プリセット名",
        removePreset: "プリセットを削除",
        zoomEmptyTitle: "ズームはまだありません",
        zoomEmptyCaption: "クリックから作成するか、タイムラインに追加してください。",
        createAutomaticZooms: "自動ズームを作成",
        typingZoomToggle: "入力中はズームを維持",
        typingZoomCaption: "クリック後に入力すると、その位置の自動ズームが続きます。",
        microphoneToggle: "マイクを収録",
        microphoneCaption: "声は別のトラックに収録され、エディタで調整できます。",
        systemAudioTrackLabel: "Macの音",
        microphoneTrackLabel: "マイク",
        audioVolumeLabel: "音量",
        removeAudio: "削除",
        restoreAudio: "復元",
        microphoneUnavailableHUD: "マイクを使用できません",
        microphonePermissionName: "マイク",
        microphonePermissionExplain: "オンにすると画面収録に声を含められます。",
        automaticZoomToggle: "ズームを自動的に追加",
        automaticZoomCaption: "オフにすると、新しい収録はズームなしで始まります。エディタで後から追加できます。",
        pauseButton: "収録を一時停止",
        resumeButton: "収録を再開",
        blurLaneLabel: "ぼかし",
        addBlurButton: "範囲をぼかす",
        blurLaneEmptyHint: "ここをクリックしてぼかしを追加",
        thisBlurLabel: "このぼかし",
        blurPickArea: "範囲を選ぶ",
        blurPickAreaHint: "隠したい部分をドラッグ",
        blurCaption: "タイムラインのブロックが続く間は隠れたままです。",
        addImageButton: "画像を追加",
        imageLaneLabel: "画像",
        imageLaneEmptyHint: "クリックして画像を追加",
        thisImageLabel: "この画像",
        imageSizeLabel: "サイズ",
        imageOpacityLabel: "不透明度",
        imagePositionLabel: "位置",
        imageImportFailed: "この画像を追加できませんでした。"
    )

    static let ko = RecorderFeatureStrings(
        pageTitle: "화면 기록",
        hubDescription: "영역, 윈도우 또는 화면을 기록하고 나중에 편집합니다",
        panelCaption: "영역, 윈도우 또는 전체 화면을 기록합니다",
        startButton: "지금 기록",
        stopButton: "기록 중단",
        fileNamePrefix: "화면 기록",
        selectionPurpose: "기록할 대상 선택",
        indicatorTooltip: "화면 기록 제어",
        countdownLabel: "카운트다운",
        countdownOff: "끔",
        countdownSecondsFormat: "%d초",
        qualityLabel: "품질",
        qualitySmall: "작은 파일",
        qualityBalanced: "균형",
        qualityHigh: "높음",
        qualityCaption: "대부분의 경우 균형으로 충분합니다. 높음은 세세한 부분까지 남기지만 파일이 커집니다.",
        frameRateLabel: "초당 프레임 수",
        frameRateFormat: "%d fps",
        systemAudioToggle: "Mac의 소리 기록",
        systemAudioCaption: "들리는 모든 소리가 별도 트랙으로 함께 기록되므로 나중에 소리를 끌 수 있습니다.",
        folderLabel: "저장 위치",
        folderChoose: "선택…",
        moreOptions: "추가 옵션",
        copyButton: "복사",
        saveButton: "저장",
        discardButton: "삭제",
        copiedHUD: "화면 기록을 복사했습니다",
        savedHUDFormat: "%@에 저장했습니다",
        recordFailed: "화면을 기록할 수 없습니다",
        noSpaceTitle: "기록할 공간이 부족합니다",
        noSpaceMessage: "디스크 공간을 확보한 다음 다시 시도하세요.",
        stoppedNoSpaceHUD: "디스크가 거의 차서 기록을 중단했습니다",
        shortcutLabel: "단축키",
        editorTitle: "화면 기록",
        saveVideoButton: "저장",
        saveGIFButton: "GIF로 저장",
        exportingLabel: "저장 중…",
        cancelButton: "취소",
        exportFailed: "화면 기록을 저장할 수 없습니다",
        gifTooLongFormat: "GIF는 최대 %d초까지 만들 수 있습니다",
        gifSizeLabel: "GIF 크기",
        gifSizeSmall: "작게",
        gifSizeMedium: "중간",
        gifSizeLarge: "크게",
        gifFrameRateLabel: "GIF 부드러운 정도",
        discardTitle: "이 화면 기록을 삭제하시겠습니까?",
        discardMessage: "아직 어디에도 저장되지 않았습니다.",
        openEditorToggle: "화면 기록 후 편집기 열기",
        openEditorCaption: "화면 기록이 열리면 바로 다듬고, 음소거하고, 저장할 수 있습니다. 이 옵션을 끄면 편집기 없이 파일이 바로 저장됩니다.",
        lookLabel: "스타일",
        lookRaw: "원본",
        lookClean: "부드럽게",
        lookStudio: "스튜디오",
        lookCaption: "시작점입니다. 아래에서 바꾼 내용은 유지됩니다.",
        pointerSectionLabel: "포인터",
        pointerShowToggle: "포인터 표시",
        pointerSmoothingLabel: "부드러움",
        pointerSmoothingOff: "없음",
        pointerSmoothingLight: "약하게",
        pointerSmoothingSmooth: "부드럽게",
        pointerSmoothingCinematic: "시네마틱",
        pointerSizeLabel: "크기",
        clickRingToggle: "클릭한 곳 표시",
        zoomSectionLabel: "확대/축소",
        zoomToggle: "클릭할 때마다 확대",
        zoomAmountLabel: "확대 정도",
        backgroundSectionLabel: "배경",
        shapeLabel: "모양",
        shapeOriginal: "원본",
        shapeWide: "와이드",
        shapeSquare: "정사각형",
        shapeVertical: "세로",
        noPointerNote: "포인터를 기록하지 않고 녹화한 영상이라 부드럽게 하거나 확대할 수 없습니다.",
        zoomLaneEmptyHint: "여기를 클릭해 확대를 추가하세요",
        addZoomButton: "확대 추가",
        removeZoom: "제거",
        thisZoomLabel: "선택한 확대",
        zoomWhereLabel: "확대 위치",
        zoomFollowsPointer: "포인터 따라가기",
        zoomPickSpot: "지점 직접 선택",
        zoomPickSpotHint: "영상을 클릭해 지점을 지정하세요",
        regenerateZooms: "클릭마다 확대 하나로 되돌리기",
        backToOptions: "전체 옵션",
        cutOutButton: "잘라내기",
        cutHint: "필름을 드래그해 지울 구간을 선택하세요",
        addTextButton: "텍스트 추가",
        textLaneEmptyHint: "여기를 클릭해 텍스트를 추가하세요",
        thisTextLabel: "선택한 텍스트",
        textPlaceholder: "여기에 텍스트 입력",
        textContentLabel: "텍스트",
        textSizeLabel: "크기",
        textPositionLabel: "위치",
        textColorLabel: "색상",
        removeText: "제거",
        copyAndDeleteButton: "복사하고 삭제",
        saveAsButton: "다른 이름으로 저장…",
        discardSavedMessage: "저장하거나 복사한 파일은 그대로 유지됩니다.",
        presetsButton: "프리셋",
        savePreset: "현재 프리셋 저장…",
        presetNamePlaceholder: "프리셋 이름",
        removePreset: "프리셋 제거",
        zoomEmptyTitle: "아직 확대 없음",
        zoomEmptyCaption: "클릭으로 만들거나 타임라인에 하나를 추가하세요.",
        createAutomaticZooms: "자동 확대 만들기",
        typingZoomToggle: "입력하는 동안 확대 유지",
        typingZoomCaption: "클릭 후 입력하면 자동 확대가 그 위치에 유지됩니다.",
        microphoneToggle: "마이크 녹음",
        microphoneCaption: "음성이 별도 트랙에 녹음되며 편집기에서 조절할 수 있습니다.",
        systemAudioTrackLabel: "Mac 소리",
        microphoneTrackLabel: "마이크",
        audioVolumeLabel: "음량",
        removeAudio: "제거",
        restoreAudio: "복원",
        microphoneUnavailableHUD: "마이크를 사용할 수 없습니다",
        microphonePermissionName: "마이크",
        microphonePermissionExplain: "켜면 화면 녹화에 음성을 포함합니다.",
        automaticZoomToggle: "확대 효과 자동 추가",
        automaticZoomCaption: "끄면 새 화면 기록이 확대 효과 없이 시작됩니다. 편집기에서 나중에 추가할 수 있습니다.",
        pauseButton: "화면 기록 일시 정지",
        resumeButton: "화면 기록 계속",
        blurLaneLabel: "흐림",
        addBlurButton: "영역 흐리게",
        blurLaneEmptyHint: "여기를 클릭해 흐림을 추가하세요",
        thisBlurLabel: "선택한 흐림",
        blurPickArea: "영역 선택",
        blurPickAreaHint: "숨길 부분 위로 드래그하세요",
        blurCaption: "타임라인의 블록이 지속되는 동안 숨겨집니다.",
        addImageButton: "이미지 추가",
        imageLaneLabel: "이미지",
        imageLaneEmptyHint: "여기를 클릭해 이미지를 추가하세요",
        thisImageLabel: "선택한 이미지",
        imageSizeLabel: "크기",
        imageOpacityLabel: "불투명도",
        imagePositionLabel: "위치",
        imageImportFailed: "이 이미지를 추가할 수 없습니다."
    )

    static let zhHans = RecorderFeatureStrings(
        pageTitle: "屏幕录制",
        hubDescription: "录制区域、窗口或屏幕，录完还能编辑",
        panelCaption: "录制一块区域、某个窗口或整个屏幕",
        startButton: "开始录制",
        stopButton: "停止录制",
        fileNamePrefix: "屏幕录制",
        selectionPurpose: "选择要录制的内容",
        indicatorTooltip: "录制控制",
        countdownLabel: "倒计时",
        countdownOff: "关闭",
        countdownSecondsFormat: "%d 秒",
        qualityLabel: "质量",
        qualitySmall: "小文件",
        qualityBalanced: "均衡",
        qualityHigh: "高",
        qualityCaption: "大多数情况用“均衡”就够了。“高”会保留每一处细节，文件也更大。",
        frameRateLabel: "帧速率",
        frameRateFormat: "%d fps",
        systemAudioToggle: "录制 Mac 的声音",
        systemAudioCaption: "你听到的声音都会一起录进去，单独放在一条音轨上，之后可以把它静音。",
        folderLabel: "存储到",
        folderChoose: "选择…",
        moreOptions: "更多选项",
        copyButton: "拷贝",
        saveButton: "存储",
        discardButton: "删除",
        copiedHUD: "录屏已拷贝",
        savedHUDFormat: "已存储到 %@",
        recordFailed: "无法录制屏幕",
        noSpaceTitle: "空间不足，无法录制",
        noSpaceMessage: "请腾出一些磁盘空间后再试。",
        stoppedNoSpaceHUD: "录制已停止，磁盘快满了",
        shortcutLabel: "快捷键",
        editorTitle: "屏幕录制",
        saveVideoButton: "存储",
        saveGIFButton: "存储为 GIF",
        exportingLabel: "正在存储…",
        cancelButton: "取消",
        exportFailed: "无法存储这段录制内容",
        gifTooLongFormat: "GIF 最长为 %d 秒",
        gifSizeLabel: "GIF 尺寸",
        gifSizeSmall: "小",
        gifSizeMedium: "中",
        gifSizeLarge: "大",
        gifFrameRateLabel: "GIF 流畅度",
        discardTitle: "要删除这段录制内容吗？",
        discardMessage: "这段内容还没有存储到任何位置。",
        openEditorToggle: "录制后打开编辑器",
        openEditorCaption: "录制的内容会自动打开，可以修剪、静音，然后存储。关闭后会直接得到文件。",
        lookLabel: "外观",
        lookRaw: "原始",
        lookClean: "流畅",
        lookStudio: "影棚",
        lookCaption: "这只是一个起点。下面的设置改了就会保留。",
        pointerSectionLabel: "指针",
        pointerShowToggle: "显示指针",
        pointerSmoothingLabel: "平滑度",
        pointerSmoothingOff: "无",
        pointerSmoothingLight: "轻微",
        pointerSmoothingSmooth: "顺滑",
        pointerSmoothingCinematic: "电影感",
        pointerSizeLabel: "大小",
        clickRingToggle: "标记点按位置",
        zoomSectionLabel: "缩放",
        zoomToggle: "每次点按时放大",
        zoomAmountLabel: "放大程度",
        backgroundSectionLabel: "背景",
        shapeLabel: "形状",
        shapeOriginal: "原始",
        shapeWide: "宽屏",
        shapeSquare: "方形",
        shapeVertical: "竖屏",
        noPointerNote: "这段录制没有跟踪指针，所以没有可以平滑的内容。手动放置的缩放仍然有效。",
        zoomLaneEmptyHint: "点按此处添加缩放",
        addZoomButton: "添加缩放",
        removeZoom: "移除",
        thisZoomLabel: "当前缩放",
        zoomWhereLabel: "对准方式",
        zoomFollowsPointer: "跟随指针",
        zoomPickSpot: "选取位置",
        zoomPickSpotHint: "点按画面选取位置",
        regenerateZooms: "改回每次点按一个缩放",
        backToOptions: "全部选项",
        cutOutButton: "剪掉",
        cutHint: "在胶片上拖动，选择要删除的片段",
        addTextButton: "添加文字",
        textLaneEmptyHint: "点按此处添加文字",
        thisTextLabel: "当前文字",
        textPlaceholder: "在此输入文字",
        textContentLabel: "文字",
        textSizeLabel: "大小",
        textPositionLabel: "位置",
        textColorLabel: "颜色",
        removeText: "移除",
        copyAndDeleteButton: "拷贝并删除",
        saveAsButton: "另存为…",
        discardSavedMessage: "已存储和已拷贝的文件会保留在原位置。",
        presetsButton: "预设",
        savePreset: "保存当前预设…",
        presetNamePlaceholder: "预设名称",
        removePreset: "移除预设",
        zoomEmptyTitle: "还没有缩放",
        zoomEmptyCaption: "根据点击创建，或在时间线上添加一个。",
        createAutomaticZooms: "创建自动缩放",
        typingZoomToggle: "输入时保持缩放",
        typingZoomCaption: "点击后继续输入，会让自动缩放停留在该位置。",
        microphoneToggle: "录制麦克风",
        microphoneCaption: "你的声音会进入独立音轨，并可在编辑器中调整。",
        systemAudioTrackLabel: "Mac 声音",
        microphoneTrackLabel: "麦克风",
        audioVolumeLabel: "音量",
        removeAudio: "移除",
        restoreAudio: "恢复",
        microphoneUnavailableHUD: "麦克风不可用",
        microphonePermissionName: "麦克风",
        microphonePermissionExplain: "开启后可在屏幕录制中加入你的声音。",
        automaticZoomToggle: "自动添加缩放",
        automaticZoomCaption: "关闭后，新录制将不带缩放。你仍可在编辑器中添加缩放。",
        pauseButton: "暂停录制",
        resumeButton: "继续录制",
        blurLaneLabel: "模糊",
        addBlurButton: "模糊一个区域",
        blurLaneEmptyHint: "点按此处添加模糊",
        thisBlurLabel: "当前模糊",
        blurPickArea: "选取区域",
        blurPickAreaHint: "拖过需要隐藏的内容",
        blurCaption: "在时间线上的区块持续期间保持隐藏。",
        addImageButton: "添加图片",
        imageLaneLabel: "图片",
        imageLaneEmptyHint: "点按此处添加图片",
        thisImageLabel: "当前图片",
        imageSizeLabel: "大小",
        imageOpacityLabel: "不透明度",
        imagePositionLabel: "位置",
        imageImportFailed: "无法添加此图片。"
    )

    static let zhTW = RecorderFeatureStrings(
        pageTitle: "螢幕錄製",
        hubDescription: "錄製區域、視窗或螢幕，錄完還能編輯",
        panelCaption: "錄製區域、視窗或整個螢幕",
        startButton: "立即錄製",
        stopButton: "停止錄製",
        fileNamePrefix: "螢幕錄製",
        selectionPurpose: "選擇要錄製的內容",
        indicatorTooltip: "錄製控制",
        countdownLabel: "倒數計時",
        countdownOff: "關閉",
        countdownSecondsFormat: "%d 秒",
        qualityLabel: "品質",
        qualitySmall: "小檔案",
        qualityBalanced: "平衡",
        qualityHigh: "高",
        qualityCaption: "「平衡」適合大部分情況。「高」會保留所有細節，檔案也比較大。",
        frameRateLabel: "每秒影格數",
        frameRateFormat: "%d fps",
        systemAudioToggle: "錄製 Mac 的聲音",
        systemAudioCaption: "你聽到的聲音都會錄進去，放在獨立的音軌，之後想靜音也可以。",
        folderLabel: "儲存位置",
        folderChoose: "選擇…",
        moreOptions: "更多選項",
        copyButton: "拷貝",
        saveButton: "儲存",
        discardButton: "刪除",
        copiedHUD: "已拷貝錄製檔",
        savedHUDFormat: "已儲存到 %@",
        recordFailed: "無法錄製螢幕",
        noSpaceTitle: "空間不足，無法錄製",
        noSpaceMessage: "請騰出一些磁碟空間後再試一次。",
        stoppedNoSpaceHUD: "已停止錄製，磁碟快滿了",
        shortcutLabel: "快速鍵",
        editorTitle: "錄影",
        saveVideoButton: "儲存",
        saveGIFButton: "儲存為 GIF",
        exportingLabel: "儲存中…",
        cancelButton: "取消",
        exportFailed: "無法儲存這段錄影",
        gifTooLongFormat: "GIF 長度最多 %d 秒",
        gifSizeLabel: "GIF 尺寸",
        gifSizeSmall: "小",
        gifSizeMedium: "中",
        gifSizeLarge: "大",
        gifFrameRateLabel: "GIF 流暢度",
        discardTitle: "要刪除這段錄影嗎？",
        discardMessage: "這段錄影還沒有儲存到任何地方。",
        openEditorToggle: "錄影結束後打開編輯器",
        openEditorCaption: "錄影會自動打開，可以先修剪、靜音再儲存。關閉後就直接取得檔案。",
        lookLabel: "風格",
        lookRaw: "原始",
        lookClean: "流暢",
        lookStudio: "專業",
        lookCaption: "這只是起點，下方任何調整都會保留。",
        pointerSectionLabel: "指標",
        pointerShowToggle: "顯示指標",
        pointerSmoothingLabel: "平滑度",
        pointerSmoothingOff: "無",
        pointerSmoothingLight: "輕微",
        pointerSmoothingSmooth: "平順",
        pointerSmoothingCinematic: "電影感",
        pointerSizeLabel: "大小",
        clickRingToggle: "標示點按位置",
        zoomSectionLabel: "縮放",
        zoomToggle: "每次點按時放大",
        zoomAmountLabel: "放大程度",
        backgroundSectionLabel: "背景",
        shapeLabel: "形狀",
        shapeOriginal: "原始",
        shapeWide: "寬幅",
        shapeSquare: "方形",
        shapeVertical: "直式",
        noPointerNote: "錄製這段影片時還沒有開始追蹤指標，所以沒有可以平滑或放大的內容。",
        zoomLaneEmptyHint: "按一下這裡加入縮放",
        addZoomButton: "加入縮放",
        removeZoom: "移除",
        thisZoomLabel: "這段縮放",
        zoomWhereLabel: "對準哪裡",
        zoomFollowsPointer: "跟隨指標",
        zoomPickSpot: "指定位置",
        zoomPickSpotHint: "按一下畫面指定位置",
        regenerateZooms: "依滑鼠點按重建縮放",
        backToOptions: "所有選項",
        cutOutButton: "剪掉",
        cutHint: "在影格條上拖曳，選擇要刪除的片段",
        addTextButton: "加入文字",
        textLaneEmptyHint: "按一下這裡加入文字",
        thisTextLabel: "這段文字",
        textPlaceholder: "在此輸入文字",
        textContentLabel: "文字",
        textSizeLabel: "大小",
        textPositionLabel: "位置",
        textColorLabel: "顏色",
        removeText: "移除",
        copyAndDeleteButton: "複製並刪除",
        saveAsButton: "另存新檔…",
        discardSavedMessage: "已儲存和複製的檔案會保留在原位置。",
        presetsButton: "預設組合",
        savePreset: "儲存目前的預設組合…",
        presetNamePlaceholder: "預設組合名稱",
        removePreset: "移除預設組合",
        zoomEmptyTitle: "還沒有縮放",
        zoomEmptyCaption: "根據點按建立，或在時間軸上加入一個。",
        createAutomaticZooms: "建立自動縮放",
        typingZoomToggle: "輸入時保持縮放",
        typingZoomCaption: "點按後繼續輸入，會讓自動縮放停留在該位置。",
        microphoneToggle: "錄製麥克風",
        microphoneCaption: "你的聲音會進入獨立音軌，並可在編輯器中調整。",
        systemAudioTrackLabel: "Mac 聲音",
        microphoneTrackLabel: "麥克風",
        audioVolumeLabel: "音量",
        removeAudio: "移除",
        restoreAudio: "還原",
        microphoneUnavailableHUD: "麥克風無法使用",
        microphonePermissionName: "麥克風",
        microphonePermissionExplain: "開啟後可在螢幕錄製中加入你的聲音。",
        automaticZoomToggle: "自動加入縮放",
        automaticZoomCaption: "關閉後，新錄影將不含縮放。你仍可在編輯器中加入縮放。",
        pauseButton: "暫停錄製",
        resumeButton: "繼續錄製",
        blurLaneLabel: "模糊",
        addBlurButton: "模糊一個區域",
        blurLaneEmptyHint: "按一下這裡加入模糊",
        thisBlurLabel: "這個模糊",
        blurPickArea: "選取區域",
        blurPickAreaHint: "拖曳過需要隱藏的內容",
        blurCaption: "在時間軸上的區塊持續期間保持隱藏。",
        addImageButton: "加入圖片",
        imageLaneLabel: "圖片",
        imageLaneEmptyHint: "按一下這裡加入圖片",
        thisImageLabel: "這張圖片",
        imageSizeLabel: "大小",
        imageOpacityLabel: "不透明度",
        imagePositionLabel: "位置",
        imageImportFailed: "無法加入這張圖片。"
    )

    static let zhHK = RecorderFeatureStrings(
        pageTitle: "螢幕錄製",
        hubDescription: "錄製選取範圍、視窗或螢幕，完成後可再編輯",
        panelCaption: "錄製選取範圍、視窗或整個螢幕",
        startButton: "開始錄製",
        stopButton: "停止錄製",
        fileNamePrefix: "螢幕錄製",
        selectionPurpose: "選擇要錄製的內容",
        indicatorTooltip: "錄製控制",
        countdownLabel: "倒數",
        countdownOff: "關閉",
        countdownSecondsFormat: "%d 秒",
        qualityLabel: "品質",
        qualitySmall: "檔案較小",
        qualityBalanced: "平衡",
        qualityHigh: "高",
        qualityCaption: "「平衡」適合大部分情況。「高」會保留所有細節，檔案亦會較大。",
        frameRateLabel: "每秒影格數",
        frameRateFormat: "%d fps",
        systemAudioToggle: "錄下 Mac 的聲音",
        systemAudioCaption: "你聽到的所有聲音都會錄進獨立音軌，之後可以隨時靜音。",
        folderLabel: "儲存位置",
        folderChoose: "選擇…",
        moreOptions: "更多選項",
        copyButton: "拷貝",
        saveButton: "儲存",
        discardButton: "刪除",
        copiedHUD: "錄影已拷貝",
        savedHUDFormat: "已儲存到 %@",
        recordFailed: "無法錄製螢幕",
        noSpaceTitle: "儲存空間不足，無法錄製",
        noSpaceMessage: "請騰出一些磁碟空間，再試一次。",
        stoppedNoSpaceHUD: "錄製已停止，磁碟幾乎已滿",
        shortcutLabel: "快速鍵",
        editorTitle: "錄影",
        saveVideoButton: "儲存",
        saveGIFButton: "儲存為 GIF",
        exportingLabel: "儲存中…",
        cancelButton: "取消",
        exportFailed: "無法儲存這段錄影",
        gifTooLongFormat: "GIF 最長 %d 秒",
        gifSizeLabel: "GIF 尺寸",
        gifSizeSmall: "小",
        gifSizeMedium: "中",
        gifSizeLarge: "大",
        gifFrameRateLabel: "GIF 流暢度",
        discardTitle: "要刪除這段錄影嗎？",
        discardMessage: "還未儲存到任何地方。",
        openEditorToggle: "錄影後開啟編輯器",
        openEditorCaption: "錄影完成後會開啟，可以修剪、靜音和儲存。關閉後就會直接取得檔案。",
        lookLabel: "風格",
        lookRaw: "原始",
        lookClean: "流暢",
        lookStudio: "專業",
        lookCaption: "只是起點。下方的設定改了就會保留。",
        pointerSectionLabel: "指標",
        pointerShowToggle: "顯示指標",
        pointerSmoothingLabel: "平滑度",
        pointerSmoothingOff: "無",
        pointerSmoothingLight: "輕微",
        pointerSmoothingSmooth: "平滑",
        pointerSmoothingCinematic: "電影感",
        pointerSizeLabel: "大小",
        clickRingToggle: "標示點按位置",
        zoomSectionLabel: "縮放",
        zoomToggle: "每次點按都放大",
        zoomAmountLabel: "放大程度",
        backgroundSectionLabel: "背景",
        shapeLabel: "形狀",
        shapeOriginal: "原始",
        shapeWide: "橫向",
        shapeSquare: "正方形",
        shapeVertical: "直向",
        noPointerNote: "這段影片錄製時並未追蹤指標，所以無法平滑或放大。",
        zoomLaneEmptyHint: "點按這裡加入縮放",
        addZoomButton: "加入縮放",
        removeZoom: "移除",
        thisZoomLabel: "這個縮放",
        zoomWhereLabel: "對準位置",
        zoomFollowsPointer: "跟隨指標",
        zoomPickSpot: "自選位置",
        zoomPickSpotHint: "點按畫面選定位置",
        regenerateZooms: "重設為每次點按一個縮放",
        backToOptions: "所有選項",
        cutOutButton: "剪走",
        cutHint: "在影格條上拖曳，選擇要刪除的片段",
        addTextButton: "加入文字",
        textLaneEmptyHint: "點按這裡加入文字",
        thisTextLabel: "這段文字",
        textPlaceholder: "在此輸入文字",
        textContentLabel: "文字",
        textSizeLabel: "大小",
        textPositionLabel: "位置",
        textColorLabel: "顏色",
        removeText: "移除",
        copyAndDeleteButton: "複製並刪除",
        saveAsButton: "另存新檔…",
        discardSavedMessage: "已儲存及複製的檔案會保留在原來位置。",
        presetsButton: "預設組合",
        savePreset: "儲存目前的預設組合…",
        presetNamePlaceholder: "預設組合名稱",
        removePreset: "移除預設組合",
        zoomEmptyTitle: "還沒有縮放",
        zoomEmptyCaption: "根據點按建立，或在時間軸上加入一個。",
        createAutomaticZooms: "建立自動縮放",
        typingZoomToggle: "輸入時保持縮放",
        typingZoomCaption: "點按後繼續輸入，會讓自動縮放停留在該位置。",
        microphoneToggle: "錄低咪高風",
        microphoneCaption: "你把聲會放入獨立音軌，並可在編輯器調校。",
        systemAudioTrackLabel: "Mac 聲音",
        microphoneTrackLabel: "咪高風",
        audioVolumeLabel: "音量",
        removeAudio: "移除",
        restoreAudio: "還原",
        microphoneUnavailableHUD: "麥克風無法使用",
        microphonePermissionName: "咪高風",
        microphonePermissionExplain: "開啟後可在螢幕錄製加入你的聲音。",
        automaticZoomToggle: "自動加入縮放",
        automaticZoomCaption: "關閉後，新錄影將不含縮放。你仍可在編輯器中加入縮放。",
        pauseButton: "暫停錄製",
        resumeButton: "繼續錄製",
        blurLaneLabel: "模糊",
        addBlurButton: "模糊一個區域",
        blurLaneEmptyHint: "點按這裡加入模糊",
        thisBlurLabel: "這個模糊",
        blurPickArea: "選取區域",
        blurPickAreaHint: "拖曳過需要隱藏的內容",
        blurCaption: "在時間軸上的區塊持續期間保持隱藏。",
        addImageButton: "加入圖片",
        imageLaneLabel: "圖片",
        imageLaneEmptyHint: "點按這裡加入圖片",
        thisImageLabel: "這張圖片",
        imageSizeLabel: "大小",
        imageOpacityLabel: "不透明度",
        imagePositionLabel: "位置",
        imageImportFailed: "無法加入這張圖片。"
    )
}
