// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

/// Strings for the text snippets feature. Same contract as the other
/// FeatureStrings structs: memberwise init in declaration order, one static
/// per language, all in this file.
struct SnippetFeatureStrings {
    let pageTitle: String
    let hubDescription: String
    let enable: String
    let enableCaption: String
    let addButton: String
    let newTitle: String
    let editTitle: String
    let nameLabel: String
    let namePlaceholder: String
    let triggerLabel: String
    let triggerPlaceholder: String
    let replacementLabel: String
    let replacementPlaceholder: String
    let expansionLabel: String
    let expansionImmediate: String
    let expansionDelimiter: String
    let variablesHint: String
    let variablesCaption: String
    let emptyList: String
    let duplicateTrigger: String
    let triggerTooShort: String
    let deleteButton: String
    let saveButton: String
    let manageButton: String
    let ignoreCaseLabel: String
    let libraryTitle: String
    let libraryToggle: String
    let libraryCaption: String
    let librarySearchPlaceholder: String
    let libraryNoResults: String
    let libraryEmpty: String
    let libraryFooterHint: String
    let folderLabel: String
    let folderPlaceholder: String
    let showInLibraryLabel: String
    let variablesFormatCaption: String
    let editorFormatCaption: String
    let dateTimeInsertButton: String
    let dateTimeEditButton: String
    let dateTimeTypeLabel: String
    let dateTimeKindDate: String
    let dateTimeKindTime: String
    let dateTimeKindDateTime: String
    let dateTimeStyleLabel: String
    let dateTimeStyleShort: String
    let dateTimeStyleMedium: String
    let dateTimeStyleLong: String
    let dateTimeStyleFull: String
    let dateTimeStyleISO8601: String
    let dateTimeStyleCustom: String
    let dateTimeStyleLocaleNote: String
    let dateTimeTimezoneLabel: String
    let dateTimeTimezoneDeviceDefault: String
    let dateTimeTimezoneValid: String
    let dateTimeTimezoneInvalid: String
    let dateTimeTimezoneClear: String
    let dateTimeTimezoneSearchPlaceholder: String
    let dateTimePatternLabel: String
    let dateTimePreviewLabel: String
    let dateTimeConfirmInsert: String
    let dateTimeConfirmUpdate: String
}

extension FeatureStrings {
    static func snippets(_ language: AppLanguage) -> SnippetFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension SnippetFeatureStrings {
    static let ko = SnippetFeatureStrings(
        pageTitle: "텍스트 스니펫",
        hubDescription: "짧은 트리거를 전체 텍스트로 확장합니다",
        enable: "입력 중 스니펫 확장",
        enableCaption: "어디에서나 트리거를 입력하면 해당 텍스트로 바뀝니다. 모든 내용은 이 Mac에만 남습니다.",
        addButton: "스니펫 추가",
        newTitle: "새 스니펫",
        editTitle: "스니펫 편집",
        nameLabel: "이름",
        namePlaceholder: "개인 이메일",
        triggerLabel: "트리거",
        triggerPlaceholder: ";email",
        replacementLabel: "텍스트",
        replacementPlaceholder: "myemail@example.com",
        expansionLabel: "확장",
        expansionImmediate: "즉시",
        expansionDelimiter: "Space, Tab 또는 Return 뒤에",
        variablesHint: "변수: {{date}}, {{time}}, {{datetime}}, {{clipboard}}",
        variablesCaption: "확장 시점에 날짜, 시간 및 복사한 텍스트로 바뀝니다.",
        emptyList: "아직 스니펫이 없습니다. 첫 번째 스니펫을 추가하세요.",
        duplicateTrigger: "다른 스니펫이 이미 이 트리거를 사용하고 있습니다.",
        triggerTooShort: "트리거는 2자 이상이어야 합니다.",
        deleteButton: "삭제",
        saveButton: "저장",
        manageButton: "스니펫 관리",
        ignoreCaseLabel: "대소문자 구분 안 함",
        libraryTitle: "빠른 스니펫 메뉴",
        libraryToggle: "메뉴에서 스니펫 열기",
        libraryCaption: "단축키를 누르면 검색 가능한 메뉴가 열립니다. 선택한 스니펫은 커서 위치에 바로 입력됩니다.",
        librarySearchPlaceholder: "스니펫 검색",
        libraryNoResults: "검색과 일치하는 스니펫이 없습니다.",
        libraryEmpty: "아직 표시할 스니펫이 없습니다. 스니펫을 추가하거나 자주 쓰는 스니펫에서 “빠른 메뉴에 표시”를 켜세요.",
        libraryFooterHint: "↩ 입력 · esc 닫기",
        folderLabel: "폴더",
        folderPlaceholder: "업무",
        showInLibraryLabel: "빠른 메뉴에 표시",
        variablesFormatCaption: "콜론 뒤에 형식을 적으면 원하는 모양이 됩니다. 예: {{date:yyyy-MM-dd}}. 시간대는 {{date-tz(America/New_York):yyyy-MM-dd}}처럼 -tz(...)로 지정합니다.",
        editorFormatCaption: "콜론 뒤에 형식을 적으면 원하는 모양이 됩니다. 예: {{date:yyyy-MM-dd}}. 또는 위의 날짜/시간 버튼을 사용하세요. 시간대는 {{date-tz(America/New_York):yyyy-MM-dd}}처럼 -tz(...)로 지정합니다.",
        dateTimeInsertButton: "날짜/시간 삽입",
        dateTimeEditButton: "날짜/시간 편집",
        dateTimeTypeLabel: "유형",
        dateTimeKindDate: "날짜",
        dateTimeKindTime: "시간",
        dateTimeKindDateTime: "날짜시간",
        dateTimeStyleLabel: "스타일",
        dateTimeStyleShort: "짧게",
        dateTimeStyleMedium: "보통",
        dateTimeStyleLong: "길게",
        dateTimeStyleFull: "전체",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "사용자 지정",
        dateTimeStyleLocaleNote: "이름이 있는 형식은 Mac의 지역 표기를 지금 그대로 저장합니다.",
        dateTimeTimezoneLabel: "시간대",
        dateTimeTimezoneDeviceDefault: "기기 기본값",
        dateTimeTimezoneValid: "유효한 시간대",
        dateTimeTimezoneInvalid: "인식할 수 없는 시간대",
        dateTimeTimezoneClear: "시간대 지우기",
        dateTimeTimezoneSearchPlaceholder: "시간대 검색",
        dateTimePatternLabel: "패턴",
        dateTimePreviewLabel: "미리보기",
        dateTimeConfirmInsert: "삽입",
        dateTimeConfirmUpdate: "업데이트"
    )
}

extension SnippetFeatureStrings {
    static let enUS = SnippetFeatureStrings(
        pageTitle: "Text snippets",
        hubDescription: "Short triggers expand into full text",
        enable: "Expand snippets while typing",
        enableCaption: "Type a trigger anywhere and it becomes its text. Everything stays on this Mac.",
        addButton: "Add snippet",
        newTitle: "New snippet",
        editTitle: "Edit snippet",
        nameLabel: "Name",
        namePlaceholder: "Personal email",
        triggerLabel: "Trigger",
        triggerPlaceholder: ";email",
        replacementLabel: "Text",
        replacementPlaceholder: "myemail@example.com",
        expansionLabel: "Expand",
        expansionImmediate: "Right away",
        expansionDelimiter: "After space, Tab or Return",
        variablesHint: "Variables: {{date}}, {{time}}, {{datetime}}, {{clipboard}}",
        variablesCaption: "They become the date, the time and the copied text at the moment of expansion.",
        emptyList: "No snippets yet. Add the first one.",
        duplicateTrigger: "Another snippet already uses this trigger.",
        triggerTooShort: "The trigger needs at least 2 characters.",
        deleteButton: "Delete",
        saveButton: "Save",
        manageButton: "Manage snippets",
        ignoreCaseLabel: "Ignore capitalization",
        libraryTitle: "Quick snippet menu",
        libraryToggle: "Open snippets from a menu",
        libraryCaption: "The shortcut opens a searchable menu. Picking a snippet types it right where your cursor is.",
        librarySearchPlaceholder: "Search snippets",
        libraryNoResults: "No snippet matches the search.",
        libraryEmpty: "Nothing to show yet. Add snippets, or turn on “Show in the quick menu” for the ones you use most.",
        libraryFooterHint: "↩ inserts · esc closes",
        folderLabel: "Folder",
        folderPlaceholder: "Work",
        showInLibraryLabel: "Show in the quick menu",
        variablesFormatCaption: "A format after a colon picks how they look, like {{date:yyyy-MM-dd}}. A -tz(...) part sets the timezone, like {{date-tz(America/New_York):yyyy-MM-dd}}.",
        editorFormatCaption: "A format after a colon picks how they look, like {{date:yyyy-MM-dd}}, or use the date/time button above. A -tz(...) part sets the timezone, like {{date-tz(America/New_York):yyyy-MM-dd}}.",
        dateTimeInsertButton: "Insert date/time",
        dateTimeEditButton: "Edit date/time",
        dateTimeTypeLabel: "Type",
        dateTimeKindDate: "Date",
        dateTimeKindTime: "Time",
        dateTimeKindDateTime: "DateTime",
        dateTimeStyleLabel: "Style",
        dateTimeStyleShort: "Short",
        dateTimeStyleMedium: "Medium",
        dateTimeStyleLong: "Long",
        dateTimeStyleFull: "Full",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "Custom",
        dateTimeStyleLocaleNote: "A named style saves the format your Mac’s region uses right now.",
        dateTimeTimezoneLabel: "Timezone",
        dateTimeTimezoneDeviceDefault: "Device default",
        dateTimeTimezoneValid: "Valid timezone",
        dateTimeTimezoneInvalid: "Unrecognized timezone",
        dateTimeTimezoneClear: "Clear timezone",
        dateTimeTimezoneSearchPlaceholder: "Search timezones",
        dateTimePatternLabel: "Pattern",
        dateTimePreviewLabel: "Preview",
        dateTimeConfirmInsert: "Insert",
        dateTimeConfirmUpdate: "Update"
    )

    static let ptBR = SnippetFeatureStrings(
        pageTitle: "Snippets de texto",
        hubDescription: "Gatilhos curtos viram textos completos",
        enable: "Expandir snippets enquanto digita",
        enableCaption: "Digite um gatilho em qualquer lugar e ele vira o texto dele. Tudo fica neste Mac.",
        addButton: "Adicionar snippet",
        newTitle: "Novo snippet",
        editTitle: "Editar snippet",
        nameLabel: "Nome",
        namePlaceholder: "Email pessoal",
        triggerLabel: "Gatilho",
        triggerPlaceholder: ";email",
        replacementLabel: "Texto",
        replacementPlaceholder: "meuemail@exemplo.com",
        expansionLabel: "Expandir",
        expansionImmediate: "Na hora",
        expansionDelimiter: "Após espaço, Tab ou Enter",
        variablesHint: "Variáveis: {{date}}, {{time}}, {{datetime}}, {{clipboard}}",
        variablesCaption: "Elas viram a data, a hora e o texto copiado no momento da expansão.",
        emptyList: "Nenhum snippet ainda. Adicione o primeiro.",
        duplicateTrigger: "Outro snippet já usa esse gatilho.",
        triggerTooShort: "O gatilho precisa de pelo menos 2 caracteres.",
        deleteButton: "Apagar",
        saveButton: "Salvar",
        manageButton: "Gerenciar snippets",
        ignoreCaseLabel: "Ignorar maiúsculas e minúsculas",
        libraryTitle: "Menu rápido de snippets",
        libraryToggle: "Abrir snippets por um menu",
        libraryCaption: "O atalho abre um menu com busca. Escolher um snippet digita o texto onde o cursor está.",
        librarySearchPlaceholder: "Buscar snippets",
        libraryNoResults: "Nenhum snippet corresponde à busca.",
        libraryEmpty: "Nada para mostrar ainda. Adicione snippets ou ative “Mostrar no menu rápido” nos que você mais usa.",
        libraryFooterHint: "↩ insere · esc fecha",
        folderLabel: "Pasta",
        folderPlaceholder: "Trabalho",
        showInLibraryLabel: "Mostrar no menu rápido",
        variablesFormatCaption: "Um formato depois de dois pontos escolhe a aparência, como {{date:yyyy-MM-dd}}. Uma parte -tz(...) define o fuso horário, como {{date-tz(America/New_York):yyyy-MM-dd}}.",
        editorFormatCaption: "Um formato depois de dois pontos escolhe a aparência, como {{date:yyyy-MM-dd}}, ou use o botão de data/hora acima. Uma parte -tz(...) define o fuso horário, como {{date-tz(America/New_York):yyyy-MM-dd}}.",
        dateTimeInsertButton: "Inserir data/hora",
        dateTimeEditButton: "Editar data/hora",
        dateTimeTypeLabel: "Tipo",
        dateTimeKindDate: "Data",
        dateTimeKindTime: "Hora",
        dateTimeKindDateTime: "Data e hora",
        dateTimeStyleLabel: "Estilo",
        dateTimeStyleShort: "Curto",
        dateTimeStyleMedium: "Médio",
        dateTimeStyleLong: "Longo",
        dateTimeStyleFull: "Completo",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "Personalizado",
        dateTimeStyleLocaleNote: "Um estilo nomeado salva o formato que a região do seu Mac usa agora.",
        dateTimeTimezoneLabel: "Fuso horário",
        dateTimeTimezoneDeviceDefault: "Padrão do dispositivo",
        dateTimeTimezoneValid: "Fuso horário válido",
        dateTimeTimezoneInvalid: "Fuso horário não reconhecido",
        dateTimeTimezoneClear: "Limpar fuso horário",
        dateTimeTimezoneSearchPlaceholder: "Buscar fusos horários",
        dateTimePatternLabel: "Padrão",
        dateTimePreviewLabel: "Pré-visualização",
        dateTimeConfirmInsert: "Inserir",
        dateTimeConfirmUpdate: "Atualizar"
    )

    static let tr = SnippetFeatureStrings(
        pageTitle: "Metin parçacıkları",
        hubDescription: "Kısa tetikleyiciler tam metne dönüşür",
        enable: "Yazarken parçacıkları genişlet",
        enableCaption: "Herhangi bir yerde bir tetikleyici yazın, metnine dönüşsün. Her şey bu Mac’te kalır.",
        addButton: "Parçacık ekle",
        newTitle: "Yeni parçacık",
        editTitle: "Parçacığı düzenle",
        nameLabel: "Ad",
        namePlaceholder: "Kişisel e-posta",
        triggerLabel: "Tetikleyici",
        triggerPlaceholder: ";eposta",
        replacementLabel: "Metin",
        replacementPlaceholder: "epostam@ornek.com",
        expansionLabel: "Genişletme",
        expansionImmediate: "Hemen",
        expansionDelimiter: "Boşluk, Tab veya Enter’dan sonra",
        variablesHint: "Değişkenler: {{date}}, {{time}}, {{datetime}}, {{clipboard}}",
        variablesCaption: "Genişletme anında tarihe, saate ve kopyalanan metne dönüşürler.",
        emptyList: "Henüz parçacık yok. İlkini ekleyin.",
        duplicateTrigger: "Bu tetikleyiciyi başka bir parçacık kullanıyor.",
        triggerTooShort: "Tetikleyici en az 2 karakter olmalı.",
        deleteButton: "Sil",
        saveButton: "Kaydet",
        manageButton: "Parçacıkları yönet",
        ignoreCaseLabel: "Büyük küçük harf farkını yok say",
        libraryTitle: "Hızlı parçacık menüsü",
        libraryToggle: "Parçacıkları menüden aç",
        libraryCaption: "Kısayol aranabilir bir menü açar. Seçilen parçacık imlecin olduğu yere yazılır.",
        librarySearchPlaceholder: "Parçacık ara",
        libraryNoResults: "Aramayla eşleşen parçacık yok.",
        libraryEmpty: "Henüz gösterilecek bir şey yok. Parçacık ekleyin veya en çok kullandıklarınızda “Hızlı menüde göster”i açın.",
        libraryFooterHint: "↩ yazar · esc kapatır",
        folderLabel: "Klasör",
        folderPlaceholder: "İş",
        showInLibraryLabel: "Hızlı menüde göster",
        variablesFormatCaption: "İki noktadan sonra yazılan biçim görünümü belirler, örneğin {{date:yyyy-MM-dd}}. -tz(...) bölümü saat dilimini belirler, örneğin {{date-tz(America/New_York):yyyy-MM-dd}}.",
        editorFormatCaption: "İki noktadan sonra yazılan biçim görünümü belirler, örneğin {{date:yyyy-MM-dd}}, veya yukarıdaki tarih/saat düğmesini kullanın. -tz(...) bölümü saat dilimini belirler, örneğin {{date-tz(America/New_York):yyyy-MM-dd}}.",
        dateTimeInsertButton: "Tarih/saat ekle",
        dateTimeEditButton: "Tarih/saati düzenle",
        dateTimeTypeLabel: "Tür",
        dateTimeKindDate: "Tarih",
        dateTimeKindTime: "Saat",
        dateTimeKindDateTime: "Tarih ve saat",
        dateTimeStyleLabel: "Stil",
        dateTimeStyleShort: "Kısa",
        dateTimeStyleMedium: "Orta",
        dateTimeStyleLong: "Uzun",
        dateTimeStyleFull: "Tam",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "Özel",
        dateTimeStyleLocaleNote: "Adlandırılmış bir biçem, Mac’inizin bölge gösterimini şu anki haliyle kaydeder.",
        dateTimeTimezoneLabel: "Saat dilimi",
        dateTimeTimezoneDeviceDefault: "Cihaz varsayılanı",
        dateTimeTimezoneValid: "Geçerli saat dilimi",
        dateTimeTimezoneInvalid: "Tanınmayan saat dilimi",
        dateTimeTimezoneClear: "Saat dilimini temizle",
        dateTimeTimezoneSearchPlaceholder: "Saat dilimi ara",
        dateTimePatternLabel: "Desen",
        dateTimePreviewLabel: "Önizleme",
        dateTimeConfirmInsert: "Ekle",
        dateTimeConfirmUpdate: "Güncelle"
    )

    static let ru = SnippetFeatureStrings(
        pageTitle: "Текстовые сниппеты",
        hubDescription: "Короткие триггеры превращаются в готовый текст",
        enable: "Разворачивать сниппеты при вводе",
        enableCaption: "Наберите триггер где угодно, и он станет своим текстом. Всё остаётся на этом Mac.",
        addButton: "Добавить сниппет",
        newTitle: "Новый сниппет",
        editTitle: "Изменить сниппет",
        nameLabel: "Название",
        namePlaceholder: "Личная почта",
        triggerLabel: "Триггер",
        triggerPlaceholder: ";почта",
        replacementLabel: "Текст",
        replacementPlaceholder: "moyapochta@primer.ru",
        expansionLabel: "Разворачивать",
        expansionImmediate: "Сразу",
        expansionDelimiter: "После пробела, Tab или Enter",
        variablesHint: "Переменные: {{date}}, {{time}}, {{datetime}}, {{clipboard}}",
        variablesCaption: "В момент развёртывания они становятся датой, временем и скопированным текстом.",
        emptyList: "Сниппетов пока нет. Добавьте первый.",
        duplicateTrigger: "Этот триггер уже занят другим сниппетом.",
        triggerTooShort: "Триггеру нужно не меньше 2 символов.",
        deleteButton: "Удалить",
        saveButton: "Сохранить",
        manageButton: "Управление сниппетами",
        ignoreCaseLabel: "Не учитывать регистр",
        libraryTitle: "Быстрое меню сниппетов",
        libraryToggle: "Открывать сниппеты из меню",
        libraryCaption: "Сочетание клавиш открывает меню с поиском. Выбранный сниппет печатается там, где стоит курсор.",
        librarySearchPlaceholder: "Поиск сниппетов",
        libraryNoResults: "Ни один сниппет не подходит под запрос.",
        libraryEmpty: "Пока нечего показывать. Добавьте сниппеты или включите «Показывать в быстром меню» для самых нужных.",
        libraryFooterHint: "↩ вставить · esc закрыть",
        folderLabel: "Папка",
        folderPlaceholder: "Работа",
        showInLibraryLabel: "Показывать в быстром меню",
        variablesFormatCaption: "Формат после двоеточия задаёт вид, например {{date:yyyy-MM-dd}}. Часть -tz(...) задаёт часовой пояс, например {{date-tz(America/New_York):yyyy-MM-dd}}.",
        editorFormatCaption: "Формат после двоеточия задаёт вид, например {{date:yyyy-MM-dd}}, или используйте кнопку даты и времени выше. Часть -tz(...) задаёт часовой пояс, например {{date-tz(America/New_York):yyyy-MM-dd}}.",
        dateTimeInsertButton: "Вставить дату/время",
        dateTimeEditButton: "Изменить дату/время",
        dateTimeTypeLabel: "Тип",
        dateTimeKindDate: "Дата",
        dateTimeKindTime: "Время",
        dateTimeKindDateTime: "Дата и время",
        dateTimeStyleLabel: "Стиль",
        dateTimeStyleShort: "Короткий",
        dateTimeStyleMedium: "Средний",
        dateTimeStyleLong: "Длинный",
        dateTimeStyleFull: "Полный",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "Свой",
        dateTimeStyleLocaleNote: "Именованный стиль сохраняет формат, который регион вашего Mac использует сейчас.",
        dateTimeTimezoneLabel: "Часовой пояс",
        dateTimeTimezoneDeviceDefault: "По умолчанию на устройстве",
        dateTimeTimezoneValid: "Допустимый часовой пояс",
        dateTimeTimezoneInvalid: "Нераспознанный часовой пояс",
        dateTimeTimezoneClear: "Очистить часовой пояс",
        dateTimeTimezoneSearchPlaceholder: "Поиск часовых поясов",
        dateTimePatternLabel: "Шаблон",
        dateTimePreviewLabel: "Предпросмотр",
        dateTimeConfirmInsert: "Вставить",
        dateTimeConfirmUpdate: "Обновить"
    )

    static let es = SnippetFeatureStrings(
        pageTitle: "Fragmentos de texto",
        hubDescription: "Disparadores cortos se convierten en texto completo",
        enable: "Expandir fragmentos al escribir",
        enableCaption: "Escribe un disparador en cualquier lugar y se convierte en su texto. Todo queda en este Mac.",
        addButton: "Añadir fragmento",
        newTitle: "Nuevo fragmento",
        editTitle: "Editar fragmento",
        nameLabel: "Nombre",
        namePlaceholder: "Correo personal",
        triggerLabel: "Disparador",
        triggerPlaceholder: ";correo",
        replacementLabel: "Texto",
        replacementPlaceholder: "micorreo@ejemplo.com",
        expansionLabel: "Expandir",
        expansionImmediate: "Al instante",
        expansionDelimiter: "Tras espacio, Tab o Enter",
        variablesHint: "Variables: {{date}}, {{time}}, {{datetime}}, {{clipboard}}",
        variablesCaption: "Se convierten en la fecha, la hora y el texto copiado al momento de expandir.",
        emptyList: "Aún no hay fragmentos. Añade el primero.",
        duplicateTrigger: "Otro fragmento ya usa ese disparador.",
        triggerTooShort: "El disparador necesita al menos 2 caracteres.",
        deleteButton: "Eliminar",
        saveButton: "Guardar",
        manageButton: "Gestionar fragmentos",
        ignoreCaseLabel: "Ignorar mayúsculas y minúsculas",
        libraryTitle: "Menú rápido de fragmentos",
        libraryToggle: "Abrir fragmentos desde un menú",
        libraryCaption: "El atajo abre un menú con búsqueda. Elegir un fragmento lo escribe justo donde está el cursor.",
        librarySearchPlaceholder: "Buscar fragmentos",
        libraryNoResults: "Ningún fragmento coincide con la búsqueda.",
        libraryEmpty: "Nada que mostrar todavía. Añade fragmentos o activa “Mostrar en el menú rápido” en los que más usas.",
        libraryFooterHint: "↩ inserta · esc cierra",
        folderLabel: "Carpeta",
        folderPlaceholder: "Trabajo",
        showInLibraryLabel: "Mostrar en el menú rápido",
        variablesFormatCaption: "Un formato después de dos puntos elige la apariencia, como {{date:yyyy-MM-dd}}. Una parte -tz(...) define la zona horaria, como {{date-tz(America/New_York):yyyy-MM-dd}}.",
        editorFormatCaption: "Un formato después de dos puntos elige la apariencia, como {{date:yyyy-MM-dd}}, o usa el botón de fecha/hora de arriba. Una parte -tz(...) define la zona horaria, como {{date-tz(America/New_York):yyyy-MM-dd}}.",
        dateTimeInsertButton: "Insertar fecha/hora",
        dateTimeEditButton: "Editar fecha/hora",
        dateTimeTypeLabel: "Tipo",
        dateTimeKindDate: "Fecha",
        dateTimeKindTime: "Hora",
        dateTimeKindDateTime: "Fecha y hora",
        dateTimeStyleLabel: "Estilo",
        dateTimeStyleShort: "Corto",
        dateTimeStyleMedium: "Medio",
        dateTimeStyleLong: "Largo",
        dateTimeStyleFull: "Completo",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "Personalizado",
        dateTimeStyleLocaleNote: "Un estilo con nombre guarda el formato que usa la región de tu Mac ahora mismo.",
        dateTimeTimezoneLabel: "Zona horaria",
        dateTimeTimezoneDeviceDefault: "Predeterminada del dispositivo",
        dateTimeTimezoneValid: "Zona horaria válida",
        dateTimeTimezoneInvalid: "Zona horaria no reconocida",
        dateTimeTimezoneClear: "Borrar zona horaria",
        dateTimeTimezoneSearchPlaceholder: "Buscar zonas horarias",
        dateTimePatternLabel: "Patrón",
        dateTimePreviewLabel: "Vista previa",
        dateTimeConfirmInsert: "Insertar",
        dateTimeConfirmUpdate: "Actualizar"
    )

    static let de = SnippetFeatureStrings(
        pageTitle: "Textbausteine",
        hubDescription: "Kurze Kürzel werden zu ganzem Text",
        enable: "Bausteine beim Tippen ausschreiben",
        enableCaption: "Tippe ein Kürzel irgendwo und es wird zu seinem Text. Alles bleibt auf diesem Mac.",
        addButton: "Baustein hinzufügen",
        newTitle: "Neuer Baustein",
        editTitle: "Baustein bearbeiten",
        nameLabel: "Name",
        namePlaceholder: "Private E-Mail",
        triggerLabel: "Kürzel",
        triggerPlaceholder: ";mail",
        replacementLabel: "Text",
        replacementPlaceholder: "meinemail@beispiel.de",
        expansionLabel: "Ausschreiben",
        expansionImmediate: "Sofort",
        expansionDelimiter: "Nach Leerzeichen, Tab oder Enter",
        variablesHint: "Variablen: {{date}}, {{time}}, {{datetime}}, {{clipboard}}",
        variablesCaption: "Sie werden beim Ausschreiben zu Datum, Uhrzeit und dem kopierten Text.",
        emptyList: "Noch keine Bausteine. Füge den ersten hinzu.",
        duplicateTrigger: "Ein anderer Baustein nutzt dieses Kürzel bereits.",
        triggerTooShort: "Das Kürzel braucht mindestens 2 Zeichen.",
        deleteButton: "Löschen",
        saveButton: "Sichern",
        manageButton: "Textbausteine verwalten",
        ignoreCaseLabel: "Groß- und Kleinschreibung ignorieren",
        libraryTitle: "Schnellmenü für Schnipsel",
        libraryToggle: "Schnipsel über ein Menü öffnen",
        libraryCaption: "Das Tastenkürzel öffnet ein durchsuchbares Menü. Ein gewählter Schnipsel wird direkt an der Cursorposition getippt.",
        librarySearchPlaceholder: "Schnipsel suchen",
        libraryNoResults: "Kein Schnipsel passt zur Suche.",
        libraryEmpty: "Noch nichts anzuzeigen. Füge Schnipsel hinzu oder aktiviere „Im Schnellmenü zeigen“ bei deinen wichtigsten.",
        libraryFooterHint: "↩ einfügen · esc schließen",
        folderLabel: "Ordner",
        folderPlaceholder: "Arbeit",
        showInLibraryLabel: "Im Schnellmenü zeigen",
        variablesFormatCaption: "Ein Format nach einem Doppelpunkt bestimmt das Aussehen, etwa {{date:yyyy-MM-dd}}. Ein -tz(...)-Teil legt die Zeitzone fest, etwa {{date-tz(America/New_York):yyyy-MM-dd}}.",
        editorFormatCaption: "Ein Format nach einem Doppelpunkt bestimmt das Aussehen, etwa {{date:yyyy-MM-dd}}, oder verwende die Datum/Uhrzeit-Schaltfläche oben. Ein -tz(...)-Teil legt die Zeitzone fest, etwa {{date-tz(America/New_York):yyyy-MM-dd}}.",
        dateTimeInsertButton: "Datum/Uhrzeit einfügen",
        dateTimeEditButton: "Datum/Uhrzeit bearbeiten",
        dateTimeTypeLabel: "Typ",
        dateTimeKindDate: "Datum",
        dateTimeKindTime: "Uhrzeit",
        dateTimeKindDateTime: "Datum und Uhrzeit",
        dateTimeStyleLabel: "Stil",
        dateTimeStyleShort: "Kurz",
        dateTimeStyleMedium: "Mittel",
        dateTimeStyleLong: "Lang",
        dateTimeStyleFull: "Vollständig",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "Benutzerdefiniert",
        dateTimeStyleLocaleNote: "Ein benannter Stil speichert das Format, das die Region deines Mac jetzt verwendet.",
        dateTimeTimezoneLabel: "Zeitzone",
        dateTimeTimezoneDeviceDefault: "Gerätestandard",
        dateTimeTimezoneValid: "Gültige Zeitzone",
        dateTimeTimezoneInvalid: "Unbekannte Zeitzone",
        dateTimeTimezoneClear: "Zeitzone löschen",
        dateTimeTimezoneSearchPlaceholder: "Zeitzonen suchen",
        dateTimePatternLabel: "Muster",
        dateTimePreviewLabel: "Vorschau",
        dateTimeConfirmInsert: "Einfügen",
        dateTimeConfirmUpdate: "Aktualisieren"
    )

    static let fr = SnippetFeatureStrings(
        pageTitle: "Extraits de texte",
        hubDescription: "Des déclencheurs courts deviennent du texte complet",
        enable: "Développer les extraits pendant la frappe",
        enableCaption: "Tapez un déclencheur n’importe où et il devient son texte. Tout reste sur ce Mac.",
        addButton: "Ajouter un extrait",
        newTitle: "Nouvel extrait",
        editTitle: "Modifier l’extrait",
        nameLabel: "Nom",
        namePlaceholder: "E-mail personnel",
        triggerLabel: "Déclencheur",
        triggerPlaceholder: ";mail",
        replacementLabel: "Texte",
        replacementPlaceholder: "monmail@exemple.fr",
        expansionLabel: "Développer",
        expansionImmediate: "Immédiatement",
        expansionDelimiter: "Après espace, Tab ou Entrée",
        variablesHint: "Variables\u{00A0}: {{date}}, {{time}}, {{datetime}}, {{clipboard}}",
        variablesCaption: "Elles deviennent la date, l’heure et le texte copié au moment du développement.",
        emptyList: "Aucun extrait pour l’instant. Ajoutez le premier.",
        duplicateTrigger: "Un autre extrait utilise déjà ce déclencheur.",
        triggerTooShort: "Le déclencheur doit faire au moins 2 caractères.",
        deleteButton: "Supprimer",
        saveButton: "Enregistrer",
        manageButton: "Gérer les extraits",
        ignoreCaseLabel: "Ignorer les majuscules et minuscules",
        libraryTitle: "Menu rapide des extraits",
        libraryToggle: "Ouvrir les extraits depuis un menu",
        libraryCaption: "Le raccourci ouvre un menu avec recherche. Choisir un extrait le tape là où se trouve le curseur.",
        librarySearchPlaceholder: "Rechercher un extrait",
        libraryNoResults: "Aucun extrait ne correspond à la recherche.",
        libraryEmpty: "Rien à afficher pour l’instant. Ajoutez des extraits ou activez «\u{00A0}Afficher dans le menu rapide\u{00A0}» pour vos favoris.",
        libraryFooterHint: "↩ insère · esc ferme",
        folderLabel: "Dossier",
        folderPlaceholder: "Travail",
        showInLibraryLabel: "Afficher dans le menu rapide",
        variablesFormatCaption: "Un format après deux-points choisit l’apparence, par exemple {{date:yyyy-MM-dd}}. Une partie -tz(...) définit le fuseau horaire, par exemple {{date-tz(America/New_York):yyyy-MM-dd}}.",
        editorFormatCaption: "Un format après deux-points choisit l’apparence, par exemple {{date:yyyy-MM-dd}}, ou utilisez le bouton date/heure ci-dessus. Une partie -tz(...) définit le fuseau horaire, par exemple {{date-tz(America/New_York):yyyy-MM-dd}}.",
        dateTimeInsertButton: "Insérer date/heure",
        dateTimeEditButton: "Modifier date/heure",
        dateTimeTypeLabel: "Type",
        dateTimeKindDate: "Date",
        dateTimeKindTime: "Heure",
        dateTimeKindDateTime: "Date et heure",
        dateTimeStyleLabel: "Style",
        dateTimeStyleShort: "Court",
        dateTimeStyleMedium: "Moyen",
        dateTimeStyleLong: "Long",
        dateTimeStyleFull: "Complet",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "Personnalisé",
        dateTimeStyleLocaleNote: "Un style nommé enregistre le format utilisé par la région de votre Mac.",
        dateTimeTimezoneLabel: "Fuseau horaire",
        dateTimeTimezoneDeviceDefault: "Par défaut de l’appareil",
        dateTimeTimezoneValid: "Fuseau horaire valide",
        dateTimeTimezoneInvalid: "Fuseau horaire non reconnu",
        dateTimeTimezoneClear: "Effacer le fuseau horaire",
        dateTimeTimezoneSearchPlaceholder: "Rechercher un fuseau horaire",
        dateTimePatternLabel: "Motif",
        dateTimePreviewLabel: "Aperçu",
        dateTimeConfirmInsert: "Insérer",
        dateTimeConfirmUpdate: "Mettre à jour"
    )

    static let it = SnippetFeatureStrings(
        pageTitle: "Frammenti di testo",
        hubDescription: "Trigger brevi diventano testo completo",
        enable: "Espandi i frammenti mentre scrivi",
        enableCaption: "Digita un trigger ovunque e diventa il suo testo. Tutto resta su questo Mac.",
        addButton: "Aggiungi frammento",
        newTitle: "Nuovo frammento",
        editTitle: "Modifica frammento",
        nameLabel: "Nome",
        namePlaceholder: "Email personale",
        triggerLabel: "Trigger",
        triggerPlaceholder: ";email",
        replacementLabel: "Testo",
        replacementPlaceholder: "miamail@esempio.it",
        expansionLabel: "Espandi",
        expansionImmediate: "Subito",
        expansionDelimiter: "Dopo spazio, Tab o Invio",
        variablesHint: "Variabili: {{date}}, {{time}}, {{datetime}}, {{clipboard}}",
        variablesCaption: "Diventano la data, l’ora e il testo copiato al momento dell’espansione.",
        emptyList: "Ancora nessun frammento. Aggiungi il primo.",
        duplicateTrigger: "Un altro frammento usa già questo trigger.",
        triggerTooShort: "Il trigger richiede almeno 2 caratteri.",
        deleteButton: "Elimina",
        saveButton: "Salva",
        manageButton: "Gestisci frammenti",
        ignoreCaseLabel: "Ignora maiuscole e minuscole",
        libraryTitle: "Menu rapido degli snippet",
        libraryToggle: "Aprire gli snippet da un menu",
        libraryCaption: "La scorciatoia apre un menu con ricerca. Scegliere uno snippet lo digita dove si trova il cursore.",
        librarySearchPlaceholder: "Cerca snippet",
        libraryNoResults: "Nessuno snippet corrisponde alla ricerca.",
        libraryEmpty: "Ancora niente da mostrare. Aggiungi snippet o attiva “Mostra nel menu rapido” per quelli che usi di più.",
        libraryFooterHint: "↩ inserisce · esc chiude",
        folderLabel: "Cartella",
        folderPlaceholder: "Lavoro",
        showInLibraryLabel: "Mostra nel menu rapido",
        variablesFormatCaption: "Un formato dopo i due punti sceglie l’aspetto, ad esempio {{date:yyyy-MM-dd}}. Una parte -tz(...) imposta il fuso orario, ad esempio {{date-tz(America/New_York):yyyy-MM-dd}}.",
        editorFormatCaption: "Un formato dopo i due punti sceglie l’aspetto, ad esempio {{date:yyyy-MM-dd}}, oppure usa il pulsante data/ora qui sopra. Una parte -tz(...) imposta il fuso orario, ad esempio {{date-tz(America/New_York):yyyy-MM-dd}}.",
        dateTimeInsertButton: "Inserisci data/ora",
        dateTimeEditButton: "Modifica data/ora",
        dateTimeTypeLabel: "Tipo",
        dateTimeKindDate: "Data",
        dateTimeKindTime: "Ora",
        dateTimeKindDateTime: "Data e ora",
        dateTimeStyleLabel: "Stile",
        dateTimeStyleShort: "Breve",
        dateTimeStyleMedium: "Medio",
        dateTimeStyleLong: "Lungo",
        dateTimeStyleFull: "Completo",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "Personalizzato",
        dateTimeStyleLocaleNote: "Uno stile con nome salva il formato usato ora dalla regione del tuo Mac.",
        dateTimeTimezoneLabel: "Fuso orario",
        dateTimeTimezoneDeviceDefault: "Predefinito del dispositivo",
        dateTimeTimezoneValid: "Fuso orario valido",
        dateTimeTimezoneInvalid: "Fuso orario non riconosciuto",
        dateTimeTimezoneClear: "Cancella fuso orario",
        dateTimeTimezoneSearchPlaceholder: "Cerca fusi orari",
        dateTimePatternLabel: "Modello",
        dateTimePreviewLabel: "Anteprima",
        dateTimeConfirmInsert: "Inserisci",
        dateTimeConfirmUpdate: "Aggiorna"
    )

    static let ja = SnippetFeatureStrings(
        pageTitle: "テキストスニペット",
        hubDescription: "短いトリガーが文章に展開されます",
        enable: "入力中にスニペットを展開",
        enableCaption: "どこでもトリガーを入力すると、その本文に変わります。すべてこのMacの中だけで完結します。",
        addButton: "スニペットを追加",
        newTitle: "新規スニペット",
        editTitle: "スニペットを編集",
        nameLabel: "名前",
        namePlaceholder: "個人用メール",
        triggerLabel: "トリガー",
        triggerPlaceholder: ";mail",
        replacementLabel: "テキスト",
        replacementPlaceholder: "mymail@example.com",
        expansionLabel: "展開のタイミング",
        expansionImmediate: "すぐに",
        expansionDelimiter: "スペース、Tab、Returnの後",
        variablesHint: "変数: {{date}}, {{time}}, {{datetime}}, {{clipboard}}",
        variablesCaption: "展開した瞬間の日付、時刻、コピー中のテキストになります。",
        emptyList: "スニペットはまだありません。最初のひとつを追加してください。",
        duplicateTrigger: "このトリガーは別のスニペットが使っています。",
        triggerTooShort: "トリガーは2文字以上必要です。",
        deleteButton: "削除",
        saveButton: "保存",
        manageButton: "スニペットを管理",
        ignoreCaseLabel: "大文字と小文字を区別しない",
        libraryTitle: "スニペットのクイックメニュー",
        libraryToggle: "メニューからスニペットを開く",
        libraryCaption: "ショートカットで検索できるメニューが開きます。選んだスニペットはカーソル位置にそのまま入力されます。",
        librarySearchPlaceholder: "スニペットを検索",
        libraryNoResults: "検索に一致するスニペットがありません。",
        libraryEmpty: "まだ表示するものがありません。スニペットを追加するか、よく使うものの「クイックメニューに表示」をオンにしてください。",
        libraryFooterHint: "↩ 入力 · esc 閉じる",
        folderLabel: "フォルダ",
        folderPlaceholder: "仕事",
        showInLibraryLabel: "クイックメニューに表示",
        variablesFormatCaption: "コロンの後に形式を書くと表示を選べます。例: {{date:yyyy-MM-dd}}。-tz(...) で時間帯を指定できます。例: {{date-tz(America/New_York):yyyy-MM-dd}}",
        editorFormatCaption: "コロンの後に形式を書くと表示を選べます。例: {{date:yyyy-MM-dd}}。または上の日付/時刻ボタンを使ってください。-tz(...) で時間帯を指定できます。例: {{date-tz(America/New_York):yyyy-MM-dd}}",
        dateTimeInsertButton: "日付/時刻を挿入",
        dateTimeEditButton: "日付/時刻を編集",
        dateTimeTypeLabel: "種類",
        dateTimeKindDate: "日付",
        dateTimeKindTime: "時刻",
        dateTimeKindDateTime: "日付と時刻",
        dateTimeStyleLabel: "スタイル",
        dateTimeStyleShort: "短い",
        dateTimeStyleMedium: "標準",
        dateTimeStyleLong: "長い",
        dateTimeStyleFull: "完全",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "カスタム",
        dateTimeStyleLocaleNote: "名前付きの形式は、Macの地域の表記をそのまま保存します。",
        dateTimeTimezoneLabel: "タイムゾーン",
        dateTimeTimezoneDeviceDefault: "デバイスの既定値",
        dateTimeTimezoneValid: "有効なタイムゾーン",
        dateTimeTimezoneInvalid: "認識できないタイムゾーン",
        dateTimeTimezoneClear: "タイムゾーンを消去",
        dateTimeTimezoneSearchPlaceholder: "タイムゾーンを検索",
        dateTimePatternLabel: "パターン",
        dateTimePreviewLabel: "プレビュー",
        dateTimeConfirmInsert: "挿入",
        dateTimeConfirmUpdate: "更新"
    )

    static let zhHans = SnippetFeatureStrings(
        pageTitle: "文本片段",
        hubDescription: "短触发词展开为完整文本",
        enable: "输入时展开片段",
        enableCaption: "在任何地方输入触发词，它就会变成对应文本。一切都只在这台 Mac 上。",
        addButton: "添加片段",
        newTitle: "新建片段",
        editTitle: "编辑片段",
        nameLabel: "名称",
        namePlaceholder: "个人邮箱",
        triggerLabel: "触发词",
        triggerPlaceholder: ";email",
        replacementLabel: "文本",
        replacementPlaceholder: "mymail@example.com",
        expansionLabel: "展开时机",
        expansionImmediate: "立即",
        expansionDelimiter: "空格、Tab 或回车后",
        variablesHint: "变量：{{date}}、{{time}}、{{datetime}}、{{clipboard}}",
        variablesCaption: "展开那一刻，它们会变成日期、时间和已拷贝的文本。",
        emptyList: "还没有片段。添加第一个吧。",
        duplicateTrigger: "另一个片段已在使用该触发词。",
        triggerTooShort: "触发词至少需要 2 个字符。",
        deleteButton: "删除",
        saveButton: "保存",
        manageButton: "管理文本片段",
        ignoreCaseLabel: "忽略大小写",
        libraryTitle: "片段快捷菜单",
        libraryToggle: "从菜单打开片段",
        libraryCaption: "按下快捷键会打开一个可搜索的菜单。选中的片段会直接输入到光标所在位置。",
        librarySearchPlaceholder: "搜索片段",
        libraryNoResults: "没有匹配搜索的片段。",
        libraryEmpty: "暂时没有可显示的内容。添加片段，或为常用片段开启“在快捷菜单中显示”。",
        libraryFooterHint: "↩ 输入 · esc 关闭",
        folderLabel: "文件夹",
        folderPlaceholder: "工作",
        showInLibraryLabel: "在快捷菜单中显示",
        variablesFormatCaption: "冒号后加上格式就能自定样式，例如 {{date:yyyy-MM-dd}}。用 -tz(...) 指定时区，例如 {{date-tz(America/New_York):yyyy-MM-dd}}。",
        editorFormatCaption: "冒号后加上格式就能自定样式，例如 {{date:yyyy-MM-dd}}，或使用上方的日期/时间按钮。用 -tz(...) 指定时区，例如 {{date-tz(America/New_York):yyyy-MM-dd}}。",
        dateTimeInsertButton: "插入日期/时间",
        dateTimeEditButton: "编辑日期/时间",
        dateTimeTypeLabel: "类型",
        dateTimeKindDate: "日期",
        dateTimeKindTime: "时间",
        dateTimeKindDateTime: "日期和时间",
        dateTimeStyleLabel: "样式",
        dateTimeStyleShort: "简短",
        dateTimeStyleMedium: "中等",
        dateTimeStyleLong: "较长",
        dateTimeStyleFull: "完整",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "自定义",
        dateTimeStyleLocaleNote: "命名样式会保存 Mac 地区此刻使用的格式。",
        dateTimeTimezoneLabel: "时区",
        dateTimeTimezoneDeviceDefault: "设备默认",
        dateTimeTimezoneValid: "有效时区",
        dateTimeTimezoneInvalid: "无法识别的时区",
        dateTimeTimezoneClear: "清除时区",
        dateTimeTimezoneSearchPlaceholder: "搜索时区",
        dateTimePatternLabel: "格式",
        dateTimePreviewLabel: "预览",
        dateTimeConfirmInsert: "插入",
        dateTimeConfirmUpdate: "更新"
    )

    static let zhTW = SnippetFeatureStrings(
        pageTitle: "文字片段",
        hubDescription: "簡短觸發詞展開為完整文字",
        enable: "輸入時展開片段",
        enableCaption: "在任何地方輸入觸發詞,它就會變成對應文字。一切都只在這台 Mac 上。",
        addButton: "加入片段",
        newTitle: "新增片段",
        editTitle: "編輯片段",
        nameLabel: "名稱",
        namePlaceholder: "個人電郵",
        triggerLabel: "觸發詞",
        triggerPlaceholder: ";email",
        replacementLabel: "文字",
        replacementPlaceholder: "mymail@example.com",
        expansionLabel: "展開時機",
        expansionImmediate: "立即",
        expansionDelimiter: "空格、Tab 或 Return 後",
        variablesHint: "變數:{{date}}、{{time}}、{{datetime}}、{{clipboard}}",
        variablesCaption: "展開那一刻,它們會變成日期、時間和已拷貝的文字。",
        emptyList: "還沒有片段。加入第一個吧。",
        duplicateTrigger: "另一個片段已使用此觸發詞。",
        triggerTooShort: "觸發詞至少需要 2 個字元。",
        deleteButton: "刪除",
        saveButton: "儲存",
        manageButton: "管理文字片段",
        ignoreCaseLabel: "忽略大小寫",
        libraryTitle: "程式片段快捷選單",
        libraryToggle: "從選單開啟片段",
        libraryCaption: "按下快速鍵會開啟可搜尋的選單。選取的片段會直接輸入到游標所在位置。",
        librarySearchPlaceholder: "搜尋片段",
        libraryNoResults: "沒有符合搜尋的片段。",
        libraryEmpty: "目前沒有可顯示的內容。加入片段，或為常用片段開啟「在快捷選單中顯示」。",
        libraryFooterHint: "↩ 輸入 · esc 關閉",
        folderLabel: "檔案夾",
        folderPlaceholder: "工作",
        showInLibraryLabel: "在快捷選單中顯示",
        variablesFormatCaption: "冒號後加上格式就能自訂樣式,例如 {{date:yyyy-MM-dd}}。用 -tz(...) 指定時區,例如 {{date-tz(America/New_York):yyyy-MM-dd}}。",
        editorFormatCaption: "冒號後加上格式就能自訂樣式,例如 {{date:yyyy-MM-dd}},或使用上方的日期/時間按鈕。用 -tz(...) 指定時區,例如 {{date-tz(America/New_York):yyyy-MM-dd}}。",
        dateTimeInsertButton: "插入日期/時間",
        dateTimeEditButton: "編輯日期/時間",
        dateTimeTypeLabel: "類型",
        dateTimeKindDate: "日期",
        dateTimeKindTime: "時間",
        dateTimeKindDateTime: "日期和時間",
        dateTimeStyleLabel: "樣式",
        dateTimeStyleShort: "簡短",
        dateTimeStyleMedium: "中等",
        dateTimeStyleLong: "較長",
        dateTimeStyleFull: "完整",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "自訂",
        dateTimeStyleLocaleNote: "命名樣式會儲存 Mac 地區此刻使用的格式。",
        dateTimeTimezoneLabel: "時區",
        dateTimeTimezoneDeviceDefault: "裝置預設",
        dateTimeTimezoneValid: "有效時區",
        dateTimeTimezoneInvalid: "無法辨識的時區",
        dateTimeTimezoneClear: "清除時區",
        dateTimeTimezoneSearchPlaceholder: "搜尋時區",
        dateTimePatternLabel: "格式",
        dateTimePreviewLabel: "預覽",
        dateTimeConfirmInsert: "插入",
        dateTimeConfirmUpdate: "更新"
    )

    static let zhHK = SnippetFeatureStrings(
        pageTitle: "文字片段",
        hubDescription: "簡短觸發詞展開為完整文字",
        enable: "輸入時展開片段",
        enableCaption: "在任何地方輸入觸發詞,它就會變成對應文字。一切都只在這台 Mac 上。",
        addButton: "加入片段",
        newTitle: "新增片段",
        editTitle: "編輯片段",
        nameLabel: "名稱",
        namePlaceholder: "個人電郵",
        triggerLabel: "觸發詞",
        triggerPlaceholder: ";email",
        replacementLabel: "文字",
        replacementPlaceholder: "mymail@example.com",
        expansionLabel: "展開時機",
        expansionImmediate: "立即",
        expansionDelimiter: "空格、Tab 或 Return 後",
        variablesHint: "變數:{{date}}、{{time}}、{{datetime}}、{{clipboard}}",
        variablesCaption: "展開嗰一刻,佢哋會變成日期、時間同已複製嘅文字。",
        emptyList: "仲未有片段。加入第一個啦。",
        duplicateTrigger: "另一個片段已使用此觸發詞。",
        triggerTooShort: "觸發詞至少需要 2 個字元。",
        deleteButton: "刪除",
        saveButton: "儲存",
        manageButton: "管理文字片段",
        ignoreCaseLabel: "忽略大小寫",
        libraryTitle: "程式片段快捷選單",
        libraryToggle: "從選單開啟片段",
        libraryCaption: "按下快速鍵會開啟可搜尋的選單。選取的片段會直接輸入到游標所在位置。",
        librarySearchPlaceholder: "搜尋片段",
        libraryNoResults: "沒有符合搜尋的片段。",
        libraryEmpty: "目前沒有可顯示的內容。加入片段，或為常用片段開啟「在快捷選單中顯示」。",
        libraryFooterHint: "↩ 輸入 · esc 關閉",
        folderLabel: "檔案夾",
        folderPlaceholder: "工作",
        showInLibraryLabel: "在快捷選單中顯示",
        variablesFormatCaption: "喺冒號後加上格式就可以自訂樣式,例如 {{date:yyyy-MM-dd}}。用 -tz(...) 指定時區,例如 {{date-tz(America/New_York):yyyy-MM-dd}}。",
        editorFormatCaption: "喺冒號後加上格式就可以自訂樣式,例如 {{date:yyyy-MM-dd}},或者用返上面嘅日期/時間掣。用 -tz(...) 指定時區,例如 {{date-tz(America/New_York):yyyy-MM-dd}}。",
        dateTimeInsertButton: "插入日期/時間",
        dateTimeEditButton: "編輯日期/時間",
        dateTimeTypeLabel: "類型",
        dateTimeKindDate: "日期",
        dateTimeKindTime: "時間",
        dateTimeKindDateTime: "日期和時間",
        dateTimeStyleLabel: "樣式",
        dateTimeStyleShort: "簡短",
        dateTimeStyleMedium: "中等",
        dateTimeStyleLong: "較長",
        dateTimeStyleFull: "完整",
        dateTimeStyleISO8601: "ISO 8601",
        dateTimeStyleCustom: "自訂",
        dateTimeStyleLocaleNote: "命名樣式會儲存 Mac 地區而家用緊嘅格式。",
        dateTimeTimezoneLabel: "時區",
        dateTimeTimezoneDeviceDefault: "裝置預設",
        dateTimeTimezoneValid: "有效時區",
        dateTimeTimezoneInvalid: "無法辨識嘅時區",
        dateTimeTimezoneClear: "清除時區",
        dateTimeTimezoneSearchPlaceholder: "搜尋時區",
        dateTimePatternLabel: "格式",
        dateTimePreviewLabel: "預覽",
        dateTimeConfirmInsert: "插入",
        dateTimeConfirmUpdate: "更新"
    )
}
