// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Русский — полный перевод интерфейса.
extension Strings {
    static let ru = Strings(
        statusIdleTooltip: "Vorssaint: обычный сон",
        statusActiveUntil: "Vorssaint: активно до",
        statusActiveIndefinite: "Vorssaint: активно без срока",
        menuEnableAwake: "Включить режим без сна",
        menuDisableAwake: "Выключить режим без сна",
        menuActivateFor: "Включить на…",
        menuSettings: "Настройки…",
        menuAbout: "О Vorssaint",
        menuQuit: "Выйти из Vorssaint",
        menuHide: "Скрыть Vorssaint",
        menuHideOthers: "Скрыть остальные",
        menuShowAll: "Показать все",
        menuEdit: "Правка",
        menuUndo: "Отменить",
        menuRedo: "Повторить",
        actionClear: "Очистить",
        actionRemove: "Удалить",
        actionBack: "Назад",
        actionSearch: "Поиск",
        actionMute: "Выключить звук",
        actionUnmute: "Включить звук",
        actionPlay: "Воспроизвести",
        actionPause: "Пауза",
        menuCut: "Вырезать",
        menuCopy: "Скопировать",
        menuPaste: "Вставить",
        menuSelectAll: "Выбрать все",
        menuWindow: "Окно",
        menuMinimize: "Свернуть",
        menuZoom: "Увеличить",
        menuClose: "Закрыть",

        minutes15: "15 минут",
        minutes30: "30 минут",
        hour1: "1 час",
        hours2: "2 часа",
        hours4: "4 часа",
        hours8: "8 часов",
        indefinitely: "Без срока",
        indefinite: "Бессрочно",

        panelSettings: "Настройки",
        panelQuit: "Выйти",
        panelHotkeyHint: "Горячая клавиша переключает",

        keepAwakeTitle: "Не давать Mac уснуть",
        keepAwakeEndsIn: "Завершится через",
        keepAwakeUntilDisabled: "Активно, пока вы не отключите режим",
        keepAwakeNormalRules: "Mac следует обычным правилам энергосбережения",
        keepAwakeOptions: "Параметры",
        keepAwakeMouseJiggle: "Слегка двигать указатель",
        keepAwakeMouseJiggleCaption: "Во время сеанса слегка двигает указатель с выбранным интервалом.",
        keepAwakeMouseJiggleInterval: "Интервал",
        keepAwakeActiveIconLabel: "Активный значок",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Кофе",
        keepAwakeActiveIconEye: "Глаз",
        keepAwakeActiveIconMoon: "Луна",
        keepAwakeActiveIconLight: "Лампочка",
        keepAwakeIconTintLabel: "Цвет активного значка",
        keepAwakeIconTintOrange: "Оранжевый",
        keepAwakeIconTintGreen: "Зелёный",
        keepAwakeIconTintBlue: "Синий",
        keepAwakeIconTintPurple: "Фиолетовый",
        keepAwakeIconTintPink: "Розовый",
        keepAwakeIconTintNone: "Без цвета",
        durationLabel: "Длительность",
        clamshellTitle: "Работать с закрытой крышкой",
        clamshellOnCaption: "Сон полностью отключён. Следите за питанием",
        clamshellNeedsSession: "Применяется, когда активен режим «Не давать уснуть»",
        clamshellReady: "Готово. Переключается без пароля",
        clamshellNeedsPassword: "Один раз попросит пароль администратора",

        systemSection: "Система",
        temperatures: "Температуры",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Батарея",
        usageSection: "Нагрузка",
        memorySection: "Память",
        memoryPressure: "Давление",
        memorySwapUsed: "Подкачка",
        memoryCompressed: "Сжатая",
        memoryCachedFiles: "Кэшированные файлы",
        pressureNormal: "Норма",
        pressureWarning: "Предупреждение",
        pressureCritical: "Критично",
        monitorUnavailable: "Датчики недоступны на этом Mac",
        energyAppsTitle: "Приложения с высоким энергопотреблением",
        energyAppsIdle: "Сейчас нет заметного энергопотребления",

        notifySessionEndedTitle: "Сеанс завершён",
        notifySessionEndedBody: "Время вышло. Mac снова будет засыпать как обычно.",
        notifyBatteryTitle: "Vorssaint отключён",
        notifyBatteryBody: "Низкий заряд. Обычный сон восстановлен, чтобы сохранить батарею.",
        adminPromptClamshellOn: "Vorssaint нужен ваш пароль, чтобы Mac продолжал работать с закрытой крышкой.",
        adminPromptClamshellOff: "Vorssaint нужен ваш пароль, чтобы вернуть обычный режим сна Mac.",
        adminPromptRecover: "Vorssaint завершился, пока сон Mac был отключён. Введите пароль, чтобы вернуть обычный режим сна.",
        adminPromptUpdate: "Vorssaint нужен ваш пароль, чтобы установить обновление.",
        adminPromptSudoersInstall: "Vorssaint создаст ограниченное правило (только pmset disablesleep), чтобы переключать режим закрытой крышки без запроса пароля. Пароль понадобится только сейчас.",
        adminPromptSudoersRemove: "Vorssaint удалит правило для режима закрытой крышки без пароля.",

        settingsTitle: "Настройки Vorssaint",
        tabGeneral: "Основное",
        tabEnergy: "Питание",
        tabMouse: "Мышь и трекпад",
        tabSwitcher: "Переключатель",
        tabAdvanced: "Дополнительно",
        tabAbout: "О программе",
        tabReleaseNotes: "Что нового",
        releaseNotesOnUpdateToggle: "Показывать изменения после обновления",
        minimalWindowPreviews: "Минималистичные миниатюры",
        minimalWindowPreviewsCaption: "Скрывает заголовки, кнопки и оформление миниатюр в Dock и переключателе приложений. Выделение остаётся видимым.",
        previewSizeLabel: "Размер превью",
        previewSizeNormal: "Обычный",
        previewSizeLarge: "Большой",
        previewSizeXLarge: "Очень большой",
        settingsGroupFeatures: "Функции",
        advancedResetSection: "Разрешения",
        advancedResetDescription: "Удаляет все разрешения, которые вы дали Vorssaint (Универсальный доступ, Запись экрана, Полный доступ к диску и другие), элемент входа и правило закрытой крышки. Полезно, если хотите начать с чистого листа или перед удалением. Приложение останется установленным.",
        advancedClearButton: "Сбросить все разрешения",
        advancedCleared: "Разрешения сброшены.",
        advancedClearConfirmTitle: "Сбросить все разрешения?",
        advancedClearConfirmBody: "Функции, которым нужны разрешения, перестанут работать, пока вы не выдадите их снова. Настройки сохранятся.",
        advancedUninstallSection: "Удаление",
        advancedUninstallDescription: "Сделает всё вышеперечисленное, затем удалит настройки и переместит Vorssaint в Корзину без остатка. После завершения приложение закроется. Установить его снова можно в любой момент.",
        advancedUninstallButton: "Удалить Vorssaint полностью",
        advancedUninstallConfirmTitle: "Удалить Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint очистит разрешения, удалит настройки и переместится в Корзину, после чего закроется. Это нельзя отменить из приложения, но файл останется в Корзине, пока вы её не очистите.",
        advancedUninstallFailedTitle: "Удаление остановлено",
        advancedUninstallFailedBody: "Vorssaint не смог вернуть изменённую системную настройку: режим сна, скорость вентиляторов или ускорение мыши. Ничего не удалено. Повторите попытку и разрешите запрос пароля, если он появится.",

        launchAtLogin: "Запускать при входе",
        languageLabel: "Язык",
        menuBarSection: "Строка меню",
        showCountdown: "Показывать оставшееся время рядом со значком",
        globalHotkeySection: "Глобальная горячая клавиша",
        hotkeyToggle: "Включить горячую клавишу для «Не давать уснуть»",
        hotkeyCaption: "Работает в любом приложении, без дополнительных разрешений.",

        sessionSection: "Сеанс",
        defaultDurationLabel: "Длительность по умолчанию",
        keepAwakeAutoStart: "Не давать уснуть при запуске Vorssaint",
        keepAwakeAutoStartCaption: "Запускает сеанс с длительностью по умолчанию.",
        batteryProtectionSection: "Защита батареи",
        batteryDisableBelow: "Отключать, когда заряд упадёт ниже",
        batteryNever: "Никогда",
        batteryProtectionCaption: "Не даёт забытому сеансу разрядить батарею MacBook.",
        clamshellSection: "Закрытая крышка",
        configuring: "Настройка…",
        sudoersFailed: "Не удалось включить режим закрытой крышки. Попробуйте ещё раз.",
        clamshellExplanation: "«Работать с закрытой крышкой» полностью отключает сон, пока активен режим «Не давать уснуть», и автоматически возвращает обычное поведение, когда сеанс заканчивается или приложение закрывается. Лучше использовать при подключённом питании.",

        scrollSection: "Прокрутка",
        invertMouseScroll: "Инвертировать прокрутку мыши",
        invertMouseScrollCaption: "Меняет направление колеса мыши на обратное.",
        scrollTrackpadNote: "Трекпад не изменяется: естественная прокрутка macOS остаётся как есть.",
        scrollActiveNow: "Прокрутка мыши сейчас инвертируется",
        mouseNavigationActiveNow: "Боковые кнопки сейчас активны",
        smoothScrollName: "Плавная прокрутка",
        smoothScrollCaption: "Превращает каждый щелчок колёсика мыши в короткое плавное скольжение. Трекпад не меняется.",
        smoothScrollStepLabel: "Скорость прокрутки",
        mouseNavigationSection: "Навигация",
        mouseNavigationEnable: "Использовать боковые кнопки для переходов назад и вперёд",
        mouseNavigationCaption: "Преобразует кнопки мыши Назад и Вперёд в команды навигации для Finder, браузеров и совместимых приложений.",
        middleClickSection: "Средняя кнопка",
        middleClickEnable: "Щелчок тремя пальцами как средняя кнопка",
        middleClickEnableCaption: "Нажатие на трекпад тремя пальцами работает как щелчок колёсиком мыши: открытие ссылок в новой вкладке, закрытие вкладок и всё остальное, что умеет средняя кнопка.",
        middleClickDragConflict: "Перетягивание тремя пальцами в macOS включено и использует этот же жест. Отключите его в Системных настройках в разделе Универсальный доступ, Управление указателем, Параметры трекпада, и щелчок средней кнопкой заработает.",
        middleClickTapPicker: "Лёгкое касание тоже кликает",
        middleClickTapOff: "Выключено",
        middleClickTapThreeFingers: "3 пальца",
        middleClickTapFourFingers: "4 пальца",
        middleClickTapCaption: "Лёгкое касание таким числом пальцев, без нажатия, тоже срабатывает как средний клик. Скольжение не считается. Если в macOS касание тремя пальцами назначено на «Поиск», отключите его, чтобы оба не срабатывали вместе.",
        quickToolsTab: "Быстрая панель",
        quickToolShortcutToggle: "Глобальное сочетание",
        ocrName: "Скопировать текст с экрана",
        ocrCaption: "Выделите область экрана, и распознанный текст будет скопирован и готов к вставке.",
        ocrCopied: "Текст скопирован",
        ocrNoText: "Текст не найден",
        colorPickerName: "Пипетка цвета",
        colorPickerCaption: "Возьмите цвет любого пикселя на экране и скопируйте его в удобном формате.",
        colorPickerFormatLabel: "Формат копирования",
        colorPickerBareHexToggle: "Копировать без префикса #",
        colorPickerPickNow: "Взять цвет",
        micMuteName: "Выключить микрофон",
        micUnmuteName: "Включить микрофон",
        micMuteCaption: "Отключает микрофон Mac одним щелчком или сочетанием клавиш во всех приложениях.",
        micMutedHUD: "Микрофон выключен",
        micUnmutedHUD: "Микрофон снова включён",
        micMuteMenuBarToggle: "Показывать в строке меню, пока микрофон выключен",
        micMuteMenuBarCaption: "Рядом со значком приложения в строке меню появляется красный перечёркнутый микрофон.",
        pastePlainName: "Вставить как обычный текст",
        pastePlainCaption: "Вставляет скопированное без цветов, шрифтов и форматирования. Оригинал остаётся в буфере обмена.",
        launcherName: "Быстрая панель",
        launcherCaption: "Плавающая панель с любимыми инструментами, вызывается сочетанием клавиш откуда угодно.",
        launcherOpenNow: "Открыть быструю панель",
        launcherEditHint: "Кнопка настройки позволяет выбирать, скрывать и перетаскивать инструменты.",
        launcherEmptyState: "Все инструменты скрыты. Верните их кнопкой настройки.",
        launcherAddSection: "Вернуть",
        launcherKeysHint: "Стрелки для навигации, Enter открывает, 1–9 открывают сразу",

        switcherSection: "Переключатель приложений",
        switcherEnable: "Использовать переключатель Vorssaint",
        switcherEnableCaption: "Переключает приложения и окна, включая свернутые и несколько окон одного приложения.",
        switcherUsageHint: "Удерживайте сочетание клавиш для навигации; отпустите, чтобы активировать окно. Shift или ← возвращают назад; W закрывает окно; Q завершает приложение; Esc отменяет.",
        switcherNoWindows: "Нет открытых окон",
        switcherIconRowMode: "Показывать %@ с крупными значками",
        switcherIconRowModeCaption: "Показывает по одному значку на приложение, а сверху миниатюры его окон.",
        switcherSimpleMode: "Простой переключатель приложений",
        switcherSimpleModeCaption: "Показывает значки приложений и заголовки окон, без миниатюр и захвата экрана переключателем.",
        switcherShortcutHintApps: "Приложения",
        switcherShortcutHintWindows: "Окна",
        switcherWindowShortcutCaption: "Открывает переключатель окон приложения на переднем плане. Пока открыт переключатель приложений, переходит между окнами выбранного приложения.",
        switcherTakeOverSystemShortcuts: "Заменить ⌘Tab и ⌘` macOS",
        switcherTakeOverSystemShortcutsCaption: "Отключает соответствующие сочетания macOS только на время работы переключателя Vorssaint. Все запущенные приложения остаются доступны.",
        switcherAppearanceDelay: "Задержка появления",
        switcherAppearanceDelayCaption: "Как долго нужно удерживать сочетание клавиш, прежде чем появится переключатель.",
        switcherMergeTabs: "Показывать одну запись на приложение",
        switcherMergeTabsCaption: "Сводит все окна приложения в одну запись в переключателе вместо отдельной записи на каждое окно.",
        switcherWindowlessApps: "Приложения без открытых окон",
        switcherWindowlessAppsCaption: "Выбирает, какие запущенные приложения без единого окна появляются в переключателе.",
        switcherWindowlessAppsOff: "Не показывать",
        switcherWindowlessAppsFinder: "Только Finder",
        switcherWindowlessAppsAll: "Все приложения",
        switcherNoOpenWindow: "Без открытых окон",
        switcherOtherDesktop: "Другой рабочий стол",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Показывать окна из Dock",
        dockPreviewEnableCaption: "Наведите указатель на открытое приложение в Dock, чтобы увидеть его окна, затем нажмите нужное.",
        dockPreviewBackgroundOpacity: "Фон панели",
        dockPreviewBackgroundOpacityCaption: "Уменьшите, чтобы видеть больше того, что находится за панелью.",
        dockPreviewOpenDelay: "Задержка открытия",
        dockPreviewOpenDelayCaption: "Сколько указатель должен оставаться на значке, прежде чем откроется панель.",
        dockPreviewQuitAppOnClose: "Завершать приложение кнопкой ×",
        dockPreviewQuitAppOnCloseCaption: "В Dock Preview кнопка × завершает всё приложение, а не закрывает только это окно.",
        dockClickMinimize: "Сворачивать кликом по Dock",
        dockClickMinimizeCaption: "Окна активного приложения сворачиваются при клике по его значку в Dock. Кликните ещё раз, чтобы вернуть их.",
        dockClickCycleWindows: "Кликом по Dock переключать окна",
        dockClickCycleWindowsCaption: "Клик по значку активного приложения в Dock переключает между его окнами, как ⌘`.",
        dockPreviewActiveNow: "Активно в Dock",
        dockPreviewDockUnavailable: "Не удалось прочитать элементы Dock.",
        dockPreviewAutohideBeta: "Бета. Возможны ошибки.",
        dockPreviewOpenWindow: "Открыть окно",
        dockPreviewCloseWindow: "Закрыть окно",
        dockPreviewMinimizeWindow: "Свернуть окно",
        dockPreviewRestoreWindow: "Восстановить окно",
        dockPreviewPinPanel: "Закрепить превью",
        dockPreviewUnpinPanel: "Открепить превью",
        dockPreviewPinned: "Закреплено",
        dockPreviewClosePanel: "Закрыть превью",
        dockPreviewPreviousWindow: "Предыдущее окно",
        dockPreviewNextWindow: "Следующее окно",

        cutPasteName: "Вырезать и вставить",
        cutPasteEnable: "Вырезать и вставлять файлы в Finder",
        cutPasteEnableCaption: "Используйте ⌘X для вырезания и ⌘V для перемещения файлов и папок в Finder.",
        cutPasteShowHUD: "Показывать плавающую панель",
        cutPasteShowHUDCaption: "Отображать плавающий индикатор с вырезанными файлами, пока активен Finder.",
        cutPasteHowTitle: "Как использовать",
        cutPasteStep1: "Выберите элементы в Finder и нажмите ⌘X, чтобы вырезать их.",
        cutPasteStep2: "Откройте папку назначения и нажмите ⌘V, чтобы переместить их туда.",
        cutPasteTextNote: "В текстовых полях (например, при переименовании) ⌘X и ⌘V продолжают работать как обычно.",
        cutPasteActiveNow: "Готово к вырезанию в Finder",
        cutPasteAutomationNote: "При первом использовании macOS попросит разрешение на управление Finder.",
        cutReadyTitle: "Вырезано",
        cutReadyHint: "в папке назначения для перемещения",
        cutCancel: "Отменить вырезание",
        cutDoneTitle: "Перемещено!",
        cutMovedSingular: "Перемещён 1 элемент",
        cutMovedPluralFormat: "Перемещено элементов: %d",
        cutSomeFailed: "Некоторые элементы не удалось переместить",
        cutMovingTitle: "Перемещение…",
        cutMovingCountFormat: "%d из %d",

        autoQuitName: "Закрывать вместе с окном",
        autoQuitEnable: "Закрывать приложение, когда закрывается его последнее окно",
        autoQuitEnableCaption: "Если закрыть последнее окно приложения, оно тоже завершится.",
        autoQuitActiveNow: "Сейчас активно",
        autoQuitHowTitle: "Как это работает",
        autoQuitStep1: "Закройте последнее окно приложения (⌘W или красной кнопкой).",
        autoQuitStep2: "Приложение завершится само. Диалоги «Сохранить изменения?» по-прежнему будут показываться.",
        autoQuitPredictableNote: "Приложения, которые обычно работают без окна, никогда не закрываются автоматически.",
        autoQuitExceptionsTitle: "Исключения",
        autoQuitExceptionsCaption: "Приложения в этом списке остаются открытыми даже без окон.",
        autoQuitExceptionsEmpty: "Без исключений",
        autoQuitAddApp: "Добавить приложение…",

        uninstallerName: "Деинсталлятор",
        uninstallerEnableCaption: "Удаляет приложение вместе с его кэшами, настройками, логами и прочими остатками.",
        uninstallerStep1: "Перетащите приложение в Настройки или выберите его из списка.",
        uninstallerStep2: "Просмотрите найденные файлы и объём занимаемого места.",
        uninstallerStep3: "Переместите в Корзину то, что хотите удалить. Ничего не удаляется безвозвратно.",
        uninstallerMenuItem: "Удалить приложение…",
        uninstallerDropTitle: "Перетащите сюда приложение",
        uninstallerDropSubtitle: "или выберите одно для сканирования",
        uninstallerChoose: "Выбрать приложение…",
        uninstallerPickerTitle: "Выберите приложение",
        uninstallerPickerSearch: "Искать приложения",
        uninstallerPickerEmpty: "Приложения не найдены",
        uninstallerEmptyNote: "Ничего не удаляется без вашего подтверждения.",
        uninstallerFDANote: "Выдайте полный доступ к диску для более глубокого сканирования.",
        uninstallerFDAGrant: "Выдать доступ…",
        uninstallerFDAHint: "Включите Vorssaint в списке. Если его там нет, нажмите + и выберите Vorssaint из папки «Программы». Доступ начнёт действовать только после повторного запуска приложения.",
        uninstallerFDARelaunch: "Перезапустить сейчас",
        uninstallerScanning: "Сканирование файлов…",
        uninstallerRemoving: "Перемещение в Корзину…",
        uninstallerFoundTitle: "найдено",
        uninstallerSelectedFormat: "Выбрано %d из %d",
        uninstallerRemove: "Переместить в Корзину",
        uninstallerCancel: "Отмена",
        uninstallerDoneTitle: "Готово!",
        uninstallerFreedFormat: "Освобождено %@",
        uninstallerSomeFailed: "Некоторые элементы не удалось переместить в Корзину.",
        uninstallerFailedNeedsFDA: "Данные приложений в песочнице можно переместить только с полным доступом к диску. Пароль администратора его не заменяет.",
        uninstallerFailedMoreFormat: "и ещё %d",
        uninstallerAnother: "Удалить другое",
        uninstallerCatApp: "Приложение",
        uninstallerCatSupport: "Поддержка",
        uninstallerCatCaches: "Кэши",
        uninstallerCatPreferences: "Настройки",
        uninstallerCatContainers: "Контейнеры",
        uninstallerCatLogs: "Логи",
        uninstallerCatState: "Сохранённое состояние",
        uninstallerCatOther: "Другое",

        urlCleanerName: "Очистка URL",
        urlCleanerEnable: "Очищать URL при копировании",
        urlCleanerEnableCaption: "Удаляет параметры отслеживания из ссылки, как только она попадает в буфер обмена.",
        urlCleanerActiveNow: "Сейчас активно",
        urlCleanerManualTitle: "Очистить сейчас",
        urlCleanerInputPlaceholder: "Вставьте URL",
        urlCleanerOutputPlaceholder: "Здесь появится очищенный URL",
        urlCleanerCleanButton: "Очистить",
        urlCleanerPasteButton: "Вставить",
        urlCleanerCopyButton: "Скопировать",
        urlCleanerClearButton: "Очистить поле",
        urlCleanerNoURL: "Вставьте корректный URL.",
        urlCleanerNoChange: "Нечего очищать.",
        urlCleanerCleaned: "URL очищен.",
        urlCleanerCopied: "Скопировано.",
        urlCleanerLocalNote: "Локально. Без сети.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Поиск, установка и удаление пакетов Homebrew.",
        homebrewMissingTitle: "Homebrew не найден",
        homebrewMissingBody: "Vorssaint может открыть Терминал с официальным установщиком Homebrew. Терминал покажет шаги и при необходимости запросит ваш пароль.",
        homebrewInstallHomebrew: "Установить Homebrew",
        homebrewInstallHomebrewCaption: "Когда Терминал завершит установку, вернитесь сюда и нажмите «Обновить».",
        homebrewInstallHomebrewOpened: "Установщик открыт в Терминале.",
        homebrewShellSetupTitle: "Завершить настройку Терминала",
        homebrewShellSetupBody: "Homebrew установлен, но Терминал может ещё не видеть команду brew. Vorssaint может открыть Терминал с нужной командой настройки.",
        homebrewShellSetupButton: "Настроить Терминал",
        homebrewShellSetupOpened: "Команда открыта в Терминале. Затем вернитесь сюда и нажмите «Обновить».",
        homebrewRefresh: "Обновить",
        homebrewCheckPackages: "Проверить пакеты",
        homebrewTrustTitle: "Tap ещё не доверенный",
        homebrewTrustCaption: "Homebrew теперь запрашивает подтверждение перед использованием сторонних tap. Доверьтесь %@, чтобы продолжить.",
        homebrewTrustButton: "Доверять и продолжить",
        homebrewSearchPlaceholder: "Поиск пакетов",
        homebrewKeyboardHint: "Клавиши Space и Return закрывают системную панель macOS. Используйте кнопку поиска.",
        homebrewSearchButton: "Искать",
        homebrewSearchResults: "Результаты",
        homebrewInstalled: "Установлено",
        homebrewAll: "Все",
        homebrewFormulas: "Formulae",
        homebrewCasks: "Casks",
        homebrewNoPackages: "Пакеты не найдены",
        homebrewNoSelection: "Выберите установленный пакет или найдите новый.",
        homebrewDetailsTitle: "Детали пакета",
        homebrewInstall: "Установить",
        homebrewUninstall: "Удалить",
        homebrewUpgrade: "Обновить",
        homebrewUpgradeAll: "Обновить всё",
        homebrewUpdateHomebrew: "Обновить Homebrew",
        homebrewAllPackages: "пакеты",
        homebrewOpenTerminal: "Открыть Терминал",
        homebrewCancelOperation: "Отмена",
        homebrewClearLog: "Очистить лог",
        homebrewLogTitle: "Лог",
        homebrewVersion: "Версия",
        homebrewDescription: "Тип",
        homebrewHomepage: "Открыть сайт",
        homebrewPopularity: "Популярность",
        homebrewPopularityFormat: "%@ установок за %@ дней",
        homebrewInstalledBadge: "Установлено",
        homebrewNotInstalledBadge: "Не установлено",
        homebrewUpdates: "Обновления",
        homebrewUpdateAvailableBadge: "Доступно обновление",
        homebrewLatestVersion: "Последняя",
        homebrewConfirmInstallTitle: "Установить через Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew загрузит и установит %@. Также могут быть установлены зависимости.",
        homebrewConfirmUninstallTitle: "Удалить через Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew удалит %@. Конфигурационные файлы могут остаться в системе.",
        homebrewConfirmUpgradeTitle: "Обновить через Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew загрузит и применит последнюю версию %@. Также могут обновиться зависимости.",
        homebrewConfirmUpgradeAllTitle: "Обновить всё через Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew загрузит и применит последние версии пакетов, для которых доступны обновления. Зависимости тоже могут обновиться.",
        homebrewConfirmUpdateHomebrewTitle: "Обновить Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew получит свежую информацию и затем перезагрузит ваши пакеты.",
        homebrewTerminalFallback: "Для этой операции нужен Терминал, чтобы запросить пароль администратора. Vorssaint не перехватывает пароли.",
        homebrewLoading: "Загрузка…",
        homebrewSearchEmpty: "Нет результатов",
        homebrewOperationInstallFormat: "Установка %@",
        homebrewOperationUninstallFormat: "Удаление %@",
        homebrewOperationUpgradeFormat: "Обновление %@",
        homebrewOperationUpgradeAll: "Обновление пакетов",
        homebrewOperationUpdateHomebrew: "Обновление Homebrew",
        homebrewOperationInstalledFormat: "%@ установлен.",
        homebrewOperationUninstalledFormat: "%@ удалён.",
        homebrewOperationUpgradedFormat: "%@ обновлён.",
        homebrewOperationUpgradedAll: "Пакеты обновлены.",
        homebrewOperationUpdatedHomebrew: "Homebrew обновлён.",
        homebrewOperationFailedFormat: "Не удалось завершить %@.",
        homebrewOperationCancelled: "Операция отменена.",
        homebrewOperationPreparing: "Подготовка…",
        homebrewOperationDownloading: "Загрузка файлов…",
        homebrewOperationInstalling: "Установка файлов…",
        homebrewOperationUninstalling: "Удаление файлов…",
        homebrewOperationUpgrading: "Обновление файлов…",
        homebrewOperationFinalizing: "Завершение…",
        homebrewOperationRefreshing: "Обновление списка…",
        homebrewOperationTerminal: "Продолжите в Терминале.",
        homebrewOperationElapsedFormat: "Прошло %@",
        homebrewOperationShowDetails: "Показать детали",
        homebrewOperationHideDetails: "Скрыть детали",
        homebrewOperationTechnicalLog: "Технические детали",
        homebrewOperationProgressUnknown: "Homebrew ещё не сообщил процент выполнения.",

        mediaName: "Медиа",
        mediaEnableCaption: "Сжимайте видео, преобразуйте и обрабатывайте изображения, создавайте GIF и извлекайте текст локально.",
        mediaLocalNote: "Локально. Без сети.",
        mediaToolVideo: "Видео",
        mediaToolGIF: "GIF",
        mediaToolImage: "Изображение",
        mediaToolText: "Текст",
        mediaSelectFile: "Выбрать файл",
        mediaDropHint: "Перетащите сюда файл или нажмите для выбора.",
        mediaOutput: "Вывод",
        mediaOutputAutomatic: "Автоматически",
        mediaChooseOutput: "Папка назначения",
        mediaStartVideo: "Сжать видео",
        mediaStartGIF: "Создать GIF",
        mediaStartImage: "Обработать изображение",
        mediaStartConvertPDF: "Конвертировать в PDF",
        mediaStartText: "Извлечь текст",
        mediaCancel: "Отмена",
        mediaStartTime: "Начало",
        mediaEndTime: "Конец",
        mediaQuality: "Сжатие",
        mediaCompressionLow: "Низкое",
        mediaCompressionMedium: "Среднее",
        mediaCompressionHigh: "Высокое",
        mediaMaxSize: "Размер",
        mediaSizingResolution: "Разрешение",
        mediaSizingFileSize: "Размер файла",
        mediaTargetSize: "Целевой размер",
        mediaTargetSizeHint: "Разрешение подстраивается, чтобы не превысить лимит.",
        mediaErrorTargetTooSmall: "Целевой размер слишком мал для этого ролика. Сократите его или увеличьте лимит.",
        mediaMegabytesSuffix: " МБ",
        mediaWidth: "Ширина",
        mediaFPS: "FPS",
        mediaKeepAudio: "Сохранить звук",
        mediaCodec: "Кодек",
        mediaFormat: "Формат",
        mediaStripMetadata: "Удалить метаданные",
        mediaLoopGIF: "Зациклить GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Точно",
        mediaOCRFast: "Быстро",
        mediaLanguageCorrection: "Языковая коррекция",
        mediaTextOutputNote: "Извлечённый текст можно скопировать и сохранить как TXT.",
        mediaRunning: "Обработка",
        mediaCompleted: "Готово",
        mediaCancelled: "Отменено.",
        mediaOpenInFinder: "Показать",
        mediaCopyText: "Скопировать текст",
        mediaRunAgain: "Запустить снова",
        mediaEmptyText: "Текст не найден.",
        mediaResultSavedFormat: "Сохранено как %@",
        mediaResultSizeFormat: "%@ в %@",
        mediaResultGrewCaption: "Преобразованный файл получился больше исходного.",
        mediaErrorNoFile: "Сначала выберите файл.",
        mediaErrorNoVideo: "У этого файла нет видеодорожки.",
        mediaErrorSameOutput: "Выберите папку назначения, отличную от исходного файла.",
        mediaErrorUnsupported: "Формат не поддерживается macOS.",

        shelfName: "Полка",
        shelfEnable: "Временная область для перетаскивания файлов",
        shelfEnableCaption: "Плавающее место, куда можно собрать файлы, изображения и текст, а потом перетащить их куда угодно.",
        shelfHowTitle: "Как использовать",
        shelfStep1: "Откройте её горячей клавишей или встряхнув мышь во время перетаскивания.",
        shelfStep2: "Бросайте на неё файлы, изображения, ссылки или текст, чтобы временно их хранить.",
        shelfStep3: "Когда понадобится, перетащите каждый элемент обратно в любое приложение.",
        shelfShakeToggle: "Открывать встряхиванием мыши при перетаскивании",
        shelfShakeCaption: "Быстро потрясите указателем, удерживая объект, чтобы вызвать полку рядом с курсором.",
        shelfDropZoneToggle: "Держать перетащенные файлы в строке меню",
        shelfDropZoneCaption: "Пока вы перетаскиваете файл, полка появляется под значком в строке меню. То, что вы отпустите, остаётся прямо там, в кнопке, которую можно свернуть и открыть одним щелчком и которая исчезает, когда полка пустеет.",
        shelfDropZoneLabel: "Отпустите здесь",
        shelfCollapse: "Свернуть",
        shelfBehaviorTitle: "После использования",
        shelfCloseAfterDrop: "Закрывать после переноса в другое приложение",
        shelfCloseAfterDropCaption: "Закрывает полку, когда приложение принимает элементы. Булавка на панели оставляет её открытой.",
        shelfRemoveAfterDrop: "Удалять элементы после переноса",
        shelfRemoveAfterDropCaption: "Принятые другим приложением элементы покидают полку. Отключите, чтобы сохранить копию.",
        shelfExclusionsTitle: "Автоматические исключения",
        shelfExclusionsEmpty: "Приложения не добавлены.",
        shelfExclusionsCaption: "Встряхивание и зона в строке меню не открываются для перетаскиваний из этих приложений. Сочетание клавиш и Открыть сейчас продолжают работать.",
        shelfPin: "Оставить открытой",
        shelfUnpin: "Разрешить закрытие после использования",
        extraBrightnessName: "Дополнительная яркость",
        extraBrightnessCaption: "Использует запас HDR дисплея, чтобы выйти за максимальную яркость. Расходует больше батареи, и Mac может нагреваться.",
        extraBrightnessLevelLabel: "Интенсивность",
        extraBrightnessUnsupported: "Доступно только на дисплеях XDR, например у MacBook Pro 14 и 16 дюймов.",
        shelfHotkeyLabel: "Горячая клавиша",
        shelfOpenNow: "Открыть сейчас",
        shelfNoPermission: "Разрешения не нужны.",
        shelfMenuItem: "Открыть полку",
        shelfTitle: "Полка",
        shelfEmpty: "Перетащите элементы сюда",
        shelfClearAll: "Очистить всё",
        shelfRemoveSelected: "Удалить выбранное",
        shelfSelectedFormat: "Выбрано: %d",
        shelfHint: "Нажмите для выбора. Перетащите для использования или щёлкните правой кнопкой для других действий.",
        shelfItemImage: "Изображение",
        shelfTooltipItemsFormat: "%d элементов",
        shelfTooltipItemsFew: "%d элемента",
        shelfTooltipImageSingular: "%d изображение",
        shelfTooltipImageFew: "%d изображения",
        shelfTooltipImagePlural: "%d изображений",
        shelfTooltipFileSingular: "%d файл",
        shelfTooltipFileFew: "%d файла",
        shelfTooltipFilePlural: "%d файлов",
        shelfTooltipNoteSingular: "%d заметка",
        shelfTooltipNoteFew: "%d заметки",
        shelfTooltipNotePlural: "%d заметок",
        shelfTooltipLinkSingular: "%d ссылка",
        shelfTooltipLinkFew: "%d ссылки",
        shelfTooltipLinkPlural: "%d ссылок",
        shelfActionOpen: "Открыть",
        shelfActionOpenWith: "Открыть с помощью",
        shelfActionShare: "Поделиться",

        breakdownMeasuring: "Измерение…",

        mixerSection: "Микшер громкости",
        mixerEmpty: "Здесь появятся приложения, которые воспроизводят звук",
        mixerUnavailable: "Доступно в macOS 14.4 и новее",
        mixerPermissionBody: "Чтобы регулировать громкость по приложениям, разрешите «Запись экрана и системного аудио» в Системных настройках. Аудио никогда не записывается.",
        mixerResetTooltip: "Сбросить на 100%",
        mixerOutputDefault: "По умолчанию",
        mixerOutputCurrent: "текущий",
        mixerOutputUnavailable: "Выход недоступен",
        mixerOutputFallback: "Используется выход по умолчанию, пока это устройство не вернётся.",
        mixerBypassedCaption: "Это приложение само управляет своим звуком.",
        mixerOutputTooltip: "Выбрать выход",
        mixerSystemOutputTitle: "Выход",
        mixerSystemOutputNoDevices: "Выходы не найдены",
        mixerSystemOutputTooltip: "Выбрать системный выход",
        mixerSystemOutputErrorFormat: "Не удалось переключить: %@",
        mixerLowerOnHeadphonesDisconnect: "Снижать громкость при отключении наушников",
        mixerLowerOnHeadphonesDisconnectCaption: "Меняет громкость выхода при отключении проводных или Bluetooth-наушников.",
        mixerHeadphonesDisconnectVolume: "Громкость после отключения",
        preciseVolumeRollerEnable: "Использовать более точные шаги громкости",
        preciseVolumeRollerCaption: "Преобразует колесики и клавиши громкости в меньшие системные шаги.",
        preciseVolumeRollerTapFailed: "Не удалось отслеживать клавиши громкости.",
        soundOutputSwitcherTitle: "Переключатель выхода",
        soundOutputSwitcherEnable: "Переключать выходы горячей клавишей",
        soundOutputSwitcherCaption: "Выберите выходы и используйте сочетание клавиш, чтобы перейти к следующему доступному.",
        soundOutputSwitcherDevices: "Выходы в цикле",
        soundOutputSwitcherNoAvailableSelection: "Выберите хотя бы один доступный выход.",
        mixerInputTitle: "Микрофон",
        mixerInputNoDevices: "Микрофоны не найдены",
        mixerInputUnavailable: "Микрофон недоступен",
        mixerInputFallback: "Используется значение по умолчанию, пока этот микрофон не вернётся.",
        mixerInputTooltip: "Выбрать микрофон",
        mixerInputErrorFormat: "Не удалось переключить: %@",
        mixerVisibleApps: "Приложения в списке",
        mixerAllShown: "Все",
        mixerHiddenCountLabel: "Скрыто",
        mixerHideFromList: "Скрыть из списка",

        updatesSection: "Обновления",
        autoCheckToggle: "Проверять обновления автоматически",
        includeBetaUpdatesToggle: "Получать бета-версии",
        includeBetaUpdatesCaption: "Бета-версии содержат функции в разработке и могут работать нестабильно.",
        betaBadgeLabel: "Бета",
        checkNowButton: "Проверить сейчас",
        updateChecking: "Проверка…",
        updateUpToDate: "У вас последняя версия.",
        updateAvailablePrefix: "Доступно обновление:",
        updateInstallButton: "Скачать и установить",
        updateDownloading: "Загрузка обновления…",
        updateInstalling: "Установка и перезапуск…",
        updateFailedPrefix: "Не удалось проверить:",
        updateLastChecked: "Последняя проверка:",
        updateNotifyTitle: "Обновление Vorssaint",
        updateInstallFailedBody: "Обновление загружено, но применить его не удалось. Скачайте последнюю версию со страницы релизов на GitHub и перетащите приложение поверх текущего.",
        updateNeedsApplicationsTitle: "Переместите Vorssaint в папку «Программы»",
        updateNeedsApplicationsBody: "Приложение запущено из места, которое нельзя обновить, например из образа диска или временного системного расположения. Перетащите Vorssaint в папку «Программы», откройте его оттуда и попробуйте снова.",
        menuCheckUpdates: "Проверить обновления…",

        permissionRequired: "Требуется разрешение",
        permissionAccessibility: "Универсальный доступ",
        permissionScreenRecording: "Запись экрана",
        permissionGranted: "Разрешено",
        permissionMissing: "Не выдано",
        permissionOpenSettings: "Открыть Системные настройки…",
        permissionRequest: "Выдать доступ",
        permissionRestartNote: "После выдачи доступа macOS может предложить переоткрыть приложение.",

        aboutDescription: "Набор полезных инструментов для вашего Mac.\nПитание, системный монитор, прокрутка и переключатель окон прямо в строке меню.",
        versionPrefix: "Версия",
        reviewIntro: "Повторно показать вступление",
        reviewHighlights: "Повторно показать обзор новинок",
        viewOnGitHub: "Открыть на GitHub",

        obContinue: "Далее",
        obBack: "Назад",
        obSkipStep: "Пропустить шаг",
        obStart: "Открыть Vorssaint",
        obStepWelcomeTitle: "Добро пожаловать в Vorssaint",
        obStepWelcomeBody: "Незаметная утилита в строке меню, которая делает повседневную работу в macOS удобнее.",
        obWelcomeBullet1Title: "Питание под контролем",
        obWelcomeBullet1Body: "Не давайте Mac уснуть столько, сколько нужно, даже с закрытой крышкой.",
        obWelcomeBullet2Title: "Понятная картина системы",
        obWelcomeBullet2Body: "Температуры CPU, GPU и батареи, нагрузка железа и давление памяти в реальном времени.",
        obWelcomeBullet3Title: "Мышь и окна по-вашему",
        obWelcomeBullet3Body: "Инверсия прокрутки мыши и переключатель окон с миниатюрами.",
        obLanguageLabel: "Язык",
        obStepAccessibilityTitle: "Универсальный доступ",
        obStepAccessibilityBody: "Нужен для инверсии прокрутки мыши и для работы переключателя окон с клавиатуры.",
        obAccessibilityWhy: "Приложение отслеживает только колесо мыши и сочетание клавиш переключателя. Ничего не записывается и никуда не отправляется.",
        obStepRecordingTitle: "Запись экрана",
        obStepRecordingBody: "Позволяет переключателю показывать настоящие миниатюры окон вместо одних значков.",
        obRecordingWhy: "Миниатюры создаются на лету, остаются в памяти и никогда не покидают ваш Mac. Без этого переключатель всё равно работает, но только со значками.",
        obStepMonitorTitle: "Системный монитор",
        obStepMonitorBody: "Панель показывает температуры CPU, GPU и батареи, нагрузку железа и давление памяти.",
        obMonitorNoPermission: "Разрешения не нужны. Датчики читаются напрямую из системы.",
        obStepOptionalTitle: "Необязательные функции",
        obStepOptionalBody: "Включите то, чем хотите пользоваться прямо сейчас. Всё можно будет изменить позже в Настройках.",
        obStepStatusTitle: "Проверка",
        obStepStatusBody: "Убедитесь, что всё готово для нужных вам функций.",
        obStatusRecheck: "Проверить снова",
        obStepDoneTitle: "Всё готово!",
        obStepDoneBody: "Vorssaint уже заботится о вашем Mac.",
        obDoneHint: "Ищите чёрную дыру в строке меню, в правом верхнем углу экрана.",
        obWhatsNewTitle: "Что нового в этой версии",
        obWhatsNewFallback: "В это обновление вошли последние исправления и улучшения.",
        obLanguageUpdateTitle: "Теперь и на вашем языке",
        obLanguageUpdateBody: "Теперь Vorssaint говорит на нескольких языках. Выберите тот, который хотите использовать; в любой момент его можно сменить в Настройках.",
        obPurposeTitle: "Что привело вас сюда?",
        obPurposeBody: "Выберите готовую настройку или именно те функции, которыми хотите пользоваться.",
        obPurposeSkip: "Функции можно добавить или убрать позже в настройках.",

        tabMonitor: "Монитор",
        monitorMenuBarSection: "В строке меню",
        monitorMenuBarCaption: "Выберите, что показывать рядом со значком в строке меню.",
        monitorCombineTemperatures: "Объединять нагрузку и температуру",
        monitorCombineTemperaturesCaption: "Когда включены и нагрузка, и температура одного и того же элемента, показывать их одним блоком.",
        monitorSeparateMenuBarMetrics: "Выводить метрики отдельными элементами",
        monitorSeparateMenuBarMetricsCaption: "Разделяет активные блоки в строке меню и сохраняет нагрузку и температуру вместе, если включено объединение.",
        monitorNetworkUploadFirst: "Показывать отдачу над загрузкой",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Память",
        monitorShowNetwork: "Сеть",
        monitorShowPowerLabel: "Питание",
        monitorIntervalLabel: "Обновлять каждые",
        monitorInterval1: "1 секунду",
        monitorInterval2: "2 секунды",
        monitorInterval5: "5 секунд",
        monitorPanelSection: "В панели",
        panelNavigationMode: "Навигация по секциям",
        panelNavigationCaption: "Показывает по одной секции за раз. Выберите «Список», чтобы просматривать всё непрерывной прокруткой.",
        panelFooterSections: "Секции",
        panelFooterList: "Список",
        betaBadge: "БЕТА",
        betaFeatureWarning: "Бета. Возможны ошибки.",

        networkSection: "Сеть",
        networkDownload: "Загрузка",
        networkUpload: "Отдача",
        networkThisSession: "Этот сеанс",
        networkMeasuring: "Измерение…",
        networkApps: "Приложения, использующие сеть",
        networkAppsIdle: "Сейчас нет приложений, использующих сеть",

        diskSection: "Диски",
        diskUsed: "занято",
        diskFree: "свободно",
        diskAvailable: "доступно",
        diskPurgeable: "очищаемый",
        diskInternal: "Внутренний",
        diskExternal: "Внешний",
        diskSelect: "Выбрать диск",
        diskRead: "Чтение",
        diskWrite: "Запись",
        diskSMARTStatus: "Статус",
        diskSMARTUnavailable: "SMART недоступен для этого диска",
        diskTotalRead: "Всего прочитано",
        diskTotalWritten: "Всего записано",
        diskTemperature: "Температура",
        diskHealth: "Состояние",
        diskPowerCycles: "Циклы питания",
        diskPowerOnHours: "Часы работы",
        diskUnsafeShutdowns: "Небезопасные выключения",
        diskMediaErrors: "Ошибки носителя",
        diskEject: "Извлечь",
        diskEjectAll: "Извлечь всё",
        diskEjecting: "Извлечение…",
        diskReadyToRemove: "Можно отключать",
        diskEjectFailed: "Не удалось извлечь",
        diskProtectionCaption: "Извлекайте перед отключением.",
        diskNoExternal: "Нет внешних дисков, готовых к извлечению.",
        diskOpenInFinder: "Открыть",
        diskStorageSettings: "Хранилище",
        diskNoDisks: "Смонтированные диски не найдены.",

        powerSection: "Питание",
        powerSystem: "Система",
        powerAdapter: "Адаптер",
        powerBattery: "Батарея",
        powerCharging: "Заряжается",
        powerOnBattery: "От батареи",
        powerPluggedIn: "Подключено к питанию",
        powerUnavailable: "Метрики питания недоступны на этом Mac",
        powerAdapterMaxFormat: "макс. %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Температура CPU",
        monitorShowGPUTemperature: "Температура GPU",
        monitorShowBatteryTemperature: "Температура батареи",
        monitorShowPeripheralBattery: "Батарея аксессуаров",
        peripheralBatteryNoDevices: "Устройства не найдены",
        monitorGraphsSection: "Графики",
        monitorGraphsCaption: "Выберите, для каких метрик показывать график во времени.",

        updateBannerTitle: "Доступно обновление",
        updateBannerAction: "Обновить",
        obStepMenuBarTitle: "Метрики в строке меню",
        obStepMenuBarBody: "Выберите, что показывать рядом со значком. Превью выше обновляется вживую.",
        obStepMenuBarNote: "Новое: блоки Сеть и Питание, а также графики в панели. Позже всё можно настроить в Настройки › Монитор.",
        monitorMenuBarPresetLabel: "Стиль",
        menuBarPresetReadable: "Читаемый",
        menuBarPresetDense: "Плотный",
        menuBarSpacingLabel: "Интервал в строке меню",
        menuBarSpacingStandard: "Стандартный",
        menuBarSpacingCompact: "Компактный",
        menuBarHideIconToggle: "Скрывать значок приложения, пока показаны метрики",
        menuBarHideIconCaption: "Значок возвращается сам, когда метрики исчезают из строки меню, а также когда есть что сообщить (готово обновление или выключен микрофон).",
        monitorLabelStyleLabel: "Подписи",
        menuBarLabelStyleCompact: "Компактные",
        menuBarLabelStyleClassic: "Классические",
        monitorMemoryStyleLabel: "Показывать память как",
        monitorMemoryPressureDot: "Точка давления",
        memoryStyleDot: "Точка",
        memoryStylePercent: "%",
        memoryStyleBoth: "Оба",
        systemUptime: "Время работы",
        batteryCharge: "Заряд",
        powerHealth: "Состояние батареи",
        powerCycles: "Циклы",
        speedTestRun: "Тест скорости",
        speedTestAgain: "Проверить снова",
        speedTestLatency: "Задержка",
        speedTestTesting: "Проверка…",
        speedTestFailed: "Тест не удался",

        monitorShowInPanel: "Показывать в панели",
        disclosureExpanded: "Развёрнуто",
        disclosureCollapsed: "Свёрнуто",
        panelHideItem: "Скрыть из панели",
        panelShowItem: "Показать в панели",
        panelHiddenItem: "Скрыто",
        monitorItemUptime: "Время работы",
        monitorItemNetSpeed: "Текущая скорость",
        monitorItemNetTotals: "Итоги сеанса",
        monitorItemNetTest: "Тест скорости",
        monitorItemDiskUsage: "Использование диска",
        monitorItemDiskActivity: "Текущая активность",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Защита внешних дисков",
        monitorItemDiskTools: "Инструменты",
        monitorPanelConfigHint: "Откройте блок, чтобы выбрать, что он показывает.",
        monitorOrderSection: "Порядок секций",
        monitorOrderHint: "Перетаскивайте, чтобы менять порядок секций панели, и используйте глаз, чтобы показывать или скрывать каждую из них.",
        obStepPanelTitle: "Что находится в панели",
        obStepPanelBody: "Откройте каждый блок и выберите, что именно будет показываться по нажатию на значок.",
        obStepPanelNavigationTitle: "Панель по секциям",
        obStepPanelNavigationBody: "Теперь панель может показывать по одной секции за раз. Переключаться между «Секциями» и «Списком» можно в настройках.",

        cleaningMenuItem: "Режим очистки",
        utilitiesSection: "Утилиты",
        quickControlsSection: "Управление",
        panelCategoryWindows: "Окна",
        panelCategoryInput: "Мышь и клавиатура",
        panelCategoryFiles: "Файлы",
        windowMaximizeName: "Разворачивать окна",
        windowMaximizeCaption: "Зелёная кнопка разворачивает окно, не создавая новый Space.",
        windowMaximizeActiveNow: "Переопределение зелёной кнопки активно",
        windowMaximizeNeedsAccessibility: "Для работы нужен Универсальный доступ.",
        keyDebounceName: "Фильтр повторов",
        keyDebounceEnable: "Фильтровать повторные нажатия",
        keyDebounceCaption: "Фильтрует очень быстрые повторные нажатия клавиш.",
        keyDebounceActiveNow: "Фильтр активен",
        keyDebounceGlobalWindow: "Глобальное окно",
        keyDebouncePerKeySection: "Отдельные клавиши",
        keyDebouncePerKeyCaption: "Значения для отдельных клавиш имеют приоритет над глобальным окном. Используйте 0 мс, чтобы не фильтровать конкретную клавишу.",
        keyDebounceKeyLabel: "Клавиша",
        keyDebounceWindowLabel: "Окно",
        keyDebounceAddKey: "Добавить клавишу",
        keyDebounceNoOverrides: "Отдельные клавиши не настроены.",
        keyDebounceRemoveKey: "Удалить клавишу",
        cleaningPanelCaption: "Блокирует клавиатуру, чтобы можно было безопасно почистить её.",
        cleaningOverlayTitle: "Клавиатура заблокирована для чистки",
        cleaningOverlaySubtitle: "Нажмите Esc 5 раз, чтобы разблокировать",
        cleaningOverlayUnlock: "Разблокировать",
        cleaningOverlayMouseHint: "Мышь и трекпад продолжают работать",
        cleaningKeepScreenVisibleToggle: "Оставлять экран видимым",
        cleaningKeepScreenVisibleCaption: "Показывает компактный индикатор в углу экрана вместо затемнения содержимого.",
        cleaningStartNow: "Заблокировать клавиатуру сейчас",
        cleaningNeedsAxTitle: "Нужен Универсальный доступ",
        cleaningNeedsAxBody: "Чтобы безопасно блокировать клавиатуру, Vorssaint нужен доступ к Универсальному доступу. Выдайте его в Системных настройках и попробуйте снова.",

        tabSupport: "Поддержка",
        shortcutsPageCaption: "Изменяйте здесь все глобальные сочетания установленных на этом Mac функций. Неактивные сочетания сохраняются, но не срабатывают.",
        shortcutsPageTitle: "Сочетания клавиш",
        settingsSearchPlaceholder: "Поиск в настройках",
        donateHeading: "Помогите Vorssaint развиваться",
        donateMessage: "Vorssaint бесплатен, независим и создаётся в моё свободное время. Если вы хотите помочь финансово, Buy Me a Coffee напрямую поддерживает дальнейшую разработку.",
        donateButton: "Поддержать через Buy Me a Coffee",
        donateThanks: "Спасибо, что вы здесь. 🖤",
        supportIntroTitle: "Помогите Vorssaint развиваться",
        supportIntroMessage: "Если вы хотите финансово поддержать разработку, сделать это можно только через Buy Me a Coffee.",
        supportIntroStarButton: "Поставить Vorssaint звезду на GitHub",
        supportIntroStarMessage: "Финансовая поддержка совсем не обязательна. Звезда на GitHub помогает большему числу людей найти Vorssaint и действительно влияет на его развитие.",
        supportIntroCoffeeButton: "Поддержать через Buy Me a Coffee",
        supportIntroLaterButton: "Не сейчас",
        supportIntroDoneButton: "Готово",
        discordIntroTitle: "Сообщество Vorssaint в Discord только начинает расти",
        discordIntroMessage: "Сообщество Vorssaint новое и всё ещё формируется. Присоединяйтесь сейчас, знакомьтесь с другими пользователями и помогите создать дружелюбное пространство вокруг приложения.",
        discordIntroJoinButton: "Присоединиться к сообществу в Discord",
        communityIntroTitle: "Смотрите всё раньше всех",
        communityIntroMessage: "Те, кто уже следил за мной в X, увидели многие изменения этого обновления раньше всех. Там я публикую превью будущих новинок и показываю, как они работают, чтобы вы знали основы ещё до выхода обновления. Подписывайтесь и узнайте, что будет дальше!",
        communityIntroFollowButton: "Подписаться на @vorssaint в X",
        homebrewOfficialIntroTitle: "Теперь в официальном каталоге Homebrew",
        homebrewOfficialIntroMessage: "Теперь Vorssaint можно установить прямо из официального каталога Homebrew.",
        homebrewOfficialIntroInstallLabel: "Новая установка",
        homebrewOfficialIntroMigrationTitle: "Пользовались старым tap?",
        homebrewOfficialIntroMigrationMessage: "Удалите старый tap один раз. Приложение и ваши настройки останутся на месте.",
        homebrewOfficialIntroCopyButton: "Копировать команду",
        updateShowcaseTitle: "Что нового в 3.1.4",
        updateShowcaseMessage: "Быстро взгляните на главные улучшения этого обновления.",
        updateShowcaseUnavailable: "Сейчас не удалось загрузить видео. Вы всё равно можете продолжить.",
        updateShowcaseRestart: "Начать заново",
        showMenuBarIcon: "Показывать значок в строке меню",
        showMenuBarIconCaption: "Если значок Vorssaint исчезнет (macOS может скрывать значки строки меню, когда в ней не хватает места, что часто бывает на Mac с вырезом), откройте Vorssaint снова из папки «Программы» или через Spotlight: это пересоздаст значок и, если он всё ещё скрыт, откроет это окно.",
        menuBarIconStillHiddenTitle: "Значок всё ещё скрыт",
        menuBarIconStillHiddenBody: "Значок был создан заново, но macOS не выделила ему видимого места. Скорее всего, в строке меню не хватает места: уберите несколько значков (или закройте приложения с длинными меню) и попробуйте снова.",
        menuBarIconManagerHintFormat: "%@ запущен и, возможно, держит значок в своей скрытой секции. Поищите Vorssaint там или настройте %@ всегда показывать Vorssaint.",
        shortcutRecording: "Нажмите новое сочетание клавиш",
        shortcutReset: "Сбросить",
        shortcutNone: "Нет",
        shortcutClear: "Убрать сочетание клавиш",
        shortcutInvalid: "Используйте хотя бы Control, Option или Command вместе с клавишей.",
        shortcutPressKeys: "Нажмите",
        shortcutEscapeHint: "Esc отменяет.",
        shortcutDeleteHint: "Delete убирает.",
        shortcutNotCaptured: "Ничего не записано. Это сочетание уже занято macOS или другим приложением. Попробуйте другое.",
        shortcutConflictFormat: "Это сочетание уже используется %@.",
        shortcutUnavailable: "macOS отклонила это сочетание клавиш. Выберите другое.",
        shelfShortcutToggle: "Горячая клавиша полки",
        switcherUsageHintFormat: "Удерживайте %@ для навигации; отпустите, чтобы активировать окно. Shift или ← возвращают назад; W закрывает окно; Q завершает приложение; Esc отменяет.",
        musicBlockSection: "Медиаклавиши",
        musicBlockTitle: "Не давать Музыке открываться самой",
        musicBlockCaption: "Приложение Музыка больше не открывается при нажатии медиаклавиш. Его по-прежнему можно открыть самому.",
        musicBlockReplacementLabel: "Открывать вместо",
        musicBlockReplacementNone: "Нет",
        musicBlockChooseApp: "Выбрать приложение…",
        cleanerName: "Очистка",
        cleanerIntroTitle: "Очистите Mac от мусора",
        cleanerIntroCaption: "Ищет остатки удалённых приложений, кэши, журналы и Корзину. Всё проверяется заранее, а удалённое попадает в Корзину.",
        cleanerScan: "Проверить",
        cleanerScanning: "Проверка…",
        cleanerCleaning: "Очистка…",
        cleanerCatLeftovers: "Остатки удалённых приложений",
        cleanerCatLoginItems: "Осиротевшие объекты входа",
        cleanerCatCaches: "Кэши",
        cleanerCatLogs: "Журналы",
        cleanerCatDeveloper: "Мусор разработчика",
        cleanerCatTrash: "Корзина",
        cleanerLeftoversNote: "Найдены анализом и не отмечены. Проверьте путь, прежде чем отмечать.",
        cleanerLoginItemsNote: "Запись в Объектах входа исчезает после перезагрузки Mac.",
        cleanerTrashNote: "Очистка Корзины необратима.",
        cleanerCatDeviceBackups: "Резервные копии iPhone",
        cleanerDeviceBackupsCaption: "Старые копии iPhone и iPad занимают большую часть хранилища, которое macOS называет «Другое». Удаляйте только ненужные; новая копия создаётся при следующем подключении.",
        cleanerNothingFound: "Нечего очищать. Ваш Mac в порядке.",
        cleanerClean: "Очистить",
        cleanerDoneNote: "Объекты перемещены в Корзину, откуда их можно восстановить.",
        cleanerAgain: "Проверить снова",
        cleanerRevealInFinder: "Показать в Finder",
        cleanerPanelCaption: "Остатки приложений, кэши и журналы",
        cleanerSafeSection: "Безопасная очистка",
        cleanerOptionalSection: "По желанию, сначала проверьте",
        cleanerCatOtherCaches: "Прочие кэши",
        cleanerCachesCaption: "Временные файлы, которые приложения создают заново сами.",
        cleanerLogsCaption: "Старые журналы диагностики.",
        cleanerDeveloperCaption: "Остатки сборок и симуляторов Xcode.",
        cleanerLoginItemsCaption: "Объекты входа приложений, которых больше нет.",
        cleanerLeftoversCaption: "Файлы, оставшиеся от удалённых приложений.",
        cleanerOtherCachesCaption: "Удалять безопасно, ничего не сломается. Приложения могут открыться медленнее один раз, а загруженное, например офлайн-музыка, скачается заново.",
        cleanerCleanSizeFormat: "Очистить %@",
        cleanerScheduleTitle: "Автоматическая очистка",
        cleanerScheduleOff: "Выключена",
        cleanerScheduleDaily: "Ежедневно",
        cleanerScheduleWeekly: "Еженедельно",
        cleanerScheduleCaption: "В выбранное время сама очищает только безопасную часть и отправляет всё в Корзину.",
        cleanerScheduleLastFormat: "Последняя автоматическая очистка освободила %@.",
        cleanerAutoNotificationFormat: "%@ освобождено и отправлено в Корзину.",
        cleanerScheduleNextFormat: "Следующая очистка %@.",
        cleanerScheduleRanFormat: "Последняя автоматическая очистка %@.",
        cleanerScheduleNotifyToggle: "Уведомлять по завершении",
        cleanerNotifDenied: "Уведомления Vorssaint отключены в системе.",
        cleanerNotifOpenSettings: "Открыть настройки уведомлений…",
        launchAtLoginNeedsApplications: "Приложение запущено из места, из которого нельзя открываться при входе. Перетащите Vorssaint в папку «Программы», откройте его оттуда и включите параметр снова.",
        launchAtLoginNeedsApproval: "Объект входа зарегистрирован, но в Системных настройках он выключен. Откройте «Системные настройки › Основные › Объекты входа и расширения» и включите Vorssaint в разделе «Открывать при входе».",
        ocrRemoveLineBreaksToggle: "Убирать переносы строк",
        ocrRemoveLineBreaksCaption: "Удаляет переносы строк, чтобы скопированный текст вставлялся одним абзацем.",
        ocrQRToggle: "Читать QR-коды",
        ocrQRCaption: "Если в области есть QR-код, его содержимое можно скопировать или открыть.",
        ocrQRCopied: "QR-код скопирован",
        qrResultTitle: "QR-код",
        qrResultCopy: "Копировать",
        qrResultOpen: "Открыть ссылку",
        highlightsTitle: "Новое в этом обновлении",
        highlightsTitleClipboardRedesign: "Обновлённый буфер обмена",
        highlightsTitleWindowLayout: "Размещение окон",
        highlightsTitleQuitProtection: "Защита от ⌘Q и ⌘W",
        highlightsTitleRecorderBlur: "Размытие в записи экрана",
        highlightsCaptionDockPreview: "Dock Preview теперь работает при включённом увеличении Dock",
        highlightsCaptionScreenshot: "Инструмент снимков экрана получил пиксельную лупу и чтение QR-кодов",
        highlightsCaptionSnippetLibrary: "Меню сниппетов с поиском печатает любой сниппет прямо у курсора",
        highlightsCaptionCapturePalette: "Одно сочетание клавиш теперь открывает плавающую палитру для снимков, записей, текста на экране и цветов с удобным доступом к настройкам.",
        highlightsCaptionClipboardRedesign: "История теперь открывается как компактная палитра с аккуратными строками и предпросмотром по запросу для чтения или редактирования элемента.",
        highlightsCaptionWindowLayout: "Размещайте окна с помощью кругового меню по сочетанию клавиш и указателю или перетягивайте к краям экрана с настраиваемыми отступами.",
        highlightsCaptionQuitProtection: "Предотвращайте случайное закрытие программ и окон удержанием клавиши, двойным нажатием или дополнительным модификатором для каждого приложения.",
        highlightsCaptionRecorderBlur: "Скрывайте конфиденциальные данные, пароли и личную информацию на любом отрезке записанного видео перед экспортом.",
        highlightsConfigure: "Настроить",
        highlightsTry: "Попробовать",
        highlightsSeeAll: "Все изменения",
        switcherCurrentSpaceOnly: "Показывать только текущий рабочий стол",
        switcherCurrentSpaceOnlyCaption: "В переключателе видны только окна рабочего стола, на котором вы находитесь. Выбор окна никогда не переносит вас на другой рабочий стол.",
        shelfFileMissing: "Файл больше не существует",
        previewSizeSmall: "Маленький",
        mixerSoundEffectsOutputTitle: "Системные звуки",
        mixerSoundEffectsOutputTooltip: "Выбрать устройство для оповещений и звуковых эффектов",
        monitorOpenActivityMonitor: "Открыть Мониторинг системы",
        dockClickHide: "Скрывать приложение кликом по Dock",
        dockClickHideCaption: "Активное приложение скрывается при клике по его значку в Dock. Нажмите ещё раз, чтобы вернуть его.",
        monitorMemoryMetricLabel: "Как измерять память",
        memoryMetricUsed: "Занято памяти",
        memoryMetricApp: "Память приложений",
        keepAwakeRightClickToggle: "Щёлкните правой кнопкой значок в строке меню, чтобы включить или выключить «Не давать уснуть»",
        keepAwakeRightClickToggleCaption: "Заменяет контекстное меню правой кнопки мыши.",
        urlCleanerRulesTitle: "Правила очистки",
        urlCleanerRulesCaption: "Сайт добавляет эти параметры в собственные ссылки для обмена, чтобы отследить, откуда пришла ссылка. С флажком название удаляется при очистке ссылки, без флажка остаётся. Добавленные вами названия можно удалить.",
        urlCleanerRulesCoverageCaption: "Список охватывает разные способы поделиться на одном сайте (страницу, приложение, эфир), поэтому он длинный; в настоящей ссылке обычно всего два-четыре из них.",
        urlCleanerRulesAllSites: "Все сайты",
        urlCleanerRulesCountSingular: "1 параметр",
        urlCleanerRulesCountPluralFormat: "Параметров: %d",
        urlCleanerRulesAddSite: "Добавить сайт",
        urlCleanerRulesParameterPlaceholder: "Название параметра",
        urlCleanerRulesMatchCaption: "Впишите название слева от = , например utm_source. Совпавшее название убирает из ссылки только этот параметр, остальное остаётся как было.",
        urlCleanerRulesAddButton: "Добавить",
        urlCleanerRulesRemoveButton: "Удалить название",
        urlCleanerRulesRemoveSiteButton: "Отключить все правила этого сайта",
        urlCleanerRemovedFormat: "Удалено: %@",
        switcherSearchPin: "Закрепить поиск по S",
        switcherSearchPinCaption: "S запускает поиск и закрепляет переключатель открытым. Печать больше не даёт специальные символы, если сочетание использует ⌥, а поиск, начинающийся с Q или W, больше не закрывает окно и не завершает приложение по ошибке.",
        invertVerticalScroll: "Инвертировать вертикальную прокрутку",
        invertHorizontalScroll: "Инвертировать горизонтальную прокрутку",
        switcherShowShortcutHints: "Показывать подсказки сочетаний клавиш",
        switcherShowShortcutHintsCaption: "Показывает сочетания клавиш для приложений и окон под значками.",
        uninstallerHomebrewPackageFormat: "%@ также будет удалён из Homebrew.",
        shelfEdgeToggle: "Открывать у края экрана",
        shelfEdgeCaption: "Перетащите файл к краю экрана, чтобы полка выглянула. Отпустите его там, или потяните обратно, и полка уберётся.",
        focusFollowsMouseName: "Фокус следует за мышью",
        focusFollowsMouseCaption: "Фокусирует и поднимает окно под указателем после короткой паузы.",
        focusFollowsMouseDelay: "Задержка наведения",
        switcherMinimizedPlacementLabel: "Свёрнутые окна",
        switcherMinimizedPlacementNormal: "Обычный порядок",
        switcherMinimizedPlacementEnd: "В конец списка",
        switcherMinimizedPlacementHidden: "Скрывать",
        switcherShowFullscreenWindows: "Показывать полноэкранные окна",
        switcherScreenPlacementLabel: "Показывать на",
        switcherScreenPlacementPointer: "Экран с указателем",
        switcherScreenPlacementMenuBar: "Экран со строкой меню",
        switcherScreenPlacementActiveWindow: "Экран с активным окном",
        switcherScreenPlacementCaption: "На каком экране открывается переключатель, когда подключено несколько экранов.",
        smoothScrollResponseLabel: "Отклик",
        mouseAccelerationName: "Отключить ускорение мыши",
        mouseAccelerationCaption: "Отключает ускорение указателя для подключённых мышей. Прежняя настройка вернётся после выключения функции или выхода из Vorssaint.",
        shelfClearOnClose: "Очищать при закрытии",
        shelfClearOnCloseCaption: "Очищает полку только при нажатии кнопки закрытия. Автоматическое скрытие и сворачивание сохраняют элементы."
    )
}
