// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// 繁體中文（香港）— translated and hand-checked, not machine output.
extension Strings {
    static let zhHK = Strings(
        statusIdleTooltip: "Vorssaint：正常睡眠",
        statusActiveUntil: "Vorssaint：保持喚醒至",
        statusActiveIndefinite: "Vorssaint：持續保持喚醒",
        menuEnableAwake: "開啟保持喚醒",
        menuDisableAwake: "關閉保持喚醒",
        menuActivateFor: "設定時長…",
        menuSettings: "設定…",
        menuAbout: "關於 Vorssaint",
        menuQuit: "結束 Vorssaint",
        menuHide: "隱藏 Vorssaint",
        menuHideOthers: "隱藏其他",
        menuShowAll: "全部顯示",
        menuEdit: "編輯",
        menuUndo: "復原",
        menuRedo: "重做",
        actionClear: "清除",
        actionRemove: "移除",
        actionBack: "返回",
        actionSearch: "搜尋",
        actionMute: "靜音",
        actionUnmute: "取消靜音",
        actionPlay: "播放",
        actionPause: "暫停",
        menuCut: "剪下",
        menuCopy: "複製",
        menuPaste: "貼上",
        menuSelectAll: "全選",
        menuWindow: "視窗",
        menuMinimize: "最小化",
        menuZoom: "縮放",
        menuClose: "關閉",

        minutes15: "15 分鐘",
        minutes30: "30 分鐘",
        hour1: "1 小時",
        hours2: "2 小時",
        hours4: "4 小時",
        hours8: "8 小時",
        indefinitely: "無限期",
        indefinite: "無限期",

        panelSettings: "設定",
        panelQuit: "結束",
        panelHotkeyHint: "快捷鍵切換",

        keepAwakeTitle: "保持喚醒",
        keepAwakeEndsIn: "剩餘時間",
        keepAwakeUntilDisabled: "保持開啟，直至你手動關閉",
        keepAwakeNormalRules: "Mac 會依照正常電源規則",
        keepAwakeOptions: "選項",
        keepAwakeMouseJiggle: "輕微移動指標",
        keepAwakeMouseJiggleCaption: "時段內按所選間隔輕微移動指標。",
        keepAwakeMouseJiggleInterval: "間隔",
        keepAwakeActiveIconLabel: "使用中的圖示",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "咖啡",
        keepAwakeActiveIconEye: "眼睛",
        keepAwakeActiveIconMoon: "月亮",
        keepAwakeActiveIconLight: "燈泡",
        keepAwakeIconTintLabel: "啟用時圖示顏色",
        keepAwakeIconTintOrange: "橙色",
        keepAwakeIconTintGreen: "綠色",
        keepAwakeIconTintBlue: "藍色",
        keepAwakeIconTintPurple: "紫色",
        keepAwakeIconTintPink: "粉紅色",
        keepAwakeIconTintNone: "沒有顏色",
        durationLabel: "時間長度",
        clamshellTitle: "合上機蓋後繼續運作",
        clamshellOnCaption: "已完全停用睡眠，請留意電池電量",
        clamshellNeedsSession: "每當「保持喚醒」啟用時生效",
        clamshellReady: "準備就緒，切換時無需輸入密碼",
        clamshellNeedsPassword: "只需要輸入一次管理員密碼",

        systemSection: "系統",
        temperatures: "溫度",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "電池",
        usageSection: "硬件使用量",
        memorySection: "記憶體",
        memoryPressure: "壓力",
        memorySwapUsed: "已用交換空間",
        memoryCompressed: "已壓縮",
        memoryCachedFiles: "已快取的檔案",
        pressureNormal: "正常",
        pressureWarning: "注意",
        pressureCritical: "嚴重",
        monitorUnavailable: "此 Mac 上沒有可用感應器",
        energyAppsTitle: "耗電量高",
        energyAppsIdle: "沒有耗電量高項目",

        notifySessionEndedTitle: "時段已結束",
        notifySessionEndedBody: "時間到。Mac 會恢復正常睡眠。",
        notifyBatteryTitle: "Vorssaint 已關閉",
        notifyBatteryBody: "電量過低。已恢復正常睡眠以保護電池。",
        adminPromptClamshellOn: "Vorssaint 需要你輸入密碼，才能在合上機蓋後繼續運作。",
        adminPromptClamshellOff: "Vorssaint 需要你輸入密碼，才能恢復 Mac 的正常睡眠。",
        adminPromptRecover: "Vorssaint 在 Mac 睡眠被停用時結束了。請輸入密碼以恢復正常睡眠。",
        adminPromptUpdate: "Vorssaint 需要您的密碼來安裝更新。",
        adminPromptSudoersInstall: "Vorssaint 會建立一條受限規則（僅限 pmset disablesleep），用來切換合上機蓋模式時免於輸入密碼。這是唯一一次需要輸入密碼。",
        adminPromptSudoersRemove: "Vorssaint 會移除免密碼的合上機蓋規則。",

        settingsTitle: "Vorssaint 設定",
        tabGeneral: "通用",
        tabEnergy: "電源",
        tabMouse: "滑鼠與觸控板",
        tabSwitcher: "切換器",
        tabAdvanced: "進階",
        tabAbout: "關於",
        tabReleaseNotes: "新功能",
        releaseNotesOnUpdateToggle: "更新後顯示新功能",
        minimalWindowPreviews: "簡潔預覽",
        minimalWindowPreviewsCaption: "隱藏 Dock 和 App 切換器預覽中的標題、按鈕及裝飾，保留選取標記。",
        previewSizeLabel: "預覽大小",
        previewSizeNormal: "正常",
        previewSizeLarge: "大",
        previewSizeXLarge: "特大",
        settingsGroupFeatures: "功能",
        advancedResetSection: "權限",
        advancedResetDescription: "移除你允許 Vorssaint 使用的所有權限（輔助使用、螢幕錄製、完整磁碟存取權限等）、登入項目以及合上機蓋規則。適合重新開始或解除安裝前使用。App 仍會保留安裝狀態。",
        advancedClearButton: "清除所有權限",
        advancedCleared: "權限已清除。",
        advancedClearConfirmTitle: "清除所有權限？",
        advancedClearConfirmBody: "需要權限的功能會停止運作，直到你重新允許。你的設定會保留。",
        advancedUninstallSection: "解除安裝",
        advancedUninstallDescription: "執行以上全部操作，然後移除偏好設定並將 Vorssaint 移至垃圾桶，不留下任何痕跡。完成後 App 會結束。你可以隨時重新安裝。",
        advancedUninstallButton: "完全解除安裝 Vorssaint",
        advancedUninstallConfirmTitle: "解除安裝 Vorssaint？",
        advancedUninstallConfirmBody: "Vorssaint 會清除其權限、移除偏好設定並移至垃圾桶，然後結束。此操作無法從 App 內復原，但在你清空垃圾桶之前，它仍會留在垃圾桶內。",
        advancedUninstallFailedTitle: "已停止解除安裝",
        advancedUninstallFailedBody: "Vorssaint 無法還原它變更過的系統設定：睡眠、風扇轉速或滑鼠加速。沒有移除任何項目。請再試一次，並在出現密碼要求時允許。",

        launchAtLogin: "登入時啟動",
        languageLabel: "語言",
        menuBarSection: "選單列",
        showCountdown: "在圖示旁顯示剩餘時間",
        globalHotkeySection: "全域快捷鍵",
        hotkeyToggle: "啟用「保持喚醒」快捷鍵",
        hotkeyCaption: "在任何 App 中都有效，無需額外權限。",

        sessionSection: "時段",
        defaultDurationLabel: "預設時間長度",
        keepAwakeAutoStart: "開啟 Vorssaint 時保持喚醒",
        keepAwakeAutoStartCaption: "使用預設時間啟動工作階段。",
        batteryProtectionSection: "電池保護",
        batteryDisableBelow: "電池電量低於以下數值時關閉",
        batteryNever: "從不",
        batteryProtectionCaption: "避免忘記關閉的時段耗盡 MacBook 電池電量。",
        clamshellSection: "合上機蓋",
        configuring: "設定中…",
        sudoersFailed: "無法啟用合上機蓋模式。請重試。",
        clamshellExplanation: "「合上機蓋後繼續運作」會在「保持喚醒」啟用期間完全停用睡眠，並在時段結束或 App 結束時自動恢復。建議在連接電源時使用。",

        scrollSection: "捲動",
        invertMouseScroll: "反轉滑鼠捲動",
        invertMouseScrollCaption: "反轉滑鼠滾輪的方向。",
        scrollTrackpadNote: "觸控板不受影響：仍保持 macOS 的自然捲動。",
        scrollActiveNow: "正在反轉滑鼠捲動",
        mouseNavigationActiveNow: "側鍵目前已啟用",
        smoothScrollName: "平滑捲動",
        smoothScrollCaption: "把滑鼠滾輪的每一格變成短暫順暢的滑動。觸控板不受影響。",
        smoothScrollStepLabel: "捲動速度",
        mouseNavigationSection: "導覽",
        mouseNavigationEnable: "使用側鍵返回與前進",
        mouseNavigationCaption: "將滑鼠的返回與前進按鈕轉成 Finder、瀏覽器和相容 App 的導覽指令。",
        middleClickSection: "中鍵點按",
        middleClickEnable: "三指按下作為中鍵點按",
        middleClickEnableCaption: "用三隻手指按下觸控板，效果等同於滑鼠滾輪點按：在新分頁開啟連結、關閉分頁，以及中鍵能做的一切。",
        middleClickDragConflict: "macOS 的三指拖移已開啟，與此手勢相同。請在系統設定的輔助使用、指標控制、觸控板選項中將其關閉，中鍵點按即可使用。",
        middleClickTapPicker: "輕點也可點按",
        middleClickTapOff: "關閉",
        middleClickTapThreeFingers: "3 隻手指",
        middleClickTapFourFingers: "4 隻手指",
        middleClickTapCaption: "用該數量的手指輕點（無需按壓）也會觸發中鍵點按。滑動不會觸發。如果 macOS 的三指輕點被指定為「查詢」，請將其關閉以免兩者同時觸發。",
        quickToolsTab: "快速面板",
        quickToolShortcutToggle: "全域快速鍵",
        ocrName: "拷貝螢幕文字",
        ocrCaption: "選擇螢幕上的一塊區域，識別出的文字會被拷貝，隨時可以貼上。",
        ocrCopied: "文字已拷貝",
        ocrNoText: "未找到文字",
        colorPickerName: "顏色吸管",
        colorPickerCaption: "取得螢幕上任意像素的顏色，並以你喜歡的格式拷貝。",
        colorPickerFormatLabel: "拷貝格式",
        colorPickerBareHexToggle: "拷貝時不帶 # 前綴",
        colorPickerPickNow: "擷取顏色",
        micMuteName: "靜音麥克風",
        micUnmuteName: "取消靜音麥克風",
        micMuteCaption: "透過點按或快速鍵切斷 Mac 的麥克風，對所有 App 生效。",
        micMutedHUD: "麥克風已靜音",
        micUnmutedHUD: "麥克風已恢復",
        micMuteMenuBarToggle: "靜音時在選單列顯示",
        micMuteMenuBarCaption: "選單列中的 App 圖示旁會出現一個紅色的劃線麥克風。",
        pastePlainName: "貼上為純文字",
        pastePlainCaption: "貼上拷貝的內容時去除顏色、字體和格式。原始內容仍保留在剪貼簿中。",
        launcherName: "快速面板",
        launcherCaption: "一個匯集你最愛工具的懸浮面板，隨時隨地用快速鍵喚出。",
        launcherOpenNow: "打開快速面板",
        launcherEditHint: "使用調整按鈕來選擇、隱藏和拖動工具。",
        launcherEmptyState: "所有工具都已隱藏。使用調整按鈕將它們加回來。",
        launcherAddSection: "重新加入",
        launcherKeysHint: "方向鍵導航，Enter 打開，1 到 9 直接打開",

        switcherSection: "App 切換器",
        switcherEnable: "使用 Vorssaint 切換器",
        switcherEnableCaption: "在 App 和視窗之間切換，包括已最小化的視窗和同一 App 的多個視窗。",
        switcherUsageHint: "按住快捷鍵瀏覽；放開即可切換至視窗。Shift 或 ← 返回；W 關閉視窗；Q 結束 App；Esc 取消。",
        switcherNoWindows: "沒有開啟的視窗",
        switcherIconRowMode: "用大圖示顯示 %@",
        switcherIconRowModeCaption: "每個 App 顯示一個圖示，並在上方顯示該 App 的視窗預覽。",
        switcherSimpleMode: "簡潔 App 切換器",
        switcherSimpleModeCaption: "顯示 App 圖示和視窗標題，不顯示預覽，也不會由切換器擷取螢幕。",
        switcherShortcutHintApps: "App",
        switcherShortcutHintWindows: "視窗",
        switcherWindowShortcutCaption: "開啟最前應用程式的視窗切換器。應用程式切換器開啟時，在所選應用程式的視窗之間跳轉。",
        switcherTakeOverSystemShortcuts: "接管 macOS 的 ⌘Tab 和 ⌘`",
        switcherTakeOverSystemShortcutsCaption: "只在 Vorssaint 切換器運行時停用對應的 macOS App 及視窗快速鍵，並保留所有運行中 App 的入口。",
        switcherAppearanceDelay: "顯示延遲",
        switcherAppearanceDelayCaption: "按住快速鍵多久後顯示切換器。",
        switcherMergeTabs: "每個 App 僅顯示一項",
        switcherMergeTabsCaption: "將 App 的所有視窗合併為切換器中的一項，而不是每個視窗一項。",
        switcherWindowlessApps: "沒有開啟視窗的 App",
        switcherWindowlessAppsCaption: "選擇哪些已開啟但完全沒有視窗的 App 會顯示在切換器中。",
        switcherWindowlessAppsOff: "不顯示",
        switcherWindowlessAppsFinder: "僅 Finder",
        switcherWindowlessAppsAll: "所有 App",
        switcherNoOpenWindow: "沒有開啟視窗",
        switcherOtherDesktop: "其他桌面",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "在 Dock 中預覽視窗",
        dockPreviewEnableCaption: "將指標停在 Dock 中已開啟的 App 上查看視窗，然後點按要開啟的視窗。",
        dockPreviewBackgroundOpacity: "面板背景",
        dockPreviewBackgroundOpacityCaption: "調低後可以看到更多面板後面的內容。",
        dockPreviewOpenDelay: "開啟延遲",
        dockPreviewOpenDelayCaption: "指標停在圖示上多久之後才打開面板。",
        dockPreviewQuitAppOnClose: "使用 × 按鈕結束 App",
        dockPreviewQuitAppOnCloseCaption: "在 Dock Preview 中，× 會結束整個 App，而不只是關閉該視窗。",
        dockClickMinimize: "點按 Dock 圖示最小化",
        dockClickMinimizeCaption: "點按最前面 App 的 Dock 圖示可將其視窗最小化。再點按一次即可還原。",
        dockClickCycleWindows: "點按 Dock 圖示切換視窗",
        dockClickCycleWindowsCaption: "點按最前面 App 的 Dock 圖示可在其視窗之間輪換，類似 ⌘`。",
        dockPreviewActiveNow: "已在 Dock 中啟用",
        dockPreviewDockUnavailable: "無法讀取 Dock 項目。",
        dockPreviewAutohideBeta: "測試版。你可能會遇到一些問題。",
        dockPreviewOpenWindow: "開啟視窗",
        dockPreviewCloseWindow: "關閉視窗",
        dockPreviewMinimizeWindow: "最小化視窗",
        dockPreviewRestoreWindow: "還原視窗",
        dockPreviewPinPanel: "釘選預覽",
        dockPreviewUnpinPanel: "取消釘選預覽",
        dockPreviewPinned: "已釘選",
        dockPreviewClosePanel: "關閉預覽",
        dockPreviewPreviousWindow: "上一個視窗",
        dockPreviewNextWindow: "下一個視窗",

        cutPasteName: "剪下和貼上",
        cutPasteEnable: "在 Finder 中剪下和貼上檔案",
        cutPasteEnableCaption: "在 Finder 中用 ⌘X 剪下、用 ⌘V 移動檔案和資料夾。",
        cutPasteShowHUD: "顯示浮動面板",
        cutPasteShowHUDCaption: "Finder 處於啟動狀態時，顯示包含已剪下檔案的浮動提示。",
        cutPasteHowTitle: "使用方法",
        cutPasteStep1: "在 Finder 中選取項目，按 ⌘X 剪下。",
        cutPasteStep2: "開啟目的地資料夾，按 ⌘V 移到該處。",
        cutPasteTextNote: "在文字欄位中（例如重新命名時），⌘X 和 ⌘V 仍照常工作。",
        cutPasteActiveNow: "已可在 Finder 中剪下",
        cutPasteAutomationNote: "首次使用時，macOS 會要求控制 Finder 的權限。",
        cutReadyTitle: "已剪下",
        cutReadyHint: "在目的地資料夾中貼上以移動",
        cutCancel: "取消剪下",
        cutDoneTitle: "已移動！",
        cutMovedSingular: "已移動 1 個項目",
        cutMovedPluralFormat: "已移動 %d 個項目",
        cutSomeFailed: "部分項目無法移動",
        cutMovingTitle: "正在移動…",
        cutMovingCountFormat: "%d / %d",

        autoQuitName: "關閉時結束",
        autoQuitEnable: "關閉 App 最後一個視窗時結束該 App",
        autoQuitEnableCaption: "關閉 App 的最後一個視窗時，亦會結束該 App。",
        autoQuitActiveNow: "目前已啟用",
        autoQuitHowTitle: "運作方式",
        autoQuitStep1: "關閉某個 App 的最後一個視窗（⌘W 或紅色按鈕）。",
        autoQuitStep2: "該 App 會自行結束。「要儲存更改嗎？」對話框仍會出現。",
        autoQuitPredictableNote: "一般來說，沒有視窗的 App 不會自行結束。",
        autoQuitExceptionsTitle: "例外",
        autoQuitExceptionsCaption: "此清單中的 App 即使沒有視窗也會保持開啟。",
        autoQuitExceptionsEmpty: "沒有例外項目",
        autoQuitAddApp: "加入 App…",

        uninstallerName: "解除安裝工具",
        uninstallerEnableCaption: "移除 App 時，一併清除它遺留的快取、偏好設定、記錄及殘留檔案。",
        uninstallerStep1: "將 App 拖到設定中，或從清單中選取一個。",
        uninstallerStep2: "查看找到的檔案以及所佔用的空間。",
        uninstallerStep3: "把想移除的內容移至垃圾桶。不會永久刪除任何內容。",
        uninstallerMenuItem: "解除安裝 App…",
        uninstallerDropTitle: "將 App 拖到這裡",
        uninstallerDropSubtitle: "或選取一個來掃描",
        uninstallerChoose: "選取 App…",
        uninstallerPickerTitle: "選取 App",
        uninstallerPickerSearch: "搜尋 App",
        uninstallerPickerEmpty: "找不到 App",
        uninstallerEmptyNote: "未經你確認，不會移除任何內容。",
        uninstallerFDANote: "允許完整磁碟存取權限可掃描得更徹底。",
        uninstallerFDAGrant: "允許存取…",
        uninstallerFDAHint: "在清單中開啟 Vorssaint。如果清單中沒有，按一下 + 並從「應用程式」中選取 Vorssaint。權限須在你重新開啟 App 後才會生效。",
        uninstallerFDARelaunch: "立即重新開啟",
        uninstallerScanning: "正在掃描檔案…",
        uninstallerRemoving: "正在移至垃圾桶…",
        uninstallerFoundTitle: "已找到",
        uninstallerSelectedFormat: "已選取 %d 項，共 %d 項",
        uninstallerRemove: "移至垃圾桶",
        uninstallerCancel: "取消",
        uninstallerDoneTitle: "完成！",
        uninstallerFreedFormat: "已騰出 %@",
        uninstallerSomeFailed: "部分項目無法移至垃圾桶。",
        uninstallerFailedNeedsFDA: "沙盒應用程式的資料只有在具備完整磁碟存取權限時才能移動，管理員密碼無法取代這項權限。",
        uninstallerFailedMoreFormat: "另有 %d 項",
        uninstallerAnother: "解除安裝另一個",
        uninstallerCatApp: "應用程式",
        uninstallerCatSupport: "支援檔案",
        uninstallerCatCaches: "快取",
        uninstallerCatPreferences: "偏好設定",
        uninstallerCatContainers: "容器",
        uninstallerCatLogs: "記錄",
        uninstallerCatState: "已儲存狀態",
        uninstallerCatOther: "其他",

        urlCleanerName: "清理 URL",
        urlCleanerEnable: "複製時自動清理 URL",
        urlCleanerEnableCaption: "連結一進剪貼簿就移除當中的追蹤參數。",
        urlCleanerActiveNow: "目前已啟用",
        urlCleanerManualTitle: "立即清理",
        urlCleanerInputPlaceholder: "貼上 URL",
        urlCleanerOutputPlaceholder: "清理後的 URL 會顯示在這裡",
        urlCleanerCleanButton: "清理",
        urlCleanerPasteButton: "貼上",
        urlCleanerCopyButton: "複製",
        urlCleanerClearButton: "清空輸入欄",
        urlCleanerNoURL: "請貼上有效的 URL。",
        urlCleanerNoChange: "沒有可清理的內容。",
        urlCleanerCleaned: "URL 已清理。",
        urlCleanerCopied: "已複製。",
        urlCleanerLocalNote: "本機處理，不會連接網絡。",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "搜尋、安裝和移除 formula 與 cask。",
        homebrewMissingTitle: "找不到 Homebrew",
        homebrewMissingBody: "Vorssaint 可以在終端機中開啟官方 Homebrew 安裝器。終端機會顯示步驟，並在需要時要求你輸入密碼。",
        homebrewInstallHomebrew: "安裝 Homebrew",
        homebrewInstallHomebrewCaption: "終端機完成後，請返回這裡並按一下「重新整理」。",
        homebrewInstallHomebrewOpened: "安裝器已在終端機中開啟。",
        homebrewShellSetupTitle: "完成終端機設定",
        homebrewShellSetupBody: "Homebrew 已安裝，但終端機可能仍找不到 brew 指令。Vorssaint 可以在終端機中開啟設定指令。",
        homebrewShellSetupButton: "設定終端機",
        homebrewShellSetupOpened: "指令已在終端機中開啟。完成後請返回這裡並按一下「重新整理」。",
        homebrewRefresh: "重新整理",
        homebrewCheckPackages: "檢查套件",
        homebrewTrustTitle: "Tap 尚未受信任",
        homebrewTrustCaption: "Homebrew 現在會在使用第三方 tap 前徵求你的確認。信任 %@ 即可繼續。",
        homebrewTrustButton: "信任並繼續",
        homebrewSearchPlaceholder: "搜尋套件",
        homebrewKeyboardHint: "空白鍵或 Return 會關閉 macOS 面板。請使用「搜尋」按鈕。",
        homebrewSearchButton: "搜尋",
        homebrewSearchResults: "結果",
        homebrewInstalled: "已安裝",
        homebrewAll: "全部",
        homebrewFormulas: "Formula",
        homebrewCasks: "Cask",
        homebrewNoPackages: "找不到套件",
        homebrewNoSelection: "選取已安裝的套件，或搜尋新的套件。",
        homebrewDetailsTitle: "套件詳情",
        homebrewInstall: "安裝",
        homebrewUninstall: "解除安裝",
        homebrewUpgrade: "更新",
        homebrewUpgradeAll: "全部更新",
        homebrewUpdateHomebrew: "更新 Homebrew",
        homebrewAllPackages: "套件",
        homebrewOpenTerminal: "開啟終端機",
        homebrewCancelOperation: "取消",
        homebrewClearLog: "清空記錄",
        homebrewLogTitle: "記錄",
        homebrewVersion: "版本",
        homebrewDescription: "類型",
        homebrewHomepage: "開啟網站",
        homebrewPopularity: "熱門程度",
        homebrewPopularityFormat: "%@ 次安裝，%@ 天",
        homebrewInstalledBadge: "已安裝",
        homebrewNotInstalledBadge: "未安裝",
        homebrewUpdates: "更新",
        homebrewUpdateAvailableBadge: "有可用更新",
        homebrewLatestVersion: "最新",
        homebrewConfirmInstallTitle: "使用 Homebrew 安裝？",
        homebrewConfirmInstallBodyFormat: "Homebrew 會下載並安裝 %@。亦可能安裝相依套件。",
        homebrewConfirmUninstallTitle: "使用 Homebrew 解除安裝？",
        homebrewConfirmUninstallBodyFormat: "Homebrew 會解除安裝 %@。設定檔可能仍會留在系統中。",
        homebrewConfirmUpgradeTitle: "使用 Homebrew 更新？",
        homebrewConfirmUpgradeBodyFormat: "Homebrew 會下載並套用 %@ 的最新版本。相依套件亦可能會更新。",
        homebrewConfirmUpgradeAllTitle: "使用 Homebrew 全部更新？",
        homebrewConfirmUpgradeAllBody: "Homebrew 會下載並套用所有可更新套件的最新版本。相依套件亦可能會更新。",
        homebrewConfirmUpdateHomebrewTitle: "更新 Homebrew？",
        homebrewConfirmUpdateHomebrewBody: "Homebrew 會取得最新資料，然後重新載入你的套件清單。",
        homebrewTerminalFallback: "此操作需要透過終端機要求管理員密碼。Vorssaint 不會取得密碼。",
        homebrewLoading: "正在載入…",
        homebrewSearchEmpty: "沒有結果",
        homebrewOperationInstallFormat: "正在安裝 %@",
        homebrewOperationUninstallFormat: "正在解除安裝 %@",
        homebrewOperationUpgradeFormat: "正在更新 %@",
        homebrewOperationUpgradeAll: "正在更新套件",
        homebrewOperationUpdateHomebrew: "正在更新 Homebrew",
        homebrewOperationInstalledFormat: "%@ 已安裝。",
        homebrewOperationUninstalledFormat: "%@ 已解除安裝。",
        homebrewOperationUpgradedFormat: "%@ 已更新。",
        homebrewOperationUpgradedAll: "套件已更新。",
        homebrewOperationUpdatedHomebrew: "Homebrew 已更新。",
        homebrewOperationFailedFormat: "無法完成 %@。",
        homebrewOperationCancelled: "操作已取消。",
        homebrewOperationPreparing: "正在準備…",
        homebrewOperationDownloading: "正在下載檔案…",
        homebrewOperationInstalling: "正在安裝檔案…",
        homebrewOperationUninstalling: "正在移除檔案…",
        homebrewOperationUpgrading: "正在更新檔案…",
        homebrewOperationFinalizing: "正在完成…",
        homebrewOperationRefreshing: "正在重新整理清單…",
        homebrewOperationTerminal: "請在終端機中繼續。",
        homebrewOperationElapsedFormat: "已用時間 %@",
        homebrewOperationShowDetails: "顯示詳情",
        homebrewOperationHideDetails: "隱藏詳情",
        homebrewOperationTechnicalLog: "技術詳情",
        homebrewOperationProgressUnknown: "Homebrew 尚未回報百分比。",

        mediaName: "媒體",
        mediaEnableCaption: "在本機壓縮影片、轉換和處理圖片、製作 GIF，並從圖片中擷取文字。",
        mediaLocalNote: "本機處理，不會連接網絡。",
        mediaToolVideo: "影片",
        mediaToolGIF: "GIF",
        mediaToolImage: "圖片",
        mediaToolText: "文字",
        mediaSelectFile: "選取檔案",
        mediaDropHint: "將檔案拖到這裡，或按一下選取。",
        mediaOutput: "輸出",
        mediaOutputAutomatic: "自動",
        mediaChooseOutput: "目的地",
        mediaStartVideo: "壓縮影片",
        mediaStartGIF: "製作 GIF",
        mediaStartImage: "處理圖片",
        mediaStartConvertPDF: "轉換為 PDF",
        mediaStartText: "擷取文字",
        mediaCancel: "取消",
        mediaStartTime: "開始",
        mediaEndTime: "結束",
        mediaQuality: "壓縮",
        mediaCompressionLow: "低",
        mediaCompressionMedium: "中",
        mediaCompressionHigh: "高",
        mediaMaxSize: "大小",
        mediaSizingResolution: "解像度",
        mediaSizingFileSize: "檔案大小",
        mediaTargetSize: "目標大小",
        mediaTargetSizeHint: "解像度會自動調整以不超過上限。",
        mediaErrorTargetTooSmall: "目標大小對此片段來說太小。請縮短片段或提高上限。",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "闊度",
        mediaFPS: "FPS",
        mediaKeepAudio: "保留音訊",
        mediaCodec: "編碼",
        mediaFormat: "格式",
        mediaStripMetadata: "移除中繼資料",
        mediaLoopGIF: "循環 GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "準確",
        mediaOCRFast: "快速",
        mediaLanguageCorrection: "語言修正",
        mediaTextOutputNote: "擷取的文字可以複製並儲存為 TXT。",
        mediaRunning: "處理中",
        mediaCompleted: "完成",
        mediaCancelled: "已取消。",
        mediaOpenInFinder: "顯示",
        mediaCopyText: "複製文字",
        mediaRunAgain: "再次執行",
        mediaEmptyText: "找不到文字。",
        mediaResultSavedFormat: "已儲存為 %@",
        mediaResultSizeFormat: "%@ 至 %@",
        mediaResultGrewCaption: "轉換後的檔案比原始檔更大。",
        mediaErrorNoFile: "請先選取檔案。",
        mediaErrorNoVideo: "此檔案沒有影片軌道。",
        mediaErrorSameOutput: "請選取不同於原檔案的目的地。",
        mediaErrorUnsupported: "macOS 不支援此格式。",

        shelfName: "暫存架",
        shelfEnable: "用來暫放拖曳檔案的區域",
        shelfEnableCaption: "一個浮動空間，用來收集檔案、圖片和文字，稍後再拖到任何 App 中。",
        shelfHowTitle: "使用方法",
        shelfStep1: "用快捷鍵開啟它，或在拖曳時搖動滑鼠開啟。",
        shelfStep2: "把檔案、圖片、連結或文字拖放到上面以暫存。",
        shelfStep3: "需要時再把項目拖到任何 App。",
        shelfShakeToggle: "拖曳時搖動滑鼠開啟",
        shelfShakeCaption: "按住項目時快速搖動指標，即可在游標附近叫出暫存架。",
        shelfDropZoneToggle: "將拖曳的檔案保留在選單列",
        shelfDropZoneCaption: "拖移檔案時，暫存架會出現在選單列圖示下方。放下的內容就保存在那裡，收進一個點按即可收合或打開的按鈕，暫存架清空後按鈕便會消失。",
        shelfDropZoneLabel: "放到這裡",
        shelfCollapse: "收合",
        shelfBehaviorTitle: "使用後",
        shelfCloseAfterDrop: "拖放到其他 App 後關閉",
        shelfCloseAfterDropCaption: "目標接收項目後關閉暫存架。面板中的圖釘可讓它保持開啟。",
        shelfRemoveAfterDrop: "拖放後移除項目",
        shelfRemoveAfterDropCaption: "其他 App 接收的項目會離開暫存架。關閉此選項可保留副本。",
        shelfExclusionsTitle: "自動例外",
        shelfExclusionsEmpty: "尚未加入 App。",
        shelfExclusionsCaption: "從這些 App 開始拖移時，搖動手勢和選單列區域不會開啟。快捷鍵和立即開啟仍可使用。",
        shelfPin: "保持開啟",
        shelfUnpin: "允許使用後關閉",
        extraBrightnessName: "超亮度",
        extraBrightnessCaption: "利用顯示器的HDR餘裕突破最高亮度。會更耗電，Mac可能會發熱。",
        extraBrightnessLevelLabel: "強度",
        extraBrightnessUnsupported: "僅適用於XDR顯示器，例如14吋和16吋MacBook Pro。",
        shelfHotkeyLabel: "快捷鍵",
        shelfOpenNow: "立即開啟",
        shelfNoPermission: "無需任何權限。",
        shelfMenuItem: "開啟暫存架",
        shelfTitle: "暫存架",
        shelfEmpty: "將項目拖到這裡",
        shelfClearAll: "全部清除",
        shelfRemoveSelected: "移除所選",
        shelfSelectedFormat: "已選取 %d 項",
        shelfHint: "按一下以選取，拖出即可使用，或按右鍵查看更多操作。",
        shelfItemImage: "圖片",
        shelfTooltipItemsFormat: "%d 個項目",
        shelfTooltipItemsFew: "%d 個項目",
        shelfTooltipImageSingular: "%d 張圖片",
        shelfTooltipImageFew: "%d 張圖片",
        shelfTooltipImagePlural: "%d 張圖片",
        shelfTooltipFileSingular: "%d 個檔案",
        shelfTooltipFileFew: "%d 個檔案",
        shelfTooltipFilePlural: "%d 個檔案",
        shelfTooltipNoteSingular: "%d 則備註",
        shelfTooltipNoteFew: "%d 則備註",
        shelfTooltipNotePlural: "%d 則備註",
        shelfTooltipLinkSingular: "%d 個連結",
        shelfTooltipLinkFew: "%d 個連結",
        shelfTooltipLinkPlural: "%d 個連結",
        shelfActionOpen: "開啟",
        shelfActionOpenWith: "開啟方式",
        shelfActionShare: "分享",

        breakdownMeasuring: "測量中…",

        mixerSection: "音量混音器",
        mixerEmpty: "正在使用音訊的 App 會顯示在這裡",
        mixerUnavailable: "需要 macOS 14.4 及更高版本",
        mixerPermissionBody: "若要調整各 App 的音量，請在「系統設定」中允許「螢幕與系統音訊錄製」。絕不會錄製音訊。",
        mixerResetTooltip: "重設為 100%",
        mixerOutputDefault: "預設",
        mixerOutputCurrent: "目前",
        mixerOutputUnavailable: "輸出無法使用",
        mixerOutputFallback: "此裝置恢復前，使用預設輸出。",
        mixerBypassedCaption: "此 App 自行管理音訊。",
        mixerOutputTooltip: "選取輸出",
        mixerSystemOutputTitle: "輸出",
        mixerSystemOutputNoDevices: "找不到輸出裝置",
        mixerSystemOutputTooltip: "選取系統輸出",
        mixerSystemOutputErrorFormat: "無法切換：%@",
        mixerLowerOnHeadphonesDisconnect: "耳機中斷連接時降低音量",
        mixerLowerOnHeadphonesDisconnectCaption: "有線或藍牙耳機中斷連接時自動調整音量。",
        mixerHeadphonesDisconnectVolume: "調整至",
        preciseVolumeRollerEnable: "使用更細的音量級距",
        preciseVolumeRollerCaption: "將音量滾輪和按鍵轉成更小的系統音量級距。",
        preciseVolumeRollerTapFailed: "無法監聽音量鍵。",
        soundOutputSwitcherTitle: "輸出切換器",
        soundOutputSwitcherEnable: "用快捷鍵切換輸出",
        soundOutputSwitcherCaption: "選取輸出裝置，然後用快捷鍵切到下一個可用輸出。",
        soundOutputSwitcherDevices: "循環中的輸出",
        soundOutputSwitcherNoAvailableSelection: "請至少選取一個可用輸出。",
        mixerInputTitle: "咪高峰",
        mixerInputNoDevices: "找不到咪高峰",
        mixerInputUnavailable: "咪高峰無法使用",
        mixerInputFallback: "此咪高峰恢復前，使用預設輸入。",
        mixerInputTooltip: "選取咪高峰",
        mixerInputErrorFormat: "無法切換：%@",
        mixerVisibleApps: "列表中的 App",
        mixerAllShown: "全部",
        mixerHiddenCountLabel: "已隱藏",
        mixerHideFromList: "從列表中隱藏",

        updatesSection: "更新",
        autoCheckToggle: "自動檢查更新",
        includeBetaUpdatesToggle: "接收 Beta 測試版更新",
        includeBetaUpdatesCaption: "Beta 版本包含開發中的新功能，可能存在不穩定或未完善的情況。",
        betaBadgeLabel: "Beta",
        checkNowButton: "立即檢查",
        updateChecking: "檢查中…",
        updateUpToDate: "你已使用最新版本。",
        updateAvailablePrefix: "有可用更新：",
        updateInstallButton: "下載並安裝",
        updateDownloading: "正在下載更新…",
        updateInstalling: "正在安裝並重新啟動…",
        updateFailedPrefix: "無法檢查：",
        updateLastChecked: "上次檢查：",
        updateNotifyTitle: "Vorssaint 更新",
        updateInstallFailedBody: "更新已下載，但無法安裝。請前往 GitHub 發佈頁面下載最新版本，並將 App 拖曳到目前的 App 上覆蓋。",
        updateNeedsApplicationsTitle: "請將 Vorssaint 移到「應用程式」檔案夾",
        updateNeedsApplicationsBody: "App 正在無法更新的位置執行，例如磁碟映像檔或系統暫存位置。請將 Vorssaint 拖曳到「應用程式」檔案夾，從那裡開啟後再試一次。",
        menuCheckUpdates: "檢查更新…",

        permissionRequired: "需要權限",
        permissionAccessibility: "輔助使用",
        permissionScreenRecording: "螢幕錄製",
        permissionGranted: "已允許",
        permissionMissing: "未允許",
        permissionOpenSettings: "開啟系統設定…",
        permissionRequest: "允許存取",
        permissionRestartNote: "允許後，macOS 可能會要求重新開啟 App。",

        aboutDescription: "你的 Mac 實用工具中心。\n電源、系統監控、捲動和視窗切換器，盡在選單列中。",
        versionPrefix: "版本",
        reviewIntro: "重看介紹",
        reviewHighlights: "重看新功能導覽",
        viewOnGitHub: "在 GitHub 上查看",

        obContinue: "繼續",
        obBack: "返回",
        obSkipStep: "略過此步驟",
        obStart: "開啟 Vorssaint",
        obStepWelcomeTitle: "歡迎使用 Vorssaint",
        obStepWelcomeBody: "一款低調的選單列實用工具，讓日常使用 macOS 更順手。",
        obWelcomeBullet1Title: "掌控電源",
        obWelcomeBullet1Body: "讓 Mac 想保持喚醒多久都可以，合上機蓋也不例外。",
        obWelcomeBullet2Title: "清楚掌握系統狀態",
        obWelcomeBullet2Body: "即時查看 CPU、GPU 和電池溫度、硬件使用量以及記憶體壓力。",
        obWelcomeBullet3Title: "滑鼠和視窗，由你決定",
        obWelcomeBullet3Body: "反轉滑鼠捲動，以及帶縮圖的視窗切換器。",
        obLanguageLabel: "語言",
        obStepAccessibilityTitle: "輔助使用",
        obStepAccessibilityBody: "用於反轉滑鼠捲動，並讓視窗切換器響應鍵盤操作。",
        obAccessibilityWhy: "App 只會監察滑鼠滾輪和切換器快捷鍵。不會錄製任何內容，也不會傳送到任何地方。",
        obStepRecordingTitle: "螢幕錄製",
        obStepRecordingBody: "讓切換器顯示真實的視窗縮圖，而不僅是圖示。",
        obRecordingWhy: "縮圖即時產生，只會保留在記憶體中，絕不會離開你的 Mac。即使沒有此權限，切換器仍可用圖示運作。",
        obStepMonitorTitle: "系統監控",
        obStepMonitorBody: "面板會顯示 CPU、GPU 和電池溫度、硬件使用量以及記憶體壓力。",
        obMonitorNoPermission: "無需任何權限。感應器直接從系統讀取。",
        obStepOptionalTitle: "可選功能",
        obStepOptionalBody: "現在開啟你想用的功能。一切都可以稍後在設定中更改。",
        obStepStatusTitle: "檢查",
        obStepStatusBody: "確認你想使用的功能都準備就緒。",
        obStatusRecheck: "重新檢查",
        obStepDoneTitle: "全部準備好！",
        obStepDoneBody: "Vorssaint 已開始照顧你的 Mac。",
        obDoneHint: "在選單列（螢幕右上角）尋找那個黑洞圖示。",
        obWhatsNewTitle: "此版本的新功能",
        obWhatsNewFallback: "此更新包含最新的修復和改進。",
        obLanguageUpdateTitle: "現已支援你的語言",
        obLanguageUpdateBody: "Vorssaint 現已支援多種語言。選取你想使用的語言，隨時可在設定中更改。",
        obPurposeTitle: "你想用它做什麼？",
        obPurposeBody: "選擇一套預設，或準確勾選你想使用的功能。",
        obPurposeSkip: "之後可隨時在設定中加入或移除功能。",

        tabMonitor: "監控",
        monitorMenuBarSection: "在選單列中",
        monitorMenuBarCaption: "選取選單列中圖示旁顯示的內容。",
        monitorCombineTemperatures: "合併使用率和溫度",
        monitorCombineTemperaturesCaption: "同一項目的使用率和溫度都啟用時，在一個區塊中顯示。",
        monitorSeparateMenuBarMetrics: "將指標分開顯示",
        monitorSeparateMenuBarMetricsCaption: "將已啟用的區塊拆成獨立的選單列項目；合併開啟時，使用率和溫度仍會放在一起。",
        monitorNetworkUploadFirst: "上傳顯示在下載上方",
        monitorShowCPU: "CPU",
        monitorShowMemory: "記憶體",
        monitorShowNetwork: "網絡",
        monitorShowPowerLabel: "電源",
        monitorIntervalLabel: "更新間隔",
        monitorInterval1: "1 秒",
        monitorInterval2: "2 秒",
        monitorInterval5: "5 秒",
        monitorPanelSection: "在面板中",
        panelNavigationMode: "分區式面板",
        panelNavigationCaption: "一次顯示一個分區。選擇「清單」即可連續捲動查看全部內容。",
        panelFooterSections: "分區",
        panelFooterList: "清單",
        betaBadge: "BETA",
        betaFeatureWarning: "測試版。你可能會遇到一些問題。",

        networkSection: "網絡",
        networkDownload: "下載",
        networkUpload: "上傳",
        networkThisSession: "今次時段",
        networkMeasuring: "測量中…",
        networkApps: "正使用網路的 App",
        networkAppsIdle: "無 App 使用網路中",

        diskSection: "磁碟",
        diskUsed: "已使用",
        diskFree: "可用",
        diskAvailable: "可用",
        diskPurgeable: "可清除",
        diskInternal: "內置",
        diskExternal: "外置",
        diskSelect: "選取磁碟",
        diskRead: "讀取",
        diskWrite: "寫入",
        diskSMARTStatus: "狀態",
        diskSMARTUnavailable: "此磁碟沒有可用的 SMART",
        diskTotalRead: "總讀取量",
        diskTotalWritten: "總寫入量",
        diskTemperature: "溫度",
        diskHealth: "健康度",
        diskPowerCycles: "通電次數",
        diskPowerOnHours: "通電時數",
        diskUnsafeShutdowns: "異常關機",
        diskMediaErrors: "媒體錯誤",
        diskEject: "推出",
        diskEjectAll: "全部推出",
        diskEjecting: "正在推出…",
        diskReadyToRemove: "可以移除",
        diskEjectFailed: "無法推出",
        diskProtectionCaption: "拔除前先推出。",
        diskNoExternal: "沒有可推出的外置磁碟。",
        diskOpenInFinder: "開啟",
        diskStorageSettings: "儲存",
        diskNoDisks: "找不到已掛載磁碟。",

        powerSection: "電源",
        powerSystem: "系統",
        powerAdapter: "插電器",
        powerBattery: "電池",
        powerCharging: "正插電",
        powerOnBattery: "使用電池",
        powerPluggedIn: "已連接電源",
        powerUnavailable: "此 Mac 上沒有可用的電源指標",
        powerAdapterMaxFormat: "最高 %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU 溫度",
        monitorShowGPUTemperature: "GPU 溫度",
        monitorShowBatteryTemperature: "電池溫度",
        monitorShowPeripheralBattery: "外置電池",
        peripheralBatteryNoDevices: "無外置電池",
        monitorGraphsSection: "圖表",
        monitorGraphsCaption: "選取哪些指標顯示隨時間變化的圖表。",

        updateBannerTitle: "有可用更新",
        updateBannerAction: "更新",
        obStepMenuBarTitle: "選單列中的指標",
        obStepMenuBarBody: "選取圖示旁要顯示的內容。上方預覽會即時更新。",
        obStepMenuBarNote: "新增：面板中的網絡和電源模組及圖表。稍後可在設定 › 監控中細緻調整。",
        monitorMenuBarPresetLabel: "樣式",
        menuBarPresetReadable: "易讀",
        menuBarPresetDense: "密集",
        menuBarSpacingLabel: "選單列間距",
        menuBarSpacingStandard: "標準",
        menuBarSpacingCompact: "緊湊",
        menuBarHideIconToggle: "顯示指標時隱藏 App 圖示",
        menuBarHideIconCaption: "當指標離開選單列，或有需要提示的內容（更新就緒或麥克風已靜音）時，圖示會自動回來。",
        monitorLabelStyleLabel: "標籤",
        menuBarLabelStyleCompact: "緊湊",
        menuBarLabelStyleClassic: "經典",
        monitorMemoryStyleLabel: "記憶體顯示方式",
        monitorMemoryPressureDot: "壓力圓點",
        memoryStyleDot: "圓點",
        memoryStylePercent: "%",
        memoryStyleBoth: "兩者",
        systemUptime: "已運作",
        batteryCharge: "電量",
        powerHealth: "電池健康度",
        powerCycles: "次循環",
        speedTestRun: "速度測試",
        speedTestAgain: "再次測速",
        speedTestLatency: "延遲",
        speedTestTesting: "測試中…",
        speedTestFailed: "測試失敗",

        monitorShowInPanel: "在面板中顯示",
        disclosureExpanded: "已展開",
        disclosureCollapsed: "已收合",
        panelHideItem: "從面板隱藏",
        panelShowItem: "在面板中顯示",
        panelHiddenItem: "隱藏",
        monitorItemUptime: "運作時間",
        monitorItemNetSpeed: "即時速度",
        monitorItemNetTotals: "時段總量",
        monitorItemNetTest: "速度測試",
        monitorItemDiskUsage: "磁碟使用",
        monitorItemDiskActivity: "即時活動",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "外置磁碟保護",
        monitorItemDiskTools: "工具",
        monitorPanelConfigHint: "開啟某個模組以選取它顯示的內容。",
        monitorOrderSection: "分區次序",
        monitorOrderHint: "拖曳以重新排列面板分區，按一下眼睛圖示可顯示或隱藏各分區。",
        obStepPanelTitle: "面板中顯示的內容",
        obStepPanelBody: "開啟每個模組，精確選取按一下圖示時顯示的內容。",
        obStepPanelNavigationTitle: "分區式面板",
        obStepPanelNavigationBody: "面板現時可以一次顯示一個分區。你可以在設定中切換「分區」與「清單」。",

        cleaningMenuItem: "清潔模式",
        utilitiesSection: "工具",
        quickControlsSection: "控制",
        panelCategoryWindows: "視窗",
        panelCategoryInput: "滑鼠和鍵盤",
        panelCategoryFiles: "檔案",
        windowMaximizeName: "最大化視窗",
        windowMaximizeCaption: "綠色按鈕會最大化視窗，而不會建立新的桌面空間。",
        windowMaximizeActiveNow: "綠色按鈕已啟用",
        windowMaximizeNeedsAccessibility: "需要輔助使用權限才能運作。",
        keyDebounceName: "按鍵重複過濾",
        keyDebounceEnable: "過濾重複按鍵",
        keyDebounceCaption: "過濾短時間內重複輸入的按鍵。",
        keyDebounceActiveNow: "過濾已開啟",
        keyDebounceGlobalWindow: "全域時間範圍",
        keyDebouncePerKeySection: "個別按鍵",
        keyDebouncePerKeyCaption: "個別按鍵的設定會覆蓋全域時間範圍。設為 0 ms 可讓該按鍵不套用過濾。",
        keyDebounceKeyLabel: "按鍵",
        keyDebounceWindowLabel: "時間範圍",
        keyDebounceAddKey: "加入按鍵",
        keyDebounceNoOverrides: "暫未設定個別按鍵。",
        keyDebounceRemoveKey: "移除按鍵",
        cleaningPanelCaption: "鎖定鍵盤，方便安全清潔。",
        cleaningOverlayTitle: "鍵盤已鎖定，方便清潔",
        cleaningOverlaySubtitle: "按 Esc 鍵 5 次即可解鎖",
        cleaningOverlayUnlock: "解鎖",
        cleaningOverlayMouseHint: "滑鼠和觸控板仍可使用",
        cleaningKeepScreenVisibleToggle: "保持螢幕可見",
        cleaningKeepScreenVisibleCaption: "在螢幕角落顯示小巧的指示條，而不調暗螢幕內容。",
        cleaningStartNow: "立即鎖定鍵盤",
        cleaningNeedsAxTitle: "需要輔助使用",
        cleaningNeedsAxBody: "為安全鎖定鍵盤，Vorssaint 需要輔助使用權限。請在「系統設定」中允許後重試。",

        tabSupport: "支援",
        shortcutsPageCaption: "喺呢度編輯此 Mac 已安裝功能嘅所有全域快捷鍵。未啟用嘅快捷鍵仍會保留，但唔會執行。",
        shortcutsPageTitle: "鍵盤快捷鍵",
        settingsSearchPlaceholder: "搜尋設定",
        donateHeading: "幫助 Vorssaint 繼續成長",
        donateMessage: "Vorssaint 免費、獨立，由我用空餘時間開發。如果你想提供經濟支持，Buy Me a Coffee 會直接幫助我繼續推進開發。",
        donateButton: "透過 Buy Me a Coffee 支持",
        donateThanks: "多謝你支持。🖤",
        supportIntroTitle: "幫助 Vorssaint 繼續成長",
        supportIntroMessage: "如果你想喺經濟上支持開發，Buy Me a Coffee 係唯一嘅支持方式。",
        supportIntroStarButton: "在 GitHub 為 Vorssaint 加星",
        supportIntroStarMessage: "我哋從不期待經濟支持。在 GitHub 加一顆星可以令更多人發現 Vorssaint，亦會實際幫助佢繼續發展。",
        supportIntroCoffeeButton: "透過 Buy Me a Coffee 支持",
        supportIntroLaterButton: "稍後再說",
        supportIntroDoneButton: "完成",
        discordIntroTitle: "Vorssaint Discord 社群啱啱起步",
        discordIntroMessage: "Vorssaint 社群啱啱成立，仲喺度慢慢完善。依家加入，認識其他用戶，一齊建立一個圍繞呢個 App 嘅友善空間。",
        discordIntroJoinButton: "加入 Discord 社群",
        communityIntroTitle: "搶先看到每個新功能",
        communityIntroMessage: "已經喺 X 追蹤我的人，早過其他人睇到今次更新嘅多項改動。我會喺嗰度發佈即將推出嘅新功能預覽同示範用法，等你喺更新推出前就掌握基本操作。追蹤我，搶先睇下之後有咩新嘢！",
        communityIntroFollowButton: "在 X 追蹤 @vorssaint",
        homebrewOfficialIntroTitle: "現已加入 Homebrew 官方目錄",
        homebrewOfficialIntroMessage: "而家可以直接由 Homebrew 官方目錄安裝 Vorssaint。",
        homebrewOfficialIntroInstallLabel: "全新安裝",
        homebrewOfficialIntroMigrationTitle: "用過舊 tap？",
        homebrewOfficialIntroMigrationMessage: "移除一次舊 tap。App 同你嘅設定都會保留。",
        homebrewOfficialIntroCopyButton: "複製指令",
        updateShowcaseTitle: "3.1.4 新功能",
        updateShowcaseMessage: "快速預覽今次更新的主要改進。",
        updateShowcaseUnavailable: "現時無法載入影片。你仍然可以繼續。",
        updateShowcaseRestart: "返回開頭",
        showMenuBarIcon: "顯示選單列圖示",
        showMenuBarIconCaption: "如果 Vorssaint 的圖示消失了（選單列空間不足時，macOS 可能會隱藏圖示；有瀏海的 Mac 較常見），請從「應用程式」或 Spotlight 重新開啟 Vorssaint。這會重新建立圖示；如果圖示仍被隱藏，則會開啟此視窗。",
        menuBarIconStillHiddenTitle: "圖示仍然被隱藏",
        menuBarIconStillHiddenBody: "圖示已重建，但 macOS 沒有給它可見的位置。選單列可能已經沒有空間：請移除一些選單列圖示（或關閉選單很長的 App）後再試一次。",
        menuBarIconManagerHintFormat: "%@ 正在執行，可能把圖示收進了它的隱藏區域。請在那裡找找 Vorssaint，或將 %@ 設定為一律顯示 Vorssaint。",
        shortcutRecording: "按下新的快捷鍵",
        shortcutReset: "重設",
        shortcutNone: "無",
        shortcutClear: "移除快捷鍵",
        shortcutInvalid: "請至少配搭 Control、Option 或 Command 其中一個修飾鍵，再加一個按鍵。",
        shortcutPressKeys: "按下按鍵",
        shortcutEscapeHint: "Esc 取消。",
        shortcutDeleteHint: "Delete 移除。",
        shortcutNotCaptured: "沒有擷取到任何按鍵。macOS 或其他應用程式已在使用這個組合，請換一個。",
        shortcutConflictFormat: "此快捷鍵已被 %@ 使用。",
        shortcutUnavailable: "macOS 拒絕使用此快捷鍵。請選取另一個。",
        shelfShortcutToggle: "暫存架快捷鍵",
        switcherUsageHintFormat: "按住 %@ 瀏覽；放開即可切換至視窗。Shift 或 ← 返回；W 關閉視窗；Q 結束 App；Esc 取消。",
        musicBlockSection: "媒體鍵",
        musicBlockTitle: "阻止音樂 App 自行開啟",
        musicBlockCaption: "按媒體鍵時音樂 App 不再開啟。你仍可以自己打開它。",
        musicBlockReplacementLabel: "改為開啟",
        musicBlockReplacementNone: "無",
        musicBlockChooseApp: "選擇 App…",
        cleanerName: "清理",
        cleanerIntroTitle: "清理 Mac 垃圾",
        cleanerIntroCaption: "尋找已解除安裝 App 的殘留、快取、記錄和垃圾桶。清理前可逐項確認，移除的項目會移到垃圾桶。",
        cleanerScan: "掃描",
        cleanerScanning: "掃描中…",
        cleanerCleaning: "清理中…",
        cleanerCatLeftovers: "已解除安裝 App 的殘留",
        cleanerCatLoginItems: "失效的登入項目",
        cleanerCatCaches: "快取",
        cleanerCatLogs: "記錄",
        cleanerCatDeveloper: "開發垃圾",
        cleanerCatTrash: "垃圾桶",
        cleanerLeftoversNote: "由分析找到，預設不勾選。勾選前請確認路徑。",
        cleanerLoginItemsNote: "登入項目中的項目會在 Mac 重新開機後消失。",
        cleanerTrashNote: "清空垃圾桶是永久操作。",
        cleanerCatDeviceBackups: "iPhone 備份",
        cleanerDeviceBackupsCaption: "舊的 iPhone 和 iPad 備份佔了 macOS 所稱「其他」儲存空間的很大一部分。只刪除不再需要的備份；下次連接裝置時會建立新的備份。",
        cleanerNothingFound: "沒有可清理的內容。Mac 很整潔。",
        cleanerClean: "清理",
        cleanerDoneNote: "項目已移到垃圾桶，可以從那裡復原。",
        cleanerAgain: "再次掃描",
        cleanerRevealInFinder: "在 Finder 中顯示",
        cleanerPanelCaption: "App 殘留、快取和日誌",
        cleanerSafeSection: "安全清理",
        cleanerOptionalSection: "可選，請先確認",
        cleanerCatOtherCaches: "其他快取",
        cleanerCachesCaption: "App 會自行重建的暫存檔案。",
        cleanerLogsCaption: "舊的診斷記錄。",
        cleanerDeveloperCaption: "Xcode 建置和模擬器殘留。",
        cleanerLoginItemsCaption: "已不存在的 App 留下的登入項目。",
        cleanerLeftoversCaption: "已解除安裝 App 留下的檔案。",
        cleanerOtherCachesCaption: "可以放心刪除，不會損壞任何東西。App 首次開啟可能變慢，離線音樂等已下載內容會重新下載。",
        cleanerCleanSizeFormat: "清理 %@",
        cleanerScheduleTitle: "自動清理",
        cleanerScheduleOff: "關閉",
        cleanerScheduleDaily: "每天",
        cleanerScheduleWeekly: "每週",
        cleanerScheduleCaption: "在所選時間自動清理安全部分，並把所有內容移到垃圾桶。",
        cleanerScheduleLastFormat: "上次自動清理釋放了 %@。",
        cleanerAutoNotificationFormat: "已釋放 %@ 並移到垃圾桶。",
        cleanerScheduleNextFormat: "下次清理%@。",
        cleanerScheduleRanFormat: "上次自動清理%@。",
        cleanerScheduleNotifyToggle: "完成時通知",
        cleanerNotifDenied: "Vorssaint 的通知在系統中已關閉。",
        cleanerNotifOpenSettings: "打開通知設定…",
        launchAtLoginNeedsApplications: "App 正從無法在登入時開啟的位置執行。請將 Vorssaint 拖到「應用程式」檔案夾，從那裡開啟後再重新開啟此選項。",
        launchAtLoginNeedsApproval: "登入項目已註冊，但系統設定中仍是關閉的。請打開「系統設定 › 一般 › 登入項目與延伸功能」，在「登入時打開」中開啟 Vorssaint。",
        ocrRemoveLineBreaksToggle: "移除換行",
        ocrRemoveLineBreaksCaption: "移除識別文字中的換行，讓拷貝的內容貼上為單一段落。",
        ocrQRToggle: "讀取 QR 碼",
        ocrQRCaption: "如果所選區域包含 QR 碼，會顯示它的內容以便拷貝或打開。",
        ocrQRCopied: "QR 碼已拷貝",
        qrResultTitle: "QR 碼",
        qrResultCopy: "拷貝",
        qrResultOpen: "打開連結",
        highlightsTitle: "本次更新亮點",
        highlightsTitleClipboardRedesign: "剪貼板全新設計",
        highlightsTitleWindowLayout: "視窗佈局",
        highlightsTitleQuitProtection: "⌘Q 與 ⌘W 保護",
        highlightsTitleRecorderBlur: "螢幕錄影模糊遮蓋",
        highlightsCaptionDockPreview: "Dock Preview 現在可以在開啟 Dock 放大時使用",
        highlightsCaptionScreenshot: "截圖工具新增了像素放大鏡和 QR 碼讀取",
        highlightsCaptionSnippetLibrary: "可搜尋的片段選單把任何片段直接輸入到游標處",
        highlightsCaptionCapturePalette: "單個快捷鍵現在可開啟浮動面板，快速進行截圖、錄影、擷取螢幕文字與取色，並就近調整各項設定。",
        highlightsCaptionClipboardRedesign: "剪貼板歷史現在作為緊湊浮動面板開啟，行佈局更簡潔，並提供按需預覽以閱讀或編輯完整內容。",
        highlightsCaptionWindowLayout: "使用快捷鍵和指標的方向環放置視窗，或拖曳至螢幕邊緣按自訂間距貼齊。",
        highlightsCaptionQuitProtection: "透過長按、連按兩次或額外修飾鍵防止誤關應用程式與視窗，支援個別應用程式獨立設定。",
        highlightsCaptionRecorderBlur: "在匯出或分享錄影前，可在任何時間段對密碼及私隱資訊進行模糊遮蓋。",
        highlightsConfigure: "設定",
        highlightsTry: "試試看",
        highlightsSeeAll: "查看所有變更",
        switcherCurrentSpaceOnly: "僅顯示目前的桌面",
        switcherCurrentSpaceOnlyCaption: "切換器中只顯示你所在桌面的視窗。選擇視窗不會帶你前往其他桌面。",
        shelfFileMissing: "檔案已不存在",
        previewSizeSmall: "小",
        mixerSoundEffectsOutputTitle: "系統聲音",
        mixerSoundEffectsOutputTooltip: "選擇提示音和音效的播放裝置",
        monitorOpenActivityMonitor: "打開活動監視器",
        dockClickHide: "點按 Dock 圖示隱藏 App",
        dockClickHideCaption: "點按目前 App 的 Dock 圖示即可隱藏它。再點按一次即可帶回。",
        monitorMemoryMetricLabel: "記憶體計量方式",
        memoryMetricUsed: "已用記憶體",
        memoryMetricApp: "App 記憶體",
        keepAwakeRightClickToggle: "在選單列圖示按右鍵來切換「保持喚醒」",
        keepAwakeRightClickToggleCaption: "會取代按右鍵選單。",
        urlCleanerRulesTitle: "清理規則",
        urlCleanerRulesCaption: "網站會把這些參數加在自己的分享連結上，用來追蹤連結從哪裡來。勾選表示清理時把它刪掉，取消勾選表示保留。自行加入的名稱可以刪除。",
        urlCleanerRulesCoverageCaption: "表裡涵蓋的是同一個網站的不同分享入口（網頁、App、直播間），所以條目多；一條真實連結通常只帶當中 2 至 4 個。",
        urlCleanerRulesAllSites: "所有網站",
        urlCleanerRulesCountSingular: "1 個參數",
        urlCleanerRulesCountPluralFormat: "%d 個參數",
        urlCleanerRulesAddSite: "加入網站",
        urlCleanerRulesParameterPlaceholder: "參數名稱",
        urlCleanerRulesMatchCaption: "填 = 左邊的名字，例如 utm_source。命中的名字只會讓那一個參數從連結裡消失，其餘部分原樣保留。",
        urlCleanerRulesAddButton: "加入",
        urlCleanerRulesRemoveButton: "刪除名稱",
        urlCleanerRulesRemoveSiteButton: "關閉這個網站的全部規則",
        urlCleanerRemovedFormat: "已移除 %@",
        switcherSearchPin: "按 S 固定搜尋",
        switcherSearchPinCaption: "瀏覽時按 S 啟動搜尋，固定切換器；避免自訂快捷鍵為 ⌥ 時打出特殊字符，以及 Q/W 開頭誤觸發關閉/結束。",
        invertVerticalScroll: "反轉垂直捲動",
        invertHorizontalScroll: "反轉水平捲動",
        switcherShowShortcutHints: "顯示快速鍵提示",
        switcherShowShortcutHintsCaption: "在圖示下方顯示 App 和視窗快速鍵。",
        uninstallerHomebrewPackageFormat: "%@ 亦會從 Homebrew 移除。",
        shelfEdgeToggle: "接近螢幕邊緣時開啟",
        shelfEdgeCaption: "將檔案拖曳至螢幕邊緣，暫存架便會探出一角。放在那裡即可放低，往回拖曳暫存架便會縮回去。",
        focusFollowsMouseName: "游標停留時聚焦",
        focusFollowsMouseCaption: "游標短暫停留後，聚焦並將其下方視窗移至最前方。",
        focusFollowsMouseDelay: "停留延遲",
        switcherMinimizedPlacementLabel: "已最小化的視窗",
        switcherMinimizedPlacementNormal: "正常順序",
        switcherMinimizedPlacementEnd: "放到最後",
        switcherMinimizedPlacementHidden: "隱藏",
        switcherShowFullscreenWindows: "顯示全螢幕視窗",
        switcherScreenPlacementLabel: "顯示於",
        switcherScreenPlacementPointer: "指標所在的螢幕",
        switcherScreenPlacementMenuBar: "選單列所在的螢幕",
        switcherScreenPlacementActiveWindow: "使用中視窗所在的螢幕",
        switcherScreenPlacementCaption: "連接多個螢幕時，切換器在哪個螢幕開啟。",
        smoothScrollResponseLabel: "反應速度",
        mouseAccelerationName: "關閉滑鼠加速",
        mouseAccelerationCaption: "移除已連接滑鼠的指標加速。關閉此選項或結束 Vorssaint 後，會還原之前的設定。",
        shelfClearOnClose: "關閉時清空",
        shelfClearOnCloseCaption: "只有點按關閉按鈕時才會清空暫存架。自動隱藏或收合時會保留項目。"
    )
}
