// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Français — translated and hand-checked, not machine output.
extension Strings {
    static let fr = Strings(
        statusIdleTooltip: "Vorssaint\u{00A0}: veille normale",
        statusActiveUntil: "Vorssaint\u{00A0}: éveillé jusqu’à",
        statusActiveIndefinite: "Vorssaint\u{00A0}: éveillé indéfiniment",
        menuEnableAwake: "Activer le maintien éveillé",
        menuDisableAwake: "Désactiver le maintien éveillé",
        menuActivateFor: "Activer pour…",
        menuSettings: "Réglages…",
        menuAbout: "À propos de Vorssaint",
        menuQuit: "Quitter Vorssaint",
        menuHide: "Masquer Vorssaint",
        menuHideOthers: "Masquer les autres",
        menuShowAll: "Tout afficher",
        menuEdit: "Édition",
        menuUndo: "Annuler",
        menuRedo: "Rétablir",
        actionClear: "Effacer",
        actionRemove: "Retirer",
        actionBack: "Retour",
        actionSearch: "Rechercher",
        actionMute: "Couper le son",
        actionUnmute: "Réactiver le son",
        actionPlay: "Lire",
        actionPause: "Suspendre",
        menuCut: "Couper",
        menuCopy: "Copier",
        menuPaste: "Coller",
        menuSelectAll: "Tout sélectionner",
        menuWindow: "Fenêtre",
        menuMinimize: "Réduire",
        menuZoom: "Zoom",
        menuClose: "Fermer",

        minutes15: "15 minutes",
        minutes30: "30 minutes",
        hour1: "1 heure",
        hours2: "2 heures",
        hours4: "4 heures",
        hours8: "8 heures",
        indefinitely: "Indéfiniment",
        indefinite: "Indéfinie",

        panelSettings: "Réglages",
        panelQuit: "Quitter",
        panelHotkeyHint: "Le raccourci bascule",

        keepAwakeTitle: "Garder éveillé",
        keepAwakeEndsIn: "Se termine dans",
        keepAwakeUntilDisabled: "Actif jusqu’à ce que vous le désactiviez",
        keepAwakeNormalRules: "Le Mac suit ses règles d’énergie normales",
        keepAwakeOptions: "Options",
        keepAwakeMouseJiggle: "Déplacer légèrement le pointeur",
        keepAwakeMouseJiggleCaption: "Pendant une session, déplace un peu le pointeur à l’intervalle choisi.",
        keepAwakeMouseJiggleInterval: "Intervalle",
        keepAwakeActiveIconLabel: "Icône active",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Café",
        keepAwakeActiveIconEye: "Œil",
        keepAwakeActiveIconMoon: "Lune",
        keepAwakeActiveIconLight: "Ampoule",
        keepAwakeIconTintLabel: "Couleur de l’icône active",
        keepAwakeIconTintOrange: "Orange",
        keepAwakeIconTintGreen: "Vert",
        keepAwakeIconTintBlue: "Bleu",
        keepAwakeIconTintPurple: "Violet",
        keepAwakeIconTintPink: "Rose",
        keepAwakeIconTintNone: "Sans couleur",
        durationLabel: "Durée",
        clamshellTitle: "Continuer écran rabattu",
        clamshellOnCaption: "Veille entièrement désactivée. Attention à l’énergie",
        clamshellNeedsSession: "Appliqué dès que «\u{00A0}Garder éveillé\u{00A0}» est actif",
        clamshellReady: "Prêt. Bascule sans mot de passe",
        clamshellNeedsPassword: "Demandera le mot de passe administrateur une fois",

        systemSection: "Système",
        temperatures: "Températures",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batterie",
        usageSection: "Utilisation du matériel",
        memorySection: "Mémoire",
        memoryPressure: "Pression",
        memorySwapUsed: "Swap utilisé",
        memoryCompressed: "Compressée",
        memoryCachedFiles: "Fichiers en cache",
        pressureNormal: "Normale",
        pressureWarning: "Attention",
        pressureCritical: "Critique",
        monitorUnavailable: "Capteurs indisponibles sur ce Mac",
        energyAppsTitle: "Consommation importante",
        energyAppsIdle: "Aucune consommation importante",

        notifySessionEndedTitle: "Session terminée",
        notifySessionEndedBody: "Le temps est écoulé. Le Mac se remettra en veille normalement.",
        notifyBatteryTitle: "Vorssaint désactivé",
        notifyBatteryBody: "Batterie faible. La veille normale a été rétablie pour préserver la charge.",
        adminPromptClamshellOn: "Vorssaint a besoin de votre mot de passe pour continuer écran rabattu.",
        adminPromptClamshellOff: "Vorssaint a besoin de votre mot de passe pour rétablir la veille normale du Mac.",
        adminPromptRecover: "Vorssaint a quitté alors que la veille du Mac était désactivée. Saisissez le mot de passe pour rétablir la veille normale.",
        adminPromptUpdate: "Vorssaint a besoin de votre mot de passe pour installer la mise à jour.",
        adminPromptSudoersInstall: "Vorssaint va créer une règle restreinte (pmset disablesleep uniquement) pour basculer le mode écran rabattu sans demander de mot de passe. C’est la seule fois où le mot de passe est nécessaire.",
        adminPromptSudoersRemove: "Vorssaint va supprimer la règle d’écran rabattu sans mot de passe.",

        settingsTitle: "Réglages de Vorssaint",
        tabGeneral: "Général",
        tabEnergy: "Énergie",
        tabMouse: "Souris et trackpad",
        tabSwitcher: "Sélecteur",
        tabAdvanced: "Avancé",
        tabAbout: "À propos",
        tabReleaseNotes: "Nouveautés",
        releaseNotesOnUpdateToggle: "Afficher les nouveautés après mise à jour",
        minimalWindowPreviews: "Aperçus minimalistes",
        minimalWindowPreviewsCaption: "Masque les titres, les boutons et les ornements des aperçus du Dock et du sélecteur d’apps. La sélection reste visible.",
        previewSizeLabel: "Taille des aperçus",
        previewSizeNormal: "Normale",
        previewSizeLarge: "Grande",
        previewSizeXLarge: "Très grande",
        settingsGroupFeatures: "Fonctionnalités",
        advancedResetSection: "Autorisations",
        advancedResetDescription: "Retire toutes les autorisations que vous avez accordées à Vorssaint (Accessibilité, Enregistrement de l’écran, Accès complet au disque et autres), l’élément d’ouverture et la règle d’écran rabattu. Utile pour repartir de zéro ou avant de désinstaller. L’app reste installée.",
        advancedClearButton: "Effacer toutes les autorisations",
        advancedCleared: "Autorisations effacées.",
        advancedClearConfirmTitle: "Effacer toutes les autorisations\u{00A0}?",
        advancedClearConfirmBody: "Les fonctionnalités qui nécessitent des autorisations cesseront de fonctionner jusqu’à ce que vous les accordiez à nouveau. Vos réglages sont conservés.",
        advancedUninstallSection: "Désinstaller",
        advancedUninstallDescription: "Fait tout ce qui précède, puis supprime les préférences et place Vorssaint dans la corbeille, sans rien laisser. L’app quitte une fois terminé. Vous pouvez réinstaller à tout moment.",
        advancedUninstallButton: "Désinstaller complètement Vorssaint",
        advancedUninstallConfirmTitle: "Désinstaller Vorssaint\u{00A0}?",
        advancedUninstallConfirmBody: "Vorssaint va effacer ses autorisations, supprimer ses préférences et se placer dans la corbeille, puis quitter. L’app ne peut pas annuler cette action, mais elle reste dans la corbeille jusqu’à ce que vous la vidiez.",
        advancedUninstallFailedTitle: "Désinstallation interrompue",
        advancedUninstallFailedBody: "Vorssaint n’a pas pu rétablir un réglage système qu’il avait modifié\u{00A0}: la veille, la vitesse des ventilateurs ou l’accélération de la souris. Rien n’a été supprimé. Réessayez et autorisez la demande de mot de passe si elle apparaît.",

        launchAtLogin: "Ouvrir à l’ouverture de session",
        languageLabel: "Langue",
        menuBarSection: "Barre des menus",
        showCountdown: "Afficher le temps restant à côté de l’icône",
        globalHotkeySection: "Raccourci global",
        hotkeyToggle: "Activer le raccourci pour «\u{00A0}Garder éveillé\u{00A0}»",
        hotkeyCaption: "Fonctionne dans toutes les apps, sans autorisation supplémentaire.",

        sessionSection: "Session",
        defaultDurationLabel: "Durée par défaut",
        keepAwakeAutoStart: "Garder éveillé à l’ouverture de Vorssaint",
        keepAwakeAutoStartCaption: "Démarre une session avec la durée par défaut.",
        batteryProtectionSection: "Protection de la batterie",
        batteryDisableBelow: "Désactiver lorsque la batterie passe sous",
        batteryNever: "Jamais",
        batteryProtectionCaption: "Empêche une session oubliée de vider la batterie du MacBook.",
        clamshellSection: "Écran rabattu",
        configuring: "Configuration…",
        sudoersFailed: "Impossible d’activer l’écran rabattu. Réessayez.",
        clamshellExplanation: "«\u{00A0}Continuer écran rabattu\u{00A0}» désactive entièrement la veille tant que «\u{00A0}Garder éveillé\u{00A0}» est actif et se rétablit automatiquement à la fin de la session ou quand l’app quitte. À privilégier branché sur secteur.",

        scrollSection: "Défilement",
        invertMouseScroll: "Inverser le défilement de la souris",
        invertMouseScrollCaption: "Inverse le sens de la molette de la souris.",
        scrollTrackpadNote: "Le trackpad n’est pas affecté\u{00A0}: il conserve le défilement naturel de macOS.",
        scrollActiveNow: "Inversion du défilement de la souris en cours",
        mouseNavigationActiveNow: "Boutons latéraux actifs en ce moment",
        smoothScrollName: "Défilement fluide",
        smoothScrollCaption: "Transforme chaque cran de la molette de la souris en un court glissement fluide. Le trackpad ne change pas.",
        smoothScrollStepLabel: "Vitesse de défilement",
        mouseNavigationSection: "Navigation",
        mouseNavigationEnable: "Utiliser les boutons latéraux pour Précédent et Suivant",
        mouseNavigationCaption: "Transforme les boutons Précédent et Suivant de la souris en commandes de navigation dans le Finder, les navigateurs et les apps compatibles.",
        middleClickSection: "Clic du milieu",
        middleClickEnable: "Le clic à trois doigts devient un clic du milieu",
        middleClickEnableCaption: "Appuyer sur le trackpad avec trois doigts agit comme un clic sur la molette de la souris\u{00A0}: ouvrir les liens dans un nouvel onglet, fermer des onglets et tout ce que fait le bouton du milieu.",
        middleClickDragConflict: "Le glissement à trois doigts de macOS est activé et utilise ce même geste. Désactivez-le dans Réglages Système, sous Accessibilité, Contrôle du pointeur, Options du trackpad, pour que le clic du milieu fonctionne.",
        middleClickTapPicker: "Un tapotement léger clique aussi",
        middleClickTapOff: "Désactivé",
        middleClickTapThreeFingers: "3 doigts",
        middleClickTapFourFingers: "4 doigts",
        middleClickTapCaption: "Un tapotement léger avec ce nombre de doigts, sans appuyer, déclenche aussi le clic du milieu. Glisser ne compte jamais. Si le tapotement à trois doigts de macOS est assigné à Rechercher, désactivez-le pour que les deux ne se déclenchent pas ensemble.",
        quickToolsTab: "Panneau rapide",
        quickToolShortcutToggle: "Raccourci global",
        ocrName: "Copier le texte à l’écran",
        ocrCaption: "Sélectionnez une zone de l’écran et le texte reconnu est copié, prêt à coller.",
        ocrCopied: "Texte copié",
        ocrNoText: "Aucun texte trouvé",
        colorPickerName: "Pipette de couleur",
        colorPickerCaption: "Capturez la couleur de n’importe quel pixel de l’écran et copiez-la dans le format de votre choix.",
        colorPickerFormatLabel: "Format copié",
        colorPickerBareHexToggle: "Copier sans le préfixe #",
        colorPickerPickNow: "Prélever la couleur",
        micMuteName: "Couper le micro",
        micUnmuteName: "Réactiver le micro",
        micMuteCaption: "Coupe le micro du Mac d’un clic ou d’un raccourci, dans toutes les apps.",
        micMutedHUD: "Micro coupé",
        micUnmutedHUD: "Micro réactivé",
        micMuteMenuBarToggle: "Afficher dans la barre des menus quand le micro est coupé",
        micMuteMenuBarCaption: "Un micro barré en rouge apparaît à côté de l’icône de l’app dans la barre des menus.",
        pastePlainName: "Coller en texte brut",
        pastePlainCaption: "Colle ce qui a été copié sans couleurs, polices ni mise en forme. L’original reste dans le presse-papiers.",
        launcherName: "Panneau rapide",
        launcherCaption: "Un panneau flottant avec vos outils préférés, appelé par un raccourci depuis n’importe où.",
        launcherOpenNow: "Ouvrir le panneau rapide",
        launcherEditHint: "Utilisez le bouton de réglage pour choisir, masquer et faire glisser les outils.",
        launcherEmptyState: "Tous les outils sont masqués. Utilisez le bouton de réglage pour les remettre.",
        launcherAddSection: "Rajouter",
        launcherKeysHint: "Les flèches naviguent, Entrée ouvre, 1 à 9 ouvrent directement",
        switcherSection: "Sélecteur d’apps",
        switcherEnable: "Utiliser le sélecteur Vorssaint",
        switcherEnableCaption: "Passez d’une app ou fenêtre à l’autre, y compris les fenêtres minimisées et plusieurs fenêtres d’une même app.",
        switcherUsageHint: "Maintenez le raccourci pour naviguer\u{00A0}; relâchez pour activer la fenêtre. Maj ou ← revient en arrière\u{00A0}; W ferme la fenêtre\u{00A0}; Q quitte l’app\u{00A0}; Échap annule.",
        switcherNoWindows: "Aucune fenêtre ouverte",
        switcherIconRowMode: "Afficher %@ avec de grandes icônes",
        switcherIconRowModeCaption: "Affiche une icône par app avec les aperçus de ses fenêtres au-dessus.",
        switcherSimpleMode: "Sélecteur d’apps simple",
        switcherSimpleModeCaption: "Affiche les icônes des apps et les titres des fenêtres, sans aperçu ni capture d’écran par le sélecteur.",
        switcherShortcutHintApps: "Apps",
        switcherShortcutHintWindows: "Fenêtres",
        switcherWindowShortcutCaption: "Ouvre un sélecteur pour les fenêtres de l’app au premier plan. Sélecteur d’apps ouvert, passe d’une fenêtre à l’autre de l’app sélectionnée.",
        switcherTakeOverSystemShortcuts: "Remplacer ⌘Tab et ⌘` de macOS",
        switcherTakeOverSystemShortcutsCaption: "Désactive les raccourcis macOS correspondants uniquement lorsque le sélecteur Vorssaint est actif. Toutes les apps ouvertes restent accessibles.",
        switcherAppearanceDelay: "Délai d’affichage",
        switcherAppearanceDelayCaption: "Durée pendant laquelle le raccourci doit rester enfoncé avant l’affichage du sélecteur.",
        switcherMergeTabs: "Afficher une seule entrée par app",
        switcherMergeTabsCaption: "Regroupe toutes les fenêtres d’une app en une seule entrée dans le sélecteur, au lieu d’une entrée par fenêtre.",
        switcherWindowlessApps: "Apps sans fenêtre ouverte",
        switcherWindowlessAppsCaption: "Choisit quelles apps ouvertes sans aucune fenêtre apparaissent dans le sélecteur.",
        switcherWindowlessAppsOff: "Ne pas afficher",
        switcherWindowlessAppsFinder: "Finder uniquement",
        switcherWindowlessAppsAll: "Toutes les apps",
        switcherNoOpenWindow: "Sans fenêtre ouverte",
        switcherOtherDesktop: "Autre bureau",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Prévisualiser les fenêtres dans le Dock",
        dockPreviewEnableCaption: "Survolez une app ouverte dans le Dock pour voir ses fenêtres, puis cliquez sur celle à ouvrir.",
        dockPreviewBackgroundOpacity: "Fond du panneau",
        dockPreviewBackgroundOpacityCaption: "Baissez-le pour voir davantage ce qui se trouve derrière le panneau.",
        dockPreviewOpenDelay: "Délai d’ouverture",
        dockPreviewOpenDelayCaption: "Combien de temps le pointeur doit rester sur une icône avant que le panneau s’ouvre.",
        dockPreviewQuitAppOnClose: "Quitter l’app avec le bouton ×",
        dockPreviewQuitAppOnCloseCaption: "Dans Dock Preview, × quitte toute l’app au lieu de fermer uniquement cette fenêtre.",
        dockClickMinimize: "Réduire d’un clic sur le Dock",
        dockClickMinimizeCaption: "Les fenêtres de l’app active se réduisent d’un clic sur son icône du Dock. Cliquez à nouveau pour les faire revenir.",
        dockClickCycleWindows: "Clic sur le Dock pour alterner les fenêtres",
        dockClickCycleWindowsCaption: "Cliquez sur l’icône d’une app active dans le Dock pour passer d’une fenêtre à l’autre, comme ⌘`.",
        dockPreviewActiveNow: "Actif dans le Dock",
        dockPreviewDockUnavailable: "Impossible de lire les éléments du Dock.",
        dockPreviewAutohideBeta: "Bêta. Vous pouvez rencontrer quelques bugs.",
        dockPreviewOpenWindow: "Ouvrir la fenêtre",
        dockPreviewCloseWindow: "Fermer la fenêtre",
        dockPreviewMinimizeWindow: "Réduire la fenêtre",
        dockPreviewRestoreWindow: "Restaurer la fenêtre",
        dockPreviewPinPanel: "Épingler l’aperçu",
        dockPreviewUnpinPanel: "Détacher l’aperçu",
        dockPreviewPinned: "Épinglé",
        dockPreviewClosePanel: "Fermer l’aperçu",
        dockPreviewPreviousWindow: "Fenêtre précédente",
        dockPreviewNextWindow: "Fenêtre suivante",

        cutPasteName: "Couper-coller",
        cutPasteEnable: "Couper-coller des fichiers dans le Finder",
        cutPasteEnableCaption: "Utilisez ⌘X pour couper et ⌘V pour déplacer des fichiers et des dossiers dans le Finder.",
        cutPasteShowHUD: "Afficher le panneau flottant",
        cutPasteShowHUDCaption: "Affiche un indicateur flottant avec les fichiers coupés lorsque le Finder est actif.",
        cutPasteHowTitle: "Comment l’utiliser",
        cutPasteStep1: "Sélectionnez des éléments dans le Finder et appuyez sur ⌘X pour les couper.",
        cutPasteStep2: "Ouvrez le dossier de destination et appuyez sur ⌘V pour les y déplacer.",
        cutPasteTextNote: "Dans les champs de texte (comme lors d’un renommage), ⌘X et ⌘V continuent de fonctionner normalement.",
        cutPasteActiveNow: "Prêt à couper dans le Finder",
        cutPasteAutomationNote: "La première fois, macOS demande l’autorisation de contrôler le Finder.",
        cutReadyTitle: "Coupé",
        cutReadyHint: "dans le dossier de destination pour déplacer",
        cutCancel: "Annuler la coupe",
        cutDoneTitle: "Déplacé\u{00A0}!",
        cutMovedSingular: "1 élément déplacé",
        cutMovedPluralFormat: "%d éléments déplacés",
        cutSomeFailed: "Certains éléments n’ont pas pu être déplacés",
        cutMovingTitle: "Déplacement…",
        cutMovingCountFormat: "%d sur %d",

        autoQuitName: "Quitter à la fermeture",
        autoQuitEnable: "Quitter une app à la fermeture de sa dernière fenêtre",
        autoQuitEnableCaption: "Fermer la dernière fenêtre d’une app la fait aussi quitter.",
        autoQuitActiveNow: "Actif en ce moment",
        autoQuitHowTitle: "Comment ça marche",
        autoQuitStep1: "Fermez la dernière fenêtre d’une app (⌘W ou le bouton rouge).",
        autoQuitStep2: "L’app quitte d’elle-même. Les fenêtres «\u{00A0}Enregistrer les modifications\u{00A0}?\u{00A0}» s’affichent toujours.",
        autoQuitPredictableNote: "Les apps qui fonctionnent normalement sans fenêtre ne quittent jamais.",
        autoQuitExceptionsTitle: "Exceptions",
        autoQuitExceptionsCaption: "Les apps de cette liste restent ouvertes même sans aucune fenêtre.",
        autoQuitExceptionsEmpty: "Aucune exception",
        autoQuitAddApp: "Ajouter une app…",

        uninstallerName: "Programme de désinstallation",
        uninstallerEnableCaption: "Retire une app avec les caches, les préférences, les journaux et les résidus qu’elle laisse derrière elle.",
        uninstallerStep1: "Glissez une app sur les Réglages, ou choisissez-en une dans la liste.",
        uninstallerStep2: "Examinez les fichiers trouvés et l’espace qu’ils occupent.",
        uninstallerStep3: "Placez ce que vous voulez dans la corbeille. Rien n’est supprimé définitivement.",
        uninstallerMenuItem: "Désinstaller une app…",
        uninstallerDropTitle: "Glissez une app ici",
        uninstallerDropSubtitle: "ou choisissez-en une à analyser",
        uninstallerChoose: "Choisir une app…",
        uninstallerPickerTitle: "Choisir une app",
        uninstallerPickerSearch: "Rechercher des apps",
        uninstallerPickerEmpty: "Aucune app trouvée",
        uninstallerEmptyNote: "Rien n’est retiré sans votre confirmation.",
        uninstallerFDANote: "Accordez l’Accès complet au disque pour une analyse plus approfondie.",
        uninstallerFDAGrant: "Accorder l’accès…",
        uninstallerFDAHint: "Activez Vorssaint dans la liste. S’il ne s’y trouve pas, cliquez sur + et choisissez Vorssaint dans Applications. L’accès ne s’applique qu’après la réouverture de l’app.",
        uninstallerFDARelaunch: "Relancer maintenant",
        uninstallerScanning: "Analyse des fichiers…",
        uninstallerRemoving: "Déplacement vers la corbeille…",
        uninstallerFoundTitle: "trouvé",
        uninstallerSelectedFormat: "%d sur %d sélectionnés",
        uninstallerRemove: "Placer dans la corbeille",
        uninstallerCancel: "Annuler",
        uninstallerDoneTitle: "Terminé\u{00A0}!",
        uninstallerFreedFormat: "%@ récupérés",
        uninstallerSomeFailed: "Certains éléments n’ont pas pu être placés dans la corbeille.",
        uninstallerFailedNeedsFDA: "Les données des apps en bac à sable ne peuvent être déplacées qu’avec l’accès complet au disque. Le mot de passe administrateur ne le remplace pas.",
        uninstallerFailedMoreFormat: "et %d autres",
        uninstallerAnother: "Désinstaller une autre app",
        uninstallerCatApp: "Application",
        uninstallerCatSupport: "Assistance",
        uninstallerCatCaches: "Caches",
        uninstallerCatPreferences: "Préférences",
        uninstallerCatContainers: "Conteneurs",
        uninstallerCatLogs: "Journaux",
        uninstallerCatState: "État enregistré",
        uninstallerCatOther: "Autres",

        urlCleanerName: "Nettoyer l’URL",
        urlCleanerEnable: "Nettoyer les URL à la copie",
        urlCleanerEnableCaption: "Retire les paramètres de suivi d’un lien dès qu’il arrive dans le presse-papiers.",
        urlCleanerActiveNow: "Actif en ce moment",
        urlCleanerManualTitle: "Nettoyer maintenant",
        urlCleanerInputPlaceholder: "Collez une URL",
        urlCleanerOutputPlaceholder: "L’URL nettoyée apparaît ici",
        urlCleanerCleanButton: "Nettoyer",
        urlCleanerPasteButton: "Coller",
        urlCleanerCopyButton: "Copier",
        urlCleanerClearButton: "Vider le champ",
        urlCleanerNoURL: "Collez une URL valide.",
        urlCleanerNoChange: "Rien à nettoyer.",
        urlCleanerCleaned: "URL nettoyée.",
        urlCleanerCopied: "Copié.",
        urlCleanerLocalNote: "Local. Sans réseau.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Recherchez, installez et retirez des formules et des casks.",
        homebrewMissingTitle: "Homebrew introuvable",
        homebrewMissingBody: "Vorssaint peut ouvrir Terminal avec l’installateur officiel de Homebrew. Terminal affiche les étapes et demande votre mot de passe si nécessaire.",
        homebrewInstallHomebrew: "Installer Homebrew",
        homebrewInstallHomebrewCaption: "Quand Terminal a terminé, revenez ici et cliquez sur Actualiser.",
        homebrewInstallHomebrewOpened: "Installateur ouvert dans Terminal.",
        homebrewShellSetupTitle: "Finaliser la configuration de Terminal",
        homebrewShellSetupBody: "Homebrew est installé, mais Terminal peut ne pas encore trouver la commande brew. Vorssaint peut ouvrir Terminal avec la commande de configuration.",
        homebrewShellSetupButton: "Configurer Terminal",
        homebrewShellSetupOpened: "Commande ouverte dans Terminal. Revenez ensuite ici et cliquez sur Actualiser.",
        homebrewRefresh: "Actualiser",
        homebrewCheckPackages: "Vérifier les paquets",
        homebrewTrustTitle: "Tap pas encore approuvé",
        homebrewTrustCaption: "Homebrew demande désormais votre confirmation avant d’utiliser des taps tiers. Approuvez %@ pour continuer.",
        homebrewTrustButton: "Approuver et continuer",
        homebrewSearchPlaceholder: "Rechercher des paquets",
        homebrewKeyboardHint: "Espace ou Retour ferme le panneau macOS. Utilisez le bouton de recherche.",
        homebrewSearchButton: "Rechercher",
        homebrewSearchResults: "Résultats",
        homebrewInstalled: "Installés",
        homebrewAll: "Tous",
        homebrewFormulas: "Formules",
        homebrewCasks: "Casks",
        homebrewNoPackages: "Aucun paquet trouvé",
        homebrewNoSelection: "Sélectionnez un paquet installé ou recherchez-en un nouveau.",
        homebrewDetailsTitle: "Détails du paquet",
        homebrewInstall: "Installer",
        homebrewUninstall: "Désinstaller",
        homebrewUpgrade: "Mettre à jour",
        homebrewUpgradeAll: "Tout mettre à jour",
        homebrewUpdateHomebrew: "Mettre à jour Homebrew",
        homebrewAllPackages: "paquets",
        homebrewOpenTerminal: "Ouvrir Terminal",
        homebrewCancelOperation: "Annuler",
        homebrewClearLog: "Effacer le journal",
        homebrewLogTitle: "Journal",
        homebrewVersion: "Version",
        homebrewDescription: "Type",
        homebrewHomepage: "Ouvrir le site",
        homebrewPopularity: "Popularité",
        homebrewPopularityFormat: "%@ installations en %@ jours",
        homebrewInstalledBadge: "Installé",
        homebrewNotInstalledBadge: "Non installé",
        homebrewUpdates: "Mises à jour",
        homebrewUpdateAvailableBadge: "Mise à jour disponible",
        homebrewLatestVersion: "Dernière",
        homebrewConfirmInstallTitle: "Installer avec Homebrew\u{00A0}?",
        homebrewConfirmInstallBodyFormat: "Homebrew va télécharger et installer %@. Des dépendances peuvent aussi être installées.",
        homebrewConfirmUninstallTitle: "Désinstaller avec Homebrew\u{00A0}?",
        homebrewConfirmUninstallBodyFormat: "Homebrew va désinstaller %@. Des fichiers de configuration peuvent rester sur le système.",
        homebrewConfirmUpgradeTitle: "Mettre à jour avec Homebrew\u{00A0}?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew va télécharger et appliquer la dernière version de %@. Des dépendances peuvent aussi être mises à jour.",
        homebrewConfirmUpgradeAllTitle: "Tout mettre à jour avec Homebrew\u{00A0}?",
        homebrewConfirmUpgradeAllBody: "Homebrew va télécharger et appliquer les dernières versions des paquets avec une mise à jour disponible. Des dépendances peuvent aussi être mises à jour.",
        homebrewConfirmUpdateHomebrewTitle: "Mettre à jour Homebrew\u{00A0}?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew va récupérer les dernières informations puis recharger vos paquets.",
        homebrewTerminalFallback: "Cette opération nécessite Terminal pour demander le mot de passe administrateur. Vorssaint ne capture pas les mots de passe.",
        homebrewLoading: "Chargement…",
        homebrewSearchEmpty: "Aucun résultat",
        homebrewOperationInstallFormat: "Installation de %@",
        homebrewOperationUninstallFormat: "Désinstallation de %@",
        homebrewOperationUpgradeFormat: "Mise à jour de %@",
        homebrewOperationUpgradeAll: "Mise à jour des paquets",
        homebrewOperationUpdateHomebrew: "Mise à jour de Homebrew",
        homebrewOperationInstalledFormat: "%@ installé.",
        homebrewOperationUninstalledFormat: "%@ désinstallé.",
        homebrewOperationUpgradedFormat: "%@ mis à jour.",
        homebrewOperationUpgradedAll: "Paquets mis à jour.",
        homebrewOperationUpdatedHomebrew: "Homebrew mis à jour.",
        homebrewOperationFailedFormat: "Impossible de terminer %@.",
        homebrewOperationCancelled: "Opération annulée.",
        homebrewOperationPreparing: "Préparation…",
        homebrewOperationDownloading: "Téléchargement des fichiers…",
        homebrewOperationInstalling: "Installation des fichiers…",
        homebrewOperationUninstalling: "Suppression des fichiers…",
        homebrewOperationUpgrading: "Mise à jour des fichiers…",
        homebrewOperationFinalizing: "Finalisation…",
        homebrewOperationRefreshing: "Actualisation de la liste…",
        homebrewOperationTerminal: "Continuez dans Terminal.",
        homebrewOperationElapsedFormat: "%@ écoulés",
        homebrewOperationShowDetails: "Afficher les détails",
        homebrewOperationHideDetails: "Masquer les détails",
        homebrewOperationTechnicalLog: "Détails techniques",
        homebrewOperationProgressUnknown: "Homebrew n’a pas encore indiqué de pourcentage.",

        mediaName: "Médias",
        mediaEnableCaption: "Compressez les vidéos, convertissez et traitez les images, créez des GIFs et extrayez du texte localement.",
        mediaLocalNote: "Local. Sans réseau.",
        mediaToolVideo: "Vidéo",
        mediaToolGIF: "GIF",
        mediaToolImage: "Image",
        mediaToolText: "Texte",
        mediaSelectFile: "Choisir un fichier",
        mediaDropHint: "Déposez un fichier ici ou cliquez pour choisir.",
        mediaOutput: "Sortie",
        mediaOutputAutomatic: "Automatique",
        mediaChooseOutput: "Destination",
        mediaStartVideo: "Compresser la vidéo",
        mediaStartGIF: "Créer un GIF",
        mediaStartImage: "Traiter l’image",
        mediaStartConvertPDF: "Convertir en PDF",
        mediaStartText: "Extraire le texte",
        mediaCancel: "Annuler",
        mediaStartTime: "Début",
        mediaEndTime: "Fin",
        mediaQuality: "Compression",
        mediaCompressionLow: "Faible",
        mediaCompressionMedium: "Moyenne",
        mediaCompressionHigh: "Forte",
        mediaMaxSize: "Taille",
        mediaSizingResolution: "Résolution",
        mediaSizingFileSize: "Poids",
        mediaTargetSize: "Poids visé",
        mediaTargetSizeHint: "La résolution s’adapte pour rester sous la limite.",
        mediaErrorTargetTooSmall: "Poids visé trop bas pour ce clip. Raccourcissez-le ou augmentez la limite.",
        mediaMegabytesSuffix: " Mo",
        mediaWidth: "Largeur",
        mediaFPS: "FPS",
        mediaKeepAudio: "Garder l’audio",
        mediaCodec: "Codec",
        mediaFormat: "Format",
        mediaStripMetadata: "Supprimer les métadonnées",
        mediaLoopGIF: "Boucler le GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Précis",
        mediaOCRFast: "Rapide",
        mediaLanguageCorrection: "Correction de langue",
        mediaTextOutputNote: "Le texte extrait peut être copié et enregistré en TXT.",
        mediaRunning: "Traitement",
        mediaCompleted: "Terminé",
        mediaCancelled: "Annulé.",
        mediaOpenInFinder: "Afficher",
        mediaCopyText: "Copier le texte",
        mediaRunAgain: "Relancer",
        mediaEmptyText: "Aucun texte trouvé.",
        mediaResultSavedFormat: "Enregistré sous %@",
        mediaResultSizeFormat: "%@ vers %@",
        mediaResultGrewCaption: "Le fichier converti est plus volumineux que l’original.",
        mediaErrorNoFile: "Choisissez d’abord un fichier.",
        mediaErrorNoVideo: "Ce fichier ne contient pas de piste vidéo.",
        mediaErrorSameOutput: "Choisissez une destination différente du fichier original.",
        mediaErrorUnsupported: "Format non pris en charge par macOS.",

        shelfName: "Étagère",
        shelfEnable: "Espace temporaire pour glisser des fichiers",
        shelfEnableCaption: "Un espace flottant pour rassembler fichiers, images et texte, puis les glisser ailleurs plus tard.",
        shelfHowTitle: "Comment l’utiliser",
        shelfStep1: "Ouvrez-la avec le raccourci, ou en secouant la souris pendant un glissement.",
        shelfStep2: "Déposez-y des fichiers, des images, des liens ou du texte pour les conserver.",
        shelfStep3: "Glissez chaque élément vers n’importe quelle app au moment voulu.",
        shelfShakeToggle: "Ouvrir en secouant la souris pendant un glissement",
        shelfShakeCaption: "Secouez rapidement le pointeur tout en tenant un élément pour faire apparaître l’étagère près du curseur.",
        shelfDropZoneToggle: "Garder les fichiers glissés dans la barre des menus",
        shelfDropZoneCaption: "Pendant que vous faites glisser un fichier, l’étagère apparaît sous l’icône de la barre des menus. Ce que vous déposez y reste, dans un bouton que vous réduisez et ouvrez d’un clic et qui disparaît une fois l’étagère vide.",
        shelfDropZoneLabel: "Déposez ici",
        shelfCollapse: "Réduire",
        shelfBehaviorTitle: "Après utilisation",
        shelfCloseAfterDrop: "Fermer après un dépôt dans une autre app",
        shelfCloseAfterDropCaption: "Ferme l’étagère quand la destination accepte les éléments. L’épingle du panneau la maintient ouverte.",
        shelfRemoveAfterDrop: "Retirer les éléments après le dépôt",
        shelfRemoveAfterDropCaption: "Les éléments acceptés par une autre app quittent l’étagère. Désactivez cette option pour en garder une copie.",
        shelfExclusionsTitle: "Exceptions automatiques",
        shelfExclusionsEmpty: "Aucune app ajoutée.",
        shelfExclusionsCaption: "Le geste de secousse et la zone de dépôt restent inactifs pour les glissements commencés dans ces apps. Le raccourci et Ouvrir restent disponibles.",
        shelfPin: "Maintenir ouverte",
        shelfUnpin: "Autoriser la fermeture après utilisation",
        extraBrightnessName: "Luminosité extra",
        extraBrightnessCaption: "Utilise la réserve HDR de l’écran pour dépasser la luminosité maximale. Consomme plus de batterie et le Mac peut chauffer.",
        extraBrightnessLevelLabel: "Intensité",
        extraBrightnessUnsupported: "Disponible uniquement sur les écrans XDR, comme ceux des MacBook Pro 14 et 16 pouces.",
        shelfHotkeyLabel: "Raccourci",
        shelfOpenNow: "Ouvrir maintenant",
        shelfNoPermission: "Ne nécessite aucune autorisation.",
        shelfMenuItem: "Ouvrir l’étagère",
        shelfTitle: "Étagère",
        shelfEmpty: "Glissez des éléments ici",
        shelfClearAll: "Tout effacer",
        shelfRemoveSelected: "Retirer la sélection",
        shelfSelectedFormat: "%d sélectionnés",
        shelfHint: "Cliquez pour sélectionner. Glissez pour utiliser ou faites un clic droit pour plus d’actions.",
        shelfItemImage: "Image",
        shelfTooltipItemsFormat: "%d éléments",
        shelfTooltipItemsFew: "%d éléments",
        shelfTooltipImageSingular: "%d image",
        shelfTooltipImageFew: "%d images",
        shelfTooltipImagePlural: "%d images",
        shelfTooltipFileSingular: "%d fichier",
        shelfTooltipFileFew: "%d fichiers",
        shelfTooltipFilePlural: "%d fichiers",
        shelfTooltipNoteSingular: "%d note",
        shelfTooltipNoteFew: "%d notes",
        shelfTooltipNotePlural: "%d notes",
        shelfTooltipLinkSingular: "%d lien",
        shelfTooltipLinkFew: "%d liens",
        shelfTooltipLinkPlural: "%d liens",
        shelfActionOpen: "Ouvrir",
        shelfActionOpenWith: "Ouvrir avec",
        shelfActionShare: "Partager",

        breakdownMeasuring: "Mesure…",

        mixerSection: "Mélangeur de volume",
        mixerEmpty: "Les apps qui utilisent l’audio apparaissent ici",
        mixerUnavailable: "Disponible à partir de macOS 14.4",
        mixerPermissionBody: "Pour régler le volume par app, autorisez «\u{00A0}Enregistrement de l’écran et de l’audio du système\u{00A0}» dans les Réglages Système. L’audio n’est jamais enregistré.",
        mixerResetTooltip: "Rétablir à 100 %",
        mixerOutputDefault: "Par défaut",
        mixerOutputCurrent: "actuelle",
        mixerOutputUnavailable: "Sortie indisponible",
        mixerOutputFallback: "Utilise la sortie par défaut jusqu’au retour de cet appareil.",
        mixerBypassedCaption: "Cette app gère elle-même son audio.",
        mixerOutputTooltip: "Choisir la sortie",
        mixerSystemOutputTitle: "Sortie",
        mixerSystemOutputNoDevices: "Aucune sortie trouvée",
        mixerSystemOutputTooltip: "Choisir la sortie système",
        mixerSystemOutputErrorFormat: "Impossible de changer\u{00A0}: %@",
        mixerLowerOnHeadphonesDisconnect: "Baisser le volume quand les écouteurs se déconnectent",
        mixerLowerOnHeadphonesDisconnectCaption: "Ajuste la sortie quand des écouteurs filaires ou Bluetooth se déconnectent.",
        mixerHeadphonesDisconnectVolume: "Volume après déconnexion",
        preciseVolumeRollerEnable: "Utiliser des pas de volume plus fins",
        preciseVolumeRollerCaption: "Transforme molettes et touches de volume en pas système plus petits.",
        preciseVolumeRollerTapFailed: "Impossible d’écouter les touches de volume.",
        soundOutputSwitcherTitle: "Sélecteur de sortie",
        soundOutputSwitcherEnable: "Changer de sortie avec un raccourci",
        soundOutputSwitcherCaption: "Choisissez les sorties et utilisez le raccourci pour passer à la suivante disponible.",
        soundOutputSwitcherDevices: "Sorties du cycle",
        soundOutputSwitcherNoAvailableSelection: "Sélectionnez au moins une sortie disponible.",
        mixerInputTitle: "Micro",
        mixerInputNoDevices: "Aucun micro trouvé",
        mixerInputUnavailable: "Micro indisponible",
        mixerInputFallback: "Utilise le micro par défaut jusqu’au retour de celui-ci.",
        mixerInputTooltip: "Choisir le micro",
        mixerInputErrorFormat: "Impossible de changer\u{00A0}: %@",
        mixerVisibleApps: "Apps dans la liste",
        mixerAllShown: "Toutes",
        mixerHiddenCountLabel: "Masquées",
        mixerHideFromList: "Masquer de la liste",

        updatesSection: "Mises à jour",
        autoCheckToggle: "Rechercher les mises à jour automatiquement",
        includeBetaUpdatesToggle: "Recevoir les mises à jour bêta",
        includeBetaUpdatesCaption: "Les versions bêta incluent des fonctionnalités en cours de développement et peuvent présenter des instabilités.",
        betaBadgeLabel: "Bêta",
        checkNowButton: "Rechercher maintenant",
        updateChecking: "Recherche…",
        updateUpToDate: "Vous disposez de la dernière version.",
        updateAvailablePrefix: "Mise à jour disponible\u{00A0}:",
        updateInstallButton: "Télécharger et installer",
        updateDownloading: "Téléchargement de la mise à jour…",
        updateInstalling: "Installation et redémarrage…",
        updateFailedPrefix: "Recherche impossible\u{00A0}:",
        updateLastChecked: "Dernière recherche\u{00A0}:",
        updateNotifyTitle: "Mise à jour de Vorssaint",
        updateInstallFailedBody: "La mise à jour a été téléchargée mais n’a pas pu être appliquée. Téléchargez la dernière version depuis la page des releases GitHub et faites glisser l’app par-dessus l’actuelle.",
        updateNeedsApplicationsTitle: "Déplacez Vorssaint vers Applications",
        updateNeedsApplicationsBody: "L’app s’exécute depuis un emplacement qui ne peut pas être mis à jour, comme l’image disque ou un emplacement temporaire du système. Faites glisser Vorssaint dans le dossier Applications, ouvrez-le depuis là et réessayez.",
        menuCheckUpdates: "Rechercher les mises à jour…",

        permissionRequired: "Autorisation requise",
        permissionAccessibility: "Accessibilité",
        permissionScreenRecording: "Enregistrement de l’écran",
        permissionGranted: "Accordée",
        permissionMissing: "Non accordée",
        permissionOpenSettings: "Ouvrir les Réglages Système…",
        permissionRequest: "Accorder l’accès",
        permissionRestartNote: "macOS peut demander de rouvrir l’app après l’avoir accordée.",

        aboutDescription: "Un centre d’utilitaires pour votre Mac.\nÉnergie, moniteur système, défilement et sélecteur de fenêtres, directement dans la barre des menus.",
        versionPrefix: "Version",
        reviewIntro: "Revoir l’introduction",
        reviewHighlights: "Revoir les nouveautés",
        viewOnGitHub: "Voir sur GitHub",

        obContinue: "Continuer",
        obBack: "Retour",
        obSkipStep: "Passer cette étape",
        obStart: "Ouvrir Vorssaint",
        obStepWelcomeTitle: "Bienvenue dans Vorssaint",
        obStepWelcomeBody: "Un utilitaire discret dans la barre des menus qui rend macOS plus pratique au quotidien.",
        obWelcomeBullet1Title: "Énergie maîtrisée",
        obWelcomeBullet1Body: "Gardez le Mac éveillé aussi longtemps que vous le souhaitez, même écran rabattu.",
        obWelcomeBullet2Title: "Une vue claire du système",
        obWelcomeBullet2Body: "Températures du CPU, du GPU et de la batterie, utilisation du matériel et pression de la mémoire en temps réel.",
        obWelcomeBullet3Title: "Souris et fenêtres à votre façon",
        obWelcomeBullet3Body: "Défilement de souris inversé et un sélecteur de fenêtres avec miniatures.",
        obLanguageLabel: "Langue",
        obStepAccessibilityTitle: "Accessibilité",
        obStepAccessibilityBody: "Nécessaire pour inverser le défilement de la souris et pour que le sélecteur de fenêtres réponde au clavier.",
        obAccessibilityWhy: "L’app observe seulement la molette de la souris et le raccourci du sélecteur. Rien n’est enregistré ni envoyé où que ce soit.",
        obStepRecordingTitle: "Enregistrement de l’écran",
        obStepRecordingBody: "Permet au sélecteur d’afficher de vraies miniatures de fenêtres au lieu des seules icônes.",
        obRecordingWhy: "Les miniatures sont générées à la volée, restent en mémoire et ne quittent jamais votre Mac. Sans cela, le sélecteur fonctionne tout de même avec des icônes.",
        obStepMonitorTitle: "Moniteur système",
        obStepMonitorBody: "Le panneau affiche les températures du CPU, du GPU et de la batterie, l’utilisation du matériel et la pression de la mémoire.",
        obMonitorNoPermission: "Aucune autorisation nécessaire. Les capteurs sont lus directement depuis le système.",
        obStepOptionalTitle: "Fonctionnalités optionnelles",
        obStepOptionalBody: "Activez maintenant ce que vous voulez utiliser. Tout peut être modifié plus tard dans les Réglages.",
        obStepStatusTitle: "Vérification",
        obStepStatusBody: "Assurez-vous que tout est prêt pour les fonctionnalités que vous voulez utiliser.",
        obStatusRecheck: "Vérifier à nouveau",
        obStepDoneTitle: "Tout est prêt\u{00A0}!",
        obStepDoneBody: "Vorssaint veille déjà sur votre Mac.",
        obDoneHint: "Cherchez le trou noir dans la barre des menus, en haut à droite de l’écran.",
        obWhatsNewTitle: "Nouveautés de cette version",
        obWhatsNewFallback: "Cette mise à jour inclut les derniers correctifs et améliorations.",
        obLanguageUpdateTitle: "Maintenant dans votre langue",
        obLanguageUpdateBody: "Vorssaint parle désormais plusieurs langues. Choisissez celle que vous voulez utiliser\u{00A0}; vous pouvez en changer à tout moment dans les Réglages.",
        obPurposeTitle: "Qu’est-ce qui vous amène\u{00A0}?",
        obPurposeBody: "Choisissez une configuration prête ou exactement les fonctions à utiliser.",
        obPurposeSkip: "Vous pourrez ajouter ou retirer des fonctions dans les Réglages.",

        tabMonitor: "Moniteur",
        monitorMenuBarSection: "Dans la barre des menus",
        monitorMenuBarCaption: "Choisissez ce qui apparaît à côté de l’icône dans la barre des menus.",
        monitorCombineTemperatures: "Combiner utilisation et température",
        monitorCombineTemperaturesCaption: "Quand l’utilisation et la température du même élément sont activées, elles s’affichent dans un seul bloc.",
        monitorSeparateMenuBarMetrics: "Séparer les mesures en éléments dédiés",
        monitorSeparateMenuBarMetricsCaption: "Sépare les blocs actifs dans la barre des menus et garde utilisation et température ensemble quand combiner est actif.",
        monitorNetworkUploadFirst: "Envoi au-dessus du téléchargement",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Mémoire",
        monitorShowNetwork: "Réseau",
        monitorShowPowerLabel: "Énergie",
        monitorIntervalLabel: "Actualiser toutes les",
        monitorInterval1: "1 seconde",
        monitorInterval2: "2 secondes",
        monitorInterval5: "5 secondes",
        monitorPanelSection: "Dans le panneau",
        panelNavigationMode: "Naviguer par sections dans le panneau",
        panelNavigationCaption: "Affiche une section à la fois. Choisissez Liste pour tout voir dans un défilement continu.",
        panelFooterSections: "Sections",
        panelFooterList: "Liste",
        betaBadge: "BETA",
        betaFeatureWarning: "Bêta. Vous pouvez rencontrer quelques bugs.",

        networkSection: "Réseau",
        networkDownload: "Téléchargement",
        networkUpload: "Envoi",
        networkThisSession: "Cette session",
        networkMeasuring: "Mesure…",
        networkApps: "Apps utilisant le réseau",
        networkAppsIdle: "Aucune app n’utilise le réseau",

        diskSection: "Disques",
        diskUsed: "utilisé",
        diskFree: "libre",
        diskAvailable: "disponible",
        diskPurgeable: "purgeable",
        diskInternal: "Interne",
        diskExternal: "Externe",
        diskSelect: "Choisir un disque",
        diskRead: "Lecture",
        diskWrite: "Écriture",
        diskSMARTStatus: "État",
        diskSMARTUnavailable: "SMART indisponible pour ce disque",
        diskTotalRead: "Total lu",
        diskTotalWritten: "Total écrit",
        diskTemperature: "Température",
        diskHealth: "Santé",
        diskPowerCycles: "Cycles",
        diskPowerOnHours: "Heures allumé",
        diskUnsafeShutdowns: "Arrêts non sûrs",
        diskMediaErrors: "Erreurs média",
        diskEject: "Éjecter",
        diskEjectAll: "Tout éjecter",
        diskEjecting: "Éjection…",
        diskReadyToRemove: "Prêt à retirer",
        diskEjectFailed: "Impossible d’éjecter",
        diskProtectionCaption: "Éjectez avant de débrancher.",
        diskNoExternal: "Aucun disque externe prêt à être éjecté.",
        diskOpenInFinder: "Ouvrir",
        diskStorageSettings: "Stockage",
        diskNoDisks: "Aucun disque monté trouvé.",

        powerSection: "Énergie",
        powerSystem: "Système",
        powerAdapter: "Adaptateur",
        powerBattery: "Batterie",
        powerCharging: "En charge",
        powerOnBattery: "Sur batterie",
        powerPluggedIn: "Branché",
        powerUnavailable: "Mesures d’énergie indisponibles sur ce Mac",
        powerAdapterMaxFormat: "%@ max",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Température CPU",
        monitorShowGPUTemperature: "Température GPU",
        monitorShowBatteryTemperature: "Température batterie",
        monitorShowPeripheralBattery: "Batterie des périphériques",
        peripheralBatteryNoDevices: "Aucun périphérique trouvé",
        monitorGraphsSection: "Graphiques",
        monitorGraphsCaption: "Choisissez quelles mesures affichent un graphique dans le temps.",

        updateBannerTitle: "Mise à jour disponible",
        updateBannerAction: "Mettre à jour",
        obStepMenuBarTitle: "Mesures dans la barre des menus",
        obStepMenuBarBody: "Choisissez ce qui s’affiche à côté de l’icône. L’aperçu ci-dessus se met à jour en direct.",
        obStepMenuBarNote: "Nouveau\u{00A0}: blocs Réseau et Énergie et graphiques dans le panneau. Ajustez le tout plus tard dans Réglages › Moniteur.",
        monitorMenuBarPresetLabel: "Style",
        menuBarPresetReadable: "Lisible",
        menuBarPresetDense: "Dense",
        menuBarSpacingLabel: "Espacement dans la barre",
        menuBarSpacingStandard: "Standard",
        menuBarSpacingCompact: "Compact",
        menuBarHideIconToggle: "Masquer l’icône de l’app quand des métriques sont affichées",
        menuBarHideIconCaption: "L’icône revient d’elle-même quand les métriques quittent la barre et quand il y a quelque chose à signaler (une mise à jour prête ou le micro coupé).",
        monitorLabelStyleLabel: "Libellés",
        menuBarLabelStyleCompact: "Compacts",
        menuBarLabelStyleClassic: "Classiques",
        monitorMemoryStyleLabel: "Afficher la mémoire en",
        monitorMemoryPressureDot: "Point de pression",
        memoryStyleDot: "Point",
        memoryStylePercent: "%",
        memoryStyleBoth: "Les deux",
        systemUptime: "Actif depuis",
        batteryCharge: "Charge",
        powerHealth: "État de la batterie",
        powerCycles: "Cycles",
        speedTestRun: "Test de débit",
        speedTestAgain: "Tester à nouveau",
        speedTestLatency: "Latence",
        speedTestTesting: "Test en cours…",
        speedTestFailed: "Échec du test",

        monitorShowInPanel: "Afficher dans le panneau",
        disclosureExpanded: "Développé",
        disclosureCollapsed: "Réduit",
        panelHideItem: "Masquer du panneau",
        panelShowItem: "Afficher dans le panneau",
        panelHiddenItem: "Masqué",
        monitorItemUptime: "Durée d’activité",
        monitorItemNetSpeed: "Débit en direct",
        monitorItemNetTotals: "Totaux de la session",
        monitorItemNetTest: "Test de débit",
        monitorItemDiskUsage: "Utilisation du disque",
        monitorItemDiskActivity: "Activité en direct",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Protection externe",
        monitorItemDiskTools: "Outils",
        monitorPanelConfigHint: "Ouvrez un bloc pour choisir ce qu’il affiche.",
        monitorOrderSection: "Ordre des sections",
        monitorOrderHint: "Glissez pour réordonner les sections du panneau et utilisez l’œil pour afficher ou masquer chacune.",
        obStepPanelTitle: "Ce qui s’affiche dans le panneau",
        obStepPanelBody: "Ouvrez chaque bloc et choisissez exactement ce qui s’affiche quand vous cliquez sur l’icône.",
        obStepPanelNavigationTitle: "Panneau par sections",
        obStepPanelNavigationBody: "Le panneau peut maintenant afficher une section à la fois. Vous pouvez passer de Sections à Liste dans les réglages.",

        cleaningMenuItem: "Mode nettoyage",
        utilitiesSection: "Utilitaires",
        quickControlsSection: "Contrôles",
        panelCategoryWindows: "Fenêtres",
        panelCategoryInput: "Souris et clavier",
        panelCategoryFiles: "Fichiers",
        windowMaximizeName: "Maximiser les fenêtres",
        windowMaximizeCaption: "Le bouton vert maximise sans créer un autre Espace.",
        windowMaximizeActiveNow: "Bouton vert actif",
        windowMaximizeNeedsAccessibility: "Nécessite l’Accessibilité pour fonctionner.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Filtrer les touches doublées",
        keyDebounceCaption: "Filtre les touches doublées très rapides.",
        keyDebounceActiveNow: "Filtre actif",
        keyDebounceGlobalWindow: "Fenêtre globale",
        keyDebouncePerKeySection: "Touches spécifiques",
        keyDebouncePerKeyCaption: "Les valeurs par touche remplacent la fenêtre globale. Utilisez 0 ms pour ne pas filtrer une touche.",
        keyDebounceKeyLabel: "Touche",
        keyDebounceWindowLabel: "Fenêtre",
        keyDebounceAddKey: "Ajouter une touche",
        keyDebounceNoOverrides: "Aucune touche spécifique configurée.",
        keyDebounceRemoveKey: "Supprimer la touche",
        cleaningPanelCaption: "Verrouille le clavier pour nettoyer en sécurité.",
        cleaningOverlayTitle: "Clavier verrouillé pour le nettoyage",
        cleaningOverlaySubtitle: "Appuyez 5 fois sur Échap pour déverrouiller",
        cleaningOverlayUnlock: "Déverrouiller",
        cleaningOverlayMouseHint: "Votre souris et votre trackpad fonctionnent toujours",
        cleaningKeepScreenVisibleToggle: "Garder l’écran visible",
        cleaningKeepScreenVisibleCaption: "Affiche un indicateur discret dans un coin de l’écran sans masquer le contenu.",
        cleaningStartNow: "Verrouiller le clavier maintenant",
        cleaningNeedsAxTitle: "Accessibilité requise",
        cleaningNeedsAxBody: "Pour verrouiller le clavier en toute sécurité, Vorssaint a besoin de l’autorisation Accessibilité. Accordez-la dans les Réglages Système et réessayez.",

        tabSupport: "Soutenir",
        shortcutsPageCaption: "Modifiez ici tous les raccourcis globaux des fonctions installées sur ce Mac. Les raccourcis inactifs restent enregistrés sans se déclencher.",
        shortcutsPageTitle: "Raccourcis clavier",
        settingsSearchPlaceholder: "Rechercher dans les réglages",
        donateHeading: "Aidez Vorssaint à continuer de grandir",
        donateMessage: "Vorssaint est gratuit, indépendant et développé pendant mon temps libre. Si vous souhaitez contribuer financièrement, Buy Me a Coffee aide directement à poursuivre son développement.",
        donateButton: "Soutenir sur Buy Me a Coffee",
        donateThanks: "Merci d’être là. 🖤",
        supportIntroTitle: "Aidez Vorssaint à continuer de grandir",
        supportIntroMessage: "Si vous souhaitez soutenir financièrement le développement, Buy Me a Coffee est l’unique endroit pour le faire.",
        supportIntroStarButton: "Ajouter une étoile à Vorssaint sur GitHub",
        supportIntroStarMessage: "Un soutien financier n’est jamais attendu. Une étoile sur GitHub aide davantage de personnes à découvrir Vorssaint et fait une vraie différence pour son développement.",
        supportIntroCoffeeButton: "Soutenir sur Buy Me a Coffee",
        supportIntroLaterButton: "Pas maintenant",
        supportIntroDoneButton: "Terminer",
        discordIntroTitle: "La communauté Vorssaint sur Discord ne fait que commencer",
        discordIntroMessage: "La communauté Vorssaint est nouvelle et se construit encore. Rejoignez-la dès maintenant pour rencontrer d’autres utilisateurs et créer un espace accueillant autour de l’app.",
        discordIntroJoinButton: "Rejoindre la communauté sur Discord",
        communityIntroTitle: "Voyez tout avant tout le monde",
        communityIntroMessage: "Les personnes qui me suivaient déjà sur X ont découvert plusieurs changements de cette mise à jour avant tout le monde. J’y publie des aperçus des prochaines nouveautés et montre leur fonctionnement, pour que vous connaissiez déjà l’essentiel avant leur sortie. Suivez-moi pour voir la suite\u{00A0}!",
        communityIntroFollowButton: "Suivre @vorssaint sur X",
        homebrewOfficialIntroTitle: "Maintenant dans le catalogue officiel de Homebrew",
        homebrewOfficialIntroMessage: "Vorssaint peut maintenant être installé directement depuis le catalogue officiel de Homebrew.",
        homebrewOfficialIntroInstallLabel: "Nouvelle installation",
        homebrewOfficialIntroMigrationTitle: "Vous utilisiez l’ancien tap\u{00A0}?",
        homebrewOfficialIntroMigrationMessage: "Supprimez l’ancien tap une fois. L’app et vos réglages restent en place.",
        homebrewOfficialIntroCopyButton: "Copier la commande",
        updateShowcaseTitle: "Nouveautés de la 3.1.4",
        updateShowcaseMessage: "Découvrez rapidement les principales améliorations de cette mise à jour.",
        updateShowcaseUnavailable: "La vidéo n’a pas pu se charger maintenant. Vous pouvez quand même continuer.",
        updateShowcaseRestart: "Revenir au début",
        showMenuBarIcon: "Afficher l’icône dans la barre des menus",
        showMenuBarIconCaption: "Si l’icône de Vorssaint disparaît (macOS peut masquer des icônes lorsque la barre des menus manque de place, fréquent sur les Mac avec encoche), rouvrez Vorssaint depuis Applications ou Spotlight\u{00A0}: cela recrée l’icône et, si elle reste masquée, ouvre cette fenêtre.",
        menuBarIconStillHiddenTitle: "L’icône est toujours masquée",
        menuBarIconStillHiddenBody: "L’icône a été reconstruite, mais macOS ne lui a pas donné de place visible. La barre des menus manque probablement d’espace\u{00A0}: retirez quelques icônes de la barre (ou fermez les apps aux menus longs) et réessayez.",
        menuBarIconManagerHintFormat: "%@ est ouvert et garde peut-être l’icône dans sa section masquée. Cherchez Vorssaint là-bas, ou réglez %@ pour toujours afficher Vorssaint.",
        shortcutRecording: "Appuyez sur le nouveau raccourci",
        shortcutReset: "Réinitialiser",
        shortcutNone: "Aucun",
        shortcutClear: "Supprimer le raccourci",
        shortcutInvalid: "Utilisez au moins Control, Option ou Command avec une touche.",
        shortcutPressKeys: "Appuyez",
        shortcutEscapeHint: "Esc annule.",
        shortcutDeleteHint: "Delete efface.",
        shortcutNotCaptured: "Rien n’a été capturé. macOS ou une autre app utilise déjà cette combinaison. Essayez-en une autre.",
        shortcutConflictFormat: "Ce raccourci est déjà utilisé par %@.",
        shortcutUnavailable: "macOS a refusé ce raccourci. Choisissez-en un autre.",
        shelfShortcutToggle: "Raccourci Shelf",
        switcherUsageHintFormat: "Maintenez %@ pour naviguer\u{00A0}; relâchez pour activer la fenêtre. Maj ou ← revient en arrière\u{00A0}; W ferme la fenêtre\u{00A0}; Q quitte l’app\u{00A0}; Échap annule.",
        musicBlockSection: "Touches multimédias",
        musicBlockTitle: "Empêcher Musique de s’ouvrir toute seule",
        musicBlockCaption: "L’app Musique ne s’ouvre plus quand vous appuyez sur les touches multimédias. Vous pouvez toujours l’ouvrir vous-même.",
        musicBlockReplacementLabel: "Ouvrir à la place",
        musicBlockReplacementNone: "Aucune",
        musicBlockChooseApp: "Choisir une app…",
        cleanerName: "Nettoyage",
        cleanerIntroTitle: "Nettoyez votre Mac",
        cleanerIntroCaption: "Recherche les restes d’apps désinstallées, les caches, les journaux et la corbeille. Vous vérifiez tout avant et les éléments retirés vont à la corbeille.",
        cleanerScan: "Analyser",
        cleanerScanning: "Analyse…",
        cleanerCleaning: "Nettoyage…",
        cleanerCatLeftovers: "Restes d’apps désinstallées",
        cleanerCatLoginItems: "Éléments de démarrage orphelins",
        cleanerCatCaches: "Caches",
        cleanerCatLogs: "Journaux",
        cleanerCatDeveloper: "Données de développement",
        cleanerCatTrash: "Corbeille",
        cleanerLeftoversNote: "Trouvés par analyse et non cochés. Vérifiez le chemin avant de cocher.",
        cleanerLoginItemsNote: "L’entrée dans Éléments de connexion disparaît après un redémarrage.",
        cleanerTrashNote: "Vider la corbeille est définitif.",
        cleanerCatDeviceBackups: "Sauvegardes iPhone",
        cleanerDeviceBackupsCaption: "Les anciennes sauvegardes d’iPhone et d’iPad occupent une grande part du stockage que macOS appelle Autre. Ne supprimez que celles devenues inutiles\u{00A0}; une nouvelle est créée au prochain branchement.",
        cleanerNothingFound: "Rien à nettoyer. Votre Mac est en ordre.",
        cleanerClean: "Nettoyer",
        cleanerDoneNote: "Les éléments sont dans la corbeille et peuvent y être récupérés.",
        cleanerAgain: "Analyser à nouveau",
        cleanerRevealInFinder: "Afficher dans le Finder",
        cleanerPanelCaption: "Restes d’apps, caches et journaux",
        cleanerSafeSection: "Nettoyage sûr",
        cleanerOptionalSection: "Facultatif, vérifiez d’abord",
        cleanerCatOtherCaches: "Autres caches",
        cleanerCachesCaption: "Fichiers temporaires que les apps recréent seules.",
        cleanerLogsCaption: "Anciens journaux de diagnostic.",
        cleanerDeveloperCaption: "Restes de compilations et de simulateurs Xcode.",
        cleanerLoginItemsCaption: "Entrées de démarrage laissées par des apps qui n’existent plus.",
        cleanerLeftoversCaption: "Fichiers laissés par des apps désinstallées.",
        cleanerOtherCachesCaption: "Suppression sûre, rien ne casse. Les apps peuvent ouvrir plus lentement une fois et le contenu téléchargé, comme la musique hors ligne, se retélécharge.",
        cleanerCleanSizeFormat: "Nettoyer %@",
        cleanerScheduleTitle: "Nettoyage automatique",
        cleanerScheduleOff: "Désactivé",
        cleanerScheduleDaily: "Quotidien",
        cleanerScheduleWeekly: "Hebdomadaire",
        cleanerScheduleCaption: "Nettoie seul uniquement la partie sûre à l’heure choisie et envoie tout à la corbeille.",
        cleanerScheduleLastFormat: "Le dernier nettoyage automatique a libéré %@.",
        cleanerAutoNotificationFormat: "%@ libérés et envoyés à la corbeille.",
        cleanerScheduleNextFormat: "Prochain nettoyage %@.",
        cleanerScheduleRanFormat: "Dernier nettoyage automatique %@.",
        cleanerScheduleNotifyToggle: "Prévenir à la fin",
        cleanerNotifDenied: "Les notifications de Vorssaint sont désactivées dans le système.",
        cleanerNotifOpenSettings: "Ouvrir les réglages de notifications…",
        launchAtLoginNeedsApplications: "L’app s’exécute depuis un emplacement qui ne permet pas l’ouverture à la connexion. Glissez Vorssaint dans le dossier Applications, ouvrez l’app depuis ce dossier et réactivez l’option.",
        launchAtLoginNeedsApproval: "L’élément d’ouverture est enregistré, mais il reste désactivé dans les Réglages Système. Ouvrez Réglages Système › Général › Ouverture et extensions, puis activez Vorssaint sous «\u{00A0}Ouvrir à la session\u{00A0}».",
        ocrRemoveLineBreaksToggle: "Supprimer les sauts de ligne",
        ocrRemoveLineBreaksCaption: "Supprime les sauts de ligne afin que le texte copié soit collé en un seul paragraphe.",
        ocrQRToggle: "Lire les codes QR",
        ocrQRCaption: "Si la zone contient un code QR, son contenu s’affiche pour le copier ou l’ouvrir.",
        ocrQRCopied: "Code QR copié",
        qrResultTitle: "Code QR",
        qrResultCopy: "Copier",
        qrResultOpen: "Ouvrir le lien",
        highlightsTitle: "Nouveautés de cette mise à jour",
        highlightsTitleClipboardRedesign: "Presse-papiers repensé",
        highlightsTitleWindowLayout: "Disposition des fenêtres",
        highlightsTitleQuitProtection: "Protection de ⌘Q et ⌘W",
        highlightsTitleRecorderBlur: "Flou de confidentialité vidéo",
        highlightsCaptionDockPreview: "Dock Preview fonctionne désormais avec l’agrandissement du Dock activé",
        highlightsCaptionScreenshot: "L’outil de capture d’écran gagne une loupe de pixels et la lecture des codes QR",
        highlightsCaptionSnippetLibrary: "Un menu d’extraits avec recherche tape n’importe quel extrait au curseur",
        highlightsCaptionCapturePalette: "Un seul raccourci ouvre désormais une palette flottante pour les captures d’écran, les enregistrements, le texte et les couleurs avec les réglages à portée de main.",
        highlightsCaptionClipboardRedesign: "L’historique s’ouvre désormais sous la forme d’une palette compacte aux lignes épurées, avec un aperçu à la demande pour lire ou modifier l’élément complet.",
        highlightsCaptionWindowLayout: "Placez les fenêtres avec l’anneau directionnel via un raccourci et le pointeur, ou glissez vers les bords de l’écran pour aligner avec des marges réglables.",
        highlightsCaptionQuitProtection: "Évitez de quitter des apps ou fermer des fenêtres par erreur en maintenant la touche, en appuyant deux fois ou avec un modificateur supplémentaire, par app.",
        highlightsCaptionRecorderBlur: "Masquez des données sensibles, mots de passe et détails privés sur n’importe quelle section de votre enregistrement avant de l’exporter.",
        highlightsConfigure: "Configurer",
        highlightsTry: "Essayer",
        highlightsSeeAll: "Voir tous les changements",
        switcherCurrentSpaceOnly: "Afficher uniquement le bureau actuel",
        switcherCurrentSpaceOnlyCaption: "N’affiche dans le sélecteur que les fenêtres du bureau où vous êtes. Choisir une fenêtre ne vous emmène jamais sur un autre bureau.",
        shelfFileMissing: "Le fichier n’existe plus",
        previewSizeSmall: "Petite",
        mixerSoundEffectsOutputTitle: "Sons du système",
        mixerSoundEffectsOutputTooltip: "Choisir où sont diffusés les alertes et effets sonores",
        monitorOpenActivityMonitor: "Ouvrir le Moniteur d’activité",
        dockClickHide: "Masquer l’app d’un clic sur le Dock",
        dockClickHideCaption: "L’app active se masque lorsque vous cliquez sur son icône dans le Dock. Cliquez à nouveau pour la faire revenir.",
        monitorMemoryMetricLabel: "Mesurer la mémoire comme",
        memoryMetricUsed: "Mémoire utilisée",
        memoryMetricApp: "Mémoire des apps",
        keepAwakeRightClickToggle: "Faire un clic droit sur l’icône de la barre des menus pour basculer «\u{00A0}Garder éveillé\u{00A0}»",
        keepAwakeRightClickToggleCaption: "Remplace le menu contextuel du clic droit.",
        urlCleanerRulesTitle: "Règles de nettoyage",
        urlCleanerRulesCaption: "Un site ajoute ces paramètres à ses propres liens de partage pour savoir d’où vient le lien. Coché, le nom est retiré lors du nettoyage\u{00A0}; décoché, il reste. Les noms que vous ajoutez peuvent être supprimés.",
        urlCleanerRulesCoverageCaption: "La liste couvre les différents chemins de partage d’un site (la page web, l’app, un direct), d’où sa longueur\u{00A0}; un vrai lien n’en porte généralement que deux à quatre.",
        urlCleanerRulesAllSites: "Tous les sites",
        urlCleanerRulesCountSingular: "1 paramètre",
        urlCleanerRulesCountPluralFormat: "%d paramètres",
        urlCleanerRulesAddSite: "Ajouter un site",
        urlCleanerRulesParameterPlaceholder: "Nom du paramètre",
        urlCleanerRulesMatchCaption: "Saisissez le nom à gauche du = , par exemple utm_source. Un nom qui correspond retire ce seul paramètre du lien et laisse le reste tel quel.",
        urlCleanerRulesAddButton: "Ajouter",
        urlCleanerRulesRemoveButton: "Supprimer le nom",
        urlCleanerRulesRemoveSiteButton: "Désactiver toutes les règles de ce site",
        urlCleanerRemovedFormat: "Retirés %@",
        switcherSearchPin: "Épingler la recherche avec S",
        switcherSearchPinCaption: "S lance une recherche et épingle le sélecteur ouvert\u{00A0}: plus de caractères spéciaux tapés quand le raccourci utilise ⌥, et une recherche commençant par Q ou W ne ferme plus la fenêtre ni ne quitte l’app par erreur.",
        invertVerticalScroll: "Inverser le défilement vertical",
        invertHorizontalScroll: "Inverser le défilement horizontal",
        switcherShowShortcutHints: "Afficher les raccourcis",
        switcherShowShortcutHintsCaption: "Affiche les raccourcis des apps et des fenêtres sous les icônes.",
        uninstallerHomebrewPackageFormat: "%@ sera aussi retiré de Homebrew.",
        shelfEdgeToggle: "Ouvrir près d’un bord de l’écran",
        shelfEdgeCaption: "Faites glisser un fichier vers le bord de l’écran pour entrevoir l’étagère. Déposez-le là, ou reculez et elle se retire.",
        focusFollowsMouseName: "Le focus suit la souris",
        focusFollowsMouseCaption: "Active et place au premier plan la fenêtre sous le pointeur après une courte pause.",
        focusFollowsMouseDelay: "Délai de survol",
        switcherMinimizedPlacementLabel: "Fenêtres réduites",
        switcherMinimizedPlacementNormal: "Ordre normal",
        switcherMinimizedPlacementEnd: "Placer à la fin",
        switcherMinimizedPlacementHidden: "Masquer",
        switcherShowFullscreenWindows: "Afficher les fenêtres plein écran",
        switcherScreenPlacementLabel: "Afficher sur",
        switcherScreenPlacementPointer: "Écran avec le pointeur",
        switcherScreenPlacementMenuBar: "Écran avec la barre des menus",
        switcherScreenPlacementActiveWindow: "Écran avec la fenêtre active",
        switcherScreenPlacementCaption: "Sur quel écran le sélecteur s’ouvre quand plusieurs sont connectés.",
        smoothScrollResponseLabel: "Réactivité",
        mouseAccelerationName: "Désactiver l’accélération de la souris",
        mouseAccelerationCaption: "Supprime l’accélération du pointeur pour les souris connectées. Le réglage précédent est restauré à la désactivation ou à la fermeture de Vorssaint.",
        shelfClearOnClose: "Vider à la fermeture",
        shelfClearOnCloseCaption: "Vide l’étagère uniquement lorsque vous cliquez sur le bouton de fermeture. Le masquage automatique et la réduction conservent les éléments."
    )
}
