// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// 한국어
extension Strings {
    static let ko = Strings(
        statusIdleTooltip: "Vorssaint: 일반 절전",
        statusActiveUntil: "Vorssaint: 다음 시간까지 절전 방지",
        statusActiveIndefinite: "Vorssaint: 끌 때까지 절전 방지",
        menuEnableAwake: "절전 방지 켜기",
        menuDisableAwake: "절전 방지 끄기",
        menuActivateFor: "시간을 정해 켜기…",
        menuSettings: "설정…",
        menuAbout: "Vorssaint 정보",
        menuQuit: "Vorssaint 종료",
        menuHide: "Vorssaint 가리기",
        menuHideOthers: "다른 항목 가리기",
        menuShowAll: "모두 보기",
        menuEdit: "편집",
        menuUndo: "실행 취소",
        menuRedo: "다시 실행",
        actionClear: "지우기",
        actionRemove: "제거",
        actionBack: "뒤로",
        actionSearch: "검색",
        actionMute: "음소거",
        actionUnmute: "음소거 해제",
        actionPlay: "재생",
        actionPause: "일시 정지",
        menuCut: "잘라내기",
        menuCopy: "복사",
        menuPaste: "붙여넣기",
        menuSelectAll: "모두 선택",
        menuWindow: "윈도우",
        menuMinimize: "최소화",
        menuZoom: "확대/축소",
        menuClose: "닫기",

        minutes15: "15분",
        minutes30: "30분",
        hour1: "1시간",
        hours2: "2시간",
        hours4: "4시간",
        hours8: "8시간",
        indefinitely: "계속",
        indefinite: "계속",

        panelSettings: "설정",
        panelQuit: "종료",
        panelHotkeyHint: "단축키로 전환",

        keepAwakeTitle: "절전 방지",
        keepAwakeEndsIn: "남은 시간",
        keepAwakeUntilDisabled: "끌 때까지 유지",
        keepAwakeNormalRules: "Mac이 일반적인 에너지 절약 설정을 따릅니다",
        keepAwakeOptions: "옵션",
        keepAwakeMouseJiggle: "포인터 살짝 움직이기",
        keepAwakeMouseJiggleCaption: "세션 중 선택한 간격마다 포인터를 살짝 움직입니다.",
        keepAwakeMouseJiggleInterval: "간격",
        keepAwakeActiveIconLabel: "활성 아이콘",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "커피",
        keepAwakeActiveIconEye: "눈",
        keepAwakeActiveIconMoon: "달",
        keepAwakeActiveIconLight: "전구",
        keepAwakeIconTintLabel: "활성 상태 아이콘 색상",
        keepAwakeIconTintOrange: "주황색",
        keepAwakeIconTintGreen: "녹색",
        keepAwakeIconTintBlue: "파란색",
        keepAwakeIconTintPurple: "보라색",
        keepAwakeIconTintPink: "분홍색",
        keepAwakeIconTintNone: "없음",
        durationLabel: "지속 시간",
        clamshellTitle: "덮개를 닫아도 계속 유지",
        clamshellOnCaption: "절전이 완전히 비활성화됩니다. 전원 사용량에 유의하세요.",
        clamshellNeedsSession: "절전 방지가 켜져 있는 동안 항상 적용됩니다",
        clamshellReady: "준비되었습니다. 암호 없이 전환할 수 있습니다",
        clamshellNeedsPassword: "관리자 암호는 한 번만 요청됩니다",

        systemSection: "시스템",
        temperatures: "온도",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "배터리",
        usageSection: "하드웨어 사용량",
        memorySection: "메모리",
        memoryPressure: "압력",
        memorySwapUsed: "사용 중인 스왑",
        memoryCompressed: "압축됨",
        memoryCachedFiles: "캐시된 파일",
        pressureNormal: "정상",
        pressureWarning: "주의",
        pressureCritical: "위험",
        monitorUnavailable: "이 Mac에서는 센서를 사용할 수 없습니다",
        energyAppsTitle: "에너지를 많이 쓰는 앱",
        energyAppsIdle: "에너지를 많이 쓰는 앱이 없습니다",

        notifySessionEndedTitle: "세션이 끝났습니다",
        notifySessionEndedBody: "설정한 시간이 지났습니다. Mac이 다시 평소처럼 절전 모드로 전환됩니다.",
        notifyBatteryTitle: "Vorssaint를 껐습니다",
        notifyBatteryBody: "배터리 잔량이 낮습니다. 충전을 보호하기 위해 일반 절전 모드로 되돌렸습니다.",
        adminPromptClamshellOn: "덮개를 닫아도 계속 사용하려면 Vorssaint에 관리자 암호가 필요합니다.",
        adminPromptClamshellOff: "Mac의 일반 절전 모드를 복원하려면 관리자 암호가 필요합니다.",
        adminPromptRecover: "Mac의 절전이 비활성화된 상태에서 Vorssaint가 종료되었습니다. 일반 절전 모드를 복원하려면 암호를 입력하세요.",
        adminPromptUpdate: "업데이트를 설치하려면 Vorssaint에 관리자 암호가 필요합니다.",
        adminPromptSudoersInstall: "덮개 닫힘 모드를 암호 없이 전환할 수 있도록 Vorssaint가 제한된 규칙(pmset disablesleep만)을 만듭니다. 암호는 이번 한 번만 필요합니다.",
        adminPromptSudoersRemove: "Vorssaint가 암호 없이 사용하는 덮개 닫힘 모드 규칙을 제거합니다.",

        settingsTitle: "Vorssaint 설정",
        tabGeneral: "일반",
        tabEnergy: "에너지",
        tabMouse: "마우스 및 트랙패드",
        tabSwitcher: "전환기",
        tabAdvanced: "고급",
        tabAbout: "정보",
        tabReleaseNotes: "새로운 기능",
        releaseNotesOnUpdateToggle: "업데이트 후 새로운 기능 보기",
        minimalWindowPreviews: "간결한 미리보기",
        minimalWindowPreviewsCaption: "Dock 및 앱 전환기 미리보기에서 제목, 버튼, 장식을 숨깁니다. 선택 표시는 유지됩니다.",
        previewSizeLabel: "미리보기 크기",
        previewSizeNormal: "보통",
        previewSizeLarge: "크게",
        previewSizeXLarge: "매우 크게",
        settingsGroupFeatures: "기능",
        advancedResetSection: "권한",
        advancedResetDescription: "Vorssaint에 허용한 모든 권한(손쉬운 사용, 화면 녹화, 전체 디스크 접근 등), 로그인 항목 및 덮개 닫힘 모드 규칙을 제거합니다. 처음부터 다시 시작하거나 앱을 삭제하기 전에 유용합니다. 앱은 설치된 상태로 유지됩니다.",
        advancedClearButton: "모든 권한 지우기",
        advancedCleared: "권한을 지웠습니다.",
        advancedClearConfirmTitle: "모든 권한을 지울까요?",
        advancedClearConfirmBody: "권한이 필요한 기능은 다시 허용할 때까지 작동하지 않습니다. 설정은 유지됩니다.",
        advancedUninstallSection: "제거",
        advancedUninstallDescription: "위 작업을 모두 수행한 뒤 설정을 지우고 Vorssaint를 휴지통으로 옮겨 아무것도 남기지 않습니다. 완료되면 앱이 종료됩니다. 언제든 다시 설치할 수 있습니다.",
        advancedUninstallButton: "Vorssaint 완전히 제거",
        advancedUninstallConfirmTitle: "Vorssaint를 제거할까요?",
        advancedUninstallConfirmBody: "Vorssaint가 권한과 설정을 지우고 휴지통으로 이동한 뒤 종료됩니다. 이 작업은 앱에서 되돌릴 수 없지만 휴지통을 비우기 전까지는 복원할 수 있습니다.",
        advancedUninstallFailedTitle: "제거를 중단했습니다",
        advancedUninstallFailedBody: "Vorssaint가 변경한 시스템 설정을 되돌리지 못했습니다. 잠자기, 팬 속도 또는 마우스 가속입니다. 아무것도 삭제되지 않았습니다. 다시 시도하고 암호를 요청하면 허용하세요.",

        launchAtLogin: "로그인 시 실행",
        languageLabel: "언어",
        menuBarSection: "메뉴 막대",
        showCountdown: "아이콘 옆에 남은 시간 표시",
        globalHotkeySection: "전역 단축키",
        hotkeyToggle: "절전 방지 단축키 사용",
        hotkeyCaption: "추가 권한 없이 어떤 앱에서든 사용할 수 있습니다.",

        sessionSection: "세션",
        defaultDurationLabel: "기본 지속 시간",
        keepAwakeAutoStart: "Vorssaint 실행 시 잠자기 방지",
        keepAwakeAutoStartCaption: "기본 시간으로 세션을 시작합니다.",
        batteryProtectionSection: "배터리 보호",
        batteryDisableBelow: "배터리 잔량이 다음보다 낮으면 끄기",
        batteryNever: "안 함",
        batteryProtectionCaption: "켜진 채로 남은 세션이 MacBook 배터리를 소모하지 않도록 합니다.",
        clamshellSection: "덮개 닫힘 모드",
        configuring: "설정하는 중…",
        sudoersFailed: "덮개 닫힘 모드를 활성화할 수 없습니다. 다시 시도하세요.",
        clamshellExplanation: "덮개를 닫아도 계속 유지는 절전 방지가 켜져 있는 동안 절전을 완전히 비활성화하며, 세션이나 앱이 끝나면 자동으로 원래 상태로 되돌립니다. 전원에 연결한 상태에서 사용하는 것을 권장합니다.",

        scrollSection: "스크롤",
        invertMouseScroll: "마우스 스크롤 반전",
        invertMouseScrollCaption: "마우스 휠의 스크롤 방향을 반대로 바꿉니다.",
        scrollTrackpadNote: "트랙패드는 변경하지 않고 macOS의 자연스러운 스크롤을 유지합니다.",
        scrollActiveNow: "마우스 스크롤을 반전하는 중",
        mouseNavigationActiveNow: "사이드 버튼이 현재 활성화되어 있습니다",
        smoothScrollName: "부드러운 스크롤",
        smoothScrollCaption: "마우스 휠 한 칸을 짧고 부드러운 슬라이드로 바꿉니다. 트랙패드는 변경되지 않습니다.",
        smoothScrollStepLabel: "스크롤 속도",
        mouseNavigationSection: "탐색",
        mouseNavigationEnable: "사이드 버튼으로 뒤로 및 앞으로 이동",
        mouseNavigationCaption: "마우스의 뒤로 및 앞으로 버튼을 Finder, 브라우저 및 지원 앱의 탐색 동작으로 바꿉니다.",
        middleClickSection: "가운데 클릭",
        middleClickEnable: "세 손가락 클릭을 가운데 클릭으로 사용",
        middleClickEnableCaption: "트랙패드를 세 손가락으로 누르면 마우스 휠 클릭과 같이 동작합니다. 링크를 새 탭으로 열거나 탭을 닫는 등 가운데 버튼으로 할 수 있는 모든 동작에 사용할 수 있습니다.",
        middleClickDragConflict: "macOS의 세 손가락 드래그가 켜져 있고 같은 제스처를 사용합니다. 시스템 설정의 손쉬운 사용 > 포인터 제어 > 트랙패드 옵션에서 끄면 가운데 클릭이 작동합니다.",
        middleClickTapPicker: "가볍게 탭해도 클릭",
        middleClickTapOff: "끔",
        middleClickTapThreeFingers: "세 손가락",
        middleClickTapFourFingers: "네 손가락",
        middleClickTapCaption: "해당 개수의 손가락으로 가볍게 탭하기만 해도(누르지 않아도) 가운데 클릭이 실행됩니다. 쓸어 넘기기는 포함되지 않습니다. macOS의 세 손가락 탭에 ‘찾아보기’가 지정되어 있다면 두 동작이 함께 실행되지 않도록 끄세요.",
        quickToolsTab: "빠른 패널",
        quickToolShortcutToggle: "전역 단축키",
        ocrName: "화면의 텍스트 복사",
        ocrCaption: "화면 영역을 선택하면 인식한 텍스트를 복사해 즉시 붙여넣을 수 있습니다.",
        ocrCopied: "텍스트를 복사했습니다",
        ocrNoText: "텍스트를 찾을 수 없습니다",
        colorPickerName: "색상 선택기",
        colorPickerCaption: "화면의 모든 픽셀 색상을 가져와 원하는 형식으로 복사합니다.",
        colorPickerFormatLabel: "복사 형식",
        colorPickerBareHexToggle: "앞의 # 없이 복사",
        colorPickerPickNow: "색상 가져오기",
        micMuteName: "마이크 음소거",
        micUnmuteName: "마이크 음소거 해제",
        micMuteCaption: "클릭 또는 단축키로 모든 앱에서 Mac의 마이크를 음소거합니다.",
        micMutedHUD: "마이크를 음소거했습니다",
        micUnmutedHUD: "마이크 음소거를 해제했습니다",
        micMuteMenuBarToggle: "음소거 중 메뉴 막대에 표시",
        micMuteMenuBarCaption: "메뉴 막대의 앱 아이콘 옆에 빨간 줄이 그어진 마이크가 표시됩니다.",

        pastePlainName: "일반 텍스트로 붙여넣기",
        pastePlainCaption: "색상, 글꼴, 서식 없이 복사한 내용을 붙여넣습니다. 원본은 클립보드에 유지됩니다.",
        launcherName: "빠른 패널",
        launcherCaption: "즐겨 쓰는 도구를 모아 둔 떠 있는 패널입니다. 어디서나 단축키로 열 수 있습니다.",
        launcherOpenNow: "빠른 패널 열기",
        launcherEditHint: "조정 버튼에서 도구 선택, 숨기기, 드래그 이동을 할 수 있습니다.",
        launcherEmptyState: "모든 도구가 숨겨져 있습니다. 조정 버튼에서 다시 표시할 수 있습니다.",
        launcherAddSection: "복원",
        launcherKeysHint: "화살표 키로 이동, Return으로 열기, 1~9로 바로 열기",
        switcherSection: "앱 전환기",
        switcherEnable: "Vorssaint 전환기 사용",
        switcherEnableCaption: "앱과 윈도우를 전환합니다. 최소화한 윈도우와 같은 앱의 여러 윈도우도 지원합니다.",
        switcherUsageHint: "단축키를 누른 채 이동하고 놓으면 윈도우가 활성화됩니다. Shift 또는 ←로 뒤로 이동하고, W로 윈도우를 닫고, Q로 앱을 종료하며, Esc로 취소합니다.",
        switcherNoWindows: "열린 윈도우가 없습니다",
        switcherIconRowMode: "%@을 큰 아이콘으로 표시",
        switcherIconRowModeCaption: "앱마다 하나의 아이콘을 표시하고 그 위에 해당 앱의 윈도우 미리보기를 표시합니다.",
        switcherSimpleMode: "간단한 앱 전환기",
        switcherSimpleModeCaption: "미리보기와 전환기의 화면 녹화 기능을 사용하지 않고 앱 아이콘과 윈도우 제목을 표시합니다.",
        switcherShortcutHintApps: "앱",
        switcherShortcutHintWindows: "윈도우",
        switcherWindowShortcutCaption: "맨 앞 앱의 윈도우 전환기를 엽니다. 앱 전환기가 열려 있으면 선택한 앱의 윈도우를 차례로 전환합니다.",
        switcherTakeOverSystemShortcuts: "macOS ⌘Tab 및 ⌘` 대체",
        switcherTakeOverSystemShortcutsCaption: "Vorssaint 전환기가 활성화된 동안에만 해당 macOS 앱 및 윈도우 단축키를 끕니다. 실행 중인 모든 앱에 계속 접근할 수 있습니다.",
        switcherAppearanceDelay: "표시 지연",
        switcherAppearanceDelayCaption: "전환기가 나타나기 전에 단축키를 누르고 있어야 하는 시간입니다.",
        switcherMergeTabs: "앱별로 하나로 묶어 표시",
        switcherMergeTabsCaption: "전환기에서 앱의 모든 윈도우를 각각이 아닌 하나의 항목으로 묶습니다.",
        switcherWindowlessApps: "열린 윈도우가 없는 앱",
        switcherWindowlessAppsCaption: "윈도우가 하나도 없이 실행 중인 앱 중에서 어떤 앱을 전환기에 표시할지 선택합니다.",
        switcherWindowlessAppsOff: "표시 안 함",
        switcherWindowlessAppsFinder: "Finder만",
        switcherWindowlessAppsAll: "모든 앱",
        switcherNoOpenWindow: "열린 윈도우 없음",
        switcherOtherDesktop: "다른 데스크탑",
        dockPreviewName: "Dock 미리보기",
        dockPreviewEnable: "Dock에서 윈도우 미리보기",
        dockPreviewEnableCaption: "Dock의 열린 앱 위에 포인터를 올려 윈도우를 확인한 다음 원하는 윈도우를 클릭하세요.",
        dockPreviewBackgroundOpacity: "패널 배경",
        dockPreviewBackgroundOpacityCaption: "낮추면 패널 뒤에 있는 것이 더 많이 보입니다.",
        dockPreviewOpenDelay: "열림 지연",
        dockPreviewOpenDelayCaption: "포인터가 아이콘 위에 머문 뒤 패널이 열리기까지의 시간입니다.",
        dockPreviewQuitAppOnClose: "× 버튼으로 앱 종료",
        dockPreviewQuitAppOnCloseCaption: "Dock Preview에서 ×는 해당 윈도우만 닫는 대신 앱 전체를 종료합니다.",
        dockClickMinimize: "Dock 클릭으로 최소화",
        dockClickMinimizeCaption: "앞에 있는 앱의 Dock 아이콘을 클릭하면 윈도우를 최소화합니다. 다시 클릭하면 복원됩니다.",
        dockClickCycleWindows: "Dock 클릭으로 윈도우 전환",
        dockClickCycleWindowsCaption: "앞에 있는 앱의 Dock 아이콘을 클릭하면 윈도우를 차례로 전환합니다(⌘`과 동일).",
        dockPreviewActiveNow: "Dock에서 활성화됨",
        dockPreviewDockUnavailable: "Dock 항목을 읽을 수 없습니다.",
        dockPreviewAutohideBeta: "베타 기능입니다. 일부 문제가 남아 있을 수 있습니다.",
        dockPreviewOpenWindow: "윈도우 열기",
        dockPreviewCloseWindow: "윈도우 닫기",
        dockPreviewMinimizeWindow: "윈도우 최소화",
        dockPreviewRestoreWindow: "윈도우 복원",
        dockPreviewPinPanel: "미리보기 고정",
        dockPreviewUnpinPanel: "고정 해제",
        dockPreviewPinned: "고정됨",
        dockPreviewClosePanel: "미리보기 닫기",
        dockPreviewPreviousWindow: "이전 윈도우",
        dockPreviewNextWindow: "다음 윈도우",

        cutPasteName: "잘라내기 및 붙여넣기",
        cutPasteEnable: "Finder에서 파일 잘라내기 및 붙여넣기",
        cutPasteEnableCaption: "⌘X로 잘라내고 ⌘V로 Finder의 파일과 폴더를 이동합니다.",
        cutPasteShowHUD: "플로팅 패널 표시",
        cutPasteShowHUDCaption: "Finder가 활성화되어 있는 동안 잘라낸 파일이 담긴 플로팅 표시를 띄웁니다.",
        cutPasteHowTitle: "사용 방법",
        cutPasteStep1: "Finder에서 항목을 선택하고 ⌘X를 눌러 잘라냅니다.",
        cutPasteStep2: "대상 폴더를 열고 ⌘V를 눌러 그곳으로 이동합니다.",
        cutPasteTextNote: "텍스트 필드에서는(예: 이름 변경) ⌘X와 ⌘V가 이전과 같이 작동합니다.",
        cutPasteActiveNow: "Finder에서 잘라낼 수 있습니다",
        cutPasteAutomationNote: "처음 사용할 때 macOS가 Finder 제어 권한을 요청합니다.",
        cutReadyTitle: "잘라냈습니다",
        cutReadyHint: "대상 폴더에서",
        cutCancel: "잘라내기 취소",
        cutDoneTitle: "이동했습니다!",
        cutMovedSingular: "항목 1개를 이동했습니다",
        cutMovedPluralFormat: "항목 %d개를 이동했습니다",
        cutSomeFailed: "일부 항목을 이동할 수 없습니다",
        cutMovingTitle: "이동하는 중…",
        cutMovingCountFormat: "%d / %d",

        autoQuitName: "닫으면 종료",
        autoQuitEnable: "마지막 윈도우를 닫을 때 앱 종료",
        autoQuitEnableCaption: "앱의 마지막 윈도우를 닫으면 해당 앱도 종료합니다.",
        autoQuitActiveNow: "현재 활성화됨",
        autoQuitHowTitle: "작동 방식",
        autoQuitStep1: "앱의 마지막 윈도우를 닫습니다(⌘W 또는 빨간 버튼).",
        autoQuitStep2: "앱이 자동으로 종료됩니다. ‘변경 사항을 저장할까요?’ 대화상자는 계속 표시됩니다.",
        autoQuitPredictableNote: "보통 윈도우 없이 실행되는 앱은 종료하지 않습니다.",
        autoQuitExceptionsTitle: "예외",
        autoQuitExceptionsCaption: "이 목록의 앱은 윈도우가 없어도 계속 열려 있습니다.",
        autoQuitExceptionsEmpty: "예외가 없습니다",
        autoQuitAddApp: "앱 추가…",

        uninstallerName: "앱 제거기",
        uninstallerEnableCaption: "앱과 함께 남겨진 캐시, 설정, 로그 및 파일도 제거합니다.",
        uninstallerStep1: "앱을 설정으로 드래그하거나 목록에서 하나를 선택합니다.",
        uninstallerStep2: "찾은 파일과 해당 파일이 차지하는 공간을 검토합니다.",
        uninstallerStep3: "원하는 항목을 휴지통으로 보냅니다. 영구적으로 삭제하지는 않습니다.",
        uninstallerMenuItem: "앱 제거…",
        uninstallerDropTitle: "여기에 앱을 드래그하세요",
        uninstallerDropSubtitle: "또는 검사할 앱 선택",
        uninstallerChoose: "앱 선택…",
        uninstallerPickerTitle: "앱 선택",
        uninstallerPickerSearch: "앱 검색",
        uninstallerPickerEmpty: "앱을 찾을 수 없습니다",
        uninstallerEmptyNote: "검토 없이 삭제되는 항목은 없습니다.",
        uninstallerFDANote: "더 철저히 검사하려면 전체 디스크 접근을 허용하세요.",
        uninstallerFDAGrant: "접근 허용…",
        uninstallerFDAHint: "목록에서 Vorssaint를 켜세요. 표시되지 않으면 +를 클릭하고 응용 프로그램에서 Vorssaint를 선택하세요. 앱을 다시 열면 권한이 적용됩니다.",
        uninstallerFDARelaunch: "지금 다시 열기",
        uninstallerScanning: "파일을 검사하는 중…",
        uninstallerRemoving: "휴지통으로 이동하는 중…",
        uninstallerFoundTitle: "개 찾음",
        uninstallerSelectedFormat: "%d / %d개 선택됨",
        uninstallerRemove: "휴지통으로 이동",
        uninstallerCancel: "취소",
        uninstallerDoneTitle: "완료!",
        uninstallerFreedFormat: "%@ 확보됨",
        uninstallerSomeFailed: "일부 항목을 휴지통으로 이동할 수 없습니다.",
        uninstallerFailedNeedsFDA: "샌드박스 앱 데이터는 전체 디스크 접근 권한이 있어야 옮길 수 있습니다. 관리자 암호로는 대신할 수 없습니다.",
        uninstallerFailedMoreFormat: "외 %d개",
        uninstallerAnother: "다른 앱 제거",
        uninstallerCatApp: "응용 프로그램",
        uninstallerCatSupport: "지원 파일",
        uninstallerCatCaches: "캐시",
        uninstallerCatPreferences: "환경설정",
        uninstallerCatContainers: "컨테이너",
        uninstallerCatLogs: "로그",
        uninstallerCatState: "저장된 상태",
        uninstallerCatOther: "기타",

        urlCleanerName: "URL 정리",
        urlCleanerEnable: "복사할 때 URL 자동 정리",
        urlCleanerEnableCaption: "링크가 클립보드에 들어오는 즉시 추적 매개변수를 제거합니다.",
        urlCleanerActiveNow: "현재 활성화됨",
        urlCleanerManualTitle: "지금 정리",
        urlCleanerInputPlaceholder: "URL 붙여넣기",
        urlCleanerOutputPlaceholder: "정리된 URL이 여기에 표시됩니다",
        urlCleanerCleanButton: "정리",
        urlCleanerPasteButton: "붙여넣기",
        urlCleanerCopyButton: "복사",
        urlCleanerClearButton: "필드 지우기",
        urlCleanerNoURL: "유효한 URL을 붙여넣으세요.",
        urlCleanerNoChange: "제거할 항목이 없습니다.",
        urlCleanerCleaned: "URL을 정리했습니다.",
        urlCleanerCopied: "복사했습니다.",
        urlCleanerLocalNote: "로컬 처리. 네트워크 없음.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "formula와 cask를 검색, 설치 및 제거합니다.",
        homebrewMissingTitle: "Homebrew를 찾을 수 없습니다",
        homebrewMissingBody: "Vorssaint에서 공식 Homebrew 설치 관리자를 Terminal로 열 수 있습니다. Terminal에 단계가 표시되며 필요하면 암호를 요청합니다.",
        homebrewInstallHomebrew: "Homebrew 설치",
        homebrewInstallHomebrewCaption: "Terminal이 완료되면 여기로 돌아와 새로 고침을 클릭하세요.",
        homebrewInstallHomebrewOpened: "설치 관리자를 Terminal에서 열었습니다.",
        homebrewShellSetupTitle: "Terminal 설정 완료",
        homebrewShellSetupBody: "Homebrew는 설치되었지만 Terminal에서 아직 brew 명령을 찾지 못할 수 있습니다. Vorssaint에서 설정 명령을 Terminal로 열 수 있습니다.",
        homebrewShellSetupButton: "Terminal 설정",
        homebrewShellSetupOpened: "명령을 Terminal에서 열었습니다. 완료되면 여기로 돌아와 새로 고침을 클릭하세요.",
        homebrewRefresh: "새로 고침",
        homebrewCheckPackages: "패키지 확인",
        homebrewTrustTitle: "아직 신뢰하지 않은 Tap",
        homebrewTrustCaption: "Homebrew는 타사 Tap을 사용하기 전에 확인을 요청합니다. %@을(를) 신뢰하면 계속할 수 있습니다.",
        homebrewTrustButton: "신뢰하고 계속",
        homebrewSearchPlaceholder: "패키지 검색",
        homebrewKeyboardHint: "Space 또는 Return을 누르면 macOS 패널이 닫힙니다. 검색 버튼을 사용하세요.",
        homebrewSearchButton: "검색",
        homebrewSearchResults: "결과",
        homebrewInstalled: "설치됨",
        homebrewAll: "모두",
        homebrewFormulas: "Formula",
        homebrewCasks: "Cask",
        homebrewNoPackages: "패키지를 찾을 수 없습니다",
        homebrewNoSelection: "설치한 패키지를 선택하거나 새 패키지를 검색하세요.",
        homebrewDetailsTitle: "패키지 세부 정보",
        homebrewInstall: "설치",
        homebrewUninstall: "제거",
        homebrewUpgrade: "업그레이드",
        homebrewUpgradeAll: "모두 업그레이드",
        homebrewUpdateHomebrew: "Homebrew 업데이트",
        homebrewAllPackages: "패키지",
        homebrewOpenTerminal: "Terminal 열기",
        homebrewCancelOperation: "취소",
        homebrewClearLog: "로그 지우기",
        homebrewLogTitle: "로그",
        homebrewVersion: "버전",
        homebrewDescription: "설명",
        homebrewHomepage: "웹 사이트 열기",
        homebrewPopularity: "인기도",
        homebrewPopularityFormat: "%@회 설치, %@일",
        homebrewInstalledBadge: "설치됨",
        homebrewNotInstalledBadge: "설치되지 않음",
        homebrewUpdates: "업데이트",
        homebrewUpdateAvailableBadge: "업데이트 가능",
        homebrewLatestVersion: "최신",
        homebrewConfirmInstallTitle: "Homebrew로 설치할까요?",
        homebrewConfirmInstallBodyFormat: "Homebrew가 %@을(를) 다운로드하고 설치합니다. 종속성도 설치될 수 있습니다.",
        homebrewConfirmUninstallTitle: "Homebrew로 제거할까요?",
        homebrewConfirmUninstallBodyFormat: "Homebrew가 %@을(를) 제거합니다. 설정 파일은 시스템에 남아 있을 수 있습니다.",
        homebrewConfirmUpgradeTitle: "Homebrew로 업그레이드할까요?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew가 %@의 최신 버전을 다운로드해 적용합니다. 종속성도 업그레이드될 수 있습니다.",
        homebrewConfirmUpgradeAllTitle: "Homebrew의 모든 패키지를 업그레이드할까요?",
        homebrewConfirmUpgradeAllBody: "Homebrew가 업그레이드 가능한 패키지의 최신 버전을 다운로드해 적용합니다. 종속성도 업그레이드될 수 있습니다.",
        homebrewConfirmUpdateHomebrewTitle: "Homebrew를 업데이트할까요?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew가 최신 정보를 가져온 다음 패키지를 새로 불러옵니다.",
        homebrewTerminalFallback: "이 작업은 관리자 암호를 요청하기 위해 Terminal이 필요합니다. Vorssaint는 암호를 수집하지 않습니다.",
        homebrewLoading: "불러오는 중…",
        homebrewSearchEmpty: "결과 없음",
        homebrewOperationInstallFormat: "%@ 설치 중",
        homebrewOperationUninstallFormat: "%@ 제거 중",
        homebrewOperationUpgradeFormat: "%@ 업그레이드 중",
        homebrewOperationUpgradeAll: "패키지 업그레이드 중",
        homebrewOperationUpdateHomebrew: "Homebrew 업데이트 중",
        homebrewOperationInstalledFormat: "%@을(를) 설치했습니다.",
        homebrewOperationUninstalledFormat: "%@을(를) 제거했습니다.",
        homebrewOperationUpgradedFormat: "%@을(를) 업그레이드했습니다.",
        homebrewOperationUpgradedAll: "패키지를 업그레이드했습니다.",
        homebrewOperationUpdatedHomebrew: "Homebrew를 업데이트했습니다.",
        homebrewOperationFailedFormat: "%@을(를) 완료하지 못했습니다.",
        homebrewOperationCancelled: "작업을 취소했습니다.",
        homebrewOperationPreparing: "준비 중…",
        homebrewOperationDownloading: "파일 다운로드 중…",
        homebrewOperationInstalling: "파일 설치 중…",
        homebrewOperationUninstalling: "파일 제거 중…",
        homebrewOperationUpgrading: "파일 업그레이드 중…",
        homebrewOperationFinalizing: "마무리 중…",
        homebrewOperationRefreshing: "목록 새로 고치는 중…",
        homebrewOperationTerminal: "Terminal에서 계속하세요.",
        homebrewOperationElapsedFormat: "%@ 경과",
        homebrewOperationShowDetails: "세부 정보 보기",
        homebrewOperationHideDetails: "세부 정보 가리기",
        homebrewOperationTechnicalLog: "기술 세부 정보",
        homebrewOperationProgressUnknown: "Homebrew가 아직 진행률을 보고하지 않았습니다.",

        mediaName: "미디어",
        mediaEnableCaption: "동영상을 압축하고 이미지를 변환 및 처리하며, GIF를 만들고 텍스트를 로컬에서 추출합니다.",
        mediaLocalNote: "로컬 처리. 네트워크 없음.",
        mediaToolVideo: "동영상",
        mediaToolGIF: "GIF",
        mediaToolImage: "이미지",
        mediaToolText: "텍스트",
        mediaSelectFile: "파일 선택",
        mediaDropHint: "여기에 파일을 놓거나 클릭해 선택하세요.",
        mediaOutput: "출력",
        mediaOutputAutomatic: "자동",
        mediaChooseOutput: "저장 위치",
        mediaStartVideo: "동영상 압축",
        mediaStartGIF: "GIF 만들기",
        mediaStartImage: "이미지 처리",
        mediaStartConvertPDF: "PDF로 변환",
        mediaStartText: "텍스트 추출",
        mediaCancel: "취소",
        mediaStartTime: "시작",
        mediaEndTime: "끝",
        mediaQuality: "압축",
        mediaCompressionLow: "낮음",
        mediaCompressionMedium: "중간",
        mediaCompressionHigh: "높음",
        mediaMaxSize: "크기",
        mediaSizingResolution: "해상도",
        mediaSizingFileSize: "파일 크기",
        mediaTargetSize: "목표 크기",
        mediaTargetSizeHint: "제한을 넘지 않도록 해상도가 자동으로 조정됩니다.",
        mediaErrorTargetTooSmall: "이 클립에는 목표 크기가 너무 작습니다. 길이를 줄이거나 제한을 높이세요.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "너비",
        mediaFPS: "FPS",
        mediaKeepAudio: "오디오 유지",
        mediaCodec: "코덱",
        mediaFormat: "형식",
        mediaStripMetadata: "메타데이터 제거",
        mediaLoopGIF: "GIF 반복",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "정확도 우선",
        mediaOCRFast: "속도 우선",
        mediaLanguageCorrection: "언어 보정",
        mediaTextOutputNote: "추출한 텍스트는 복사하거나 TXT로 저장할 수 있습니다.",
        mediaRunning: "처리 중",
        mediaCompleted: "완료",
        mediaCancelled: "취소했습니다.",
        mediaOpenInFinder: "Finder에서 보기",
        mediaCopyText: "텍스트 복사",
        mediaRunAgain: "다시 실행",
        mediaEmptyText: "텍스트를 찾을 수 없습니다.",
        mediaResultSavedFormat: "%@(으)로 저장했습니다",
        mediaResultSizeFormat: "%@에서 %@",
        mediaResultGrewCaption: "변환한 파일이 원본보다 커졌습니다.",
        mediaErrorNoFile: "먼저 파일을 선택하세요.",
        mediaErrorNoVideo: "이 파일에는 동영상 트랙이 없습니다.",
        mediaErrorSameOutput: "원본 파일과 다른 저장 위치를 선택하세요.",
        mediaErrorUnsupported: "macOS에서 지원하지 않는 형식입니다.",

        shelfName: "선반",
        shelfEnable: "파일을 드래그해 두는 임시 공간",
        shelfEnableCaption: "파일, 이미지, 텍스트를 모아 두었다가 나중에 어디든 드래그할 수 있는 떠 있는 공간입니다.",
        shelfHowTitle: "사용 방법",
        shelfStep1: "단축키를 누르거나 드래그 중 마우스를 흔들어 엽니다.",
        shelfStep2: "파일, 이미지, 링크, 텍스트를 놓아 보관합니다.",
        shelfStep3: "필요할 때 각 항목을 원하는 앱으로 드래그해 꺼냅니다.",
        shelfShakeToggle: "드래그 중 마우스를 흔들어 열기",
        shelfShakeCaption: "항목을 잡은 채 포인터를 빠르게 흔들면 커서 근처에서 열 수 있습니다.",
        shelfDropZoneToggle: "드래그한 파일을 메뉴 막대에 보관",
        shelfDropZoneCaption: "파일을 드래그하면 메뉴 막대 아이콘 아래에 선반이 나타납니다. 놓은 항목은 그대로 보관되고 클릭해 열고 닫을 수 있는 버튼에 들어가며, 선반이 비면 사라집니다.",
        shelfDropZoneLabel: "여기에 놓기",
        shelfCollapse: "접기",
        shelfBehaviorTitle: "사용 후",
        shelfCloseAfterDrop: "다른 앱에 놓은 후 닫기",
        shelfCloseAfterDropCaption: "대상 앱이 항목을 받으면 선반을 닫습니다. 패널 고정으로 열어 둘 수 있습니다.",
        shelfRemoveAfterDrop: "놓은 후 항목 제거",
        shelfRemoveAfterDropCaption: "다른 앱이 받은 항목을 선반에서 제거합니다. 사본을 남기려면 끄세요.",
        shelfExclusionsTitle: "자동 표시 예외",
        shelfExclusionsEmpty: "추가한 앱이 없습니다.",
        shelfExclusionsCaption: "이 앱에서 시작한 드래그에서는 흔들기 동작과 메뉴 막대 영역이 열리지 않습니다. 단축키와 지금 열기는 계속 사용할 수 있습니다.",
        shelfPin: "열어 두기",
        shelfUnpin: "사용 후 닫기",
        extraBrightnessName: "추가 밝기",
        extraBrightnessCaption: "디스플레이의 HDR 여유를 사용해 최대 밝기를 넘깁니다. 배터리 소모가 늘고 Mac이 뜨거워질 수 있습니다.",
        extraBrightnessLevelLabel: "강도",
        extraBrightnessUnsupported: "14인치 및 16인치 MacBook Pro 등의 XDR 디스플레이에서만 사용할 수 있습니다.",
        shelfHotkeyLabel: "단축키",
        shelfOpenNow: "지금 열기",
        shelfNoPermission: "권한이 필요하지 않습니다.",
        shelfMenuItem: "선반 열기",
        shelfTitle: "선반",
        shelfEmpty: "여기에 항목을 드래그하세요",
        shelfClearAll: "모두 지우기",
        shelfRemoveSelected: "선택 항목 제거",
        shelfSelectedFormat: "%d개 선택됨",
        shelfHint: "클릭하여 선택하고 드래그하여 사용하거나, 보조 클릭하여 더 많은 동작을 표시하세요.",
        shelfItemImage: "이미지",
        shelfTooltipItemsFormat: "%d개 항목",
        shelfTooltipItemsFew: "%d개 항목",
        shelfTooltipImageSingular: "%d개 이미지",
        shelfTooltipImageFew: "%d개 이미지",
        shelfTooltipImagePlural: "%d개 이미지",
        shelfTooltipFileSingular: "%d개 파일",
        shelfTooltipFileFew: "%d개 파일",
        shelfTooltipFilePlural: "%d개 파일",
        shelfTooltipNoteSingular: "%d개 메모",
        shelfTooltipNoteFew: "%d개 메모",
        shelfTooltipNotePlural: "%d개 메모",
        shelfTooltipLinkSingular: "%d개 링크",
        shelfTooltipLinkFew: "%d개 링크",
        shelfTooltipLinkPlural: "%d개 링크",
        shelfActionOpen: "열기",
        shelfActionOpenWith: "다음으로 열기",
        shelfActionShare: "공유",

        breakdownMeasuring: "측정 중…",

        mixerSection: "볼륨 믹서",
        mixerEmpty: "오디오를 사용하는 앱이 여기에 표시됩니다",
        mixerUnavailable: "macOS 14.4 이상에서 사용할 수 있습니다",
        mixerPermissionBody: "앱별 볼륨을 조절하려면 시스템 설정에서 ‘화면 및 시스템 오디오 녹음’을 허용하세요. 오디오는 기록되지 않습니다.",
        mixerResetTooltip: "100%로 재설정",
        mixerOutputDefault: "기본값",
        mixerOutputCurrent: "현재",
        mixerOutputUnavailable: "출력을 사용할 수 없습니다",
        mixerOutputFallback: "이 기기가 돌아올 때까지 기본 출력을 사용합니다.",
        mixerBypassedCaption: "이 앱은 자체적으로 오디오를 관리합니다.",
        mixerOutputTooltip: "출력 선택",
        mixerSystemOutputTitle: "출력",
        mixerSystemOutputNoDevices: "출력을 찾을 수 없습니다",
        mixerSystemOutputTooltip: "시스템 출력 선택",
        mixerSystemOutputErrorFormat: "변경하지 못했습니다: %@",
        mixerLowerOnHeadphonesDisconnect: "헤드폰 연결 해제 시 볼륨 낮추기",
        mixerLowerOnHeadphonesDisconnectCaption: "유선 또는 Bluetooth 헤드폰이 연결 해제되면 출력을 조정합니다.",
        mixerHeadphonesDisconnectVolume: "연결 해제 후 볼륨",
        preciseVolumeRollerEnable: "더 세밀한 볼륨 단계 사용",
        preciseVolumeRollerCaption: "볼륨 휠과 키를 더 작은 시스템 볼륨 단계로 바꿉니다.",
        preciseVolumeRollerTapFailed: "볼륨 키를 감지할 수 없습니다.",
        soundOutputSwitcherTitle: "출력 전환",
        soundOutputSwitcherEnable: "단축키로 출력 전환",
        soundOutputSwitcherCaption: "출력을 선택하고 단축키로 다음 사용 가능한 출력으로 전환합니다.",
        soundOutputSwitcherDevices: "전환할 출력",
        soundOutputSwitcherNoAvailableSelection: "사용 가능한 출력을 하나 이상 선택하세요.",
        mixerInputTitle: "마이크",
        mixerInputNoDevices: "마이크를 찾을 수 없습니다",
        mixerInputUnavailable: "마이크를 사용할 수 없습니다",
        mixerInputFallback: "이 마이크가 돌아올 때까지 기본 입력을 사용합니다.",
        mixerInputTooltip: "마이크 선택",
        mixerInputErrorFormat: "변경하지 못했습니다: %@",
        mixerVisibleApps: "목록에 표시할 앱",
        mixerAllShown: "모두",
        mixerHiddenCountLabel: "숨김",
        mixerHideFromList: "목록에서 숨기기",

        updatesSection: "업데이트",
        autoCheckToggle: "업데이트 자동 확인",
        includeBetaUpdatesToggle: "베타 업데이트 받기",
        includeBetaUpdatesCaption: "베타 버전에는 개발 중인 기능이 포함되어 있으며 불안정하거나 오류가 발생할 수 있습니다.",
        betaBadgeLabel: "베타",
        checkNowButton: "지금 확인",
        updateChecking: "확인하는 중…",
        updateUpToDate: "최신 버전을 사용하고 있습니다.",
        updateAvailablePrefix: "업데이트를 사용할 수 있습니다:",
        updateInstallButton: "다운로드 및 설치",
        updateDownloading: "업데이트 다운로드 중…",
        updateInstalling: "설치하고 다시 시작하는 중…",
        updateFailedPrefix: "확인하지 못했습니다:",
        updateLastChecked: "마지막 확인:",
        updateNotifyTitle: "Vorssaint 업데이트",
        updateInstallFailedBody: "업데이트를 다운로드했지만 적용하지 못했습니다. GitHub 릴리스 페이지에서 최신 버전을 다운로드하고 현재 앱 위로 드래그해 교체하세요.",
        updateNeedsApplicationsTitle: "Vorssaint를 ‘응용 프로그램’으로 이동하세요",
        updateNeedsApplicationsBody: "앱이 디스크 이미지나 시스템 임시 위치처럼 업데이트할 수 없는 위치에서 실행 중입니다. Vorssaint를 ‘응용 프로그램’ 폴더로 드래그하고 그곳에서 연 뒤 다시 시도하세요.",
        menuCheckUpdates: "업데이트 확인…",

        permissionRequired: "권한이 필요합니다",
        permissionAccessibility: "손쉬운 사용",
        permissionScreenRecording: "화면 녹화",
        permissionGranted: "허용됨",
        permissionMissing: "허용되지 않음",
        permissionOpenSettings: "시스템 설정 열기…",
        permissionRequest: "접근 허용",
        permissionRestartNote: "권한을 허용한 뒤 macOS에서 앱을 다시 열도록 요청할 수 있습니다.",

        aboutDescription: "Mac을 위한 유틸리티 허브입니다.\n메뉴 막대에서 에너지 관리, 시스템 모니터, 스크롤 및 윈도우 전환을 제공합니다.",
        versionPrefix: "버전",
        reviewIntro: "시작하기 다시 보기",
        reviewHighlights: "업데이트 둘러보기 다시 보기",
        viewOnGitHub: "GitHub에서 보기",

        obContinue: "계속",
        obBack: "뒤로",
        obSkipStep: "이 단계 건너뛰기",
        obStart: "Vorssaint 열기",
        obStepWelcomeTitle: "Vorssaint에 오신 것을 환영합니다",
        obStepWelcomeBody: "매일의 macOS를 더 편하게 만드는 조용한 메뉴 막대 유틸리티입니다.",
        obWelcomeBullet1Title: "에너지 관리를 원하는 대로",
        obWelcomeBullet1Body: "덮개를 닫은 상태에서도 원하는 만큼 Mac이 잠들지 않게 유지합니다.",
        obWelcomeBullet2Title: "시스템을 한눈에",
        obWelcomeBullet2Body: "CPU, GPU, 배터리 온도와 하드웨어 사용량, 메모리 압력을 실시간으로 확인합니다.",
        obWelcomeBullet3Title: "마우스와 윈도우를 내 방식대로",
        obWelcomeBullet3Body: "마우스 스크롤 반전과 썸네일이 있는 윈도우 전환기를 제공합니다.",
        obLanguageLabel: "언어",
        obStepAccessibilityTitle: "손쉬운 사용",
        obStepAccessibilityBody: "마우스 스크롤을 반전하고 윈도우 전환기가 키보드에 반응하도록 하는 데 필요합니다.",
        obAccessibilityWhy: "앱은 마우스 휠과 전환기 단축키만 감시합니다. 어떤 내용도 기록하거나 전송하지 않습니다.",
        obStepRecordingTitle: "화면 녹화",
        obStepRecordingBody: "전환기에서 아이콘뿐 아니라 실제 윈도우의 썸네일도 표시할 수 있습니다.",
        obRecordingWhy: "썸네일은 즉시 생성되어 메모리에만 머무르며 Mac 밖으로 나가지 않습니다. 허용하지 않아도 전환기는 아이콘으로 작동합니다.",
        obStepMonitorTitle: "시스템 모니터",
        obStepMonitorBody: "패널에 CPU, GPU, 배터리 온도와 하드웨어 사용량, 메모리 압력이 표시됩니다.",
        obMonitorNoPermission: "권한이 필요하지 않습니다. 센서는 시스템에서 직접 읽습니다.",
        obStepOptionalTitle: "선택 기능",
        obStepOptionalBody: "지금 사용할 기능을 켜세요. 나중에 설정에서 모두 변경할 수 있습니다.",
        obStepStatusTitle: "확인",
        obStepStatusBody: "사용하려는 기능이 모두 준비되었는지 확인합니다.",
        obStatusRecheck: "다시 확인",
        obStepDoneTitle: "준비 완료!",
        obStepDoneBody: "Vorssaint가 이미 Mac을 살피고 있습니다.",
        obDoneHint: "화면 오른쪽 위 메뉴 막대에서 블랙홀 아이콘을 찾으세요.",
        obWhatsNewTitle: "이번 버전의 새로운 기능",
        obWhatsNewFallback: "이 업데이트에는 최신 수정 사항과 개선 사항이 포함되어 있습니다.",
        obLanguageUpdateTitle: "내 언어로 사용하기",
        obLanguageUpdateBody: "Vorssaint가 여러 언어를 지원합니다. 사용할 언어를 선택하세요. 설정에서 언제든 변경할 수 있습니다.",
        obPurposeTitle: "무엇을 하고 싶으신가요?",
        obPurposeBody: "준비된 설정을 고르거나 사용할 기능을 정확히 선택하세요.",
        obPurposeSkip: "기능은 나중에 설정에서 추가하거나 제거할 수 있습니다.",

        tabMonitor: "모니터",
        monitorMenuBarSection: "메뉴 막대",
        monitorMenuBarCaption: "메뉴 막대의 아이콘 옆에 표시할 항목을 선택합니다.",
        monitorCombineTemperatures: "사용량과 온도 결합",
        monitorCombineTemperaturesCaption: "같은 항목의 사용량과 온도가 모두 활성화되면 하나의 블록으로 묶어 표시합니다.",
        monitorSeparateMenuBarMetrics: "지표를 개별 메뉴 막대 항목으로 분리",
        monitorSeparateMenuBarMetricsCaption: "활성화된 블록을 메뉴 막대에서 분리하고, 결합이 켜져 있으면 사용량과 온도를 함께 표시합니다.",
        monitorNetworkUploadFirst: "업로드를 다운로드 위에 표시",
        monitorShowCPU: "CPU",
        monitorShowMemory: "메모리",
        monitorShowNetwork: "네트워크",
        monitorShowPowerLabel: "전원",
        monitorIntervalLabel: "갱신 간격",
        monitorInterval1: "1초",
        monitorInterval2: "2초",
        monitorInterval5: "5초",
        monitorPanelSection: "패널",
        panelNavigationMode: "패널을 섹션별로 이동",
        panelNavigationCaption: "한 번에 하나의 섹션만 표시합니다. ‘목록’을 선택하면 모든 섹션을 연속으로 스크롤해 표시합니다.",
        panelFooterSections: "섹션",
        panelFooterList: "목록",
        betaBadge: "BETA",
        betaFeatureWarning: "베타 기능입니다. 일부 문제가 남아 있을 수 있습니다.",

        networkSection: "네트워크",
        networkDownload: "다운로드",
        networkUpload: "업로드",
        networkThisSession: "이 세션",
        networkMeasuring: "측정 중…",
        networkApps: "네트워크를 사용하는 앱",
        networkAppsIdle: "현재 네트워크를 사용하는 앱이 없습니다",

        diskSection: "디스크",
        diskUsed: "사용됨",
        diskFree: "사용 가능",
        diskAvailable: "사용 가능",
        diskPurgeable: "삭제 가능",
        diskInternal: "내장",
        diskExternal: "외장",
        diskSelect: "디스크 선택",
        diskRead: "읽기",
        diskWrite: "쓰기",
        diskSMARTStatus: "상태",
        diskSMARTUnavailable: "이 디스크에서는 SMART를 사용할 수 없습니다",
        diskTotalRead: "총 읽기",
        diskTotalWritten: "총 쓰기",
        diskTemperature: "온도",
        diskHealth: "상태",
        diskPowerCycles: "전원 켠 횟수",
        diskPowerOnHours: "가동 시간",
        diskUnsafeShutdowns: "안전하지 않은 종료",
        diskMediaErrors: "미디어 오류",
        diskEject: "추출",
        diskEjectAll: "모두 추출",
        diskEjecting: "추출 중…",
        diskReadyToRemove: "제거해도 됩니다",
        diskEjectFailed: "추출하지 못했습니다",
        diskProtectionCaption: "제거하기 전에 추출합니다.",
        diskNoExternal: "추출할 수 있는 외장 디스크가 없습니다.",
        diskOpenInFinder: "Finder에서 열기",
        diskStorageSettings: "저장 공간",
        diskNoDisks: "마운트된 디스크를 찾을 수 없습니다.",

        powerSection: "전원",
        powerSystem: "시스템",
        powerAdapter: "어댑터",
        powerBattery: "배터리",
        powerCharging: "충전 중",
        powerOnBattery: "배터리 사용 중",
        powerPluggedIn: "전원 연결됨",
        powerUnavailable: "이 Mac에서는 전원 측정값을 사용할 수 없습니다",
        powerAdapterMaxFormat: "최대 %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU 온도",
        monitorShowGPUTemperature: "GPU 온도",
        monitorShowBatteryTemperature: "배터리 온도",
        monitorShowPeripheralBattery: "주변 기기 배터리",
        peripheralBatteryNoDevices: "주변 기기를 찾을 수 없습니다",
        monitorGraphsSection: "그래프",
        monitorGraphsCaption: "시간 흐름에 따라 그래프로 표시할 항목을 선택합니다.",

        updateBannerTitle: "업데이트를 사용할 수 있습니다",
        updateBannerAction: "업데이트",
        obStepMenuBarTitle: "메뉴 막대 지표",
        obStepMenuBarBody: "아이콘 옆에 표시할 항목을 선택하세요. 위 미리보기가 실시간으로 갱신됩니다.",
        obStepMenuBarNote: "새로운 기능: 패널의 네트워크 및 전원 블록과 그래프입니다. 나중에 설정 › 모니터에서 모두 미세 조정할 수 있습니다.",
        monitorMenuBarPresetLabel: "스타일",
        menuBarPresetReadable: "읽기 쉬움",
        menuBarPresetDense: "촘촘함",
        menuBarSpacingLabel: "메뉴 막대 간격",
        menuBarSpacingStandard: "표준",
        menuBarSpacingCompact: "좁게",
        menuBarHideIconToggle: "지표가 표시될 때 앱 아이콘 숨기기",
        menuBarHideIconCaption: "지표가 막대에서 사라지거나 알릴 내용이 있을 때(업데이트 준비 완료 또는 마이크 음소거) 아이콘이 자동으로 돌아옵니다.",
        monitorLabelStyleLabel: "레이블",
        menuBarLabelStyleCompact: "축약",
        menuBarLabelStyleClassic: "표준",
        monitorMemoryStyleLabel: "메모리 표시",
        monitorMemoryPressureDot: "메모리 압력 점",
        memoryStyleDot: "점",
        memoryStylePercent: "%",
        memoryStyleBoth: "둘 다",
        systemUptime: "가동 시간",
        batteryCharge: "충전량",
        powerHealth: "배터리 상태",
        powerCycles: "충전 횟수",
        speedTestRun: "속도 테스트",
        speedTestAgain: "다시 테스트",
        speedTestLatency: "지연 시간",
        speedTestTesting: "테스트 중…",
        speedTestFailed: "테스트에 실패했습니다",

        monitorShowInPanel: "패널에 표시",
        disclosureExpanded: "펼쳐짐",
        disclosureCollapsed: "접힘",
        panelHideItem: "패널에서 숨기기",
        panelShowItem: "패널에 표시",
        panelHiddenItem: "숨김",
        monitorItemUptime: "가동 시간",
        monitorItemNetSpeed: "실시간 속도",
        monitorItemNetTotals: "세션 합계",
        monitorItemNetTest: "속도 테스트",
        monitorItemDiskUsage: "디스크 사용량",
        monitorItemDiskActivity: "실시간 활동",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "외장 디스크 보호",
        monitorItemDiskTools: "도구",
        monitorPanelConfigHint: "블록을 열어 표시할 내용을 선택하세요.",
        monitorOrderSection: "섹션 순서",
        monitorOrderHint: "드래그하여 패널 섹션의 순서를 바꾸고 눈 아이콘으로 각 섹션을 표시하거나 숨길 수 있습니다.",
        obStepPanelTitle: "패널에 표시할 항목",
        obStepPanelBody: "각 블록을 열고 아이콘을 클릭했을 때 표시할 내용을 자세히 선택하세요.",
        obStepPanelNavigationTitle: "섹션형 패널",
        obStepPanelNavigationBody: "패널에 한 번에 하나의 섹션만 표시할 수 있습니다. 설정에서 ‘섹션’과 ‘목록’ 사이를 전환할 수 있습니다.",

        cleaningMenuItem: "청소 모드",
        utilitiesSection: "유틸리티",
        quickControlsSection: "제어",
        panelCategoryWindows: "윈도우",
        panelCategoryInput: "마우스 및 키보드",
        panelCategoryFiles: "파일",
        windowMaximizeName: "윈도우 최대화",
        windowMaximizeCaption: "초록색 버튼으로 별도 공간을 만들지 않고 최대화합니다.",
        windowMaximizeActiveNow: "초록색 버튼으로 활성화됨",
        windowMaximizeNeedsAccessibility: "작동하려면 손쉬운 사용 권한이 필요합니다.",
        keyDebounceName: "디바운스",
        keyDebounceEnable: "중복 키 입력 필터링",
        keyDebounceCaption: "매우 빠른 중복 입력을 필터링합니다.",
        keyDebounceActiveNow: "필터 활성화됨",
        keyDebounceGlobalWindow: "전체 시간",
        keyDebouncePerKeySection: "개별 키",
        keyDebouncePerKeyCaption: "키별 값은 전체 시간보다 우선합니다. 0ms로 설정하면 해당 키를 필터링하지 않습니다.",
        keyDebounceKeyLabel: "키",
        keyDebounceWindowLabel: "시간",
        keyDebounceAddKey: "키 추가",
        keyDebounceNoOverrides: "개별 키가 설정되지 않았습니다.",
        keyDebounceRemoveKey: "키 제거",
        cleaningPanelCaption: "안전하게 청소할 수 있도록 키보드를 잠급니다.",
        cleaningOverlayTitle: "청소를 위해 키보드 잠김",
        cleaningOverlaySubtitle: "Esc 키를 5번 눌러 잠금을 해제하세요",
        cleaningOverlayUnlock: "잠금 해제",
        cleaningOverlayMouseHint: "마우스와 트랙패드는 계속 사용할 수 있습니다",
        cleaningKeepScreenVisibleToggle: "화면을 켠 상태로 유지",
        cleaningKeepScreenVisibleCaption: "화면을 끄지 않고 구석에 눈에 띄지 않는 표시줄을 표시합니다.",
        cleaningStartNow: "지금 키보드 잠그기",
        cleaningNeedsAxTitle: "손쉬운 사용 권한이 필요합니다",
        cleaningNeedsAxBody: "키보드를 안전하게 잠그려면 Vorssaint에 손쉬운 사용 권한이 필요합니다. 시스템 설정에서 허용한 뒤 다시 시도하세요.",

        tabSupport: "지원",
        shortcutsPageCaption: "이 Mac에 설치된 기능의 모든 전역 단축키를 여기에서 편집할 수 있습니다. 비활성 단축키도 저장되지만 실행되지는 않습니다.",
        shortcutsPageTitle: "키보드 단축키",
        settingsSearchPlaceholder: "설정 검색",
        donateHeading: "Vorssaint의 성장을 도와주세요",
        donateMessage: "Vorssaint는 무료로 독립적으로 운영되며 여유 시간에 개발하고 있습니다. 금전적으로 돕고 싶다면 Buy Me a Coffee를 통한 지원이 개발을 이어 가는 데 직접 도움이 됩니다.",
        donateButton: "Buy Me a Coffee에서 후원하기",
        donateThanks: "들러 주셔서 감사합니다. 🖤",
        supportIntroTitle: "Vorssaint의 성장을 도와주세요",
        supportIntroMessage: "개발을 금전적으로 돕고 싶다면 Buy Me a Coffee가 유일한 후원 창구입니다.",
        supportIntroStarButton: "GitHub에서 Vorssaint에 별표 남기기",
        supportIntroStarMessage: "금전적인 후원은 전혀 기대하지 않습니다. GitHub의 별표 하나가 더 많은 사람이 Vorssaint를 발견하게 하고 개발에도 큰 힘이 됩니다.",
        supportIntroCoffeeButton: "Buy Me a Coffee에서 후원하기",
        supportIntroLaterButton: "나중에",
        supportIntroDoneButton: "완료",
        discordIntroTitle: "Vorssaint Discord 커뮤니티가 이제 시작됩니다",
        discordIntroMessage: "Vorssaint 커뮤니티는 새롭게 만들어지는 중입니다. 일찍 참여해 다른 사용자와 만나고 앱을 중심으로 따뜻한 공간을 함께 만들어 주세요.",
        discordIntroJoinButton: "Discord 커뮤니티 참여",
        communityIntroTitle: "누구보다 먼저 새 기능 확인",
        communityIntroMessage: "이미 X에서 저를 팔로우한 분들은 이번 업데이트의 여러 변경 사항을 누구보다 먼저 확인했습니다. X에서는 다음 기능의 미리보기와 사용 방법을 소개하므로 업데이트가 나오기 전부터 기본 사용법을 알 수 있습니다. 팔로우하고 다음 소식을 먼저 확인해 보세요!",
        communityIntroFollowButton: "X에서 @vorssaint 팔로우",
        homebrewOfficialIntroTitle: "이제 Homebrew 공식 카탈로그에서 제공",
        homebrewOfficialIntroMessage: "이제 Homebrew 공식 카탈로그에서 Vorssaint를 바로 설치할 수 있습니다.",
        homebrewOfficialIntroInstallLabel: "새로 설치",
        homebrewOfficialIntroMigrationTitle: "기존 tap을 사용하셨나요?",
        homebrewOfficialIntroMigrationMessage: "기존 tap을 한 번 제거하세요. 앱과 설정은 그대로 유지됩니다.",
        homebrewOfficialIntroCopyButton: "명령 복사",
        updateShowcaseTitle: "3.1.4의 새로운 기능",
        updateShowcaseMessage: "이 업데이트의 주요 개선 사항을 짧은 미리보기로 확인할 수 있습니다.",
        updateShowcaseUnavailable: "지금은 동영상을 불러올 수 없습니다. 계속 진행할 수 있습니다.",
        updateShowcaseRestart: "처음부터 다시 보기",
        showMenuBarIcon: "메뉴 막대에 아이콘 표시",
        showMenuBarIconCaption: "Vorssaint 아이콘이 사라진 경우(메뉴 막대 공간이 부족하면 macOS가 아이콘을 숨길 수 있으며 노치가 있는 Mac에서 특히 흔합니다) 응용 프로그램 또는 Spotlight에서 Vorssaint를 다시 여세요. 아이콘을 다시 만들고, 그래도 숨겨져 있으면 이 윈도우가 열립니다.",
        menuBarIconStillHiddenTitle: "아이콘이 아직 숨겨져 있습니다",
        menuBarIconStillHiddenBody: "아이콘을 다시 만들었지만 macOS가 표시할 공간을 할당하지 않았습니다. 메뉴 막대에 빈 공간이 없을 가능성이 높습니다. 메뉴 막대 아이콘을 일부 줄이거나 메뉴가 긴 앱을 닫은 뒤 다시 시도하세요.",
        menuBarIconManagerHintFormat: "%@이(가) 실행 중이며 아이콘을 숨김 섹션에 넣었을 수 있습니다. 그곳에서 Vorssaint를 찾거나 %@에서 Vorssaint가 항상 표시되도록 설정하세요.",
        shortcutRecording: "새 단축키를 누르세요",
        shortcutReset: "재설정",
        shortcutNone: "없음",
        shortcutClear: "단축키 지우기",
        shortcutInvalid: "Control, Option 또는 Command 중 하나와 다른 키를 함께 누르세요.",
        shortcutPressKeys: "키를 누르세요",
        shortcutEscapeHint: "Esc로 취소합니다.",
        shortcutDeleteHint: "Delete로 지웁니다.",
        shortcutNotCaptured: "아무것도 기록되지 않았습니다. macOS 또는 다른 앱이 이미 이 조합을 사용하고 있습니다. 다른 조합을 선택하세요.",
        shortcutConflictFormat: "이 단축키는 이미 %@에서 사용 중입니다.",
        shortcutUnavailable: "macOS가 이 단축키를 거부했습니다. 다른 단축키를 선택하세요.",
        shelfShortcutToggle: "선반 단축키",
        switcherUsageHintFormat: "%@을(를) 누른 채 이동하고 놓으면 윈도우가 활성화됩니다. Shift 또는 ←로 뒤로 이동하고, W로 윈도우를 닫고, Q로 앱을 종료하며, Esc로 취소합니다.",
        musicBlockSection: "미디어 키",
        musicBlockTitle: "음악 앱이 저절로 열리지 않게 하기",
        musicBlockCaption: "미디어 키를 눌러도 음악 앱이 열리지 않습니다. 직접 여는 것은 가능합니다.",
        musicBlockReplacementLabel: "대신 열기",
        musicBlockReplacementNone: "없음",
        musicBlockChooseApp: "앱 선택…",
        cleanerName: "정리",
        cleanerIntroTitle: "Mac의 불필요한 파일 정리",
        cleanerIntroCaption: "삭제한 앱의 남은 파일, 캐시, 로그와 휴지통을 검사합니다. 실행 전에 모두 검토할 수 있고 삭제한 항목은 휴지통으로 이동합니다.",
        cleanerScan: "검사",
        cleanerScanning: "검사 중…",
        cleanerCleaning: "정리 중…",
        cleanerCatLeftovers: "삭제한 앱의 남은 파일",
        cleanerCatLoginItems: "고아 로그인 항목",
        cleanerCatCaches: "캐시",
        cleanerCatLogs: "로그",
        cleanerCatDeveloper: "개발 정크",
        cleanerCatTrash: "휴지통",
        cleanerLeftoversNote: "분석으로 감지하므로 처음에는 선택 해제됩니다. 선택하기 전에 경로를 검토하세요.",
        cleanerLoginItemsNote: "로그인 항목 표시는 Mac을 재시작하면 사라집니다.",
        cleanerTrashNote: "휴지통을 비우면 되돌릴 수 없습니다.",
        cleanerCatDeviceBackups: "iPhone 백업",
        cleanerDeviceBackupsCaption: "오래된 iPhone 및 iPad 백업은 macOS가 ‘기타’라고 부르는 공간의 큰 부분을 차지할 수 있습니다. 필요 없는 항목만 삭제하세요. 다음에 기기를 연결하면 새 백업을 만들 수 있습니다.",
        cleanerNothingFound: "정리할 항목이 없습니다. Mac이 깔끔합니다.",
        cleanerClean: "정리",
        cleanerDoneNote: "항목을 휴지통으로 이동했으며 그곳에서 복원할 수 있습니다.",
        cleanerAgain: "다시 검사",
        cleanerRevealInFinder: "Finder에서 보기",
        cleanerPanelCaption: "앱 잔여 파일, 캐시 및 로그",
        cleanerSafeSection: "안전한 정리",
        cleanerOptionalSection: "선택 사항, 먼저 검토",
        cleanerCatOtherCaches: "기타 캐시",
        cleanerCachesCaption: "앱이 자동으로 다시 만드는 임시 파일입니다.",
        cleanerLogsCaption: "오래된 진단 로그입니다.",
        cleanerDeveloperCaption: "Xcode 빌드와 시뮬레이터의 남은 파일입니다.",
        cleanerLoginItemsCaption: "더 이상 존재하지 않는 앱이 남긴 로그인 항목입니다.",
        cleanerLeftoversCaption: "삭제한 앱이 남긴 파일입니다.",
        cleanerOtherCachesCaption: "삭제해도 안전하며 망가지는 것은 없습니다. 처음 실행할 때 약간 느려질 수 있고 오프라인 음악 같은 다운로드 콘텐츠는 다시 다운로드됩니다.",
        cleanerCleanSizeFormat: "%@ 정리",
        cleanerScheduleTitle: "자동 정리",
        cleanerScheduleOff: "끔",
        cleanerScheduleDaily: "매일",
        cleanerScheduleWeekly: "매주",
        cleanerScheduleCaption: "선택한 시간에 안전한 항목만 자동으로 정리하고 모두 휴지통으로 이동합니다.",
        cleanerScheduleLastFormat: "지난 자동 정리에서 %@을(를) 확보했습니다.",
        cleanerAutoNotificationFormat: "%@을(를) 확보하여 휴지통으로 이동했습니다.",
        cleanerScheduleNextFormat: "다음 정리: %@.",
        cleanerScheduleRanFormat: "지난 자동 정리: %@.",
        cleanerScheduleNotifyToggle: "완료 시 알림",
        cleanerNotifDenied: "시스템에서 Vorssaint 알림이 꺼져 있습니다.",
        cleanerNotifOpenSettings: "알림 설정 열기…",
        launchAtLoginNeedsApplications: "로그인 시 열 수 없는 위치에서 앱이 실행되고 있습니다. Vorssaint를 응용 프로그램 폴더로 드래그한 다음 거기에서 열고 이 옵션을 다시 켜 주세요.",
        launchAtLoginNeedsApproval: "로그인 항목은 등록되었지만 시스템 설정에서는 여전히 꺼져 있습니다. 시스템 설정 › 일반 › 로그인 항목 및 확장 프로그램을 열고 ‘로그인 시 열기’에서 Vorssaint를 켜 주세요.",
        ocrRemoveLineBreaksToggle: "줄바꿈 제거",
        ocrRemoveLineBreaksCaption: "인식한 텍스트의 줄바꿈을 제거하여 한 문단으로 붙여 넣습니다.",
        ocrQRToggle: "QR 코드 읽기",
        ocrQRCaption: "영역에 QR 코드가 있으면 그 내용을 복사하거나 열 수 있도록 보여 줍니다.",
        ocrQRCopied: "QR 코드를 복사했습니다",
        qrResultTitle: "QR 코드",
        qrResultCopy: "복사",
        qrResultOpen: "링크 열기",
        highlightsTitle: "이 업데이트의 새로운 기능",
        highlightsTitleClipboardRedesign: "새로워진 클립보드",
        highlightsTitleWindowLayout: "윈도우 레이아웃",
        highlightsTitleQuitProtection: "⌘Q 및 ⌘W 보호",
        highlightsTitleRecorderBlur: "화면 녹화 흐림 효과",
        highlightsCaptionDockPreview: "Dock Preview가 이제 Dock 확대가 켜져 있어도 작동합니다",
        highlightsCaptionScreenshot: "스크린샷 도구에 픽셀 루페와 QR 코드 읽기가 추가되었습니다",
        highlightsCaptionSnippetLibrary: "검색 가능한 스니펫 메뉴가 커서 위치에 스니펫을 입력합니다",
        highlightsCaptionCapturePalette: "단축키 하나로 스크린샷, 화면 녹화, 화면 텍스트 및 색상 추출과 관련 설정을 한곳에서 제어하는 플로팅 팔레트가 열립니다.",
        highlightsCaptionClipboardRedesign: "기록이 이제 깔끔한 행과 전체 항목을 확인하거나 편집할 수 있는 맞춤형 미리보기를 갖춘 컴팩트 팔레트로 열립니다.",
        highlightsCaptionWindowLayout: "단축키와 포인터를 사용한 방향 링으로 창을 배치하거나 화면 가장자리로 드래그하여 맞춤 간격으로 스냅할 수 있습니다.",
        highlightsCaptionQuitProtection: "길게 누르기, 두 번 누르기 또는 추가 수정 키를 요구하여 앱이나 창이 실수로 닫히는 것을 방지합니다. 앱별로 설정할 수 있습니다.",
        highlightsCaptionRecorderBlur: "비디오를 저장하거나 내보내기 전에 녹화본의 원하는 영역과 구간에서 비밀번호나 개인 정보를 흐리게 가릴 수 있습니다.",
        highlightsConfigure: "설정하기",
        highlightsTry: "사용해 보기",
        highlightsSeeAll: "모든 변경 사항 보기",
        switcherCurrentSpaceOnly: "현재 데스크탑만 표시",
        switcherCurrentSpaceOnlyCaption: "지금 있는 데스크탑의 윈도우만 전환기에 표시합니다. 윈도우를 선택해도 다른 데스크탑으로 이동하지 않습니다.",
        shelfFileMissing: "파일이 더 이상 존재하지 않습니다",
        previewSizeSmall: "작게",
        mixerSoundEffectsOutputTitle: "시스템 사운드",
        mixerSoundEffectsOutputTooltip: "알림 및 사운드 효과를 재생할 출력 선택",
        monitorOpenActivityMonitor: "활성 상태 보기 열기",
        dockClickHide: "Dock 클릭으로 앱 숨기기",
        dockClickHideCaption: "활성 앱의 Dock 아이콘을 클릭하면 앱이 숨겨집니다. 다시 클릭하면 돌아옵니다.",
        monitorMemoryMetricLabel: "메모리 측정 방식",
        memoryMetricUsed: "사용 중인 메모리",
        memoryMetricApp: "앱 메모리",
        keepAwakeRightClickToggle: "메뉴 막대 아이콘을 오른쪽 클릭하여 절전 방지 전환",
        keepAwakeRightClickToggleCaption: "오른쪽 클릭 메뉴를 대체합니다.",
        urlCleanerRulesTitle: "정리 규칙",
        urlCleanerRulesCaption: "사이트가 자체 공유 링크에 붙여 링크의 출처를 추적하는 매개변수입니다. 체크한 이름은 링크를 정리할 때 제거되고, 해제하면 남습니다. 직접 추가한 이름은 삭제할 수 있습니다.",
        urlCleanerRulesCoverageCaption: "목록은 한 사이트의 여러 공유 경로(웹 페이지, 앱, 라이브 방송)를 모두 담고 있어 길어집니다. 실제 링크에는 보통 2~4개만 붙습니다.",
        urlCleanerRulesAllSites: "모든 사이트",
        urlCleanerRulesCountSingular: "매개변수 1개",
        urlCleanerRulesCountPluralFormat: "매개변수 %d개",
        urlCleanerRulesAddSite: "사이트 추가",
        urlCleanerRulesParameterPlaceholder: "매개변수 이름",
        urlCleanerRulesMatchCaption: "= 왼쪽의 이름을 입력하세요(예: utm_source). 일치한 이름은 그 매개변수만 링크에서 빼고 나머지는 그대로 둡니다.",
        urlCleanerRulesAddButton: "추가",
        urlCleanerRulesRemoveButton: "이름 삭제",
        urlCleanerRulesRemoveSiteButton: "이 사이트의 규칙 모두 끄기",
        urlCleanerRemovedFormat: "%@ 삭제함",
        switcherSearchPin: "S로 검색창 고정",
        switcherSearchPinCaption: "S를 누르면 검색을 시작하고 전환기를 고정합니다. 단축키가 ⌥를 사용할 때 특수 문자가 입력되는 문제와, Q나 W로 시작하는 검색이 창을 닫거나 앱을 종료시키는 문제를 모두 막아줍니다.",
        invertVerticalScroll: "세로 스크롤 반전",
        invertHorizontalScroll: "가로 스크롤 반전",
        switcherShowShortcutHints: "단축키 힌트 보기",
        switcherShowShortcutHintsCaption: "아이콘 아래에 앱 및 윈도우 단축키를 표시합니다.",
        uninstallerHomebrewPackageFormat: "%@도 Homebrew에서 제거됩니다.",
        shelfEdgeToggle: "화면 가장자리 근처에서 열기",
        shelfEdgeCaption: "파일을 화면 가장자리 쪽으로 드래그하면 선반이 살짝 나타납니다. 그 자리에 놓거나, 다시 뒤로 당기면 선반이 들어갑니다.",
        focusFollowsMouseName: "마우스를 따라 포커스",
        focusFollowsMouseCaption: "잠시 멈춘 뒤 포인터 아래의 윈도우에 포커스를 주고 앞으로 가져옵니다.",
        focusFollowsMouseDelay: "호버 지연",
        switcherMinimizedPlacementLabel: "최소화된 윈도우",
        switcherMinimizedPlacementNormal: "일반 순서",
        switcherMinimizedPlacementEnd: "끝으로 보내기",
        switcherMinimizedPlacementHidden: "숨기기",
        switcherShowFullscreenWindows: "전체 화면 윈도우 표시",
        switcherScreenPlacementLabel: "표시 위치",
        switcherScreenPlacementPointer: "포인터가 있는 화면",
        switcherScreenPlacementMenuBar: "메뉴 막대가 있는 화면",
        switcherScreenPlacementActiveWindow: "활성 윈도우가 있는 화면",
        switcherScreenPlacementCaption: "화면이 두 개 이상 연결되어 있을 때 전환기를 어느 화면에 표시할지 선택합니다.",
        smoothScrollResponseLabel: "반응 속도",
        mouseAccelerationName: "마우스 가속 끄기",
        mouseAccelerationCaption: "연결된 마우스의 포인터 가속을 끕니다. 옵션을 끄거나 Vorssaint를 종료하면 이전 설정으로 복원됩니다.",
        shelfClearOnClose: "닫을 때 항목 지우기",
        shelfClearOnCloseCaption: "닫기 버튼을 클릭할 때만 선반을 비웁니다. 자동으로 숨겨지거나 접을 때는 항목을 유지합니다."
    )
}
