// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Italiano — translated and hand-checked, not machine output.
extension Strings {
    static let it = Strings(
        statusIdleTooltip: "Vorssaint: stop normale",
        statusActiveUntil: "Vorssaint: attivo fino alle",
        statusActiveIndefinite: "Vorssaint: attivo a tempo indeterminato",
        menuEnableAwake: "Attiva mantieni attivo",
        menuDisableAwake: "Disattiva mantieni attivo",
        menuActivateFor: "Attiva per…",
        menuSettings: "Impostazioni…",
        menuAbout: "Informazioni su Vorssaint",
        menuQuit: "Esci da Vorssaint",
        menuHide: "Nascondi Vorssaint",
        menuHideOthers: "Nascondi gli altri",
        menuShowAll: "Mostra tutto",
        menuEdit: "Modifica",
        menuUndo: "Annulla",
        menuRedo: "Ripristina",
        actionClear: "Cancella",
        actionRemove: "Rimuovi",
        actionBack: "Indietro",
        actionSearch: "Cerca",
        actionMute: "Silenzia",
        actionUnmute: "Riattiva audio",
        actionPlay: "Riproduci",
        actionPause: "Pausa",
        menuCut: "Taglia",
        menuCopy: "Copia",
        menuPaste: "Incolla",
        menuSelectAll: "Seleziona tutto",
        menuWindow: "Finestra",
        menuMinimize: "Riduci",
        menuZoom: "Zoom",
        menuClose: "Chiudi",

        minutes15: "15 minuti",
        minutes30: "30 minuti",
        hour1: "1 ora",
        hours2: "2 ore",
        hours4: "4 ore",
        hours8: "8 ore",
        indefinitely: "A tempo indeterminato",
        indefinite: "Indeterminato",

        panelSettings: "Impostazioni",
        panelQuit: "Esci",
        panelHotkeyHint: "La scorciatoia attiva/disattiva",

        keepAwakeTitle: "Mantieni attivo",
        keepAwakeEndsIn: "Termina tra",
        keepAwakeUntilDisabled: "Attivo finché non lo disattivi",
        keepAwakeNormalRules: "Il Mac segue le normali regole di risparmio energia",
        keepAwakeOptions: "Opzioni",
        keepAwakeMouseJiggle: "Muovi leggermente il puntatore",
        keepAwakeMouseJiggleCaption: "Durante una sessione, muove un po’ il puntatore all’intervallo scelto.",
        keepAwakeMouseJiggleInterval: "Intervallo",
        keepAwakeActiveIconLabel: "Icona attiva",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Caffè",
        keepAwakeActiveIconEye: "Occhio",
        keepAwakeActiveIconMoon: "Luna",
        keepAwakeActiveIconLight: "Lampadina",
        keepAwakeIconTintLabel: "Colore icona attiva",
        keepAwakeIconTintOrange: "Arancione",
        keepAwakeIconTintGreen: "Verde",
        keepAwakeIconTintBlue: "Blu",
        keepAwakeIconTintPurple: "Viola",
        keepAwakeIconTintPink: "Rosa",
        keepAwakeIconTintNone: "Nessun colore",
        durationLabel: "Durata",
        clamshellTitle: "Continua con il coperchio chiuso",
        clamshellOnCaption: "Stop completamente disattivato. Attenzione alla carica",
        clamshellNeedsSession: "Si applica ogni volta che “Mantieni attivo” è attivo",
        clamshellReady: "Pronto. Si attiva e disattiva senza password",
        clamshellNeedsPassword: "Richiede la password di amministratore una volta",

        systemSection: "Sistema",
        temperatures: "Temperature",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batteria",
        usageSection: "Utilizzo hardware",
        memorySection: "Memoria",
        memoryPressure: "Pressione",
        memorySwapUsed: "Swap usato",
        memoryCompressed: "Compressa",
        memoryCachedFiles: "File in cache",
        pressureNormal: "Normale",
        pressureWarning: "Attenzione",
        pressureCritical: "Critica",
        monitorUnavailable: "Sensori non disponibili su questo Mac",
        energyAppsTitle: "Consumo energia rilevante",
        energyAppsIdle: "Nessun consumo energia rilevante",

        notifySessionEndedTitle: "Sessione terminata",
        notifySessionEndedBody: "Il tempo è scaduto. Il Mac tornerà allo stop normale.",
        notifyBatteryTitle: "Vorssaint disattivato",
        notifyBatteryBody: "Batteria scarica. Lo stop normale è stato ripristinato per preservare la carica.",
        adminPromptClamshellOn: "Vorssaint ha bisogno della password per continuare con il coperchio chiuso.",
        adminPromptClamshellOff: "Vorssaint ha bisogno della password per ripristinare lo stop normale del Mac.",
        adminPromptRecover: "Vorssaint è stato chiuso mentre lo stop del Mac era disattivato. Inserisci la password per ripristinare lo stop normale.",
        adminPromptUpdate: "Vorssaint ha bisogno della tua password per installare l’aggiornamento.",
        adminPromptSudoersInstall: "Vorssaint creerà una regola limitata (solo pmset disablesleep) per attivare la modalità a coperchio chiuso senza chiedere la password. È l’unica volta che la password è necessaria.",
        adminPromptSudoersRemove: "Vorssaint rimuoverà la regola del coperchio chiuso senza password.",

        settingsTitle: "Impostazioni di Vorssaint",
        tabGeneral: "Generali",
        tabEnergy: "Energia",
        tabMouse: "Mouse e trackpad",
        tabSwitcher: "Commutatore",
        tabAdvanced: "Avanzate",
        tabAbout: "Informazioni",
        tabReleaseNotes: "Novità",
        releaseNotesOnUpdateToggle: "Mostra le novità dopo l’aggiornamento",
        minimalWindowPreviews: "Anteprime minimaliste",
        minimalWindowPreviewsCaption: "Nasconde titoli, pulsanti e decorazioni nelle anteprime del Dock e del selettore di app. La selezione resta visibile.",
        previewSizeLabel: "Dimensione anteprime",
        previewSizeNormal: "Normale",
        previewSizeLarge: "Grande",
        previewSizeXLarge: "Molto grande",
        settingsGroupFeatures: "Funzioni",
        advancedResetSection: "Autorizzazioni",
        advancedResetDescription: "Rimuove tutte le autorizzazioni concesse a Vorssaint (Accessibilità, Registrazione schermo, Accesso completo al disco e altre), l’elemento di login e la regola del coperchio chiuso. Utile per ripartire da zero o prima di disinstallare. L’app resta installata.",
        advancedClearButton: "Cancella tutte le autorizzazioni",
        advancedCleared: "Autorizzazioni cancellate.",
        advancedClearConfirmTitle: "Cancellare tutte le autorizzazioni?",
        advancedClearConfirmBody: "Le funzioni che richiedono autorizzazioni smetteranno di funzionare finché non le concederai di nuovo. Le tue impostazioni vengono mantenute.",
        advancedUninstallSection: "Disinstalla",
        advancedUninstallDescription: "Fa tutto quanto sopra, poi rimuove le preferenze e sposta Vorssaint nel Cestino, senza lasciare tracce. L’app si chiude al termine. Puoi reinstallarla quando vuoi.",
        advancedUninstallButton: "Disinstalla completamente Vorssaint",
        advancedUninstallConfirmTitle: "Disinstallare Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint cancellerà le autorizzazioni, rimuoverà le preferenze e si sposterà nel Cestino, poi si chiuderà. Questa azione non può essere annullata dall’app, ma resta nel Cestino finché non lo svuoti.",
        advancedUninstallFailedTitle: "Disinstallazione interrotta",
        advancedUninstallFailedBody: "Vorssaint non è riuscito a ripristinare un’impostazione di sistema che aveva cambiato: lo stop, la velocità delle ventole o l’accelerazione del mouse. Non è stato rimosso nulla. Riprova e consenti la richiesta della password, se compare.",

        launchAtLogin: "Apri al login",
        languageLabel: "Lingua",
        menuBarSection: "Barra dei menu",
        showCountdown: "Mostra il tempo rimanente accanto all’icona",
        globalHotkeySection: "Scorciatoia globale",
        hotkeyToggle: "Abilita scorciatoia per “Mantieni attivo”",
        hotkeyCaption: "Funziona in qualsiasi app, senza autorizzazioni aggiuntive.",

        sessionSection: "Sessione",
        defaultDurationLabel: "Durata predefinita",
        keepAwakeAutoStart: "Mantieni attivo all’apertura di Vorssaint",
        keepAwakeAutoStartCaption: "Avvia una sessione con la durata predefinita.",
        batteryProtectionSection: "Protezione della batteria",
        batteryDisableBelow: "Disattiva quando la batteria scende sotto",
        batteryNever: "Mai",
        batteryProtectionCaption: "Evita che una sessione dimenticata scarichi la batteria del MacBook.",
        clamshellSection: "Coperchio chiuso",
        configuring: "Configurazione…",
        sudoersFailed: "Impossibile attivare il coperchio chiuso. Riprova.",
        clamshellExplanation: "“Continua con il coperchio chiuso” disattiva completamente lo stop mentre “Mantieni attivo” è attivo e viene ripristinato automaticamente al termine della sessione o alla chiusura dell’app. È preferibile usarlo collegato all’alimentazione.",

        scrollSection: "Scorrimento",
        invertMouseScroll: "Inverti lo scorrimento del mouse",
        invertMouseScrollCaption: "Inverte la direzione della rotellina del mouse.",
        scrollTrackpadNote: "Il trackpad resta invariato: mantiene lo scorrimento naturale di macOS.",
        scrollActiveNow: "Scorrimento del mouse invertito ora",
        mouseNavigationActiveNow: "Tasti laterali attivi ora",
        smoothScrollName: "Scorrimento fluido",
        smoothScrollCaption: "Trasforma ogni scatto della rotellina del mouse in una breve scivolata fluida. Il trackpad non cambia.",
        smoothScrollStepLabel: "Velocità di scorrimento",
        mouseNavigationSection: "Navigazione",
        mouseNavigationEnable: "Usa i pulsanti laterali per Indietro e Avanti",
        mouseNavigationCaption: "Trasforma i pulsanti Indietro e Avanti del mouse in comandi di navigazione per Finder, browser e app compatibili.",
        middleClickSection: "Clic centrale",
        middleClickEnable: "Il clic con tre dita agisce da clic centrale",
        middleClickEnableCaption: "Premere il trackpad con tre dita funziona come il clic della rotellina del mouse: aprire i link in una nuova scheda, chiudere le schede e tutto ciò che fa il tasto centrale.",
        middleClickDragConflict: "Il trascinamento a tre dita di macOS è attivo e usa lo stesso gesto. Disattivalo in Impostazioni di Sistema, in Accessibilità, Controllo puntatore, Opzioni trackpad, e il clic centrale funzionerà.",
        middleClickTapPicker: "Anche un tocco leggero fa clic",
        middleClickTapOff: "Disattivato",
        middleClickTapThreeFingers: "3 dita",
        middleClickTapFourFingers: "4 dita",
        middleClickTapCaption: "Un tocco leggero con quel numero di dita, senza premere, attiva anche il clic centrale. Scorrere non conta mai. Se il tocco a tre dita di macOS è assegnato a Cerca, disattivalo perché i due non si attivino insieme.",
        quickToolsTab: "Pannello rapido",
        quickToolShortcutToggle: "Abbreviazione globale",
        ocrName: "Copia testo dallo schermo",
        ocrCaption: "Seleziona un’area dello schermo e il testo riconosciuto viene copiato, pronto da incollare.",
        ocrCopied: "Testo copiato",
        ocrNoText: "Nessun testo trovato",
        colorPickerName: "Contagocce colore",
        colorPickerCaption: "Cattura il colore di qualsiasi pixel sullo schermo e copialo nel formato che preferisci.",
        colorPickerFormatLabel: "Formato copiato",
        colorPickerBareHexToggle: "Copia senza il prefisso #",
        colorPickerPickNow: "Preleva colore",
        micMuteName: "Silenzia microfono",
        micUnmuteName: "Riattiva microfono",
        micMuteCaption: "Taglia il microfono del Mac con un clic o un’abbreviazione, in qualsiasi app.",
        micMutedHUD: "Microfono silenziato",
        micUnmutedHUD: "Microfono riattivato",
        micMuteMenuBarToggle: "Mostra nella barra dei menu quando è silenziato",
        micMuteMenuBarCaption: "Un microfono barrato in rosso appare accanto all’icona dell’app nella barra dei menu.",
        pastePlainName: "Incolla come testo semplice",
        pastePlainCaption: "Incolla ciò che hai copiato senza colori, font o formattazione. L’originale resta negli appunti.",
        launcherName: "Pannello rapido",
        launcherCaption: "Un pannello fluttuante con i tuoi strumenti preferiti, richiamato con un’abbreviazione da ovunque.",
        launcherOpenNow: "Apri pannello rapido",
        launcherEditHint: "Usa il pulsante di regolazione per scegliere, nascondere e trascinare gli strumenti.",
        launcherEmptyState: "Tutti gli strumenti sono nascosti. Usa il pulsante di regolazione per riaverli.",
        launcherAddSection: "Aggiungi di nuovo",
        launcherKeysHint: "Le frecce navigano, Invio apre, 1 a 9 aprono direttamente",
        switcherSection: "Commutatore app",
        switcherEnable: "Usa il commutatore di Vorssaint",
        switcherEnableCaption: "Passa tra app e finestre, incluse quelle ridotte a icona e più finestre della stessa app.",
        switcherUsageHint: "Tieni premuta la scorciatoia per spostarti; rilascia per attivare la finestra. Maiuscole o ← torna indietro; W chiude la finestra; Q chiude l’app; Esc annulla.",
        switcherNoWindows: "Nessuna finestra aperta",
        switcherIconRowMode: "Mostra %@ con icone grandi",
        switcherIconRowModeCaption: "Mostra un’icona per app con le anteprime delle sue finestre sopra.",
        switcherSimpleMode: "Selettore app semplice",
        switcherSimpleModeCaption: "Mostra icone delle app e titoli delle finestre, senza anteprime né acquisizione dello schermo dal selettore.",
        switcherShortcutHintApps: "App",
        switcherShortcutHintWindows: "Finestre",
        switcherWindowShortcutCaption: "Apre un selettore per le finestre dell’app in primo piano. Con il selettore app aperto, salta tra le finestre dell’app selezionata.",
        switcherTakeOverSystemShortcuts: "Sostituisci ⌘Tab e ⌘` di macOS",
        switcherTakeOverSystemShortcutsCaption: "Disattiva le scorciatoie macOS corrispondenti solo mentre il selettore Vorssaint è attivo. Tutte le app aperte restano raggiungibili.",
        switcherAppearanceDelay: "Ritardo di comparsa",
        switcherAppearanceDelayCaption: "Per quanto tempo va tenuta premuta la scorciatoia prima che appaia il selettore.",
        switcherMergeTabs: "Mostra una voce per app",
        switcherMergeTabsCaption: "Raggruppa tutte le finestre di un’app in un’unica voce nel commutatore, anziché una per finestra.",
        switcherWindowlessApps: "App senza finestre aperte",
        switcherWindowlessAppsCaption: "Sceglie quali app aperte senza alcuna finestra compaiono nel commutatore.",
        switcherWindowlessAppsOff: "Non mostrare",
        switcherWindowlessAppsFinder: "Solo il Finder",
        switcherWindowlessAppsAll: "Tutte le app",
        switcherNoOpenWindow: "Senza finestre aperte",
        switcherOtherDesktop: "Altra scrivania",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Anteprima finestre dal Dock",
        dockPreviewEnableCaption: "Passa il mouse su un’app aperta nel Dock per vedere le sue finestre, poi fai clic su quella da aprire.",
        dockPreviewBackgroundOpacity: "Sfondo del pannello",
        dockPreviewBackgroundOpacityCaption: "Abbassalo per vedere di più di ciò che sta dietro al pannello.",
        dockPreviewOpenDelay: "Ritardo di apertura",
        dockPreviewOpenDelayCaption: "Quanto a lungo il puntatore deve restare su un’icona prima che il pannello si apra.",
        dockPreviewQuitAppOnClose: "Chiudi l’app con il pulsante ×",
        dockPreviewQuitAppOnCloseCaption: "In Dock Preview, × chiude l’intera app invece della sola finestra.",
        dockClickMinimize: "Riduci con un clic sul Dock",
        dockClickMinimizeCaption: "Le finestre dell’app attiva si riducono nel Dock cliccando la sua icona. Fai clic di nuovo per ripristinarle.",
        dockClickCycleWindows: "Clic sul Dock per alternare le finestre",
        dockClickCycleWindowsCaption: "Fai clic sull’icona nel Dock dell’app attiva per passare da una finestra all’altra, come ⌘`.",
        dockPreviewActiveNow: "Attivo nel Dock",
        dockPreviewDockUnavailable: "Impossibile leggere gli elementi del Dock.",
        dockPreviewAutohideBeta: "Beta. Potresti riscontrare alcuni bug.",
        dockPreviewOpenWindow: "Apri finestra",
        dockPreviewCloseWindow: "Chiudi finestra",
        dockPreviewMinimizeWindow: "Riduci finestra",
        dockPreviewRestoreWindow: "Ripristina finestra",
        dockPreviewPinPanel: "Fissa anteprima",
        dockPreviewUnpinPanel: "Sblocca anteprima",
        dockPreviewPinned: "Fissata",
        dockPreviewClosePanel: "Chiudi anteprima",
        dockPreviewPreviousWindow: "Finestra precedente",
        dockPreviewNextWindow: "Finestra successiva",

        cutPasteName: "Taglia e incolla",
        cutPasteEnable: "Taglia e incolla i file nel Finder",
        cutPasteEnableCaption: "Usa ⌘X per tagliare e ⌘V per spostare file e cartelle nel Finder.",
        cutPasteShowHUD: "Mostra pannello mobile",
        cutPasteShowHUDCaption: "Mostra un indicatore mobile con i file tagliati mentre il Finder è attivo.",
        cutPasteHowTitle: "Come si usa",
        cutPasteStep1: "Seleziona elementi nel Finder e premi ⌘X per tagliarli.",
        cutPasteStep2: "Apri la cartella di destinazione e premi ⌘V per spostarli lì.",
        cutPasteTextNote: "Nei campi di testo (ad esempio quando rinomini), ⌘X e ⌘V continuano a funzionare normalmente.",
        cutPasteActiveNow: "Pronto a tagliare nel Finder",
        cutPasteAutomationNote: "La prima volta, macOS chiede l’autorizzazione a controllare il Finder.",
        cutReadyTitle: "Tagliato",
        cutReadyHint: "nella cartella di destinazione per spostare",
        cutCancel: "Annulla taglio",
        cutDoneTitle: "Spostato!",
        cutMovedSingular: "1 elemento spostato",
        cutMovedPluralFormat: "%d elementi spostati",
        cutSomeFailed: "Impossibile spostare alcuni elementi",
        cutMovingTitle: "Spostamento…",
        cutMovingCountFormat: "%d di %d",

        autoQuitName: "Esci alla chiusura",
        autoQuitEnable: "Esci da un’app quando si chiude la sua ultima finestra",
        autoQuitEnableCaption: "Chiudere l’ultima finestra di un’app la fa anche uscire.",
        autoQuitActiveNow: "Attivo ora",
        autoQuitHowTitle: "Come funziona",
        autoQuitStep1: "Chiudi l’ultima finestra di un’app (⌘W o il pulsante rosso).",
        autoQuitStep2: "L’app esce da sola. I dialoghi “Salvare le modifiche?” continuano ad apparire.",
        autoQuitPredictableNote: "Le app che di norma funzionano senza finestre non vengono mai chiuse.",
        autoQuitExceptionsTitle: "Eccezioni",
        autoQuitExceptionsCaption: "Le app in questo elenco restano aperte anche senza finestre.",
        autoQuitExceptionsEmpty: "Nessuna eccezione",
        autoQuitAddApp: "Aggiungi app…",

        uninstallerName: "Disinstallatore",
        uninstallerEnableCaption: "Rimuove un’app insieme a cache, preferenze, log e residui che lascia in giro.",
        uninstallerStep1: "Trascina un’app nelle Impostazioni oppure scegline una dall’elenco.",
        uninstallerStep2: "Controlla i file trovati e quanto spazio occupano.",
        uninstallerStep3: "Sposta ciò che vuoi nel Cestino. Nulla viene eliminato in modo definitivo.",
        uninstallerMenuItem: "Disinstalla un’app…",
        uninstallerDropTitle: "Trascina qui un’app",
        uninstallerDropSubtitle: "oppure scegline una da analizzare",
        uninstallerChoose: "Scegli app…",
        uninstallerPickerTitle: "Scegli app",
        uninstallerPickerSearch: "Cerca app",
        uninstallerPickerEmpty: "Nessuna app trovata",
        uninstallerEmptyNote: "Nulla viene rimosso senza la tua conferma.",
        uninstallerFDANote: "Concedi l’Accesso completo al disco per un’analisi più approfondita.",
        uninstallerFDAGrant: "Concedi accesso…",
        uninstallerFDAHint: "Attiva Vorssaint nell’elenco. Se non c’è, fai clic su + e scegli Vorssaint da Applicazioni. L’accesso ha effetto solo dopo aver riaperto l’app.",
        uninstallerFDARelaunch: "Riavvia ora",
        uninstallerScanning: "Analisi dei file…",
        uninstallerRemoving: "Spostamento nel Cestino…",
        uninstallerFoundTitle: "trovati",
        uninstallerSelectedFormat: "%d di %d selezionati",
        uninstallerRemove: "Sposta nel Cestino",
        uninstallerCancel: "Annulla",
        uninstallerDoneTitle: "Fatto!",
        uninstallerFreedFormat: "%@ recuperati",
        uninstallerSomeFailed: "Impossibile spostare alcuni elementi nel Cestino.",
        uninstallerFailedNeedsFDA: "I dati delle app in sandbox si possono spostare solo con Accesso completo al disco. La password di amministratore non lo sostituisce.",
        uninstallerFailedMoreFormat: "e altri %d",
        uninstallerAnother: "Disinstalla un’altra",
        uninstallerCatApp: "Applicazione",
        uninstallerCatSupport: "Supporto",
        uninstallerCatCaches: "Cache",
        uninstallerCatPreferences: "Preferenze",
        uninstallerCatContainers: "Container",
        uninstallerCatLogs: "Log",
        uninstallerCatState: "Stato salvato",
        uninstallerCatOther: "Altro",

        urlCleanerName: "Pulisci URL",
        urlCleanerEnable: "Pulisci gli URL quando li copi",
        urlCleanerEnableCaption: "Rimuove i parametri di tracciamento da un link non appena arriva negli appunti.",
        urlCleanerActiveNow: "Attivo ora",
        urlCleanerManualTitle: "Pulisci ora",
        urlCleanerInputPlaceholder: "Incolla un URL",
        urlCleanerOutputPlaceholder: "L’URL pulito appare qui",
        urlCleanerCleanButton: "Pulisci",
        urlCleanerPasteButton: "Incolla",
        urlCleanerCopyButton: "Copia",
        urlCleanerClearButton: "Svuota campo",
        urlCleanerNoURL: "Incolla un URL valido.",
        urlCleanerNoChange: "Niente da pulire.",
        urlCleanerCleaned: "URL pulito.",
        urlCleanerCopied: "Copiato.",
        urlCleanerLocalNote: "Locale. Senza rete.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Cerca, installa e rimuovi formule e cask.",
        homebrewMissingTitle: "Homebrew non trovato",
        homebrewMissingBody: "Vorssaint può aprire Terminale con l’installer ufficiale di Homebrew. Terminale mostra i passaggi e chiede la password se serve.",
        homebrewInstallHomebrew: "Installa Homebrew",
        homebrewInstallHomebrewCaption: "Quando Terminale ha finito, torna qui e fai clic su Aggiorna.",
        homebrewInstallHomebrewOpened: "Installer aperto in Terminale.",
        homebrewShellSetupTitle: "Completa configurazione Terminale",
        homebrewShellSetupBody: "Homebrew è installato, ma Terminale potrebbe non trovare ancora il comando brew. Vorssaint può aprire Terminale con il comando di configurazione.",
        homebrewShellSetupButton: "Configura Terminale",
        homebrewShellSetupOpened: "Comando aperto in Terminale. Poi torna qui e fai clic su Aggiorna.",
        homebrewRefresh: "Aggiorna",
        homebrewCheckPackages: "Controlla pacchetti",
        homebrewTrustTitle: "Tap non ancora attendibile",
        homebrewTrustCaption: "Homebrew ora chiede la tua conferma prima di usare tap di terze parti. Considera attendibile %@ per continuare.",
        homebrewTrustButton: "Autorizza e continua",
        homebrewSearchPlaceholder: "Cerca pacchetti",
        homebrewKeyboardHint: "Spazio o Invio chiude il pannello macOS. Usa il pulsante di ricerca.",
        homebrewSearchButton: "Cerca",
        homebrewSearchResults: "Risultati",
        homebrewInstalled: "Installati",
        homebrewAll: "Tutti",
        homebrewFormulas: "Formule",
        homebrewCasks: "Cask",
        homebrewNoPackages: "Nessun pacchetto trovato",
        homebrewNoSelection: "Seleziona un pacchetto installato o cercane uno nuovo.",
        homebrewDetailsTitle: "Dettagli pacchetto",
        homebrewInstall: "Installa",
        homebrewUninstall: "Disinstalla",
        homebrewUpgrade: "Aggiorna",
        homebrewUpgradeAll: "Aggiorna tutto",
        homebrewUpdateHomebrew: "Aggiorna Homebrew",
        homebrewAllPackages: "pacchetti",
        homebrewOpenTerminal: "Apri Terminale",
        homebrewCancelOperation: "Annulla",
        homebrewClearLog: "Svuota registro",
        homebrewLogTitle: "Registro",
        homebrewVersion: "Versione",
        homebrewDescription: "Tipo",
        homebrewHomepage: "Apri sito",
        homebrewPopularity: "Popolarità",
        homebrewPopularityFormat: "%@ installazioni in %@ giorni",
        homebrewInstalledBadge: "Installato",
        homebrewNotInstalledBadge: "Non installato",
        homebrewUpdates: "Aggiornamenti",
        homebrewUpdateAvailableBadge: "Aggiornamento disponibile",
        homebrewLatestVersion: "Più recente",
        homebrewConfirmInstallTitle: "Installare con Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew scaricherà e installerà %@. Potrebbero essere installate anche dipendenze.",
        homebrewConfirmUninstallTitle: "Disinstallare con Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew disinstallerà %@. I file di configurazione possono restare nel sistema.",
        homebrewConfirmUpgradeTitle: "Aggiornare con Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew scaricherà e applicherà la versione più recente di %@. Potrebbero essere aggiornate anche dipendenze.",
        homebrewConfirmUpgradeAllTitle: "Aggiornare tutto con Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew scaricherà e applicherà le versioni più recenti dei pacchetti con aggiornamenti disponibili. Potrebbero essere aggiornate anche dipendenze.",
        homebrewConfirmUpdateHomebrewTitle: "Aggiornare Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew recupererà le informazioni più recenti e poi ricaricherà i pacchetti.",
        homebrewTerminalFallback: "Questa operazione richiede Terminale per chiedere la password di amministratore. Vorssaint non acquisisce password.",
        homebrewLoading: "Caricamento…",
        homebrewSearchEmpty: "Nessun risultato",
        homebrewOperationInstallFormat: "Installazione di %@",
        homebrewOperationUninstallFormat: "Disinstallazione di %@",
        homebrewOperationUpgradeFormat: "Aggiornamento di %@",
        homebrewOperationUpgradeAll: "Aggiornamento dei pacchetti",
        homebrewOperationUpdateHomebrew: "Aggiornamento di Homebrew",
        homebrewOperationInstalledFormat: "%@ installato.",
        homebrewOperationUninstalledFormat: "%@ disinstallato.",
        homebrewOperationUpgradedFormat: "%@ aggiornato.",
        homebrewOperationUpgradedAll: "Pacchetti aggiornati.",
        homebrewOperationUpdatedHomebrew: "Homebrew aggiornato.",
        homebrewOperationFailedFormat: "Impossibile completare %@.",
        homebrewOperationCancelled: "Operazione annullata.",
        homebrewOperationPreparing: "Preparazione…",
        homebrewOperationDownloading: "Download dei file…",
        homebrewOperationInstalling: "Installazione dei file…",
        homebrewOperationUninstalling: "Rimozione dei file…",
        homebrewOperationUpgrading: "Aggiornamento file…",
        homebrewOperationFinalizing: "Completamento…",
        homebrewOperationRefreshing: "Aggiornamento lista…",
        homebrewOperationTerminal: "Continua nel Terminale.",
        homebrewOperationElapsedFormat: "%@ trascorsi",
        homebrewOperationShowDetails: "Mostra dettagli",
        homebrewOperationHideDetails: "Nascondi dettagli",
        homebrewOperationTechnicalLog: "Dettagli tecnici",
        homebrewOperationProgressUnknown: "Homebrew non ha ancora indicato una percentuale.",

        mediaName: "Media",
        mediaEnableCaption: "Comprimi video, converti ed elabora immagini, crea GIF ed estrai testo localmente.",
        mediaLocalNote: "Locale. Nessuna rete.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Immagine",
        mediaToolText: "Testo",
        mediaSelectFile: "Scegli file",
        mediaDropHint: "Trascina un file qui o fai clic per scegliere.",
        mediaOutput: "Uscita",
        mediaOutputAutomatic: "Automatica",
        mediaChooseOutput: "Destinazione",
        mediaStartVideo: "Comprimi video",
        mediaStartGIF: "Crea GIF",
        mediaStartImage: "Elabora immagine",
        mediaStartConvertPDF: "Converti in PDF",
        mediaStartText: "Estrai testo",
        mediaCancel: "Annulla",
        mediaStartTime: "Inizio",
        mediaEndTime: "Fine",
        mediaQuality: "Compressione",
        mediaCompressionLow: "Bassa",
        mediaCompressionMedium: "Media",
        mediaCompressionHigh: "Alta",
        mediaMaxSize: "Dimensione",
        mediaSizingResolution: "Risoluzione",
        mediaSizingFileSize: "Dimensione file",
        mediaTargetSize: "Dimensione obiettivo",
        mediaTargetSizeHint: "La risoluzione si adatta per restare sotto il limite.",
        mediaErrorTargetTooSmall: "Dimensione obiettivo troppo piccola per questa clip. Accorciala o aumenta il limite.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Larghezza",
        mediaFPS: "FPS",
        mediaKeepAudio: "Mantieni audio",
        mediaCodec: "Codec",
        mediaFormat: "Formato",
        mediaStripMetadata: "Rimuovi metadati",
        mediaLoopGIF: "Ripeti GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Accurato",
        mediaOCRFast: "Rapido",
        mediaLanguageCorrection: "Correzione lingua",
        mediaTextOutputNote: "Il testo estratto può essere copiato e salvato come TXT.",
        mediaRunning: "Elaborazione",
        mediaCompleted: "Completato",
        mediaCancelled: "Annullato.",
        mediaOpenInFinder: "Mostra",
        mediaCopyText: "Copia testo",
        mediaRunAgain: "Esegui di nuovo",
        mediaEmptyText: "Nessun testo trovato.",
        mediaResultSavedFormat: "Salvato come %@",
        mediaResultSizeFormat: "%@ in %@",
        mediaResultGrewCaption: "Il file convertito è più grande dell’originale.",
        mediaErrorNoFile: "Scegli prima un file.",
        mediaErrorNoVideo: "Questo file non contiene una traccia video.",
        mediaErrorSameOutput: "Scegli una destinazione diversa dal file originale.",
        mediaErrorUnsupported: "Formato non supportato da macOS.",

        shelfName: "Ripiano",
        shelfEnable: "Area temporanea per trascinare i file",
        shelfEnableCaption: "Uno spazio fluttuante per raccogliere file, immagini e testo, da trascinare poi ovunque.",
        shelfHowTitle: "Come si usa",
        shelfStep1: "Aprilo con la scorciatoia oppure scuotendo il mouse durante un trascinamento.",
        shelfStep2: "Rilascia su di esso file, immagini, link o testo per conservarli.",
        shelfStep3: "Trascina di nuovo fuori ogni elemento verso qualsiasi app quando ti serve.",
        shelfShakeToggle: "Apri scuotendo il mouse durante il trascinamento",
        shelfShakeCaption: "Scuoti rapidamente il puntatore mentre tieni un elemento per richiamarlo vicino al cursore.",
        shelfDropZoneToggle: "Tieni nella barra dei menu i file trascinati",
        shelfDropZoneCaption: "Mentre trascini un file, il ripiano appare sotto l’icona della barra dei menu. Quello che rilasci resta lì, in un pulsante che riduci e apri con un clic e che scompare quando il ripiano è vuoto.",
        shelfDropZoneLabel: "Rilascia qui",
        shelfCollapse: "Riduci",
        shelfBehaviorTitle: "Dopo l’uso",
        shelfCloseAfterDrop: "Chiudi dopo il rilascio in un’altra app",
        shelfCloseAfterDropCaption: "Chiude lo scaffale quando la destinazione accetta gli elementi. La puntina nel pannello lo mantiene aperto.",
        shelfRemoveAfterDrop: "Rimuovi gli elementi dopo il rilascio",
        shelfRemoveAfterDropCaption: "Gli elementi accettati da un’altra app lasciano lo scaffale. Disattiva per conservarne una copia.",
        shelfExclusionsTitle: "Eccezioni automatiche",
        shelfExclusionsEmpty: "Nessuna app aggiunta.",
        shelfExclusionsCaption: "Lo scuotimento e l’area nella barra dei menu restano inattivi per i trascinamenti avviati in queste app. La scorciatoia e Apri ora funzionano ancora.",
        shelfPin: "Mantieni aperto",
        shelfUnpin: "Consenti chiusura dopo l’uso",
        extraBrightnessName: "Luminosità extra",
        extraBrightnessCaption: "Usa la riserva HDR dello schermo per superare la luminosità massima. Consuma più batteria e il Mac può scaldarsi.",
        extraBrightnessLevelLabel: "Intensità",
        extraBrightnessUnsupported: "Disponibile solo su schermi XDR, come quelli dei MacBook Pro da 14 e 16 pollici.",
        shelfHotkeyLabel: "Scorciatoia",
        shelfOpenNow: "Apri ora",
        shelfNoPermission: "Non richiede alcuna autorizzazione.",
        shelfMenuItem: "Apri ripiano",
        shelfTitle: "Ripiano",
        shelfEmpty: "Trascina qui gli elementi",
        shelfClearAll: "Cancella tutto",
        shelfRemoveSelected: "Rimuovi selezionati",
        shelfSelectedFormat: "%d selezionati",
        shelfHint: "Fai clic per selezionare. Trascina per usare o fai clic destro per altre azioni.",
        shelfItemImage: "Immagine",
        shelfTooltipItemsFormat: "%d elementi",
        shelfTooltipItemsFew: "%d elementi",
        shelfTooltipImageSingular: "%d immagine",
        shelfTooltipImageFew: "%d immagini",
        shelfTooltipImagePlural: "%d immagini",
        shelfTooltipFileSingular: "%d file",
        shelfTooltipFileFew: "%d file",
        shelfTooltipFilePlural: "%d file",
        shelfTooltipNoteSingular: "%d nota",
        shelfTooltipNoteFew: "%d note",
        shelfTooltipNotePlural: "%d note",
        shelfTooltipLinkSingular: "%d link",
        shelfTooltipLinkFew: "%d link",
        shelfTooltipLinkPlural: "%d link",
        shelfActionOpen: "Apri",
        shelfActionOpenWith: "Apri con",
        shelfActionShare: "Condividi",

        breakdownMeasuring: "Misurazione…",

        mixerSection: "Mixer del volume",
        mixerEmpty: "Le app che usano l’audio compaiono qui",
        mixerUnavailable: "Disponibile su macOS 14.4 e successivi",
        mixerPermissionBody: "Per regolare il volume per ogni app, consenti “Registrazione schermo e audio di sistema” in Impostazioni di Sistema. L’audio non viene mai registrato.",
        mixerResetTooltip: "Ripristina al 100%",
        mixerOutputDefault: "Predefinita",
        mixerOutputCurrent: "attuale",
        mixerOutputUnavailable: "Uscita non disponibile",
        mixerOutputFallback: "Uso l’uscita predefinita finché questo dispositivo non torna.",
        mixerBypassedCaption: "Questa app gestisce da sé il proprio audio.",
        mixerOutputTooltip: "Scegli uscita",
        mixerSystemOutputTitle: "Uscita",
        mixerSystemOutputNoDevices: "Nessuna uscita trovata",
        mixerSystemOutputTooltip: "Scegli uscita di sistema",
        mixerSystemOutputErrorFormat: "Impossibile cambiare: %@",
        mixerLowerOnHeadphonesDisconnect: "Abbassa il volume quando le cuffie si scollegano",
        mixerLowerOnHeadphonesDisconnectCaption: "Regola l’uscita quando cuffie cablate o Bluetooth si scollegano.",
        mixerHeadphonesDisconnectVolume: "Volume dopo disconnessione",
        preciseVolumeRollerEnable: "Usa passi volume più fini",
        preciseVolumeRollerCaption: "Trasforma rotelle e tasti volume in passi di sistema più piccoli.",
        preciseVolumeRollerTapFailed: "Impossibile ascoltare i tasti volume.",
        soundOutputSwitcherTitle: "Selettore uscita",
        soundOutputSwitcherEnable: "Cambia uscite con scorciatoia",
        soundOutputSwitcherCaption: "Scegli le uscite e usa la scorciatoia per passare alla prossima disponibile.",
        soundOutputSwitcherDevices: "Uscite nel ciclo",
        soundOutputSwitcherNoAvailableSelection: "Seleziona almeno un’uscita disponibile.",
        mixerInputTitle: "Microfono",
        mixerInputNoDevices: "Nessun microfono trovato",
        mixerInputUnavailable: "Microfono non disponibile",
        mixerInputFallback: "Uso il predefinito finché questo microfono non torna.",
        mixerInputTooltip: "Scegli microfono",
        mixerInputErrorFormat: "Impossibile cambiare: %@",
        mixerVisibleApps: "App nell’elenco",
        mixerAllShown: "Tutte",
        mixerHiddenCountLabel: "Nascoste",
        mixerHideFromList: "Nascondi dall’elenco",

        updatesSection: "Aggiornamenti",
        autoCheckToggle: "Cerca aggiornamenti automaticamente",
        includeBetaUpdatesToggle: "Ricevi aggiornamenti beta",
        includeBetaUpdatesCaption: "Le versioni beta includono funzionalità in fase di sviluppo e potrebbero presentare instabilità o comportamenti incompleti.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Cerca ora",
        updateChecking: "Ricerca…",
        updateUpToDate: "Hai la versione più recente.",
        updateAvailablePrefix: "Aggiornamento disponibile:",
        updateInstallButton: "Scarica e installa",
        updateDownloading: "Download dell’aggiornamento…",
        updateInstalling: "Installazione e riavvio…",
        updateFailedPrefix: "Impossibile verificare:",
        updateLastChecked: "Ultima verifica:",
        updateNotifyTitle: "Aggiornamento di Vorssaint",
        updateInstallFailedBody: "L’aggiornamento è stato scaricato ma non è stato possibile applicarlo. Scarica l’ultima versione dalla pagina delle release su GitHub e trascina l’app sopra quella attuale.",
        updateNeedsApplicationsTitle: "Sposta Vorssaint in Applicazioni",
        updateNeedsApplicationsBody: "L’app è in esecuzione da una posizione che non può essere aggiornata, come l’immagine disco o una posizione temporanea di sistema. Trascina Vorssaint nella cartella Applicazioni, aprilo da lì e riprova.",
        menuCheckUpdates: "Cerca aggiornamenti…",

        permissionRequired: "Autorizzazione richiesta",
        permissionAccessibility: "Accessibilità",
        permissionScreenRecording: "Registrazione schermo",
        permissionGranted: "Concessa",
        permissionMissing: "Non concessa",
        permissionOpenSettings: "Apri Impostazioni di Sistema…",
        permissionRequest: "Concedi accesso",
        permissionRestartNote: "macOS potrebbe chiedere di riaprire l’app dopo la concessione.",

        aboutDescription: "Un centro di utilità per il tuo Mac.\nEnergia, monitoraggio del sistema, scorrimento e un commutatore di finestre, direttamente nella barra dei menu.",
        versionPrefix: "Versione",
        reviewIntro: "Rivedi l’introduzione",
        reviewHighlights: "Rivedi le novità",
        viewOnGitHub: "Vedi su GitHub",

        obContinue: "Continua",
        obBack: "Indietro",
        obSkipStep: "Salta questo passaggio",
        obStart: "Apri Vorssaint",
        obStepWelcomeTitle: "Ti diamo il benvenuto in Vorssaint",
        obStepWelcomeBody: "Un’utilità discreta nella barra dei menu che rende macOS più pratico ogni giorno.",
        obWelcomeBullet1Title: "Energia sotto controllo",
        obWelcomeBullet1Body: "Mantieni il Mac attivo per tutto il tempo che vuoi, anche con il coperchio chiuso.",
        obWelcomeBullet2Title: "Una visione chiara del sistema",
        obWelcomeBullet2Body: "Temperature di CPU, GPU e batteria, utilizzo dell’hardware e pressione della memoria in tempo reale.",
        obWelcomeBullet3Title: "Mouse e finestre come piacciono a te",
        obWelcomeBullet3Body: "Scorrimento invertito del mouse e un commutatore di finestre con miniature.",
        obLanguageLabel: "Lingua",
        obStepAccessibilityTitle: "Accessibilità",
        obStepAccessibilityBody: "Necessaria per invertire lo scorrimento del mouse e perché il commutatore di finestre risponda alla tastiera.",
        obAccessibilityWhy: "L’app si limita a osservare la rotellina del mouse e la scorciatoia del commutatore. Nulla viene registrato o inviato altrove.",
        obStepRecordingTitle: "Registrazione schermo",
        obStepRecordingBody: "Consente al commutatore di mostrare miniature reali delle finestre invece delle sole icone.",
        obRecordingWhy: "Le miniature vengono generate al momento, restano in memoria e non lasciano mai il tuo Mac. Senza, il commutatore funziona comunque con le icone.",
        obStepMonitorTitle: "Monitoraggio del sistema",
        obStepMonitorBody: "Il pannello mostra le temperature di CPU, GPU e batteria, l’utilizzo dell’hardware e la pressione della memoria.",
        obMonitorNoPermission: "Nessuna autorizzazione necessaria. I sensori vengono letti direttamente dal sistema.",
        obStepOptionalTitle: "Funzioni opzionali",
        obStepOptionalBody: "Attiva ora ciò che vuoi usare. Puoi cambiare tutto in seguito nelle Impostazioni.",
        obStepStatusTitle: "Controllo",
        obStepStatusBody: "Assicurati che sia tutto pronto per le funzioni che vuoi usare.",
        obStatusRecheck: "Controlla di nuovo",
        obStepDoneTitle: "Tutto pronto!",
        obStepDoneBody: "Vorssaint si sta già prendendo cura del tuo Mac.",
        obDoneHint: "Cerca il buco nero nella barra dei menu, in alto a destra dello schermo.",
        obWhatsNewTitle: "Novità di questa versione",
        obWhatsNewFallback: "Questo aggiornamento include le correzioni e i miglioramenti più recenti.",
        obLanguageUpdateTitle: "Ora nella tua lingua",
        obLanguageUpdateBody: "Vorssaint ora parla diverse lingue. Scegli quella che vuoi usare; puoi cambiarla quando vuoi nelle Impostazioni.",
        obPurposeTitle: "Cosa ti porta qui?",
        obPurposeBody: "Scegli una configurazione pronta o esattamente le funzioni che vuoi usare.",
        obPurposeSkip: "Puoi aggiungere o rimuovere funzioni in seguito nelle Impostazioni.",

        tabMonitor: "Monitoraggio",
        monitorMenuBarSection: "Nella barra dei menu",
        monitorMenuBarCaption: "Scegli cosa appare accanto all’icona nella barra dei menu.",
        monitorCombineTemperatures: "Combina uso e temperatura",
        monitorCombineTemperaturesCaption: "Quando uso e temperatura dello stesso elemento sono attivi, vengono mostrati in un solo blocco.",
        monitorSeparateMenuBarMetrics: "Separa le metriche in elementi propri",
        monitorSeparateMenuBarMetricsCaption: "Separa i blocchi attivi nella barra dei menu e tiene insieme utilizzo e temperatura quando combina è attivo.",
        monitorNetworkUploadFirst: "Upload sopra download",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Memoria",
        monitorShowNetwork: "Rete",
        monitorShowPowerLabel: "Energia",
        monitorIntervalLabel: "Aggiorna ogni",
        monitorInterval1: "1 secondo",
        monitorInterval2: "2 secondi",
        monitorInterval5: "5 secondi",
        monitorPanelSection: "Nel pannello",
        panelNavigationMode: "Naviga il pannello per sezioni",
        panelNavigationCaption: "Mostra una sezione alla volta. Scegli Lista per vedere tutto in uno scorrimento continuo.",
        panelFooterSections: "Sezioni",
        panelFooterList: "Lista",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Potresti riscontrare alcuni bug.",

        networkSection: "Rete",
        networkDownload: "Download",
        networkUpload: "Upload",
        networkThisSession: "In questa sessione",
        networkMeasuring: "Misurazione…",
        networkApps: "App con traffico rete",
        networkAppsIdle: "Nessuna app usa la rete ora",

        diskSection: "Dischi",
        diskUsed: "usato",
        diskFree: "libero",
        diskAvailable: "disponibile",
        diskPurgeable: "eliminabile",
        diskInternal: "Interno",
        diskExternal: "Esterno",
        diskSelect: "Scegli disco",
        diskRead: "Lettura",
        diskWrite: "Scrittura",
        diskSMARTStatus: "Stato",
        diskSMARTUnavailable: "SMART non disponibile per questo disco",
        diskTotalRead: "Totale letto",
        diskTotalWritten: "Totale scritto",
        diskTemperature: "Temperatura",
        diskHealth: "Salute",
        diskPowerCycles: "Cicli",
        diskPowerOnHours: "Ore acceso",
        diskUnsafeShutdowns: "Spegnimenti non sicuri",
        diskMediaErrors: "Errori supporto",
        diskEject: "Espelli",
        diskEjectAll: "Espelli tutti",
        diskEjecting: "Espulsione…",
        diskReadyToRemove: "Pronto da rimuovere",
        diskEjectFailed: "Impossibile espellere",
        diskProtectionCaption: "Espelli prima di scollegare.",
        diskNoExternal: "Nessun disco esterno pronto da espellere.",
        diskOpenInFinder: "Apri",
        diskStorageSettings: "Archiviazione",
        diskNoDisks: "Nessun disco montato trovato.",

        powerSection: "Energia",
        powerSystem: "Sistema",
        powerAdapter: "Alimentatore",
        powerBattery: "Batteria",
        powerCharging: "In carica",
        powerOnBattery: "A batteria",
        powerPluggedIn: "Collegato",
        powerUnavailable: "Metriche di energia non disponibili su questo Mac",
        powerAdapterMaxFormat: "%@ max",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Temperatura CPU",
        monitorShowGPUTemperature: "Temperatura GPU",
        monitorShowBatteryTemperature: "Temperatura batteria",
        monitorShowPeripheralBattery: "Batteria periferiche",
        peripheralBatteryNoDevices: "Nessuna periferica trovata",
        monitorGraphsSection: "Grafici",
        monitorGraphsCaption: "Scegli quali metriche mostrano un grafico nel tempo.",

        updateBannerTitle: "Aggiornamento disponibile",
        updateBannerAction: "Aggiorna",
        obStepMenuBarTitle: "Metriche nella barra dei menu",
        obStepMenuBarBody: "Scegli cosa mostrare accanto all’icona. L’anteprima qui sopra si aggiorna in tempo reale.",
        obStepMenuBarNote: "Novità: blocchi Rete ed Energia e grafici nel pannello. Regola tutto in seguito in Impostazioni › Monitoraggio.",
        monitorMenuBarPresetLabel: "Stile",
        menuBarPresetReadable: "Leggibile",
        menuBarPresetDense: "Denso",
        menuBarSpacingLabel: "Spaziatura nella barra",
        menuBarSpacingStandard: "Standard",
        menuBarSpacingCompact: "Compatta",
        menuBarHideIconToggle: "Nascondi l’icona dell’app mentre sono mostrate le metriche",
        menuBarHideIconCaption: "L’icona torna da sola quando le metriche lasciano la barra e quando c’è qualcosa da segnalare (un aggiornamento pronto o il microfono silenziato).",
        monitorLabelStyleLabel: "Etichette",
        menuBarLabelStyleCompact: "Compatte",
        menuBarLabelStyleClassic: "Classiche",
        monitorMemoryStyleLabel: "Mostra la memoria come",
        monitorMemoryPressureDot: "Punto pressione",
        memoryStyleDot: "Punto",
        memoryStylePercent: "%",
        memoryStyleBoth: "Entrambi",
        systemUptime: "Attivo da",
        batteryCharge: "Carica",
        powerHealth: "Stato batteria",
        powerCycles: "Cicli",
        speedTestRun: "Test velocità",
        speedTestAgain: "Ripeti il test",
        speedTestLatency: "Latenza",
        speedTestTesting: "Test in corso…",
        speedTestFailed: "Test non riuscito",

        monitorShowInPanel: "Mostra nel pannello",
        disclosureExpanded: "Espanso",
        disclosureCollapsed: "Contratto",
        panelHideItem: "Nascondi dal pannello",
        panelShowItem: "Mostra nel pannello",
        panelHiddenItem: "Nascosto",
        monitorItemUptime: "Tempo di attività",
        monitorItemNetSpeed: "Velocità in tempo reale",
        monitorItemNetTotals: "Totali della sessione",
        monitorItemNetTest: "Test velocità",
        monitorItemDiskUsage: "Uso disco",
        monitorItemDiskActivity: "Attività in tempo reale",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Protezione esterna",
        monitorItemDiskTools: "Strumenti",
        monitorPanelConfigHint: "Apri un blocco per scegliere cosa mostra.",
        monitorOrderSection: "Ordine delle sezioni",
        monitorOrderHint: "Trascina per riordinare le sezioni del pannello e usa l’occhio per mostrarne o nasconderne ognuna.",
        obStepPanelTitle: "Cosa appare nel pannello",
        obStepPanelBody: "Apri ogni blocco e scegli esattamente cosa mostrare quando fai clic sull’icona.",
        obStepPanelNavigationTitle: "Pannello per sezioni",
        obStepPanelNavigationBody: "Il pannello ora può mostrare una sezione alla volta. Puoi passare da Sezioni a Lista nelle impostazioni.",

        cleaningMenuItem: "Modalità pulizia",
        utilitiesSection: "Utilità",
        quickControlsSection: "Controlli",
        panelCategoryWindows: "Finestre",
        panelCategoryInput: "Mouse e tastiera",
        panelCategoryFiles: "File",
        windowMaximizeName: "Massimizza finestre",
        windowMaximizeCaption: "Il pulsante verde massimizza senza creare un altro Spazio.",
        windowMaximizeActiveNow: "Pulsante verde attivo",
        windowMaximizeNeedsAccessibility: "Richiede Accessibilità per funzionare.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Filtra tasti duplicati",
        keyDebounceCaption: "Filtra pressioni duplicate molto rapide.",
        keyDebounceActiveNow: "Filtro attivo",
        keyDebounceGlobalWindow: "Finestra globale",
        keyDebouncePerKeySection: "Tasti specifici",
        keyDebouncePerKeyCaption: "I valori per tasto sostituiscono la finestra globale. Usa 0 ms per non filtrare un tasto.",
        keyDebounceKeyLabel: "Tasto",
        keyDebounceWindowLabel: "Finestra",
        keyDebounceAddKey: "Aggiungi tasto",
        keyDebounceNoOverrides: "Nessun tasto specifico configurato.",
        keyDebounceRemoveKey: "Rimuovi tasto",
        cleaningPanelCaption: "Blocca la tastiera per pulire in sicurezza.",
        cleaningOverlayTitle: "Tastiera bloccata per la pulizia",
        cleaningOverlaySubtitle: "Premi Esc 5 volte per sbloccare",
        cleaningOverlayUnlock: "Sblocca",
        cleaningOverlayMouseHint: "Mouse e trackpad continuano a funzionare",
        cleaningKeepScreenVisibleToggle: "Mantieni lo schermo visibile",
        cleaningKeepScreenVisibleCaption: "Mostra un indicatore discreto nell’angolo dello schermo anziché oscurare i contenuti.",
        cleaningStartNow: "Blocca la tastiera ora",
        cleaningNeedsAxTitle: "Serve l’Accessibilità",
        cleaningNeedsAxBody: "Per bloccare la tastiera in sicurezza, Vorssaint ha bisogno dell’autorizzazione di Accessibilità. Concedila in Impostazioni di Sistema e riprova.",

        tabSupport: "Sostieni",
        shortcutsPageCaption: "Modifica qui tutte le scorciatoie globali delle funzioni installate su questo Mac. Quelle inattive restano salvate ma non si attivano.",
        shortcutsPageTitle: "Abbreviazioni da tastiera",
        settingsSearchPlaceholder: "Cerca nelle impostazioni",
        donateHeading: "Aiuta Vorssaint a continuare a crescere",
        donateMessage: "Vorssaint è gratuito, indipendente e sviluppato nel mio tempo libero. Se vuoi contribuire economicamente, Buy Me a Coffee aiuta direttamente a portare avanti lo sviluppo.",
        donateButton: "Sostieni su Buy Me a Coffee",
        donateThanks: "Grazie di essere qui. 🖤",
        supportIntroTitle: "Aiuta Vorssaint a continuare a crescere",
        supportIntroMessage: "Se vuoi sostenere economicamente lo sviluppo, Buy Me a Coffee è l’unico posto in cui farlo.",
        supportIntroStarButton: "Dai una stella a Vorssaint su GitHub",
        supportIntroStarMessage: "Il sostegno economico non è mai richiesto. Una stella su GitHub aiuta più persone a scoprire Vorssaint e fa davvero la differenza per il suo sviluppo.",
        supportIntroCoffeeButton: "Sostieni su Buy Me a Coffee",
        supportIntroLaterButton: "Non ora",
        supportIntroDoneButton: "Fatto",
        discordIntroTitle: "La community di Vorssaint su Discord è appena nata",
        discordIntroMessage: "La community di Vorssaint è nuova e sta ancora prendendo forma. Entra fin dall’inizio per conoscere altri utenti e contribuire a creare uno spazio accogliente attorno all’app.",
        discordIntroJoinButton: "Entra nella community su Discord",
        communityIntroTitle: "Guarda tutto prima degli altri",
        communityIntroMessage: "Chi mi seguiva già su X ha visto molte novità di questo aggiornamento prima di tutti. Lì pubblico anteprime di ciò che arriverà e mostro come funziona, così conosci già le basi prima ancora dell’uscita dell’aggiornamento. Seguimi e scopri cosa arriverà!",
        communityIntroFollowButton: "Segui @vorssaint su X",
        homebrewOfficialIntroTitle: "Ora nel catalogo ufficiale di Homebrew",
        homebrewOfficialIntroMessage: "Vorssaint ora può essere installato direttamente dal catalogo ufficiale di Homebrew.",
        homebrewOfficialIntroInstallLabel: "Nuova installazione",
        homebrewOfficialIntroMigrationTitle: "Usavi il vecchio tap?",
        homebrewOfficialIntroMigrationMessage: "Rimuovi una volta il vecchio tap. L’app e le tue impostazioni restano al loro posto.",
        homebrewOfficialIntroCopyButton: "Copia comando",
        updateShowcaseTitle: "Novità di 3.1.4",
        updateShowcaseMessage: "Guarda una breve anteprima dei principali miglioramenti di questo aggiornamento.",
        updateShowcaseUnavailable: "Non è stato possibile caricare il video ora. Puoi continuare comunque.",
        updateShowcaseRestart: "Torna all’inizio",
        showMenuBarIcon: "Mostra l’icona nella barra dei menu",
        showMenuBarIconCaption: "Se l’icona di Vorssaint scompare (macOS può nascondere le icone della barra dei menu quando lo spazio finisce, cosa comune sui Mac con notch), riapri Vorssaint da Applicazioni o da Spotlight: questo ricrea l’icona e, se è ancora nascosta, apre questa finestra.",
        menuBarIconStillHiddenTitle: "L’icona è ancora nascosta",
        menuBarIconStillHiddenBody: "L’icona è stata ricreata, ma macOS non le ha dato un posto visibile. Probabilmente la barra dei menu è senza spazio: rimuovi alcune icone dalla barra (o chiudi le app con menu lunghi) e riprova.",
        menuBarIconManagerHintFormat: "%@ è aperto e potrebbe tenere l’icona nella sua sezione nascosta. Cerca Vorssaint lì, oppure imposta %@ per mostrare sempre Vorssaint.",
        shortcutRecording: "Premi la nuova scorciatoia",
        shortcutReset: "Ripristina",
        shortcutNone: "Nessuna",
        shortcutClear: "Rimuovi scorciatoia",
        shortcutInvalid: "Usa almeno Control, Option o Command insieme a un tasto.",
        shortcutPressKeys: "Premi i tasti",
        shortcutEscapeHint: "Esc annulla.",
        shortcutDeleteHint: "Delete rimuove.",
        shortcutNotCaptured: "Non è stato catturato nulla. macOS o un’altra app usa già questa combinazione. Provane un’altra.",
        shortcutConflictFormat: "Questa scorciatoia è già usata da %@.",
        shortcutUnavailable: "macOS ha rifiutato questa scorciatoia. Scegline un’altra.",
        shelfShortcutToggle: "Scorciatoia Shelf",
        switcherUsageHintFormat: "Tieni premuto %@ per spostarti; rilascia per attivare la finestra. Maiuscole o ← torna indietro; W chiude la finestra; Q chiude l’app; Esc annulla.",
        musicBlockSection: "Tasti multimediali",
        musicBlockTitle: "Impedisci a Musica di aprirsi da sola",
        musicBlockCaption: "L’app Musica non si apre più premendo i tasti multimediali. Puoi comunque aprirla tu.",
        musicBlockReplacementLabel: "Apri al suo posto",
        musicBlockReplacementNone: "Nessuna",
        musicBlockChooseApp: "Scegli app…",
        cleanerName: "Pulizia",
        cleanerIntroTitle: "Pulisci il Mac",
        cleanerIntroCaption: "Cerca residui di app disinstallate, cache, log e il Cestino. Rivedi tutto prima e gli elementi rimossi vanno nel Cestino.",
        cleanerScan: "Analizza",
        cleanerScanning: "Analisi…",
        cleanerCleaning: "Pulizia…",
        cleanerCatLeftovers: "Residui di app disinstallate",
        cleanerCatLoginItems: "Elementi di avvio orfani",
        cleanerCatCaches: "Cache",
        cleanerCatLogs: "Log",
        cleanerCatDeveloper: "Dati di sviluppo",
        cleanerCatTrash: "Cestino",
        cleanerLeftoversNote: "Trovati per analisi e non selezionati. Controlla il percorso prima di selezionare.",
        cleanerLoginItemsNote: "La voce in Elementi di login sparisce dopo un riavvio del Mac.",
        cleanerTrashNote: "Svuotare il Cestino è definitivo.",
        cleanerCatDeviceBackups: "Backup di iPhone",
        cleanerDeviceBackupsCaption: "I vecchi backup di iPhone e iPad occupano gran parte dello spazio che macOS chiama Altro. Rimuovi solo quelli che non servono più; al prossimo collegamento ne viene creato uno nuovo.",
        cleanerNothingFound: "Niente da pulire. Il tuo Mac è in ordine.",
        cleanerClean: "Pulisci",
        cleanerDoneNote: "Gli elementi sono nel Cestino e possono essere recuperati da lì.",
        cleanerAgain: "Analizza di nuovo",
        cleanerRevealInFinder: "Mostra nel Finder",
        cleanerPanelCaption: "Residui di app, cache e log",
        cleanerSafeSection: "Pulizia sicura",
        cleanerOptionalSection: "Facoltativo, controlla prima",
        cleanerCatOtherCaches: "Altre cache",
        cleanerCachesCaption: "File temporanei che le app ricreano da sole.",
        cleanerLogsCaption: "Vecchi log di diagnostica.",
        cleanerDeveloperCaption: "Residui di build e simulatori di Xcode.",
        cleanerLoginItemsCaption: "Voci di avvio lasciate da app che non esistono più.",
        cleanerLeftoversCaption: "File lasciati da app disinstallate.",
        cleanerOtherCachesCaption: "Sicuro da eliminare, niente si rompe. Le app possono aprirsi più lente una volta e i contenuti scaricati, come la musica offline, si scaricano di nuovo.",
        cleanerCleanSizeFormat: "Pulisci %@",
        cleanerScheduleTitle: "Pulizia automatica",
        cleanerScheduleOff: "Disattivata",
        cleanerScheduleDaily: "Giornaliera",
        cleanerScheduleWeekly: "Settimanale",
        cleanerScheduleCaption: "Pulisce da sola solo la parte sicura all’orario scelto e manda tutto nel Cestino.",
        cleanerScheduleLastFormat: "L’ultima pulizia automatica ha liberato %@.",
        cleanerAutoNotificationFormat: "%@ liberati e spostati nel Cestino.",
        cleanerScheduleNextFormat: "Prossima pulizia %@.",
        cleanerScheduleRanFormat: "Ultima pulizia automatica %@.",
        cleanerScheduleNotifyToggle: "Avvisa al termine",
        cleanerNotifDenied: "Le notifiche di Vorssaint sono disattivate nel sistema.",
        cleanerNotifOpenSettings: "Apri impostazioni notifiche…",
        launchAtLoginNeedsApplications: "L’app è in esecuzione da una posizione che non consente l’apertura all’accesso. Trascina Vorssaint nella cartella Applicazioni, aprila da lì e riattiva l’opzione.",
        launchAtLoginNeedsApproval: "L’elemento di login è registrato, ma in Impostazioni di Sistema resta disattivato. Apri Impostazioni di Sistema › Generali › Elementi login ed estensioni e attiva Vorssaint sotto “Apri all’accesso”.",
        ocrRemoveLineBreaksToggle: "Rimuovi interruzioni di riga",
        ocrRemoveLineBreaksCaption: "Rimuove le interruzioni di riga, così il testo copiato viene incollato come un unico paragrafo.",
        ocrQRToggle: "Leggi i codici QR",
        ocrQRCaption: "Se l’area contiene un codice QR, il suo contenuto viene mostrato per copiarlo o aprirlo.",
        ocrQRCopied: "Codice QR copiato",
        qrResultTitle: "Codice QR",
        qrResultCopy: "Copia",
        qrResultOpen: "Apri link",
        highlightsTitle: "Novità di questo aggiornamento",
        highlightsTitleClipboardRedesign: "Appunti rinnovati",
        highlightsTitleWindowLayout: "Disposizione delle finestre",
        highlightsTitleQuitProtection: "Protezione da ⌘Q e ⌘W",
        highlightsTitleRecorderBlur: "Sfocatura nella registrazione",
        highlightsCaptionDockPreview: "Dock Preview ora funziona con l’ingrandimento del Dock attivo",
        highlightsCaptionScreenshot: "Lo screenshot ha guadagnato una lente dei pixel e la lettura dei codici QR",
        highlightsCaptionSnippetLibrary: "Un menu di snippet con ricerca digita qualsiasi snippet al cursore",
        highlightsCaptionCapturePalette: "Una sola scorciatoia apre ora una palette mobile per schermate, registrazioni, testo su schermo e colori con i controlli a portata di mano.",
        highlightsCaptionClipboardRedesign: "La cronologia si apre ora come una palette compatta con righe ordinate e un’anteprima su richiesta per leggere o modificare l’elemento completo.",
        highlightsCaptionWindowLayout: "Posiziona le finestre con l’anello direzionale tramite scorciatoia e puntatore, oppure trascinale sui bordi dello schermo con margini regolabili.",
        highlightsCaptionQuitProtection: "Evita di chiudere app o finestre per errore tenendo premuto il tasto, con una doppia pressione o un modificatore extra, regolabile per app.",
        highlightsCaptionRecorderBlur: "Nascondi dati riservati, password e dettagli privati in qualsiasi punto della registrazione video prima di condividerla o esportarla.",
        highlightsConfigure: "Configura",
        highlightsTry: "Prova",
        highlightsSeeAll: "Vedi tutte le modifiche",
        switcherCurrentSpaceOnly: "Mostra solo la scrivania attuale",
        switcherCurrentSpaceOnlyCaption: "Mostra nel commutatore solo le finestre della scrivania in cui ti trovi. Scegliere una finestra non ti porta mai su un’altra scrivania.",
        shelfFileMissing: "Il file non esiste più",
        previewSizeSmall: "Piccola",
        mixerSoundEffectsOutputTitle: "Suoni di sistema",
        mixerSoundEffectsOutputTooltip: "Scegli dove riprodurre avvisi ed effetti sonori",
        monitorOpenActivityMonitor: "Apri Monitoraggio Attività",
        dockClickHide: "Nascondi l’app con un clic sul Dock",
        dockClickHideCaption: "L’app attiva viene nascosta quando fai clic sulla sua icona nel Dock. Fai di nuovo clic per riportarla in primo piano.",
        monitorMemoryMetricLabel: "Misura la memoria come",
        memoryMetricUsed: "Memoria usata",
        memoryMetricApp: "Memoria app",
        keepAwakeRightClickToggle: "Fai clic destro sull’icona della barra dei menu per attivare o disattivare “Mantieni attivo”",
        keepAwakeRightClickToggleCaption: "Sostituisce il menu contestuale del clic destro.",
        urlCleanerRulesTitle: "Regole di pulizia",
        urlCleanerRulesCaption: "Un sito aggiunge questi parametri ai propri link di condivisione per risalire a dove è nato il link. Selezionato, il nome viene rimosso durante la pulizia; deselezionato, resta. I nomi che aggiungi possono essere eliminati.",
        urlCleanerRulesCoverageCaption: "L’elenco copre i diversi percorsi di condivisione di un sito (la pagina web, l’app, una diretta) ed è per questo che è lungo; un link reale ne porta di solito solo da due a quattro.",
        urlCleanerRulesAllSites: "Tutti i siti",
        urlCleanerRulesCountSingular: "1 parametro",
        urlCleanerRulesCountPluralFormat: "%d parametri",
        urlCleanerRulesAddSite: "Aggiungi sito",
        urlCleanerRulesParameterPlaceholder: "Nome del parametro",
        urlCleanerRulesMatchCaption: "Scrivi il nome a sinistra dell’ = , per esempio utm_source. Un nome che corrisponde toglie dal link solo quel parametro e lascia il resto com’era.",
        urlCleanerRulesAddButton: "Aggiungi",
        urlCleanerRulesRemoveButton: "Elimina nome",
        urlCleanerRulesRemoveSiteButton: "Disattiva tutte le regole di questo sito",
        urlCleanerRemovedFormat: "Rimossi %@",
        switcherSearchPin: "Blocca la ricerca con S",
        switcherSearchPinCaption: "S avvia la ricerca e blocca il selettore aperto: niente più caratteri speciali quando la scorciatoia usa ⌥, e una ricerca che inizia con Q o W non chiude più la finestra né l’app per errore.",
        invertVerticalScroll: "Inverti lo scorrimento verticale",
        invertHorizontalScroll: "Inverti lo scorrimento orizzontale",
        switcherShowShortcutHints: "Mostra suggerimenti scorciatoie",
        switcherShowShortcutHintsCaption: "Mostra le scorciatoie per app e finestre sotto le icone.",
        uninstallerHomebrewPackageFormat: "%@ verrà rimosso anche da Homebrew.",
        shelfEdgeToggle: "Apri vicino a un bordo dello schermo",
        shelfEdgeCaption: "Trascina un file verso il bordo dello schermo per far intravedere il ripiano. Rilascialo lì, oppure torna indietro e si ritira.",
        focusFollowsMouseName: "Il focus segue il mouse",
        focusFollowsMouseCaption: "Mette a fuoco e porta in primo piano la finestra sotto il puntatore dopo una breve pausa.",
        focusFollowsMouseDelay: "Ritardo al passaggio",
        switcherMinimizedPlacementLabel: "Finestre ridotte a icona",
        switcherMinimizedPlacementNormal: "Ordine normale",
        switcherMinimizedPlacementEnd: "Sposta alla fine",
        switcherMinimizedPlacementHidden: "Nascondi",
        switcherShowFullscreenWindows: "Mostra le finestre a schermo intero",
        switcherScreenPlacementLabel: "Mostra su",
        switcherScreenPlacementPointer: "Schermo con il puntatore",
        switcherScreenPlacementMenuBar: "Schermo con la barra dei menu",
        switcherScreenPlacementActiveWindow: "Schermo con la finestra attiva",
        switcherScreenPlacementCaption: "Su quale schermo si apre il commutatore quando ne sono collegati più di uno.",
        smoothScrollResponseLabel: "Reattività",
        mouseAccelerationName: "Disattiva l’accelerazione del mouse",
        mouseAccelerationCaption: "Rimuove l’accelerazione del puntatore per i mouse collegati. L’impostazione precedente viene ripristinata quando disattivi l’opzione o chiudi Vorssaint.",
        shelfClearOnClose: "Svuota alla chiusura",
        shelfClearOnCloseCaption: "Svuota lo scaffale solo quando fai clic sul pulsante di chiusura. Se si nasconde automaticamente o viene ridotto, gli elementi restano."
    )
}
