// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Türkçe.
extension Strings {
    static let tr = Strings(
        statusIdleTooltip: "Vorssaint: normal uyku",
        statusActiveUntil: "Vorssaint: şu zamana kadar uyanık",
        statusActiveIndefinite: "Vorssaint: süresiz uyanık",
        menuEnableAwake: "Uyanık tutmayı etkinleştir",
        menuDisableAwake: "Uyanık tutmayı kapat",
        menuActivateFor: "Şu süreyle etkinleştir…",
        menuSettings: "Ayarlar…",
        menuAbout: "Vorssaint Hakkında",
        menuQuit: "Vorssaint’ten Çık",
        menuHide: "Vorssaint’i Gizle",
        menuHideOthers: "Diğerlerini Gizle",
        menuShowAll: "Tümünü Göster",
        menuEdit: "Düzen",
        menuUndo: "Geri Al",
        menuRedo: "Yinele",
        actionClear: "Temizle",
        actionRemove: "Kaldır",
        actionBack: "Geri",
        actionSearch: "Ara",
        actionMute: "Sessize al",
        actionUnmute: "Sesi aç",
        actionPlay: "Oynat",
        actionPause: "Duraklat",
        menuCut: "Kes",
        menuCopy: "Kopyala",
        menuPaste: "Yapıştır",
        menuSelectAll: "Tümünü Seç",
        menuWindow: "Pencere",
        menuMinimize: "Küçült",
        menuZoom: "Yakınlaştır",
        menuClose: "Kapat",

        minutes15: "15 dakika",
        minutes30: "30 dakika",
        hour1: "1 saat",
        hours2: "2 saat",
        hours4: "4 saat",
        hours8: "8 saat",
        indefinitely: "Süresiz",
        indefinite: "Süresiz",

        panelSettings: "Ayarlar",
        panelQuit: "Çık",
        panelHotkeyHint: "Kısayol açıp kapatır",

        keepAwakeTitle: "Uyanık tut",
        keepAwakeEndsIn: "Kalan süre",
        keepAwakeUntilDisabled: "Sen kapatana kadar etkin",
        keepAwakeNormalRules: "Mac normal enerji kurallarını izler",
        keepAwakeOptions: "Seçenekler",
        keepAwakeMouseJiggle: "İmleci hafifçe oynat",
        keepAwakeMouseJiggleCaption: "Oturum sırasında seçilen aralıkta imleci biraz oynatır.",
        keepAwakeMouseJiggleInterval: "Aralık",
        keepAwakeActiveIconLabel: "Etkin simge",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Kahve",
        keepAwakeActiveIconEye: "Göz",
        keepAwakeActiveIconMoon: "Ay",
        keepAwakeActiveIconLight: "Ampul",
        keepAwakeIconTintLabel: "Etkin simge rengi",
        keepAwakeIconTintOrange: "Turuncu",
        keepAwakeIconTintGreen: "Yeşil",
        keepAwakeIconTintBlue: "Mavi",
        keepAwakeIconTintPurple: "Mor",
        keepAwakeIconTintPink: "Pembe",
        keepAwakeIconTintNone: "Renk yok",
        durationLabel: "Süre",
        clamshellTitle: "Kapak kapalıyken devam et",
        clamshellOnCaption: "Uyku tamamen kapalı. Gücü göz önünde bulundur",
        clamshellNeedsSession: "“Uyanık tut” etkinken uygulanır",
        clamshellReady: "Hazır. Parola istemeden açılıp kapanır",
        clamshellNeedsPassword: "Yönetici parolasını bir kez isteyecek",

        systemSection: "Sistem",
        temperatures: "Sıcaklıklar",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Pil",
        usageSection: "Donanım kullanımı",
        memorySection: "Bellek",
        memoryPressure: "Basınç",
        memorySwapUsed: "Kullanılan takas",
        memoryCompressed: "Sıkıştırılmış",
        memoryCachedFiles: "Önbellekteki dosyalar",
        pressureNormal: "Normal",
        pressureWarning: "Dikkat",
        pressureCritical: "Kritik",
        monitorUnavailable: "Bu Mac’te sensörler kullanılamıyor",
        energyAppsTitle: "Önemli enerji kullanan uygulamalar",
        energyAppsIdle: "Önemli enerji kullanımı yok",

        notifySessionEndedTitle: "Oturum bitti",
        notifySessionEndedBody: "Süre doldu. Mac yeniden normal şekilde uyuyacak.",
        notifyBatteryTitle: "Vorssaint devre dışı",
        notifyBatteryBody: "Pil düşük. Şarjı korumak için normal uyku geri yüklendi.",
        adminPromptClamshellOn: "Vorssaint’in, Mac’i kapak kapalıyken çalıştırmak için parolana ihtiyacı var.",
        adminPromptClamshellOff: "Vorssaint’in, Mac’in normal uykusunu geri yüklemek için parolana ihtiyacı var.",
        adminPromptRecover: "Mac’in uykusu kapalıyken Vorssaint kapandı. Normal uykuyu geri yüklemek için parolayı gir.",
        adminPromptUpdate: "Vorssaint güncellemeyi yüklemek için parolanıza ihtiyaç duyuyor.",
        adminPromptSudoersInstall: "Vorssaint, parola sormadan kapak kapalı modunu açıp kapatmak için kısıtlı bir kural oluşturacak (yalnızca pmset disablesleep). Parolanın gerektiği tek zaman bu.",
        adminPromptSudoersRemove: "Vorssaint, parolasız kapak kapalı kuralını kaldıracak.",

        settingsTitle: "Vorssaint Ayarları",
        tabGeneral: "Genel",
        tabEnergy: "Enerji",
        tabMouse: "Fare ve izleme dörtgeni",
        tabSwitcher: "Değiştirici",
        tabAdvanced: "Gelişmiş",
        tabAbout: "Hakkında",
        tabReleaseNotes: "Yenilikler",
        releaseNotesOnUpdateToggle: "Güncellemeden sonra yenilikleri göster",
        minimalWindowPreviews: "Sade önizlemeler",
        minimalWindowPreviewsCaption: "Dock ve uygulama değiştirici önizlemelerinde başlıkları, düğmeleri ve süslemeleri gizler. Seçim görünür kalır.",
        previewSizeLabel: "Önizleme boyutu",
        previewSizeNormal: "Normal",
        previewSizeLarge: "Büyük",
        previewSizeXLarge: "Çok büyük",
        settingsGroupFeatures: "Özellikler",
        advancedResetSection: "İzinler",
        advancedResetDescription: "Vorssaint’e verdiğin tüm izinleri (Erişilebilirlik, Ekran Kaydı, Tam Disk Erişimi ve diğerleri), oturum açma öğesini ve kapak kapalı kuralını kaldırır. Sıfırdan başlamak veya kaldırmadan önce temizlemek için kullanışlıdır. Uygulama yüklü kalır.",
        advancedClearButton: "Tüm izinleri temizle",
        advancedCleared: "İzinler temizlendi.",
        advancedClearConfirmTitle: "Tüm izinler temizlensin mi?",
        advancedClearConfirmBody: "İzin gerektiren özellikler, yeniden izin verene kadar çalışmaz. Ayarların korunur.",
        advancedUninstallSection: "Kaldır",
        advancedUninstallDescription: "Yukarıdakilerin hepsini yapar, ardından tercihleri kaldırır ve Vorssaint’i Çöp Sepeti’ne taşır; geride hiçbir şey bırakmaz. İş bitince uygulama kapanır. İstediğin zaman yeniden yükleyebilirsin.",
        advancedUninstallButton: "Vorssaint’i tamamen kaldır",
        advancedUninstallConfirmTitle: "Vorssaint kaldırılsın mı?",
        advancedUninstallConfirmBody: "Vorssaint izinlerini temizleyecek, tercihlerini kaldıracak ve Çöp Sepeti’ne taşınıp kapanacak. Bu işlem uygulama içinden geri alınamaz, ama Çöp Sepeti’ni boşaltana kadar orada kalır.",
        advancedUninstallFailedTitle: "Kaldırma durduruldu",
        advancedUninstallFailedBody: "Vorssaint değiştirdiği bir sistem ayarını geri alamadı: uyku, fan hızı veya fare hızlandırması. Hiçbir şey silinmedi. Yeniden deneyin ve parola istenirse izin verin.",

        launchAtLogin: "Oturum açınca başlat",
        languageLabel: "Dil",
        menuBarSection: "Menü çubuğu",
        showCountdown: "Kalan süreyi simgenin yanında göster",
        globalHotkeySection: "Genel kısayol",
        hotkeyToggle: "“Uyanık tut” kısayolunu etkinleştir",
        hotkeyCaption: "Her uygulamada çalışır, ek izin gerekmez.",

        sessionSection: "Oturum",
        defaultDurationLabel: "Varsayılan süre",
        keepAwakeAutoStart: "Vorssaint açılınca uyanık tut",
        keepAwakeAutoStartCaption: "Varsayılan süreyle bir oturum başlatır.",
        batteryProtectionSection: "Pil koruması",
        batteryDisableBelow: "Pil şu seviyenin altına düşünce kapat",
        batteryNever: "Asla",
        batteryProtectionCaption: "Unutulan bir oturumun MacBook pilini tüketmesini önler.",
        clamshellSection: "Kapak kapalı",
        configuring: "Yapılandırılıyor…",
        sudoersFailed: "Kapak kapalı modu açılamadı. Tekrar dene.",
        clamshellExplanation: "“Kapak kapalıyken devam et”, “Uyanık tut” etkinken uykuyu tamamen kapatır ve oturum bittiğinde veya uygulama kapandığında otomatik geri alınır. Güce bağlıyken kullanman önerilir.",

        scrollSection: "Kaydırma",
        invertMouseScroll: "Fare kaydırmasını ters çevir",
        invertMouseScrollCaption: "Fare tekerleği yönünü tersine çevirir.",
        scrollTrackpadNote: "İzleme dörtgenine dokunulmaz: macOS doğal kaydırması korunur.",
        scrollActiveNow: "Fare kaydırması şu anda ters çevriliyor",
        mouseNavigationActiveNow: "Yan düğmeler şu anda etkin",
        smoothScrollName: "Akıcı kaydırma",
        smoothScrollCaption: "Fare tekerleğinin her adımını kısa ve yumuşak bir kaymaya dönüştürür. İzleme dörtgeni değişmez.",
        smoothScrollStepLabel: "Kaydırma hızı",
        mouseNavigationSection: "Gezinme",
        mouseNavigationEnable: "Geri ve İleri için yan düğmeleri kullan",
        mouseNavigationCaption: "Farenin Geri ve İleri düğmelerini Finder, tarayıcılar ve uyumlu uygulamalarda gezinme komutlarına dönüştürür.",
        middleClickSection: "Orta tıklama",
        middleClickEnable: "Üç parmakla tıklama orta tıklama olur",
        middleClickEnableCaption: "Trackpad’e üç parmakla basmak fare tekerleği tıklaması gibi çalışır: bağlantıları yeni sekmede açma, sekmeleri kapatma ve orta düğmenin yaptığı her şey.",
        middleClickDragConflict: "macOS’un üç parmakla sürükleme özelliği açık ve aynı hareketi kullanıyor. Orta tıklamanın çalışması için Sistem Ayarları’nda Erişilebilirlik, İmleç Denetimi, Trackpad Seçenekleri bölümünden kapatın.",
        middleClickTapPicker: "Hafif dokunuş da tıklar",
        middleClickTapOff: "Kapalı",
        middleClickTapThreeFingers: "3 parmak",
        middleClickTapFourFingers: "4 parmak",
        middleClickTapCaption: "O sayıda parmakla hafifçe dokunmak, bastırmadan, orta tıklamayı da tetikler. Kaydırma asla sayılmaz. macOS üç parmak dokunuşu Araştır işlevine atanmışsa, ikisinin birlikte tetiklenmemesi için onu kapatın.",
        quickToolsTab: "Hızlı panel",
        quickToolShortcutToggle: "Genel kısayol",
        ocrName: "Ekrandaki metni kopyala",
        ocrCaption: "Ekranda bir alan seçin; tanınan metin kopyalanır ve yapıştırmaya hazır olur.",
        ocrCopied: "Metin kopyalandı",
        ocrNoText: "Metin bulunamadı",
        colorPickerName: "Renk damlalığı",
        colorPickerCaption: "Ekrandaki herhangi bir pikselin rengini alın ve istediğiniz biçimde kopyalayın.",
        colorPickerFormatLabel: "Kopyalama biçimi",
        colorPickerBareHexToggle: "# öneki olmadan kopyala",
        colorPickerPickNow: "Renk seç",
        micMuteName: "Mikrofonu sessize al",
        micUnmuteName: "Mikrofonu aç",
        micMuteCaption: "Mac’in mikrofonunu tek tıkla veya kısayolla keser; tüm uygulamalarda geçerlidir.",
        micMutedHUD: "Mikrofon sessize alındı",
        micUnmutedHUD: "Mikrofon yeniden açıldı",
        micMuteMenuBarToggle: "Sessizken menü çubuğunda göster",
        micMuteMenuBarCaption: "Menü çubuğundaki uygulama simgesinin yanında üstü çizili kırmızı bir mikrofon görünür.",
        pastePlainName: "Düz metin olarak yapıştır",
        pastePlainCaption: "Kopyalananı renk, yazı tipi ve biçimlendirme olmadan yapıştırır. Orijinal panoda kalır.",
        launcherName: "Hızlı panel",
        launcherCaption: "En sevdiğiniz araçları toplayan, her yerden kısayolla açılan yüzen bir panel.",
        launcherOpenNow: "Hızlı paneli aç",
        launcherEditHint: "Araçları seçmek, gizlemek ve sürüklemek için ayar düğmesini kullanın.",
        launcherEmptyState: "Tüm araçlar gizli. Geri eklemek için ayar düğmesini kullanın.",
        launcherAddSection: "Geri ekle",
        launcherKeysHint: "Oklar gezinir, Enter açar, 1-9 doğrudan açar",
        switcherSection: "Uygulama değiştirici",
        switcherEnable: "Vorssaint değiştiricisini kullan",
        switcherEnableCaption: "Küçültülmüş pencereler ve aynı uygulamanın birden çok penceresi dahil, uygulamalar ve pencereler arasında geçiş yap.",
        switcherUsageHint: "Gezinmek için kısayolu basılı tut; pencereyi etkinleştirmek için bırak. Shift veya ← geri gider; W pencereyi kapatır; Q uygulamadan çıkar; Esc iptal eder.",
        switcherNoWindows: "Açık pencere yok",
        switcherIconRowMode: "%@’i büyük simgelerle göster",
        switcherIconRowModeCaption: "Her uygulama için bir simge ve üstünde o uygulamanın pencere önizlemelerini gösterir.",
        switcherSimpleMode: "Basit uygulama değiştirici",
        switcherSimpleModeCaption: "Uygulama simgelerini ve pencere başlıklarını gösterir; önizleme veya değiştirici tarafından ekran yakalama kullanmaz.",
        switcherShortcutHintApps: "Uygulamalar",
        switcherShortcutHintWindows: "Pencereler",
        switcherWindowShortcutCaption: "Ön plandaki uygulamanın pencereleri için bir değiştirici açar. Uygulama değiştirici açıkken seçili uygulamanın pencereleri arasında geçiş yapar.",
        switcherTakeOverSystemShortcuts: "macOS ⌘Tab ve ⌘` kısayollarını değiştir",
        switcherTakeOverSystemShortcutsCaption: "Eşleşen macOS uygulama ve pencere kısayollarını yalnızca Vorssaint değiştiricisi etkinken kapatır. Çalışan tüm uygulamalara erişim korunur.",
        switcherAppearanceDelay: "Görünme gecikmesi",
        switcherAppearanceDelayCaption: "Değiştirici görünmeden önce kısayolun ne kadar basılı tutulacağı.",
        switcherMergeTabs: "Uygulama başına bir giriş göster",
        switcherMergeTabsCaption: "Değiştiricide pencere başına bir giriş yerine, bir uygulamanın tüm pencerelerini tek girişte toplar.",
        switcherWindowlessApps: "Açık penceresi olmayan uygulamalar",
        switcherWindowlessAppsCaption: "Hiç penceresi olmayan açık uygulamalardan hangilerinin değiştiricide görüneceğini seçer.",
        switcherWindowlessAppsOff: "Gösterme",
        switcherWindowlessAppsFinder: "Yalnızca Finder",
        switcherWindowlessAppsAll: "Tüm uygulamalar",
        switcherNoOpenWindow: "Açık penceresi yok",
        switcherOtherDesktop: "Başka masaüstü",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Dock’tan pencereleri önizle",
        dockPreviewEnableCaption: "Pencerelerini görmek için Dock’taki açık bir uygulamanın üzerine gel, ardından açmak istediğin pencereye tıkla.",
        dockPreviewBackgroundOpacity: "Panel arka planı",
        dockPreviewBackgroundOpacityCaption: "Panelin arkasındakileri daha çok görmek için azalt.",
        dockPreviewOpenDelay: "Açılma gecikmesi",
        dockPreviewOpenDelayCaption: "Panelin açılması için imlecin bir simgenin üzerinde ne kadar bekleyeceği.",
        dockPreviewQuitAppOnClose: "× düğmesiyle uygulamadan çık",
        dockPreviewQuitAppOnCloseCaption: "Dock Preview’da × yalnızca o pencereyi kapatmak yerine uygulamadan tamamen çıkar.",
        dockClickMinimize: "Dock simgesine tıklayınca küçült",
        dockClickMinimizeCaption: "Etkin uygulamanın pencereleri Dock simgesine tıklandığında küçülür. Geri getirmek için yeniden tıklayın.",
        dockClickCycleWindows: "Dock simgesine tıklayınca pencere değiştir",
        dockClickCycleWindowsCaption: "Etkin uygulamanın Dock simgesine tıklayarak pencereleri arasında geçiş yapın, ⌘` gibi.",
        dockPreviewActiveNow: "Dock’ta etkin",
        dockPreviewDockUnavailable: "Dock öğeleri okunamadı.",
        dockPreviewAutohideBeta: "Beta. Bazı hatalarla karşılaşabilirsin.",
        dockPreviewOpenWindow: "Pencereyi aç",
        dockPreviewCloseWindow: "Pencereyi kapat",
        dockPreviewMinimizeWindow: "Pencereyi küçült",
        dockPreviewRestoreWindow: "Pencereyi geri yükle",
        dockPreviewPinPanel: "Önizlemeyi sabitle",
        dockPreviewUnpinPanel: "Önizleme sabitlemesini kaldır",
        dockPreviewPinned: "Sabitlendi",
        dockPreviewClosePanel: "Önizlemeyi kapat",
        dockPreviewPreviousWindow: "Önceki pencere",
        dockPreviewNextWindow: "Sonraki pencere",

        cutPasteName: "Kes ve yapıştır",
        cutPasteEnable: "Finder’da dosya kes ve yapıştır",
        cutPasteEnableCaption: "Finder’da dosya ve klasörleri kesmek için ⌘X, taşımak için ⌘V kullan.",
        cutPasteShowHUD: "Kayan paneli göster",
        cutPasteShowHUDCaption: "Finder etkinken kesilen dosyaları içeren kayan bir gösterge görüntüler.",
        cutPasteHowTitle: "Nasıl kullanılır",
        cutPasteStep1: "Finder’da öğeleri seç ve kesmek için ⌘X’e bas.",
        cutPasteStep2: "Hedef klasörü aç ve oraya taşımak için ⌘V’ye bas.",
        cutPasteTextNote: "Metin alanlarında (yeniden adlandırma gibi) ⌘X ve ⌘V normal çalışmaya devam eder.",
        cutPasteActiveNow: "Finder’da kesmeye hazır",
        cutPasteAutomationNote: "İlk seferde macOS, Finder’ı denetlemek için izin ister.",
        cutReadyTitle: "Kesildi",
        cutReadyHint: "taşımak için hedef klasörde",
        cutCancel: "Kesmeyi iptal et",
        cutDoneTitle: "Taşındı!",
        cutMovedSingular: "1 öğe taşındı",
        cutMovedPluralFormat: "%d öğe taşındı",
        cutSomeFailed: "Bazı öğeler taşınamadı",
        cutMovingTitle: "Taşınıyor…",
        cutMovingCountFormat: "%d / %d",

        autoQuitName: "Kapatınca çık",
        autoQuitEnable: "Son penceresi kapanınca uygulamadan çık",
        autoQuitEnableCaption: "Bir uygulamanın son penceresini kapatmak uygulamadan da çıkar.",
        autoQuitActiveNow: "Şu anda etkin",
        autoQuitHowTitle: "Nasıl çalışır",
        autoQuitStep1: "Bir uygulamanın son penceresini kapat (⌘W veya kırmızı düğme).",
        autoQuitStep2: "Uygulama kendiliğinden çıkar. “Değişiklikler kaydedilsin mi?” iletişimleri yine görünür.",
        autoQuitPredictableNote: "Normalde penceresiz çalışan uygulamalardan asla çıkılmaz.",
        autoQuitExceptionsTitle: "İstisnalar",
        autoQuitExceptionsCaption: "Bu listedeki uygulamalar penceresiz kalsa bile açık kalır.",
        autoQuitExceptionsEmpty: "İstisna yok",
        autoQuitAddApp: "Uygulama ekle…",

        uninstallerName: "Kaldırıcı",
        uninstallerEnableCaption: "Bir uygulamayı geride bıraktığı önbellekler, tercihler, günlükler ve kalıntılarla birlikte kaldırır.",
        uninstallerStep1: "Bir uygulamayı Ayarlar’a sürükle veya listeden seç.",
        uninstallerStep2: "Bulunan dosyaları ve kapladıkları alanı gözden geçir.",
        uninstallerStep3: "İstediğini Çöp Sepeti’ne taşı. Hiçbir şey kalıcı olarak silinmez.",
        uninstallerMenuItem: "Bir uygulamayı kaldır…",
        uninstallerDropTitle: "Buraya bir uygulama sürükle",
        uninstallerDropSubtitle: "veya taramak için birini seç",
        uninstallerChoose: "Uygulama seç…",
        uninstallerPickerTitle: "Uygulama seç",
        uninstallerPickerSearch: "Uygulamalarda ara",
        uninstallerPickerEmpty: "Uygulama bulunamadı",
        uninstallerEmptyNote: "Onayın olmadan hiçbir şey kaldırılmaz.",
        uninstallerFDANote: "Daha kapsamlı tarama için Tam Disk Erişimi ver.",
        uninstallerFDAGrant: "Erişim ver…",
        uninstallerFDAHint: "Listede Vorssaint’i aç. Orada yoksa + düğmesine tıkla ve Uygulamalar’dan Vorssaint’i seç. Erişim yalnızca uygulamayı yeniden açtıktan sonra geçerli olur.",
        uninstallerFDARelaunch: "Şimdi yeniden başlat",
        uninstallerScanning: "Dosyalar taranıyor…",
        uninstallerRemoving: "Çöp Sepeti’ne taşınıyor…",
        uninstallerFoundTitle: "bulundu",
        uninstallerSelectedFormat: "%d / %d seçili",
        uninstallerRemove: "Çöp Sepeti’ne Taşı",
        uninstallerCancel: "İptal",
        uninstallerDoneTitle: "Tamamlandı!",
        uninstallerFreedFormat: "%@ geri kazanıldı",
        uninstallerSomeFailed: "Bazı öğeler Çöp Sepeti’ne taşınamadı.",
        uninstallerFailedNeedsFDA: "Kum havuzundaki uygulama verileri yalnızca Tam Disk Erişimi ile taşınabilir. Yönetici parolası bu iznin yerine geçmez.",
        uninstallerFailedMoreFormat: "ve %d tane daha",
        uninstallerAnother: "Başka uygulama kaldır",
        uninstallerCatApp: "Uygulama",
        uninstallerCatSupport: "Destek",
        uninstallerCatCaches: "Önbellekler",
        uninstallerCatPreferences: "Tercihler",
        uninstallerCatContainers: "Kapsayıcılar",
        uninstallerCatLogs: "Günlükler",
        uninstallerCatState: "Kaydedilen durum",
        uninstallerCatOther: "Diğer",

        urlCleanerName: "URL temizle",
        urlCleanerEnable: "URL’leri kopyalarken temizle",
        urlCleanerEnableCaption: "Bir bağlantı panoya ulaşır ulaşmaz izleme parametrelerini kaldırır.",
        urlCleanerActiveNow: "Şu anda etkin",
        urlCleanerManualTitle: "Şimdi temizle",
        urlCleanerInputPlaceholder: "Bir URL yapıştır",
        urlCleanerOutputPlaceholder: "Temiz URL burada görünür",
        urlCleanerCleanButton: "Temizle",
        urlCleanerPasteButton: "Yapıştır",
        urlCleanerCopyButton: "Kopyala",
        urlCleanerClearButton: "Alanı temizle",
        urlCleanerNoURL: "Geçerli bir URL yapıştır.",
        urlCleanerNoChange: "Temizlenecek bir şey yok.",
        urlCleanerCleaned: "URL temizlendi.",
        urlCleanerCopied: "Kopyalandı.",
        urlCleanerLocalNote: "Yerel. Ağ yok.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Formülleri ve cask’leri ara, yükle ve kaldır.",
        homebrewMissingTitle: "Homebrew bulunamadı",
        homebrewMissingBody: "Vorssaint, resmi Homebrew yükleyicisiyle Terminal’i açabilir. Terminal adımları gösterir ve gerekirse parolanı ister.",
        homebrewInstallHomebrew: "Homebrew yükle",
        homebrewInstallHomebrewCaption: "Terminal bitirdiğinde buraya dön ve Yenile’ye tıkla.",
        homebrewInstallHomebrewOpened: "Yükleyici Terminal’de açıldı.",
        homebrewShellSetupTitle: "Terminal kurulumunu tamamla",
        homebrewShellSetupBody: "Homebrew yüklü, ancak Terminal brew komutunu henüz bulamayabilir. Vorssaint, kurulum komutuyla Terminal’i açabilir.",
        homebrewShellSetupButton: "Terminal’i ayarla",
        homebrewShellSetupOpened: "Komut Terminal’de açıldı. Sonra buraya dön ve Yenile’ye tıkla.",
        homebrewRefresh: "Yenile",
        homebrewCheckPackages: "Paketleri denetle",
        homebrewTrustTitle: "Tap henüz güvenilir değil",
        homebrewTrustCaption: "Homebrew artık üçüncü taraf tap kullanmadan önce onayınızı istiyor. Devam etmek için %@ kaynağına güvenin.",
        homebrewTrustButton: "Güven ve devam et",
        homebrewSearchPlaceholder: "Paket ara",
        homebrewKeyboardHint: "Boşluk veya Return macOS panelini kapatır. Arama düğmesini kullan.",
        homebrewSearchButton: "Ara",
        homebrewSearchResults: "Sonuçlar",
        homebrewInstalled: "Yüklü",
        homebrewAll: "Tümü",
        homebrewFormulas: "Formüller",
        homebrewCasks: "Cask’ler",
        homebrewNoPackages: "Paket bulunamadı",
        homebrewNoSelection: "Yüklü bir paket seç veya yenisini ara.",
        homebrewDetailsTitle: "Paket ayrıntıları",
        homebrewInstall: "Yükle",
        homebrewUninstall: "Kaldır",
        homebrewUpgrade: "Güncelle",
        homebrewUpgradeAll: "Tümünü güncelle",
        homebrewUpdateHomebrew: "Homebrew’i güncelle",
        homebrewAllPackages: "paket",
        homebrewOpenTerminal: "Terminal’i aç",
        homebrewCancelOperation: "İptal",
        homebrewClearLog: "Günlüğü temizle",
        homebrewLogTitle: "Günlük",
        homebrewVersion: "Sürüm",
        homebrewDescription: "Tür",
        homebrewHomepage: "Web sitesini aç",
        homebrewPopularity: "Popülerlik",
        homebrewPopularityFormat: "%@ yükleme, %@ gün içinde",
        homebrewInstalledBadge: "Yüklü",
        homebrewNotInstalledBadge: "Yüklü değil",
        homebrewUpdates: "Güncellemeler",
        homebrewUpdateAvailableBadge: "Güncelleme var",
        homebrewLatestVersion: "En son",
        homebrewConfirmInstallTitle: "Homebrew ile yüklensin mi?",
        homebrewConfirmInstallBodyFormat: "Homebrew %@ paketini indirip yükleyecek. Bağımlılıklar da yüklenebilir.",
        homebrewConfirmUninstallTitle: "Homebrew ile kaldırılsın mı?",
        homebrewConfirmUninstallBodyFormat: "Homebrew %@ paketini kaldıracak. Yapılandırma dosyaları sistemde kalabilir.",
        homebrewConfirmUpgradeTitle: "Homebrew ile güncellensin mi?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew %@ paketinin en son sürümünü indirip uygulayacak. Bağımlılıklar da güncellenebilir.",
        homebrewConfirmUpgradeAllTitle: "Tümü Homebrew ile güncellensin mi?",
        homebrewConfirmUpgradeAllBody: "Homebrew, güncellemesi bulunan paketlerin en son sürümlerini indirip uygulayacak. Bağımlılıklar da güncellenebilir.",
        homebrewConfirmUpdateHomebrewTitle: "Homebrew güncellensin mi?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew en son bilgileri alacak ve ardından paketlerini yeniden yükleyecek.",
        homebrewTerminalFallback: "Bu işlem, yönetici parolasını istemek için Terminal’e ihtiyaç duyar. Vorssaint parolaları yakalamaz.",
        homebrewLoading: "Yükleniyor…",
        homebrewSearchEmpty: "Sonuç yok",
        homebrewOperationInstallFormat: "%@ yükleniyor",
        homebrewOperationUninstallFormat: "%@ kaldırılıyor",
        homebrewOperationUpgradeFormat: "%@ güncelleniyor",
        homebrewOperationUpgradeAll: "Paketler güncelleniyor",
        homebrewOperationUpdateHomebrew: "Homebrew güncelleniyor",
        homebrewOperationInstalledFormat: "%@ yüklendi.",
        homebrewOperationUninstalledFormat: "%@ kaldırıldı.",
        homebrewOperationUpgradedFormat: "%@ güncellendi.",
        homebrewOperationUpgradedAll: "Paketler güncellendi.",
        homebrewOperationUpdatedHomebrew: "Homebrew güncellendi.",
        homebrewOperationFailedFormat: "%@ tamamlanamadı.",
        homebrewOperationCancelled: "İşlem iptal edildi.",
        homebrewOperationPreparing: "Hazırlanıyor…",
        homebrewOperationDownloading: "Dosyalar indiriliyor…",
        homebrewOperationInstalling: "Dosyalar yükleniyor…",
        homebrewOperationUninstalling: "Dosyalar kaldırılıyor…",
        homebrewOperationUpgrading: "Dosyalar güncelleniyor…",
        homebrewOperationFinalizing: "Bitiriliyor…",
        homebrewOperationRefreshing: "Liste yenileniyor…",
        homebrewOperationTerminal: "Terminal’de devam et.",
        homebrewOperationElapsedFormat: "%@ geçti",
        homebrewOperationShowDetails: "Ayrıntıları göster",
        homebrewOperationHideDetails: "Ayrıntıları gizle",
        homebrewOperationTechnicalLog: "Teknik ayrıntılar",
        homebrewOperationProgressUnknown: "Homebrew henüz yüzde bildirmedi.",

        mediaName: "Medya",
        mediaEnableCaption: "Videoları sıkıştır, görselleri dönüştür ve işle, GIF oluştur ve metni yerel olarak çıkar.",
        mediaLocalNote: "Yerel. Ağ yok.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Görsel",
        mediaToolText: "Metin",
        mediaSelectFile: "Dosya seç",
        mediaDropHint: "Buraya dosya bırak veya seçmek için tıkla.",
        mediaOutput: "Çıktı",
        mediaOutputAutomatic: "Otomatik",
        mediaChooseOutput: "Hedef",
        mediaStartVideo: "Videoyu sıkıştır",
        mediaStartGIF: "GIF oluştur",
        mediaStartImage: "Görseli işle",
        mediaStartConvertPDF: "PDF’ye dönüştür",
        mediaStartText: "Metni çıkar",
        mediaCancel: "İptal",
        mediaStartTime: "Başlangıç",
        mediaEndTime: "Bitiş",
        mediaQuality: "Sıkıştırma",
        mediaCompressionLow: "Düşük",
        mediaCompressionMedium: "Orta",
        mediaCompressionHigh: "Yüksek",
        mediaMaxSize: "Boyut",
        mediaSizingResolution: "Çözünürlük",
        mediaSizingFileSize: "Dosya boyutu",
        mediaTargetSize: "Hedef boyut",
        mediaTargetSizeHint: "Çözünürlük, sınırın altında kalacak şekilde ayarlanır.",
        mediaErrorTargetTooSmall: "Hedef boyut bu klip için çok küçük. Klibi kısaltın veya sınırı artırın.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Genişlik",
        mediaFPS: "FPS",
        mediaKeepAudio: "Sesi koru",
        mediaCodec: "Codec",
        mediaFormat: "Biçim",
        mediaStripMetadata: "Meta verileri kaldır",
        mediaLoopGIF: "GIF’i döngüye al",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Doğru",
        mediaOCRFast: "Hızlı",
        mediaLanguageCorrection: "Dil düzeltmesi",
        mediaTextOutputNote: "Çıkarılan metin kopyalanabilir ve TXT olarak kaydedilebilir.",
        mediaRunning: "İşleniyor",
        mediaCompleted: "Tamamlandı",
        mediaCancelled: "İptal edildi.",
        mediaOpenInFinder: "Göster",
        mediaCopyText: "Metni kopyala",
        mediaRunAgain: "Tekrar çalıştır",
        mediaEmptyText: "Metin bulunamadı.",
        mediaResultSavedFormat: "%@ olarak kaydedildi",
        mediaResultSizeFormat: "%@ -> %@",
        mediaResultGrewCaption: "Dönüştürülen dosya orijinalinden daha büyük oldu.",
        mediaErrorNoFile: "Önce bir dosya seç.",
        mediaErrorNoVideo: "Bu dosyada video izi yok.",
        mediaErrorSameOutput: "Özgün dosyadan farklı bir hedef seç.",
        mediaErrorUnsupported: "Biçim macOS tarafından desteklenmiyor.",

        shelfName: "Raf",
        shelfEnable: "Dosya sürüklemek için geçici alan",
        shelfEnableCaption: "Dosyaları, görselleri ve metinleri toplamak, sonra istediğin yere sürüklemek için yüzen bir alan.",
        shelfHowTitle: "Nasıl kullanılır",
        shelfStep1: "Kısayolla veya sürüklerken fareyi sallayarak aç.",
        shelfStep2: "Dosyaları, görselleri, bağlantıları veya metni tutması için üzerine bırak.",
        shelfStep3: "Gerektiğinde her öğeyi istediğin uygulamaya geri sürükle.",
        shelfShakeToggle: "Sürüklerken fareyi sallayınca aç",
        shelfShakeCaption: "Bir öğeyi tutarken imleci hızlıca sallarsan raf imlecin yanında belirir.",
        shelfDropZoneToggle: "Sürüklenen dosyaları menü çubuğunda tut",
        shelfDropZoneCaption: "Bir dosyayı sürüklerken raf, menü çubuğu simgesinin altında belirir. Bıraktıkların tam orada, tek tıkla daraltıp açtığın bir düğmede kalır ve raf boşaldığında kaybolur.",
        shelfDropZoneLabel: "Buraya bırak",
        shelfCollapse: "Daralt",
        shelfBehaviorTitle: "Kullanımdan sonra",
        shelfCloseAfterDrop: "Başka bir uygulamaya bırakınca kapat",
        shelfCloseAfterDropCaption: "Hedef öğeleri kabul edince rafı kapatır. Paneldeki iğne rafı açık tutar.",
        shelfRemoveAfterDrop: "Bıraktıktan sonra öğeleri kaldır",
        shelfRemoveAfterDropCaption: "Başka bir uygulamanın kabul ettiği öğeler raftan çıkar. Bir kopyayı tutmak için kapat.",
        shelfExclusionsTitle: "Otomatik istisnalar",
        shelfExclusionsEmpty: "Uygulama eklenmedi.",
        shelfExclusionsCaption: "Bu uygulamalarda başlayan sürüklemelerde sallama ve menü çubuğu alanı açılmaz. Kısayol ve Şimdi aç çalışmaya devam eder.",
        shelfPin: "Açık tut",
        shelfUnpin: "Kullanımdan sonra kapanmasına izin ver",
        extraBrightnessName: "Ekstra parlaklık",
        extraBrightnessCaption: "Ekranın HDR payını kullanarak en yüksek parlaklığın ötesine geçer. Daha çok pil harcar ve Mac ısınabilir.",
        extraBrightnessLevelLabel: "Yoğunluk",
        extraBrightnessUnsupported: "Yalnızca 14 ve 16 inç MacBook Pro gibi XDR ekranlarda kullanılabilir.",
        shelfHotkeyLabel: "Kısayol",
        shelfOpenNow: "Şimdi aç",
        shelfNoPermission: "İzin gerektirmez.",
        shelfMenuItem: "Rafı aç",
        shelfTitle: "Raf",
        shelfEmpty: "Öğeleri buraya sürükle",
        shelfClearAll: "Tümünü temizle",
        shelfRemoveSelected: "Seçilenleri kaldır",
        shelfSelectedFormat: "%d seçili",
        shelfHint: "Seçmek için tıkla. Kullanmak için sürükle veya diğer eylemler için sağ tıkla.",
        shelfItemImage: "Görsel",
        shelfTooltipItemsFormat: "%d öğe",
        shelfTooltipItemsFew: "%d öğe",
        shelfTooltipImageSingular: "%d resim",
        shelfTooltipImageFew: "%d resim",
        shelfTooltipImagePlural: "%d resim",
        shelfTooltipFileSingular: "%d dosya",
        shelfTooltipFileFew: "%d dosya",
        shelfTooltipFilePlural: "%d dosya",
        shelfTooltipNoteSingular: "%d not",
        shelfTooltipNoteFew: "%d not",
        shelfTooltipNotePlural: "%d not",
        shelfTooltipLinkSingular: "%d bağlantı",
        shelfTooltipLinkFew: "%d bağlantı",
        shelfTooltipLinkPlural: "%d bağlantı",
        shelfActionOpen: "Aç",
        shelfActionOpenWith: "Birlikte aç",
        shelfActionShare: "Paylaş",

        breakdownMeasuring: "Ölçülüyor…",

        mixerSection: "Ses mikseri",
        mixerEmpty: "Ses kullanan uygulamalar burada görünür",
        mixerUnavailable: "macOS 14.4 ve sonrasında kullanılabilir",
        mixerPermissionBody: "Uygulama başına ses düzeyini ayarlamak için Sistem Ayarları’nda “Ekran ve Sistem Sesi Kaydı”na izin ver. Ses hiçbir zaman kaydedilmez.",
        mixerResetTooltip: "%100’e sıfırla",
        mixerOutputDefault: "Varsayılan",
        mixerOutputCurrent: "geçerli",
        mixerOutputUnavailable: "Çıkış kullanılamıyor",
        mixerOutputFallback: "Bu aygıt geri dönene kadar varsayılan kullanılıyor.",
        mixerBypassedCaption: "Bu uygulama sesini kendisi yönetir.",
        mixerOutputTooltip: "Çıkış seç",
        mixerSystemOutputTitle: "Çıkış",
        mixerSystemOutputNoDevices: "Çıkış bulunamadı",
        mixerSystemOutputTooltip: "Sistem çıkışını seç",
        mixerSystemOutputErrorFormat: "Geçiş yapılamadı: %@",
        mixerLowerOnHeadphonesDisconnect: "Kulaklık bağlantısı kesilince sesi düşür",
        mixerLowerOnHeadphonesDisconnectCaption: "Kablolu veya Bluetooth kulaklık bağlantısı kesildiğinde çıkışı seçilen seviyeye ayarlar.",
        mixerHeadphonesDisconnectVolume: "Bağlantı kesilince ses",
        preciseVolumeRollerEnable: "Daha hassas ses adımları kullan",
        preciseVolumeRollerCaption: "Ses tekerleklerini ve tuşlarını daha küçük sistem adımlarına dönüştürür.",
        preciseVolumeRollerTapFailed: "Ses tuşları dinlenemedi.",
        soundOutputSwitcherTitle: "Çıkış değiştirici",
        soundOutputSwitcherEnable: "Çıkışları kısayolla değiştir",
        soundOutputSwitcherCaption: "Çıkışları seç ve kısayolla bir sonraki kullanılabilir çıkışa geç.",
        soundOutputSwitcherDevices: "Döngüdeki çıkışlar",
        soundOutputSwitcherNoAvailableSelection: "En az bir kullanılabilir çıkış seç.",
        mixerInputTitle: "Mikrofon",
        mixerInputNoDevices: "Mikrofon bulunamadı",
        mixerInputUnavailable: "Mikrofon kullanılamıyor",
        mixerInputFallback: "Bu mikrofon geri dönene kadar varsayılan kullanılıyor.",
        mixerInputTooltip: "Mikrofon seç",
        mixerInputErrorFormat: "Geçiş yapılamadı: %@",
        mixerVisibleApps: "Listedeki uygulamalar",
        mixerAllShown: "Tümü",
        mixerHiddenCountLabel: "Gizli",
        mixerHideFromList: "Listeden gizle",

        updatesSection: "Güncellemeler",
        autoCheckToggle: "Güncellemeleri otomatik denetle",
        includeBetaUpdatesToggle: "Beta güncellemelerini al",
        includeBetaUpdatesCaption: "Beta sürümleri geliştirme aşamasındaki özellikleri içerir ve kararsızlık gösterebilir.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Şimdi denetle",
        updateChecking: "Denetleniyor…",
        updateUpToDate: "En son sürümdesin.",
        updateAvailablePrefix: "Güncelleme var:",
        updateInstallButton: "İndir ve yükle",
        updateDownloading: "Güncelleme indiriliyor…",
        updateInstalling: "Yükleniyor ve yeniden başlatılıyor…",
        updateFailedPrefix: "Denetlenemedi:",
        updateLastChecked: "Son denetleme:",
        updateNotifyTitle: "Vorssaint güncellemesi",
        updateInstallFailedBody: "Güncelleme indirildi ancak uygulanamadı. GitHub sürümler sayfasından en yeni sürümü indirin ve uygulamayı mevcut olanın üzerine sürükleyin.",
        updateNeedsApplicationsTitle: "Vorssaint’i Uygulamalar klasörüne taşıyın",
        updateNeedsApplicationsBody: "Uygulama, disk görüntüsü veya geçici bir sistem konumu gibi güncellenemeyen bir yerden çalışıyor. Vorssaint’i Uygulamalar klasörüne sürükleyin, oradan açın ve yeniden deneyin.",
        menuCheckUpdates: "Güncellemeleri denetle…",

        permissionRequired: "İzin gerekli",
        permissionAccessibility: "Erişilebilirlik",
        permissionScreenRecording: "Ekran Kaydı",
        permissionGranted: "Verildi",
        permissionMissing: "Verilmedi",
        permissionOpenSettings: "Sistem Ayarları’nı aç…",
        permissionRequest: "Erişim ver",
        permissionRestartNote: "macOS izin verdikten sonra uygulamayı yeniden açmanı isteyebilir.",

        aboutDescription: "Mac’in için bir yardımcı merkez.\nEnerji, sistem monitörü, kaydırma ve pencere değiştirici, doğrudan menü çubuğunda.",
        versionPrefix: "Sürüm",
        reviewIntro: "Tanıtımı incele",
        reviewHighlights: "Yenilikler turunu incele",
        viewOnGitHub: "GitHub’da görüntüle",

        obContinue: "Devam",
        obBack: "Geri",
        obSkipStep: "Bu adımı atla",
        obStart: "Vorssaint’i aç",
        obStepWelcomeTitle: "Vorssaint’e hoş geldin",
        obStepWelcomeBody: "Günlük macOS kullanımını daha pratik yapan sade bir menü çubuğu yardımcısı.",
        obWelcomeBullet1Title: "Enerji kontrol altında",
        obWelcomeBullet1Body: "Mac’i istediğin kadar, kapak kapalıyken bile uyanık tut.",
        obWelcomeBullet2Title: "Sisteme net bakış",
        obWelcomeBullet2Body: "CPU, GPU ve pil sıcaklıkları, donanım kullanımı ve bellek basıncı gerçek zamanlı.",
        obWelcomeBullet3Title: "Fare ve pencereler, senin tarzın",
        obWelcomeBullet3Body: "Ters fare kaydırması ve küçük resimli pencere değiştirici.",
        obLanguageLabel: "Dil",
        obStepAccessibilityTitle: "Erişilebilirlik",
        obStepAccessibilityBody: "Fare kaydırmasını ters çevirmek ve pencere değiştiricinin klavyeye yanıt vermesi için gereklidir.",
        obAccessibilityWhy: "Uygulama yalnızca fare tekerleğini ve değiştirici kısayolunu izler. Hiçbir şey kaydedilmez veya bir yere gönderilmez.",
        obStepRecordingTitle: "Ekran Kaydı",
        obStepRecordingBody: "Değiştiricinin yalnızca simge yerine gerçek pencere küçük resimleri göstermesini sağlar.",
        obRecordingWhy: "Küçük resimler anlık oluşturulur, bellekte kalır ve Mac’inden çıkmaz. Bu izin olmadan değiştirici simgelerle çalışmaya devam eder.",
        obStepMonitorTitle: "Sistem monitörü",
        obStepMonitorBody: "Panel CPU, GPU ve pil sıcaklıklarını, donanım kullanımını ve bellek basıncını gösterir.",
        obMonitorNoPermission: "İzin gerekmez. Sensörler doğrudan sistemden okunur.",
        obStepOptionalTitle: "İsteğe bağlı özellikler",
        obStepOptionalBody: "Şimdi kullanmak istediklerini aç. Her şeyi daha sonra Ayarlar’dan değiştirebilirsin.",
        obStepStatusTitle: "Kontrol",
        obStepStatusBody: "İstediğin özellikler için her şeyin hazır olduğundan emin ol.",
        obStatusRecheck: "Tekrar denetle",
        obStepDoneTitle: "Her şey hazır!",
        obStepDoneBody: "Vorssaint Mac’inle ilgilenmeye başladı bile.",
        obDoneHint: "Ekranın sağ üstündeki menü çubuğunda kara deliği ara.",
        obWhatsNewTitle: "Bu sürümdeki yenilikler",
        obWhatsNewFallback: "Bu güncelleme en son düzeltmeleri ve iyileştirmeleri içerir.",
        obLanguageUpdateTitle: "Artık kendi dilinde",
        obLanguageUpdateBody: "Vorssaint artık birçok dil konuşuyor. Kullanmak istediğin dili seç; bunu istediğin zaman Ayarlar’dan değiştirebilirsin.",
        obPurposeTitle: "Sizi buraya ne getirdi?",
        obPurposeBody: "Hazır bir kurulum veya kullanmak istediğiniz özellikleri tek tek seçin.",
        obPurposeSkip: "Özellikleri daha sonra Ayarlar’dan değiştirebilirsiniz.",

        tabMonitor: "Monitör",
        monitorMenuBarSection: "Menü çubuğunda",
        monitorMenuBarCaption: "Menü çubuğunda simgenin yanında ne görüneceğini seç.",
        monitorCombineTemperatures: "Kullanımı ve sıcaklığı birleştir",
        monitorCombineTemperaturesCaption: "Aynı öğe için kullanım ve sıcaklık etkinse, bunları tek blokta göster.",
        monitorSeparateMenuBarMetrics: "Metrikleri kendi öğelerine ayır",
        monitorSeparateMenuBarMetricsCaption: "Etkin blokları menü çubuğunda ayırır ve birleştirme açıkken kullanım ile sıcaklığı birlikte tutar.",
        monitorNetworkUploadFirst: "Yükleme indirme üstünde",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Bellek",
        monitorShowNetwork: "Ağ",
        monitorShowPowerLabel: "Güç",
        monitorIntervalLabel: "Güncelleme aralığı",
        monitorInterval1: "1 saniye",
        monitorInterval2: "2 saniye",
        monitorInterval5: "5 saniye",
        monitorPanelSection: "Panelde",
        panelNavigationMode: "Panelde bölümlere göre gezin",
        panelNavigationCaption: "Her seferinde bir bölüm gösterir. Her şeyi kesintisiz kaydırmada görmek için Liste’yi seç.",
        panelFooterSections: "Bölümler",
        panelFooterList: "Liste",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Bazı hatalarla karşılaşabilirsin.",

        networkSection: "Ağ",
        networkDownload: "İndirme",
        networkUpload: "Yükleme",
        networkThisSession: "Bu oturum",
        networkMeasuring: "Ölçülüyor…",
        networkApps: "Ağı kullanan uygulamalar",
        networkAppsIdle: "Şu anda ağı kullanan uygulama yok",

        diskSection: "Diskler",
        diskUsed: "kullanıldı",
        diskFree: "boş",
        diskAvailable: "kullanılabilir",
        diskPurgeable: "silinebilir",
        diskInternal: "Dahili",
        diskExternal: "Harici",
        diskSelect: "Disk seç",
        diskRead: "Okuma",
        diskWrite: "Yazma",
        diskSMARTStatus: "Durum",
        diskSMARTUnavailable: "Bu disk için SMART kullanılamıyor",
        diskTotalRead: "Toplam okuma",
        diskTotalWritten: "Toplam yazma",
        diskTemperature: "Sıcaklık",
        diskHealth: "Sağlık",
        diskPowerCycles: "Güç döngüleri",
        diskPowerOnHours: "Çalışma saatleri",
        diskUnsafeShutdowns: "Güvensiz kapanmalar",
        diskMediaErrors: "Medya hataları",
        diskEject: "Çıkar",
        diskEjectAll: "Tümünü çıkar",
        diskEjecting: "Çıkarılıyor…",
        diskReadyToRemove: "Kaldırmaya hazır",
        diskEjectFailed: "Çıkarılamadı",
        diskProtectionCaption: "Bağlantıyı kesmeden önce çıkar.",
        diskNoExternal: "Çıkarılmaya hazır harici disk yok.",
        diskOpenInFinder: "Aç",
        diskStorageSettings: "Depolama",
        diskNoDisks: "Bağlı disk bulunamadı.",

        powerSection: "Güç",
        powerSystem: "Sistem",
        powerAdapter: "Adaptör",
        powerBattery: "Pil",
        powerCharging: "Şarj oluyor",
        powerOnBattery: "Pilde",
        powerPluggedIn: "Prize bağlı",
        powerUnavailable: "Bu Mac’te güç metrikleri kullanılamıyor",
        powerAdapterMaxFormat: "%@ maks.",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU sıcaklığı",
        monitorShowGPUTemperature: "GPU sıcaklığı",
        monitorShowBatteryTemperature: "Pil sıcaklığı",
        monitorShowPeripheralBattery: "Çevre birimi pili",
        peripheralBatteryNoDevices: "Aygıt bulunamadı",
        monitorGraphsSection: "Grafikler",
        monitorGraphsCaption: "Hangi metriklerin zaman içinde grafik göstereceğini seç.",

        updateBannerTitle: "Güncelleme var",
        updateBannerAction: "Güncelle",
        obStepMenuBarTitle: "Menü çubuğunda metrikler",
        obStepMenuBarBody: "Simgenin yanında ne gösterileceğini seç. Yukarıdaki önizleme canlı güncellenir.",
        obStepMenuBarNote: "Yeni: Ağ ve Güç blokları ve panelde grafikler. Tümünü daha sonra Ayarlar › Monitör bölümünde ince ayarlayabilirsin.",
        monitorMenuBarPresetLabel: "Stil",
        menuBarPresetReadable: "Okunaklı",
        menuBarPresetDense: "Sıkı",
        menuBarSpacingLabel: "Menü çubuğu aralığı",
        menuBarSpacingStandard: "Standart",
        menuBarSpacingCompact: "Sıkışık",
        menuBarHideIconToggle: "Metrikler gösterilirken uygulama simgesini gizle",
        menuBarHideIconCaption: "Metrikler çubuktan kalktığında ve bildirilecek bir şey olduğunda (güncelleme hazır veya mikrofon sessizde) simge kendiliğinden geri döner.",
        monitorLabelStyleLabel: "Etiketler",
        menuBarLabelStyleCompact: "Kompakt",
        menuBarLabelStyleClassic: "Klasik",
        monitorMemoryStyleLabel: "Belleği şöyle göster",
        monitorMemoryPressureDot: "Basınç noktası",
        memoryStyleDot: "Nokta",
        memoryStylePercent: "%",
        memoryStyleBoth: "İkisi de",
        systemUptime: "Çalışma süresi",
        batteryCharge: "Şarj",
        powerHealth: "Pil sağlığı",
        powerCycles: "döngü",
        speedTestRun: "Hız testi",
        speedTestAgain: "Tekrar test et",
        speedTestLatency: "Gecikme",
        speedTestTesting: "Test ediliyor…",
        speedTestFailed: "Test başarısız",

        monitorShowInPanel: "Panelde göster",
        disclosureExpanded: "Genişletildi",
        disclosureCollapsed: "Daraltıldı",
        panelHideItem: "Panelden gizle",
        panelShowItem: "Panelde göster",
        panelHiddenItem: "Gizli",
        monitorItemUptime: "Çalışma süresi",
        monitorItemNetSpeed: "Canlı hız",
        monitorItemNetTotals: "Oturum toplamları",
        monitorItemNetTest: "Hız testi",
        monitorItemDiskUsage: "Disk kullanımı",
        monitorItemDiskActivity: "Canlı etkinlik",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Harici koruma",
        monitorItemDiskTools: "Araçlar",
        monitorPanelConfigHint: "Ne göstereceğini seçmek için bir blok aç.",
        monitorOrderSection: "Bölüm sırası",
        monitorOrderHint: "Panel bölümlerini yeniden sıralamak için sürükle ve her birini göstermek veya gizlemek için göz simgesini kullan.",
        obStepPanelTitle: "Panelde neler var",
        obStepPanelBody: "Her bloğu aç ve simgeye tıkladığında tam olarak ne görüneceğini seç.",
        obStepPanelNavigationTitle: "Bölüm tabanlı panel",
        obStepPanelNavigationBody: "Panel artık her seferinde bir bölüm gösterebilir. Ayarlar’da Bölümler ve Liste arasında geçiş yapabilirsin.",

        cleaningMenuItem: "Temizleme Modu",
        utilitiesSection: "Araçlar",
        quickControlsSection: "Denetimler",
        panelCategoryWindows: "Pencereler",
        panelCategoryInput: "Fare ve klavye",
        panelCategoryFiles: "Dosyalar",
        windowMaximizeName: "Pencereleri büyüt",
        windowMaximizeCaption: "Yeşil düğme başka bir Space oluşturmadan pencereyi büyütür.",
        windowMaximizeActiveNow: "Yeşil düğme geçersiz kılma etkin",
        windowMaximizeNeedsAccessibility: "Çalışması için Erişilebilirlik gerekir.",
        keyDebounceName: "Tuş sekmesini filtrele",
        keyDebounceEnable: "Yinelenen tuşları filtrele",
        keyDebounceCaption: "Çok hızlı yinelenen tuş basışlarını filtreler.",
        keyDebounceActiveNow: "Filtre etkin",
        keyDebounceGlobalWindow: "Genel pencere",
        keyDebouncePerKeySection: "Belirli tuşlar",
        keyDebouncePerKeyCaption: "Tuşa özel değerler genel pencereyi geçersiz kılar. Bir tuşu filtrelememek için 0 ms kullan.",
        keyDebounceKeyLabel: "Tuş",
        keyDebounceWindowLabel: "Pencere",
        keyDebounceAddKey: "Tuş ekle",
        keyDebounceNoOverrides: "Belirli tuş ayarı yok.",
        keyDebounceRemoveKey: "Tuşu kaldır",
        cleaningPanelCaption: "Güvenle temizleyebilmen için klavyeyi kilitler.",
        cleaningOverlayTitle: "Klavye temizlik için kilitlendi",
        cleaningOverlaySubtitle: "Kilidi açmak için Esc tuşuna 5 kez bas",
        cleaningOverlayUnlock: "Kilidi aç",
        cleaningOverlayMouseHint: "Fare ve izleme dörtgeni çalışmaya devam eder",
        cleaningKeepScreenVisibleToggle: "Ekranı görünür tut",
        cleaningKeepScreenVisibleCaption: "İçeriği karartmak yerine ekranın köşesinde göze çarpmayan bir gösterge gösterir.",
        cleaningStartNow: "Klavyeyi şimdi kilitle",
        cleaningNeedsAxTitle: "Erişilebilirlik gerekli",
        cleaningNeedsAxBody: "Klavyeyi güvenle kilitlemek için Vorssaint’in Erişilebilirlik iznine ihtiyacı var. Sistem Ayarları’ndan izin ver ve tekrar dene.",

        tabSupport: "Destek",
        shortcutsPageCaption: "Bu Mac’te yüklü özelliklerin tüm genel kısayollarını burada düzenleyin. Etkin olmayan kısayollar kayıtlı kalır ancak çalışmaz.",
        shortcutsPageTitle: "Klavye kısayolları",
        settingsSearchPlaceholder: "Ayarlarda ara",
        donateHeading: "Vorssaint’in gelişmesine destek ol",
        donateMessage: "Vorssaint ücretsiz, bağımsız ve boş zamanlarımda geliştiriliyor. Maddi destek olmak istersen Buy Me a Coffee, geliştirmeyi sürdürmeme doğrudan yardımcı olur.",
        donateButton: "Buy Me a Coffee ile destek ol",
        donateThanks: "Burada olduğun için teşekkürler. 🖤",
        supportIntroTitle: "Vorssaint’in gelişmesine destek ol",
        supportIntroMessage: "Geliştirmeye maddi destek olmak istersen bunu yapabileceğin tek yer Buy Me a Coffee.",
        supportIntroStarButton: "GitHub’da Vorssaint’e yıldız ver",
        supportIntroStarMessage: "Maddi destek asla beklenmez. GitHub’da verilen bir yıldız, daha fazla kişinin Vorssaint’i keşfetmesine yardımcı olur ve geliştirilmesinde gerçek bir fark yaratır.",
        supportIntroCoffeeButton: "Buy Me a Coffee ile destek ol",
        supportIntroLaterButton: "Şimdi değil",
        supportIntroDoneButton: "Tamam",
        discordIntroTitle: "Vorssaint Discord topluluğu daha yeni başlıyor",
        discordIntroMessage: "Vorssaint topluluğu yeni ve hâlâ şekilleniyor. Diğer kullanıcılarla tanışmak ve uygulamanın etrafında sıcak bir alan oluşturmaya yardım etmek için erkenden katıl.",
        discordIntroJoinButton: "Discord topluluğuna katıl",
        communityIntroTitle: "Her şeyi herkesten önce gör",
        communityIntroMessage: "Beni X’te zaten takip edenler bu güncellemedeki birçok yeniliği herkesten önce gördü. Orada sırada neler olduğuna dair ön izlemeler paylaşıyor ve nasıl çalıştıklarını gösteriyorum. Böylece güncelleme çıkmadan önce temelini öğrenebilirsin. Takip et ve sırada ne olduğunu gör!",
        communityIntroFollowButton: "X’te @vorssaint’i takip et",
        homebrewOfficialIntroTitle: "Artık resmî Homebrew kataloğunda",
        homebrewOfficialIntroMessage: "Vorssaint artık doğrudan resmî Homebrew kataloğundan kurulabilir.",
        homebrewOfficialIntroInstallLabel: "Yeni kurulum",
        homebrewOfficialIntroMigrationTitle: "Eski tap’i mi kullanıyordunuz?",
        homebrewOfficialIntroMigrationMessage: "Eski tap’i bir kez kaldırın. Uygulama ve ayarlarınız yerinde kalır.",
        homebrewOfficialIntroCopyButton: "Komutu kopyala",
        updateShowcaseTitle: "3.1.4’te yenilikler",
        updateShowcaseMessage: "Bu güncellemedeki başlıca iyileştirmelere hızlıca göz at.",
        updateShowcaseUnavailable: "Video şu anda yüklenemedi. Yine de devam edebilirsin.",
        updateShowcaseRestart: "Yeniden başlat",
        showMenuBarIcon: "Menü çubuğu simgesini göster",
        showMenuBarIconCaption: "Vorssaint simgesi kaybolursa (macOS, çubukta yer kalmadığında menü çubuğu simgelerini gizleyebilir; çentikli Mac’lerde yaygındır), Vorssaint’i Uygulamalar’dan veya Spotlight’tan yeniden aç: bu simgeyi yeniden oluşturur ve hâlâ gizliyse bu pencereyi açar.",
        menuBarIconStillHiddenTitle: "Simge hâlâ gizli",
        menuBarIconStillHiddenBody: "Simge yeniden oluşturuldu ancak macOS ona görünür bir yer vermedi. Menü çubuğunda büyük olasılıkla yer kalmadı: bazı menü çubuğu simgelerini kaldırın (veya menüleri uzun uygulamaları kapatın) ve yeniden deneyin.",
        menuBarIconManagerHintFormat: "%@ açık ve simgeyi gizli bölümünde tutuyor olabilir. Vorssaint’i orada arayın veya %@ uygulamasını Vorssaint’i her zaman gösterecek şekilde ayarlayın.",
        shortcutRecording: "Yeni kısayola bas",
        shortcutReset: "Sıfırla",
        shortcutNone: "Yok",
        shortcutClear: "Kısayolu kaldır",
        shortcutInvalid: "Bir tuşla birlikte en az Control, Option veya Command kullan.",
        shortcutPressKeys: "Tuşlara bas",
        shortcutEscapeHint: "Esc iptal eder.",
        shortcutDeleteHint: "Delete kaldırır.",
        shortcutNotCaptured: "Hiçbir şey yakalanmadı. Bu kombinasyonu macOS ya da başka bir uygulama zaten kullanıyor. Başka bir tane dene.",
        shortcutConflictFormat: "Bu kısayol zaten %@ tarafından kullanılıyor.",
        shortcutUnavailable: "macOS bu kısayolu reddetti. Başka birini seç.",
        shelfShortcutToggle: "Raf kısayolu",
        switcherUsageHintFormat: "Gezinmek için %@ tuşunu basılı tut; pencereyi etkinleştirmek için bırak. Shift veya ← geri gider; W pencereyi kapatır; Q uygulamadan çıkar; Esc iptal eder.",
        musicBlockSection: "Medya tuşları",
        musicBlockTitle: "Müzik uygulamasının kendiliğinden açılmasını engelle",
        musicBlockCaption: "Medya tuşlarına basınca Müzik uygulaması artık açılmaz. Yine de kendin açabilirsin.",
        musicBlockReplacementLabel: "Yerine aç",
        musicBlockReplacementNone: "Hiçbiri",
        musicBlockChooseApp: "Uygulama seç…",
        cleanerName: "Temizlik",
        cleanerIntroTitle: "Mac içindeki gereksizleri temizle",
        cleanerIntroCaption: "Kaldırılmış uygulama kalıntılarını, önbellekleri, günlükleri ve Çöp Sepetini arar. Önce her şeyi gözden geçirirsin ve kaldırılanlar Çöp Sepetine gider.",
        cleanerScan: "Tara",
        cleanerScanning: "Taranıyor…",
        cleanerCleaning: "Temizleniyor…",
        cleanerCatLeftovers: "Kaldırılmış uygulama kalıntıları",
        cleanerCatLoginItems: "Sahipsiz başlangıç öğeleri",
        cleanerCatCaches: "Önbellekler",
        cleanerCatLogs: "Günlükler",
        cleanerCatDeveloper: "Geliştirici kalıntıları",
        cleanerCatTrash: "Çöp Sepeti",
        cleanerLeftoversNote: "Analizle bulundu ve işaretsiz bırakıldı. İşaretlemeden önce yolu kontrol et.",
        cleanerLoginItemsNote: "Giriş Öğelerindeki kayıt Mac yeniden başlatılınca kaybolur.",
        cleanerTrashNote: "Çöp Sepetini boşaltmak kalıcıdır.",
        cleanerCatDeviceBackups: "iPhone yedekleri",
        cleanerDeviceBackupsCaption: "Eski iPhone ve iPad yedekleri, macOS’un Diğer dediği alanın büyük kısmını kaplar. Yalnızca artık gerekmeyenleri silin; aygıt yeniden bağlanınca yeni yedek alınır.",
        cleanerNothingFound: "Temizlenecek bir şey yok. Mac düzenli.",
        cleanerClean: "Temizle",
        cleanerDoneNote: "Öğeler Çöp Sepetine taşındı ve oradan geri alınabilir.",
        cleanerAgain: "Yeniden tara",
        cleanerRevealInFinder: "Finder içinde göster",
        cleanerPanelCaption: "Uygulama kalıntıları, önbellekler ve günlükler",
        cleanerSafeSection: "Güvenli temizlik",
        cleanerOptionalSection: "İsteğe bağlı, önce gözden geçir",
        cleanerCatOtherCaches: "Diğer önbellekler",
        cleanerCachesCaption: "Uygulamaların kendiliğinden yeniden oluşturduğu geçici dosyalar.",
        cleanerLogsCaption: "Eski tanılama günlükleri.",
        cleanerDeveloperCaption: "Xcode derleme ve simülatör kalıntıları.",
        cleanerLoginItemsCaption: "Artık var olmayan uygulamalardan kalan başlangıç öğeleri.",
        cleanerLeftoversCaption: "Kaldırdığın uygulamalardan kalan dosyalar.",
        cleanerOtherCachesCaption: "Silmek güvenli, hiçbir şey bozulmaz. Uygulamalar bir kez daha yavaş açılabilir ve çevrimdışı müzik gibi indirilen içerikler yeniden indirilir.",
        cleanerCleanSizeFormat: "%@ temizle",
        cleanerScheduleTitle: "Otomatik temizlik",
        cleanerScheduleOff: "Kapalı",
        cleanerScheduleDaily: "Günlük",
        cleanerScheduleWeekly: "Haftalık",
        cleanerScheduleCaption: "Seçilen saatte yalnızca güvenli kısmı kendiliğinden temizler ve her şeyi Çöp Sepetine gönderir.",
        cleanerScheduleLastFormat: "Son otomatik temizlik %@ boşalttı.",
        cleanerAutoNotificationFormat: "%@ boşaltıldı ve Çöp Sepetine gönderildi.",
        cleanerScheduleNextFormat: "Sonraki temizlik %@.",
        cleanerScheduleRanFormat: "Son otomatik temizlik %@.",
        cleanerScheduleNotifyToggle: "Bitince bildir",
        cleanerNotifDenied: "Vorssaint bildirimleri sistemde kapalı.",
        cleanerNotifOpenSettings: "Bildirim ayarlarını aç…",
        launchAtLoginNeedsApplications: "Uygulama, oturum açılırken açılmaya izin vermeyen bir konumdan çalışıyor. Vorssaint’i Uygulamalar klasörüne sürükleyin, oradan açın ve bu seçeneği yeniden açın.",
        launchAtLoginNeedsApproval: "Giriş ögesi kayıtlı, ancak Sistem Ayarları’nda hâlâ kapalı. Sistem Ayarları › Genel › Giriş Ögeleri ve Uzantılar’ı açın ve “Oturum açılırken aç” altında Vorssaint’i açın.",
        ocrRemoveLineBreaksToggle: "Satır sonlarını kaldır",
        ocrRemoveLineBreaksCaption: "Satır sonlarını kaldırarak kopyalanan metnin tek paragraf olarak yapıştırılmasını sağlar.",
        ocrQRToggle: "QR kodlarını oku",
        ocrQRCaption: "Alanda bir QR kodu varsa içeriği kopyalamak veya açmak için gösterilir.",
        ocrQRCopied: "QR kodu kopyalandı",
        qrResultTitle: "QR kodu",
        qrResultCopy: "Kopyala",
        qrResultOpen: "Bağlantıyı aç",
        highlightsTitle: "Bu güncellemedeki yenilikler",
        highlightsTitleClipboardRedesign: "Yenilenen Pano",
        highlightsTitleWindowLayout: "Pencere Yerleşimi",
        highlightsTitleQuitProtection: "⌘Q ve ⌘W Koruması",
        highlightsTitleRecorderBlur: "Ekran Kaydında Gizlilik Bulanıklığı",
        highlightsCaptionDockPreview: "Dock Preview artık Dock büyütme açıkken de çalışıyor",
        highlightsCaptionScreenshot: "Ekran görüntüsü aracına piksel büyüteci ve QR kod okuma eklendi",
        highlightsCaptionSnippetLibrary: "Aranabilir parçacık menüsü istediğiniz parçacığı imlece yazar",
        highlightsCaptionCapturePalette: "Tek bir kısayol artık ekran görüntüleri, kayıtlar, ekrandaki metinler ve renkler için yakındaki ayarlarla yüzen bir palet açar.",
        highlightsCaptionClipboardRedesign: "Geçmiş artık sade satırlara ve öğenin tamamını okumak veya düzenlemek için isteğe bağlı önizlemeye sahip kompakt bir palet olarak açılır.",
        highlightsCaptionWindowLayout: "Kısayol ve işaretçiyle yön halkasını kullanarak pencereleri yerleştirin veya ekran kenarlarına sürükleyip özel boşluklarla hizalayın.",
        highlightsCaptionQuitProtection: "Tuşu basılı tutma, iki kez basma veya fazladan değiştirici tuş isteyerek uygulamaların ve pencerelerin yanlışlıkla kapanmasını önleyin.",
        highlightsCaptionRecorderBlur: "Dışa aktarmadan önce kaydedilen videonun istediğiniz bölümünde parolaları ve gizli ayrıntıları bulanıklaştırarak gizleyin.",
        highlightsConfigure: "Ayarla",
        highlightsTry: "Dene",
        highlightsSeeAll: "Tüm değişiklikleri gör",
        switcherCurrentSpaceOnly: "Yalnızca geçerli masaüstünü göster",
        switcherCurrentSpaceOnlyCaption: "Değiştiricide yalnızca bulunduğunuz masaüstündeki pencereler listelenir. Bir pencere seçmek sizi asla başka bir masaüstüne taşımaz.",
        shelfFileMissing: "Dosya artık yok",
        previewSizeSmall: "Küçük",
        mixerSoundEffectsOutputTitle: "Sistem sesleri",
        mixerSoundEffectsOutputTooltip: "Uyarıların ve ses efektlerinin çalacağı çıkışı seç",
        monitorOpenActivityMonitor: "Etkinlik Monitörü’nü aç",
        dockClickHide: "Dock simgesine tıklayınca uygulamayı gizle",
        dockClickHideCaption: "Etkin uygulamanın Dock simgesine tıklayınca uygulama gizlenir. Geri getirmek için yeniden tıklayın.",
        monitorMemoryMetricLabel: "Belleği şu şekilde ölç",
        memoryMetricUsed: "Kullanılan Bellek",
        memoryMetricApp: "Uygulama Belleği",
        keepAwakeRightClickToggle: "Uyanık tutmayı açıp kapatmak için menü çubuğu simgesine sağ tıkla",
        keepAwakeRightClickToggleCaption: "Sağ tık bağlam menüsünün yerini alır.",
        urlCleanerRulesTitle: "Temizleme kuralları",
        urlCleanerRulesCaption: "Bir site, bağlantının nereden geldiğini izlemek için bu parametreleri kendi paylaşım bağlantılarına ekler. İşaretliyken ad temizlik sırasında kaldırılır, işaret kaldırılınca kalır. Eklediğiniz adlar silinebilir.",
        urlCleanerRulesCoverageCaption: "Liste, bir sitenin farklı paylaşım yollarını (web sayfası, uygulama, canlı yayın) kapsadığı için uzundur; gerçek bir bağlantı genelde bunlardan yalnızca iki ila dördünü taşır.",
        urlCleanerRulesAllSites: "Tüm siteler",
        urlCleanerRulesCountSingular: "1 parametre",
        urlCleanerRulesCountPluralFormat: "%d parametre",
        urlCleanerRulesAddSite: "Site ekle",
        urlCleanerRulesParameterPlaceholder: "Parametre adı",
        urlCleanerRulesMatchCaption: "= işaretinin solundaki adı yazın, örneğin utm_source. Eşleşen bir ad bağlantıdan yalnızca o parametreyi çıkarır, gerisini olduğu gibi bırakır.",
        urlCleanerRulesAddButton: "Ekle",
        urlCleanerRulesRemoveButton: "Adı sil",
        urlCleanerRulesRemoveSiteButton: "Bu sitenin tüm kurallarını kapat",
        urlCleanerRemovedFormat: "Kaldırıldı: %@",
        switcherSearchPin: "S ile aramayı sabitle",
        switcherSearchPinCaption: "S, aramayı başlatır ve değiştiriciyi sabitler; kısayolun ⌥ kullanması durumunda özel karakter yazılmasını, Q veya W ile başlayan aramaların pencereyi kapatmasını veya uygulamadan çıkmasını önler.",
        invertVerticalScroll: "Dikey kaydırmayı ters çevir",
        invertHorizontalScroll: "Yatay kaydırmayı ters çevir",
        switcherShowShortcutHints: "Kısayol ipuçlarını göster",
        switcherShowShortcutHintsCaption: "Simge sırasının altında uygulama ve pencere kısayollarını gösterir.",
        uninstallerHomebrewPackageFormat: "%@, Homebrew’den de kaldırılacak.",
        shelfEdgeToggle: "Ekran kenarına yaklaşınca aç",
        shelfEdgeCaption: "Bir dosyayı ekran kenarına doğru sürüklediğinde raf belirmeye başlar. Bıraktığın yerde kalır, ya da geri çekersen raf da geri çekilir.",
        focusFollowsMouseName: "Odak fareyi takip etsin",
        focusFollowsMouseCaption: "Kısa bir beklemeden sonra işaretçinin altındaki pencereye odaklanır ve öne getirir.",
        focusFollowsMouseDelay: "Üzerinde bekleme gecikmesi",
        switcherMinimizedPlacementLabel: "Küçültülmüş pencereler",
        switcherMinimizedPlacementNormal: "Normal sıralama",
        switcherMinimizedPlacementEnd: "Sona yerleştir",
        switcherMinimizedPlacementHidden: "Gizle",
        switcherShowFullscreenWindows: "Tam ekran pencereleri göster",
        switcherScreenPlacementLabel: "Şurada göster",
        switcherScreenPlacementPointer: "İmlecin olduğu ekran",
        switcherScreenPlacementMenuBar: "Menü çubuğunun olduğu ekran",
        switcherScreenPlacementActiveWindow: "Etkin pencerenin olduğu ekran",
        switcherScreenPlacementCaption: "Birden fazla ekran bağlıyken değiştiricinin hangi ekranda açılacağını belirler.",
        smoothScrollResponseLabel: "Tepki",
        mouseAccelerationName: "Fare hızlandırmasını kapat",
        mouseAccelerationCaption: "Bağlı farelerde işaretçi hızlandırmasını kaldırır. Seçenek kapatıldığında veya Vorssaint’ten çıkıldığında önceki ayar geri yüklenir.",
        shelfClearOnClose: "Kapatınca temizle",
        shelfClearOnCloseCaption: "Rafı yalnızca kapatma düğmesine tıkladığında boşaltır. Otomatik gizleme ve daraltma öğeleri korur."
    )
}
