// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Deutsch — translated and hand-checked, not machine output.
extension Strings {
    static let de = Strings(
        statusIdleTooltip: "Vorssaint: normaler Ruhezustand",
        statusActiveUntil: "Vorssaint: aktiv bis",
        statusActiveIndefinite: "Vorssaint: dauerhaft aktiv",
        menuEnableAwake: "Wachhalten aktivieren",
        menuDisableAwake: "Wachhalten deaktivieren",
        menuActivateFor: "Aktivieren für…",
        menuSettings: "Einstellungen…",
        menuAbout: "Über Vorssaint",
        menuQuit: "Vorssaint beenden",
        menuHide: "Vorssaint ausblenden",
        menuHideOthers: "Andere ausblenden",
        menuShowAll: "Alle einblenden",
        menuEdit: "Bearbeiten",
        menuUndo: "Widerrufen",
        menuRedo: "Wiederholen",
        actionClear: "Löschen",
        actionRemove: "Entfernen",
        actionBack: "Zurück",
        actionSearch: "Suchen",
        actionMute: "Stummschalten",
        actionUnmute: "Wieder aktivieren",
        actionPlay: "Abspielen",
        actionPause: "Pausieren",
        menuCut: "Ausschneiden",
        menuCopy: "Kopieren",
        menuPaste: "Einsetzen",
        menuSelectAll: "Alles auswählen",
        menuWindow: "Fenster",
        menuMinimize: "Im Dock ablegen",
        menuZoom: "Zoomen",
        menuClose: "Schließen",

        minutes15: "15 Minuten",
        minutes30: "30 Minuten",
        hour1: "1 Stunde",
        hours2: "2 Stunden",
        hours4: "4 Stunden",
        hours8: "8 Stunden",
        indefinitely: "Dauerhaft",
        indefinite: "Unbegrenzt",

        panelSettings: "Einstellungen",
        panelQuit: "Beenden",
        panelHotkeyHint: "Kurzbefehl schaltet um",

        keepAwakeTitle: "Wachhalten",
        keepAwakeEndsIn: "Endet in",
        keepAwakeUntilDisabled: "Aktiv, bis du es ausschaltest",
        keepAwakeNormalRules: "Der Mac folgt seinen normalen Energieregeln",
        keepAwakeOptions: "Optionen",
        keepAwakeMouseJiggle: "Zeiger leicht bewegen",
        keepAwakeMouseJiggleCaption: "Bewegt den Zeiger während einer Sitzung im gewählten Intervall leicht.",
        keepAwakeMouseJiggleInterval: "Intervall",
        keepAwakeActiveIconLabel: "Aktives Symbol",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Kaffee",
        keepAwakeActiveIconEye: "Auge",
        keepAwakeActiveIconMoon: "Mond",
        keepAwakeActiveIconLight: "Glühbirne",
        keepAwakeIconTintLabel: "Farbe des aktiven Symbols",
        keepAwakeIconTintOrange: "Orange",
        keepAwakeIconTintGreen: "Grün",
        keepAwakeIconTintBlue: "Blau",
        keepAwakeIconTintPurple: "Lila",
        keepAwakeIconTintPink: "Pink",
        keepAwakeIconTintNone: "Keine Farbe",
        durationLabel: "Dauer",
        clamshellTitle: "Bei zugeklapptem Mac weiterlaufen",
        clamshellOnCaption: "Ruhezustand komplett deaktiviert. Auf den Akku achten",
        clamshellNeedsSession: "Gilt immer, wenn „Wachhalten“ aktiv ist",
        clamshellReady: "Bereit. Schaltet ohne Passwort um",
        clamshellNeedsPassword: "Fragt einmalig nach dem Administratorpasswort",

        systemSection: "System",
        temperatures: "Temperaturen",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batterie",
        usageSection: "Hardware-Auslastung",
        memorySection: "Speicher",
        memoryPressure: "Speicherdruck",
        memorySwapUsed: "Swap-Nutzung",
        memoryCompressed: "Komprimiert",
        memoryCachedFiles: "Dateien im Cache",
        pressureNormal: "Normal",
        pressureWarning: "Erhöht",
        pressureCritical: "Kritisch",
        monitorUnavailable: "Sensoren auf diesem Mac nicht verfügbar",
        energyAppsTitle: "Hoher Energieverbrauch",
        energyAppsIdle: "Kein hoher Energieverbrauch",

        notifySessionEndedTitle: "Sitzung beendet",
        notifySessionEndedBody: "Die Zeit ist abgelaufen. Der Mac wechselt wieder normal in den Ruhezustand.",
        notifyBatteryTitle: "Vorssaint deaktiviert",
        notifyBatteryBody: "Niedriger Batteriestand. Der normale Ruhezustand wurde wiederhergestellt, um die Ladung zu schonen.",
        adminPromptClamshellOn: "Vorssaint benötigt dein Passwort, um bei zugeklapptem Mac weiterzulaufen.",
        adminPromptClamshellOff: "Vorssaint benötigt dein Passwort, um den normalen Ruhezustand des Mac wiederherzustellen.",
        adminPromptRecover: "Vorssaint wurde beendet, während der Ruhezustand des Mac deaktiviert war. Gib das Passwort ein, um den normalen Ruhezustand wiederherzustellen.",
        adminPromptUpdate: "Vorssaint benötigt dein Passwort, um das Update zu installieren.",
        adminPromptSudoersInstall: "Vorssaint legt eine eingeschränkte Regel an (nur pmset disablesleep), um den Modus bei geschlossenem Display ohne Passwortabfrage umzuschalten. Nur dieses eine Mal wird das Passwort benötigt.",
        adminPromptSudoersRemove: "Vorssaint entfernt die passwortfreie Regel für das geschlossene Display.",

        settingsTitle: "Vorssaint-Einstellungen",
        tabGeneral: "Allgemein",
        tabEnergy: "Energie",
        tabMouse: "Maus & Trackpad",
        tabSwitcher: "Umschalter",
        tabAdvanced: "Erweitert",
        tabAbout: "Über",
        tabReleaseNotes: "Neues",
        releaseNotesOnUpdateToggle: "Neuigkeiten nach Update anzeigen",
        minimalWindowPreviews: "Schlichte Vorschauen",
        minimalWindowPreviewsCaption: "Blendet Titel, Tasten und Verzierungen in den Vorschauen von Dock und App-Umschalter aus. Die Auswahl bleibt sichtbar.",
        previewSizeLabel: "Vorschaugröße",
        previewSizeNormal: "Normal",
        previewSizeLarge: "Groß",
        previewSizeXLarge: "Sehr groß",
        settingsGroupFeatures: "Funktionen",
        advancedResetSection: "Berechtigungen",
        advancedResetDescription: "Entfernt alle Berechtigungen, die du Vorssaint erteilt hast (Bedienungshilfen, Bildschirmaufnahme, Festplattenvollzugriff und weitere), das Anmeldeobjekt und die Regel für das geschlossene Display. Praktisch für einen Neustart oder vor dem Deinstallieren. Die App bleibt installiert.",
        advancedClearButton: "Alle Berechtigungen zurücksetzen",
        advancedCleared: "Berechtigungen zurückgesetzt.",
        advancedClearConfirmTitle: "Alle Berechtigungen zurücksetzen?",
        advancedClearConfirmBody: "Funktionen, die Berechtigungen benötigen, arbeiten erst wieder, wenn du sie erneut erteilst. Deine Einstellungen bleiben erhalten.",
        advancedUninstallSection: "Deinstallieren",
        advancedUninstallDescription: "Macht alles oben Genannte, entfernt dann die Einstellungen und bewegt Vorssaint in den Papierkorb, ohne Rückstände zu hinterlassen. Die App beendet sich danach. Du kannst sie jederzeit neu installieren.",
        advancedUninstallButton: "Vorssaint vollständig deinstallieren",
        advancedUninstallConfirmTitle: "Vorssaint deinstallieren?",
        advancedUninstallConfirmBody: "Vorssaint setzt seine Berechtigungen zurück, entfernt seine Einstellungen und wandert in den Papierkorb, dann beendet es sich. Das lässt sich aus der App nicht rückgängig machen, doch sie bleibt im Papierkorb, bis du ihn leerst.",
        advancedUninstallFailedTitle: "Deinstallation gestoppt",
        advancedUninstallFailedBody: "Vorssaint konnte eine geänderte Systemeinstellung nicht wiederherstellen: Ruhezustand, Lüfterdrehzahl oder Mausbeschleunigung. Es wurde nichts entfernt. Versuche es erneut und erlaube die Kennwortabfrage, falls sie erscheint.",

        launchAtLogin: "Beim Anmelden öffnen",
        languageLabel: "Sprache",
        menuBarSection: "Menüleiste",
        showCountdown: "Verbleibende Zeit neben dem Symbol anzeigen",
        globalHotkeySection: "Globaler Kurzbefehl",
        hotkeyToggle: "Kurzbefehl für „Wachhalten“ aktivieren",
        hotkeyCaption: "Funktioniert in jeder App, ohne zusätzliche Berechtigungen.",

        sessionSection: "Sitzung",
        defaultDurationLabel: "Standarddauer",
        keepAwakeAutoStart: "Beim Öffnen von Vorssaint wach halten",
        keepAwakeAutoStartCaption: "Startet eine Sitzung mit der Standarddauer.",
        batteryProtectionSection: "Batterieschutz",
        batteryDisableBelow: "Deaktivieren bei Batterie unter",
        batteryNever: "Nie",
        batteryProtectionCaption: "Verhindert, dass eine vergessene Sitzung die Batterie des MacBook entlädt.",
        clamshellSection: "Zugeklappt",
        configuring: "Wird konfiguriert…",
        sudoersFailed: "Modus bei geschlossenem Display konnte nicht aktiviert werden. Erneut versuchen.",
        clamshellExplanation: "„Bei zugeklapptem Mac weiterlaufen“ deaktiviert den Ruhezustand vollständig, solange „Wachhalten“ aktiv ist, und wird automatisch zurückgesetzt, sobald die Sitzung endet oder die App beendet wird. Nutze es am besten am Netzteil.",

        scrollSection: "Scrollen",
        invertMouseScroll: "Mausscrollen umkehren",
        invertMouseScrollCaption: "Kehrt die Richtung des Mausrads um.",
        scrollTrackpadNote: "Das Trackpad bleibt unverändert: Es behält das natürliche Scrollen von macOS bei.",
        scrollActiveNow: "Mausscrollen wird gerade umgekehrt",
        mouseNavigationActiveNow: "Seitentasten gerade aktiv",
        smoothScrollName: "Sanftes Scrollen",
        smoothScrollCaption: "Verwandelt jeden Rastschritt des Mausrads in ein kurzes, sanftes Gleiten. Das Trackpad bleibt unverändert.",
        smoothScrollStepLabel: "Scrollgeschwindigkeit",
        mouseNavigationSection: "Navigation",
        mouseNavigationEnable: "Seitentasten für Zurück und Vor verwenden",
        mouseNavigationCaption: "Wandelt die Maus-Tasten Zurück und Vor in Navigationsbefehle für Finder, Browser und kompatible Apps um.",
        middleClickSection: "Mittelklick",
        middleClickEnable: "Drei-Finger-Klick als Mittelklick",
        middleClickEnableCaption: "Das Trackpad mit drei Fingern zu drücken wirkt wie ein Klick aufs Mausrad: Links im neuen Tab öffnen, Tabs schließen und alles andere, was die mittlere Taste kann.",
        middleClickDragConflict: "Das Ziehen mit drei Fingern von macOS ist aktiviert und nutzt dieselbe Geste. Schalte es in den Systemeinstellungen unter Bedienungshilfen, Zeigersteuerung, Trackpad-Optionen aus, damit der Mittelklick funktioniert.",
        middleClickTapPicker: "Leichtes Tippen klickt ebenfalls",
        middleClickTapOff: "Aus",
        middleClickTapThreeFingers: "3 Finger",
        middleClickTapFourFingers: "4 Finger",
        middleClickTapCaption: "Ein leichtes Tippen mit dieser Fingerzahl, ohne zu drücken, löst ebenfalls den Mittelklick aus. Wischen zählt nie. Ist das Dreifinger-Tippen von macOS mit Nachschlagen belegt, schalte es aus, damit nicht beides zugleich auslöst.",
        quickToolsTab: "Schnellpanel",
        quickToolShortcutToggle: "Globaler Kurzbefehl",
        ocrName: "Text vom Bildschirm kopieren",
        ocrCaption: "Wähle einen Bildschirmbereich aus und der erkannte Text wird kopiert, bereit zum Einsetzen.",
        ocrCopied: "Text kopiert",
        ocrNoText: "Kein Text gefunden",
        colorPickerName: "Farbpipette",
        colorPickerCaption: "Greife die Farbe jedes Pixels auf dem Bildschirm ab und kopiere sie im gewünschten Format.",
        colorPickerFormatLabel: "Kopiertes Format",
        colorPickerBareHexToggle: "Ohne das Präfix # kopieren",
        colorPickerPickNow: "Farbe aufnehmen",
        micMuteName: "Mikrofon stummschalten",
        micUnmuteName: "Mikrofon wieder aktivieren",
        micMuteCaption: "Schaltet das Mikrofon des Mac per Klick oder Kurzbefehl stumm, in jeder App.",
        micMutedHUD: "Mikrofon stumm",
        micUnmutedHUD: "Mikrofon wieder an",
        micMuteMenuBarToggle: "In der Menüleiste anzeigen, solange stumm",
        micMuteMenuBarCaption: "Ein rot durchgestrichenes Mikrofon erscheint neben dem Symbol der App in der Menüleiste.",
        pastePlainName: "Als reinen Text einsetzen",
        pastePlainCaption: "Setzt Kopiertes ohne Farben, Schriften oder Formatierung ein. Das Original bleibt in der Zwischenablage.",
        launcherName: "Schnellpanel",
        launcherCaption: "Ein schwebendes Panel mit deinen Lieblingswerkzeugen, per Kurzbefehl von überall aufrufbar.",
        launcherOpenNow: "Schnellpanel öffnen",
        launcherEditHint: "Über die Einstellen-Taste lassen sich Werkzeuge wählen, ausblenden und ziehen.",
        launcherEmptyState: "Alle Werkzeuge sind ausgeblendet. Über die Einstellen-Taste kommen sie zurück.",
        launcherAddSection: "Wieder hinzufügen",
        launcherKeysHint: "Pfeile navigieren, Enter öffnet, 1 bis 9 öffnen direkt",
        switcherSection: "App-Umschalter",
        switcherEnable: "Vorssaint-Umschalter verwenden",
        switcherEnableCaption: "Wechselt zwischen Apps und Fenstern, einschließlich minimierter und mehrerer Fenster derselben App.",
        switcherUsageHint: "Halte den Kurzbefehl zum Navigieren; loslassen, um das Fenster zu aktivieren. Umschalt oder ← geht zurück; W schließt das Fenster; Q beendet die App; Esc bricht ab.",
        switcherNoWindows: "Keine geöffneten Fenster",
        switcherIconRowMode: "%@ mit großen Symbolen anzeigen",
        switcherIconRowModeCaption: "Zeigt ein Symbol pro App und darüber die Fenstervorschauen dieser App.",
        switcherSimpleMode: "Einfacher App-Umschalter",
        switcherSimpleModeCaption: "Zeigt App-Symbole und Fenstertitel, ohne Vorschauen oder Bildschirmaufnahme durch den Umschalter.",
        switcherShortcutHintApps: "Apps",
        switcherShortcutHintWindows: "Fenster",
        switcherWindowShortcutCaption: "Öffnet einen Umschalter für die Fenster der vordersten App. Bei geöffnetem App-Umschalter springt er zwischen den Fenstern der ausgewählten App.",
        switcherTakeOverSystemShortcuts: "macOS-⌘Tab und ⌘` ersetzen",
        switcherTakeOverSystemShortcutsCaption: "Deaktiviert die passenden macOS-App- und Fensterkurzbefehle nur, solange Vorssaints Umschalter aktiv ist. Alle laufenden Apps bleiben erreichbar.",
        switcherAppearanceDelay: "Einblendverzögerung",
        switcherAppearanceDelayCaption: "Wie lange das Tastenkürzel gehalten werden muss, bevor der Umschalter erscheint.",
        switcherMergeTabs: "Einen Eintrag pro App anzeigen",
        switcherMergeTabsCaption: "Fasst alle Fenster einer App zu einem Eintrag im Umschalter zusammen, statt einen Eintrag pro Fenster.",
        switcherWindowlessApps: "Apps ohne geöffnetes Fenster",
        switcherWindowlessAppsCaption: "Legt fest, welche laufenden Apps ganz ohne Fenster im Umschalter erscheinen.",
        switcherWindowlessAppsOff: "Nicht anzeigen",
        switcherWindowlessAppsFinder: "Nur Finder",
        switcherWindowlessAppsAll: "Alle Apps",
        switcherNoOpenWindow: "Kein geöffnetes Fenster",
        switcherOtherDesktop: "Anderer Schreibtisch",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Fenster im Dock vorab anzeigen",
        dockPreviewEnableCaption: "Zeige auf eine geöffnete App im Dock, um ihre Fenster zu sehen, und klicke dann auf das gewünschte.",
        dockPreviewBackgroundOpacity: "Hintergrund des Panels",
        dockPreviewBackgroundOpacityCaption: "Verringere ihn, um mehr von dem zu sehen, was hinter dem Panel liegt.",
        dockPreviewOpenDelay: "Öffnungsverzögerung",
        dockPreviewOpenDelayCaption: "Wie lange der Zeiger auf einem Symbol ruhen muss, bevor sich das Panel öffnet.",
        dockPreviewQuitAppOnClose: "App mit der ×-Taste beenden",
        dockPreviewQuitAppOnCloseCaption: "In Dock Preview beendet × die gesamte App, statt nur dieses Fenster zu schließen.",
        dockClickMinimize: "Klick aufs Dock-Symbol minimiert",
        dockClickMinimizeCaption: "Die Fenster der aktiven App werden beim Klick auf ihr Dock-Symbol im Dock abgelegt. Ein weiterer Klick holt sie zurück.",
        dockClickCycleWindows: "Klick aufs Dock-Symbol wechselt Fenster",
        dockClickCycleWindowsCaption: "Ein Klick auf das Dock-Symbol der aktiven App wechselt zwischen ihren Fenstern, wie ⌘`.",
        dockPreviewActiveNow: "Im Dock aktiv",
        dockPreviewDockUnavailable: "Dock-Elemente konnten nicht gelesen werden.",
        dockPreviewAutohideBeta: "Beta. Es können noch Fehler auftreten.",
        dockPreviewOpenWindow: "Fenster öffnen",
        dockPreviewCloseWindow: "Fenster schließen",
        dockPreviewMinimizeWindow: "Fenster minimieren",
        dockPreviewRestoreWindow: "Fenster wiederherstellen",
        dockPreviewPinPanel: "Vorschau anheften",
        dockPreviewUnpinPanel: "Vorschau lösen",
        dockPreviewPinned: "Angeheftet",
        dockPreviewClosePanel: "Vorschau schließen",
        dockPreviewPreviousWindow: "Vorheriges Fenster",
        dockPreviewNextWindow: "Nächstes Fenster",

        cutPasteName: "Ausschneiden & Einsetzen",
        cutPasteEnable: "Dateien im Finder ausschneiden & einsetzen",
        cutPasteEnableCaption: "Verwende ⌘X zum Ausschneiden und ⌘V, um Dateien und Ordner im Finder zu bewegen.",
        cutPasteShowHUD: "Schwebendes Fenster anzeigen",
        cutPasteShowHUDCaption: "Zeigt eine schwebende Anzeige mit den ausgeschnittenen Dateien, während der Finder aktiv ist.",
        cutPasteHowTitle: "So geht’s",
        cutPasteStep1: "Wähle Objekte im Finder aus und drücke ⌘X, um sie auszuschneiden.",
        cutPasteStep2: "Öffne den Zielordner und drücke ⌘V, um sie dorthin zu bewegen.",
        cutPasteTextNote: "In Textfeldern (etwa beim Umbenennen) funktionieren ⌘X und ⌘V weiterhin wie gewohnt.",
        cutPasteActiveNow: "Bereit zum Ausschneiden im Finder",
        cutPasteAutomationNote: "Beim ersten Mal fragt macOS um Erlaubnis, den Finder zu steuern.",
        cutReadyTitle: "Ausgeschnitten",
        cutReadyHint: "im Zielordner zum Bewegen",
        cutCancel: "Ausschneiden abbrechen",
        cutDoneTitle: "Bewegt!",
        cutMovedSingular: "1 Objekt bewegt",
        cutMovedPluralFormat: "%d Objekte bewegt",
        cutSomeFailed: "Einige Objekte konnten nicht bewegt werden",
        cutMovingTitle: "Wird bewegt…",
        cutMovingCountFormat: "%d von %d",

        autoQuitName: "Beim Schließen beenden",
        autoQuitEnable: "App beenden, wenn ihr letztes Fenster schließt",
        autoQuitEnableCaption: "Das Schließen des letzten Fensters einer App beendet sie auch.",
        autoQuitActiveNow: "Jetzt aktiv",
        autoQuitHowTitle: "So funktioniert’s",
        autoQuitStep1: "Schließe das letzte Fenster einer App (⌘W oder der rote Knopf).",
        autoQuitStep2: "Die App beendet sich von selbst. „Sichern?“-Dialoge erscheinen weiterhin.",
        autoQuitPredictableNote: "Apps, die normalerweise ohne Fenster laufen, werden nie beendet.",
        autoQuitExceptionsTitle: "Ausnahmen",
        autoQuitExceptionsCaption: "Apps in dieser Liste bleiben auch ohne Fenster geöffnet.",
        autoQuitExceptionsEmpty: "Keine Ausnahmen",
        autoQuitAddApp: "App hinzufügen…",

        uninstallerName: "Deinstallationsprogramm",
        uninstallerEnableCaption: "Entfernt eine App samt der Caches, Einstellungen, Protokolle und Rückstände, die sie hinterlässt.",
        uninstallerStep1: "Ziehe eine App in die Einstellungen oder wähle eine aus der Liste.",
        uninstallerStep2: "Prüfe die gefundenen Dateien und wie viel Platz sie belegen.",
        uninstallerStep3: "Bewege in den Papierkorb, was du möchtest. Nichts wird endgültig gelöscht.",
        uninstallerMenuItem: "Eine App deinstallieren…",
        uninstallerDropTitle: "Ziehe eine App hierher",
        uninstallerDropSubtitle: "oder wähle eine zur Analyse",
        uninstallerChoose: "App auswählen…",
        uninstallerPickerTitle: "App auswählen",
        uninstallerPickerSearch: "Apps suchen",
        uninstallerPickerEmpty: "Keine Apps gefunden",
        uninstallerEmptyNote: "Ohne deine Bestätigung wird nichts entfernt.",
        uninstallerFDANote: "Erteile Festplattenvollzugriff für eine gründlichere Analyse.",
        uninstallerFDAGrant: "Zugriff erteilen…",
        uninstallerFDAHint: "Aktiviere Vorssaint in der Liste. Fehlt es dort, klicke auf + und wähle Vorssaint unter „Programme“. Der Zugriff gilt erst, nachdem du die App erneut öffnest.",
        uninstallerFDARelaunch: "Jetzt neu öffnen",
        uninstallerScanning: "Dateien werden analysiert…",
        uninstallerRemoving: "Wird in den Papierkorb bewegt…",
        uninstallerFoundTitle: "gefunden",
        uninstallerSelectedFormat: "%d von %d ausgewählt",
        uninstallerRemove: "In den Papierkorb legen",
        uninstallerCancel: "Abbrechen",
        uninstallerDoneTitle: "Fertig!",
        uninstallerFreedFormat: "%@ freigegeben",
        uninstallerSomeFailed: "Einige Objekte konnten nicht in den Papierkorb bewegt werden.",
        uninstallerFailedNeedsFDA: "Daten von Apps in der Sandbox lassen sich nur mit Festplattenvollzugriff bewegen. Das Administratorpasswort ersetzt diese Berechtigung nicht.",
        uninstallerFailedMoreFormat: "und %d weitere",
        uninstallerAnother: "Weitere deinstallieren",
        uninstallerCatApp: "Programm",
        uninstallerCatSupport: "Unterstützung",
        uninstallerCatCaches: "Caches",
        uninstallerCatPreferences: "Einstellungen",
        uninstallerCatContainers: "Container",
        uninstallerCatLogs: "Protokolle",
        uninstallerCatState: "Gesicherter Zustand",
        uninstallerCatOther: "Sonstiges",

        urlCleanerName: "URL bereinigen",
        urlCleanerEnable: "URLs beim Kopieren bereinigen",
        urlCleanerEnableCaption: "Entfernt Tracking-Parameter aus einem Link, sobald er in der Zwischenablage landet.",
        urlCleanerActiveNow: "Jetzt aktiv",
        urlCleanerManualTitle: "Jetzt bereinigen",
        urlCleanerInputPlaceholder: "URL einfügen",
        urlCleanerOutputPlaceholder: "Die bereinigte URL erscheint hier",
        urlCleanerCleanButton: "Bereinigen",
        urlCleanerPasteButton: "Einfügen",
        urlCleanerCopyButton: "Kopieren",
        urlCleanerClearButton: "Feld leeren",
        urlCleanerNoURL: "Füge eine gültige URL ein.",
        urlCleanerNoChange: "Nichts zu bereinigen.",
        urlCleanerCleaned: "URL bereinigt.",
        urlCleanerCopied: "Kopiert.",
        urlCleanerLocalNote: "Lokal. Kein Netzwerk.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Suche, installiere und entferne Formeln und Casks.",
        homebrewMissingTitle: "Homebrew nicht gefunden",
        homebrewMissingBody: "Vorssaint kann Terminal mit dem offiziellen Homebrew-Installer öffnen. Terminal zeigt die Schritte und fragt bei Bedarf nach deinem Passwort.",
        homebrewInstallHomebrew: "Homebrew installieren",
        homebrewInstallHomebrewCaption: "Wenn Terminal fertig ist, komm zurück und klicke auf Aktualisieren.",
        homebrewInstallHomebrewOpened: "Installer in Terminal geöffnet.",
        homebrewShellSetupTitle: "Terminal-Konfiguration abschließen",
        homebrewShellSetupBody: "Homebrew ist installiert, aber Terminal findet den Befehl brew vielleicht noch nicht. Vorssaint kann Terminal mit dem Konfigurationsbefehl öffnen.",
        homebrewShellSetupButton: "Terminal konfigurieren",
        homebrewShellSetupOpened: "Befehl in Terminal geöffnet. Komm danach zurück und klicke auf Aktualisieren.",
        homebrewRefresh: "Aktualisieren",
        homebrewCheckPackages: "Pakete prüfen",
        homebrewTrustTitle: "Tap noch nicht vertraut",
        homebrewTrustCaption: "Homebrew fragt jetzt nach deiner Bestätigung, bevor es Taps von Dritten verwendet. Vertraue %@, um fortzufahren.",
        homebrewTrustButton: "Vertrauen und fortfahren",
        homebrewSearchPlaceholder: "Pakete suchen",
        homebrewKeyboardHint: "Leertaste oder Eingabe schließt das macOS-Panel. Nutze die Suchtaste.",
        homebrewSearchButton: "Suchen",
        homebrewSearchResults: "Ergebnisse",
        homebrewInstalled: "Installiert",
        homebrewAll: "Alle",
        homebrewFormulas: "Formeln",
        homebrewCasks: "Casks",
        homebrewNoPackages: "Keine Pakete gefunden",
        homebrewNoSelection: "Wähle ein installiertes Paket oder suche ein neues.",
        homebrewDetailsTitle: "Paketdetails",
        homebrewInstall: "Installieren",
        homebrewUninstall: "Deinstallieren",
        homebrewUpgrade: "Aktualisieren",
        homebrewUpgradeAll: "Alle aktualisieren",
        homebrewUpdateHomebrew: "Homebrew aktualisieren",
        homebrewAllPackages: "Pakete",
        homebrewOpenTerminal: "Terminal öffnen",
        homebrewCancelOperation: "Abbrechen",
        homebrewClearLog: "Protokoll leeren",
        homebrewLogTitle: "Protokoll",
        homebrewVersion: "Version",
        homebrewDescription: "Typ",
        homebrewHomepage: "Website öffnen",
        homebrewPopularity: "Beliebtheit",
        homebrewPopularityFormat: "%@ Installationen in %@ Tagen",
        homebrewInstalledBadge: "Installiert",
        homebrewNotInstalledBadge: "Nicht installiert",
        homebrewUpdates: "Updates",
        homebrewUpdateAvailableBadge: "Update verfügbar",
        homebrewLatestVersion: "Neueste",
        homebrewConfirmInstallTitle: "Mit Homebrew installieren?",
        homebrewConfirmInstallBodyFormat: "Homebrew lädt %@ herunter und installiert es. Abhängigkeiten können ebenfalls installiert werden.",
        homebrewConfirmUninstallTitle: "Mit Homebrew deinstallieren?",
        homebrewConfirmUninstallBodyFormat: "Homebrew deinstalliert %@. Konfigurationsdateien können im System bleiben.",
        homebrewConfirmUpgradeTitle: "Mit Homebrew aktualisieren?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew lädt die neueste Version von %@ herunter und wendet sie an. Abhängigkeiten können ebenfalls aktualisiert werden.",
        homebrewConfirmUpgradeAllTitle: "Alle mit Homebrew aktualisieren?",
        homebrewConfirmUpgradeAllBody: "Homebrew lädt die neuesten Versionen der Pakete mit verfügbaren Updates herunter und wendet sie an. Abhängigkeiten können ebenfalls aktualisiert werden.",
        homebrewConfirmUpdateHomebrewTitle: "Homebrew aktualisieren?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew ruft die neuesten Informationen ab und lädt danach deine Pakete neu.",
        homebrewTerminalFallback: "Diese Aktion benötigt Terminal, um nach dem Administratorpasswort zu fragen. Vorssaint erfasst keine Passwörter.",
        homebrewLoading: "Laden…",
        homebrewSearchEmpty: "Keine Ergebnisse",
        homebrewOperationInstallFormat: "%@ wird installiert",
        homebrewOperationUninstallFormat: "%@ wird deinstalliert",
        homebrewOperationUpgradeFormat: "%@ wird aktualisiert",
        homebrewOperationUpgradeAll: "Pakete werden aktualisiert",
        homebrewOperationUpdateHomebrew: "Homebrew wird aktualisiert",
        homebrewOperationInstalledFormat: "%@ installiert.",
        homebrewOperationUninstalledFormat: "%@ deinstalliert.",
        homebrewOperationUpgradedFormat: "%@ aktualisiert.",
        homebrewOperationUpgradedAll: "Pakete aktualisiert.",
        homebrewOperationUpdatedHomebrew: "Homebrew aktualisiert.",
        homebrewOperationFailedFormat: "%@ konnte nicht abgeschlossen werden.",
        homebrewOperationCancelled: "Aktion abgebrochen.",
        homebrewOperationPreparing: "Vorbereiten…",
        homebrewOperationDownloading: "Dateien werden geladen…",
        homebrewOperationInstalling: "Dateien werden installiert…",
        homebrewOperationUninstalling: "Dateien werden entfernt…",
        homebrewOperationUpgrading: "Dateien werden aktualisiert…",
        homebrewOperationFinalizing: "Abschließen…",
        homebrewOperationRefreshing: "Liste wird aktualisiert…",
        homebrewOperationTerminal: "Im Terminal fortfahren.",
        homebrewOperationElapsedFormat: "%@ vergangen",
        homebrewOperationShowDetails: "Details anzeigen",
        homebrewOperationHideDetails: "Details ausblenden",
        homebrewOperationTechnicalLog: "Technische Details",
        homebrewOperationProgressUnknown: "Homebrew hat noch keinen Prozentsatz gemeldet.",

        mediaName: "Medien",
        mediaEnableCaption: "Komprimiere Videos, konvertiere und bearbeite Bilder, erstelle GIFs und extrahiere Text lokal.",
        mediaLocalNote: "Lokal. Kein Netzwerk.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Bild",
        mediaToolText: "Text",
        mediaSelectFile: "Datei wählen",
        mediaDropHint: "Ziehe eine Datei hierher oder klicke zum Auswählen.",
        mediaOutput: "Ausgabe",
        mediaOutputAutomatic: "Automatisch",
        mediaChooseOutput: "Ziel",
        mediaStartVideo: "Video komprimieren",
        mediaStartGIF: "GIF erstellen",
        mediaStartImage: "Bild bearbeiten",
        mediaStartConvertPDF: "In PDF umwandeln",
        mediaStartText: "Text extrahieren",
        mediaCancel: "Abbrechen",
        mediaStartTime: "Start",
        mediaEndTime: "Ende",
        mediaQuality: "Komprimierung",
        mediaCompressionLow: "Niedrig",
        mediaCompressionMedium: "Mittel",
        mediaCompressionHigh: "Hoch",
        mediaMaxSize: "Größe",
        mediaSizingResolution: "Auflösung",
        mediaSizingFileSize: "Dateigröße",
        mediaTargetSize: "Zielgröße",
        mediaTargetSizeHint: "Die Auflösung passt sich an, um unter der Grenze zu bleiben.",
        mediaErrorTargetTooSmall: "Zielgröße zu klein für diesen Clip. Kürzen Sie ihn oder erhöhen Sie die Grenze.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Breite",
        mediaFPS: "FPS",
        mediaKeepAudio: "Audio behalten",
        mediaCodec: "Codec",
        mediaFormat: "Format",
        mediaStripMetadata: "Metadaten entfernen",
        mediaLoopGIF: "GIF wiederholen",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Genau",
        mediaOCRFast: "Schnell",
        mediaLanguageCorrection: "Sprachkorrektur",
        mediaTextOutputNote: "Extrahierter Text kann kopiert und als TXT gespeichert werden.",
        mediaRunning: "Verarbeitung",
        mediaCompleted: "Fertig",
        mediaCancelled: "Abgebrochen.",
        mediaOpenInFinder: "Anzeigen",
        mediaCopyText: "Text kopieren",
        mediaRunAgain: "Erneut ausführen",
        mediaEmptyText: "Kein Text gefunden.",
        mediaResultSavedFormat: "Gespeichert als %@",
        mediaResultSizeFormat: "%@ zu %@",
        mediaResultGrewCaption: "Die umgewandelte Datei ist größer als das Original.",
        mediaErrorNoFile: "Wähle zuerst eine Datei.",
        mediaErrorNoVideo: "Diese Datei hat keine Videospur.",
        mediaErrorSameOutput: "Wähle ein Ziel, das nicht die Originaldatei ist.",
        mediaErrorUnsupported: "Format wird von macOS nicht unterstützt.",

        shelfName: "Ablage",
        shelfEnable: "Temporäre Ablage zum Ziehen von Dateien",
        shelfEnableCaption: "Ein schwebender Ort, um Dateien, Bilder und Text zu sammeln und später überallhin zu ziehen.",
        shelfHowTitle: "So geht’s",
        shelfStep1: "Öffne sie mit dem Kurzbefehl oder indem du die Maus während des Ziehens schüttelst.",
        shelfStep2: "Lege Dateien, Bilder, Links oder Text darauf ab, um sie zu verwahren.",
        shelfStep3: "Ziehe jedes Objekt wieder in eine beliebige App, wenn du es brauchst.",
        shelfShakeToggle: "Durch Schütteln der Maus beim Ziehen öffnen",
        shelfShakeCaption: "Schüttle den Zeiger schnell, während du ein Objekt hältst, um die Ablage beim Cursor erscheinen zu lassen.",
        shelfDropZoneToggle: "Gezogene Dateien in der Menüleiste behalten",
        shelfDropZoneCaption: "Während du eine Datei ziehst, erscheint die Ablage unter dem Menüleistensymbol. Was du ablegst, bleibt gleich dort, in einer Taste, die du mit einem Klick ein- und ausklappst und die verschwindet, sobald die Ablage leer ist.",
        shelfDropZoneLabel: "Hier loslassen",
        shelfCollapse: "Einklappen",
        shelfBehaviorTitle: "Nach der Verwendung",
        shelfCloseAfterDrop: "Nach dem Ablegen in einer anderen App schließen",
        shelfCloseAfterDropCaption: "Schließt die Ablage, sobald das Ziel die Objekte annimmt. Die Stecknadel im Panel hält sie offen.",
        shelfRemoveAfterDrop: "Objekte nach dem Ablegen entfernen",
        shelfRemoveAfterDropCaption: "Von einer anderen App angenommene Objekte verlassen die Ablage. Ausschalten, um eine Kopie zu behalten.",
        shelfExclusionsTitle: "Automatische Ausnahmen",
        shelfExclusionsEmpty: "Keine Apps hinzugefügt.",
        shelfExclusionsCaption: "Schütteln und die Menüleisten-Ablage bleiben bei Ziehvorgängen aus diesen Apps aus. Kurzbefehl und Jetzt öffnen funktionieren weiter.",
        shelfPin: "Offen halten",
        shelfUnpin: "Schließen nach Verwendung erlauben",
        extraBrightnessName: "Extra Helligkeit",
        extraBrightnessCaption: "Nutzt die HDR-Reserve des Displays, um über die maximale Helligkeit hinauszugehen. Verbraucht mehr Akku und der Mac kann warm werden.",
        extraBrightnessLevelLabel: "Intensität",
        extraBrightnessUnsupported: "Nur auf XDR-Displays verfügbar, etwa beim 14 und 16 Zoll MacBook Pro.",
        shelfHotkeyLabel: "Kurzbefehl",
        shelfOpenNow: "Jetzt öffnen",
        shelfNoPermission: "Benötigt keine Berechtigungen.",
        shelfMenuItem: "Ablage öffnen",
        shelfTitle: "Ablage",
        shelfEmpty: "Ziehe Objekte hierher",
        shelfClearAll: "Alle entfernen",
        shelfRemoveSelected: "Ausgewählte entfernen",
        shelfSelectedFormat: "%d ausgewählt",
        shelfHint: "Klicken zum Auswählen. Zum Verwenden ziehen oder für weitere Aktionen rechtsklicken.",
        shelfItemImage: "Bild",
        shelfTooltipItemsFormat: "%d Elemente",
        shelfTooltipItemsFew: "%d Elemente",
        shelfTooltipImageSingular: "%d Bild",
        shelfTooltipImageFew: "%d Bilder",
        shelfTooltipImagePlural: "%d Bilder",
        shelfTooltipFileSingular: "%d Datei",
        shelfTooltipFileFew: "%d Dateien",
        shelfTooltipFilePlural: "%d Dateien",
        shelfTooltipNoteSingular: "%d Notiz",
        shelfTooltipNoteFew: "%d Notizen",
        shelfTooltipNotePlural: "%d Notizen",
        shelfTooltipLinkSingular: "%d Link",
        shelfTooltipLinkFew: "%d Links",
        shelfTooltipLinkPlural: "%d Links",
        shelfActionOpen: "Öffnen",
        shelfActionOpenWith: "Öffnen mit",
        shelfActionShare: "Teilen",

        breakdownMeasuring: "Wird gemessen…",

        mixerSection: "Lautstärkemixer",
        mixerEmpty: "Apps, die Audio nutzen, erscheinen hier",
        mixerUnavailable: "Verfügbar ab macOS 14.4",
        mixerPermissionBody: "Um die Lautstärke je App anzupassen, erlaube „Aufnahme von Bildschirm und Systemaudio“ in den Systemeinstellungen. Audio wird nie aufgenommen.",
        mixerResetTooltip: "Auf 100 % zurücksetzen",
        mixerOutputDefault: "Standard",
        mixerOutputCurrent: "aktuell",
        mixerOutputUnavailable: "Ausgabe nicht verfügbar",
        mixerOutputFallback: "Standard wird verwendet, bis dieses Gerät zurück ist.",
        mixerBypassedCaption: "Diese App verwaltet ihr Audio selbst.",
        mixerOutputTooltip: "Ausgabe wählen",
        mixerSystemOutputTitle: "Ausgabe",
        mixerSystemOutputNoDevices: "Keine Ausgabe gefunden",
        mixerSystemOutputTooltip: "Systemausgabe wählen",
        mixerSystemOutputErrorFormat: "Wechsel fehlgeschlagen: %@",
        mixerLowerOnHeadphonesDisconnect: "Lautstärke senken, wenn Kopfhörer getrennt werden",
        mixerLowerOnHeadphonesDisconnectCaption: "Passt die Ausgabe an, wenn kabelgebundene oder Bluetooth-Kopfhörer getrennt werden.",
        mixerHeadphonesDisconnectVolume: "Lautstärke nach Trennung",
        preciseVolumeRollerEnable: "Feinere Lautstärkeschritte verwenden",
        preciseVolumeRollerCaption: "Macht aus Lautstärkerädern und -tasten kleinere Systemschritte.",
        preciseVolumeRollerTapFailed: "Lautstärketasten konnten nicht überwacht werden.",
        soundOutputSwitcherTitle: "Ausgabeumschalter",
        soundOutputSwitcherEnable: "Ausgaben per Kurzbefehl wechseln",
        soundOutputSwitcherCaption: "Wähle Ausgaben und nutze den Kurzbefehl für die nächste verfügbare.",
        soundOutputSwitcherDevices: "Ausgaben im Wechsel",
        soundOutputSwitcherNoAvailableSelection: "Wähle mindestens eine verfügbare Ausgabe.",
        mixerInputTitle: "Mikrofon",
        mixerInputNoDevices: "Kein Mikrofon gefunden",
        mixerInputUnavailable: "Mikrofon nicht verfügbar",
        mixerInputFallback: "Standard wird verwendet, bis dieses Mikrofon zurück ist.",
        mixerInputTooltip: "Mikrofon wählen",
        mixerInputErrorFormat: "Wechsel fehlgeschlagen: %@",
        mixerVisibleApps: "Apps in der Liste",
        mixerAllShown: "Alle",
        mixerHiddenCountLabel: "Ausgeblendet",
        mixerHideFromList: "Aus der Liste ausblenden",

        updatesSection: "Updates",
        autoCheckToggle: "Automatisch nach Updates suchen",
        includeBetaUpdatesToggle: "Beta-Updates erhalten",
        includeBetaUpdatesCaption: "Beta-Versionen enthalten neue Funktionen in Entwicklung und können instabil oder unvollständig sein.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Jetzt suchen",
        updateChecking: "Wird gesucht…",
        updateUpToDate: "Du verwendest die neueste Version.",
        updateAvailablePrefix: "Update verfügbar:",
        updateInstallButton: "Laden und installieren",
        updateDownloading: "Update wird geladen…",
        updateInstalling: "Wird installiert und neu gestartet…",
        updateFailedPrefix: "Suche fehlgeschlagen:",
        updateLastChecked: "Zuletzt gesucht:",
        updateNotifyTitle: "Vorssaint-Update",
        updateInstallFailedBody: "Das Update wurde geladen, konnte aber nicht angewendet werden. Lade die neueste Version von der GitHub-Releases-Seite und ziehe die App über die aktuelle.",
        updateNeedsApplicationsTitle: "Bewege Vorssaint in den Ordner „Programme“",
        updateNeedsApplicationsBody: "Die App läuft an einem Ort, der nicht aktualisiert werden kann, etwa im Disk-Image oder an einem temporären Systemort. Ziehe Vorssaint in den Ordner „Programme“, öffne es von dort und versuche es erneut.",
        menuCheckUpdates: "Nach Updates suchen…",

        permissionRequired: "Berechtigung erforderlich",
        permissionAccessibility: "Bedienungshilfen",
        permissionScreenRecording: "Bildschirmaufnahme",
        permissionGranted: "Erteilt",
        permissionMissing: "Nicht erteilt",
        permissionOpenSettings: "Systemeinstellungen öffnen…",
        permissionRequest: "Zugriff erlauben",
        permissionRestartNote: "macOS bittet nach dem Erteilen möglicherweise darum, die App erneut zu öffnen.",

        aboutDescription: "Eine Werkzeugzentrale für deinen Mac.\nEnergie, Systemüberwachung, Scrollen und ein Fensterumschalter, direkt in der Menüleiste.",
        versionPrefix: "Version",
        reviewIntro: "Einführung erneut ansehen",
        reviewHighlights: "Neuerungen ansehen",
        viewOnGitHub: "Auf GitHub ansehen",

        obContinue: "Fortfahren",
        obBack: "Zurück",
        obSkipStep: "Diesen Schritt überspringen",
        obStart: "Vorssaint öffnen",
        obStepWelcomeTitle: "Willkommen bei Vorssaint",
        obStepWelcomeBody: "Ein dezentes Menüleisten-Werkzeug, das den macOS-Alltag praktischer macht.",
        obWelcomeBullet1Title: "Energie unter Kontrolle",
        obWelcomeBullet1Body: "Halte den Mac so lange wach, wie du möchtest, sogar wenn der Mac zugeklappt ist.",
        obWelcomeBullet2Title: "Klarer Blick aufs System",
        obWelcomeBullet2Body: "Temperaturen, CPU- und GPU-Auslastung und Speicherauslastung in Echtzeit.",
        obWelcomeBullet3Title: "Maus und Fenster nach deinem Geschmack",
        obWelcomeBullet3Body: "Umgekehrtes Mausscrollen und ein Fensterumschalter mit Vorschaubildern.",
        obLanguageLabel: "Sprache",
        obStepAccessibilityTitle: "Bedienungshilfen",
        obStepAccessibilityBody: "Erforderlich, um das Mausscrollen umzukehren und damit der Fensterumschalter auf die Tastatur reagiert.",
        obAccessibilityWhy: "Die App beobachtet nur das Mausrad und den Kurzbefehl des Umschalters. Nichts wird aufgezeichnet oder irgendwohin gesendet.",
        obStepRecordingTitle: "Bildschirmaufnahme",
        obStepRecordingBody: "Ermöglicht es dem Umschalter, echte Fenstervorschauen statt nur Symbole anzuzeigen.",
        obRecordingWhy: "Die Vorschaubilder werden im Moment erzeugt, bleiben im Speicher und verlassen deinen Mac nie. Ohne sie funktioniert der Umschalter weiterhin mit Symbolen.",
        obStepMonitorTitle: "Systemüberwachung",
        obStepMonitorBody: "Das Panel zeigt die Temperaturen von CPU, GPU und Batterie, die Hardware-Auslastung und die Speicherauslastung.",
        obMonitorNoPermission: "Keine Berechtigung nötig. Die Sensoren werden direkt aus dem System gelesen.",
        obStepOptionalTitle: "Optionale Funktionen",
        obStepOptionalBody: "Aktiviere jetzt, was du nutzen möchtest. Alles lässt sich später in den Einstellungen ändern.",
        obStepStatusTitle: "Überprüfung",
        obStepStatusBody: "Vergewissere dich, dass für die gewünschten Funktionen alles bereit ist.",
        obStatusRecheck: "Erneut prüfen",
        obStepDoneTitle: "Alles bereit!",
        obStepDoneBody: "Vorssaint kümmert sich bereits um deinen Mac.",
        obDoneHint: "Halte Ausschau nach dem schwarzen Loch in der Menüleiste, oben rechts auf dem Bildschirm.",
        obWhatsNewTitle: "Neu in dieser Version",
        obWhatsNewFallback: "Dieses Update enthält die neuesten Korrekturen und Verbesserungen.",
        obLanguageUpdateTitle: "Jetzt in deiner Sprache",
        obLanguageUpdateBody: "Vorssaint spricht jetzt mehrere Sprachen. Wähle die, die du verwenden möchtest; du kannst sie jederzeit in den Einstellungen ändern.",
        obPurposeTitle: "Was führt dich hierher?",
        obPurposeBody: "Wähle eine fertige Einrichtung oder genau die Funktionen, die du nutzen möchtest.",
        obPurposeSkip: "Du kannst Funktionen später in den Einstellungen ändern.",

        tabMonitor: "Überwachung",
        monitorMenuBarSection: "In der Menüleiste",
        monitorMenuBarCaption: "Wähle, was neben dem Symbol in der Menüleiste erscheint.",
        monitorCombineTemperatures: "Auslastung und Temperatur kombinieren",
        monitorCombineTemperaturesCaption: "Wenn Auslastung und Temperatur desselben Elements aktiv sind, erscheinen sie in einem Block.",
        monitorSeparateMenuBarMetrics: "Messwerte in eigene Elemente trennen",
        monitorSeparateMenuBarMetricsCaption: "Trennt aktive Blöcke in der Menüleiste und hält Auslastung und Temperatur zusammen, wenn Kombinieren aktiv ist.",
        monitorNetworkUploadFirst: "Upload über Download",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Speicher",
        monitorShowNetwork: "Netzwerk",
        monitorShowPowerLabel: "Energie",
        monitorIntervalLabel: "Aktualisieren alle",
        monitorInterval1: "1 Sekunde",
        monitorInterval2: "2 Sekunden",
        monitorInterval5: "5 Sekunden",
        monitorPanelSection: "Im Panel",
        panelNavigationMode: "Panel nach Bereichen navigieren",
        panelNavigationCaption: "Zeigt jeweils einen Bereich. Wähle Liste, um alles in einem durchgehenden Scrollbereich zu sehen.",
        panelFooterSections: "Bereiche",
        panelFooterList: "Liste",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Es können noch Fehler auftreten.",

        networkSection: "Netzwerk",
        networkDownload: "Download",
        networkUpload: "Upload",
        networkThisSession: "Diese Sitzung",
        networkMeasuring: "Wird gemessen…",
        networkApps: "Apps mit Netzwerkverkehr",
        networkAppsIdle: "Keine App nutzt gerade das Netzwerk",

        diskSection: "Festplatten",
        diskUsed: "belegt",
        diskFree: "frei",
        diskAvailable: "verfügbar",
        diskPurgeable: "löschbar",
        diskInternal: "Intern",
        diskExternal: "Extern",
        diskSelect: "Festplatte wählen",
        diskRead: "Lesen",
        diskWrite: "Schreiben",
        diskSMARTStatus: "Status",
        diskSMARTUnavailable: "SMART für dieses Laufwerk nicht verfügbar",
        diskTotalRead: "Insgesamt gelesen",
        diskTotalWritten: "Insgesamt geschrieben",
        diskTemperature: "Temperatur",
        diskHealth: "Gesundheit",
        diskPowerCycles: "Einschaltzyklen",
        diskPowerOnHours: "Betriebsstunden",
        diskUnsafeShutdowns: "Unsichere Abschaltungen",
        diskMediaErrors: "Medienfehler",
        diskEject: "Auswerfen",
        diskEjectAll: "Alle auswerfen",
        diskEjecting: "Wird ausgeworfen…",
        diskReadyToRemove: "Bereit zum Entfernen",
        diskEjectFailed: "Auswerfen fehlgeschlagen",
        diskProtectionCaption: "Vor dem Abziehen auswerfen.",
        diskNoExternal: "Kein externes Laufwerk zum Auswerfen bereit.",
        diskOpenInFinder: "Öffnen",
        diskStorageSettings: "Speicher",
        diskNoDisks: "Keine eingebundenen Laufwerke gefunden.",

        powerSection: "Energie",
        powerSystem: "System",
        powerAdapter: "Netzteil",
        powerBattery: "Batterie",
        powerCharging: "Wird geladen",
        powerOnBattery: "Im Batteriebetrieb",
        powerPluggedIn: "Am Netzteil",
        powerUnavailable: "Energiedaten auf diesem Mac nicht verfügbar",
        powerAdapterMaxFormat: "max. %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU-Temperatur",
        monitorShowGPUTemperature: "GPU-Temperatur",
        monitorShowBatteryTemperature: "Batterietemperatur",
        monitorShowPeripheralBattery: "Peripheriebatterie",
        peripheralBatteryNoDevices: "Keine Geräte gefunden",
        monitorGraphsSection: "Diagramme",
        monitorGraphsCaption: "Wähle, welche Werte ein Diagramm über die Zeit anzeigen.",

        updateBannerTitle: "Update verfügbar",
        updateBannerAction: "Aktualisieren",
        obStepMenuBarTitle: "Werte in der Menüleiste",
        obStepMenuBarBody: "Wähle, was neben dem Symbol angezeigt wird. Die Vorschau oben aktualisiert sich live.",
        obStepMenuBarNote: "Neu: Blöcke für Netzwerk und Energie sowie Diagramme im Panel. Stelle alles später unter Einstellungen › Überwachung fein ein.",
        monitorMenuBarPresetLabel: "Stil",
        menuBarPresetReadable: "Lesbar",
        menuBarPresetDense: "Dicht",
        menuBarSpacingLabel: "Abstand in der Menüleiste",
        menuBarSpacingStandard: "Standard",
        menuBarSpacingCompact: "Kompakt",
        menuBarHideIconToggle: "App-Symbol ausblenden, solange Messwerte angezeigt werden",
        menuBarHideIconCaption: "Das Symbol kehrt von selbst zurück, wenn die Messwerte die Leiste verlassen und wenn es etwas zu melden gibt (ein Update bereit oder das Mikrofon stumm).",
        monitorLabelStyleLabel: "Beschriftungen",
        menuBarLabelStyleCompact: "Kompakt",
        menuBarLabelStyleClassic: "Klassisch",
        monitorMemoryStyleLabel: "Speicher anzeigen als",
        monitorMemoryPressureDot: "Speicherdruckpunkt",
        memoryStyleDot: "Punkt",
        memoryStylePercent: "%",
        memoryStyleBoth: "Beides",
        systemUptime: "Aktiv seit",
        batteryCharge: "Ladung",
        powerHealth: "Batteriezustand",
        powerCycles: "Zyklen",
        speedTestRun: "Geschwindigkeitstest",
        speedTestAgain: "Erneut testen",
        speedTestLatency: "Latenz",
        speedTestTesting: "Wird getestet…",
        speedTestFailed: "Test fehlgeschlagen",

        monitorShowInPanel: "Im Panel anzeigen",
        disclosureExpanded: "Ausgeklappt",
        disclosureCollapsed: "Eingeklappt",
        panelHideItem: "Im Panel ausblenden",
        panelShowItem: "Im Panel anzeigen",
        panelHiddenItem: "Ausgeblendet",
        monitorItemUptime: "Betriebszeit",
        monitorItemNetSpeed: "Live-Geschwindigkeit",
        monitorItemNetTotals: "Sitzungssummen",
        monitorItemNetTest: "Geschwindigkeitstest",
        monitorItemDiskUsage: "Festplattennutzung",
        monitorItemDiskActivity: "Live-Aktivität",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Externer Schutz",
        monitorItemDiskTools: "Werkzeuge",
        monitorPanelConfigHint: "Öffne einen Block, um zu wählen, was er anzeigt.",
        monitorOrderSection: "Reihenfolge der Bereiche",
        monitorOrderHint: "Ziehen, um die Panel-Bereiche neu anzuordnen, und mit dem Auge jeden ein- oder ausblenden.",
        obStepPanelTitle: "Was im Panel erscheint",
        obStepPanelBody: "Öffne jeden Block und wähle genau, was angezeigt wird, wenn du auf das Symbol klickst.",
        obStepPanelNavigationTitle: "Panel nach Bereichen",
        obStepPanelNavigationBody: "Das Panel kann jetzt jeweils einen Bereich anzeigen. Du kannst in den Einstellungen zwischen Bereiche und Liste wechseln.",

        cleaningMenuItem: "Reinigungsmodus",
        utilitiesSection: "Dienstprogramme",
        quickControlsSection: "Steuerung",
        panelCategoryWindows: "Fenster",
        panelCategoryInput: "Maus und Tastatur",
        panelCategoryFiles: "Dateien",
        windowMaximizeName: "Fenster maximieren",
        windowMaximizeCaption: "Der grüne Knopf maximiert, ohne einen weiteren Space zu erstellen.",
        windowMaximizeActiveNow: "Grüner Knopf aktiv",
        windowMaximizeNeedsAccessibility: "Benötigt Bedienungshilfen, um zu funktionieren.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Doppelte Tasten filtern",
        keyDebounceCaption: "Filtert sehr schnelle doppelte Tastendrücke.",
        keyDebounceActiveNow: "Filter aktiv",
        keyDebounceGlobalWindow: "Globales Fenster",
        keyDebouncePerKeySection: "Bestimmte Tasten",
        keyDebouncePerKeyCaption: "Werte pro Taste ersetzen das globale Fenster. 0 ms filtert diese Taste nicht.",
        keyDebounceKeyLabel: "Taste",
        keyDebounceWindowLabel: "Fenster",
        keyDebounceAddKey: "Taste hinzufügen",
        keyDebounceNoOverrides: "Keine bestimmten Tasten konfiguriert.",
        keyDebounceRemoveKey: "Taste entfernen",
        cleaningPanelCaption: "Sperrt die Tastatur, damit du sicher reinigen kannst.",
        cleaningOverlayTitle: "Tastatur zum Reinigen gesperrt",
        cleaningOverlaySubtitle: "Esc 5-mal drücken zum Entsperren",
        cleaningOverlayUnlock: "Entsperren",
        cleaningOverlayMouseHint: "Maus und Trackpad funktionieren weiterhin",
        cleaningKeepScreenVisibleToggle: "Bildschirm sichtbar lassen",
        cleaningKeepScreenVisibleCaption: "Zeigt einen dezenten Hinweis in der Bildschirmecke an, anstatt Inhalte abzudunkeln.",
        cleaningStartNow: "Tastatur jetzt sperren",
        cleaningNeedsAxTitle: "Bedienungshilfen erforderlich",
        cleaningNeedsAxBody: "Um die Tastatur sicher zu sperren, benötigt Vorssaint die Berechtigung für Bedienungshilfen. Erteile sie in den Systemeinstellungen und versuche es erneut.",

        tabSupport: "Unterstützen",
        shortcutsPageCaption: "Bearbeite hier alle globalen Kurzbefehle der auf diesem Mac installierten Funktionen. Inaktive Kurzbefehle bleiben gespeichert, werden aber nicht ausgeführt.",
        shortcutsPageTitle: "Tastaturkurzbefehle",
        settingsSearchPlaceholder: "Einstellungen durchsuchen",
        donateHeading: "Hilf Vorssaint weiter zu wachsen",
        donateMessage: "Vorssaint ist kostenlos, unabhängig und entsteht in meiner Freizeit. Wenn du die Entwicklung finanziell unterstützen möchtest, hilft Buy Me a Coffee direkt dabei, sie voranzubringen.",
        donateButton: "Über Buy Me a Coffee unterstützen",
        donateThanks: "Danke, dass du hier bist. 🖤",
        supportIntroTitle: "Hilf Vorssaint weiter zu wachsen",
        supportIntroMessage: "Wenn du die Entwicklung finanziell unterstützen möchtest, ist Buy Me a Coffee der einzige Ort dafür.",
        supportIntroStarButton: "Vorssaint auf GitHub einen Stern geben",
        supportIntroStarMessage: "Finanzielle Unterstützung wird nie erwartet. Ein Stern auf GitHub hilft mehr Menschen, Vorssaint zu entdecken, und macht für die Entwicklung einen echten Unterschied.",
        supportIntroCoffeeButton: "Über Buy Me a Coffee unterstützen",
        supportIntroLaterButton: "Jetzt nicht",
        supportIntroDoneButton: "Fertig",
        discordIntroTitle: "Die Vorssaint Community auf Discord steht noch am Anfang",
        discordIntroMessage: "Die Vorssaint Community ist neu und wächst noch. Tritt früh bei, lerne andere Nutzer kennen und hilf, einen einladenden Ort rund um die App aufzubauen.",
        discordIntroJoinButton: "Der Discord Community beitreten",
        communityIntroTitle: "Sieh alles vor allen anderen",
        communityIntroMessage: "Wer mir bereits auf X folgte, hat viele Änderungen dieses Updates vor allen anderen gesehen. Dort zeige ich Vorschauen auf kommende Neuerungen und wie sie funktionieren, damit du schon vor dem Update die Grundlagen kennst. Folge mir und sieh, was als Nächstes kommt!",
        communityIntroFollowButton: "@vorssaint auf X folgen",
        homebrewOfficialIntroTitle: "Jetzt im offiziellen Katalog von Homebrew",
        homebrewOfficialIntroMessage: "Vorssaint kann jetzt direkt aus dem offiziellen Katalog von Homebrew installiert werden.",
        homebrewOfficialIntroInstallLabel: "Neue Installation",
        homebrewOfficialIntroMigrationTitle: "Hast du den alten Tap verwendet?",
        homebrewOfficialIntroMigrationMessage: "Entferne den alten Tap einmal. Die App und deine Einstellungen bleiben erhalten.",
        homebrewOfficialIntroCopyButton: "Befehl kopieren",
        updateShowcaseTitle: "Neues in 3.1.4",
        updateShowcaseMessage: "Sieh dir kurz die wichtigsten Verbesserungen in diesem Update an.",
        updateShowcaseUnavailable: "Das Video konnte gerade nicht geladen werden. Du kannst trotzdem fortfahren.",
        updateShowcaseRestart: "Zum Anfang",
        showMenuBarIcon: "Menüleistensymbol anzeigen",
        showMenuBarIconCaption: "Falls das Symbol von Vorssaint verschwindet (macOS kann Menüleistensymbole ausblenden, wenn der Platz in der Leiste knapp wird, häufig bei Macs mit Notch), öffne Vorssaint erneut über „Programme“ oder Spotlight: Das stellt das Symbol wieder her und öffnet, falls es weiterhin ausgeblendet ist, dieses Fenster.",
        menuBarIconStillHiddenTitle: "Das Symbol ist weiterhin verborgen",
        menuBarIconStillHiddenBody: "Das Symbol wurde neu aufgebaut, aber macOS hat ihm keinen sichtbaren Platz gegeben. In der Menüleiste ist vermutlich kein Platz mehr: Entferne einige Menüleisten-Symbole (oder schließe Apps mit langen Menüs) und versuche es erneut.",
        menuBarIconManagerHintFormat: "%@ läuft und hält das Symbol womöglich in seinem verborgenen Bereich. Suche Vorssaint dort, oder stelle %@ so ein, dass Vorssaint immer angezeigt wird.",
        shortcutRecording: "Neuen Kurzbefehl drücken",
        shortcutReset: "Zurücksetzen",
        shortcutNone: "Keiner",
        shortcutClear: "Kurzbefehl entfernen",
        shortcutInvalid: "Verwende mindestens Control, Option oder Command mit einer Taste.",
        shortcutPressKeys: "Drücken",
        shortcutEscapeHint: "Esc bricht ab.",
        shortcutDeleteHint: "Delete entfernt.",
        shortcutNotCaptured: "Es wurde nichts erfasst. macOS oder eine andere App belegt diese Kombination bereits. Wähle eine andere.",
        shortcutConflictFormat: "Dieser Kurzbefehl wird bereits von %@ verwendet.",
        shortcutUnavailable: "macOS hat diesen Kurzbefehl abgelehnt. Wähle einen anderen.",
        shelfShortcutToggle: "Shelf-Kurzbefehl",
        switcherUsageHintFormat: "Halte %@ zum Navigieren; loslassen, um das Fenster zu aktivieren. Umschalt oder ← geht zurück; W schließt das Fenster; Q beendet die App; Esc bricht ab.",
        musicBlockSection: "Medientasten",
        musicBlockTitle: "Musik nicht von selbst öffnen lassen",
        musicBlockCaption: "Die Musik-App öffnet sich beim Drücken der Medientasten nicht mehr. Du kannst sie weiterhin selbst öffnen.",
        musicBlockReplacementLabel: "Stattdessen öffnen",
        musicBlockReplacementNone: "Keine",
        musicBlockChooseApp: "App wählen…",
        cleanerName: "Aufräumen",
        cleanerIntroTitle: "Räume den Mac auf",
        cleanerIntroCaption: "Sucht Reste deinstallierter Apps, Caches, Protokolle und den Papierkorb. Du prüfst alles vorher und Entferntes landet im Papierkorb.",
        cleanerScan: "Prüfen",
        cleanerScanning: "Prüfe…",
        cleanerCleaning: "Räume auf…",
        cleanerCatLeftovers: "Reste deinstallierter Apps",
        cleanerCatLoginItems: "Verwaiste Anmeldeobjekte",
        cleanerCatCaches: "Caches",
        cleanerCatLogs: "Protokolle",
        cleanerCatDeveloper: "Entwicklerdaten",
        cleanerCatTrash: "Papierkorb",
        cleanerLeftoversNote: "Per Analyse gefunden und nicht angehakt. Prüfe den Pfad vor dem Anhaken.",
        cleanerLoginItemsNote: "Der Eintrag unter Anmeldeobjekte verschwindet nach einem Neustart.",
        cleanerTrashNote: "Das Leeren des Papierkorbs ist endgültig.",
        cleanerCatDeviceBackups: "iPhone-Backups",
        cleanerDeviceBackupsCaption: "Alte iPhone- und iPad-Backups belegen einen großen Teil des Speichers, den macOS Andere nennt. Entferne nur die, die du nicht mehr brauchst; beim nächsten Anschließen entsteht ein neues.",
        cleanerNothingFound: "Nichts aufzuräumen. Dein Mac ist in Ordnung.",
        cleanerClean: "Aufräumen",
        cleanerDoneNote: "Die Objekte liegen im Papierkorb und können von dort zurückgeholt werden.",
        cleanerAgain: "Erneut prüfen",
        cleanerRevealInFinder: "Im Finder zeigen",
        cleanerPanelCaption: "App-Reste, Caches und Protokolle",
        cleanerSafeSection: "Sichere Reinigung",
        cleanerOptionalSection: "Optional, vorher prüfen",
        cleanerCatOtherCaches: "Weitere Caches",
        cleanerCachesCaption: "Temporäre Dateien, die Apps von selbst neu anlegen.",
        cleanerLogsCaption: "Alte Diagnoseprotokolle.",
        cleanerDeveloperCaption: "Build- und Simulator-Reste von Xcode.",
        cleanerLoginItemsCaption: "Anmeldeeinträge von Apps, die es nicht mehr gibt.",
        cleanerLeftoversCaption: "Dateien von Apps, die du deinstalliert hast.",
        cleanerOtherCachesCaption: "Sicher zu löschen, nichts geht kaputt. Apps starten einmalig langsamer und Heruntergeladenes, etwa Offline-Musik, lädt erneut.",
        cleanerCleanSizeFormat: "%@ aufräumen",
        cleanerScheduleTitle: "Automatisches Aufräumen",
        cleanerScheduleOff: "Aus",
        cleanerScheduleDaily: "Täglich",
        cleanerScheduleWeekly: "Wöchentlich",
        cleanerScheduleCaption: "Räumt zur gewählten Zeit von selbst nur den sicheren Teil auf und legt alles in den Papierkorb.",
        cleanerScheduleLastFormat: "Das letzte automatische Aufräumen hat %@ freigegeben.",
        cleanerAutoNotificationFormat: "%@ freigegeben und in den Papierkorb gelegt.",
        cleanerScheduleNextFormat: "Nächstes Aufräumen %@.",
        cleanerScheduleRanFormat: "Letztes automatisches Aufräumen %@.",
        cleanerScheduleNotifyToggle: "Nach Abschluss benachrichtigen",
        cleanerNotifDenied: "Mitteilungen von Vorssaint sind im System deaktiviert.",
        cleanerNotifOpenSettings: "Mitteilungseinstellungen öffnen…",
        launchAtLoginNeedsApplications: "Die App läuft von einem Ort, der das Öffnen bei der Anmeldung nicht erlaubt. Ziehe Vorssaint in den Ordner Programme, öffne die App von dort und schalte die Option wieder ein.",
        launchAtLoginNeedsApproval: "Das Anmeldeobjekt ist registriert, in den Systemeinstellungen aber weiterhin aus. Öffne Systemeinstellungen › Allgemein › Anmeldeobjekte & Erweiterungen und schalte Vorssaint unter „Bei der Anmeldung öffnen“ ein.",
        ocrRemoveLineBreaksToggle: "Zeilenumbrüche entfernen",
        ocrRemoveLineBreaksCaption: "Entfernt Zeilenumbrüche, damit kopierter Text als ein Absatz eingefügt wird.",
        ocrQRToggle: "QR-Codes lesen",
        ocrQRCaption: "Enthält der Bereich einen QR-Code, wird sein Inhalt zum Kopieren oder Öffnen gezeigt.",
        ocrQRCopied: "QR-Code kopiert",
        qrResultTitle: "QR-Code",
        qrResultCopy: "Kopieren",
        qrResultOpen: "Link öffnen",
        highlightsTitle: "Neu in diesem Update",
        highlightsTitleClipboardRedesign: "Überarbeitete Zwischenablage",
        highlightsTitleWindowLayout: "Fenster-Layout",
        highlightsTitleQuitProtection: "Schutz für ⌘Q und ⌘W",
        highlightsTitleRecorderBlur: "Weichzeichner für Aufnahmen",
        highlightsCaptionDockPreview: "Dock Preview funktioniert jetzt auch mit eingeschalteter Dock-Vergrößerung",
        highlightsCaptionScreenshot: "Das Bildschirmfoto-Werkzeug hat eine Pixel-Lupe und QR-Code-Erkennung erhalten",
        highlightsCaptionSnippetLibrary: "Ein durchsuchbares Schnipsel-Menü tippt jeden Schnipsel direkt am Cursor",
        highlightsCaptionCapturePalette: "Ein einzelner Kurzbefehl öffnet jetzt eine schwebende Palette für Bildschirmfotos, Aufnahmen, Bildschirmtext und Farben mit direkten Einstellungen.",
        highlightsCaptionClipboardRedesign: "Der Verlauf öffnet sich jetzt als kompakte Palette mit übersichtlichen Zeilen und einer Vorschau auf Abruf zum Lesen oder Bearbeiten des gesamten Eintrags.",
        highlightsCaptionWindowLayout: "Positionieren Sie Fenster mit dem Richtungsring über Kurzbefehl und Zeiger oder ziehen Sie sie an die Bildschirmränder mit anpassbaren Abständen.",
        highlightsCaptionQuitProtection: "Verhindern Sie versehentliches Schließen von Apps oder Fenstern durch Gedrückthalten, Doppeltippen oder eine Zusatztaste, anpassbar pro App.",
        highlightsCaptionRecorderBlur: "Verbergen Sie vertrauliche Daten, Passwörter und private Details in beliebigen Abschnitten Ihrer Videoaufnahme vor dem Exportieren.",
        highlightsConfigure: "Einrichten",
        highlightsTry: "Ausprobieren",
        highlightsSeeAll: "Alle Änderungen ansehen",
        switcherCurrentSpaceOnly: "Nur den aktuellen Schreibtisch anzeigen",
        switcherCurrentSpaceOnlyCaption: "Zeigt im Umschalter nur Fenster des Schreibtischs, auf dem du gerade bist. Die Auswahl eines Fensters wechselt nie zu einem anderen Schreibtisch.",
        shelfFileMissing: "Die Datei existiert nicht mehr",
        previewSizeSmall: "Klein",
        mixerSoundEffectsOutputTitle: "Systemtöne",
        mixerSoundEffectsOutputTooltip: "Auswählen, wo Hinweise und Toneffekte wiedergegeben werden",
        monitorOpenActivityMonitor: "Aktivitätsanzeige öffnen",
        dockClickHide: "Klick aufs Dock-Symbol blendet App aus",
        dockClickHideCaption: "Die aktive App wird ausgeblendet, wenn du auf ihr Dock-Symbol klickst. Ein weiterer Klick holt sie zurück.",
        monitorMemoryMetricLabel: "Speicher messen als",
        memoryMetricUsed: "Genutzter Speicher",
        memoryMetricApp: "App-Speicher",
        keepAwakeRightClickToggle: "Menüleistensymbol rechtsklicken, um Wachhalten umzuschalten",
        keepAwakeRightClickToggleCaption: "Ersetzt das Kontextmenü beim Rechtsklick.",
        urlCleanerRulesTitle: "Bereinigungsregeln",
        urlCleanerRulesCaption: "Eine Website hängt diese Parameter an ihre eigenen Teilen-Links, um zu verfolgen, woher ein Link kam. Mit Haken wird der Name beim Bereinigen entfernt, ohne Haken bleibt er. Selbst hinzugefügte Namen lassen sich löschen.",
        urlCleanerRulesCoverageCaption: "Die Liste deckt die verschiedenen Teilen-Wege einer Website ab (Webseite, App, Livestream), deshalb ist sie lang; ein echter Link trägt meist nur zwei bis vier davon.",
        urlCleanerRulesAllSites: "Alle Websites",
        urlCleanerRulesCountSingular: "1 Parameter",
        urlCleanerRulesCountPluralFormat: "%d Parameter",
        urlCleanerRulesAddSite: "Website hinzufügen",
        urlCleanerRulesParameterPlaceholder: "Parametername",
        urlCleanerRulesMatchCaption: "Trage den Namen links vom = ein, etwa utm_source. Ein passender Name nimmt genau diesen Parameter aus dem Link und lässt den Rest, wie er war.",
        urlCleanerRulesAddButton: "Hinzufügen",
        urlCleanerRulesRemoveButton: "Name löschen",
        urlCleanerRulesRemoveSiteButton: "Alle Regeln dieser Website ausschalten",
        urlCleanerRemovedFormat: "Entfernt %@",
        switcherSearchPin: "Suche mit S anpinnen",
        switcherSearchPinCaption: "S startet die Suche und pinnt den Umschalter an – so tippst du keine Sonderzeichen mehr, wenn dein Kurzbefehl ⌥ nutzt, und eine Suche, die mit Q oder W beginnt, schließt das Fenster oder die App nicht mehr versehentlich.",
        invertVerticalScroll: "Vertikales Scrollen umkehren",
        invertHorizontalScroll: "Horizontales Scrollen umkehren",
        switcherShowShortcutHints: "Kurzbefehlhinweise anzeigen",
        switcherShowShortcutHintsCaption: "Zeigt die Kurzbefehle für Apps und Fenster unter den Symbolen.",
        uninstallerHomebrewPackageFormat: "%@ wird auch aus Homebrew entfernt.",
        shelfEdgeToggle: "In der Nähe eines Bildschirmrands öffnen",
        shelfEdgeCaption: "Ziehe eine Datei in Richtung Bildschirmrand, damit die Ablage kurz hervorschaut. Lass sie dort los, oder zieh zurück, und die Ablage verschwindet wieder.",
        focusFollowsMouseName: "Fokus folgt Maus",
        focusFollowsMouseCaption: "Fokussiert das Fenster unter dem Zeiger und bringt es nach kurzer Pause nach vorn.",
        focusFollowsMouseDelay: "Verzögerung",
        switcherMinimizedPlacementLabel: "Minimierte Fenster",
        switcherMinimizedPlacementNormal: "Normale Reihenfolge",
        switcherMinimizedPlacementEnd: "Ans Ende stellen",
        switcherMinimizedPlacementHidden: "Ausblenden",
        switcherShowFullscreenWindows: "Vollbildfenster anzeigen",
        switcherScreenPlacementLabel: "Anzeigen auf",
        switcherScreenPlacementPointer: "Bildschirm mit dem Zeiger",
        switcherScreenPlacementMenuBar: "Bildschirm mit der Menüleiste",
        switcherScreenPlacementActiveWindow: "Bildschirm mit dem aktiven Fenster",
        switcherScreenPlacementCaption: "Auf welchem Bildschirm der Umschalter erscheint, wenn mehrere angeschlossen sind.",
        smoothScrollResponseLabel: "Reaktion",
        mouseAccelerationName: "Mausbeschleunigung deaktivieren",
        mouseAccelerationCaption: "Deaktiviert die Zeigerbeschleunigung für angeschlossene Mäuse. Die vorherige Einstellung wird beim Ausschalten oder Beenden von Vorssaint wiederhergestellt.",
        shelfClearOnClose: "Beim Schließen leeren",
        shelfClearOnCloseCaption: "Leert die Ablage nur, wenn du auf die Schließen-Taste klickst. Automatisches Ausblenden und Einklappen behalten die Objekte."
    )
}
