// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Español — translated and hand-checked, not machine output.
extension Strings {
    static let es = Strings(
        statusIdleTooltip: "Vorssaint: reposo normal",
        statusActiveUntil: "Vorssaint: activo hasta",
        statusActiveIndefinite: "Vorssaint: activo indefinidamente",
        menuEnableAwake: "Activar mantener activo",
        menuDisableAwake: "Desactivar mantener activo",
        menuActivateFor: "Activar durante…",
        menuSettings: "Ajustes…",
        menuAbout: "Acerca de Vorssaint",
        menuQuit: "Salir de Vorssaint",
        menuHide: "Ocultar Vorssaint",
        menuHideOthers: "Ocultar los demás",
        menuShowAll: "Mostrar todo",
        menuEdit: "Edición",
        menuUndo: "Deshacer",
        menuRedo: "Rehacer",
        actionClear: "Borrar",
        actionRemove: "Quitar",
        actionBack: "Atrás",
        actionSearch: "Buscar",
        actionMute: "Silenciar",
        actionUnmute: "Reactivar sonido",
        actionPlay: "Reproducir",
        actionPause: "Pausar",
        menuCut: "Cortar",
        menuCopy: "Copiar",
        menuPaste: "Pegar",
        menuSelectAll: "Seleccionar todo",
        menuWindow: "Ventana",
        menuMinimize: "Minimizar",
        menuZoom: "Zoom",
        menuClose: "Cerrar",

        minutes15: "15 minutos",
        minutes30: "30 minutos",
        hour1: "1 hora",
        hours2: "2 horas",
        hours4: "4 horas",
        hours8: "8 horas",
        indefinitely: "Indefinidamente",
        indefinite: "Indefinido",

        panelSettings: "Ajustes",
        panelQuit: "Salir",
        panelHotkeyHint: "El atajo alterna",

        keepAwakeTitle: "Mantener activo",
        keepAwakeEndsIn: "Termina en",
        keepAwakeUntilDisabled: "Activo hasta que lo desactives",
        keepAwakeNormalRules: "El Mac sigue sus reglas de energía normales",
        keepAwakeOptions: "Opciones",
        keepAwakeMouseJiggle: "Mover ligeramente el cursor",
        keepAwakeMouseJiggleCaption: "Durante una sesión, mueve un poco el cursor en el intervalo elegido.",
        keepAwakeMouseJiggleInterval: "Intervalo",
        keepAwakeActiveIconLabel: "Icono activo",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Café",
        keepAwakeActiveIconEye: "Ojo",
        keepAwakeActiveIconMoon: "Luna",
        keepAwakeActiveIconLight: "Bombilla",
        keepAwakeIconTintLabel: "Color del icono activo",
        keepAwakeIconTintOrange: "Naranja",
        keepAwakeIconTintGreen: "Verde",
        keepAwakeIconTintBlue: "Azul",
        keepAwakeIconTintPurple: "Morado",
        keepAwakeIconTintPink: "Rosa",
        keepAwakeIconTintNone: "Sin color",
        durationLabel: "Duración",
        clamshellTitle: "Seguir con la tapa cerrada",
        clamshellOnCaption: "Reposo totalmente desactivado. Cuida la energía",
        clamshellNeedsSession: "Se aplica siempre que “Mantener activo” esté activo",
        clamshellReady: "Listo. Se alterna sin contraseña",
        clamshellNeedsPassword: "Pedirá la contraseña de administrador una vez",

        systemSection: "Sistema",
        temperatures: "Temperaturas",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batería",
        usageSection: "Uso del hardware",
        memorySection: "Memoria",
        memoryPressure: "Presión",
        memorySwapUsed: "Swap usado",
        memoryCompressed: "Comprimida",
        memoryCachedFiles: "Archivos en caché",
        pressureNormal: "Normal",
        pressureWarning: "Precaución",
        pressureCritical: "Crítica",
        monitorUnavailable: "Sensores no disponibles en este Mac",
        energyAppsTitle: "Uso significativo de energía",
        energyAppsIdle: "Sin uso significativo de energía",

        notifySessionEndedTitle: "Sesión finalizada",
        notifySessionEndedBody: "Se acabó el tiempo. El Mac volverá a entrar en reposo con normalidad.",
        notifyBatteryTitle: "Vorssaint desactivado",
        notifyBatteryBody: "Batería baja. Se restauró el reposo normal para proteger la carga.",
        adminPromptClamshellOn: "Vorssaint necesita tu contraseña para seguir con la tapa cerrada.",
        adminPromptClamshellOff: "Vorssaint necesita tu contraseña para restaurar el reposo normal del Mac.",
        adminPromptRecover: "Vorssaint se cerró mientras el reposo del Mac estaba desactivado. Introduce la contraseña para restaurar el reposo normal.",
        adminPromptUpdate: "Vorssaint necesita tu contraseña para instalar la actualización.",
        adminPromptSudoersInstall: "Vorssaint creará una regla restringida (solo pmset disablesleep) para alternar el modo de tapa cerrada sin pedir contraseña. Esta es la única vez que se necesita la contraseña.",
        adminPromptSudoersRemove: "Vorssaint eliminará la regla de tapa cerrada sin contraseña.",

        settingsTitle: "Ajustes de Vorssaint",
        tabGeneral: "General",
        tabEnergy: "Energía",
        tabMouse: "Ratón y trackpad",
        tabSwitcher: "Selector",
        tabAdvanced: "Avanzado",
        tabAbout: "Acerca de",
        tabReleaseNotes: "Novedades",
        releaseNotesOnUpdateToggle: "Mostrar novedades al actualizar",
        minimalWindowPreviews: "Vistas previas minimalistas",
        minimalWindowPreviewsCaption: "Oculta títulos, botones y adornos en las vistas previas del Dock y del selector de apps. La selección sigue visible.",
        previewSizeLabel: "Tamaño de vistas previas",
        previewSizeNormal: "Normal",
        previewSizeLarge: "Grande",
        previewSizeXLarge: "Extra grande",
        settingsGroupFeatures: "Funciones",
        advancedResetSection: "Permisos",
        advancedResetDescription: "Elimina todos los permisos que concediste a Vorssaint (Accesibilidad, Grabación de pantalla, Acceso total al disco y otros), el ítem de inicio de sesión y la regla de tapa cerrada. Útil para empezar de cero o antes de desinstalar. La app sigue instalada.",
        advancedClearButton: "Borrar todos los permisos",
        advancedCleared: "Permisos borrados.",
        advancedClearConfirmTitle: "¿Borrar todos los permisos?",
        advancedClearConfirmBody: "Las funciones que necesitan permisos dejarán de funcionar hasta que los concedas de nuevo. Tus ajustes se conservan.",
        advancedUninstallSection: "Desinstalar",
        advancedUninstallDescription: "Hace todo lo anterior y, además, elimina las preferencias y mueve Vorssaint a la Papelera, sin dejar rastro. La app se cierra al terminar. Puedes reinstalarla cuando quieras.",
        advancedUninstallButton: "Desinstalar Vorssaint por completo",
        advancedUninstallConfirmTitle: "¿Desinstalar Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint borrará sus permisos, eliminará sus preferencias y se moverá a la Papelera; después se cerrará. Esto no se puede deshacer desde la app, pero permanece en la Papelera hasta que la vacíes.",
        advancedUninstallFailedTitle: "La desinstalación se detuvo",
        advancedUninstallFailedBody: "Vorssaint no pudo restaurar un ajuste del sistema que había cambiado: la suspensión, la velocidad de los ventiladores o la aceleración del ratón. No se eliminó nada. Inténtalo de nuevo y permite la solicitud de contraseña si aparece.",

        launchAtLogin: "Abrir al iniciar sesión",
        languageLabel: "Idioma",
        menuBarSection: "Barra de menús",
        showCountdown: "Mostrar el tiempo restante junto al icono",
        globalHotkeySection: "Atajo global",
        hotkeyToggle: "Activar atajo para “Mantener activo”",
        hotkeyCaption: "Funciona en cualquier app, sin permisos adicionales.",

        sessionSection: "Sesión",
        defaultDurationLabel: "Duración predeterminada",
        keepAwakeAutoStart: "Mantener activo al abrir Vorssaint",
        keepAwakeAutoStartCaption: "Inicia una sesión con la duración predeterminada.",
        batteryProtectionSection: "Protección de la batería",
        batteryDisableBelow: "Desactivar cuando la batería baje de",
        batteryNever: "Nunca",
        batteryProtectionCaption: "Evita que una sesión olvidada agote la batería del MacBook.",
        clamshellSection: "Tapa cerrada",
        configuring: "Configurando…",
        sudoersFailed: "No se pudo activar el modo de tapa cerrada. Inténtalo de nuevo.",
        clamshellExplanation: "“Seguir con la tapa cerrada” desactiva por completo el reposo mientras “Mantener activo” está activo y se revierte automáticamente cuando la sesión termina o la app se cierra. Es preferible usarlo conectado a la corriente.",

        scrollSection: "Desplazamiento",
        invertMouseScroll: "Invertir el desplazamiento del ratón",
        invertMouseScrollCaption: "Invierte la dirección de la rueda del ratón.",
        scrollTrackpadNote: "El trackpad no se modifica: mantiene el desplazamiento natural de macOS.",
        scrollActiveNow: "Invirtiendo el desplazamiento del ratón ahora",
        mouseNavigationActiveNow: "Botones laterales activos ahora",
        smoothScrollName: "Desplazamiento suave",
        smoothScrollCaption: "Convierte cada paso de la rueda del ratón en un deslizamiento corto y suave. El trackpad no cambia.",
        smoothScrollStepLabel: "Velocidad de desplazamiento",
        mouseNavigationSection: "Navegación",
        mouseNavigationEnable: "Usar los botones laterales para Atrás y Adelante",
        mouseNavigationCaption: "Convierte los botones Atrás y Adelante del ratón en comandos de navegación para Finder, navegadores y apps compatibles.",
        middleClickSection: "Clic central",
        middleClickEnable: "El clic con tres dedos actúa como clic central",
        middleClickEnableCaption: "Presionar el trackpad con tres dedos funciona como el clic de la rueda del ratón: abrir enlaces en una pestaña nueva, cerrar pestañas y todo lo demás que hace el botón central.",
        middleClickDragConflict: "El arrastre con tres dedos de macOS está activado y usa este mismo gesto. Desactívalo en Ajustes del Sistema, en Accesibilidad, Control del puntero, Opciones del trackpad, y el clic central funcionará.",
        middleClickTapPicker: "Un toque ligero también hace clic",
        middleClickTapOff: "Desactivado",
        middleClickTapThreeFingers: "3 dedos",
        middleClickTapFourFingers: "4 dedos",
        middleClickTapCaption: "Un toque ligero con ese número de dedos, sin presionar, también dispara el clic central. Deslizar nunca cuenta. Si el toque con tres dedos de macOS está asignado a Consultar, desactívalo para que no se disparen juntos.",
        quickToolsTab: "Panel rápido",
        quickToolShortcutToggle: "Atajo global",
        ocrName: "Copiar texto de la pantalla",
        ocrCaption: "Selecciona un área de la pantalla y el texto reconocido se copia, listo para pegar.",
        ocrCopied: "Texto copiado",
        ocrNoText: "No se encontró texto",
        colorPickerName: "Cuentagotas de color",
        colorPickerCaption: "Captura el color de cualquier píxel de la pantalla y cópialo en tu formato preferido.",
        colorPickerFormatLabel: "Formato copiado",
        colorPickerBareHexToggle: "Copiar sin el prefijo #",
        colorPickerPickNow: "Capturar color",
        micMuteName: "Silenciar micrófono",
        micUnmuteName: "Reactivar micrófono",
        micMuteCaption: "Corta el micrófono del Mac con un clic o atajo, en cualquier app.",
        micMutedHUD: "Micrófono silenciado",
        micUnmutedHUD: "Micrófono reactivado",
        micMuteMenuBarToggle: "Mostrar en la barra de menús mientras está silenciado",
        micMuteMenuBarCaption: "Un micrófono tachado en rojo aparece junto al icono de la app en la barra de menús.",
        pastePlainName: "Pegar como texto sin formato",
        pastePlainCaption: "Pega lo copiado sin colores, fuentes ni formato. El original se mantiene en el portapapeles.",
        launcherName: "Panel rápido",
        launcherCaption: "Un panel flotante con tus herramientas favoritas, invocado con un atajo desde cualquier lugar.",
        launcherOpenNow: "Abrir panel rápido",
        launcherEditHint: "Usa el botón de ajustes para elegir, ocultar y arrastrar las herramientas.",
        launcherEmptyState: "Todas las herramientas están ocultas. Usa el botón de ajuste para recuperarlas.",
        launcherAddSection: "Añadir de nuevo",
        launcherKeysHint: "Las flechas navegan, Enter abre, 1 a 9 abren directo",
        switcherSection: "Selector de apps",
        switcherEnable: "Usar el selector de Vorssaint",
        switcherEnableCaption: "Cambia entre apps y ventanas, incluidas las minimizadas y varias ventanas de la misma app.",
        switcherUsageHint: "Mantén el atajo para navegar; suelta para activar la ventana. Mayúsculas o ← retrocede; W cierra la ventana; Q cierra la app; Esc cancela.",
        switcherNoWindows: "No hay ventanas abiertas",
        switcherIconRowMode: "Mostrar %@ con iconos grandes",
        switcherIconRowModeCaption: "Muestra un icono por app con las vistas previas de sus ventanas arriba.",
        switcherSimpleMode: "Selector de apps sencillo",
        switcherSimpleModeCaption: "Muestra iconos de apps y títulos de ventanas, sin vistas previas ni captura de pantalla por el selector.",
        switcherShortcutHintApps: "Apps",
        switcherShortcutHintWindows: "Ventanas",
        switcherWindowShortcutCaption: "Abre un selector de las ventanas de la app en primer plano. Con el selector de apps abierto, salta entre las ventanas de la app seleccionada.",
        switcherTakeOverSystemShortcuts: "Reemplazar ⌘Tab y ⌘` de macOS",
        switcherTakeOverSystemShortcutsCaption: "Desactiva los atajos correspondientes de macOS solo mientras el selector de Vorssaint está activo. Todas las apps abiertas siguen accesibles.",
        switcherAppearanceDelay: "Retardo de aparición",
        switcherAppearanceDelayCaption: "Cuánto tiempo debe mantenerse pulsado el atajo antes de que aparezca el selector.",
        switcherMergeTabs: "Mostrar una entrada por app",
        switcherMergeTabsCaption: "Agrupa todas las ventanas de una app en una sola entrada del selector, en vez de una por ventana.",
        switcherWindowlessApps: "Apps sin ventanas abiertas",
        switcherWindowlessAppsCaption: "Elige qué apps abiertas sin ninguna ventana aparecen en el selector.",
        switcherWindowlessAppsOff: "No mostrar",
        switcherWindowlessAppsFinder: "Solo Finder",
        switcherWindowlessAppsAll: "Todas las apps",
        switcherNoOpenWindow: "Sin ventanas abiertas",
        switcherOtherDesktop: "Otro escritorio",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Previsualizar ventanas en el Dock",
        dockPreviewEnableCaption: "Pasa el cursor sobre una app abierta en el Dock para ver sus ventanas y haz clic en la que quieras abrir.",
        dockPreviewBackgroundOpacity: "Fondo del panel",
        dockPreviewBackgroundOpacityCaption: "Bájalo para ver más de lo que hay detrás del panel.",
        dockPreviewOpenDelay: "Retardo de apertura",
        dockPreviewOpenDelayCaption: "Cuánto tiempo debe reposar el puntero sobre un icono antes de que se abra el panel.",
        dockPreviewQuitAppOnClose: "Salir de la app con el botón ×",
        dockPreviewQuitAppOnCloseCaption: "En Dock Preview, × cierra toda la app en lugar de cerrar solo esa ventana.",
        dockClickMinimize: "Clic en el Dock para minimizar",
        dockClickMinimizeCaption: "Las ventanas de la app activa se minimizan al hacer clic en su icono del Dock. Vuelve a hacer clic para recuperarlas.",
        dockClickCycleWindows: "Clic en el Dock para alternar ventanas",
        dockClickCycleWindowsCaption: "Haz clic en el icono del Dock de la app activa para rotar entre sus ventanas, como ⌘`.",
        dockPreviewActiveNow: "Activo en el Dock",
        dockPreviewDockUnavailable: "No se pudieron leer los ítems del Dock.",
        dockPreviewAutohideBeta: "Beta. Puedes encontrar algunos errores.",
        dockPreviewOpenWindow: "Abrir ventana",
        dockPreviewCloseWindow: "Cerrar ventana",
        dockPreviewMinimizeWindow: "Minimizar ventana",
        dockPreviewRestoreWindow: "Restaurar ventana",
        dockPreviewPinPanel: "Fijar vista previa",
        dockPreviewUnpinPanel: "Soltar vista previa",
        dockPreviewPinned: "Fijado",
        dockPreviewClosePanel: "Cerrar vista previa",
        dockPreviewPreviousWindow: "Ventana anterior",
        dockPreviewNextWindow: "Siguiente ventana",

        cutPasteName: "Cortar y pegar",
        cutPasteEnable: "Cortar y pegar archivos en el Finder",
        cutPasteEnableCaption: "Usa ⌘X para cortar y ⌘V para mover archivos y carpetas en el Finder.",
        cutPasteShowHUD: "Mostrar panel flotante",
        cutPasteShowHUDCaption: "Muestra un indicador flotante con los archivos cortados mientras el Finder está activo.",
        cutPasteHowTitle: "Cómo se usa",
        cutPasteStep1: "Selecciona ítems en el Finder y pulsa ⌘X para cortarlos.",
        cutPasteStep2: "Abre la carpeta de destino y pulsa ⌘V para moverlos allí.",
        cutPasteTextNote: "En los campos de texto (como al renombrar), ⌘X y ⌘V siguen funcionando con normalidad.",
        cutPasteActiveNow: "Listo para cortar en el Finder",
        cutPasteAutomationNote: "La primera vez, macOS pide permiso para controlar el Finder.",
        cutReadyTitle: "Cortado",
        cutReadyHint: "en la carpeta de destino para mover",
        cutCancel: "Cancelar corte",
        cutDoneTitle: "¡Movido!",
        cutMovedSingular: "1 ítem movido",
        cutMovedPluralFormat: "%d ítems movidos",
        cutSomeFailed: "Algunos ítems no se pudieron mover",
        cutMovingTitle: "Moviendo…",
        cutMovingCountFormat: "%d de %d",

        autoQuitName: "Salir al cerrar",
        autoQuitEnable: "Salir de una app al cerrar su última ventana",
        autoQuitEnableCaption: "Cerrar la última ventana de una app también la cierra.",
        autoQuitActiveNow: "Activo ahora",
        autoQuitHowTitle: "Cómo funciona",
        autoQuitStep1: "Cierra la última ventana de una app (⌘W o el botón rojo).",
        autoQuitStep2: "La app se cierra sola. Los diálogos “¿Guardar cambios?” siguen apareciendo.",
        autoQuitPredictableNote: "Las apps que normalmente funcionan sin ventana nunca se cierran.",
        autoQuitExceptionsTitle: "Excepciones",
        autoQuitExceptionsCaption: "Las apps de esta lista permanecen abiertas aunque no tengan ventanas.",
        autoQuitExceptionsEmpty: "Sin excepciones",
        autoQuitAddApp: "Añadir app…",

        uninstallerName: "Desinstalador",
        uninstallerEnableCaption: "Elimina una app junto con las cachés, preferencias, registros y restos que deja atrás.",
        uninstallerStep1: "Arrastra una app a Ajustes o elige una de la lista.",
        uninstallerStep2: "Revisa los archivos encontrados y cuánto espacio ocupan.",
        uninstallerStep3: "Mueve a la Papelera lo que quieras. Nada se elimina de forma permanente.",
        uninstallerMenuItem: "Desinstalar una app…",
        uninstallerDropTitle: "Arrastra una app aquí",
        uninstallerDropSubtitle: "o elige una para analizar",
        uninstallerChoose: "Elegir app…",
        uninstallerPickerTitle: "Elegir app",
        uninstallerPickerSearch: "Buscar apps",
        uninstallerPickerEmpty: "No se encontraron apps",
        uninstallerEmptyNote: "No se elimina nada sin tu confirmación.",
        uninstallerFDANote: "Concede Acceso total al disco para un análisis más exhaustivo.",
        uninstallerFDAGrant: "Conceder acceso…",
        uninstallerFDAHint: "Activa Vorssaint en la lista. Si no aparece, haz clic en + y elige Vorssaint en Aplicaciones. El acceso solo se aplica después de volver a abrir la app.",
        uninstallerFDARelaunch: "Reabrir ahora",
        uninstallerScanning: "Analizando archivos…",
        uninstallerRemoving: "Moviendo a la Papelera…",
        uninstallerFoundTitle: "encontrado",
        uninstallerSelectedFormat: "%d de %d seleccionados",
        uninstallerRemove: "Mover a la Papelera",
        uninstallerCancel: "Cancelar",
        uninstallerDoneTitle: "¡Listo!",
        uninstallerFreedFormat: "%@ recuperados",
        uninstallerSomeFailed: "Algunos ítems no se pudieron mover a la Papelera.",
        uninstallerFailedNeedsFDA: "Los datos de apps en zona protegida solo se pueden mover con Acceso total al disco. La contraseña de administrador no lo sustituye.",
        uninstallerFailedMoreFormat: "y %d más",
        uninstallerAnother: "Desinstalar otra",
        uninstallerCatApp: "Aplicación",
        uninstallerCatSupport: "Soporte",
        uninstallerCatCaches: "Cachés",
        uninstallerCatPreferences: "Preferencias",
        uninstallerCatContainers: "Contenedores",
        uninstallerCatLogs: "Registros",
        uninstallerCatState: "Estado guardado",
        uninstallerCatOther: "Otros",

        urlCleanerName: "Limpiar URL",
        urlCleanerEnable: "Limpiar URL al copiarlas",
        urlCleanerEnableCaption: "Elimina los parámetros de rastreo de un enlace en cuanto llega al portapapeles.",
        urlCleanerActiveNow: "Activo ahora",
        urlCleanerManualTitle: "Limpiar ahora",
        urlCleanerInputPlaceholder: "Pega una URL",
        urlCleanerOutputPlaceholder: "La URL limpia aparece aquí",
        urlCleanerCleanButton: "Limpiar",
        urlCleanerPasteButton: "Pegar",
        urlCleanerCopyButton: "Copiar",
        urlCleanerClearButton: "Limpiar campo",
        urlCleanerNoURL: "Pega una URL válida.",
        urlCleanerNoChange: "Nada que limpiar.",
        urlCleanerCleaned: "URL limpia.",
        urlCleanerCopied: "Copiado.",
        urlCleanerLocalNote: "Local. Sin red.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Busca, instala y elimina fórmulas y casks.",
        homebrewMissingTitle: "No se encontró Homebrew",
        homebrewMissingBody: "Vorssaint puede abrir Terminal con el instalador oficial de Homebrew. Terminal muestra los pasos y pide tu contraseña si hace falta.",
        homebrewInstallHomebrew: "Instalar Homebrew",
        homebrewInstallHomebrewCaption: "Cuando termine en Terminal, vuelve aquí y pulsa Actualizar.",
        homebrewInstallHomebrewOpened: "Instalador abierto en Terminal.",
        homebrewShellSetupTitle: "Finalizar configuración de Terminal",
        homebrewShellSetupBody: "Homebrew está instalado, pero Terminal quizá aún no encuentre el comando brew. Vorssaint puede abrir Terminal con el comando de configuración.",
        homebrewShellSetupButton: "Configurar Terminal",
        homebrewShellSetupOpened: "Comando abierto en Terminal. Luego vuelve aquí y pulsa Actualizar.",
        homebrewRefresh: "Actualizar",
        homebrewCheckPackages: "Comprobar paquetes",
        homebrewTrustTitle: "Tap aún no es de confianza",
        homebrewTrustCaption: "Homebrew ahora pide tu confirmación antes de usar taps de terceros. Confía en %@ para continuar.",
        homebrewTrustButton: "Confiar y continuar",
        homebrewSearchPlaceholder: "Buscar paquetes",
        homebrewKeyboardHint: "Espacio o Retorno cierra el panel de macOS. Usa el botón de búsqueda.",
        homebrewSearchButton: "Buscar",
        homebrewSearchResults: "Resultados",
        homebrewInstalled: "Instalados",
        homebrewAll: "Todos",
        homebrewFormulas: "Fórmulas",
        homebrewCasks: "Casks",
        homebrewNoPackages: "No se encontraron paquetes",
        homebrewNoSelection: "Selecciona un paquete instalado o busca uno nuevo.",
        homebrewDetailsTitle: "Detalles del paquete",
        homebrewInstall: "Instalar",
        homebrewUninstall: "Desinstalar",
        homebrewUpgrade: "Actualizar",
        homebrewUpgradeAll: "Actualizar todo",
        homebrewUpdateHomebrew: "Actualizar Homebrew",
        homebrewAllPackages: "paquetes",
        homebrewOpenTerminal: "Abrir Terminal",
        homebrewCancelOperation: "Cancelar",
        homebrewClearLog: "Borrar registro",
        homebrewLogTitle: "Registro",
        homebrewVersion: "Versión",
        homebrewDescription: "Tipo",
        homebrewHomepage: "Abrir sitio web",
        homebrewPopularity: "Popularidad",
        homebrewPopularityFormat: "%@ instalaciones en %@ días",
        homebrewInstalledBadge: "Instalado",
        homebrewNotInstalledBadge: "No instalado",
        homebrewUpdates: "Actualizaciones",
        homebrewUpdateAvailableBadge: "Actualización disponible",
        homebrewLatestVersion: "Más reciente",
        homebrewConfirmInstallTitle: "¿Instalar con Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew descargará e instalará %@. También puede instalar dependencias.",
        homebrewConfirmUninstallTitle: "¿Desinstalar con Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew desinstalará %@. Los archivos de configuración pueden permanecer en el sistema.",
        homebrewConfirmUpgradeTitle: "¿Actualizar con Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew descargará y aplicará la versión más reciente de %@. También puede actualizar dependencias.",
        homebrewConfirmUpgradeAllTitle: "¿Actualizar todo con Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew descargará y aplicará las versiones más recientes de los paquetes con actualizaciones disponibles. También puede actualizar dependencias.",
        homebrewConfirmUpdateHomebrewTitle: "¿Actualizar Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew buscará la información más reciente y después recargará tus paquetes.",
        homebrewTerminalFallback: "Esta operación necesita Terminal para pedir la contraseña de administrador. Vorssaint no captura contraseñas.",
        homebrewLoading: "Cargando…",
        homebrewSearchEmpty: "Sin resultados",
        homebrewOperationInstallFormat: "Instalando %@",
        homebrewOperationUninstallFormat: "Desinstalando %@",
        homebrewOperationUpgradeFormat: "Actualizando %@",
        homebrewOperationUpgradeAll: "Actualizando paquetes",
        homebrewOperationUpdateHomebrew: "Actualizando Homebrew",
        homebrewOperationInstalledFormat: "%@ instalado.",
        homebrewOperationUninstalledFormat: "%@ desinstalado.",
        homebrewOperationUpgradedFormat: "%@ actualizado.",
        homebrewOperationUpgradedAll: "Paquetes actualizados.",
        homebrewOperationUpdatedHomebrew: "Homebrew actualizado.",
        homebrewOperationFailedFormat: "No se pudo completar %@.",
        homebrewOperationCancelled: "Operación cancelada.",
        homebrewOperationPreparing: "Preparando…",
        homebrewOperationDownloading: "Descargando archivos…",
        homebrewOperationInstalling: "Instalando archivos…",
        homebrewOperationUninstalling: "Eliminando archivos…",
        homebrewOperationUpgrading: "Actualizando archivos…",
        homebrewOperationFinalizing: "Finalizando…",
        homebrewOperationRefreshing: "Actualizando lista…",
        homebrewOperationTerminal: "Continúa en Terminal.",
        homebrewOperationElapsedFormat: "%@ transcurridos",
        homebrewOperationShowDetails: "Mostrar detalles",
        homebrewOperationHideDetails: "Ocultar detalles",
        homebrewOperationTechnicalLog: "Detalles técnicos",
        homebrewOperationProgressUnknown: "Homebrew aún no informó un porcentaje.",

        mediaName: "Media",
        mediaEnableCaption: "Comprime videos, convierte y procesa imágenes, crea GIFs y extrae texto localmente.",
        mediaLocalNote: "Local. Sin red.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Imagen",
        mediaToolText: "Texto",
        mediaSelectFile: "Elegir archivo",
        mediaDropHint: "Arrastra un archivo aquí o haz clic para elegir.",
        mediaOutput: "Salida",
        mediaOutputAutomatic: "Automática",
        mediaChooseOutput: "Destino",
        mediaStartVideo: "Comprimir video",
        mediaStartGIF: "Crear GIF",
        mediaStartImage: "Procesar imagen",
        mediaStartConvertPDF: "Convertir a PDF",
        mediaStartText: "Extraer texto",
        mediaCancel: "Cancelar",
        mediaStartTime: "Inicio",
        mediaEndTime: "Fin",
        mediaQuality: "Compresión",
        mediaCompressionLow: "Baja",
        mediaCompressionMedium: "Media",
        mediaCompressionHigh: "Alta",
        mediaMaxSize: "Tamaño",
        mediaSizingResolution: "Resolución",
        mediaSizingFileSize: "Tamaño del archivo",
        mediaTargetSize: "Tamaño objetivo",
        mediaTargetSizeHint: "La resolución se ajusta para no superar el límite.",
        mediaErrorTargetTooSmall: "Tamaño objetivo demasiado pequeño para este clip. Recórtalo o aumenta el límite.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Ancho",
        mediaFPS: "FPS",
        mediaKeepAudio: "Mantener audio",
        mediaCodec: "Códec",
        mediaFormat: "Formato",
        mediaStripMetadata: "Quitar metadatos",
        mediaLoopGIF: "Repetir GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Preciso",
        mediaOCRFast: "Rápido",
        mediaLanguageCorrection: "Corrección de idioma",
        mediaTextOutputNote: "El texto extraído se puede copiar y guardar como TXT.",
        mediaRunning: "Procesando",
        mediaCompleted: "Listo",
        mediaCancelled: "Cancelado.",
        mediaOpenInFinder: "Mostrar",
        mediaCopyText: "Copiar texto",
        mediaRunAgain: "Ejecutar otra vez",
        mediaEmptyText: "No se encontró texto.",
        mediaResultSavedFormat: "Guardado como %@",
        mediaResultSizeFormat: "%@ a %@",
        mediaResultGrewCaption: "El archivo convertido quedó más grande que el original.",
        mediaErrorNoFile: "Elige un archivo primero.",
        mediaErrorNoVideo: "Este archivo no tiene pista de video.",
        mediaErrorSameOutput: "Elige un destino distinto del archivo original.",
        mediaErrorUnsupported: "Formato no compatible con macOS.",

        shelfName: "Estante",
        shelfEnable: "Área temporal para arrastrar archivos",
        shelfEnableCaption: "Un espacio flotante para reunir archivos, imágenes y texto, y luego arrastrarlos a cualquier sitio.",
        shelfHowTitle: "Cómo se usa",
        shelfStep1: "Ábrelo con el atajo o agitando el ratón durante un arrastre.",
        shelfStep2: "Suelta sobre él archivos, imágenes, enlaces o texto para guardarlos.",
        shelfStep3: "Arrastra cada ítem de vuelta a cualquier app cuando lo necesites.",
        shelfShakeToggle: "Abrir agitando el ratón al arrastrar",
        shelfShakeCaption: "Agita el puntero rápidamente mientras sostienes un ítem para que aparezca cerca del cursor.",
        shelfDropZoneToggle: "Mantener en la barra de menús los archivos arrastrados",
        shelfDropZoneCaption: "Mientras arrastras un archivo, el estante aparece debajo del icono de la barra de menús. Lo que sueltes se guarda ahí mismo, en un botón que contraes y abres con un clic y que desaparece cuando el estante se vacía.",
        shelfDropZoneLabel: "Suelta aquí",
        shelfCollapse: "Contraer",
        shelfBehaviorTitle: "Después de usar",
        shelfCloseAfterDrop: "Cerrar después de soltar en otra app",
        shelfCloseAfterDropCaption: "Cierra el estante cuando el destino acepta los ítems. El alfiler del panel lo mantiene abierto.",
        shelfRemoveAfterDrop: "Quitar ítems después de soltarlos",
        shelfRemoveAfterDropCaption: "Los ítems aceptados por otra app salen del estante. Desactívalo para conservar una copia.",
        shelfExclusionsTitle: "Excepciones automáticas",
        shelfExclusionsEmpty: "No se añadieron apps.",
        shelfExclusionsCaption: "Agitar y la zona de la barra de menús no se activan en arrastres iniciados en estas apps. El atajo y Abrir ahora siguen funcionando.",
        shelfPin: "Mantener abierto",
        shelfUnpin: "Permitir cerrar después de usar",
        extraBrightnessName: "Brillo extra",
        extraBrightnessCaption: "Usa la reserva HDR de la pantalla para superar el brillo máximo. Consume más batería y el Mac puede calentarse.",
        extraBrightnessLevelLabel: "Intensidad",
        extraBrightnessUnsupported: "Disponible solo en pantallas XDR, como las del MacBook Pro de 14 y 16 pulgadas.",
        shelfHotkeyLabel: "Atajo",
        shelfOpenNow: "Abrir ahora",
        shelfNoPermission: "No requiere ningún permiso.",
        shelfMenuItem: "Abrir el estante",
        shelfTitle: "Estante",
        shelfEmpty: "Arrastra ítems aquí",
        shelfClearAll: "Borrar todo",
        shelfRemoveSelected: "Quitar seleccionados",
        shelfSelectedFormat: "%d seleccionados",
        shelfHint: "Haz clic para seleccionar. Arrastra para usar o haz clic derecho para ver más acciones.",
        shelfItemImage: "Imagen",
        shelfTooltipItemsFormat: "%d elementos",
        shelfTooltipItemsFew: "%d elementos",
        shelfTooltipImageSingular: "%d imagen",
        shelfTooltipImageFew: "%d imágenes",
        shelfTooltipImagePlural: "%d imágenes",
        shelfTooltipFileSingular: "%d archivo",
        shelfTooltipFileFew: "%d archivos",
        shelfTooltipFilePlural: "%d archivos",
        shelfTooltipNoteSingular: "%d nota",
        shelfTooltipNoteFew: "%d notas",
        shelfTooltipNotePlural: "%d notas",
        shelfTooltipLinkSingular: "%d enlace",
        shelfTooltipLinkFew: "%d enlaces",
        shelfTooltipLinkPlural: "%d enlaces",
        shelfActionOpen: "Abrir",
        shelfActionOpenWith: "Abrir con",
        shelfActionShare: "Compartir",

        breakdownMeasuring: "Midiendo…",

        mixerSection: "Mezclador de volumen",
        mixerEmpty: "Las apps que usan audio aparecen aquí",
        mixerUnavailable: "Disponible en macOS 14.4 y posteriores",
        mixerPermissionBody: "Para ajustar el volumen por app, permite “Grabación de pantalla y audio del sistema” en Ajustes del Sistema. El audio nunca se graba.",
        mixerResetTooltip: "Restablecer al 100 %",
        mixerOutputDefault: "Predeterminado",
        mixerOutputCurrent: "actual",
        mixerOutputUnavailable: "Salida no disponible",
        mixerOutputFallback: "Usando la predeterminada hasta que vuelva este dispositivo.",
        mixerBypassedCaption: "Esta app gestiona su propio audio.",
        mixerOutputTooltip: "Elegir salida",
        mixerSystemOutputTitle: "Salida",
        mixerSystemOutputNoDevices: "No se encontró ninguna salida",
        mixerSystemOutputTooltip: "Elegir salida del sistema",
        mixerSystemOutputErrorFormat: "No se pudo cambiar: %@",
        mixerLowerOnHeadphonesDisconnect: "Bajar volumen al desconectar auriculares",
        mixerLowerOnHeadphonesDisconnectCaption: "Ajusta la salida cuando se desconectan auriculares con cable o Bluetooth.",
        mixerHeadphonesDisconnectVolume: "Volumen al desconectar",
        preciseVolumeRollerEnable: "Usar pasos de volumen más finos",
        preciseVolumeRollerCaption: "Convierte ruedas y teclas de volumen en pasos más pequeños del sistema.",
        preciseVolumeRollerTapFailed: "No se pudo escuchar las teclas de volumen.",
        soundOutputSwitcherTitle: "Selector de salida",
        soundOutputSwitcherEnable: "Cambiar salidas con atajo",
        soundOutputSwitcherCaption: "Elige salidas y usa el atajo para pasar a la siguiente disponible.",
        soundOutputSwitcherDevices: "Salidas en el ciclo",
        soundOutputSwitcherNoAvailableSelection: "Selecciona al menos una salida disponible.",
        mixerInputTitle: "Micrófono",
        mixerInputNoDevices: "No se encontró ningún micrófono",
        mixerInputUnavailable: "Micrófono no disponible",
        mixerInputFallback: "Usando el predeterminado hasta que vuelva este micrófono.",
        mixerInputTooltip: "Elegir micrófono",
        mixerInputErrorFormat: "No se pudo cambiar: %@",
        mixerVisibleApps: "Apps en la lista",
        mixerAllShown: "Todas",
        mixerHiddenCountLabel: "Ocultas",
        mixerHideFromList: "Ocultar de la lista",

        updatesSection: "Actualizaciones",
        autoCheckToggle: "Buscar actualizaciones automáticamente",
        includeBetaUpdatesToggle: "Recibir actualizaciones beta",
        includeBetaUpdatesCaption: "Las versiones beta incluyen funciones en desarrollo y pueden contener errores o estar incompletas.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Buscar ahora",
        updateChecking: "Buscando…",
        updateUpToDate: "Tienes la última versión.",
        updateAvailablePrefix: "Actualización disponible:",
        updateInstallButton: "Descargar e instalar",
        updateDownloading: "Descargando la actualización…",
        updateInstalling: "Instalando y reiniciando…",
        updateFailedPrefix: "No se pudo comprobar:",
        updateLastChecked: "Última comprobación:",
        updateNotifyTitle: "Actualización de Vorssaint",
        updateInstallFailedBody: "La actualización se descargó pero no se pudo aplicar. Descarga la última versión desde la página de releases de GitHub y arrastra la app sobre la actual.",
        updateNeedsApplicationsTitle: "Mueve Vorssaint a Aplicaciones",
        updateNeedsApplicationsBody: "La app se está ejecutando desde un lugar que no se puede actualizar, como la imagen de disco o una ubicación temporal del sistema. Arrastra Vorssaint a la carpeta Aplicaciones, ábrela desde ahí y vuelve a intentarlo.",
        menuCheckUpdates: "Buscar actualizaciones…",

        permissionRequired: "Permiso necesario",
        permissionAccessibility: "Accesibilidad",
        permissionScreenRecording: "Grabación de pantalla",
        permissionGranted: "Concedido",
        permissionMissing: "No concedido",
        permissionOpenSettings: "Abrir Ajustes del Sistema…",
        permissionRequest: "Conceder acceso",
        permissionRestartNote: "macOS puede pedir que vuelvas a abrir la app tras concederlo.",

        aboutDescription: "Un centro de utilidades para tu Mac.\nEnergía, monitor del sistema, desplazamiento y un selector de ventanas, directamente en la barra de menús.",
        versionPrefix: "Versión",
        reviewIntro: "Ver la introducción",
        reviewHighlights: "Ver novedades de la versión",
        viewOnGitHub: "Ver en GitHub",

        obContinue: "Continuar",
        obBack: "Atrás",
        obSkipStep: "Omitir este paso",
        obStart: "Abrir Vorssaint",
        obStepWelcomeTitle: "Te damos la bienvenida a Vorssaint",
        obStepWelcomeBody: "Una utilidad discreta en la barra de menús que hace que el día a día con macOS sea más práctico.",
        obWelcomeBullet1Title: "Energía bajo control",
        obWelcomeBullet1Body: "Mantén el Mac activo todo el tiempo que quieras, incluso con la tapa cerrada.",
        obWelcomeBullet2Title: "Una visión clara del sistema",
        obWelcomeBullet2Body: "Temperaturas de CPU, GPU y batería, uso del hardware y presión de memoria en tiempo real.",
        obWelcomeBullet3Title: "El ratón y las ventanas a tu manera",
        obWelcomeBullet3Body: "Desplazamiento invertido del ratón y un selector de ventanas con miniaturas.",
        obLanguageLabel: "Idioma",
        obStepAccessibilityTitle: "Accesibilidad",
        obStepAccessibilityBody: "Necesaria para invertir el desplazamiento del ratón y para que el selector de ventanas responda al teclado.",
        obAccessibilityWhy: "La app solo observa la rueda del ratón y el atajo del selector. No se graba ni se envía nada a ningún sitio.",
        obStepRecordingTitle: "Grabación de pantalla",
        obStepRecordingBody: "Permite que el selector muestre miniaturas reales de las ventanas en lugar de solo iconos.",
        obRecordingWhy: "Las miniaturas se generan al momento, permanecen en la memoria y nunca salen de tu Mac. Sin ella, el selector funciona con iconos.",
        obStepMonitorTitle: "Monitor del sistema",
        obStepMonitorBody: "El panel muestra las temperaturas de CPU, GPU y batería, el uso del hardware y la presión de memoria.",
        obMonitorNoPermission: "No necesita permiso. Los sensores se leen directamente del sistema.",
        obStepOptionalTitle: "Funciones opcionales",
        obStepOptionalBody: "Activa ahora las que quieras usar. Todo se puede cambiar más tarde en Ajustes.",
        obStepStatusTitle: "Comprobación",
        obStepStatusBody: "Asegúrate de que todo está listo para las funciones que quieres usar.",
        obStatusRecheck: "Comprobar de nuevo",
        obStepDoneTitle: "¡Todo listo!",
        obStepDoneBody: "Vorssaint ya está cuidando de tu Mac.",
        obDoneHint: "Busca el agujero negro en la barra de menús, en la esquina superior derecha de la pantalla.",
        obWhatsNewTitle: "Novedades de esta versión",
        obWhatsNewFallback: "Esta actualización incluye las correcciones y mejoras más recientes.",
        obLanguageUpdateTitle: "Ahora en tu idioma",
        obLanguageUpdateBody: "Vorssaint ahora habla varios idiomas. Elige el que quieras usar; puedes cambiarlo cuando quieras en Ajustes.",
        obPurposeTitle: "¿Qué te trae por aquí?",
        obPurposeBody: "Elige una configuración lista o exactamente las funciones que quieres usar.",
        obPurposeSkip: "Puedes añadir o quitar funciones después en Ajustes.",

        tabMonitor: "Monitor",
        monitorMenuBarSection: "En la barra de menús",
        monitorMenuBarCaption: "Elige qué aparece junto al icono en la barra de menús.",
        monitorCombineTemperatures: "Combinar uso y temperatura",
        monitorCombineTemperaturesCaption: "Cuando el uso y la temperatura del mismo elemento estén activos, se muestran en un solo bloque.",
        monitorSeparateMenuBarMetrics: "Separar métricas en elementos propios",
        monitorSeparateMenuBarMetricsCaption: "Separa los bloques activos en la barra de menús y mantiene uso y temperatura juntos cuando combinar está activo.",
        monitorNetworkUploadFirst: "Subida encima de descarga",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Memoria",
        monitorShowNetwork: "Red",
        monitorShowPowerLabel: "Energía",
        monitorIntervalLabel: "Actualizar cada",
        monitorInterval1: "1 segundo",
        monitorInterval2: "2 segundos",
        monitorInterval5: "5 segundos",
        monitorPanelSection: "En el panel",
        panelNavigationMode: "Navegar por secciones en el panel",
        panelNavigationCaption: "Muestra una sección a la vez. Elige Lista para ver todo en un desplazamiento continuo.",
        panelFooterSections: "Secciones",
        panelFooterList: "Lista",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Puedes encontrar algunos errores.",

        networkSection: "Red",
        networkDownload: "Descarga",
        networkUpload: "Subida",
        networkThisSession: "En esta sesión",
        networkMeasuring: "Midiendo…",
        networkApps: "Apps usando red",
        networkAppsIdle: "Ninguna app usa la red ahora",

        diskSection: "Discos",
        diskUsed: "usado",
        diskFree: "libre",
        diskAvailable: "disponible",
        diskPurgeable: "purgable",
        diskInternal: "Interno",
        diskExternal: "Externo",
        diskSelect: "Seleccionar disco",
        diskRead: "Lectura",
        diskWrite: "Escritura",
        diskSMARTStatus: "Estado",
        diskSMARTUnavailable: "SMART no disponible para este disco",
        diskTotalRead: "Total leído",
        diskTotalWritten: "Total escrito",
        diskTemperature: "Temperatura",
        diskHealth: "Salud",
        diskPowerCycles: "Ciclos",
        diskPowerOnHours: "Horas encendido",
        diskUnsafeShutdowns: "Apagados inseguros",
        diskMediaErrors: "Errores de medio",
        diskEject: "Expulsar",
        diskEjectAll: "Expulsar todos",
        diskEjecting: "Expulsando…",
        diskReadyToRemove: "Listo para retirar",
        diskEjectFailed: "No se pudo expulsar",
        diskProtectionCaption: "Expulsa antes de desconectar.",
        diskNoExternal: "No hay discos externos listos para expulsar.",
        diskOpenInFinder: "Abrir",
        diskStorageSettings: "Almacenamiento",
        diskNoDisks: "No se encontraron discos montados.",

        powerSection: "Energía",
        powerSystem: "Sistema",
        powerAdapter: "Adaptador",
        powerBattery: "Batería",
        powerCharging: "Cargando",
        powerOnBattery: "Con batería",
        powerPluggedIn: "Enchufado",
        powerUnavailable: "Métricas de energía no disponibles en este Mac",
        powerAdapterMaxFormat: "%@ máx.",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Temperatura de CPU",
        monitorShowGPUTemperature: "Temperatura de GPU",
        monitorShowBatteryTemperature: "Temperatura de batería",
        monitorShowPeripheralBattery: "Batería de periféricos",
        peripheralBatteryNoDevices: "No se encontraron periféricos",
        monitorGraphsSection: "Gráficas",
        monitorGraphsCaption: "Elige qué métricas muestran una gráfica a lo largo del tiempo.",

        updateBannerTitle: "Actualización disponible",
        updateBannerAction: "Actualizar",
        obStepMenuBarTitle: "Métricas en la barra de menús",
        obStepMenuBarBody: "Elige qué mostrar junto al icono. La vista previa de arriba se actualiza en tiempo real.",
        obStepMenuBarNote: "Novedad: bloques de Red y Energía y gráficas en el panel. Ajústalo todo más tarde en Ajustes › Monitor.",
        monitorMenuBarPresetLabel: "Estilo",
        menuBarPresetReadable: "Legible",
        menuBarPresetDense: "Densa",
        menuBarSpacingLabel: "Espaciado en la barra",
        menuBarSpacingStandard: "Estándar",
        menuBarSpacingCompact: "Compacto",
        menuBarHideIconToggle: "Ocultar el icono de la app mientras se muestran métricas",
        menuBarHideIconCaption: "El icono vuelve solo cuando las métricas salen de la barra y cuando hay algo que avisar (una actualización lista o el micrófono silenciado).",
        monitorLabelStyleLabel: "Etiquetas",
        menuBarLabelStyleCompact: "Compactas",
        menuBarLabelStyleClassic: "Clásicas",
        monitorMemoryStyleLabel: "Mostrar la memoria como",
        monitorMemoryPressureDot: "Punto de presión",
        memoryStyleDot: "Punto",
        memoryStylePercent: "%",
        memoryStyleBoth: "Ambos",
        systemUptime: "Activo desde hace",
        batteryCharge: "Carga",
        powerHealth: "Salud de la batería",
        powerCycles: "Ciclos",
        speedTestRun: "Prueba de velocidad",
        speedTestAgain: "Probar de nuevo",
        speedTestLatency: "Latencia",
        speedTestTesting: "Probando…",
        speedTestFailed: "La prueba falló",

        monitorShowInPanel: "Mostrar en el panel",
        disclosureExpanded: "Expandido",
        disclosureCollapsed: "Contraído",
        panelHideItem: "Ocultar del panel",
        panelShowItem: "Mostrar en el panel",
        panelHiddenItem: "Oculto",
        monitorItemUptime: "Tiempo activo",
        monitorItemNetSpeed: "Velocidad en directo",
        monitorItemNetTotals: "Totales de la sesión",
        monitorItemNetTest: "Prueba de velocidad",
        monitorItemDiskUsage: "Uso del disco",
        monitorItemDiskActivity: "Actividad en directo",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Protección externa",
        monitorItemDiskTools: "Herramientas",
        monitorPanelConfigHint: "Abre un bloque para elegir qué muestra.",
        monitorOrderSection: "Orden de las secciones",
        monitorOrderHint: "Arrastra para reordenar las secciones del panel y usa el ojo para mostrar u ocultar cada una.",
        obStepPanelTitle: "Qué aparece en el panel",
        obStepPanelBody: "Abre cada bloque y elige exactamente qué se muestra al hacer clic en el icono.",
        obStepPanelNavigationTitle: "Panel por secciones",
        obStepPanelNavigationBody: "El panel ahora puede mostrar una sección a la vez. Puedes cambiar entre Secciones y Lista en Ajustes.",

        cleaningMenuItem: "Modo de limpieza",
        utilitiesSection: "Utilidades",
        quickControlsSection: "Controles",
        panelCategoryWindows: "Ventanas",
        panelCategoryInput: "Ratón y teclado",
        panelCategoryFiles: "Archivos",
        windowMaximizeName: "Maximizar ventanas",
        windowMaximizeCaption: "El botón verde maximiza sin crear otro Espacio.",
        windowMaximizeActiveNow: "Botón verde activo",
        windowMaximizeNeedsAccessibility: "Necesita Accesibilidad para funcionar.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Filtrar teclas duplicadas",
        keyDebounceCaption: "Filtra pulsaciones duplicadas muy rápidas.",
        keyDebounceActiveNow: "Filtro activo",
        keyDebounceGlobalWindow: "Ventana global",
        keyDebouncePerKeySection: "Teclas específicas",
        keyDebouncePerKeyCaption: "Los valores por tecla sustituyen la ventana global. Usa 0 ms para no filtrar una tecla.",
        keyDebounceKeyLabel: "Tecla",
        keyDebounceWindowLabel: "Ventana",
        keyDebounceAddKey: "Añadir tecla",
        keyDebounceNoOverrides: "No hay teclas específicas configuradas.",
        keyDebounceRemoveKey: "Eliminar tecla",
        cleaningPanelCaption: "Bloquea el teclado para limpiar con seguridad.",
        cleaningOverlayTitle: "Teclado bloqueado para limpiar",
        cleaningOverlaySubtitle: "Pulsa Esc 5 veces para desbloquear",
        cleaningOverlayUnlock: "Desbloquear",
        cleaningOverlayMouseHint: "El ratón y el trackpad siguen funcionando",
        cleaningKeepScreenVisibleToggle: "Mantener la pantalla visible",
        cleaningKeepScreenVisibleCaption: "Muestra un indicador discreto en la esquina de la pantalla en lugar de oscurecer el contenido.",
        cleaningStartNow: "Bloquear el teclado ahora",
        cleaningNeedsAxTitle: "Se necesita Accesibilidad",
        cleaningNeedsAxBody: "Para bloquear el teclado de forma segura, Vorssaint necesita el permiso de Accesibilidad. Concédelo en Ajustes del Sistema e inténtalo de nuevo.",

        tabSupport: "Apoyar",
        shortcutsPageCaption: "Edita aquí todos los atajos globales de las funciones instaladas en este Mac. Los inactivos se guardan, pero no se ejecutan.",
        shortcutsPageTitle: "Atajos de teclado",
        settingsSearchPlaceholder: "Buscar en ajustes",
        donateHeading: "Ayuda a que Vorssaint siga creciendo",
        donateMessage: "Vorssaint es gratis, independiente y lo desarrollo en mi tiempo libre. Si quieres contribuir económicamente, Buy Me a Coffee ayuda directamente a mantener el desarrollo en marcha.",
        donateButton: "Apoyar en Buy Me a Coffee",
        donateThanks: "Gracias por estar aquí. 🖤",
        supportIntroTitle: "Ayuda a que Vorssaint siga creciendo",
        supportIntroMessage: "Si quieres apoyar económicamente el desarrollo, Buy Me a Coffee es el único lugar para hacerlo.",
        supportIntroStarButton: "Dar una estrella a Vorssaint en GitHub",
        supportIntroStarMessage: "Nunca se espera apoyo económico. Una estrella en GitHub ayuda a que más personas descubran Vorssaint y marca una diferencia real en su desarrollo.",
        supportIntroCoffeeButton: "Apoyar en Buy Me a Coffee",
        supportIntroLaterButton: "Ahora no",
        supportIntroDoneButton: "Listo",
        discordIntroTitle: "La comunidad de Vorssaint en Discord acaba de empezar",
        discordIntroMessage: "La comunidad de Vorssaint es nueva y todavía está tomando forma. Únete desde el principio para conocer a otros usuarios y ayudar a crear un espacio acogedor alrededor de la app.",
        discordIntroJoinButton: "Unirse a la comunidad en Discord",
        communityIntroTitle: "Míralo antes que nadie",
        communityIntroMessage: "Quienes ya me seguían en X vieron varios cambios de esta actualización antes que nadie. Allí publico avances de lo que viene y muestro cómo funciona, para que conozcas lo básico antes de que salga la actualización. Sígueme y descubre lo próximo.",
        communityIntroFollowButton: "Seguir a @vorssaint en X",
        homebrewOfficialIntroTitle: "Ahora en el catálogo oficial de Homebrew",
        homebrewOfficialIntroMessage: "Vorssaint ya se puede instalar directamente desde el catálogo oficial de Homebrew.",
        homebrewOfficialIntroInstallLabel: "Nueva instalación",
        homebrewOfficialIntroMigrationTitle: "¿Usabas el tap anterior?",
        homebrewOfficialIntroMigrationMessage: "Elimina el tap anterior una vez. La app y tus ajustes se conservan.",
        homebrewOfficialIntroCopyButton: "Copiar comando",
        updateShowcaseTitle: "Novedades de 3.1.4",
        updateShowcaseMessage: "Mira una vista previa rápida de las principales mejoras de esta actualización.",
        updateShowcaseUnavailable: "No se pudo cargar el video ahora. Puedes continuar igualmente.",
        updateShowcaseRestart: "Volver al inicio",
        showMenuBarIcon: "Mostrar el icono en la barra de menús",
        showMenuBarIconCaption: "Si el icono de Vorssaint desaparece (macOS puede ocultar iconos de la barra de menús cuando se queda sin espacio, algo habitual en Macs con notch), vuelve a abrir Vorssaint desde Aplicaciones o Spotlight: eso recrea el icono y, si sigue oculto, abre esta ventana.",
        menuBarIconStillHiddenTitle: "El icono sigue oculto",
        menuBarIconStillHiddenBody: "El icono se recreó, pero macOS no le dio un lugar visible. Probablemente la barra de menús se quedó sin espacio: quita algunos iconos de la barra (o cierra apps con menús largos) y vuelve a intentarlo.",
        menuBarIconManagerHintFormat: "%@ está abierto y puede estar guardando el icono en su sección oculta. Busca Vorssaint ahí, o configura %@ para mostrar siempre Vorssaint.",
        shortcutRecording: "Pulsa el nuevo atajo",
        shortcutReset: "Restablecer",
        shortcutNone: "Ninguno",
        shortcutClear: "Eliminar atajo",
        shortcutInvalid: "Usa al menos Control, Option o Command junto con una tecla.",
        shortcutPressKeys: "Pulsa teclas",
        shortcutEscapeHint: "Esc cancela.",
        shortcutDeleteHint: "Delete lo elimina.",
        shortcutNotCaptured: "No se capturó nada. macOS u otra app ya usa esa combinación. Prueba con otra.",
        shortcutConflictFormat: "Este atajo ya lo usa %@.",
        shortcutUnavailable: "macOS rechazó este atajo. Elige otro.",
        shelfShortcutToggle: "Atajo del estante",
        switcherUsageHintFormat: "Mantén %@ para navegar; suelta para activar la ventana. Mayúsculas o ← retrocede; W cierra la ventana; Q cierra la app; Esc cancela.",
        musicBlockSection: "Teclas multimedia",
        musicBlockTitle: "Evitar que Música se abra sola",
        musicBlockCaption: "La app Música deja de abrirse al pulsar las teclas multimedia. Sigue pudiendo abrirla tú.",
        musicBlockReplacementLabel: "Abrir en su lugar",
        musicBlockReplacementNone: "Ninguna",
        musicBlockChooseApp: "Elegir app…",
        cleanerName: "Limpieza",
        cleanerIntroTitle: "Limpia la basura del Mac",
        cleanerIntroCaption: "Busca restos de apps desinstaladas, cachés, registros y la Papelera. Revisas todo antes y lo eliminado va a la Papelera.",
        cleanerScan: "Analizar",
        cleanerScanning: "Analizando…",
        cleanerCleaning: "Limpiando…",
        cleanerCatLeftovers: "Restos de apps desinstaladas",
        cleanerCatLoginItems: "Ítems de inicio huérfanos",
        cleanerCatCaches: "Cachés",
        cleanerCatLogs: "Registros",
        cleanerCatDeveloper: "Basura de desarrollo",
        cleanerCatTrash: "Papelera",
        cleanerLeftoversNote: "Encontrados por análisis y sin marcar. Revisa la ruta antes de marcar.",
        cleanerLoginItemsNote: "La entrada en Ítems de inicio desaparece tras reiniciar el Mac.",
        cleanerTrashNote: "Vaciar la Papelera es permanente.",
        cleanerCatDeviceBackups: "Copias de iPhone",
        cleanerDeviceBackupsCaption: "Las copias antiguas de iPhone y iPad ocupan gran parte de lo que macOS llama Otros. Elimina solo las que ya no necesites; al conectar el aparato se crea una nueva.",
        cleanerNothingFound: "Nada que limpiar. Tu Mac está en orden.",
        cleanerClean: "Limpiar",
        cleanerDoneNote: "Los ítems fueron a la Papelera y pueden recuperarse desde ahí.",
        cleanerAgain: "Analizar de nuevo",
        cleanerRevealInFinder: "Mostrar en Finder",
        cleanerPanelCaption: "Restos de apps, cachés y registros",
        cleanerSafeSection: "Limpieza segura",
        cleanerOptionalSection: "Opcional, revisa antes",
        cleanerCatOtherCaches: "Otras cachés",
        cleanerCachesCaption: "Archivos temporales que las apps rehacen solas.",
        cleanerLogsCaption: "Registros antiguos de diagnóstico.",
        cleanerDeveloperCaption: "Restos de compilaciones y simuladores de Xcode.",
        cleanerLoginItemsCaption: "Entradas de inicio dejadas por apps que ya no existen.",
        cleanerLeftoversCaption: "Archivos dejados por apps que desinstalaste.",
        cleanerOtherCachesCaption: "Seguro de borrar, nada se rompe. Las apps pueden abrir más lento una vez y el contenido descargado, como música offline, se descarga de nuevo.",
        cleanerCleanSizeFormat: "Limpiar %@",
        cleanerScheduleTitle: "Limpieza automática",
        cleanerScheduleOff: "Desactivada",
        cleanerScheduleDaily: "Diaria",
        cleanerScheduleWeekly: "Semanal",
        cleanerScheduleCaption: "Limpia sola solo la parte segura a la hora elegida y envía todo a la Papelera.",
        cleanerScheduleLastFormat: "La última limpieza automática liberó %@.",
        cleanerAutoNotificationFormat: "%@ liberados y enviados a la Papelera.",
        cleanerScheduleNextFormat: "Próxima limpieza %@.",
        cleanerScheduleRanFormat: "Última limpieza automática %@.",
        cleanerScheduleNotifyToggle: "Avisar al terminar",
        cleanerNotifDenied: "Las notificaciones de Vorssaint están desactivadas en el sistema.",
        cleanerNotifOpenSettings: "Abrir ajustes de notificaciones…",
        launchAtLoginNeedsApplications: "La app se está ejecutando desde un lugar que no permite abrirse al iniciar sesión. Arrastra Vorssaint a la carpeta Aplicaciones, ábrelo desde ahí y actívalo de nuevo.",
        launchAtLoginNeedsApproval: "El ítem de inicio está registrado, pero sigue desactivado en Ajustes del Sistema. Abre Ajustes del Sistema › General › Ítems de inicio y extensiones y activa Vorssaint en “Abrir al iniciar sesión”.",
        ocrRemoveLineBreaksToggle: "Eliminar saltos de línea",
        ocrRemoveLineBreaksCaption: "Elimina los saltos de línea para que el texto copiado se pegue como un solo párrafo.",
        ocrQRToggle: "Leer códigos QR",
        ocrQRCaption: "Si el área tiene un código QR, se muestra su contenido para copiar o abrir.",
        ocrQRCopied: "Código QR copiado",
        qrResultTitle: "Código QR",
        qrResultCopy: "Copiar",
        qrResultOpen: "Abrir enlace",
        highlightsTitle: "Novedades de esta versión",
        highlightsTitleClipboardRedesign: "Portapapeles rediseñado",
        highlightsTitleWindowLayout: "Organización de ventanas",
        highlightsTitleQuitProtection: "Protección de ⌘Q y ⌘W",
        highlightsTitleRecorderBlur: "Desenfoque en grabaciones",
        highlightsCaptionDockPreview: "Dock Preview ahora funciona con la ampliación del Dock activada",
        highlightsCaptionScreenshot: "La captura de pantalla ganó una lupa de píxeles y lectura de códigos QR",
        highlightsCaptionSnippetLibrary: "Un menú de fragmentos con búsqueda escribe cualquier fragmento en el cursor",
        highlightsCaptionCapturePalette: "Un solo atajo abre ahora una paleta flotante para capturas, grabaciones, texto en pantalla y colores con ajustes al alcance.",
        highlightsCaptionClipboardRedesign: "El historial ahora se abre como una paleta compacta con filas limpias y una vista previa a demanda para leer o editar el elemento completo.",
        highlightsCaptionWindowLayout: "Coloque ventanas con el anillo direccional mediante atajo y puntero, o arrastre a los bordes de la pantalla para ajustar con márgenes personalizados.",
        highlightsCaptionQuitProtection: "Evite cerrar apps o ventanas por error manteniendo presionada la tecla, pulsando dos veces o con un modificador extra, configurable por app.",
        highlightsCaptionRecorderBlur: "Oculte datos confidenciales, contraseñas y detalles privados en cualquier tramo de su video grabado antes de guardarlo o compartirlo.",
        highlightsConfigure: "Configurar",
        highlightsTry: "Probar",
        highlightsSeeAll: "Ver todos los cambios",
        switcherCurrentSpaceOnly: "Mostrar solo el escritorio actual",
        switcherCurrentSpaceOnlyCaption: "Muestra en el selector solo las ventanas del escritorio en el que estás. Elegir una ventana nunca te lleva a otro escritorio.",
        shelfFileMissing: "El archivo ya no existe",
        previewSizeSmall: "Pequeño",
        mixerSoundEffectsOutputTitle: "Sonidos del sistema",
        mixerSoundEffectsOutputTooltip: "Elegir dónde se reproducen los avisos y efectos de sonido",
        monitorOpenActivityMonitor: "Abrir Monitor de Actividad",
        dockClickHide: "Ocultar la app al hacer clic en el Dock",
        dockClickHideCaption: "La app activa se oculta al hacer clic en su icono del Dock. Haz clic de nuevo para recuperarla.",
        monitorMemoryMetricLabel: "Medir memoria como",
        memoryMetricUsed: "Memoria usada",
        memoryMetricApp: "Memoria de apps",
        keepAwakeRightClickToggle: "Haz clic derecho en el icono de la barra de menús para activar o desactivar “Mantener activo”",
        keepAwakeRightClickToggleCaption: "Sustituye el menú contextual del clic derecho.",
        urlCleanerRulesTitle: "Reglas de limpieza",
        urlCleanerRulesCaption: "Un sitio añade estos parámetros a sus propios enlaces para compartir y así rastrear de dónde vino el enlace. Marcado, el nombre se elimina al limpiar; sin marcar, permanece. Los nombres que añadas se pueden eliminar.",
        urlCleanerRulesCoverageCaption: "La lista abarca las distintas vías para compartir de un sitio (la página web, la app, una sala en directo), por eso es larga; un enlace real suele llevar solo entre dos y cuatro.",
        urlCleanerRulesAllSites: "Todos los sitios",
        urlCleanerRulesCountSingular: "1 parámetro",
        urlCleanerRulesCountPluralFormat: "%d parámetros",
        urlCleanerRulesAddSite: "Añadir sitio",
        urlCleanerRulesParameterPlaceholder: "Nombre del parámetro",
        urlCleanerRulesMatchCaption: "Escribe el nombre a la izquierda del = , por ejemplo utm_source. Un nombre que coincide quita solo ese parámetro del enlace y deja el resto igual.",
        urlCleanerRulesAddButton: "Añadir",
        urlCleanerRulesRemoveButton: "Eliminar nombre",
        urlCleanerRulesRemoveSiteButton: "Desactivar todas las reglas de este sitio",
        urlCleanerRemovedFormat: "Eliminados %@",
        switcherSearchPin: "Fijar búsqueda con S",
        switcherSearchPinCaption: "S inicia una búsqueda y fija el selector abierto: al escribir ya no aparecen caracteres especiales cuando el atajo usa ⌥, y una búsqueda que empieza por Q o W ya no cierra la ventana ni cierra la app por error.",
        invertVerticalScroll: "Invertir el desplazamiento vertical",
        invertHorizontalScroll: "Invertir el desplazamiento horizontal",
        switcherShowShortcutHints: "Mostrar indicaciones de atajos",
        switcherShowShortcutHintsCaption: "Muestra los atajos de apps y ventanas debajo de los iconos.",
        uninstallerHomebrewPackageFormat: "%@ también se eliminará de Homebrew.",
        shelfEdgeToggle: "Abrir cerca de un borde de la pantalla",
        shelfEdgeCaption: "Arrastra un archivo hacia el borde de la pantalla para que el estante asome. Suéltalo ahí, o retíralo y el estante se repliega.",
        focusFollowsMouseName: "El foco sigue al ratón",
        focusFollowsMouseCaption: "Enfoca y trae al frente la ventana bajo el puntero tras una breve pausa.",
        focusFollowsMouseDelay: "Retraso al pasar",
        switcherMinimizedPlacementLabel: "Ventanas minimizadas",
        switcherMinimizedPlacementNormal: "Orden normal",
        switcherMinimizedPlacementEnd: "Colocar al final",
        switcherMinimizedPlacementHidden: "Ocultar",
        switcherShowFullscreenWindows: "Mostrar ventanas en pantalla completa",
        switcherScreenPlacementLabel: "Mostrar en",
        switcherScreenPlacementPointer: "Pantalla con el puntero",
        switcherScreenPlacementMenuBar: "Pantalla con la barra de menús",
        switcherScreenPlacementActiveWindow: "Pantalla con la ventana activa",
        switcherScreenPlacementCaption: "En qué pantalla se abre el selector cuando hay más de una conectada.",
        smoothScrollResponseLabel: "Respuesta",
        mouseAccelerationName: "Desactivar la aceleración del ratón",
        mouseAccelerationCaption: "Elimina la aceleración del puntero para los ratones conectados. El ajuste anterior vuelve al desactivarlo o salir de Vorssaint.",
        shelfClearOnClose: "Borrar al cerrar",
        shelfClearOnCloseCaption: "Vacía el estante solo al hacer clic en el botón de cierre. Ocultarlo automáticamente y contraerlo conservan los ítems."
    )
}
