// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// 日本語 — translated and hand-checked, not machine output.
extension Strings {
    static let ja = Strings(
        statusIdleTooltip: "Vorssaint：通常のスリープ",
        statusActiveUntil: "Vorssaint：次の時刻までスリープしない",
        statusActiveIndefinite: "Vorssaint：解除するまでスリープしない",
        menuEnableAwake: "スリープ防止をオン",
        menuDisableAwake: "スリープ防止をオフ",
        menuActivateFor: "時間を指定してオン…",
        menuSettings: "設定…",
        menuAbout: "Vorssaint について",
        menuQuit: "Vorssaint を終了",
        menuHide: "Vorssaint を隠す",
        menuHideOthers: "ほかを隠す",
        menuShowAll: "すべてを表示",
        menuEdit: "編集",
        menuUndo: "取り消す",
        menuRedo: "やり直す",
        actionClear: "消去",
        actionRemove: "削除",
        actionBack: "戻る",
        actionSearch: "検索",
        actionMute: "消音",
        actionUnmute: "再開",
        actionPlay: "再生",
        actionPause: "一時停止",
        menuCut: "カット",
        menuCopy: "コピー",
        menuPaste: "ペースト",
        menuSelectAll: "すべてを選択",
        menuWindow: "ウインドウ",
        menuMinimize: "しまう",
        menuZoom: "拡大／縮小",
        menuClose: "閉じる",

        minutes15: "15分",
        minutes30: "30分",
        hour1: "1時間",
        hours2: "2時間",
        hours4: "4時間",
        hours8: "8時間",
        indefinitely: "無期限",
        indefinite: "無期限",

        panelSettings: "設定",
        panelQuit: "終了",
        panelHotkeyHint: "ショートカットで切り替え",

        keepAwakeTitle: "スリープ防止",
        keepAwakeEndsIn: "残り",
        keepAwakeUntilDisabled: "オフにするまで継続",
        keepAwakeNormalRules: "Mac は通常の省エネルギー設定に従います",
        keepAwakeOptions: "オプション",
        keepAwakeMouseJiggle: "ポインタを少し動かす",
        keepAwakeMouseJiggleCaption: "セッション中、選んだ間隔でポインタを少し動かします。",
        keepAwakeMouseJiggleInterval: "間隔",
        keepAwakeActiveIconLabel: "使用中のアイコン",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "コーヒー",
        keepAwakeActiveIconEye: "目",
        keepAwakeActiveIconMoon: "月",
        keepAwakeActiveIconLight: "電球",
        keepAwakeIconTintLabel: "アクティブ時のアイコン色",
        keepAwakeIconTintOrange: "オレンジ",
        keepAwakeIconTintGreen: "緑",
        keepAwakeIconTintBlue: "青",
        keepAwakeIconTintPurple: "紫",
        keepAwakeIconTintPink: "ピンク",
        keepAwakeIconTintNone: "色なし",
        durationLabel: "継続時間",
        clamshellTitle: "ふたを閉じても続ける",
        clamshellOnCaption: "スリープを完全に無効化中。電源にご注意ください",
        clamshellNeedsSession: "「スリープ防止」がオンのあいだ常に適用されます",
        clamshellReady: "準備完了。パスワードなしで切り替えられます",
        clamshellNeedsPassword: "管理者パスワードは一度だけ求められます",

        systemSection: "システム",
        temperatures: "温度",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "バッテリー",
        usageSection: "ハードウェア使用状況",
        memorySection: "メモリ",
        memoryPressure: "プレッシャー",
        memorySwapUsed: "使用中のスワップ",
        memoryCompressed: "圧縮",
        memoryCachedFiles: "キャッシュ済み",
        pressureNormal: "標準",
        pressureWarning: "注意",
        pressureCritical: "危険",
        monitorUnavailable: "この Mac ではセンサーを利用できません",
        energyAppsTitle: "大きなエネルギー使用",
        energyAppsIdle: "大きなエネルギー使用なし",

        notifySessionEndedTitle: "セッションが終了しました",
        notifySessionEndedBody: "時間になりました。Mac は再び通常どおりスリープします。",
        notifyBatteryTitle: "Vorssaint をオフにしました",
        notifyBatteryBody: "バッテリー残量が少なくなりました。充電を保護するため通常のスリープに戻しました。",
        adminPromptClamshellOn: "ふたを閉じても続けるには、Vorssaint にパスワードが必要です。",
        adminPromptClamshellOff: "Mac の通常のスリープを元に戻すにはパスワードが必要です。",
        adminPromptRecover: "Mac のスリープを無効化したまま Vorssaint が終了しました。通常のスリープに戻すにはパスワードを入力してください。",
        adminPromptUpdate: "アップデートをインストールするには Vorssaint にパスワードが必要です。",
        adminPromptSudoersInstall: "ふたを閉じたモードをパスワードなしで切り替えられるよう、Vorssaint が制限付きルール（pmset disablesleep のみ）を作成します。パスワードが必要なのはこの一度きりです。",
        adminPromptSudoersRemove: "パスワード不要のふたを閉じたモードのルールを Vorssaint が削除します。",

        settingsTitle: "Vorssaint 設定",
        tabGeneral: "一般",
        tabEnergy: "省エネルギー",
        tabMouse: "マウスとトラックパッド",
        tabSwitcher: "スイッチャー",
        tabAdvanced: "詳細",
        tabAbout: "情報",
        tabReleaseNotes: "新機能",
        releaseNotesOnUpdateToggle: "アップデート後に新機能を表示",
        minimalWindowPreviews: "シンプルなプレビュー",
        minimalWindowPreviewsCaption: "Dockとアプリ切り替えのプレビューで、タイトル、ボタン、装飾を非表示にします。選択表示は残ります。",
        previewSizeLabel: "プレビューのサイズ",
        previewSizeNormal: "標準",
        previewSizeLarge: "大",
        previewSizeXLarge: "特大",
        settingsGroupFeatures: "機能",
        advancedResetSection: "アクセス権",
        advancedResetDescription: "Vorssaint に許可したすべてのアクセス権（アクセシビリティ、画面収録、フルディスクアクセスなど）、ログイン項目、ふたを閉じたモードのルールを削除します。最初からやり直すときや、アンインストールの前に便利です。アプリはインストールされたまま残ります。",
        advancedClearButton: "すべてのアクセス権を消去",
        advancedCleared: "アクセス権を消去しました。",
        advancedClearConfirmTitle: "すべてのアクセス権を消去しますか？",
        advancedClearConfirmBody: "アクセス権が必要な機能は、再度許可するまで動作しなくなります。設定はそのまま保持されます。",
        advancedUninstallSection: "アンインストール",
        advancedUninstallDescription: "上記をすべて実行したうえで、環境設定を削除し、Vorssaint をゴミ箱に移動して、何も残しません。完了後にアプリは終了します。いつでも再インストールできます。",
        advancedUninstallButton: "Vorssaint を完全にアンインストール",
        advancedUninstallConfirmTitle: "Vorssaint をアンインストールしますか？",
        advancedUninstallConfirmBody: "Vorssaint はアクセス権を消去し、環境設定を削除し、ゴミ箱に移動してから終了します。この操作はアプリからは取り消せませんが、ゴミ箱を空にするまではゴミ箱に残ります。",
        advancedUninstallFailedTitle: "アンインストールを中止しました",
        advancedUninstallFailedBody: "Vorssaint が変更したシステム設定（スリープ、ファンの回転数、マウス加速）を元に戻せませんでした。何も削除していません。もう一度試して、パスワードの入力を求められたら許可してください。",

        launchAtLogin: "ログイン時に起動",
        languageLabel: "言語",
        menuBarSection: "メニューバー",
        showCountdown: "アイコンの横に残り時間を表示",
        globalHotkeySection: "グローバルショートカット",
        hotkeyToggle: "「スリープ防止」のショートカットを有効にする",
        hotkeyCaption: "追加のアクセス権なしで、どのアプリでも使えます。",

        sessionSection: "セッション",
        defaultDurationLabel: "デフォルトの継続時間",
        keepAwakeAutoStart: "Vorssaint起動時にスリープを防ぐ",
        keepAwakeAutoStartCaption: "既定の時間でセッションを開始します。",
        batteryProtectionSection: "バッテリー保護",
        batteryDisableBelow: "バッテリーが次の値を下回ったらオフにする",
        batteryNever: "しない",
        batteryProtectionCaption: "オンのままになったセッションが MacBook のバッテリーを消耗させるのを防ぎます。",
        clamshellSection: "ふたを閉じたモード",
        configuring: "設定中…",
        sudoersFailed: "ふたを閉じたモードを有効にできませんでした。もう一度お試しください。",
        clamshellExplanation: "「ふたを閉じても続ける」は、「スリープ防止」がオンのあいだスリープを完全に無効化し、セッションの終了時またはアプリの終了時に自動的に元に戻ります。電源に接続した状態での使用をおすすめします。",

        scrollSection: "スクロール",
        invertMouseScroll: "マウスのスクロールを反転",
        invertMouseScrollCaption: "マウスホイールのスクロール方向を逆にします。",
        scrollTrackpadNote: "トラックパッドはそのままで、macOS のナチュラルなスクロールを維持します。",
        scrollActiveNow: "現在マウスのスクロールを反転中",
        mouseNavigationActiveNow: "サイドボタンは現在有効です",
        smoothScrollName: "スムーズスクロール",
        smoothScrollCaption: "マウスホイールの1目盛りを短くなめらかなスライドに変えます。トラックパッドは変わりません。",
        smoothScrollStepLabel: "スクロール速度",
        mouseNavigationSection: "ナビゲーション",
        mouseNavigationEnable: "サイドボタンで戻ると進むを操作",
        mouseNavigationCaption: "マウスの戻るボタンと進むボタンを、Finder、ブラウザ、対応アプリのナビゲーション操作に変換します。",
        middleClickSection: "中クリック",
        middleClickEnable: "3本指クリックを中クリックにする",
        middleClickEnableCaption: "トラックパッドを3本指で押すと、マウスのホイールクリックと同じように動作します。リンクを新しいタブで開く、タブを閉じるなど、中ボタンでできることすべてに使えます。",
        middleClickDragConflict: "macOSの3本指のドラッグがオンになっており、同じジェスチャを使用します。システム設定のアクセシビリティ、ポインタコントロール、トラックパッドオプションでオフにすると、中クリックが機能します。",
        middleClickTapPicker: "軽いタップでもクリック",
        middleClickTapOff: "オフ",
        middleClickTapThreeFingers: "3 本指",
        middleClickTapFourFingers: "4 本指",
        middleClickTapCaption: "その本数の指で軽くタップ（押し込まずに）しても中クリックが発火します。スライドは対象外です。macOS の 3 本指タップが「調べる」に割り当てられている場合は、両方が同時に発火しないようオフにしてください。",
        quickToolsTab: "クイックパネル",
        quickToolShortcutToggle: "グローバルショートカット",
        ocrName: "画面のテキストをコピー",
        ocrCaption: "画面の範囲を選択すると、認識されたテキストがコピーされ、すぐにペーストできます。",
        ocrCopied: "テキストをコピーしました",
        ocrNoText: "テキストが見つかりません",
        colorPickerName: "カラーピッカー",
        colorPickerCaption: "画面上の任意のピクセルの色を取得し、好みの形式でコピーします。",
        colorPickerFormatLabel: "コピー形式",
        colorPickerBareHexToggle: "先頭の # を付けずにコピー",
        colorPickerPickNow: "色を取得",
        micMuteName: "マイクを消音",
        micUnmuteName: "マイクを再開",
        micMuteCaption: "クリックまたはショートカットでMacのマイクをどのアプリでも消音します。",
        micMutedHUD: "マイクを消音しました",
        micUnmutedHUD: "マイクを再開しました",
        micMuteMenuBarToggle: "消音中はメニューバーに表示",
        micMuteMenuBarCaption: "メニューバーのアプリアイコンの横に、赤い斜線入りのマイクが表示されます。",
        pastePlainName: "プレーンテキストとしてペースト",
        pastePlainCaption: "コピーした内容を色・フォント・書式なしでペーストします。元の内容はクリップボードに残ります。",
        launcherName: "クイックパネル",
        launcherCaption: "お気に入りのツールを集めたフローティングパネル。どこからでもショートカットで呼び出せます。",
        launcherOpenNow: "クイックパネルを開く",
        launcherEditHint: "調整ボタンでツールの選択・非表示・ドラッグ移動ができます。",
        launcherEmptyState: "すべてのツールが非表示です。調整ボタンで戻せます。",
        launcherAddSection: "元に戻す",
        launcherKeysHint: "矢印で移動、Enterで開く、1〜9で直接開く",
        switcherSection: "アプリスイッチャー",
        switcherEnable: "Vorssaint のスイッチャーを使う",
        switcherEnableCaption: "アプリやウインドウを切り替えます。最小化したウインドウや同じアプリの複数ウインドウにも対応します。",
        switcherUsageHint: "ショートカットを押したまま移動し、放すとウインドウがアクティブになります。Shift または ← で戻る、W でウインドウを閉じ、Q でアプリを終了、Esc でキャンセルします。",
        switcherNoWindows: "開いているウインドウはありません",
        switcherIconRowMode: "%@ を大きなアイコンで表示",
        switcherIconRowModeCaption: "アプリごとに1つのアイコンを表示し、その上にそのアプリのウインドウプレビューを表示します。",
        switcherSimpleMode: "シンプルなアプリスイッチャー",
        switcherSimpleModeCaption: "プレビューやスイッチャーによる画面収録を使わず、アプリのアイコンとウインドウのタイトルを表示します。",
        switcherShortcutHintApps: "アプリ",
        switcherShortcutHintWindows: "ウインドウ",
        switcherWindowShortcutCaption: "最前面のアプリのウインドウ用スイッチャーを開きます。アプリスイッチャー表示中は、選択中のアプリのウインドウを順に切り替えます。",
        switcherTakeOverSystemShortcuts: "macOS の ⌘Tab と ⌘` を置き換える",
        switcherTakeOverSystemShortcutsCaption: "Vorssaint のスイッチャーが動作中の間だけ、対応する macOS のアプリとウインドウのショートカットを無効にします。実行中のすべてのアプリに切り替えられます。",
        switcherAppearanceDelay: "表示までの待ち時間",
        switcherAppearanceDelayCaption: "スイッチャーが表示されるまでショートカットを押し続ける時間です。",
        switcherMergeTabs: "アプリごとに1つにまとめて表示",
        switcherMergeTabsCaption: "スイッチャーで、アプリのすべてのウインドウをウインドウごとではなく1つの項目にまとめます。",
        switcherWindowlessApps: "ウインドウなしのアプリ",
        switcherWindowlessAppsCaption: "ウインドウを1つも開いていない起動中のアプリのうち、どれをスイッチャーに表示するかを選びます。",
        switcherWindowlessAppsOff: "表示しない",
        switcherWindowlessAppsFinder: "Finder のみ",
        switcherWindowlessAppsAll: "すべてのアプリ",
        switcherNoOpenWindow: "ウインドウなし",
        switcherOtherDesktop: "別のデスクトップ",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Dock でウインドウをプレビュー",
        dockPreviewEnableCaption: "Dock の開いているアプリにポインタを重ねてウインドウを確認し、開きたいウインドウをクリックします。",
        dockPreviewBackgroundOpacity: "パネルの背景",
        dockPreviewBackgroundOpacityCaption: "下げると、パネルの後ろにあるものがより見えるようになります。",
        dockPreviewOpenDelay: "表示までの待ち時間",
        dockPreviewOpenDelayCaption: "ポインタをアイコンに置いてからパネルが開くまでの時間です。",
        dockPreviewQuitAppOnClose: "× ボタンでアプリを終了",
        dockPreviewQuitAppOnCloseCaption: "Dock Preview では、× はそのウインドウだけを閉じる代わりにアプリ全体を終了します。",
        dockClickMinimize: "Dock クリックでしまう",
        dockClickMinimizeCaption: "手前のアプリの Dock アイコンをクリックするとウインドウをしまいます。もう一度クリックすると戻ります。",
        dockClickCycleWindows: "Dock クリックでウインドウを切り替え",
        dockClickCycleWindowsCaption: "手前のアプリの Dock アイコンをクリックするとウインドウを順に切り替えます（⌘` と同様）。",
        dockPreviewActiveNow: "Dock で有効",
        dockPreviewDockUnavailable: "Dock の項目を読み取れませんでした。",
        dockPreviewAutohideBeta: "ベータ版です。一部の不具合が残っている場合があります。",
        dockPreviewOpenWindow: "ウインドウを開く",
        dockPreviewCloseWindow: "ウインドウを閉じる",
        dockPreviewMinimizeWindow: "ウインドウをしまう",
        dockPreviewRestoreWindow: "ウインドウを戻す",
        dockPreviewPinPanel: "プレビューを固定",
        dockPreviewUnpinPanel: "固定を解除",
        dockPreviewPinned: "固定中",
        dockPreviewClosePanel: "プレビューを閉じる",
        dockPreviewPreviousWindow: "前のウインドウ",
        dockPreviewNextWindow: "次のウインドウ",

        cutPasteName: "カット＆ペースト",
        cutPasteEnable: "Finder でファイルをカット＆ペースト",
        cutPasteEnableCaption: "⌘X でカット、⌘V で Finder のファイルやフォルダを移動できます。",
        cutPasteShowHUD: "フローティングパネルを表示",
        cutPasteShowHUDCaption: "Finder がアクティブなときに、カットしたファイルのフローティング表示を出します。",
        cutPasteHowTitle: "使いかた",
        cutPasteStep1: "Finder で項目を選択し、⌘X を押してカットします。",
        cutPasteStep2: "移動先のフォルダを開き、⌘V を押してそこへ移動します。",
        cutPasteTextNote: "テキストフィールド内では（名前の変更時など）、⌘X と ⌘V はこれまでどおり動作します。",
        cutPasteActiveNow: "Finder でカットできます",
        cutPasteAutomationNote: "初回は、macOS が Finder を制御する許可を求めます。",
        cutReadyTitle: "カットしました",
        cutReadyHint: "移動先のフォルダで",
        cutCancel: "カットをキャンセル",
        cutDoneTitle: "移動しました！",
        cutMovedSingular: "1項目を移動しました",
        cutMovedPluralFormat: "%d項目を移動しました",
        cutSomeFailed: "一部の項目を移動できませんでした",
        cutMovingTitle: "移動中…",
        cutMovingCountFormat: "%d / %d",

        autoQuitName: "閉じたら終了",
        autoQuitEnable: "最後のウインドウを閉じたらアプリを終了",
        autoQuitEnableCaption: "アプリの最後のウインドウを閉じると、そのアプリも終了します。",
        autoQuitActiveNow: "現在有効",
        autoQuitHowTitle: "しくみ",
        autoQuitStep1: "アプリの最後のウインドウを閉じます（⌘W または赤いボタン）。",
        autoQuitStep2: "アプリは自動的に終了します。「変更を保存しますか？」のダイアログは引き続き表示されます。",
        autoQuitPredictableNote: "通常ウインドウなしで動作するアプリは、終了されることはありません。",
        autoQuitExceptionsTitle: "例外",
        autoQuitExceptionsCaption: "このリストのアプリは、ウインドウがなくても開いたままになります。",
        autoQuitExceptionsEmpty: "例外はありません",
        autoQuitAddApp: "アプリを追加…",

        uninstallerName: "アンインストーラ",
        uninstallerEnableCaption: "アプリを、それが残すキャッシュ、環境設定、ログ、残存ファイルもろとも削除します。",
        uninstallerStep1: "アプリを設定にドラッグするか、リストから1つ選びます。",
        uninstallerStep2: "見つかったファイルと、それらが占める容量を確認します。",
        uninstallerStep3: "必要なものをゴミ箱に移動します。完全には削除されません。",
        uninstallerMenuItem: "アプリをアンインストール…",
        uninstallerDropTitle: "ここにアプリをドラッグ",
        uninstallerDropSubtitle: "またはスキャンするアプリを選択",
        uninstallerChoose: "アプリを選択…",
        uninstallerPickerTitle: "アプリを選択",
        uninstallerPickerSearch: "アプリを検索",
        uninstallerPickerEmpty: "アプリが見つかりません",
        uninstallerEmptyNote: "確認なしに削除されるものはありません。",
        uninstallerFDANote: "より徹底的にスキャンするにはフルディスクアクセスを許可してください。",
        uninstallerFDAGrant: "アクセスを許可…",
        uninstallerFDAHint: "リストで Vorssaint をオンにします。表示されない場合は + をクリックし、アプリケーションから Vorssaint を選びます。アクセス権はアプリを再度開いた後に有効になります。",
        uninstallerFDARelaunch: "今すぐ再起動",
        uninstallerScanning: "ファイルをスキャン中…",
        uninstallerRemoving: "ゴミ箱に移動中…",
        uninstallerFoundTitle: "件見つかりました",
        uninstallerSelectedFormat: "%d／%d 件を選択中",
        uninstallerRemove: "ゴミ箱に移動",
        uninstallerCancel: "キャンセル",
        uninstallerDoneTitle: "完了！",
        uninstallerFreedFormat: "%@ を回復しました",
        uninstallerSomeFailed: "一部の項目をゴミ箱に移動できませんでした。",
        uninstallerFailedNeedsFDA: "サンドボックス内のアプリデータは、フルディスクアクセスがなければ移動できません。管理者パスワードでは代われません。",
        uninstallerFailedMoreFormat: "ほか %d 項目",
        uninstallerAnother: "別のアプリをアンインストール",
        uninstallerCatApp: "アプリケーション",
        uninstallerCatSupport: "サポート",
        uninstallerCatCaches: "キャッシュ",
        uninstallerCatPreferences: "環境設定",
        uninstallerCatContainers: "コンテナ",
        uninstallerCatLogs: "ログ",
        uninstallerCatState: "保存された状態",
        uninstallerCatOther: "その他",

        urlCleanerName: "URL をクリーン",
        urlCleanerEnable: "コピー時に URL を自動でクリーン",
        urlCleanerEnableCaption: "リンクがクリップボードに入った時点でトラッキング用パラメータを削除します。",
        urlCleanerActiveNow: "現在有効",
        urlCleanerManualTitle: "今すぐクリーン",
        urlCleanerInputPlaceholder: "URL をペースト",
        urlCleanerOutputPlaceholder: "クリーンな URL がここに表示されます",
        urlCleanerCleanButton: "クリーン",
        urlCleanerPasteButton: "ペースト",
        urlCleanerCopyButton: "コピー",
        urlCleanerClearButton: "欄をクリア",
        urlCleanerNoURL: "有効な URL をペーストしてください。",
        urlCleanerNoChange: "削除するものはありません。",
        urlCleanerCleaned: "URL をクリーンしました。",
        urlCleanerCopied: "コピーしました。",
        urlCleanerLocalNote: "ローカル。通信なし。",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "formula と cask を検索、インストール、削除します。",
        homebrewMissingTitle: "Homebrew が見つかりません",
        homebrewMissingBody: "Vorssaint は公式 Homebrew インストーラを Terminal で開けます。Terminal に手順が表示され、必要ならパスワードを求められます。",
        homebrewInstallHomebrew: "Homebrew をインストール",
        homebrewInstallHomebrewCaption: "Terminal が終わったら、ここに戻って更新をクリックしてください。",
        homebrewInstallHomebrewOpened: "インストーラを Terminal で開きました。",
        homebrewShellSetupTitle: "Terminal 設定を完了",
        homebrewShellSetupBody: "Homebrew はインストールされていますが、Terminal がまだ brew コマンドを見つけられない場合があります。Vorssaint は設定コマンドを Terminal で開けます。",
        homebrewShellSetupButton: "Terminal を設定",
        homebrewShellSetupOpened: "コマンドを Terminal で開きました。終わったら戻って更新をクリックしてください。",
        homebrewRefresh: "更新",
        homebrewCheckPackages: "パッケージを確認",
        homebrewTrustTitle: "まだ信頼されていないTap",
        homebrewTrustCaption: "Homebrewはサードパーティ製Tapを使う前に確認を求めるようになりました。%@を信頼すると続行できます。",
        homebrewTrustButton: "信頼して続ける",
        homebrewSearchPlaceholder: "パッケージを検索",
        homebrewKeyboardHint: "スペースまたは Return で macOS パネルが閉じます。検索ボタンを使用してください。",
        homebrewSearchButton: "検索",
        homebrewSearchResults: "結果",
        homebrewInstalled: "インストール済み",
        homebrewAll: "すべて",
        homebrewFormulas: "Formula",
        homebrewCasks: "Cask",
        homebrewNoPackages: "パッケージが見つかりません",
        homebrewNoSelection: "インストール済みパッケージを選択するか、新しいものを検索してください。",
        homebrewDetailsTitle: "パッケージ詳細",
        homebrewInstall: "インストール",
        homebrewUninstall: "アンインストール",
        homebrewUpgrade: "更新",
        homebrewUpgradeAll: "すべて更新",
        homebrewUpdateHomebrew: "Homebrew を更新",
        homebrewAllPackages: "パッケージ",
        homebrewOpenTerminal: "Terminal を開く",
        homebrewCancelOperation: "キャンセル",
        homebrewClearLog: "ログをクリア",
        homebrewLogTitle: "ログ",
        homebrewVersion: "バージョン",
        homebrewDescription: "種類",
        homebrewHomepage: "サイトを開く",
        homebrewPopularity: "人気度",
        homebrewPopularityFormat: "%@ 件のインストール、%@ 日間",
        homebrewInstalledBadge: "インストール済み",
        homebrewNotInstalledBadge: "未インストール",
        homebrewUpdates: "更新",
        homebrewUpdateAvailableBadge: "更新あり",
        homebrewLatestVersion: "最新",
        homebrewConfirmInstallTitle: "Homebrew でインストールしますか？",
        homebrewConfirmInstallBodyFormat: "Homebrew が %@ をダウンロードしてインストールします。依存関係もインストールされる場合があります。",
        homebrewConfirmUninstallTitle: "Homebrew でアンインストールしますか？",
        homebrewConfirmUninstallBodyFormat: "Homebrew が %@ をアンインストールします。設定ファイルがシステムに残る場合があります。",
        homebrewConfirmUpgradeTitle: "Homebrew で更新しますか？",
        homebrewConfirmUpgradeBodyFormat: "Homebrew が %@ の最新バージョンをダウンロードして適用します。依存関係も更新される場合があります。",
        homebrewConfirmUpgradeAllTitle: "Homebrew ですべて更新しますか？",
        homebrewConfirmUpgradeAllBody: "Homebrew が更新可能なパッケージの最新バージョンをダウンロードして適用します。依存関係も更新される場合があります。",
        homebrewConfirmUpdateHomebrewTitle: "Homebrew を更新しますか？",
        homebrewConfirmUpdateHomebrewBody: "Homebrew が最新情報を取得し、その後パッケージを再読み込みします。",
        homebrewTerminalFallback: "この操作では管理者パスワードを求めるために Terminal が必要です。Vorssaint はパスワードを取得しません。",
        homebrewLoading: "読み込み中…",
        homebrewSearchEmpty: "結果なし",
        homebrewOperationInstallFormat: "%@ をインストール中",
        homebrewOperationUninstallFormat: "%@ をアンインストール中",
        homebrewOperationUpgradeFormat: "%@ を更新中",
        homebrewOperationUpgradeAll: "パッケージを更新中",
        homebrewOperationUpdateHomebrew: "Homebrew を更新中",
        homebrewOperationInstalledFormat: "%@ をインストールしました。",
        homebrewOperationUninstalledFormat: "%@ をアンインストールしました。",
        homebrewOperationUpgradedFormat: "%@ を更新しました。",
        homebrewOperationUpgradedAll: "パッケージを更新しました。",
        homebrewOperationUpdatedHomebrew: "Homebrew を更新しました。",
        homebrewOperationFailedFormat: "%@ を完了できませんでした。",
        homebrewOperationCancelled: "操作をキャンセルしました。",
        homebrewOperationPreparing: "準備中…",
        homebrewOperationDownloading: "ファイルをダウンロード中…",
        homebrewOperationInstalling: "ファイルをインストール中…",
        homebrewOperationUninstalling: "ファイルを削除中…",
        homebrewOperationUpgrading: "ファイルを更新中…",
        homebrewOperationFinalizing: "完了処理中…",
        homebrewOperationRefreshing: "一覧を更新中…",
        homebrewOperationTerminal: "Terminal で続行してください。",
        homebrewOperationElapsedFormat: "%@ 経過",
        homebrewOperationShowDetails: "詳細を表示",
        homebrewOperationHideDetails: "詳細を隠す",
        homebrewOperationTechnicalLog: "技術的な詳細",
        homebrewOperationProgressUnknown: "Homebrew はまだ割合を報告していません。",

        mediaName: "メディア",
        mediaEnableCaption: "動画を圧縮し、画像の変換と加工、GIF の作成、テキストの抽出をローカルで行います。",
        mediaLocalNote: "ローカル。ネットワークなし。",
        mediaToolVideo: "動画",
        mediaToolGIF: "GIF",
        mediaToolImage: "画像",
        mediaToolText: "テキスト",
        mediaSelectFile: "ファイルを選択",
        mediaDropHint: "ここにファイルをドロップするか、クリックして選択します。",
        mediaOutput: "出力",
        mediaOutputAutomatic: "自動",
        mediaChooseOutput: "保存先",
        mediaStartVideo: "動画を圧縮",
        mediaStartGIF: "GIF を作成",
        mediaStartImage: "画像を加工",
        mediaStartConvertPDF: "PDFに変換",
        mediaStartText: "テキストを抽出",
        mediaCancel: "キャンセル",
        mediaStartTime: "開始",
        mediaEndTime: "終了",
        mediaQuality: "圧縮",
        mediaCompressionLow: "低",
        mediaCompressionMedium: "中",
        mediaCompressionHigh: "高",
        mediaMaxSize: "サイズ",
        mediaSizingResolution: "解像度",
        mediaSizingFileSize: "ファイルサイズ",
        mediaTargetSize: "目標サイズ",
        mediaTargetSizeHint: "上限を超えないよう解像度が自動で調整されます。",
        mediaErrorTargetTooSmall: "この動画には目標サイズが小さすぎます。長さを短くするか上限を上げてください。",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "幅",
        mediaFPS: "FPS",
        mediaKeepAudio: "音声を保持",
        mediaCodec: "コーデック",
        mediaFormat: "形式",
        mediaStripMetadata: "メタデータを削除",
        mediaLoopGIF: "GIF をループ",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "高精度",
        mediaOCRFast: "高速",
        mediaLanguageCorrection: "言語補正",
        mediaTextOutputNote: "抽出したテキストはコピーして TXT として保存できます。",
        mediaRunning: "処理中",
        mediaCompleted: "完了",
        mediaCancelled: "キャンセルしました。",
        mediaOpenInFinder: "表示",
        mediaCopyText: "テキストをコピー",
        mediaRunAgain: "もう一度実行",
        mediaEmptyText: "テキストが見つかりません。",
        mediaResultSavedFormat: "%@ として保存しました",
        mediaResultSizeFormat: "%@ から %@",
        mediaResultGrewCaption: "変換後のファイルは元より大きくなりました。",
        mediaErrorNoFile: "先にファイルを選択してください。",
        mediaErrorNoVideo: "このファイルには動画トラックがありません。",
        mediaErrorSameOutput: "元のファイルとは別の保存先を選んでください。",
        mediaErrorUnsupported: "macOS が対応していない形式です。",

        shelfName: "シェルフ",
        shelfEnable: "ファイルをドラッグする一時置き場",
        shelfEnableCaption: "ファイル、画像、テキストを集めておき、あとからどこへでもドラッグできるフローティングの置き場です。",
        shelfHowTitle: "使いかた",
        shelfStep1: "ショートカットを押すか、ドラッグ中にマウスを振って開きます。",
        shelfStep2: "ファイル、画像、リンク、テキストをドロップして保持します。",
        shelfStep3: "必要なときに、各項目をどのアプリへでもドラッグして取り出します。",
        shelfShakeToggle: "ドラッグ中にマウスを振って開く",
        shelfShakeCaption: "項目を持ったままポインタをすばやく振ると、カーソルの近くに呼び出せます。",
        shelfDropZoneToggle: "ドラッグしたファイルをメニューバーに残す",
        shelfDropZoneCaption: "ファイルをドラッグすると、メニューバーのアイコンの下にシェルフが表示されます。ドロップしたものはそのままそこに保存され、クリックで開閉できるボタンに収まり、シェルフが空になると消えます。",
        shelfDropZoneLabel: "ここにドロップ",
        shelfCollapse: "折りたたむ",
        shelfBehaviorTitle: "使用後",
        shelfCloseAfterDrop: "別のアプリにドロップしたら閉じる",
        shelfCloseAfterDropCaption: "ドロップ先が項目を受け取るとシェルフを閉じます。パネルのピンで開いたままにできます。",
        shelfRemoveAfterDrop: "ドロップ後に項目を削除",
        shelfRemoveAfterDropCaption: "別のアプリが受け取った項目をシェルフから削除します。コピーを残す場合はオフにします。",
        shelfExclusionsTitle: "自動表示の例外",
        shelfExclusionsEmpty: "アプリは追加されていません。",
        shelfExclusionsCaption: "これらのアプリから始めたドラッグでは、振る操作とメニューバーの領域は開きません。ショートカットと今すぐ開くは引き続き使えます。",
        shelfPin: "開いたままにする",
        shelfUnpin: "使用後に閉じる",
        extraBrightnessName: "エクストラ輝度",
        extraBrightnessCaption: "ディスプレイのHDR余力を使って最大輝度を超えます。バッテリー消費が増え、Macが温かくなることがあります。",
        extraBrightnessLevelLabel: "強さ",
        extraBrightnessUnsupported: "14インチ・16インチMacBook ProなどのXDRディスプレイでのみ利用できます。",
        shelfHotkeyLabel: "ショートカット",
        shelfOpenNow: "今すぐ開く",
        shelfNoPermission: "アクセス権は不要です。",
        shelfMenuItem: "シェルフを開く",
        shelfTitle: "シェルフ",
        shelfEmpty: "ここに項目をドラッグ",
        shelfClearAll: "すべてを消去",
        shelfRemoveSelected: "選択した項目を削除",
        shelfSelectedFormat: "%d 件を選択中",
        shelfHint: "クリックで選択。ドラッグして使用するか、右クリックでその他の操作を表示します。",
        shelfItemImage: "画像",
        shelfTooltipItemsFormat: "%d 件",
        shelfTooltipItemsFew: "%d 件",
        shelfTooltipImageSingular: "%d 枚の画像",
        shelfTooltipImageFew: "%d 枚の画像",
        shelfTooltipImagePlural: "%d 枚の画像",
        shelfTooltipFileSingular: "%d 個のファイル",
        shelfTooltipFileFew: "%d 個のファイル",
        shelfTooltipFilePlural: "%d 個のファイル",
        shelfTooltipNoteSingular: "%d 件のメモ",
        shelfTooltipNoteFew: "%d 件のメモ",
        shelfTooltipNotePlural: "%d 件のメモ",
        shelfTooltipLinkSingular: "%d 件のリンク",
        shelfTooltipLinkFew: "%d 件のリンク",
        shelfTooltipLinkPlural: "%d 件のリンク",
        shelfActionOpen: "開く",
        shelfActionOpenWith: "このアプリケーションで開く",
        shelfActionShare: "共有",

        breakdownMeasuring: "計測中…",

        mixerSection: "音量ミキサー",
        mixerEmpty: "オーディオを使用するアプリがここに表示されます",
        mixerUnavailable: "macOS 14.4 以降で利用できます",
        mixerPermissionBody: "アプリごとの音量を調整するには、システム設定で「画面とシステムオーディオ収録」を許可してください。オーディオが記録されることはありません。",
        mixerResetTooltip: "100% にリセット",
        mixerOutputDefault: "デフォルト",
        mixerOutputCurrent: "現在",
        mixerOutputUnavailable: "出力を利用できません",
        mixerOutputFallback: "このデバイスが戻るまでデフォルトを使用します。",
        mixerBypassedCaption: "このアプリは自身でオーディオを管理します。",
        mixerOutputTooltip: "出力を選択",
        mixerSystemOutputTitle: "出力",
        mixerSystemOutputNoDevices: "出力が見つかりません",
        mixerSystemOutputTooltip: "システム出力を選択",
        mixerSystemOutputErrorFormat: "変更できませんでした: %@",
        mixerLowerOnHeadphonesDisconnect: "ヘッドフォン切断時に音量を下げる",
        mixerLowerOnHeadphonesDisconnectCaption: "有線またはBluetoothヘッドフォンが切断されたら出力を調整します。",
        mixerHeadphonesDisconnectVolume: "切断後の音量",
        preciseVolumeRollerEnable: "より細かい音量ステップを使う",
        preciseVolumeRollerCaption: "音量ホイールやキーを、より小さなシステム音量ステップに変換します。",
        preciseVolumeRollerTapFailed: "音量キーを監視できませんでした。",
        soundOutputSwitcherTitle: "出力切り替え",
        soundOutputSwitcherEnable: "ショートカットで出力を切り替える",
        soundOutputSwitcherCaption: "出力を選び、ショートカットで次に利用可能な出力へ切り替えます。",
        soundOutputSwitcherDevices: "切り替える出力",
        soundOutputSwitcherNoAvailableSelection: "利用可能な出力を1つ以上選択してください。",
        mixerInputTitle: "マイク",
        mixerInputNoDevices: "マイクが見つかりません",
        mixerInputUnavailable: "マイクを利用できません",
        mixerInputFallback: "このマイクが戻るまでデフォルトを使用します。",
        mixerInputTooltip: "マイクを選択",
        mixerInputErrorFormat: "変更できませんでした: %@",
        mixerVisibleApps: "リストに表示するアプリ",
        mixerAllShown: "すべて",
        mixerHiddenCountLabel: "非表示",
        mixerHideFromList: "リストから隠す",

        updatesSection: "アップデート",
        autoCheckToggle: "アップデートを自動的に確認",
        includeBetaUpdatesToggle: "ベータ版のアップデートを受け取る",
        includeBetaUpdatesCaption: "ベータ版には開発中の機能が含まれており、動作が不安定な場合があります。",
        betaBadgeLabel: "ベータ",
        checkNowButton: "今すぐ確認",
        updateChecking: "確認中…",
        updateUpToDate: "最新バージョンを使用しています。",
        updateAvailablePrefix: "アップデートが利用できます：",
        updateInstallButton: "ダウンロードしてインストール",
        updateDownloading: "アップデートをダウンロード中…",
        updateInstalling: "インストールして再起動中…",
        updateFailedPrefix: "確認できませんでした：",
        updateLastChecked: "前回の確認：",
        updateNotifyTitle: "Vorssaint のアップデート",
        updateInstallFailedBody: "アップデートはダウンロードされましたが、適用できませんでした。GitHub のリリースページから最新版をダウンロードし、現在のアプリの上にドラッグして置き換えてください。",
        updateNeedsApplicationsTitle: "Vorssaint を「アプリケーション」に移動してください",
        updateNeedsApplicationsBody: "アプリが、ディスクイメージやシステムの一時的な場所など、アップデートできない場所から実行されています。Vorssaint を「アプリケーション」フォルダにドラッグし、そこから開いてからもう一度お試しください。",
        menuCheckUpdates: "アップデートを確認…",

        permissionRequired: "アクセス権が必要です",
        permissionAccessibility: "アクセシビリティ",
        permissionScreenRecording: "画面収録",
        permissionGranted: "許可済み",
        permissionMissing: "未許可",
        permissionOpenSettings: "システム設定を開く…",
        permissionRequest: "アクセスを許可",
        permissionRestartNote: "許可後、macOS がアプリの再オープンを求めることがあります。",

        aboutDescription: "あなたの Mac のためのユーティリティハブ。\n省エネルギー、システムモニタ、スクロール、ウインドウスイッチャーを、メニューバーから。",
        versionPrefix: "バージョン",
        reviewIntro: "はじめにを見直す",
        reviewHighlights: "新機能ツアーを見直す",
        viewOnGitHub: "GitHub で見る",

        obContinue: "続ける",
        obBack: "戻る",
        obSkipStep: "このステップをスキップ",
        obStart: "Vorssaint を開く",
        obStepWelcomeTitle: "Vorssaint へようこそ",
        obStepWelcomeBody: "日々の macOS をもっと快適にする、控えめなメニューバーユーティリティです。",
        obWelcomeBullet1Title: "省エネルギーを思いどおりに",
        obWelcomeBullet1Body: "ふたを閉じたままでも、好きなだけ Mac をスリープさせずに使えます。",
        obWelcomeBullet2Title: "システムをひと目で把握",
        obWelcomeBullet2Body: "CPU・GPU・バッテリーの温度、ハードウェア使用状況、メモリプレッシャーをリアルタイムで。",
        obWelcomeBullet3Title: "マウスとウインドウを自分流に",
        obWelcomeBullet3Body: "マウスのスクロール反転と、サムネール付きのウインドウスイッチャー。",
        obLanguageLabel: "言語",
        obStepAccessibilityTitle: "アクセシビリティ",
        obStepAccessibilityBody: "マウスのスクロールを反転したり、ウインドウスイッチャーがキーボードに反応したりするために必要です。",
        obAccessibilityWhy: "アプリが監視するのはマウスホイールとスイッチャーのショートカットだけです。記録したり、どこかに送信したりすることはありません。",
        obStepRecordingTitle: "画面収録",
        obStepRecordingBody: "スイッチャーで、アイコンだけでなく実際のウインドウのサムネールを表示できるようになります。",
        obRecordingWhy: "サムネールはその場で生成され、メモリ内にとどまり、Mac の外に出ることはありません。許可しなくても、スイッチャーはアイコンで動作します。",
        obStepMonitorTitle: "システムモニタ",
        obStepMonitorBody: "パネルに CPU・GPU・バッテリーの温度、ハードウェア使用状況、メモリプレッシャーが表示されます。",
        obMonitorNoPermission: "アクセス権は不要です。センサーはシステムから直接読み取られます。",
        obStepOptionalTitle: "オプション機能",
        obStepOptionalBody: "今すぐ使いたいものをオンにしてください。すべて後から設定で変更できます。",
        obStepStatusTitle: "チェック",
        obStepStatusBody: "使いたい機能の準備がすべて整っているか確認します。",
        obStatusRecheck: "もう一度確認",
        obStepDoneTitle: "準備完了！",
        obStepDoneBody: "Vorssaint はすでにあなたの Mac を見守っています。",
        obDoneHint: "画面右上のメニューバーで、ブラックホールを探してください。",
        obWhatsNewTitle: "このバージョンの新機能",
        obWhatsNewFallback: "このアップデートには最新の修正と改善が含まれています。",
        obLanguageUpdateTitle: "あなたの言語に対応",
        obLanguageUpdateBody: "Vorssaint が複数の言語に対応しました。使いたい言語を選んでください。設定でいつでも変更できます。",
        obPurposeTitle: "目的を教えてください",
        obPurposeBody: "用意された設定か、使いたい機能を一つずつ選んでください。",
        obPurposeSkip: "機能は後から設定で追加または削除できます。",

        tabMonitor: "モニタ",
        monitorMenuBarSection: "メニューバー",
        monitorMenuBarCaption: "メニューバーのアイコンの横に表示する項目を選びます。",
        monitorCombineTemperatures: "使用率と温度をまとめる",
        monitorCombineTemperaturesCaption: "同じ項目の使用率と温度が有効な場合、1つのブロックにまとめて表示します。",
        monitorSeparateMenuBarMetrics: "メトリクスを個別の項目に分ける",
        monitorSeparateMenuBarMetricsCaption: "有効なブロックをメニューバーで分け、結合がオンなら使用率と温度は一緒に表示します。",
        monitorNetworkUploadFirst: "アップロードをダウンロードの上に表示",
        monitorShowCPU: "CPU",
        monitorShowMemory: "メモリ",
        monitorShowNetwork: "ネットワーク",
        monitorShowPowerLabel: "電源",
        monitorIntervalLabel: "更新間隔",
        monitorInterval1: "1秒",
        monitorInterval2: "2秒",
        monitorInterval5: "5秒",
        monitorPanelSection: "パネル",
        panelNavigationMode: "パネルをセクションごとに移動",
        panelNavigationCaption: "1つのセクションだけを表示します。「リスト」を選ぶと、すべてを連続スクロールで表示します。",
        panelFooterSections: "セクション",
        panelFooterList: "リスト",
        betaBadge: "BETA",
        betaFeatureWarning: "ベータ版です。一部の不具合が残っている場合があります。",

        networkSection: "ネットワーク",
        networkDownload: "ダウンロード",
        networkUpload: "アップロード",
        networkThisSession: "このセッション",
        networkMeasuring: "計測中…",
        networkApps: "通信中のアプリ",
        networkAppsIdle: "現在ネットワークを使用中のアプリはありません",

        diskSection: "ディスク",
        diskUsed: "使用済み",
        diskFree: "空き",
        diskAvailable: "利用可能",
        diskPurgeable: "パージ可能",
        diskInternal: "内蔵",
        diskExternal: "外部",
        diskSelect: "ディスクを選択",
        diskRead: "読み込み",
        diskWrite: "書き込み",
        diskSMARTStatus: "状態",
        diskSMARTUnavailable: "このディスクでは SMART を利用できません",
        diskTotalRead: "総読み込み",
        diskTotalWritten: "総書き込み",
        diskTemperature: "温度",
        diskHealth: "健康状態",
        diskPowerCycles: "電源投入回数",
        diskPowerOnHours: "通電時間",
        diskUnsafeShutdowns: "安全でない終了",
        diskMediaErrors: "メディアエラー",
        diskEject: "取り出す",
        diskEjectAll: "すべて取り出す",
        diskEjecting: "取り出し中…",
        diskReadyToRemove: "取り外せます",
        diskEjectFailed: "取り出せませんでした",
        diskProtectionCaption: "抜く前に取り出します。",
        diskNoExternal: "取り出せる外部ディスクはありません。",
        diskOpenInFinder: "開く",
        diskStorageSettings: "ストレージ",
        diskNoDisks: "マウント済みディスクが見つかりません。",

        powerSection: "電源",
        powerSystem: "システム",
        powerAdapter: "アダプタ",
        powerBattery: "バッテリー",
        powerCharging: "充電中",
        powerOnBattery: "バッテリー駆動",
        powerPluggedIn: "電源に接続",
        powerUnavailable: "この Mac では電源の計測値を利用できません",
        powerAdapterMaxFormat: "最大 %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU温度",
        monitorShowGPUTemperature: "GPU温度",
        monitorShowBatteryTemperature: "バッテリー温度",
        monitorShowPeripheralBattery: "周辺機器のバッテリー",
        peripheralBatteryNoDevices: "周辺機器が見つかりません",
        monitorGraphsSection: "グラフ",
        monitorGraphsCaption: "経過に応じてグラフを表示する項目を選びます。",

        updateBannerTitle: "アップデートが利用できます",
        updateBannerAction: "アップデート",
        obStepMenuBarTitle: "メニューバーの計測値",
        obStepMenuBarBody: "アイコンの横に表示する項目を選びます。上のプレビューがリアルタイムで更新されます。",
        obStepMenuBarNote: "新機能：パネルのネットワークと電源のブロック、そしてグラフ。すべて後から設定 › モニタで微調整できます。",
        monitorMenuBarPresetLabel: "スタイル",
        menuBarPresetReadable: "読みやすい",
        menuBarPresetDense: "高密度",
        menuBarSpacingLabel: "メニューバーの間隔",
        menuBarSpacingStandard: "標準",
        menuBarSpacingCompact: "コンパクト",
        menuBarHideIconToggle: "メトリクス表示中はアプリのアイコンを隠す",
        menuBarHideIconCaption: "メトリクスがバーから消えたときや、知らせることがあるとき（アップデートの準備完了やマイクの消音）は、アイコンが自動的に戻ります。",
        monitorLabelStyleLabel: "ラベル",
        menuBarLabelStyleCompact: "短縮",
        menuBarLabelStyleClassic: "標準",
        monitorMemoryStyleLabel: "メモリの表示",
        monitorMemoryPressureDot: "メモリ圧力ドット",
        memoryStyleDot: "ドット",
        memoryStylePercent: "%",
        memoryStyleBoth: "両方",
        systemUptime: "稼働時間",
        batteryCharge: "充電量",
        powerHealth: "バッテリーの状態",
        powerCycles: "充放電回数",
        speedTestRun: "速度テスト",
        speedTestAgain: "もう一度テスト",
        speedTestLatency: "レイテンシ",
        speedTestTesting: "テスト中…",
        speedTestFailed: "テストに失敗しました",

        monitorShowInPanel: "パネルに表示",
        disclosureExpanded: "展開済み",
        disclosureCollapsed: "折りたたみ済み",
        panelHideItem: "パネルで非表示",
        panelShowItem: "パネルに表示",
        panelHiddenItem: "非表示",
        monitorItemUptime: "稼働時間",
        monitorItemNetSpeed: "リアルタイム速度",
        monitorItemNetTotals: "セッション合計",
        monitorItemNetTest: "速度テスト",
        monitorItemDiskUsage: "ディスク使用量",
        monitorItemDiskActivity: "ライブ活動",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "外部保護",
        monitorItemDiskTools: "ツール",
        monitorPanelConfigHint: "ブロックを開いて、表示する内容を選びます。",
        monitorOrderSection: "セクションの並び順",
        monitorOrderHint: "ドラッグしてパネルのセクションを並べ替え、目のアイコンで各セクションを表示/非表示にできます。",
        obStepPanelTitle: "パネルに表示する内容",
        obStepPanelBody: "各ブロックを開いて、アイコンをクリックしたときに表示する内容を細かく選びます。",
        obStepPanelNavigationTitle: "セクション式パネル",
        obStepPanelNavigationBody: "パネルで1つのセクションだけを表示できるようになりました。設定で「セクション」と「リスト」を切り替えられます。",

        cleaningMenuItem: "クリーニングモード",
        utilitiesSection: "ユーティリティ",
        quickControlsSection: "コントロール",
        panelCategoryWindows: "ウインドウ",
        panelCategoryInput: "マウスとキーボード",
        panelCategoryFiles: "ファイル",
        windowMaximizeName: "ウインドウを最大化",
        windowMaximizeCaption: "緑のボタンで別のスペースを作らず最大化します。",
        windowMaximizeActiveNow: "緑のボタンで有効",
        windowMaximizeNeedsAccessibility: "動作にはアクセシビリティが必要です。",
        keyDebounceName: "デバウンス",
        keyDebounceEnable: "重複キーをフィルタ",
        keyDebounceCaption: "非常に速い重複入力をフィルタします。",
        keyDebounceActiveNow: "フィルタ有効",
        keyDebounceGlobalWindow: "全体の時間",
        keyDebouncePerKeySection: "個別キー",
        keyDebouncePerKeyCaption: "キーごとの値は全体の時間より優先されます。0 ms にするとそのキーはフィルタされません。",
        keyDebounceKeyLabel: "キー",
        keyDebounceWindowLabel: "時間",
        keyDebounceAddKey: "キーを追加",
        keyDebounceNoOverrides: "個別キーは設定されていません。",
        keyDebounceRemoveKey: "キーを削除",
        cleaningPanelCaption: "安全に掃除できるようキーボードをロックします。",
        cleaningOverlayTitle: "クリーニングのためキーボードをロック中",
        cleaningOverlaySubtitle: "Escキーを5回押すとロックを解除します",
        cleaningOverlayUnlock: "ロックを解除",
        cleaningOverlayMouseHint: "マウスとトラックパッドはそのまま使えます",
        cleaningKeepScreenVisibleToggle: "画面を表示したままにする",
        cleaningKeepScreenVisibleCaption: "画面を暗くせず、画面の隅に控えめなインジケータを表示します。",
        cleaningStartNow: "今すぐキーボードをロック",
        cleaningNeedsAxTitle: "アクセシビリティが必要です",
        cleaningNeedsAxBody: "キーボードを安全にロックするには、Vorssaint にアクセシビリティのアクセス権が必要です。システム設定で許可して、もう一度お試しください。",

        tabSupport: "支援",
        shortcutsPageCaption: "このMacにインストールされている機能のグローバルショートカットをすべてここで編集できます。無効なものも保存されますが、動作はしません。",
        shortcutsPageTitle: "キーボードショートカット",
        settingsSearchPlaceholder: "設定を検索",
        donateHeading: "Vorssaint の成長を支える",
        donateMessage: "Vorssaint は無料で独立したアプリとして、わたしの空き時間に開発しています。金銭的に支援したい場合は、Buy Me a Coffee が開発の継続に直接役立ちます。",
        donateButton: "Buy Me a Coffee で支援する",
        donateThanks: "来てくれてありがとう。🖤",
        supportIntroTitle: "Vorssaint の成長を支える",
        supportIntroMessage: "開発を金銭的に支援したい場合は、Buy Me a Coffee が唯一の窓口です。",
        supportIntroStarButton: "GitHub で Vorssaint にスターを付ける",
        supportIntroStarMessage: "金銭的な支援は決して必要ではありません。GitHub のスターは、より多くの人が Vorssaint を見つける助けになり、開発にも大きな力になります。",
        supportIntroCoffeeButton: "Buy Me a Coffee で支援する",
        supportIntroLaterButton: "今はしない",
        supportIntroDoneButton: "完了",
        discordIntroTitle: "VorssaintのDiscordコミュニティが始まります",
        discordIntroMessage: "Vorssaint コミュニティは新しく、まだ成長の途中です。早い段階から参加して他のユーザーと出会い、アプリを囲む心地よい場所を一緒につくりましょう。",
        discordIntroJoinButton: "Discord コミュニティに参加",
        communityIntroTitle: "誰よりも先に新機能をチェック",
        communityIntroMessage: "すでにXでフォローしてくれていた人は、今回のアップデートに含まれるいくつもの変更を誰よりも早く知っていました。Xでは次に登場する機能のプレビューや使い方を紹介しているので、アップデートの公開前から基本を知ることができます。フォローして次の新機能をチェックしてください！",
        communityIntroFollowButton: "Xで@vorssaintをフォロー",
        homebrewOfficialIntroTitle: "Homebrew 公式カタログに登場",
        homebrewOfficialIntroMessage: "Vorssaint を Homebrew 公式カタログから直接インストールできるようになりました。",
        homebrewOfficialIntroInstallLabel: "新規インストール",
        homebrewOfficialIntroMigrationTitle: "以前の tap を使っていましたか？",
        homebrewOfficialIntroMigrationMessage: "以前の tap を一度削除してください。アプリと設定はそのまま残ります。",
        homebrewOfficialIntroCopyButton: "コマンドをコピー",
        updateShowcaseTitle: "3.1.4 の新機能",
        updateShowcaseMessage: "このアップデートの主な改善点を短いプレビューで確認できます。",
        updateShowcaseUnavailable: "今は動画を読み込めません。続けることはできます。",
        updateShowcaseRestart: "最初に戻る",
        showMenuBarIcon: "メニューバーにアイコンを表示",
        showMenuBarIconCaption: "Vorssaint のアイコンが消えた場合（メニューバーに空きがなくなると macOS がアイコンを隠すことがあり、ノッチのある Mac でよく起こります）、アプリケーションまたは Spotlight から Vorssaint を開き直してください。アイコンが再作成され、それでも隠れている場合はこのウインドウが開きます。",
        menuBarIconStillHiddenTitle: "アイコンはまだ隠れています",
        menuBarIconStillHiddenBody: "アイコンを作り直しましたが、macOS が表示できる場所を割り当てませんでした。メニューバーに空きがない可能性が高いので、メニューバーのアイコンをいくつか減らす（またはメニューの長いアプリを閉じる）してから、もう一度お試しください。",
        menuBarIconManagerHintFormat: "%@ が起動中で、アイコンを隠しセクションにしまっている可能性があります。そこで Vorssaint を探すか、%@ で Vorssaint を常に表示する設定にしてください。",
        shortcutRecording: "新しいショートカットを押してください",
        shortcutReset: "リセット",
        shortcutNone: "なし",
        shortcutClear: "ショートカットを削除",
        shortcutInvalid: "Control、Option、Command のいずれかとキーを組み合わせてください。",
        shortcutPressKeys: "キーを押す",
        shortcutEscapeHint: "Esc で取り消します。",
        shortcutDeleteHint: "Delete で解除します。",
        shortcutNotCaptured: "何も取得できませんでした。この組み合わせは macOS か別のアプリがすでに使っています。別のものを選んでください。",
        shortcutConflictFormat: "このショートカットはすでに %@ で使われています。",
        shortcutUnavailable: "macOS がこのショートカットを拒否しました。別のものを選んでください。",
        shelfShortcutToggle: "Shelf ショートカット",
        switcherUsageHintFormat: "%@ を押したまま移動し、放すとウインドウがアクティブになります。Shift または ← で戻る、W でウインドウを閉じ、Q でアプリを終了、Esc でキャンセルします。",
        musicBlockSection: "メディアキー",
        musicBlockTitle: "ミュージックが勝手に開かないようにする",
        musicBlockCaption: "メディアキーを押してもミュージックアプリは開かなくなります。自分で開くことはできます。",
        musicBlockReplacementLabel: "代わりに開く",
        musicBlockReplacementNone: "なし",
        musicBlockChooseApp: "アプリを選択…",
        cleanerName: "クリーンアップ",
        cleanerIntroTitle: "Mac の不要ファイルを掃除",
        cleanerIntroCaption: "アンインストール済みアプリの残骸、キャッシュ、ログ、ゴミ箱を調べます。実行前にすべて確認でき、削除した項目はゴミ箱に移動します。",
        cleanerScan: "スキャン",
        cleanerScanning: "スキャン中…",
        cleanerCleaning: "クリーンアップ中…",
        cleanerCatLeftovers: "アンインストール済みアプリの残骸",
        cleanerCatLoginItems: "孤立したログイン項目",
        cleanerCatCaches: "キャッシュ",
        cleanerCatLogs: "ログ",
        cleanerCatDeveloper: "開発ジャンク",
        cleanerCatTrash: "ゴミ箱",
        cleanerLeftoversNote: "解析による検出のため最初はオフです。チェックする前にパスを確認してください。",
        cleanerLoginItemsNote: "ログイン項目の表示は Mac の再起動後に消えます。",
        cleanerTrashNote: "ゴミ箱を空にすると元に戻せません。",
        cleanerCatDeviceBackups: "iPhoneのバックアップ",
        cleanerDeviceBackupsCaption: "古いiPhoneやiPadのバックアップは、macOSが「その他」と呼ぶ領域の大部分を占めます。不要なものだけを削除してください。次に接続すると新しいバックアップが作られます。",
        cleanerNothingFound: "掃除するものはありません。Mac は整っています。",
        cleanerClean: "クリーンアップ",
        cleanerDoneNote: "項目はゴミ箱に移動され、そこから復元できます。",
        cleanerAgain: "もう一度スキャン",
        cleanerRevealInFinder: "Finder に表示",
        cleanerPanelCaption: "アプリの残骸、キャッシュ、ログ",
        cleanerSafeSection: "安全なクリーンアップ",
        cleanerOptionalSection: "オプション、先に確認",
        cleanerCatOtherCaches: "その他のキャッシュ",
        cleanerCachesCaption: "アプリが自動で作り直す一時ファイルです。",
        cleanerLogsCaption: "古い診断ログです。",
        cleanerDeveloperCaption: "Xcode のビルドとシミュレータの残骸です。",
        cleanerLoginItemsCaption: "もう存在しないアプリが残したログイン項目です。",
        cleanerLeftoversCaption: "アンインストールしたアプリが残したファイルです。",
        cleanerOtherCachesCaption: "削除しても安全で、壊れるものはありません。初回起動が少し遅くなり、オフライン音楽などのダウンロード済みコンテンツは再ダウンロードされます。",
        cleanerCleanSizeFormat: "%@ をクリーンアップ",
        cleanerScheduleTitle: "自動クリーンアップ",
        cleanerScheduleOff: "オフ",
        cleanerScheduleDaily: "毎日",
        cleanerScheduleWeekly: "毎週",
        cleanerScheduleCaption: "選んだ時刻に安全な部分だけを自動で掃除し、すべてゴミ箱に移動します。",
        cleanerScheduleLastFormat: "前回の自動クリーンアップで %@ 解放されました。",
        cleanerAutoNotificationFormat: "%@ を解放してゴミ箱に移動しました。",
        cleanerScheduleNextFormat: "次のクリーンアップは %@。",
        cleanerScheduleRanFormat: "前回の自動クリーンアップは %@。",
        cleanerScheduleNotifyToggle: "完了時に通知",
        cleanerNotifDenied: "Vorssaint の通知がシステムでオフになっています。",
        cleanerNotifOpenSettings: "通知設定を開く…",
        launchAtLoginNeedsApplications: "ログイン時に開けない場所からアプリが実行されています。Vorssaintをアプリケーションフォルダにドラッグし、そこから開いてもう一度オンにしてください。",
        launchAtLoginNeedsApproval: "ログイン項目は登録されていますが、システム設定ではオフのままです。「システム設定 › 一般 › ログイン項目と機能拡張」を開き、「ログイン時に開く」でVorssaintをオンにしてください。",
        ocrRemoveLineBreaksToggle: "改行を削除",
        ocrRemoveLineBreaksCaption: "認識したテキストの改行を取り除き、1つの段落としてペーストします。",
        ocrQRToggle: "QRコードを読み取る",
        ocrQRCaption: "選択した範囲にQRコードがあると、その内容をコピーまたは開けるように表示します。",
        ocrQRCopied: "QRコードをコピーしました",
        qrResultTitle: "QRコード",
        qrResultCopy: "コピー",
        qrResultOpen: "リンクを開く",
        highlightsTitle: "このアップデートの新機能",
        highlightsTitleClipboardRedesign: "クリップボードの再設計",
        highlightsTitleWindowLayout: "ウィンドウの配置",
        highlightsTitleQuitProtection: "⌘Qと⌘Wの保護",
        highlightsTitleRecorderBlur: "画面録画のプライバシーぼかし",
        highlightsCaptionDockPreview: "Dock Preview がDockの拡大がオンのままでも動作するようになりました",
        highlightsCaptionScreenshot: "スクリーンショットにピクセルルーペとQRコードの読み取りが加わりました",
        highlightsCaptionSnippetLibrary: "検索できるスニペットメニューがカーソル位置にスニペットを入力します",
        highlightsCaptionCapturePalette: "1つのショートカットで、スクリーンショット、録画、画面テキスト、カラーの取得と各種設定が手元で操作できるフローティングパレットが開きます。",
        highlightsCaptionClipboardRedesign: "履歴はすっきりした行と、項目全体を読んだり編集したりできるオンデマンドプレビューを備えたコンパクトなパレットとして開くようになります。",
        highlightsCaptionWindowLayout: "ショートカットとポインタによる方向リングでの配置や、画面端へのドラッグによる間隔調整付きスナップに対応しました。",
        highlightsCaptionQuitProtection: "長押しや2回押し、追加の修飾キーを必要にすることで、アプリやウィンドウの誤終了を防ぎます。アプリごとに設定可能です。",
        highlightsCaptionRecorderBlur: "保存や書き出しの前に、録画ビデオの指定した領域や時間帯でパスワードや個人情報をぼかして隠せます。",
        highlightsConfigure: "設定する",
        highlightsTry: "試す",
        highlightsSeeAll: "すべての変更を見る",
        switcherCurrentSpaceOnly: "現在のデスクトップのみ表示",
        switcherCurrentSpaceOnlyCaption: "今いるデスクトップのウインドウだけをスイッチャーに表示します。ウインドウを選んでも別のデスクトップには移動しません。",
        shelfFileMissing: "ファイルはもう存在しません",
        previewSizeSmall: "小",
        mixerSoundEffectsOutputTitle: "システムサウンド",
        mixerSoundEffectsOutputTooltip: "通知音とサウンドエフェクトの出力先を選択",
        monitorOpenActivityMonitor: "アクティビティモニタを開く",
        dockClickHide: "Dock クリックでアプリを隠す",
        dockClickHideCaption: "手前のアプリの Dock アイコンをクリックすると、そのアプリを隠します。もう一度クリックすると戻ります。",
        monitorMemoryMetricLabel: "メモリの測定方法",
        memoryMetricUsed: "使用中のメモリ",
        memoryMetricApp: "Appメモリ",
        keepAwakeRightClickToggle: "メニューバーアイコンの右クリックでスリープ防止を切り替える",
        keepAwakeRightClickToggleCaption: "右クリックのコンテキストメニューを置き換えます。",
        urlCleanerRulesTitle: "クリーンのルール",
        urlCleanerRulesCaption: "サイトが自身の共有リンクに付ける、どこから来たリンクかを追跡するためのパラメータです。チェックを入れた名前はリンクの整理時に削除され、外すと残ります。自分で追加した名前は削除できます。",
        urlCleanerRulesCoverageCaption: "一覧はサイトごとの共有経路（ウェブページ、アプリ、ライブルーム）をまとめて扱うため長くなります。実際のリンクが持つのは通常 2〜4 個です。",
        urlCleanerRulesAllSites: "すべてのサイト",
        urlCleanerRulesCountSingular: "パラメータ 1 個",
        urlCleanerRulesCountPluralFormat: "パラメータ %d 個",
        urlCleanerRulesAddSite: "サイトを追加",
        urlCleanerRulesParameterPlaceholder: "パラメータ名",
        urlCleanerRulesMatchCaption: "= の左側の名前を入力します（例：utm_source）。一致した名前はそのパラメータだけをリンクから取り除き、ほかはそのまま残します。",
        urlCleanerRulesAddButton: "追加",
        urlCleanerRulesRemoveButton: "名前を削除",
        urlCleanerRulesRemoveSiteButton: "このサイトのルールをすべてオフにする",
        urlCleanerRemovedFormat: "%@ を削除しました",
        switcherSearchPin: "S で検索欄を固定",
        switcherSearchPinCaption: "S を押すと検索を開始して切り替え画面を固定表示にします。ショートカットが ⌥ を使う場合の特殊文字入力も、Q や W で始める検索によるウインドウを閉じる/アプリを終了する誤動作も防げます。",
        invertVerticalScroll: "縦スクロールを反転",
        invertHorizontalScroll: "横スクロールを反転",
        switcherShowShortcutHints: "ショートカットのヒントを表示",
        switcherShowShortcutHintsCaption: "アイコンの下にアプリとウインドウのショートカットを表示します。",
        uninstallerHomebrewPackageFormat: "%@ も Homebrew から削除されます。",
        shelfEdgeToggle: "画面の端に近づけたら開く",
        shelfEdgeCaption: "ファイルを画面の端に向けてドラッグすると、シェルフが少しだけ現れます。そこでドロップするか、手を戻すとシェルフは引っ込みます。",
        focusFollowsMouseName: "マウス追従フォーカス",
        focusFollowsMouseCaption: "短い停止後、ポインタの下にあるウインドウをフォーカスして手前に表示します。",
        focusFollowsMouseDelay: "ホバー遅延",
        switcherMinimizedPlacementLabel: "最小化されたウインドウ",
        switcherMinimizedPlacementNormal: "通常の順序",
        switcherMinimizedPlacementEnd: "最後に配置",
        switcherMinimizedPlacementHidden: "非表示",
        switcherShowFullscreenWindows: "フルスクリーンのウインドウを表示",
        switcherScreenPlacementLabel: "表示先",
        switcherScreenPlacementPointer: "ポインタのある画面",
        switcherScreenPlacementMenuBar: "メニューバーのある画面",
        switcherScreenPlacementActiveWindow: "アクティブなウインドウのある画面",
        switcherScreenPlacementCaption: "複数の画面を接続しているとき、スイッチャーをどの画面に表示するかを選びます。",
        smoothScrollResponseLabel: "反応",
        mouseAccelerationName: "マウス加速を無効にする",
        mouseAccelerationCaption: "接続したマウスのポインタ加速を無効にします。オフにするか Vorssaint を終了すると以前の設定に戻ります。",
        shelfClearOnClose: "閉じるときに項目を消去",
        shelfClearOnCloseCaption: "閉じるボタンをクリックしたときだけシェルフを空にします。自動的に隠れた場合や折りたたんだ場合は項目を保持します。"
    )
}
