// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// 简体中文 — translated and hand-checked, not machine output.
extension Strings {
    static let zhHans = Strings(
        statusIdleTooltip: "Vorssaint：正常睡眠",
        statusActiveUntil: "Vorssaint：唤醒至",
        statusActiveIndefinite: "Vorssaint：持续唤醒",
        menuEnableAwake: "开启保持唤醒",
        menuDisableAwake: "关闭保持唤醒",
        menuActivateFor: "启用时长…",
        menuSettings: "设置…",
        menuAbout: "关于 Vorssaint",
        menuQuit: "退出 Vorssaint",
        menuHide: "隐藏 Vorssaint",
        menuHideOthers: "隐藏其他",
        menuShowAll: "全部显示",
        menuEdit: "编辑",
        menuUndo: "撤销",
        menuRedo: "重做",
        actionClear: "清除",
        actionRemove: "移除",
        actionBack: "返回",
        actionSearch: "搜索",
        actionMute: "静音",
        actionUnmute: "取消静音",
        actionPlay: "播放",
        actionPause: "暂停",
        menuCut: "剪切",
        menuCopy: "拷贝",
        menuPaste: "粘贴",
        menuSelectAll: "全选",
        menuWindow: "窗口",
        menuMinimize: "最小化",
        menuZoom: "缩放",
        menuClose: "关闭",

        minutes15: "15 分钟",
        minutes30: "30 分钟",
        hour1: "1 小时",
        hours2: "2 小时",
        hours4: "4 小时",
        hours8: "8 小时",
        indefinitely: "持续不限",
        indefinite: "不限时",

        panelSettings: "设置",
        panelQuit: "退出",
        panelHotkeyHint: "快捷键切换",

        keepAwakeTitle: "保持唤醒",
        keepAwakeEndsIn: "剩余时间",
        keepAwakeUntilDisabled: "保持启用直到你手动关闭",
        keepAwakeNormalRules: "Mac 遵循正常的能源规则",
        keepAwakeOptions: "选项",
        keepAwakeMouseJiggle: "轻微移动指针",
        keepAwakeMouseJiggleCaption: "会话期间按所选间隔轻微移动指针。",
        keepAwakeMouseJiggleInterval: "间隔",
        keepAwakeActiveIconLabel: "活跃图标",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "咖啡",
        keepAwakeActiveIconEye: "眼睛",
        keepAwakeActiveIconMoon: "月亮",
        keepAwakeActiveIconLight: "灯泡",
        keepAwakeIconTintLabel: "启用时图标颜色",
        keepAwakeIconTintOrange: "橙色",
        keepAwakeIconTintGreen: "绿色",
        keepAwakeIconTintBlue: "蓝色",
        keepAwakeIconTintPurple: "紫色",
        keepAwakeIconTintPink: "粉色",
        keepAwakeIconTintNone: "无颜色",
        durationLabel: "时长",
        clamshellTitle: "合盖后继续运行",
        clamshellOnCaption: "已完全禁用睡眠，请注意电量",
        clamshellNeedsSession: "每当“保持唤醒”启用时生效",
        clamshellReady: "已就绪，切换时无需密码",
        clamshellNeedsPassword: "只会要求输入一次管理员密码",

        systemSection: "系统",
        temperatures: "温度",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "电池",
        usageSection: "硬件占用",
        memorySection: "内存",
        memoryPressure: "压力",
        memorySwapUsed: "已用交换空间",
        memoryCompressed: "已压缩",
        memoryCachedFiles: "已缓存的文件",
        pressureNormal: "正常",
        pressureWarning: "注意",
        pressureCritical: "严重",
        monitorUnavailable: "此 Mac 上无可用传感器",
        energyAppsTitle: "显著耗能",
        energyAppsIdle: "无显著耗能",

        notifySessionEndedTitle: "会话已结束",
        notifySessionEndedBody: "时间到。Mac 将恢复正常睡眠。",
        notifyBatteryTitle: "Vorssaint 已关闭",
        notifyBatteryBody: "电量过低。已恢复正常睡眠以保护电量。",
        adminPromptClamshellOn: "Vorssaint 需要您的密码才能在合盖后继续运行。",
        adminPromptClamshellOff: "Vorssaint 需要您的密码才能恢复 Mac 的正常睡眠。",
        adminPromptRecover: "Vorssaint 在 Mac 睡眠被禁用时退出了。请输入您的密码以恢复正常睡眠。",
        adminPromptUpdate: "Vorssaint 需要您的密码来安装更新。",
        adminPromptSudoersInstall: "Vorssaint 将创建一条受限规则（仅限 pmset disablesleep），用于切换合盖模式时无需输入密码。这是唯一一次需要您输入密码。",
        adminPromptSudoersRemove: "Vorssaint 将为您移除免密码的合盖规则。",

        settingsTitle: "Vorssaint 设置",
        tabGeneral: "通用",
        tabEnergy: "能源",
        tabMouse: "鼠标与触控板",
        tabSwitcher: "切换器",
        tabAdvanced: "高级",
        tabAbout: "关于",
        tabReleaseNotes: "新功能",
        releaseNotesOnUpdateToggle: "更新后显示新功能",
        minimalWindowPreviews: "简洁预览",
        minimalWindowPreviewsCaption: "隐藏程序坞和应用切换器预览中的标题、按钮和装饰，保留选中标记。",
        previewSizeLabel: "预览大小",
        previewSizeNormal: "正常",
        previewSizeLarge: "大",
        previewSizeXLarge: "特大",
        settingsGroupFeatures: "功能",
        advancedResetSection: "权限",
        advancedResetDescription: "移除你授予 Vorssaint 的所有权限（辅助功能、屏幕录制、完全磁盘访问权限等）、登录项以及合盖规则。适合重新开始或卸载前使用。App 仍保持安装状态。",
        advancedClearButton: "清除所有权限",
        advancedCleared: "权限已清除。",
        advancedClearConfirmTitle: "清除所有权限？",
        advancedClearConfirmBody: "依赖权限的功能将停止工作，直到你重新授予。你的设置会保留。",
        advancedUninstallSection: "卸载",
        advancedUninstallDescription: "执行以上全部操作，然后移除偏好设置并将 Vorssaint 移到废纸篓，不留任何痕迹。完成后 App 会退出。你可以随时重新安装。",
        advancedUninstallButton: "完全卸载 Vorssaint",
        advancedUninstallConfirmTitle: "卸载 Vorssaint？",
        advancedUninstallConfirmBody: "Vorssaint 将清除其权限、移除偏好设置并移到废纸篓，然后退出。此操作无法从 App 内撤销，但在你清倒废纸篓之前它仍会留在其中。",
        advancedUninstallFailedTitle: "已停止卸载",
        advancedUninstallFailedBody: "Vorssaint 无法还原它更改过的系统设置：睡眠、风扇转速或鼠标加速。没有移除任何内容。请重试，并在出现密码请求时允许。",

        launchAtLogin: "登录时启动",
        languageLabel: "语言",
        menuBarSection: "菜单栏",
        showCountdown: "在图标旁显示剩余时间",
        globalHotkeySection: "全局快捷键",
        hotkeyToggle: "启用“保持唤醒”快捷键",
        hotkeyCaption: "在任何 App 中都有效，无需额外权限。",

        sessionSection: "会话",
        defaultDurationLabel: "默认时长",
        keepAwakeAutoStart: "打开 Vorssaint 时保持唤醒",
        keepAwakeAutoStartCaption: "使用默认时长启动会话。",
        batteryProtectionSection: "电池保护",
        batteryDisableBelow: "电量低于以下值时关闭",
        batteryNever: "从不",
        batteryProtectionCaption: "避免被遗忘的会话耗尽 MacBook 的电量。",
        clamshellSection: "合盖",
        configuring: "配置中…",
        sudoersFailed: "无法启用合盖模式。请重试。",
        clamshellExplanation: "“合盖后继续运行”会在“保持唤醒”启用期间完全禁用睡眠，并在会话结束或 App 退出时自动恢复。建议在接通电源时使用。",

        scrollSection: "滚动",
        invertMouseScroll: "反转鼠标滚动",
        invertMouseScrollCaption: "反转鼠标滚轮的方向。",
        scrollTrackpadNote: "触控板不受影响：仍保持 macOS 的自然滚动。",
        scrollActiveNow: "正在反转鼠标滚动",
        mouseNavigationActiveNow: "侧键当前已启用",
        smoothScrollName: "平滑滚动",
        smoothScrollCaption: "把鼠标滚轮的每一格变成短暂顺滑的滑动。触控板不受影响。",
        smoothScrollStepLabel: "滚动速度",
        mouseNavigationSection: "导航",
        mouseNavigationEnable: "使用侧键后退和前进",
        mouseNavigationCaption: "将鼠标的后退和前进按钮转换为 Finder、浏览器和兼容 App 的导航命令。",
        middleClickSection: "中键点按",
        middleClickEnable: "三指按下作为中键点按",
        middleClickEnableCaption: "用三根手指按下触控板，效果等同于鼠标滚轮点按：在新标签页中打开链接、关闭标签页，以及中键能做的一切。",
        middleClickDragConflict: "macOS 的三指拖移已开启，与此手势相同。请在系统设置的辅助功能、指针控制、触控板选项中将其关闭，中键点按即可使用。",
        middleClickTapPicker: "轻点也可点按",
        middleClickTapOff: "关闭",
        middleClickTapThreeFingers: "3 根手指",
        middleClickTapFourFingers: "4 根手指",
        middleClickTapCaption: "用该数量的手指轻点（无需按压）也会触发中键点按。滑动不会触发。如果 macOS 的三指轻点被指定为“查询”，请将其关闭以免两者同时触发。",
        quickToolsTab: "快捷面板",
        quickToolShortcutToggle: "全局快捷键",
        ocrName: "拷贝屏幕文字",
        ocrCaption: "选择屏幕上的一块区域，识别出的文字会被拷贝，随时可以粘贴。",
        ocrCopied: "文字已拷贝",
        ocrNoText: "未找到文字",
        colorPickerName: "颜色吸管",
        colorPickerCaption: "获取屏幕上任意像素的颜色，并以你喜欢的格式拷贝。",
        colorPickerFormatLabel: "拷贝格式",
        colorPickerBareHexToggle: "拷贝时不带 # 前缀",
        colorPickerPickNow: "拾取颜色",
        micMuteName: "静音麦克风",
        micUnmuteName: "取消静音麦克风",
        micMuteCaption: "通过点按或快捷键切断 Mac 的麦克风，对所有 App 生效。",
        micMutedHUD: "麦克风已静音",
        micUnmutedHUD: "麦克风已恢复",
        micMuteMenuBarToggle: "静音时在菜单栏显示",
        micMuteMenuBarCaption: "菜单栏中的 App 图标旁会出现一个红色的划线麦克风。",
        pastePlainName: "粘贴为纯文本",
        pastePlainCaption: "粘贴拷贝的内容时去除颜色、字体和格式。原始内容仍保留在剪贴板中。",
        launcherName: "快捷面板",
        launcherCaption: "一个汇集你最爱工具的悬浮面板，随时随地用快捷键唤出。",
        launcherOpenNow: "打开快捷面板",
        launcherEditHint: "使用调整按钮来选择、隐藏和拖动工具。",
        launcherEmptyState: "所有工具都已隐藏。使用调整按钮把它们加回来。",
        launcherAddSection: "重新添加",
        launcherKeysHint: "方向键导航，Enter 打开，1 到 9 直接打开",
        switcherSection: "App 切换器",
        switcherEnable: "使用 Vorssaint 切换器",
        switcherEnableCaption: "在 App 和窗口之间切换，包括最小化窗口和同一 App 的多个窗口。",
        switcherUsageHint: "按住快捷键进行浏览；松开即可激活窗口。Shift 或 ← 返回；W 关闭窗口；Q 退出 App；Esc 取消。",
        switcherNoWindows: "没有打开的窗口",
        switcherIconRowMode: "用大图标显示 %@",
        switcherIconRowModeCaption: "每个 App 显示一个图标，并在上方显示该 App 的窗口预览。",
        switcherSimpleMode: "简洁 App 切换器",
        switcherSimpleModeCaption: "显示 App 图标和窗口标题，不显示预览，也不会由切换器捕捉屏幕。",
        switcherShortcutHintApps: "App",
        switcherShortcutHintWindows: "窗口",
        switcherWindowShortcutCaption: "打开最前 App 的窗口切换器。App 切换器打开时，在所选 App 的窗口之间跳转。",
        switcherTakeOverSystemShortcuts: "接管 macOS 的 ⌘Tab 和 ⌘`",
        switcherTakeOverSystemShortcutsCaption: "仅在 Vorssaint 切换器运行时停用对应的 macOS App 与窗口快捷键，并保留所有正在运行的 App 入口。",
        switcherAppearanceDelay: "显示延迟",
        switcherAppearanceDelayCaption: "按住快捷键多久后显示切换器。",
        switcherMergeTabs: "每个 App 仅显示一项",
        switcherMergeTabsCaption: "将一个 App 的所有窗口合并为切换器中的一项，而不是每个窗口一项。",
        switcherWindowlessApps: "无打开窗口的 App",
        switcherWindowlessAppsCaption: "选择哪些正在运行但完全没有窗口的 App 显示在切换器中。",
        switcherWindowlessAppsOff: "不显示",
        switcherWindowlessAppsFinder: "仅访达",
        switcherWindowlessAppsAll: "全部 App",
        switcherNoOpenWindow: "无打开的窗口",
        switcherOtherDesktop: "其他桌面",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "在 Dock 中预览窗口",
        dockPreviewEnableCaption: "将指针悬停在 Dock 中已打开的 App 上查看窗口，然后点按要打开的窗口。",
        dockPreviewBackgroundOpacity: "面板背景",
        dockPreviewBackgroundOpacityCaption: "调低后可以看到更多面板后面的内容。",
        dockPreviewOpenDelay: "打开延迟",
        dockPreviewOpenDelayCaption: "指针停在图标上多久之后才打开面板。",
        dockPreviewQuitAppOnClose: "使用 × 按钮退出 App",
        dockPreviewQuitAppOnCloseCaption: "在 Dock Preview 中，× 会退出整个 App，而不只是关闭该窗口。",
        dockClickMinimize: "点按 Dock 图标最小化",
        dockClickMinimizeCaption: "点按最前面 App 的 Dock 图标可将其窗口最小化。再次点按即可恢复。",
        dockClickCycleWindows: "点按 Dock 图标切换窗口",
        dockClickCycleWindowsCaption: "点按最前面 App 的 Dock 图标可在其窗口之间轮换，类似 ⌘`。",
        dockPreviewActiveNow: "已在 Dock 中启用",
        dockPreviewDockUnavailable: "无法读取 Dock 项目。",
        dockPreviewAutohideBeta: "测试版。你可能会遇到一些错误。",
        dockPreviewOpenWindow: "打开窗口",
        dockPreviewCloseWindow: "关闭窗口",
        dockPreviewMinimizeWindow: "最小化窗口",
        dockPreviewRestoreWindow: "恢复窗口",
        dockPreviewPinPanel: "固定预览",
        dockPreviewUnpinPanel: "取消固定预览",
        dockPreviewPinned: "已固定",
        dockPreviewClosePanel: "关闭预览",
        dockPreviewPreviousWindow: "上一个窗口",
        dockPreviewNextWindow: "下一个窗口",

        cutPasteName: "剪切和粘贴",
        cutPasteEnable: "在访达中剪切和粘贴文件",
        cutPasteEnableCaption: "在访达中用 ⌘X 剪切、用 ⌘V 移动文件和文件夹。",
        cutPasteShowHUD: "显示浮动面板",
        cutPasteShowHUDCaption: "访达处于活跃状态时，显示包含已剪切文件的浮动提示。",
        cutPasteHowTitle: "使用方法",
        cutPasteStep1: "在访达中选择项目，按 ⌘X 将其剪切。",
        cutPasteStep2: "打开目标文件夹，按 ⌘V 将其移动到那里。",
        cutPasteTextNote: "在文本字段中（例如重命名时），⌘X 和 ⌘V 仍照常工作。",
        cutPasteActiveNow: "已可在访达中剪切",
        cutPasteAutomationNote: "首次使用时，macOS 会请求控制访达的权限。",
        cutReadyTitle: "已剪切",
        cutReadyHint: "在目标文件夹中粘贴以移动",
        cutCancel: "取消剪切",
        cutDoneTitle: "已移动！",
        cutMovedSingular: "已移动 1 个项目",
        cutMovedPluralFormat: "已移动 %d 个项目",
        cutSomeFailed: "部分项目无法移动",
        cutMovingTitle: "正在移动…",
        cutMovingCountFormat: "%d / %d",

        autoQuitName: "关闭时退出",
        autoQuitEnable: "App 最后一个窗口关闭时退出该 App",
        autoQuitEnableCaption: "关闭 App 的最后一个窗口也会退出该 App。",
        autoQuitActiveNow: "当前已启用",
        autoQuitHowTitle: "工作原理",
        autoQuitStep1: "关闭某个 App 的最后一个窗口（⌘W 或红色按钮）。",
        autoQuitStep2: "该 App 会自行退出。“是否存储更改？”对话框仍会出现。",
        autoQuitPredictableNote: "通常无窗口运行的 App 永远不会被退出。",
        autoQuitExceptionsTitle: "例外",
        autoQuitExceptionsCaption: "此列表中的 App 即使没有窗口也会保持打开。",
        autoQuitExceptionsEmpty: "没有例外",
        autoQuitAddApp: "添加 App…",

        uninstallerName: "卸载器",
        uninstallerEnableCaption: "在移除 App 的同时，清除它遗留的缓存、偏好设置、日志和残留文件。",
        uninstallerStep1: "将一个 App 拖到设置中，或从列表中选择一个。",
        uninstallerStep2: "查看找到的文件以及它们占用的空间。",
        uninstallerStep3: "把想移除的内容移到废纸篓。不会永久删除任何内容。",
        uninstallerMenuItem: "卸载某个 App…",
        uninstallerDropTitle: "将 App 拖到这里",
        uninstallerDropSubtitle: "或选择一个进行扫描",
        uninstallerChoose: "选择 App…",
        uninstallerPickerTitle: "选择 App",
        uninstallerPickerSearch: "搜索 App",
        uninstallerPickerEmpty: "未找到 App",
        uninstallerEmptyNote: "未经你确认，不会移除任何内容。",
        uninstallerFDANote: "授予完全磁盘访问权限可进行更彻底的扫描。",
        uninstallerFDAGrant: "授予访问权限…",
        uninstallerFDAHint: "在列表中开启 Vorssaint。如果列表中没有，点按 + 并从“应用程序”中选择 Vorssaint。访问权限须在你重新打开 App 后才会生效。",
        uninstallerFDARelaunch: "立即重新打开",
        uninstallerScanning: "正在扫描文件…",
        uninstallerRemoving: "正在移到废纸篓…",
        uninstallerFoundTitle: "已找到",
        uninstallerSelectedFormat: "已选择 %d 项，共 %d 项",
        uninstallerRemove: "移到废纸篓",
        uninstallerCancel: "取消",
        uninstallerDoneTitle: "完成！",
        uninstallerFreedFormat: "已释放 %@",
        uninstallerSomeFailed: "部分项目无法移到废纸篓。",
        uninstallerFailedNeedsFDA: "沙盒 App 的数据只有在拥有完全磁盘访问权限时才能移动，管理员密码无法代替这项权限。",
        uninstallerFailedMoreFormat: "另有 %d 项",
        uninstallerAnother: "卸载另一个",
        uninstallerCatApp: "应用程序",
        uninstallerCatSupport: "支持文件",
        uninstallerCatCaches: "缓存",
        uninstallerCatPreferences: "偏好设置",
        uninstallerCatContainers: "容器",
        uninstallerCatLogs: "日志",
        uninstallerCatState: "已存储状态",
        uninstallerCatOther: "其他",

        urlCleanerName: "清理 URL",
        urlCleanerEnable: "拷贝时自动清理 URL",
        urlCleanerEnableCaption: "链接一进剪贴板就移除其中的跟踪参数。",
        urlCleanerActiveNow: "当前已启用",
        urlCleanerManualTitle: "立即清理",
        urlCleanerInputPlaceholder: "粘贴 URL",
        urlCleanerOutputPlaceholder: "清理后的 URL 会显示在这里",
        urlCleanerCleanButton: "清理",
        urlCleanerPasteButton: "粘贴",
        urlCleanerCopyButton: "拷贝",
        urlCleanerClearButton: "清空输入框",
        urlCleanerNoURL: "请粘贴有效的 URL。",
        urlCleanerNoChange: "没有可清理的内容。",
        urlCleanerCleaned: "URL 已清理。",
        urlCleanerCopied: "已拷贝。",
        urlCleanerLocalNote: "本地处理。无网络。",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "搜索、安装和移除 formula 与 cask。",
        homebrewMissingTitle: "未找到 Homebrew",
        homebrewMissingBody: "Vorssaint 可以在终端中打开官方 Homebrew 安装器。终端会显示步骤，并在需要时请求你的密码。",
        homebrewInstallHomebrew: "安装 Homebrew",
        homebrewInstallHomebrewCaption: "终端完成后，请回到这里并点击刷新。",
        homebrewInstallHomebrewOpened: "安装器已在终端中打开。",
        homebrewShellSetupTitle: "完成终端配置",
        homebrewShellSetupBody: "Homebrew 已安装，但终端可能还找不到 brew 命令。Vorssaint 可以在终端中打开配置命令。",
        homebrewShellSetupButton: "配置终端",
        homebrewShellSetupOpened: "命令已在终端中打开。完成后请回到这里并点击刷新。",
        homebrewRefresh: "刷新",
        homebrewCheckPackages: "检查软件包",
        homebrewTrustTitle: "Tap 尚未受信任",
        homebrewTrustCaption: "Homebrew 现在会在使用第三方 tap 前请求你的确认。信任 %@ 即可继续。",
        homebrewTrustButton: "信任并继续",
        homebrewSearchPlaceholder: "搜索包",
        homebrewKeyboardHint: "空格或回车会关闭 macOS 面板。请使用搜索按钮。",
        homebrewSearchButton: "搜索",
        homebrewSearchResults: "结果",
        homebrewInstalled: "已安装",
        homebrewAll: "全部",
        homebrewFormulas: "Formula",
        homebrewCasks: "Cask",
        homebrewNoPackages: "未找到包",
        homebrewNoSelection: "选择一个已安装的包，或搜索一个新的包。",
        homebrewDetailsTitle: "包详情",
        homebrewInstall: "安装",
        homebrewUninstall: "卸载",
        homebrewUpgrade: "更新",
        homebrewUpgradeAll: "全部更新",
        homebrewUpdateHomebrew: "更新 Homebrew",
        homebrewAllPackages: "软件包",
        homebrewOpenTerminal: "打开终端",
        homebrewCancelOperation: "取消",
        homebrewClearLog: "清空日志",
        homebrewLogTitle: "日志",
        homebrewVersion: "版本",
        homebrewDescription: "类型",
        homebrewHomepage: "打开网站",
        homebrewPopularity: "热度",
        homebrewPopularityFormat: "%@ 次安装，%@ 天",
        homebrewInstalledBadge: "已安装",
        homebrewNotInstalledBadge: "未安装",
        homebrewUpdates: "更新",
        homebrewUpdateAvailableBadge: "有可用更新",
        homebrewLatestVersion: "最新",
        homebrewConfirmInstallTitle: "用 Homebrew 安装？",
        homebrewConfirmInstallBodyFormat: "Homebrew 将下载并安装“%@”。也可能安装依赖项。",
        homebrewConfirmUninstallTitle: "用 Homebrew 卸载？",
        homebrewConfirmUninstallBodyFormat: "Homebrew 将卸载“%@”。配置文件可能仍保留在系统中。",
        homebrewConfirmUpgradeTitle: "用 Homebrew 更新？",
        homebrewConfirmUpgradeBodyFormat: "Homebrew 将下载并安装“%@”的最新版本。依赖项也可能会更新。",
        homebrewConfirmUpgradeAllTitle: "用 Homebrew 全部更新？",
        homebrewConfirmUpgradeAllBody: "Homebrew 将下载并安装有可用更新的软件包的最新版本。依赖项也可能会更新。",
        homebrewConfirmUpdateHomebrewTitle: "更新 Homebrew？",
        homebrewConfirmUpdateHomebrewBody: "Homebrew 将获取最新信息，然后重新加载你的软件包。",
        homebrewTerminalFallback: "此操作需要通过终端询问管理员密码。Vorssaint 不会获取密码。",
        homebrewLoading: "正在加载…",
        homebrewSearchEmpty: "无结果",
        homebrewOperationInstallFormat: "正在安装 %@",
        homebrewOperationUninstallFormat: "正在卸载 %@",
        homebrewOperationUpgradeFormat: "正在更新 %@",
        homebrewOperationUpgradeAll: "正在更新软件包",
        homebrewOperationUpdateHomebrew: "正在更新 Homebrew",
        homebrewOperationInstalledFormat: "%@ 已安装。",
        homebrewOperationUninstalledFormat: "%@ 已卸载。",
        homebrewOperationUpgradedFormat: "%@ 已更新。",
        homebrewOperationUpgradedAll: "软件包已更新。",
        homebrewOperationUpdatedHomebrew: "Homebrew 已更新。",
        homebrewOperationFailedFormat: "无法完成 %@。",
        homebrewOperationCancelled: "操作已取消。",
        homebrewOperationPreparing: "正在准备…",
        homebrewOperationDownloading: "正在下载文件…",
        homebrewOperationInstalling: "正在安装文件…",
        homebrewOperationUninstalling: "正在移除文件…",
        homebrewOperationUpgrading: "正在更新文件…",
        homebrewOperationFinalizing: "正在完成…",
        homebrewOperationRefreshing: "正在刷新列表…",
        homebrewOperationTerminal: "请在终端中继续。",
        homebrewOperationElapsedFormat: "已用 %@",
        homebrewOperationShowDetails: "显示详情",
        homebrewOperationHideDetails: "隐藏详情",
        homebrewOperationTechnicalLog: "技术详情",
        homebrewOperationProgressUnknown: "Homebrew 尚未报告百分比。",

        mediaName: "媒体",
        mediaEnableCaption: "在本地压缩视频、转换和处理图像、制作 GIF，并从图像中提取文字。",
        mediaLocalNote: "本地。无网络。",
        mediaToolVideo: "视频",
        mediaToolGIF: "GIF",
        mediaToolImage: "图像",
        mediaToolText: "文字",
        mediaSelectFile: "选择文件",
        mediaDropHint: "将文件拖到这里，或点击选择。",
        mediaOutput: "输出",
        mediaOutputAutomatic: "自动",
        mediaChooseOutput: "目标位置",
        mediaStartVideo: "压缩视频",
        mediaStartGIF: "制作 GIF",
        mediaStartImage: "处理图像",
        mediaStartConvertPDF: "转换为 PDF",
        mediaStartText: "提取文字",
        mediaCancel: "取消",
        mediaStartTime: "开始",
        mediaEndTime: "结束",
        mediaQuality: "压缩",
        mediaCompressionLow: "低",
        mediaCompressionMedium: "中",
        mediaCompressionHigh: "高",
        mediaMaxSize: "大小",
        mediaSizingResolution: "分辨率",
        mediaSizingFileSize: "文件大小",
        mediaTargetSize: "目标大小",
        mediaTargetSizeHint: "分辨率会自动调整以不超过上限。",
        mediaErrorTargetTooSmall: "目标大小对该片段来说太小。请缩短片段或提高上限。",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "宽度",
        mediaFPS: "FPS",
        mediaKeepAudio: "保留音频",
        mediaCodec: "编码",
        mediaFormat: "格式",
        mediaStripMetadata: "移除元数据",
        mediaLoopGIF: "循环 GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "准确",
        mediaOCRFast: "快速",
        mediaLanguageCorrection: "语言校正",
        mediaTextOutputNote: "提取的文字可以拷贝并存储为 TXT。",
        mediaRunning: "处理中",
        mediaCompleted: "完成",
        mediaCancelled: "已取消。",
        mediaOpenInFinder: "显示",
        mediaCopyText: "拷贝文本",
        mediaRunAgain: "再次运行",
        mediaEmptyText: "未找到文字。",
        mediaResultSavedFormat: "已存储为 %@",
        mediaResultSizeFormat: "%@ 到 %@",
        mediaResultGrewCaption: "转换后的文件比原文件更大。",
        mediaErrorNoFile: "请先选择文件。",
        mediaErrorNoVideo: "此文件没有视频轨道。",
        mediaErrorSameOutput: "请选择不同于原文件的目标位置。",
        mediaErrorUnsupported: "macOS 不支持此格式。",

        shelfName: "暂存架",
        shelfEnable: "用于拖放文件的临时区域",
        shelfEnableCaption: "一个浮动空间，用来收集文件、图像和文本，稍后再拖到任何 App 中。",
        shelfHowTitle: "使用方法",
        shelfStep1: "用快捷键打开它，或在拖动时晃动鼠标打开。",
        shelfStep2: "把文件、图像、链接或文本拖放到上面以暂存。",
        shelfStep3: "需要时再把每个项目拖回任何 App。",
        shelfShakeToggle: "拖动时晃动鼠标打开",
        shelfShakeCaption: "按住某个项目时快速晃动指针，即可在光标附近呼出暂存架。",
        shelfDropZoneToggle: "将拖动的文件保留在菜单栏",
        shelfDropZoneCaption: "拖动文件时，暂存架会出现在菜单栏图标下方。放下的内容就保存在那里，收进一个点按即可收起或打开的按钮，暂存架清空后按钮会消失。",
        shelfDropZoneLabel: "放到这里",
        shelfCollapse: "收起",
        shelfBehaviorTitle: "使用后",
        shelfCloseAfterDrop: "拖放到其他 App 后关闭",
        shelfCloseAfterDropCaption: "目标接收项目后关闭暂存架。面板中的图钉可让它保持打开。",
        shelfRemoveAfterDrop: "拖放后移除项目",
        shelfRemoveAfterDropCaption: "其他 App 接收的项目会离开暂存架。关闭此项可保留副本。",
        shelfExclusionsTitle: "自动例外",
        shelfExclusionsEmpty: "尚未添加 App。",
        shelfExclusionsCaption: "从这些 App 开始拖移时，摇动手势和菜单栏区域不会打开。快捷键和立即打开仍可使用。",
        shelfPin: "保持打开",
        shelfUnpin: "允许使用后关闭",
        extraBrightnessName: "超亮度",
        extraBrightnessCaption: "利用显示屏的HDR余量突破最高亮度。会更耗电，Mac可能会发热。",
        extraBrightnessLevelLabel: "强度",
        extraBrightnessUnsupported: "仅适用于XDR显示屏，例如14英寸和16英寸MacBook Pro。",
        shelfHotkeyLabel: "快捷键",
        shelfOpenNow: "立即打开",
        shelfNoPermission: "无需任何权限。",
        shelfMenuItem: "打开暂存架",
        shelfTitle: "暂存架",
        shelfEmpty: "将项目拖到这里",
        shelfClearAll: "全部清除",
        shelfRemoveSelected: "移除所选",
        shelfSelectedFormat: "已选择 %d 项",
        shelfHint: "点按以选择，拖出即可使用，或右键点按查看更多操作。",
        shelfItemImage: "图像",
        shelfTooltipItemsFormat: "%d 项",
        shelfTooltipItemsFew: "%d 项",
        shelfTooltipImageSingular: "%d 张图片",
        shelfTooltipImageFew: "%d 张图片",
        shelfTooltipImagePlural: "%d 张图片",
        shelfTooltipFileSingular: "%d 个文件",
        shelfTooltipFileFew: "%d 个文件",
        shelfTooltipFilePlural: "%d 个文件",
        shelfTooltipNoteSingular: "%d 条备注",
        shelfTooltipNoteFew: "%d 条备注",
        shelfTooltipNotePlural: "%d 条备注",
        shelfTooltipLinkSingular: "%d 个链接",
        shelfTooltipLinkFew: "%d 个链接",
        shelfTooltipLinkPlural: "%d 个链接",
        shelfActionOpen: "打开",
        shelfActionOpenWith: "打开方式",
        shelfActionShare: "共享",

        breakdownMeasuring: "测量中…",

        mixerSection: "音量混音器",
        mixerEmpty: "使用音频的 App 会显示在这里",
        mixerUnavailable: "需 macOS 14.4 及更高版本",
        mixerPermissionBody: "若要调整各 App 的音量，请在“系统设置”中允许“屏幕与系统音频录制”。绝不会录制音频。",
        mixerResetTooltip: "重置为 100%",
        mixerOutputDefault: "默认",
        mixerOutputCurrent: "当前",
        mixerOutputUnavailable: "输出不可用",
        mixerOutputFallback: "在此设备恢复前使用默认输出。",
        mixerBypassedCaption: "此 App 自行管理音频。",
        mixerOutputTooltip: "选择输出",
        mixerSystemOutputTitle: "输出",
        mixerSystemOutputNoDevices: "未找到输出设备",
        mixerSystemOutputTooltip: "选择系统输出",
        mixerSystemOutputErrorFormat: "无法切换：%@",
        mixerLowerOnHeadphonesDisconnect: "耳机断开时降低音量",
        mixerLowerOnHeadphonesDisconnectCaption: "有线或蓝牙耳机断开时，自动调整输出音量。",
        mixerHeadphonesDisconnectVolume: "断开后的音量",
        preciseVolumeRollerEnable: "使用更细的音量步进",
        preciseVolumeRollerCaption: "将音量滚轮和按键转换为更小的系统音量步进。",
        preciseVolumeRollerTapFailed: "无法监听音量键。",
        soundOutputSwitcherTitle: "输出切换器",
        soundOutputSwitcherEnable: "用快捷键切换输出",
        soundOutputSwitcherCaption: "选择输出设备，然后用快捷键切到下一个可用输出。",
        soundOutputSwitcherDevices: "循环中的输出",
        soundOutputSwitcherNoAvailableSelection: "请至少选择一个可用输出。",
        mixerInputTitle: "麦克风",
        mixerInputNoDevices: "未找到麦克风",
        mixerInputUnavailable: "麦克风不可用",
        mixerInputFallback: "在此麦克风恢复前使用默认输入。",
        mixerInputTooltip: "选择麦克风",
        mixerInputErrorFormat: "无法切换：%@",
        mixerVisibleApps: "列表中的 App",
        mixerAllShown: "全部",
        mixerHiddenCountLabel: "已隐藏",
        mixerHideFromList: "从列表中隐藏",

        updatesSection: "更新",
        autoCheckToggle: "自动检查更新",
        includeBetaUpdatesToggle: "接收 Beta 测试版更新",
        includeBetaUpdatesCaption: "Beta 版本包含开发中的新功能，可能存在不稳定或未完善的情况。",
        betaBadgeLabel: "Beta",
        checkNowButton: "立即检查",
        updateChecking: "检查中…",
        updateUpToDate: "你已是最新版本。",
        updateAvailablePrefix: "有可用更新：",
        updateInstallButton: "下载并安装",
        updateDownloading: "正在下载更新…",
        updateInstalling: "正在安装并重新启动…",
        updateFailedPrefix: "无法检查：",
        updateLastChecked: "上次检查：",
        updateNotifyTitle: "Vorssaint 更新",
        updateInstallFailedBody: "更新已下载，但无法安装。请前往 GitHub 发布页面下载最新版本，并将 App 拖到当前 App 上覆盖。",
        updateNeedsApplicationsTitle: "请将 Vorssaint 移到“应用程序”文件夹",
        updateNeedsApplicationsBody: "App 正在一个无法更新的位置运行，例如磁盘映像或系统临时位置。请将 Vorssaint 拖到“应用程序”文件夹，从那里打开后再试一次。",
        menuCheckUpdates: "检查更新…",

        permissionRequired: "需要权限",
        permissionAccessibility: "辅助功能",
        permissionScreenRecording: "屏幕录制",
        permissionGranted: "已授予",
        permissionMissing: "未授予",
        permissionOpenSettings: "打开系统设置…",
        permissionRequest: "授予访问权限",
        permissionRestartNote: "授予后，macOS 可能会要求重新打开 App。",

        aboutDescription: "你的 Mac 实用工具中心。\n能源、系统监视器、滚动和窗口切换器，尽在菜单栏中。",
        versionPrefix: "版本",
        reviewIntro: "重看介绍",
        reviewHighlights: "重看新功能导览",
        viewOnGitHub: "在 GitHub 上查看",

        obContinue: "继续",
        obBack: "返回",
        obSkipStep: "跳过此步骤",
        obStart: "打开 Vorssaint",
        obStepWelcomeTitle: "欢迎使用 Vorssaint",
        obStepWelcomeBody: "一款低调的菜单栏实用工具，让日常使用 macOS 更顺手。",
        obWelcomeBullet1Title: "掌控能源",
        obWelcomeBullet1Body: "让 Mac 想唤醒多久就唤醒多久，合盖也不例外。",
        obWelcomeBullet2Title: "清晰掌握系统状态",
        obWelcomeBullet2Body: "实时查看 CPU、GPU 和电池温度、硬件占用以及内存压力。",
        obWelcomeBullet3Title: "鼠标和窗口，随你所愿",
        obWelcomeBullet3Body: "反转鼠标滚动，以及带缩略图的窗口切换器。",
        obLanguageLabel: "语言",
        obStepAccessibilityTitle: "辅助功能",
        obStepAccessibilityBody: "用于反转鼠标滚动，并让窗口切换器响应键盘操作。",
        obAccessibilityWhy: "App 只会监视鼠标滚轮和切换器快捷键。不会录制任何内容，也不会发送到任何地方。",
        obStepRecordingTitle: "屏幕录制",
        obStepRecordingBody: "让切换器显示真实的窗口缩略图，而不仅是图标。",
        obRecordingWhy: "缩略图实时生成，仅保留在内存中，绝不会离开你的 Mac。即使没有它，切换器仍可用图标工作。",
        obStepMonitorTitle: "系统监视器",
        obStepMonitorBody: "面板会显示 CPU、GPU 和电池温度、硬件占用以及内存压力。",
        obMonitorNoPermission: "无需任何权限。传感器直接从系统读取。",
        obStepOptionalTitle: "可选功能",
        obStepOptionalBody: "现在开启你想用的功能。一切都可以稍后在设置中更改。",
        obStepStatusTitle: "检查",
        obStepStatusBody: "确认你想使用的功能都已就绪。",
        obStatusRecheck: "重新检查",
        obStepDoneTitle: "全部就绪！",
        obStepDoneBody: "Vorssaint 已开始照看你的 Mac。",
        obDoneHint: "在菜单栏（屏幕右上角）寻找那个黑洞图标。",
        obWhatsNewTitle: "此版本的新功能",
        obWhatsNewFallback: "此更新包含最新的修复和改进。",
        obLanguageUpdateTitle: "现在支持你的语言",
        obLanguageUpdateBody: "Vorssaint 现在支持多种语言。选择你想使用的语言，随时可在设置中更改。",
        obPurposeTitle: "你想用它做什么？",
        obPurposeBody: "选择一套预设，或准确勾选你想使用的功能。",
        obPurposeSkip: "之后可随时在设置中添加或移除功能。",

        tabMonitor: "监视",
        monitorMenuBarSection: "在菜单栏中",
        monitorMenuBarCaption: "选择菜单栏中图标旁显示的内容。",
        monitorCombineTemperatures: "合并使用率和温度",
        monitorCombineTemperaturesCaption: "同一项目的使用率和温度都启用时，在一个区块中显示。",
        monitorSeparateMenuBarMetrics: "将指标分成独立项目",
        monitorSeparateMenuBarMetricsCaption: "将已启用的区块拆成单独的菜单栏项目，合并开启时使用率和温度仍保持在一起。",
        monitorNetworkUploadFirst: "上传显示在下载上方",
        monitorShowCPU: "CPU",
        monitorShowMemory: "内存",
        monitorShowNetwork: "网络",
        monitorShowPowerLabel: "电源",
        monitorIntervalLabel: "更新间隔",
        monitorInterval1: "1 秒",
        monitorInterval2: "2 秒",
        monitorInterval5: "5 秒",
        monitorPanelSection: "在面板中",
        panelNavigationMode: "按分区导航面板",
        panelNavigationCaption: "一次显示一个分区。选择“列表”可在连续滚动中查看全部内容。",
        panelFooterSections: "分区",
        panelFooterList: "列表",
        betaBadge: "BETA",
        betaFeatureWarning: "测试版。你可能会遇到一些错误。",

        networkSection: "网络",
        networkDownload: "下载",
        networkUpload: "上传",
        networkThisSession: "本次会话",
        networkMeasuring: "测量中…",
        networkApps: "正在使用网络的 App",
        networkAppsIdle: "当前没有 App 使用网络",

        diskSection: "磁盘",
        diskUsed: "已用",
        diskFree: "可用",
        diskAvailable: "可用",
        diskPurgeable: "可清除",
        diskInternal: "内置",
        diskExternal: "外置",
        diskSelect: "选择磁盘",
        diskRead: "读取",
        diskWrite: "写入",
        diskSMARTStatus: "状态",
        diskSMARTUnavailable: "此磁盘没有可用的 SMART",
        diskTotalRead: "总读取",
        diskTotalWritten: "总写入",
        diskTemperature: "温度",
        diskHealth: "健康度",
        diskPowerCycles: "通电次数",
        diskPowerOnHours: "通电小时",
        diskUnsafeShutdowns: "异常关机",
        diskMediaErrors: "介质错误",
        diskEject: "推出",
        diskEjectAll: "全部推出",
        diskEjecting: "正在推出…",
        diskReadyToRemove: "可以移除",
        diskEjectFailed: "无法推出",
        diskProtectionCaption: "拔出前先推出。",
        diskNoExternal: "没有可推出的外置磁盘。",
        diskOpenInFinder: "打开",
        diskStorageSettings: "存储空间",
        diskNoDisks: "未找到已挂载磁盘。",

        powerSection: "电源",
        powerSystem: "系统",
        powerAdapter: "电源适配器",
        powerBattery: "电池",
        powerCharging: "充电中",
        powerOnBattery: "使用电池",
        powerPluggedIn: "已接通电源",
        powerUnavailable: "此 Mac 上无可用电源指标",
        powerAdapterMaxFormat: "最高 %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU 温度",
        monitorShowGPUTemperature: "GPU 温度",
        monitorShowBatteryTemperature: "电池温度",
        monitorShowPeripheralBattery: "外设电池",
        peripheralBatteryNoDevices: "未找到外设",
        monitorGraphsSection: "图表",
        monitorGraphsCaption: "选择哪些指标显示随时间变化的图表。",

        updateBannerTitle: "有可用更新",
        updateBannerAction: "更新",
        obStepMenuBarTitle: "菜单栏中的指标",
        obStepMenuBarBody: "选择图标旁要显示的内容。上方预览会实时更新。",
        obStepMenuBarNote: "新增：面板中的网络和电源模块及图表。稍后可在设置 › 监视中细致调整。",
        monitorMenuBarPresetLabel: "样式",
        menuBarPresetReadable: "易读",
        menuBarPresetDense: "密集",
        menuBarSpacingLabel: "菜单栏间距",
        menuBarSpacingStandard: "标准",
        menuBarSpacingCompact: "紧凑",
        menuBarHideIconToggle: "显示指标时隐藏 App 图标",
        menuBarHideIconCaption: "当指标离开菜单栏，或有需要提示的内容（更新就绪或麦克风已静音）时，图标会自动回来。",
        monitorLabelStyleLabel: "标签",
        menuBarLabelStyleCompact: "紧凑",
        menuBarLabelStyleClassic: "经典",
        monitorMemoryStyleLabel: "内存显示方式",
        monitorMemoryPressureDot: "压力圆点",
        memoryStyleDot: "圆点",
        memoryStylePercent: "%",
        memoryStyleBoth: "两者",
        systemUptime: "已运行",
        batteryCharge: "电量",
        powerHealth: "电池健康度",
        powerCycles: "循环次数",
        speedTestRun: "测速",
        speedTestAgain: "再次测速",
        speedTestLatency: "延迟",
        speedTestTesting: "测试中…",
        speedTestFailed: "测试失败",

        monitorShowInPanel: "在面板中显示",
        disclosureExpanded: "已展开",
        disclosureCollapsed: "已折叠",
        panelHideItem: "从面板隐藏",
        panelShowItem: "在面板中显示",
        panelHiddenItem: "隐藏",
        monitorItemUptime: "运行时间",
        monitorItemNetSpeed: "实时速度",
        monitorItemNetTotals: "会话总量",
        monitorItemNetTest: "测速",
        monitorItemDiskUsage: "磁盘使用",
        monitorItemDiskActivity: "实时活动",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "外置保护",
        monitorItemDiskTools: "工具",
        monitorPanelConfigHint: "打开某个模块以选择它显示的内容。",
        monitorOrderSection: "分区顺序",
        monitorOrderHint: "拖动以重新排列面板分区，点按眼睛图标可显示或隐藏各分区。",
        obStepPanelTitle: "面板中显示的内容",
        obStepPanelBody: "打开每个模块，精确选择点按图标时显示的内容。",
        obStepPanelNavigationTitle: "分区式面板",
        obStepPanelNavigationBody: "面板现在可以一次显示一个分区。你可以在设置中切换“分区”和“列表”。",

        cleaningMenuItem: "清洁模式",
        utilitiesSection: "实用工具",
        quickControlsSection: "控制",
        panelCategoryWindows: "窗口",
        panelCategoryInput: "鼠标和键盘",
        panelCategoryFiles: "文件",
        windowMaximizeName: "最大化窗口",
        windowMaximizeCaption: "绿色按钮会最大化，不创建新的空间。",
        windowMaximizeActiveNow: "绿色按钮已启用",
        windowMaximizeNeedsAccessibility: "需要辅助功能权限才能工作。",
        keyDebounceName: "按键防抖",
        keyDebounceEnable: "过滤重复按键",
        keyDebounceCaption: "过滤过快的重复按键。",
        keyDebounceActiveNow: "过滤已启用",
        keyDebounceGlobalWindow: "全局窗口",
        keyDebouncePerKeySection: "指定按键",
        keyDebouncePerKeyCaption: "单个按键的值会覆盖全局窗口。使用 0 ms 可不再过滤该按键。",
        keyDebounceKeyLabel: "按键",
        keyDebounceWindowLabel: "窗口",
        keyDebounceAddKey: "添加按键",
        keyDebounceNoOverrides: "尚未配置指定按键。",
        keyDebounceRemoveKey: "移除按键",
        cleaningPanelCaption: "锁定键盘，便于安全清洁。",
        cleaningOverlayTitle: "键盘已锁定以便清洁",
        cleaningOverlaySubtitle: "按下 Esc 键 5 次以解锁",
        cleaningOverlayUnlock: "解锁",
        cleaningOverlayMouseHint: "你的鼠标和触控板仍可使用",
        cleaningKeepScreenVisibleToggle: "保持屏幕可见",
        cleaningKeepScreenVisibleCaption: "在屏幕角落显示小巧的指示条，而不调暗屏幕内容。",
        cleaningStartNow: "立即锁定键盘",
        cleaningNeedsAxTitle: "需要辅助功能",
        cleaningNeedsAxBody: "为安全地锁定键盘，Vorssaint 需要辅助功能权限。请在“系统设置”中授予后重试。",

        tabSupport: "支持",
        shortcutsPageCaption: "在这里编辑此 Mac 已安装功能的所有全局快捷键。未启用的快捷键仍会保存，但不会执行。",
        shortcutsPageTitle: "键盘快捷键",
        settingsSearchPlaceholder: "搜索设置",
        donateHeading: "帮助 Vorssaint 继续成长",
        donateMessage: "Vorssaint 免费、独立，由我在业余时间开发。如果你愿意提供经济支持，Buy Me a Coffee 会直接帮助我继续推进开发。",
        donateButton: "通过 Buy Me a Coffee 支持",
        donateThanks: "谢谢你的到来。🖤",
        supportIntroTitle: "帮助 Vorssaint 继续成长",
        supportIntroMessage: "如果你愿意在经济上支持开发，Buy Me a Coffee 是唯一的支持方式。",
        supportIntroStarButton: "在 GitHub 为 Vorssaint 点星",
        supportIntroStarMessage: "我们从不期待经济支持。在 GitHub 点一颗星能让更多人发现 Vorssaint，也会切实帮助它继续发展。",
        supportIntroCoffeeButton: "通过 Buy Me a Coffee 支持",
        supportIntroLaterButton: "稍后再说",
        supportIntroDoneButton: "完成",
        discordIntroTitle: "Vorssaint Discord 社区刚刚起步",
        discordIntroMessage: "Vorssaint 社区刚刚建立，还在不断完善。现在加入，认识其他用户，并一起打造一个围绕这款 App 的友好空间。",
        discordIntroJoinButton: "加入 Discord 社区",
        communityIntroTitle: "抢先看到每个新功能",
        communityIntroMessage: "已经在 X 上关注我的人，早在其他人之前就看到了这次更新中的多项变化。我会在那里发布即将推出的新功能预览并展示使用方法，让你在更新发布前就了解基本操作。关注我，提前看看接下来会有什么！",
        communityIntroFollowButton: "在 X 上关注 @vorssaint",
        homebrewOfficialIntroTitle: "现已加入 Homebrew 官方目录",
        homebrewOfficialIntroMessage: "现在可以直接从 Homebrew 官方目录安装 Vorssaint。",
        homebrewOfficialIntroInstallLabel: "全新安装",
        homebrewOfficialIntroMigrationTitle: "用过旧 tap？",
        homebrewOfficialIntroMigrationMessage: "移除一次旧 tap。App 和你的设置都会保留。",
        homebrewOfficialIntroCopyButton: "拷贝命令",
        updateShowcaseTitle: "3.1.4 新功能",
        updateShowcaseMessage: "快速预览这次更新的主要改进。",
        updateShowcaseUnavailable: "现在无法加载视频。你仍然可以继续。",
        updateShowcaseRestart: "回到开头",
        showMenuBarIcon: "显示菜单栏图标",
        showMenuBarIconCaption: "如果 Vorssaint 的图标消失了（当菜单栏空间不足时，macOS 可能会隐藏图标，这在带刘海的 Mac 上很常见），请从“应用程序”或 Spotlight 重新打开 Vorssaint：这会重建图标，如果它仍被隐藏，则会打开此窗口。",
        menuBarIconStillHiddenTitle: "图标仍然被隐藏",
        menuBarIconStillHiddenBody: "图标已重建，但 macOS 没有给它可见的位置。菜单栏可能已经没有空间：请移除一些菜单栏图标（或关闭菜单很长的 App）后再试一次。",
        menuBarIconManagerHintFormat: "%@ 正在运行，可能把图标收进了它的隐藏区域。请在那里找找 Vorssaint，或将 %@ 设置为始终显示 Vorssaint。",
        shortcutRecording: "按下新的快捷键",
        shortcutReset: "重置",
        shortcutNone: "无",
        shortcutClear: "移除快捷键",
        shortcutInvalid: "请至少搭配 Control、Option 或 Command 和一个按键。",
        shortcutPressKeys: "按下按键",
        shortcutEscapeHint: "Esc 取消。",
        shortcutDeleteHint: "Delete 清除。",
        shortcutNotCaptured: "没有捕获到任何按键。macOS 或其他 App 已在使用该组合，请换一个。",
        shortcutConflictFormat: "此快捷键已被 %@ 使用。",
        shortcutUnavailable: "macOS 拒绝了此快捷键。请选择另一个。",
        shelfShortcutToggle: "暂存架快捷键",
        switcherUsageHintFormat: "按住 %@ 进行浏览；松开即可激活窗口。Shift 或 ← 返回；W 关闭窗口；Q 退出 App；Esc 取消。",
        musicBlockSection: "媒体键",
        musicBlockTitle: "阻止音乐 App 自行打开",
        musicBlockCaption: "按下媒体键时音乐 App 不再打开。你仍可以自己打开它。",
        musicBlockReplacementLabel: "改为打开",
        musicBlockReplacementNone: "无",
        musicBlockChooseApp: "选择 App…",
        cleanerName: "清理",
        cleanerIntroTitle: "清理 Mac 垃圾",
        cleanerIntroCaption: "查找已卸载 App 的残留、缓存、日志和废纸篓。清理前可逐项确认，移除的项目会进入废纸篓。",
        cleanerScan: "扫描",
        cleanerScanning: "正在扫描…",
        cleanerCleaning: "正在清理…",
        cleanerCatLeftovers: "已卸载 App 的残留",
        cleanerCatLoginItems: "失效的登录项",
        cleanerCatCaches: "缓存",
        cleanerCatLogs: "日志",
        cleanerCatDeveloper: "开发垃圾",
        cleanerCatTrash: "废纸篓",
        cleanerLeftoversNote: "由分析找到，默认不勾选。勾选前请确认路径。",
        cleanerLoginItemsNote: "登录项里的条目在 Mac 重新启动后消失。",
        cleanerTrashNote: "清倒废纸篓是永久操作。",
        cleanerCatDeviceBackups: "iPhone 备份",
        cleanerDeviceBackupsCaption: "旧的 iPhone 和 iPad 备份占据了 macOS 所称“其他”存储的很大一部分。只删除不再需要的备份；下次连接设备时会生成新的备份。",
        cleanerNothingFound: "没有可清理的内容。Mac 很整洁。",
        cleanerClean: "清理",
        cleanerDoneNote: "项目已移到废纸篓，可以从那里恢复。",
        cleanerAgain: "再次扫描",
        cleanerRevealInFinder: "在访达中显示",
        cleanerPanelCaption: "App 残留、缓存和日志",
        cleanerSafeSection: "安全清理",
        cleanerOptionalSection: "可选，请先确认",
        cleanerCatOtherCaches: "其他缓存",
        cleanerCachesCaption: "App 会自行重建的临时文件。",
        cleanerLogsCaption: "旧的诊断日志。",
        cleanerDeveloperCaption: "Xcode 构建和模拟器残留。",
        cleanerLoginItemsCaption: "已不存在的 App 留下的登录项。",
        cleanerLeftoversCaption: "已卸载 App 留下的文件。",
        cleanerOtherCachesCaption: "可以放心删除，不会损坏任何东西。App 首次打开可能变慢，离线音乐等已下载内容会重新下载。",
        cleanerCleanSizeFormat: "清理 %@",
        cleanerScheduleTitle: "自动清理",
        cleanerScheduleOff: "关闭",
        cleanerScheduleDaily: "每天",
        cleanerScheduleWeekly: "每周",
        cleanerScheduleCaption: "在所选时间自动清理安全部分，并把所有内容移到废纸篓。",
        cleanerScheduleLastFormat: "上次自动清理释放了 %@。",
        cleanerAutoNotificationFormat: "已释放 %@ 并移到废纸篓。",
        cleanerScheduleNextFormat: "下次清理%@。",
        cleanerScheduleRanFormat: "上次自动清理%@。",
        cleanerScheduleNotifyToggle: "完成时通知",
        cleanerNotifDenied: "Vorssaint 的通知在系统中已关闭。",
        cleanerNotifOpenSettings: "打开通知设置…",
        launchAtLoginNeedsApplications: "App 正从一个无法在登录时打开的位置运行。请将 Vorssaint 拖到“应用程序”文件夹，从那里打开后再重新开启此选项。",
        launchAtLoginNeedsApproval: "登录项已注册，但系统设置里仍处于关闭状态。请打开“系统设置 › 通用 › 登录项与扩展”，在“登录时打开”中开启 Vorssaint。",
        ocrRemoveLineBreaksToggle: "移除换行",
        ocrRemoveLineBreaksCaption: "移除识别文本中的换行，使复制的内容粘贴为一个段落。",
        ocrQRToggle: "读取二维码",
        ocrQRCaption: "如果所选区域包含二维码，会显示它的内容以便拷贝或打开。",
        ocrQRCopied: "二维码已拷贝",
        qrResultTitle: "二维码",
        qrResultCopy: "拷贝",
        qrResultOpen: "打开链接",
        highlightsTitle: "本次更新亮点",
        highlightsTitleClipboardRedesign: "剪贴板全新设计",
        highlightsTitleWindowLayout: "窗口布局",
        highlightsTitleQuitProtection: "⌘Q 与 ⌘W 保护",
        highlightsTitleRecorderBlur: "屏幕录制模糊遮挡",
        highlightsCaptionDockPreview: "Dock Preview 现在可以在开启 Dock 放大时使用",
        highlightsCaptionScreenshot: "截屏工具新增了像素放大镜和二维码读取",
        highlightsCaptionSnippetLibrary: "可搜索的片段菜单把任意片段直接输入到光标处",
        highlightsCaptionCapturePalette: "单个快捷键现在可打开浮动面板，快速进行截屏、录屏、提取屏幕文字和取色，并就近调整各项设置。",
        highlightsCaptionClipboardRedesign: "剪贴板历史现在作为紧凑浮动面板打开，行布局更简洁，并提供按需预览以阅读或编辑完整内容。",
        highlightsCaptionWindowLayout: "使用快捷键和指针的方向环放置窗口，或拖动至屏幕边缘按自定义间距吸附。",
        highlightsCaptionQuitProtection: "通过长按、连按两次或额外修饰键防止误关应用与窗口，支持针对各个应用单独设置。",
        highlightsCaptionRecorderBlur: "在导出或分享录屏前，可在任意时段对密码及私密信息进行模糊遮挡。",
        highlightsConfigure: "配置",
        highlightsTry: "试一试",
        highlightsSeeAll: "查看全部更改",
        switcherCurrentSpaceOnly: "仅显示当前桌面",
        switcherCurrentSpaceOnlyCaption: "切换器中只显示你所在桌面的窗口。选择窗口不会把你带到其他桌面。",
        shelfFileMissing: "文件已不存在",
        previewSizeSmall: "小",
        mixerSoundEffectsOutputTitle: "系统声音",
        mixerSoundEffectsOutputTooltip: "选择提醒和音效的播放设备",
        monitorOpenActivityMonitor: "打开活动监视器",
        dockClickHide: "点按 Dock 图标隐藏 App",
        dockClickHideCaption: "点按当前 App 的 Dock 图标可隐藏它。再次点按即可恢复。",
        monitorMemoryMetricLabel: "内存计量方式",
        memoryMetricUsed: "已用内存",
        memoryMetricApp: "App 内存",
        keepAwakeRightClickToggle: "右键点按菜单栏图标以切换“保持唤醒”",
        keepAwakeRightClickToggleCaption: "将取代右键点按菜单。",
        urlCleanerRulesTitle: "清理规则",
        urlCleanerRulesCaption: "网站会把这些参数附加在自己的分享链接上，用来追踪链接从哪里来。勾上表示清理时把它删掉，取消勾选表示保留。自己添加的名称可以删除。",
        urlCleanerRulesCoverageCaption: "表里覆盖的是同一个站点的不同分享入口（网页、App、直播间），所以条目多；一条真实链接通常只带其中 2 到 4 个。",
        urlCleanerRulesAllSites: "全部网站",
        urlCleanerRulesCountSingular: "1 个参数",
        urlCleanerRulesCountPluralFormat: "%d 个参数",
        urlCleanerRulesAddSite: "添加网站",
        urlCleanerRulesParameterPlaceholder: "参数名称",
        urlCleanerRulesMatchCaption: "填 = 左边的名字，比如 utm_source。命中的名字只会让那一个参数从链接里消失，其余部分原样保留。",
        urlCleanerRulesAddButton: "添加",
        urlCleanerRulesRemoveButton: "删除名称",
        urlCleanerRulesRemoveSiteButton: "关闭这个网站的全部规则",
        urlCleanerRemovedFormat: "已移除 %@",
        switcherSearchPin: "按 S 固定搜索",
        switcherSearchPinCaption: "浏览时按 S 启动搜索，固定切换器；避免自定义快捷键为 ⌥ 时打出特殊字符，以及 Q/W 开头误触发关闭/退出。",
        invertVerticalScroll: "反转垂直滚动",
        invertHorizontalScroll: "反转水平滚动",
        switcherShowShortcutHints: "显示快捷键提示",
        switcherShowShortcutHintsCaption: "在图标下方显示 App 和窗口快捷键。",
        uninstallerHomebrewPackageFormat: "%@ 也会从 Homebrew 中移除。",
        shelfEdgeToggle: "靠近屏幕边缘时打开",
        shelfEdgeCaption: "将文件拖向屏幕边缘，暂存架就会探出一角。放在那里即可放下，往回拖则会收回去。",
        focusFollowsMouseName: "悬停聚焦",
        focusFollowsMouseCaption: "鼠标短暂停留后，聚焦并置前指针下方的窗口。",
        focusFollowsMouseDelay: "悬停延迟",
        switcherMinimizedPlacementLabel: "最小化的窗口",
        switcherMinimizedPlacementNormal: "正常顺序",
        switcherMinimizedPlacementEnd: "放到末尾",
        switcherMinimizedPlacementHidden: "隐藏",
        switcherShowFullscreenWindows: "显示全屏窗口",
        switcherScreenPlacementLabel: "显示在",
        switcherScreenPlacementPointer: "指针所在的屏幕",
        switcherScreenPlacementMenuBar: "菜单栏所在的屏幕",
        switcherScreenPlacementActiveWindow: "活跃窗口所在的屏幕",
        switcherScreenPlacementCaption: "连接多个屏幕时，切换器在哪个屏幕上打开。",
        smoothScrollResponseLabel: "响应",
        mouseAccelerationName: "关闭鼠标加速",
        mouseAccelerationCaption: "移除已连接鼠标的指针加速。关闭此选项或退出 Vorssaint 后，会恢复之前的设置。",
        shelfClearOnClose: "关闭时清空",
        shelfClearOnCloseCaption: "仅在点按关闭按钮时清空暂存架。自动隐藏或收起时会保留项目。"
    )
}
